### ISSUE TITLE
[Feature] A real ping command

### ISSUE THREAD

**Issue by Zenrac** [Just-Some-Bots/MusicBot#1001]
Maybe adding a ping command can be useful in order to know if there are some lagging issues.
I mean "real" cause it have to answer with a time (in ms).  Like this for example: 
![image](https://cloud.githubusercontent.com/assets/19573589/23831221/facd15ac-071c-11e7-9ad9-a18fa8e51337.png)

**Comment by jayktaylor** [comment]
The difficulty with this is that there's not really an accurate way of calculating how long it was taken for a response to be sent, without monitoring websocket events. While this is possible, it would be a bit of work just for a command like this.

**Comment by zenrac** [comment]
I don't know if it works, but i made this command.
```
    async def cmd_ping(self, channel):
        """
        Usage:
            =ping
            
        Displays the ping 
        """
        start = time.time()
        await self.safe_send_message(channel, "Pong!")        
        end = (time.time() - start)*100
        end = int(end)
        async for message in self.logs_from(channel, limit=10):
            if message.author == self.user and message.content == "Pong!":
                await self.edit_message(message, new_content="Pong! {}ms.".format(end))	
                return	
```

**Comment by Zenrac** [comment]
Well, i made this : 
```
    async def cmd_ping(self, channel):
        """
        
            =ping
            
        Displays the ping
        """
        start = time()
        msg = await self.safe_send_message(channel, "Pong!")        
        end = int((time() - start)*1000)
        return await self.edit_message(msg, "Pong! %sms" % end)	
```

**Comment by StrawberryWater** [comment]
When i use that ping command, i get this error.

Traceback (most recent call last):
  File "/root/MusicBot/musicbot/bot.py", line 1959, in on_message
    response = await handler(**handler_kwargs)
  File "/root/MusicBot/musicbot/bot.py", line 769, in cmd_ping
    start = time()
TypeError: 'module' object is not callable

**Comment by Zenrac** [comment]
Yes, it depends of your import way
`import time`
--> time.time()
`from time import *`
--> time()

**Comment by jayktaylor** [comment]
A "real" ping command won't be possible. You can make a command as described above, but it isn't really accurate.
