### ISSUE TITLE
Autoplaylist delay?

### ISSUE THREAD

**Issue by kogasaka6** [Just-Some-Bots/MusicBot#1002]
I just loaded up a new autoplaylist with about 85 songs and am planning on adding more with the days to come, the issue I'm having is looooooooong wait times/delay between songs, up to a minute downtime. Is this an internet related issue? Will it go away on its own?

**Comment by Chriscox462** [comment]
your download speeds maybe.

**Comment by jayktaylor** [comment]
This is likely related to your download speed, the bot downloads the songs and then plays them to Discord.
