### ISSUE TITLE
Kernel

### ISSUE THREAD

**Issue by Qasimmodo** [Just-Some-Bots/MusicBot#1003]
If I'm on a old kernel/OpenVZ will that make significant difference to the performance of the MusicBot, compared to being on a new kernel with KVM. My bot has been lagging on OpenVZ with multiple instances.

Thank you, and please give a explanation too. :)

**Comment by amit177** [comment]
The reason I assume it would lag is either system resources or bandwidth, monitor these.

If this is still relevant, please open a new issue.
