### ISSUE TITLE
Cant run run.py

### ISSUE THREAD

**Issue by XeroShi** [Just-Some-Bots/MusicBot#1005]
Everytime i try to run run.py it says it cant find the file.

**Comment by V-Go** [comment]
i had this issue when i tried to make a sym link start the music bot, there seems to be a dependency on the current folder to be the main music bot folder.

**Comment by LuBlaBo** [comment]
Make sure that you are exactly in the same direcory as your run.py

**Comment by XeroShi** [comment]
i don't know what run.py is.

**Comment by EndenDragon** [comment]
So you know the folder where you downloaded the bot? No? Well download the bot first. Otherwise, inside that folder is the python code to start the bot. Aka, run.py.

**Comment by jayktaylor** [comment]
Please follow the correct guide for your system here to the letter: https://github.com/Just-Some-Bots/MusicBot/wiki
