### ISSUE TITLE
Can't run runbot.bat

### ISSUE THREAD

**Issue by kyrellr** [Just-Some-Bots/MusicBot#1006]
Whenever I double click runbot.bat, it opens up the Python 3.5.1 (64bit) Setup and has me modify, repair, or uninstall Python. Not sure why this is happening, but it happens for all my BAT files. Another thing I noticed is that for others, the symbol on their bat files is a gear, while mine is the python icon.

**Comment by chuushi** [comment]
The `.bat` extension should be linked to a command prompt, not directly to Python.

Change the default program for `.bat` to `cmd.exe`, or run the file within the `cmd` (command prompt) program.
