### ISSUE TITLE
Error when login with token

### ISSUE THREAD

**Issue by paradox8599** [Just-Some-Bots/MusicBot#1009]
I have tried on Ubuntu, Fedora, Debian on VPS, and on my raspberry pi
Email and Password login works fine, but when I use token, it always comes with error:

    An error has occured:

        Problem: Bot cannot login, bad credentials.
        Solution: Fix your Email or Password or Token in the options file. Remember that each field should be on their own line.

    Unclosed client session
    client_session: <aiohttp.client.ClientSession object at 0x757581d0>

I am pretty sure that the tokens I have entered is correct
I edited file with VIM

**Comment by KingGold171** [comment]
options.ini.ini: :warning: Check for options.ini.ini
If you get a problem with "OwnerID not specified" etc, check that your config file is saved as options.ini.
By default, Windows hides file extensions, so you should check you haven't named this file options.ini.ini.
This is a common problem. If you have an options and options.ini file in your config folder, the correct one is options.

**Comment by paradox8599** [comment]
@KingGold171 
Yes I saved it as options.ini
I use Linux, not windows
and the text editor is VIM.
