### ISSUE TITLE
PyNaCl install error

### ISSUE THREAD

**Issue by mariofpalb** [Just-Some-Bots/MusicBot#1011]
When I summon the bot, the console write this: 

![5ffe02f063fc84e2c787b19a8220e98c](https://cloud.githubusercontent.com/assets/26458400/23993034/5b2c2c7e-0a3f-11e7-83e7-68c517554e80.png)

I've tried to install the pynacl libraries but then I get this error:

![4dcb0d2c1d5ee2c1a04d3427e8dd2056](https://cloud.githubusercontent.com/assets/26458400/23993110/a1c9e216-0a3f-11e7-87a7-304366447622.png)

What can I do to fix this?

**Comment by EndenDragon** [comment]
Are you running the commands as root to install pynacl? Eg: run the command with sudo

**Comment by mariofpalb** [comment]
Nothing, i'm having the same problem. By the way, im executing this with FreeBSD, not linux.

**Comment by Zenrac** [comment]
Maybe try to install py 3.5 instead of 3.6

**Comment by mariofpalb** [comment]
Im using py3.5 and im sure about that, im having problems with that ffi_type_pointer. The cffi version is 1.9 btw, because it didnt let me to install the 1.6 version

**Comment by jayktaylor** [comment]
If you're still having issues, you should probably create an issue on https://github.com/pyca/pynacl.
