### ISSUE TITLE
Error output mess

### ISSUE THREAD

**Issue by No-Death** [Just-Some-Bots/MusicBot#1015]
Why do I get all this mess from one simple Permission error? Pretty anoying if you ask me. I use PM2 on my ubuntu VPS. 

`MusikBot > [ERROR:bot] Error in play: PermissionsError: You don't have permission to use that command.    
MusikBot > Reason: You have reached your enqueued song limit (4)
MusikBot > Traceback (most recent call last):                                                             
MusikBot >   File "/home/nodeath/MusicBot/musicbot/bot.py", line 2495, in on_message
MusikBot >     response = await handler(**handler_kwargs)
MusikBot >   File "/home/nodeath/MusicBot/musicbot/bot.py", line 1256, in cmd_play
MusikBot >     "You have reached your enqueued song limit (%s)" % permissions.max_songs, expire_in=30     
MusikBot > musicbot.exceptions.PermissionsError: You have reached your enqueued song limit (4)`

All I want is a cleaner console output like:
`[PERMISSION ERROR] %user% don't have permissions to use that command. %reason%.`
Or something like that

**Comment by AutumnClove** [comment]
Logging implemented
