### ISSUE TITLE
[feature request] !rewind 30 (rewinds /ffw the track 30 seconds)

### ISSUE THREAD

**Issue by OmenLW** [Just-Some-Bots/MusicBot#1017]
It would be great to be able to rewind a song by xx seconds

!rwd 30
!rewind 30

This could also apply to fast forwarding a song

!fwd 30
!forward 30

Edit: Whoops, I didnt see the [similar request](https://github.com/Just-Some-Bots/MusicBot/issues/452) as I searched for `rewind`

**Comment by siku2** [comment]
Take a look at this #452

**Comment by jayktaylor** [comment]
As #452 is similar to this feature request, I'll be closing this one and directing responses there.
