### ISSUE TITLE
can't run bot on raspberry pi

### ISSUE THREAD

**Issue by FIERCEDINO080** [Just-Some-Bots/MusicBot#1020]
hey, so whenever i try to run the bot using python3.5 run.py command, it gives me an error:
No module named aiohttp
Attempting to install dependencies...

And then it does nothing. any help?

**Comment by Zenrac** [comment]
https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Raspbian

**Comment by FIERCEDINO080** [comment]
i did all that and im still getting the same...

**Comment by ccodykid** [comment]
Can you paste what you get when you run `pip3.5 --version`?

**Comment by Minxxe** [comment]
If you still have that issue, try replacing 3.5 with 3.6 worked for me.

**Comment by FIERCEDINO080** [comment]
yeah, guys, i found a solution don't worry. thanks for your help anyway! :D
