### ISSUE TITLE
Can't run the bot debian wheezy

### ISSUE THREAD

**Issue by mathougui** [Just-Some-Bots/MusicBot#1024]
When running the command:
    python3.5 run.py 

PS: libopus0 is installed

Here is what I have:
`
Traceback (most recent call last):
  File "run.py", line 162, in main
    from musicbot import MusicBot
  File "/home/x/MusicBot/musicbot/__init__.py", line 1, in <module>
    from .bot import MusicBot
  File "/home/x/MusicBot/musicbot/bot.py", line 38, in <module>
    load_opus_lib()
  File "/home/x/MusicBot/musicbot/opus_loader.py", line 17, in load_opus_lib
    raise RuntimeError('Could not load an opus lib. Tried %s' % (', '.join(opus_libs)))
RuntimeError: Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib`

EDIT: Fixed it by myself, installed the wrong libopus

**Comment by TBK** [comment]
Install libopus.

**Comment by JayySoar** [comment]
yeah I have the same issue, I installed it and it did not work

**Comment by TBK** [comment]
Did you install libopus0? - https://packages.debian.org/wheezy-backports/libopus0
