### ISSUE TITLE
bot wont respond to commands

### ISSUE THREAD

**Issue by LoneWolfSMC** [Just-Some-Bots/MusicBot#1025]
I have set the bot up and followed all the instructions. How do I get it to do my commands?

**Comment by siku2** [comment]
Please provide more information as to how it doesn't work.
Have you even tried yet and are you sure you followed the instructions correctly?

**Comment by ghost** [comment]
I properly installed the bot (i think). i have gotten it to join a voice channel, however, it wont respond to any of my commands sucha as `.play how to make mtn dew` or `.np`

my `CommandPrefix = .`
(edit) i figured it out! you need to bind the bot to a text channel for it to listen to and a voice channel for it to play through.

**Comment by jayktaylor** [comment]
As the OP is inactive and didn't respond to a request for more info, this issue will be closed.
