### ISSUE TITLE
Roles help 

### ISSUE THREAD

**Issue by GameCentral** [Just-Some-Bots/MusicBot#1031]
I set it up so my role had full permissions but it says I am default not Music Master

**Comment by Zenrac** [comment]
https://github.com/Just-Some-Bots/MusicBot/wiki/Configuration#permissions
https://github.com/Just-Some-Bots/MusicBot/wiki/Permissions

**Comment by GameCentral** [comment]
I have tried that but it does not give me the perms it says that i am grouped at default
