### ISSUE TITLE
[Feature Request] Allow users with "InstaSkip" to be able to vote to skip normaly?

### ISSUE THREAD

**Issue by ktzr** [Just-Some-Bots/MusicBot#1032]
Was wondering if it would be possible to add commands separating InstaSkip from a vote to skip.
This would allow those with InstaSkip permissions to still be able to vote without forcing the channel.
#### Proposed changes:
- change "skip" to always count as a vote to skip regardless, of permissions
- add "InstantSkip" to allow those with the relevant permission to force the song to skip

**Comment by jayktaylor** [comment]
Added in review
