### ISSUE TITLE
Bot randomly crashes when using !skip

### ISSUE THREAD

**Issue by JosephTico** [Just-Some-Bots/MusicBot#1036]
Have seen this happen a considerable amount of times over the last few days.

When a member uses !skip sometimes (rarely) the bot will crash and output this message:

```
Traceback (most recent call last):
  File "/home/****/discord/MusicBot/musicbot/bot.py", line 1931, in on_message
    response = await handler(**handler_kwargs)
  File "/home/****/discord/MusicBot/musicbot/bot.py", line 1431, in cmd_skip
    num_voice = sum(1 for m in voice_channel.voice_members if not (
AttributeError: 'NoneType' object has no attribute 'voice_members'
```

**Comment by jayktaylor** [comment]
Is the bot and all its dependencies up to date?

**Comment by JosephTico** [comment]
That's correct. Fully updated (master branch) and its dependencies. It's worth mentioning that this doesn't happen all the times. Usually this happens 2 or 3 times per day. Also when this happens the bot continues to listen and reply to commands, and can even be summoned, but doesn't output any sound to the voice channel.

**Comment by max-bromberg** [comment]
It looks to me like there was either no one in the voice channel when the command was run or there is a typo in your bot.py if you attempted to modify it
