### ISSUE TITLE
Configs being erased on update pull

### ISSUE THREAD

**Issue by PolyacovYury** [Just-Some-Bots/MusicBot#1039]
So basically the bot erases all data from autoplaylist.txt, whitelist.txt or blacklist.txt which makes downloading bot updates to be not simply
```git pull```
but rather annoying
```
git stash
git pull
git stash pop
```
which I actually tried to implement into the runbot.bat, but the bat file got also reverted by git stash command and the process collapsed.

All I say is that it would be nicer to create these files from the bot code directly if they are not present as they probably are necessary for it to run properly.

**Comment by jayktaylor** [comment]
https://github.com/Just-Some-Bots/MusicBot/commit/3356540df6c4ea3eb53844ae09f7ea7e70f1bf41

**Comment by PolyacovYury** [comment]
Nice New Year's present, good sir!)
