### ISSUE TITLE
[Feature Request] Set maximum time limit and Allow !volume to be used only by owner

### ISSUE THREAD

**Issue by Cryzin** [Just-Some-Bots/MusicBot#104]
Can we have an option to set a time limit on the music playing? So if we set time limit to be 5 minutes maximum and someone posts 1 hour, it cuts off at 5 mins.

Secondly, I would like an option where the !volume is primarily controlled by the owner but can be enabled for all users. Because currently any user can increase the volume to an absurd amount.

**Comment by imayhaveborkedit** [comment]
These are already implemented in review with permissions, however the max song length disallows users from adding songs above a certain length.  This doesn't work for some songs which youtube-dl doesn't have a duration field for, but I'll consider the cutoff method, since it would fix that.,

**Comment by Cryzin** [comment]
@imayhaveborkedit Forgive my ignorance, but where can I modify the !volume permission?

**Comment by imayhaveborkedit** [comment]
It's not in develop yet.  It's in review, the unstable branch.  I'll push an update to develop when I've finished ironing out the permissions system, adding config related commands, and fixing the various standing bugs.

**Comment by Cryzin** [comment]
@imayhaveborkedit Oh ok, Thank you!

**Comment by Cryzin** [comment]
Also Wiki links in the Ubuntu are broken

**Comment by Cryzin** [comment]
@imayhaveborkedit Thanks for adding this also :)
