### ISSUE TITLE
Reconnect on voice server crash

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1040]
Currently, if the voice server the bot is connected to crashes, the bot does not attempt to reconnect and must be manually restarted. The bot should periodically attempt to reconnect if it has been disconnected.

**Comment by ghost** [comment]
This happens so often that the bot is essentially unusable. It would be one thing if the bot completely stopped when the voice server crashed so a script could restart it, but there appears to be no easy way of acting on the disconnect. Please implement some sort of fix for this.

**Comment by junhui-f** [comment]
Would this help? 

**pm2**
https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Ubuntu#pm2

**Comment by ghost** [comment]
@Grift Thanks. I just set up pm2 and I'll see how it goes. It seems logical however to have something as essential to the function of the bot as automatic reconnecting built in rather than as a separate, optional dependency.

**Comment by junhui-f** [comment]
Development has stopped for awhile now, perhaps it was a feature in the pipelines?

**Comment by jayktaylor** [comment]
The library we depend on is going through a complete rewrite. It's more or less 'ready for use' which is what we've been holding out on before further developing the bot.

The rewritten version of the library has an implementation of reconnect logic that should fix these issues.

Work on MusicBot has started up again recently and changes will be published to this repo when they're ready for use. Thanks!

**Comment by ghost** [comment]
If anyone is curious, pm2 does not restart the bot in response to a voice server crash.

**Comment by jayktaylor** [comment]
Recent updates to the bot may have helped deal with this issue. See how it goes.
