### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by Adrien25251** [Just-Some-Bots/MusicBot#1041]
https://i.imgur.com/sA00qf4.png

**Comment by max-bromberg** [comment]
You used the command in the wrong context.

`!setavatar [Direct image link]`

**Comment by jayktaylor** [comment]
As noted above, you used the command wrong. However, the error you got is a bug and should have returned something friendlier to tell you that you used the command in an incorrect context. As such, I'll keep this issue open and label it as a bug.
