### ISSUE TITLE
Bot constantly downloading songs even when Music Voice channels are empty.  Not autopausing when empty.

### ISSUE THREAD

**Issue by likwidtek** [Just-Some-Bots/MusicBot#1042]
I tried this with the main branch and the review branch.  I have the music bot connected to 2 servers, bound to 2 channels, and set to autojoin 2 voice/music channels.  Basically the expected behavior is that if the bot gets started when the voice channels are empty, it will autopause on start up.  But it is not doing that.  It seems to behave if it's started or restarted while someone is in it but it's hard to tell.

The issue is happening on both the review and main branch.  Let me know if there's more info you need but here's info you may need.

Windows 2012 dedicated hardware server.  
Config options that I set:

[Credentials]
Token = redacted

[Permissions]

OwnerID = redacted

[Chat]
CommandPrefix = .

BindToChannels = 294230071160602626, 292003786053124127
AutojoinChannels = 156475180267339777, 294307929836748801

[MusicBot]
DefaultVolume = 0.5
WhiteListCheck = no
SkipsRequired = 4
SkipRatio = 0.5
SaveVideos = no
NowPlayingMentions = Yes
AutoSummon = yes
UseAutoPlaylist = yes
AutoPause = yes
DeleteMessages = no
DeleteInvoking = no
DebugMode = no

**Comment by BaiqingL** [comment]
Do you have caching enabled?

**Comment by likwidtek** [comment]
I have save videos turned off if that's what you mean.

**Comment by BaiqingL** [comment]
The only reason I could see it is that either your playlist is very large, and the bot needs to cache videos when it is being played, or that the users are querying new songs.

Side note: *Linux...*

**Comment by jayktaylor** [comment]
Recent updates to the bot may have somewhat resolved this.
