### ISSUE TITLE
Problem with music bot

### ISSUE THREAD

**Issue by YNGhost** [Just-Some-Bots/MusicBot#1043]
You don't have permission to use that command.
Reason: This command is not enabled for your group (Default).

When I join a different server in a different name, try to summon but its not working!
What can I do?

**Comment by GNUGradyn** [comment]
Did you set yourself as the owner of the bot in the config?

**Comment by max-bromberg** [comment]
When adding yourself as the owner, you need to use your user ID, not your username.

https://github.com/Just-Some-Bots/MusicBot/wiki/FAQ
