### ISSUE TITLE
Make musicbot into a systemctl service

### ISSUE THREAD

**Issue by axsddlr** [Just-Some-Bots/MusicBot#1044]
currently wont run as a service because it cant find the options.ini file

**Comment by rafaelwastaken** [comment]
I've been running my bot as a service without any problems for over 2 months. Did you setup the options.ini file before trying to run it as a service?

**Comment by axsddlr** [comment]
Yes my ini file is setup but I run the service file in system folder. Guess
I should run it in the root musicbot folder?

**Comment by Deadshroom** [comment]
Hey guys, theres no need to run it as a service, use Task Scheduler to run the program for you and it will run it as a background process. Then you don't have to do any work or deal with it.

**Comment by rafaelwastaken** [comment]
We were talking about running it as a systemctl on Linux. Task Scheduler is a Windows thing lol.

I used the systemctl method from Redbot to run my musicbot, this is my file atm
```
[Unit]
Description=Musicbot
After=multi-user.target
[Service]
WorkingDirectory=<path to bot's directory>
User=<user to run as>
Group=<user to run as>
ExecStart=/usr/bin/python3.5 <path to bot's run.py> --no-prompt
Type=idle
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

**Comment by Cilverjolt** [comment]
Hey did you ever get this working 100%? For some reason the bot only works if you run it from the location its intalled it. so you would have to cd /home/user/MusicBot/ for it to work. so you can't be in "/" area and do python3 /home/user/MusicBot/run.py it gives you that same error.

**Comment by dannymichel** [comment]
> We were talking about running it as a systemctl on Linux. Task Scheduler is a Windows thing lol.
> 
> I used the systemctl method from Redbot to run my musicbot, this is my file atm
> 
> ```
> [Unit]
> Description=Musicbot
> After=multi-user.target
> [Service]
> WorkingDirectory=<path to bot's directory>
> User=<user to run as>
> Group=<user to run as>
> ExecStart=/usr/bin/python3.5 <path to bot's run.py> --no-prompt
> Type=idle
> Restart=always
> RestartSec=10
> 
> [Install]
> WantedBy=multi-user.target
> ```

I got the service started and running, however, it starts silent. i have to ``.restart`` the bot to get it to be audible.
```
[Unit]
Description=music bot
After=multi-user.target
[Service]
WorkingDirectory=/home/bots/musicbot
User=bots
Group=bots
ExecStart=/home/bots/musicbot/run.sh
Type=idle
Restart=always
RestartSec=1
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=musicbot
[Install]
WantedBy=multi-user.target
```

**Comment by vanoc** [comment]
cat /etc/systemd/system/musicbot.service
```
[Unit]
Description=musicbot
After=network.target 

[Service]
Type=idle
User=musicbot
Group=musicbot
ExecStart=/web/musicbot/run.sh
ExecReload=/bin/kill -HUP $MAINPID
ExecStop=/bin/kill -QUIT $MAINPID
Restart=always
TimeoutSec=60

[Install]
WantedBy=multi-user.target
```

**Comment by amit177** [comment]
This will be added in the next release.
