### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by GoddessHylia13** [Just-Some-Bots/MusicBot#1045]
I have followed all the steps to setting up the bot, yet it does not join a voice chat with auto summon on, even when trying to force it to join just one channel. Another problem is that it does not answer to commands

**Comment by ghost** [comment]
i've gotten it to join a voice channel, it wont respond to any commands tho

**Comment by max-bromberg** [comment]
We need more information to resolve your problem. What OS are you trying to run it on? (Mac, Ubuntu, Windows)

(Be sure it has permission to speak in your text and voice channels)

**Comment by odddellarobbia** [comment]
Is also having the same issue.

**Comment by odddellarobbia** [comment]
Is also having the same issue.
My OS is -  Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-71-generic x86_64)
Running it as a docker image.

**Comment by GoddessHylia13** [comment]
I am running on Windows and I have resolved the problem. In the options.ini file the  AutoJoinChannel was wrote AutojoinChannels without an uppercase "j". After changing this lowercase "j" to an upper case J the problem was resolved

**Comment by odddellarobbia** [comment]
I tried changing the J to an uppercase, I still am having the same issue.

**Comment by jayktaylor** [comment]
Glad your issue was resolved @hylianlegends. If you are having issues @odddellarobbia, please make a new issue for it with any errors/console screenshots.
