### ISSUE TITLE
CMD Instantly closes after running Runbot Batchfile

### ISSUE THREAD

**Issue by Popdude125** [Just-Some-Bots/MusicBot#1049]
cant seem to figure out what is causing this issue, and previous request into this issue was closed without a resolution

**Comment by max-bromberg** [comment]
What OS are u trying to use?

**Comment by Popdude125** [comment]
Windows 10 (64)

**Comment by Popdude125** [comment]
I've posted on the discord help page, and somebody suggested I re-install Python, taking extra caution to follow every step in the guide, so I'll try that

**Comment by jayktaylor** [comment]
Deleting [these lines](https://github.com/Just-Some-Bots/MusicBot/blob/master/runbot.bat#L6-L20) in **runbot.bat** may resolve this issue.

**Comment by royalaid** [comment]
Also run the bat file from cmd (win+r then "cmd" and enter) to get the error.

**Comment by Geesmen** [comment]
Alright I reinstall everything and did run runbot.bat on cmd and delete everything on those line that you gave me @jaydenkieran but it still closes instantly after I open runbot.bat even the update_deps.bat closes once I open it. Does it have problem on my path? or what?

Edit: Okay @jaydenkieran it is about my path i fixed it and thanks for the help really appreciate you man. Keep it up. You might think no one cares about this but really thankss alot

**Comment by Looke116** [comment]
How did you added python to your path I can't seem to find it.

**Comment by royalaid** [comment]
@Looke116 are you on windows?

**Comment by Looke116** [comment]
Yes I am on windows and I did reinstaled Python and I saw that "Add to path" checkbox but runbot.bat still dosen't work but I found a way around it I tried to open run.py some thing happend and then I tried again and the bot went online.
