### ISSUE TITLE
Bot goes offline.

### ISSUE THREAD

**Issue by AltHeath** [Just-Some-Bots/MusicBot#1051]
When I run runbot.bat everything works just fine but whenever I close the CMD window, my bot stops working and goes offline after a few minutes. Is this normal? Or is there a way to make my bot run 24/7 playing music on the server even if I am away or my computer is off?

**Comment by rafaelwastaken** [comment]
The bot runs inside the CMD window. If you close the CMD window, you also kill the bot. A couple possible ways to make the bot run 24/7 would be to get a VPS, or a Raspberry Pi.

**Comment by AltHeath** [comment]
Ohh, so the bots on the other servers that I have joined all have raspberry pi or VPS on them? I thought theres some way I could get a musicbot working on my discord server even if Im on other devices

**Comment by AltHeath** [comment]
I see now, I need to rent a server itself with active bots as an alternatives for VPS or pi, anyways found my solution, thanks for the help

**Comment by jayktaylor** [comment]
For future reference we have always had this information at the bottom of the guide for Windows.

![SS](http://i.imgur.com/U62Jsjg.png)
