### ISSUE TITLE
Errors (cant get the pages from youtube)

### ISSUE THREAD

**Issue by DasilvaC** [Just-Some-Bots/MusicBot#1052]
i've got a annoying error showing up every time i do the command:        >play "Song"  *obviously the perfix is different* and then i get this error in the console ...

Could not extract information from https://www.youtube.com/watch?v=VEou0QBeHlk

`ERROR: Unable to download webpage: <urlopen error [WinError 10060] Een verbindingspoging is mislukt omdat de verbonden party niet correct heeft geantwoord na een bepaalde tijd, of de gemaakte verbinding is mislukt omdat de verbonden host niet heeft geantwoord> (caused by URLError(TimeoutError(10060, 'Een verbindingspoging is mislukt omdat de verbonden party niet correct heeft geantwoord na een bepaalde tijd, of de gemaakte verbinding is mislukt omdat de verbonden host niet heeft geantwoord', None, 10060, None),))`

**Comment by arunesh90** [comment]
It's most likely a internet issue
