### ISSUE TITLE
SoundCloud API Page Error

### ISSUE THREAD

**Issue by francescolf** [Just-Some-Bots/MusicBot#1054]
Every time I try to play a song from SoundCloud, the console gives this error:

Unable to download API page: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>)

How can I fix it?

**Comment by jayktaylor** [comment]
You need to update ytdl using our dependency update scripts:

- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal

You can also update ytdl manually using the command `sudo pip install -U youtube-dl`.
