### ISSUE TITLE
AutoPlaylist

### ISSUE THREAD

**Issue by DerekZ905** [Just-Some-Bots/MusicBot#1056]
AutoPlaylist doesnt auto play music for somereason anyone know why ?

; Play random songs when nothing is queued.
UseAutoPlaylist = yes

**Comment by jayktaylor** [comment]
Is your `autoplaylist.txt` file empty in the config folder?

**Comment by DerekZ905** [comment]
yeah its empty

**Comment by jayktaylor** [comment]
Then that would be why, adding some YouTube URLs in it ([like this](https://github.com/Just-Some-Bots/MusicBot/blob/master/config/autoplaylist.txt)) will give it songs to play automatically.
