### ISSUE TITLE
Can't use with Python 3.6

### ISSUE THREAD

**Issue by LiderKonmils** [Just-Some-Bots/MusicBot#1057]
The question is in the title. When i use it with Python 3.6, i'ts write that i don't have python 3.5.

**Comment by tilda** [comment]
I use Python 3.6 for mine and it works fine. What command are you using to launch the bot, and what OS?

**Comment by jayktaylor** [comment]
This issue was fixed in January in the review branch: https://github.com/Just-Some-Bots/MusicBot/commit/7b38765b1ebce36467d3b895bda88d9e5baf2878. Switch to the review branch using the `git checkout review` command. Alternatively, apply the changes yourself based on the commit linked.
