### ISSUE TITLE
Option to serialize the queue to a file so it can be restored if the bot crashes

### ISSUE THREAD

**Issue by Ivoz** [Just-Some-Bots/MusicBot#106]
Just having some people playing with it the bot sometimes crashes, and thereafter everything that was in the queue was lost

example of a 'crash'

```
> Traceback (most recent call last):
  File "C:\Users\Matthew\code\MusicBot-develop\musicbot\bot.py", line 433, in handle_play
    time_until = await player.playlist.estimate_time_until(position, player)
  File "C:\Users\Matthew\code\MusicBot-develop\musicbot\playlist.py", line 144, in estimate_time_until
    estimated_time += player.current_entry.duration - player.progress
AttributeError: 'NoneType' object has no attribute 'duration'
```

if the queue was written to a file it could be re-read on startup so ppl don't have to re-enter songs

**Comment by imayhaveborkedit** [comment]
It's actually on my todo list.  That bug you've posted there has already been fixed, but I will have the bot save the current playlist every time it changes.

**Comment by JanB1** [comment]
Will you continue using text files for all the stuff? Because if you want to realize the multi server stuff... :P

**Comment by tiddi2** [comment]
What is the status on this feature?

**Comment by imayhaveborkedit** [comment]
On the todo list because I have more important things to take care of.

**Comment by tiddi2** [comment]
Thanks you're awesome :+1:

**Comment by jayktaylor** [comment]
Queue serialisation has been added in `review` and will be in the next release of the MusicBot. (https://github.com/SexualRhinoceros/MusicBot/commit/07dff628c05fe3eec2985f9fb4dca4d7f44c3c18 et al.)

**Comment by jayktaylor** [comment]
Released.
