### ISSUE TITLE
Not really an Issue but a simple question

### ISSUE THREAD

**Issue by UndeadDreamz** [Just-Some-Bots/MusicBot#1060]
Been looking around ( probably missed it knowing me) to see how can I add the music and not let it show up on the chat, for example not let it show a link of the youtube video who posted it and so on. Unless it doesn't show for anyone only me?

**Comment by Technetium1** [comment]
@UndeadDreamz https://github.com/Just-Some-Bots/MusicBot/blob/master/musicbot/bot.py#L398
