### ISSUE TITLE
Some exceptions

### ISSUE THREAD

**Issue by dedicatus-545** [Just-Some-Bots/MusicBot#1063]
I have no idea how this happend nor what it could mean, it seemingly threw these at random after having being in use for a few hours (113 cached music files) and stopped playing.
I could close it with !shutdown though after waiting for some time for if it would add more or restart itself, which didn't happen.

https://pastebin.com/0dEDHg2z

It's really a nice gadget to have around and maybe this log can give you some pointers for stability or sth in development. If not, feel free to ignore it ofc~

Whatever it will be, please keep up the good work, it's appreciated a lot :)

**Comment by Zenrac** [comment]
Same

**Comment by BaiqingL** [comment]
Yeah I have gotten same error on a Linux server. What I do now is enabling a crontab that runs a script to restart the screen which contains the bot every 4 hours.

**Comment by jayktaylor** [comment]
Newer versions of the bot should handle these better.
