### ISSUE TITLE
Aria2c Integration

### ISSUE THREAD

**Issue by zQueal** [Just-Some-Bots/MusicBot#1066]
`youtube-dl` has two specific command flags which easily facilitate the usage of an external download manager. Specifically [aria2c](https://aria2.github.io/) which enables you to specify `x` number of thread parts to download at once instead of simply using 1 thread. In some situations this can increase the downloading of audio data many fold.

    youtube-dl -x --audio-format mp3 {youtube_url} --external-downloader aria2c --external-downloader-args --file-allocation=none --external-downloader-args -x6

# Breakdown

    -x
extracts audio from provided YouTube url

    --audio-format mp3 {youtube_url}
specifies we want mp3 formatted audio

    --external-downloader aria2c
specifies the external downloader we want to use

    --external-downloader-args --file-allocation=none
disables pre-allocation of file space

    --external-downloader-args -x6
we want to split the mp3 file into `6` parts and download them all simultaneously
________________________________

[Aria2c static builds](https://github.com/q3aql/aria2-static-builds).

Aria2c is ubiquitous--so it should work on just about any platform.

_________________________________

### From `downloader.py`

    def __init__(self, download_folder=None):
            self.thread_pool = ThreadPoolExecutor(max_workers=2)
                self.unsafe_ytdl = youtube_dl.YoutubeDL(ytdl_format_options)
                self.safe_ytdl = youtube_dl.YoutubeDL(ytdl_format_options)
                self.safe_ytdl.params['ignoreerrors'] = True
                self.download_folder = download_folder

It seems by default there are 2 parallel task running at once so this may not be necessary--but would still be nice to have.

**Comment by rogl4784** [comment]
Send me $113,000.
