### ISSUE TITLE
Captcha Resolving

### ISSUE THREAD

**Issue by Unkn0wnAssassin** [Just-Some-Bots/MusicBot#1067]
Hello,
When the Bot is supposed to play something from YouTube it returns following error:
`ERROR: unable to download video info webpage: HTTP Error 402: Payment Required (caused by <HTTPError 402: 'Payment Required'>)`
Research told me this means YT's anti spam protection wants me to solve a capture.
Any idea how to make this work on a vServer?

**Comment by arunesh90** [comment]
Switching ip if possible, else install a vpn on your server, connect to it and solve the captcha manually.
