### ISSUE TITLE
show song title on different discord server

### ISSUE THREAD

**Issue by jcgo16** [Just-Some-Bots/MusicBot#1069]
i only see playing music 2 of the server

something like that

hope theres a way to show it different songs on both servers

lets say i prevail scars on server 1
and 2nd is o2jam v3

any idea?

**Comment by rafaelwastaken** [comment]
I don't think this is possible, since accounts can only have one playing status at a time.

**Comment by FIERCEDINO080** [comment]
that wouldn't be possible, but you can set up a custom status by doing this: https://github.com/Just-Some-Bots/MusicBot/pull/227/files
