### ISSUE TITLE
option to let the bot delete user commands after some time?

### ISSUE THREAD

**Issue by CuddleBear92** [Just-Some-Bots/MusicBot#107]
would be great to have an option to let the bot delete user commands after some time like the bot does for itself.
commands like !skip, !queue, !volume and so on. bonus if this could be an option in the settings file to let the user choose what to get removed or not. 

right now the bot does remove some things, but not everything. i think this should atleast be an option for the bot tho. ofc the bot needs to have rights to remove such things tho, which shouldnt be an issue.

**Comment by imayhaveborkedit** [comment]
In the release after this next one, i'm going to have a responses file which holds all the responses for things the bot says, message deletion timers, and a delete invoking command option.

**Comment by Cryzin** [comment]
@imayhaveborkedit I think he meant the bot deleting user commands. Like if I say !skip it deletes it after the vote is done.

**Comment by imayhaveborkedit** [comment]
The skip message is a special case, i'll have to take care of that specifically, but I know what he wants and it's been on the todo list.

**Comment by mephasor** [comment]
delete_message after it was handled should take care of this: 
http://discordpy.readthedocs.org/en/latest/api.html#discord.Client.delete_message

the bot requires the "manage messages" permission for this though
