### ISSUE TITLE
Bot breaks after trying to play live station

### ISSUE THREAD

**Issue by ThePhantomZwei** [Just-Some-Bots/MusicBot#1070]
live stations on youtube, such as this https://www.youtube.com/watch?v=OpIQNxiKJoE

bot works fine before it, but works fine after clear and reset, but bot will not play this, or anything entered after this.

**Comment by EggplantSama** [comment]
I also have this problem. Hopefully it's fixable, because I'd really like to have a constant streamed LoFi station in my discord server

**Comment by TBK** [comment]
I used the URL you posted with the review branch and used the !stream command.

It works just as expected :)

**Comment by ThePhantomZwei** [comment]
i actually posted this in place of a friend who is actually using the bot, as hes kind of tech-illiterate. is the review branch seperate from the normal version? any chance you can link the specific one you downloaded to test with?

**Comment by EggplantSama** [comment]
What is the review branch and how do I get it?

**Comment by junhui-f** [comment]
https://github.com/Just-Some-Bots/MusicBot/tree/review

**Comment by EggplantSama** [comment]
what's the difference between the three branches?

**Comment by TBK** [comment]
Branches are different stages of development.

https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging
