### ISSUE TITLE
Signature Extraction Failed

### ISSUE THREAD

**Issue by rockcabbage** [Just-Some-Bots/MusicBot#1072]
```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))
```

**Comment by randomentity93** [comment]
I am getting the same issue, even after a fresh install. Had an autoplaylist contain 600+ links and is now down to 300 because the bot is automatically removing unplayable songs.

**Comment by protella** [comment]
Also getting this as of a few min ago.

**Comment by ArtificialSloth** [comment]
As of a few minutes ago, I am also getting this error. At first, I thought it was a problem with having an older version of youtube-dl but even after updating, nothing.

**Comment by rafaelwastaken** [comment]
I've also been getting this a lot today. It'a problem with youtube-dl(YouTube probably changed something again). Your gonna have to wait for youtube-dl to update to fix this.

**Comment by randomentity93** [comment]
Link to the issue in youtube-dl hub.

https://github.com/rg3/youtube-dl/issues/12885

**Comment by ConsoleQAQ** [comment]
Any idea how to update youtube-dl?

**Comment by rafaelwastaken** [comment]
You gotta wait for the youtube-dl devs to update it first.

Someone posted a manual fix in the issue listed above, so feel free to try that in the meantime.

**Comment by jayktaylor** [comment]
Beyond our control. https://github.com/rg3/youtube-dl/issues/12885

**Comment by hadronp** [comment]
For Docker based MusicBots I was able to apply a fix courtesy of user @yan12125 https://github.com/rg3/youtube-dl/issues/12885

Edit the Dockerfile as follows:
```
FROM ubuntu:trusty

MAINTAINER Sidesplitter, https://github.com/SexualRhinoceros/MusicBot

#Install `dependencies`
RUN sudo apt-get update \
    && sudo apt-get install git -y \
    && sudo apt-get install software-properties-common -y \
    && sudo add-apt-repository ppa:fkrull/deadsnakes -y \
    && sudo add-apt-repository ppa:mc3man/trusty-media -y \
    && sudo apt-get update -y \
    && sudo apt-get install build-essential unzip -y \
    && sudo apt-get install python3.5 python3.5-dev -y \
    && sudo apt-get install ffmpeg -y \
    && sudo apt-get install libopus-dev -y \
    && sudo apt-get install libffi-dev -y

#Install Pip
RUN sudo apt-get install wget \
    && wget https://bootstrap.pypa.io/get-pip.py \
    && sudo python3.5 get-pip.py

#Add musicBot
ADD . /musicBot
WORKDIR /musicBot

#Install PIP dependencies
RUN sudo pip install -r requirements.txt \
    && pip install --upgrade git+https://github.com/rg3/youtube-dl

#Add volume for configuration
VOLUME /musicBot/config

CMD python3.5 run.py
```
--then invoke the following on the CLI--

```
docker build -t MusicBotFix .
docker run -d -v $(pwd)/config:/musicBot/config MusicBotFix
```
Hope this helps.

**Comment by TomLongAshfords** [comment]
As a  slightly simpler workaround than the above, until an update is rolled out you can edit a regex in the  Youtube extractor element of youtube_dl (\site-packages\youtube_dl\extractor\youtube.py) .

Replace the existing regex with:
`r'.*?-(?P<id>[a-zA-Z0-9_-]+)(?:/[a-z]{2}_[A-Z]{2})?(?:/watch_as3|/html5player(?:-new)?|/base)?\.(?P<ext>[a-z]+)$'`

Fix courtesy of @amoschu in [this thread](https://github.com/rg3/youtube-dl/issues/12885).

**Comment by jaydenkieran** [comment]
youtube-dl has issued a fix for the above issue but hasn't pushed to official release channels yet. For now, you can fix it by using the following command on your command prompt/terminal: `python -m pip install --upgrade git+https://github.com/rg3/youtube-dl`
(Replace 'python' with the correct alias you use. This command probably won't work if you didn't install the bot properly through git, as the guides on our wiki instruct you to.)

I'm going to keep this issue open for a small while for visibility, but lock to collabs to prevent confusion. If anyone has further issues after performing this update, contact us at https://discord.gg/bots or by creating a new issue.

**Comment by jayktaylor** [comment]
An official release has been pushed. You need to update ytdl using our dependency update scripts:

- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal

You can also update ytdl manually using the command `sudo pip install -U youtube-dl`.
