### ISSUE TITLE
My Runbot.bat Closes as soon as I open it.

### ISSUE THREAD

**Issue by Geesmen** [Just-Some-Bots/MusicBot#1074]
My Runbot.bat Closes as soon as I open it and it doesn't make the option.ini for me to edit for my music bot, that's my first problem. Hopfully somebody help me with this first!

here's my runbot.bat

@ECHO off

CHCP 65001 > NUL
CD /d "%~dp0"

SETLOCAL ENABLEEXTENSIONS
SET KEY_NAME="HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"
SET VALUE_NAME=HideFileExt

FOR /F "usebackq tokens=1-3" %%A IN (`REG QUERY %KEY_NAME% /v %VALUE_NAME% 2^>nul`) DO (
    SET ValueName=%%A
    SET ValueType=%%B
    SET ValueValue=%%C
)

IF x%ValueValue:0x0=%==x%ValueValue% (
    ECHO Unhiding file extensions...
    START CMD /c REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v HideFileExt /t REG_DWORD /d 0 /f
)
ENDLOCAL

IF EXIST %SYSTEMROOT%\py.exe (
    CMD /k py.exe -3.5 run.py
    EXIT
)

python --version > NUL 2>&1
IF %ERRORLEVEL% NEQ 0 GOTO nopython

CMD /k python run.py
GOTO end

:nopython
ECHO ERROR: Python has either not been installed or not added to your PATH.

:end
PAUSE

-------------------------------------------------------------------------------------------------
       I reinstall everything because my second problem is this ERROR: Signature extraction failed: Traceback (most recent call last) which i know has something to do with Youtube_dl but my youtube_dl is updated my comp said. If anyone can help me with the new Youtube-dl please please make it step by step

here's cmd said: 

(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Asus>pip install --upgrade youtube_dl
Requirement already up-to-date: youtube_dl in c:\users\asus\appdata\local\programs\python\python35\lib\site-packages

C:\Users\Asus>

I hope anyone can help me with this because i really like my own Musicbot It was working fine 
before then it just stop working on me Please help and I'd Appreciate it alot if anyone can explain to me
this thanks alot in advance

**Comment by jayktaylor** [comment]
#1049 for your first issue. #1072 for your second one.
