### ISSUE TITLE
Trouble with $play and $search

### ISSUE THREAD

**Issue by coldarchie** [Just-Some-Bots/MusicBot#1075]
When I send  `$search NCS`  or  `$play will.i.am - scream`  bot gives me an error:
`[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))`

Why's this happening?
P.S. I doesn't edited any files except config.txt and permissions.txt in config

**Comment by Mohammed-Ali45** [comment]
Me and my friend have the same problem with the same error message, however it will only play some songs that neither of us listen to and I don't want to turn on autoplaylist either. someone pls help because the bot was a breakthrough for boring gaming.

**Comment by GrayAntagonist** [comment]
I'm having the same problem right now.

**Comment by TomLongAshfords** [comment]
Run [update_deps](https://github.com/Just-Some-Bots/MusicBot/issues/1072#event-1061982903); a problem emerged with youtube_dl today which has been patched.

**Comment by Aequil** [comment]
same

**Comment by coldarchie** [comment]
Thank you, @DukeMcAwesome! Now I solved my issue :)

**Comment by jayktaylor** [comment]
Please search for previous issues in future. https://github.com/Just-Some-Bots/MusicBot/issues/1072#event-1061982903
