### ISSUE TITLE
Bot used to work fine, but now it chooses to not work on certain songs

### ISSUE THREAD

**Issue by RavMango** [Just-Some-Bots/MusicBot#1077]
![image](https://cloud.githubusercontent.com/assets/28155558/25538157/345257ae-2c4a-11e7-9907-9b246079571d.png)

**Comment by TomLongAshfords** [comment]
Run [update_deps.bat](https://github.com/Just-Some-Bots/MusicBot/issues/1072#event-1061982903). Youtube changed something so Youtube_dl needs a small patch to work.

https://github.com/Just-Some-Bots/MusicBot/issues/1072#event-1061982903

**Comment by jayktaylor** [comment]
Please read through previous issues before making new ones.
