### ISSUE TITLE
Bot crashing when downloading music

### ISSUE THREAD

**Issue by WernerderChamp** [Just-Some-Bots/MusicBot#1078]
Every time I want to play something, I get exactly this error. It plays no role if I enter URL directly, use search function, or type play and search term 

`ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1070, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 958, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))`

It had worked before, but I haven't used the bot for a while now.

**Comment by FIERCEDINO080** [comment]
it happened to me a few hours ago. run update_deps.bat and wait for youtube_dl to complete updating. close the window and restart the bot. there. fixed.

**Comment by jayktaylor** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/1072#event-1061982903. Search through previous issues next time.
