### ISSUE TITLE
Bot Console Error (Signature extraction failed)

### ISSUE THREAD

**Issue by NATroutter** [Just-Some-Bots/MusicBot#1079]
Can someone help me with this error
sometimes when someone request song bot console gives this error

[Command] 267071239581990915/Migsu (!play https://www.youtube.com/watch?v=2ZozbFkcqjo)
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))
<class 'musicbot.exceptions.CommandError'>: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))

and bot skip that song and try to play next song from autoplaylist sometimes it's plays sometimes not
and bot types this to discord server chat -> [http://prnt.sc/f1z3j9](http://prnt.sc/f1z3j9)

**Comment by FIERCEDINO080** [comment]
happened to me a few hours ago. run update_deps.bat and wait for youtube_dl to complete updating. close the window and restart the bot. there. fixed.

**Comment by jayktaylor** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/1072#event-1061982903. Search through previous issues next time.
