### ISSUE TITLE
the bot is broken

### ISSUE THREAD

**Issue by chimkoe** [Just-Some-Bots/MusicBot#1080]
So my bot has been fine, but then something started to happen to the bots and it's been happening to a lot of other people's bots as well (even my friend's bot).
When i request a song, it crashes and says:
"ERROR: Signature extraction failed: Traceback (most recent call last): File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1070, in _decrypt_signature video_id, player_url, s File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 958, in _extract_signature_function raise ExtractorError('Cannot identify player %r' % player_url) youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js' (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))"
I even tried to remake my bot a lot of times, but the same exact thing comes up.

Is there a solution for this?

**Comment by FIERCEDINO080** [comment]
yep. happened to me a few hours ago. run update_deps.bat and wait for youtube_dl to complete updating. close the window and restart the bot. there. fixed.

**Comment by jayktaylor** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/1072#event-1061982903. Search through previous issues next time.
