### ISSUE TITLE
MusicBot produces error after trying to play music

### ISSUE THREAD

**Issue by JuppyPi** [Just-Some-Bots/MusicBot#1082]
I run this music bot on a Raspberry Pi and it was working fine. Now after queueing certain songs it produces the following error: 
[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))

This leads me to believe its opening the java script of certain songs youtube page. I don't know why it does this with some requests and not others but its really annoying. Its out of my limited knowledge on stuff like this to fix it. If you need any other info just ask for it.

**Comment by jayktaylor** [comment]
#1072
