### ISSUE TITLE
I cant open the Bot

### ISSUE THREAD

**Issue by Lokzii** [Just-Some-Bots/MusicBot#1083]
For some reason when I try to pen the bot "runbot.bat" or try to update "update_deps.bat" I always get this messenge 
![cmd_2017-04-28_21-45-24](https://cloud.githubusercontent.com/assets/28170668/25551578/2f36cc38-2c5d-11e7-955c-8725d8af0ce1.png) 
I'm always opening as admin and I tried re download the bot and still the same problem.

**Comment by BaiqingL** [comment]
You would need to uninstall youtube-dl and reinstall that. Do you know how to use pip?

**Comment by Lokzii** [comment]
No sorry, how do I do that ?

**Comment by TBK** [comment]
Run the following command in the musicbot directory:
`pip3 install -U -r requirements.txt`

Did not see that you are on Windows, in that case just run  `update_deps.bat`

**Comment by jayktaylor** [comment]
You can try running `pip install -U --force-reinstall -r requirements.txt` in your musicbot folder and see if that resolves your issue. On Windows, you can open `lazy_cmd.bat` in that folder to open a command prompt there. Alternatively, if you installed the bot properly using Git Bash, shift-right click the folder and choose `Git Bash Here` to open a command prompt.

**Comment by Lokzii** [comment]
thanks all, I tried those codes but no luck, I probably did something wrong, all I needed to do was reinstall Python and its working again.
