### ISSUE TITLE
Signature Extraction Failed

### ISSUE THREAD

**Issue by sethf99** [Just-Some-Bots/MusicBot#1086]
Hey, using most recent main branch version, getting this error whenever !play ing any song. 

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1070, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\USER\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 958, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))

Tried this on multiple songs, keeps breaking. Weird part is, some songs work while others don't.

Eg. https://www.youtube.com/watch?v=LlU4FuIJT2k does not work and results in the above error

however https://www.youtube.com/watch?v=NWWeQlXfSa0 does work.

**Comment by iDragonforce** [comment]
Hi, I got the exactly same problem with the review branch on Ubuntu 16.10

**Comment by agentklaas** [comment]
We fixed that issue by replacing the "...\youtube_dl" directory with the updated version from this program:
https://pypi.python.org/pypi/youtube_dl
You may also have to restart the bot after.
(This is probably not the proper way to do this but in our case that didn't matter.)

**Comment by arunesh90** [comment]
An official release has been pushed. You need to update ytdl using our dependency update scripts:

- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal

You can also update ytdl manually using the command `sudo pip install -U youtube-dl`.
