### ISSUE TITLE
"Now playing" message not deleted after song ends

### ISSUE THREAD

**Issue by Webberjo** [Just-Some-Bots/MusicBot#1090]
With `DeleteMessages` and `DeleteInvoking` both set to "yes", and permissions granted for the bot to manage the text channel's messages, the "Now playing" message is not deleted when the song ends. Instead, it is deleted when a new song is queued and starts playing.

**Comment by Soitora** [comment]
Same, this frequently happens to me too

**Comment by zenrac** [comment]
Try to add in on_player_play the following code:
                    async for message in self.logs_from(channel, limit=30): #limit can be changed
                        if 'Now playing' in message.content and message.author == self.user:
                            try:
                                await self.safe_delete_message(message)
                            except:
                                pass

**Comment by Webberjo** [comment]
I think you misunderstood the problem, zenrac. It's not that the "Now playing" message isn't being deleted at all, but only after the last song is finished playing. A proper solution I'd think would be to delete the "Now playing" message when the song ends, not when a new one starts playing.

**Comment by zenrac** [comment]
Yes mb, add if to on_finished_playing

**Comment by Webberjo** [comment]
The `channel` variable is created from the `entry` parameter which is not available in `on_player_finished_playing`.

**Comment by zenrac** [comment]
I didn't find better. 
add in **on_player_play**:
`        duration = player.current_entry.duration
`
**and change this:**
`            if self.server_specific_data[channel.server]['last_np_msg']:
                self.server_specific_data[channel.server]['last_np_msg'] = await self.safe_edit_message(last_np_msg, newmsg, send_if_fail=True)
                await asyncio.sleep(duration)
                try:
                    await self.safe_delete_message(message)
                except:
                    pass
            else:
                message = self.server_specific_data[channel.server]['last_np_msg'] = await self.safe_send_message(channel, newmsg)
                await asyncio.sleep(duration)
                try:
                    await self.safe_delete_message(message)
                except:
                    pass`

**in cmd_skip**:
`                    async for message in self.logs_from(channel, limit=30): #limit can be changed
                        if 'Now playing' in message.content and message.author == self.user:
                            try:
                                await self.safe_delete_message(message)
                            except:
                                pass`

It will spam a few in the console, if you don't want it, just remove the following line
**in safe_edit_message**:
                self.safe_print("Warning: Cannot edit message \"%s\", message not found" % message.clean_content)

Hope it will help you.

**Comment by Webberjo** [comment]
I added `entry` as a parameter for `on_player_finished_playing` then moved the code snippet from `on_player_play` that removes the "Now playing" message to `on_player_finished_playing` on a whim, and it actually works.

```
    async def on_player_play(self, player, entry):
        await self.update_now_playing(entry)
        player.skip_state.reset()

        channel = entry.meta.get('channel', None)
        author = entry.meta.get('author', None)

        if channel and author:
            if self.config.now_playing_mentions:
                newmsg = '%s - your song **%s** is now playing in %s!' % (
                    entry.meta['author'].mention, entry.title, player.voice_client.channel.name)
            else:
                newmsg = 'Now playing in %s: **%s**' % (
                    player.voice_client.channel.name, entry.title)
    ...
```

```
    async def on_player_finished_playing(self, player, entry, **_):
        channel = entry.meta.get('channel', None)
        author = entry.meta.get('author', None)

        if channel and author:
            last_np_msg = self.server_specific_data[channel.server]['last_np_msg']
            if last_np_msg and last_np_msg.channel == channel:

                async for lmsg in self.logs_from(channel, limit=1):
                    if lmsg != last_np_msg and last_np_msg:
                        await self.safe_delete_message(last_np_msg)
                        self.server_specific_data[channel.server]['last_np_msg'] = None
                    break  # This is probably redundant
    ...
```
