### ISSUE TITLE
!play requesting songs not working

### ISSUE THREAD

**Issue by VorstrifeEdits** [Just-Some-Bots/MusicBot#1091]
This is an error I get when I try to play a song with text or url.

> ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Secondary\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Secondary\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))

**Comment by hqjoker** [comment]
This seems to only affect youtube URLs for me. I have only tried soundcloud as well and that still works.

**Comment by hqjoker** [comment]
@VorstrifeEdits Ok so I downloaded the most recent version of youtube-dl (28.04.17) found [here](http://yt-dl.org/l)

Replaced youtube-dl folder at _C:\Users\\*name*\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl_ with the new version. Restarted bot and everything worked perfectly.

Btw I'm not familiar with github so if this needs to be forwarded elsewhere then by all means do so :)

Hope this works/helps others

**Comment by VorstrifeEdits** [comment]
@hqjoker Thank you! Everything works just fine now!

**Comment by jayktaylor** [comment]
@hqjoker That's a really bad way of doing it. You've pretty much bypassed how the bot and the dependencies were initially installed. This is the correct procedure:

- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal

You can also update ytdl manually using the command `sudo pip install -U youtube-dl`.

Doing what you did means that the version that `pip` (Python's package manager) has listed is incorrect. `pip` thinks that your youtube-dl version is actually an earlier version, and thus causes inconsistencies. **Always** use `pip` to upgrade or change any dependencies (those in the `site-packages` folder). It isn't difficult, and most of the time it's as easy as `pip install -U <package_name>`.

**Comment by hqjoker** [comment]
@jaydenkieran I have no idea about all of this stuff so of course I wouldnt know any other way.

**Comment by Dengara421** [comment]
I'm trying to update the file, but I have no idea what im doing. I have windows, with python installed. I've tried that sudo pip command but it just says syntaxerror. Any help would be appreciated.

**Comment by jayktaylor** [comment]
@Dengara421 On Windows, open `update_deps.bat` in the MusicBot's folder.

**Comment by Dengara421** [comment]
@jaydenkieran Oh.. that was really easy.. Thank you so much. I feel silly now.
