### ISSUE TITLE
Bot isnt starting up

### ISSUE THREAD

**Issue by Jan3ka** [Just-Some-Bots/MusicBot#1093]
The bot stopped working from one day to the other, I reinstalled it completely including git and python through all the links given and the bot doesnt go online on the server and I have no clue why.

**Comment by Jan3ka** [comment]
http://prntscr.com/f2kl2f

**Comment by Tawmmm** [comment]
Looks like an issue with your permissions.ini file, check around line 20 for any issues. Post it if you want me to take a look.

**Comment by Jan3ka** [comment]
Line 20 is whitelisted commands , play queue and skip. What of those might be causing trouble
