### ISSUE TITLE
permissions.ini not working

### ISSUE THREAD

**Issue by Jan3ka** [Just-Some-Bots/MusicBot#1096]
If I have something as toggled on permissions.ini (on another words if I remove the semmicolon before any of the values: for example maxsongs, so I can set the max ammount of them) the bot wont connect to the server and will display this error http://prnt.sc/f2kl2f

**Comment by Jan3ka** [comment]
Update: There is no bot command working at the moment. I cant change the song I cant do help I cant do nothing

**Comment by Zenrac** [comment]
Please post your permissions.ini
