### ISSUE TITLE
Youtube Extraction Error

### ISSUE THREAD

**Issue by shinney123** [Just-Some-Bots/MusicBot#1097]
It does this error for almost every song in the autoplaylist. It also does this when I try to load in a playlist from youtube and the individual videos that don't work. I even re-downloaded the bot. They were working till a few days ago.
https://pastebin.com/NW5609Zk

**Comment by eduardog3000** [comment]
It's a youtube-dl error, update youtube-dl:

```
# Ubuntu 14.04(.*) LTS
python3.5 -m pip install -U -r requirements.txt

# Ubuntu 16.04 LTS or higher
python3 -m pip install -U -r requirements.txt
```

**Comment by jayktaylor** [comment]
You need to update ytdl using our dependency update scripts:

- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal

You can also update ytdl manually using the command `sudo pip install -U youtube-dl`.
