### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by FilipAgert** [Just-Some-Bots/MusicBot#1100]
When trying to play specific songs, such as but not limited to instant crush by daft punk.

This error comes up:
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\$user$\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\$user$\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))

any help is welcome

**Comment by Surematus** [comment]
I've been getting this error too recently. Both when using the 'Play' option and the 'Search' option.
![error1](https://cloud.githubusercontent.com/assets/28274369/25595115/994b5da6-2e91-11e7-9a27-8a7d115ada3f.PNG)
![error2](https://cloud.githubusercontent.com/assets/28274369/25595118/9b3acac0-2e91-11e7-9723-d82f0f53acfe.PNG)

**Comment by hotspot1234** [comment]
same

**Comment by arunesh90** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/1072#issuecomment-297976717
@hotspot1234 @Surematus @file321
