### ISSUE TITLE
I'm recieving a discord music bot error

### ISSUE THREAD

**Issue by SoginoBro** [Just-Some-Bots/MusicBot#1101]
I've been trying to do update_deps, but it just won't run and just instantly closes. Also I have been receiving this error when trying to !play (music).

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Sean\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1070, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Sean\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 958, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))

**Comment by Tichael** [comment]
I just got this error. I updated the dependencies using the update_deps.bat file and it works now

**Comment by arunesh90** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/1072#issuecomment-297976717

**Comment by SoginoBro** [comment]
Thank you so much, this helped a lot.
