### ISSUE TITLE
Bot Is offline and run.bot says Owner ID not there, but Ive had the owner id there

### ISSUE THREAD

**Issue by LuckyZZZZZ** [Just-Some-Bots/MusicBot#1108]
when i open run.bot it says my owner id isnt there but when i open the config and then options, its there

**Comment by LuckyZZZZZ** [comment]
Nvm

**Comment by LuckyZZZZZ** [comment]
Fixed it

**Comment by TBK** [comment]
@LuckyZZZZZ then please close the issue.
