### ISSUE TITLE
MusicBot Stuttering

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1109]
Ok so I havent checked for packet loss just yet, however, server performance cannot be the issue. I can get the bot working just fine but every song comes in laggy. I have tried the bot on my home computer and my $130 /month dedicated server. The server is i7 7700k 4.2ghz, 64GB DDR4 and 256GB SSD with 1GBPS port and my ping to the server is <20 ms. Any clue how I should proceed to diagnose this issue? Thank you for your time.

**Comment by ghost** [comment]
Note: I searched google endlessly for a fix for this but all of the replies just say: Oh you have bad connection, oh you have bad cpu/ram whichbis not helpful. The only thing I can think of is possibly lag to the discord server itself? My region is NYC area.

**Comment by lilchancep** [comment]
Have you tried changing the location of the discord server itself?

**Comment by randomentity93** [comment]
@dz9c92 Try setting the process priority of the music bot to Realtime. This should allocate more CPU time to the musicbot and reduce stuttering.

**Comment by chuushi** [comment]
Someone apparently fixed the problem by [reinstalling Python and Git using the guide in Wiki (#661)](https://github.com/Just-Some-Bots/MusicBot/issues/661#issuecomment-252790255).

**Comment by ghost** [comment]
@SimonOrJ Yes! This was the fix. Thank you all for your replies! Have a blessed day!
