### ISSUE TITLE
other sources of the same song?

### ISSUE THREAD

**Issue by CuddleBear92** [Just-Some-Bots/MusicBot#111]
would it be possible to issue searches for the song playing on other services than it was found? 
say if you want an iTunes link or pro.beatport.com link for higher quality and so on?

i mean it have to parse the name of the link and search of such services with multible searches before it finds the right one tho.... 
maybe too hard to do flawless or close to it. 

right now we do use the bot alot to share songs we might use in our projects like AMV, HMV and FH videos. would just be great to have it being able to search multible lossless sites for us to either buy it and so on.

**Comment by imayhaveborkedit** [comment]
This is beyond the scope of the bot.
