### ISSUE TITLE
lazy.cmd problems

### ISSUE THREAD

**Issue by MaximusMeridiousDecimus** [Just-Some-Bots/MusicBot#1110]
In my MusicBot's lazy.cmd file I am trying to input the command "pip install --trusted-host pypi.python.org -r requirements.txt" and it say's "'pip' is not recognized as internal or external command.

**http://imgur.com/a/wbChk**

**Comment by chuushi** [comment]
`pip` is not added to your `PATH` environment.  The error you received is a generic error message for when the command does not exist.

Why not just run the `update_deps.bat` file?

**Comment by jayktaylor** [comment]
This is a Python related issue and as such we won't help you much with it. `lazy_cmd.bat` is used for when we provide help on our server (discord.gg/bots) and need you to enter custom commands for debugging. Your issue probably stems from installing Python wrong.

Please follow the installation guides for your system correctly: https://github.com/Just-Some-Bots/MusicBot/wiki
