### ISSUE TITLE
!play Problems

### ISSUE THREAD

**Issue by Dani064g** [Just-Some-Bots/MusicBot#1111]
For some reason i cant use the bot. Do anyone have a fix?

https://gyazo.com/7b9bd4784c193c8b9eaf339678876f37

**Comment by MintLily** [comment]
go to https://discordapp.com/developers/applications/me and update your bot token.

**Comment by WernerderChamp** [comment]
You need to update ytdl

Use `python3 -m pip install -U -r requirements.txt` on your server

**Comment by TBK** [comment]
@WernerderChamp is correct, update youtube_dl.

**Comment by WhitleyStriber** [comment]
I'm running the docker container version. `pip install -U -r requirements.txt` updates the dependencies but does not fix the issue. `python3 -m pip install -U -r requirements.txt` gives you the error "/usr/bin/python3: No module named pip"

**Comment by TBK** [comment]
Which docker image?

**Comment by Loxworth** [comment]
Using the `pip install -U -r requirements.txt` command fixed it for me!
