### ISSUE TITLE
Can't run runbot.bat

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1113]
I try to run runbot.bat but the cmd prompt is only there for like half a second.

**Comment by Zenrac** [comment]
Open the terminal in the folder with run.py (shift + right click, open the terminal for windows) 
Then write run.py in the terminal.
If you have an error, just post it here.

**Comment by ghost** [comment]
It's saying to run as admin.  But I don't what the command is to run as
admin.

**Comment by TBK** [comment]
Then run the both in another enviroment (another machine, virtual machine or docker).

**Comment by Zenrac** [comment]
Did you tried to open as admin update_deps ?

**Comment by ghost** [comment]
How do I run in docker?

**Comment by Zenrac** [comment]
Did you follow this guide ? https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Docker

**Comment by chuushi** [comment]
Docker documentation is **out of date**. You don't want to use it.

> It's saying to run as admin.  But I don't what the command is to run as admin.

1. Make sure you have administration privilege for your computer on your Windows account.
2. Right click `runbot.bat` (or similar) and click "Run as Administrator".  That option should have a shield icon next to it.

![2017-05-12 2](https://cloud.githubusercontent.com/assets/13530989/26021727/e58c81d0-3761-11e7-8f04-f69a23f7da5d.png)

Try that and see if it works.

**Comment by ghost** [comment]
It didn't

**Comment by kingboss5000** [comment]
i have the same issue it only says run bot not runbot.bat and the cmd prompt only opens for half a second

**Comment by IceViper04** [comment]
@kingboss5000 Try to rightclick the file runbot and save the bot as a .bat file. Or you can try going to musicbotmaster folder and run the bot through the run.py. If the program closes after just a few seconds. Try to read what it ses and message me with the text in my discord server http://IVDInvite
