### ISSUE TITLE
[REQUEST] Auto kick members in specific role when detected voice activity

### ISSUE THREAD

**Issue by BaiqingL** [Just-Some-Bots/MusicBot#1115]
As the title, I want the bot to auto kick default newly joined members once they join the music channels to prevent audio spam.

Or is there already a way to prevent them from using voice activity?

Since music is in its own dedicated channel.

Running Ubuntu 16.04 Server

**Comment by TBK** [comment]
You can set the channels permissions to disables everybodys Microphone.

**Comment by BaiqingL** [comment]
Yeah but then they would use push to talk.

**Comment by rafaelwastaken** [comment]
No, if you deny them permission to speak in a voice channel, they won't be able to talk at all.
