### ISSUE TITLE
Unable to download webpage

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1117]
everytime i want to play anything this comes up:
`
[0;31mERROR:[0m Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))`

and i also tried to use the review branch of the bot. both not working

**Comment by ghost** [comment]
PS: dependencies already up to date

**Comment by pdisser8** [comment]
I know what you just said, but make sure your youtube-dl is up to date.
youtube-dl --update
