### ISSUE TITLE
!skip issue with auto-playlist

### ISSUE THREAD

**Issue by Hamss1** [Just-Some-Bots/MusicBot#1119]
I have a problem with the auto-playlist, It does ONLY play the first song in the list and I can't skip to the next one. Also when the song ends, it starts over again

**Comment by IceViper04** [comment]
I am sorry to hear that your astablishing problems with the bot. Try deleting that specific link in the autoplaylist file and see if that works. If this doesnt work you can contact me on my discord server http://bit.ly/IVDInvite

**Comment by iDanny07** [comment]
+1 Same issue here

**Comment by jayktaylor** [comment]
Resolved in 1.9.6_1.
