### ISSUE TITLE
Error while installing pip

### ISSUE THREAD

**Issue by VeryLongNicknameSuchWow** [Just-Some-Bots/MusicBot#1122]
After `sudo python3.5 get-pip.py` It says:
`Collecting pip
  Using cached pip-9.0.1-py2.py3-none-any.whl
Collecting setuptools
  Could not fetch URL https://pypi.python.org/simple/setuptools/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
  Could not find a version that satisfies the requirement setuptools (from versions: )
No matching distribution found for setuptools`
how do i fix it?

**Comment by TBK** [comment]
Try:
`sudo pip3 install --no-cache-dir --upgrade --force-reinstall pip`
