### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1123]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\patty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1070, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\patty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 958, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflp8UEng/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflp8UEng/en_US/base.js'",))

bot worked fine for a long time. until this started happening. i have tried reloading and installing it several, times but to no avail.

**Comment by TBK** [comment]
Update youtube_dl. It can be done with the update_deps.bat script (might need to be run as administrator).

**Comment by ghost** [comment]
I ran it as an admin but i was met with: 
C:\Users\patty\AppData\Local\Programs\Python\Python35-32\python.exe: Error while finding spec for 'pip.__main__' (<class 'ImportError'>: No module named 'urllib3'); 'pip' is a package and cannot be directly executed

**Comment by TBK** [comment]
Try to uninstall and then install a new if possible the 64bit version - https://www.python.org/ftp/python/3.5.3/python-3.5.3-amd64.exe

**Comment by ghost** [comment]
thanks. works now

**Comment by TBK** [comment]
Please close the issue.
