### ISSUE TITLE
Songs keep being deleted from default playlist

### ISSUE THREAD

**Issue by Drunkstains** [Just-Some-Bots/MusicBot#1124]
Im not sure why but the playlist.txt file I have set up keeps deleting songs from it without my knowledge. I use to have over 500 default songs in there but its deleted it down to like 50 songs now. Is there something causing this issue that Im just not aware of?

**Comment by Jogt** [comment]
The bot seems to delete all youtube-videos that it can't play, as seen here in this info-output from the bot:
`[Info] Removing unplayable song from autoplaylist: https://www.youtube.com/watch?v=XXXXXXX`
This can be caused either by a youtube-dl error, check that the most recent version is installed, or by youtube banning the video in your region.
