### ISSUE TITLE
Syntax error when try to run runbot.bat

### ISSUE THREAD

**Issue by Govik** [Just-Some-Bots/MusicBot#1127]
I have followed the instruction on the site on how to download and set up the bot, and yes I ran the dependencies bat because I followed the instructions as I mentioned before. When I try to run the runbot.bat to start the bot I get an error. Below is my console output.

```
C:\Users\goviksrealm\MusicBot>run.py
Traceback (most recent call last):
     File "C:\Users\goviksrealm\MusicBot\run.py", line 162, in main
          from musicbot import MusicBot
     File "C:\Users\goviksrealm\MusicBot\musicbot\__init__.py", line 1 in <module>

          from .bot import MusicBot
     File "C:\Users\goviksrealm\MusicBot\musicbot\bot.py", line 101
          async def wrapper(self, *args, **kwargs):
              ^
SyntaxError: invalid syntax
```

**Comment by TBK** [comment]
What version of python do you have installed?

You can use this command to figure it out:
`python -V` or `python3 -V`

**Comment by Zenrac** [comment]
Asyncio (=yield from) was added in Python 3.5. Please check your version

**Comment by Govik** [comment]
I had 3.5.1 installed so I uninstalled it and installed 3.6.1 and that gave me the error that I needed 3.5 so I installed 3.5.3 and now it seems to be working. I should have thought about it being my python version. Thanks for the help!
