### ISSUE TITLE
I need help trying to run the bot on mac

### ISSUE THREAD

**Issue by SoginoBro** [Just-Some-Bots/MusicBot#1128]
![screen shot 2017-05-11 at 1 20 57 pm](https://cloud.githubusercontent.com/assets/26101164/25965157/c6b8fed4-364c-11e7-92f1-1249222d69f6.png)

**Comment by TBK** [comment]
The the bot can not find the libopus.0.dylib file, which means that you do not have Opus Codec installed.

Read the install guide for OSX here - https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-OSX

If this resolves your issue, then please close it.

**Comment by SoginoBro** [comment]
I ran the homebrew wrong >< sorry
