### ISSUE TITLE
Crash on AWS Box

### ISSUE THREAD

**Issue by JanB1** [Just-Some-Bots/MusicBot#1129]
So, we started the Bot on an AWS box. After a few idle hours, the Bot just stops working and we have to restart it again.

I included the error text in the file below.

I saw that someone else had a similar issue: https://github.com/Just-Some-Bots/MusicBot/issues/445

[Musikbot_error.txt](https://github.com/Just-Some-Bots/MusicBot/files/994086/Musikbot_error.txt)

**Comment by TBK** [comment]
It is a problem with either Discord.py or the Websockets library, I am still trying to figure it out myself.

So far I have found that the vc.disconnect() method call (bot.py) is for the most part failing to killing the websocket.

Strange behaviour to give op a thumbs down, when it is a concrete issue.

**Comment by saviola777** [comment]
Was just teasing him for a very lacking initial issue text (which was basically "bot crashed, here's the log"), it's better now :)

**Comment by lukasni** [comment]
To add some more info , this is on an Ubuntu 16.04 box, the bot is running in a virtualenv, though I doubt that has any relevant impact.

Python version is 3.5.2, with the following packages / versions:

```aiohttp==1.0.5
appdirs==1.4.3
async-timeout==1.2.1
cffi==1.10.0
chardet==3.0.2
discord.py==0.12.0
multidict==2.1.4
packaging==16.8
pycparser==2.17
PyNaCl==1.0.1
pyparsing==2.2.0
six==1.10.0
websockets==3.3
youtube-dl==2017.5.9```

**Comment by nirinium** [comment]
Running on a 16.04 box on AWS with 0 issues. I would be willing to help with more info.

**Comment by dannymichel** [comment]
What more info could i give you and where would i find the log to show you for my repeated AWS crashes?@nirinium

**Comment by amit177** [comment]
If this is still an issue in the latest version, please open a new issue.
