### ISSUE TITLE
Opus Lib will not load 

### ISSUE THREAD

**Issue by JayySoar** [Just-Some-Bots/MusicBot#1137]
Last login: Mon May 15 20:13:48 on ttys000
/Users/Josh/Desktop/MusicBot-master/runbot_mac.command ; exit;
Joshs-Air:~ Josh$ /Users/Josh/Desktop/MusicBot-master/runbot_mac.command ; exit;
Traceback (most recent call last):
  File "run.py", line 162, in main
    from musicbot import MusicBot
  File "/Users/Josh/Desktop/MusicBot-master/musicbot/__init__.py", line 1, in <module>
    from .bot import MusicBot
  File "/Users/Josh/Desktop/MusicBot-master/musicbot/bot.py", line 38, in <module>
    load_opus_lib()
  File "/Users/Josh/Desktop/MusicBot-master/musicbot/opus_loader.py", line 17, in load_opus_lib
    raise RuntimeError('Could not load an opus lib. Tried %s' % (', '.join(opus_libs)))
RuntimeError: Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

I have tried doing the update, downloading the specific files and adding them to folder, and nothing works. Please help. Also I am on mac

**Comment by TBK** [comment]
Did you run `brew install opus`?
https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-OSX
