### ISSUE TITLE
change_status to change_presence

### ISSUE THREAD

**Issue by jaschuu** [Just-Some-Bots/MusicBot#1146]
i went to that line and changed it to change_presence, but that creates more issues anyone know how i fix this?

[Download] Started: https://www.youtube.com/watch?v=VaE203hSZNs
[Download] Complete: https://www.youtube.com/watch?v=VaE203hSZNs
D:\github\MusicBot-dev\musicbot\bot.py:467: DeprecationWarning: change_status is deprecated, use change_presence instead.
  await self.change_status(game)

**Comment by amit177** [comment]
You can ignore it.

**Comment by TBK** [comment]
Take a look at the review branch.

**Comment by Zenrac** [comment]
Just change "change_status" to "change_presence" in your code

**Comment by iThinkiWin** [comment]
change line 467 in bot.py from:
await self.change_status(game)
to:
await self.change_presence(game=None, status=None, afk=False)

**Comment by andregabriotti** [comment]
await self.change_presence(game=game, status=None, afk=False)

**Comment by jayktaylor** [comment]
Review branch has merged with the master branch today, this issue is resolved.
