### ISSUE TITLE
Can you disable game status?

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1148]
I want to disable game status if a new song is playing. How to do that?

**Comment by Zenrac** [comment]
In bot.py, in **async def update_now_playing** change for this:

```
    async def update_now_playing(self, entry=None, is_paused=False):
        pass
```

**Comment by ghost** [comment]
I don't find bot.py

**Comment by Zenrac** [comment]
musicbot/bot.py
