### ISSUE TITLE
Black runbot.bat

### ISSUE THREAD

**Issue by Brazuka-1** [Just-Some-Bots/MusicBot#1150]
The window is just black, nothing happens, the bot was working fine a few months ago then it suddenly went black and nothing else happens, I am using python 3.5.1, just like my other computer, I tried running there too and it worked just fine with the 3.5.1.
But on this computer it suddenly doesn't work anymore

**Comment by Brazuka-1** [comment]
And yes I tried running update and runbot on admin

**Comment by ratkinq** [comment]
I'm having a similar issue, I try to runbot.bat and the window just shows up black for a few seconds then disappears and the bot doesn't work :/

**Comment by jayktaylor** [comment]
Make sure that you follow the guides on the wiki correctly.
