### ISSUE TITLE
Error: Signature extraction failed: traceback (most recent call last)

### ISSUE THREAD

**Issue by PlayerOne6281** [Just-Some-Bots/MusicBot#1151]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1061, in _decrypt_signature
    return lambda s: ''.join(s[i] for i in cache_spec)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 949, in _extract_signature_function
    'params': {
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfl4Xq3l4/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfl4Xq3l4/en_US/base.js'",))

**Comment by PlayerOne6281** [comment]
I dont know how to fix it

**Comment by PlayerOne6281** [comment]
never mind i fixed it

**Comment by badboyjerry** [comment]
how did you fix this im having trouble with mine

**Comment by TBK** [comment]
Update youtube_dl

**Comment by PlayerOne6281** [comment]
i didnt have my bot authorized im my discord so i just did that step again from when i created it

**Comment by jayktaylor** [comment]
- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal

You can also update ytdl manually using the command `sudo pip install -U youtube-dl`.
