### ISSUE TITLE
[Feature Request] !uptime

### ISSUE THREAD

**Issue by owocado** [Just-Some-Bots/MusicBot#1152]
It would be great if we could check bot uptime with this feature. Just a suggestion though. Feel free to throw it in dustbin, if you want to. ^^

**Comment by Zenrac** [comment]
You can easilly make it with a global variable defined in on_ready,
e.g : global uptime 
uptime = time.time()
and called it in a function 
e.g : async def cmd_uptime(self, channel):
currentuptime = uptime - time.time()

**Comment by owocado** [comment]
Alright! Thanks.
