### ISSUE TITLE
RPI 2B+ Debian Jessie - songs are sped up

### ISSUE THREAD

**Issue by pdisser8** [Just-Some-Bots/MusicBot#1155]
Hello, 

So when I first installed the MusicBot on the PI, the sound was unbearable - like a bad chopped and screwed song. To fix it I decided to overclock my PI (overclocked to turbo preset in raspi-config) and now we can hear songs but they sound sped up/higher pitched.  

I am super new to Linux, Raspberry Pis, and Python. So it is possible that I've just made a rookie mistake somewhere in compiling or installation, but I was thinking if the bot runs it probably isn't code/dependency related. 

also experiencing this issue: https://github.com/Just-Some-Bots/MusicBot/issues/696
but as TheHeroBilly suggested not to do, I did install on root because I don't know how to not install that way. 

thanks for any help or suggestions on what to do!

**Comment by jayktaylor** [comment]
duplicate of #696, deferring discussion to there
