### ISSUE TITLE
error: command 'cl.exe' failed: No such file or directory

### ISSUE THREAD

**Issue by Profeer** [Just-Some-Bots/MusicBot#1158]
I have Visual C ++ 2014
I have reinstalled python
I have cl.exe at "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin"
Here is logs:

Everything else works except installing cffi

I have spent over 4 hours trying to get this to work. I really hope somebody could help me.

**Comment by noirscape** [comment]
Is cl.exe added to your path? Windows doesn't see it unless you add it.

**Comment by Profeer** [comment]
Well i only changed cffi==1.6.0; to cffi==1.10.0;
and it fixed everything

**Comment by TEJAPS** [comment]
yes added and it shows that path on printing echo %path% as well so env variable is done properly.
But still the same error.
