### ISSUE TITLE
Errors when trying to yt search

### ISSUE THREAD

**Issue by facelesshero** [Just-Some-Bots/MusicBot#1161]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "D:\lib\site-packages\youtube_dl\extractor\youtube.py", line 1064, in _decrypt_signature
    video_id, player_url, s
  File "D:\lib\site-packages\youtube_dl\extractor\youtube.py", line 952, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfluaMKo6/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfluaMKo6/en_US/base.js'",))

I have even made a totally new bot to try and fix it and I am getting the same error message there as well. It was working fine until I moved and didn't use it for about a month. Would love to get it back up and running.

Thanks in advance for help

**Comment by jayktaylor** [comment]
#1072
