### ISSUE TITLE
How 

### ISSUE THREAD

**Issue by IKalman** [Just-Some-Bots/MusicBot#1165]
so i was almost done and everything worked except ITS STILL OFFLINE I've been trying for more than 3 hours and it doesn't work please help

**Comment by IKalman** [comment]
raise RuntimeError('Could not load an opus lib. Tried %s' % (', '.join(opus_libs)))
RuntimeError: Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib
logout
Saving session...
 
thats what i get

**Comment by pdisser8** [comment]
Hello, 

What operating system are you trying to install on? 

have you tried to run these commands again?
sudo apt-get install git libopus-dev libffi-dev libsodium-dev -y
sudo apt-get install build-essential libncursesw5-dev libgdbm-dev libc6-dev zlib1g-dev libsqlite3-dev tk-dev libssl-dev openssl -y

**Comment by pdisser8** [comment]
oh or if you are on mac
brew install opus

**Comment by IKalman** [comment]
i did and it worked thanks
