### ISSUE TITLE
Ownerissues

### ISSUE THREAD

**Issue by PinguinMelker** [Just-Some-Bots/MusicBot#1166]
Hey,
i copied my ID as the OwnerID in the gap where stands: "OwnerID" but when i start the Bot it says: "Owner not in a voicechannel" buti am in one and i dont get it why he isnt autojoining my channel even when its enabled and there areno bindedchannels.
pls help :c

**Comment by pdisser8** [comment]
Can you see your bot in the right side of the user list in discord? Does it update to online when you start the bot? 

does the !summon command bring it to your channel?

check your MusicBot\config\options.ini to make sure that autojoin isn't commented out or disabled.

maybe try actually binding it to your channel
