### ISSUE TITLE
                               F:\Discord\MusicBot-1.9.5_2>

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1167]
An error has occured parsing the config:

  Problem:  One or more required config sections are missing.                                                           
  Solution: Fix your config.  Each [Section] should be on its own line with nothing else on it.  The following sections             are missing: [Chat], [MusicBot], [Permissions], [Credentials]                                               

F:\Discord\MusicBot-1.9.5_2>

**Comment by ghost** [comment]
What does this mean and how to fix it exactly?

**Comment by chuushi** [comment]
It means that your configuration file is missing the "Chat", "MusicBot", "Permissions", and "Credentials" sections, which basically says there is no [`config/options.ini`](https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_options.ini) file.  It's right in the code you copy-pasted:

> Solution: Fix your config. Each [Section] should be on its own line with nothing else on it. The following sections are missing: [Chat], [MusicBot], [Permissions], [Credentials]

**Comment by jayktaylor** [comment]
The comment above is spot on.
