### ISSUE TITLE
Cannot update dependencies

### ISSUE THREAD

**Issue by lukeeberhard** [Just-Some-Bots/MusicBot#1168]
Even after a fresh install, I get an error when trying to update dependencies. It appears that it can't find the requirements.txt file even though I've left it alone since I installed it.

Upon running update_deps.bat, I get this error message: http://i.imgur.com/6jSpOcu.png
Even when I tried to do it manually, same thing: http://i.imgur.com/95UkcfF.png

For posterity, here's the file, right where it should be: http://i.imgur.com/UPcdcOe.png

**Comment by pdisser8** [comment]
is your file in the root directory of your D: drive? 

try shift + right click in the folder -> open command window here -> start update_deps.bat

**Comment by jayktaylor** [comment]
Try doing it manually, but have your command prompt navigated to the right folder. The command won't work if you aren't navigated to the right folder.

**Comment by lukeeberhard** [comment]
I tried out your solution and it works fine now. I guess it's just because my default command prompt location is the root of the D: drive. Thanks so much.

**Comment by lukeeberhard** [comment]
I tried out your solution and it works fine now. I guess it's just because my default command prompt location is the root of the D: drive. Thanks so much.
