### ISSUE TITLE
How do i add a playlist

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1169]
How do i make it autoplaylist autoplay upon booting the console window!?

**Comment by pdisser8** [comment]
MusicBot -> config 
check options.ini and enable the autoplaylist. If it is commented out be sure to remove the ; before it. if it is disabled change to autoplaylist = yes

If you have a specific playlist you'd like to play the easiest way is to replace the autoplaylist.txt with yours.
