### ISSUE TITLE
Binding/Autojoining not working

### ISSUE THREAD

**Issue by mike4125** [Just-Some-Bots/MusicBot#1170]
I tried editing both text and voice channels but when I run runbot.bat it doesn't recognize it. Help!

**Comment by ssbtoday** [comment]
@mike4125 Did you remove the semicolon before each setting?

```
; Restrict the bot to only listen to certain text channels.  Uncomment (remove $
; An id looks like this number: 41771983423143930
; To get a channel id, enable Developer Mode in discord (settings, appearance),$
; Example: BindToChannels = 41000000000000005 41000000000000007
; (Don't use these ids, they won't work)
; This next line is the one you uncomment to use the option:
;
BindToChannels = <channelidgoeshere>
;

; Join a channel on startup.  Multiple channels can be added for multiple serve$
; If both this option and AutoSummon are enabled, this option takes priority.
;
AutojoinChannels = <channelidgoeshere>
;

```

What is the output of the console? Any error messages? Did you either put a Token or Email/Password?

**Comment by mike4125** [comment]
Tried removing the semicolons but they don't seem to fix the problem. The console just says that the owner isn't in a voice channel & its not bound to any channels, even though I put multiple ids. I also put in a token. Also, I can't seem to find the console .-.

**Comment by pdisser8** [comment]
Hi Mike,

can we see your options.ini here?

**Comment by IceViper04** [comment]
Try putting in the channel id that you want the bot to join. Then save the document. When you have done that you should open discord and join the specified channel. Then the bot should join the server. If you have the ability to move members in voicechats you can move the bot to different channels. I have also tried configuring the bot to join a channel without me being conected to that voicechannel but Indont think it totaly works that way. If you need to contact me further, join my discord server: http://bit.ly/IVDInvite
