### ISSUE TITLE
Issues with some requests

### ISSUE THREAD

**Issue by Snowplex** [Just-Some-Bots/MusicBot#1173]
![error](https://cloud.githubusercontent.com/assets/29170995/26758870/ee297000-48b9-11e7-956d-35f2ef59453f.PNG)
The screenshot is the error information I receive when I attempt to request song from YouTube videos. This started to occur recently

**Comment by jayktaylor** [comment]
- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal

You can also update ytdl manually using the command `sudo pip install -U youtube-dl`.
