### ISSUE TITLE
Is there a way to put songs higher in the queue?

### ISSUE THREAD

**Issue by TheDefendHand** [Just-Some-Bots/MusicBot#1175]
I'm trying to set songs, which where searched by me or my buddys higher in queue, so we don't have to wait for the playlist to end.

Thanks for help :)

**Comment by pdisser8** [comment]
check for the feature !playnext. I don't think its added yet but there are some people working on it

**Comment by pdisser8** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/786

**Comment by TheDefendHand** [comment]
thx
