### ISSUE TITLE
sync YouTube Playlist with Autoplaylist

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1176]
I want sync my Autoplaylist with a YouTube Playlist.

Is there a way?

Please excuse my bad English!!!

**Comment by ghost** [comment]
Is it perhaps possible with youtube-dl?

**Comment by gabe-adams** [comment]
If you mean you want to replace the autoplaylist the bot pulls songs from with a YouTube playlist you find, there's an easy way to do it. Find the autoplaylist.txt file. It's a comma-delimited list of URLs. Rename this to autoplaylist_default.txt or something just in case. 

Find the youtube playlist you want. You need to have the url that actually contains 'playlist' in it (ex. https://www.youtube  (. ) com/**playlist?**list=PLBPgkLjAQ0qcIXrOfjMwhEmQ07VtdGifd)  

With the bot running, type !pldump (your playlist url). The bot takes the playlist URL and outputs a txt file with all of the individual URLs listed and delimited by commas. Take this file and rename it to autoplaylist.txt. Relaunch the bot and the new autoplaylist should be the one that you just found and dumped.

**Comment by ghost** [comment]
On linux:
At the Desktop:
autoplaylist.sh:

**Comment by mining-d** [comment]
cd /home/pi
sudo youtube-dl -i --get-id https://www.youtube.com/playlis
cd /home/pi
sudo mv -f /home/pi/autoplaylist.txt /home/pi/EXECUTE/confi
cd /home/pi
sudo youtube-dl -i --get-id http://www.youtube.com/playlist
cd /home/pi
sudo mv -f /home/pi/autoplaylist.txt /home/pi/MusicBot/conf

**Comment by mining-d** [comment]
cd /home/pi
sudo youtube-dl -i --get-id https://www.youtube.com/playlist?list=PLdo1SSQ1_RpF
cd /home/pi
sudo mv -f /home/pi/autoplaylist.txt /home/pi/EXECUTE/config
cd /home/pi
sudo youtube-dl -i --get-id http://www.youtube.com/playlist?list=PL3TvkdFxMpNUP
cd /home/pi
sudo mv -f /home/pi/autoplaylist.txt /home/pi/MusicBot/config

**Comment by ghost** [comment]
On Windows: just type move and not mv
And use your phad
And use a Batch file (.bat)

**Comment by mining-d** [comment]
cd /home/pi
sudo youtube-dl -i --get-id https://www.youtube.com/playlist?list=PLdo1SSQ1_RpFNULSipINiUp1m6m5fDOaj > autoplaylist.txt
cd /home/pi
sudo mv -f /home/pi/autoplaylist.txt /home/pi/EXECUTE/config
cd /home/pi
sudo youtube-dl -i --get-id http://www.youtube.com/playlist?list=PL3TvkdFxMpNUP1eTgjCeaUnsZCW8fChdp > autoplaylist.txt
cd /home/pi
sudo mv -f /home/pi/autoplaylist.txt /home/pi/MusicBot/config

**Comment by mining-d** [comment]
`cd /home/pi
sudo youtube-dl -i --get-id https://www.youtube.com/playlist?list=PLdo1SSQ1_RpFNULSipINiUp1m6m5fDOaj > autoplaylist.txt
cd /home/pi
sudo mv -f /home/pi/autoplaylist.txt /home/pi/EXECUTE/config
cd /home/pi
sudo youtube-dl -i --get-id http://www.youtube.com/playlist?list=PL3TvkdFxMpNUP1eTgjCeaUnsZCW8fChdp > autoplaylist.txt
cd /home/pi
sudo mv -f /home/pi/autoplaylist.txt /home/pi/MusicBot/config

`

**Comment by mining-d** [comment]
`cd /home/pi
sudo youtube-dl -i --get-id https://www.youtube.com/playlist?list=PLdo1SSQ1_RpFNULSipINiUp1m6m5fDOaj > autoplaylist.txt
cd /home/pi
sudo mv -f /home/pi/autoplaylist.txt /home/pi/EXECUTE/config
cd /home/pi
sudo youtube-dl -i --get-id http://www.youtube.com/playlist?list=PL3TvkdFxMpNUP1eTgjCeaUnsZCW8fChdp > autoplaylist.txt
cd /home/pi
sudo mv -f /home/pi/autoplaylist.txt /home/pi/MusicBot/config`

**Comment by ghost** [comment]
[autoplaylist.sh.txt](https://github.com/Just-Some-Bots/MusicBot/files/1130761/autoplaylist.sh.txt)
