### ISSUE TITLE
Bot can't launch

### ISSUE THREAD

**Issue by PaysGaming** [Just-Some-Bots/MusicBot#1177]
Bot isn't connecting to the channel. I made app on discord developers website and i authorized it to my channel.
![problem](https://cloud.githubusercontent.com/assets/29201958/26785129/3f0296bc-4a01-11e7-9529-6d788b85d1a2.jpg)
![image](https://cloud.githubusercontent.com/assets/29201958/26785171/6a306b34-4a01-11e7-936c-fd2bf9450769.png)
![image](https://cloud.githubusercontent.com/assets/29201958/26785286/cf1b0e14-4a01-11e7-8097-93f793581c0f.png)

**Comment by PaysGaming** [comment]
Please help me

**Comment by how2vim** [comment]
Did you install all the dependencies specified in the installation guide. Like Python 3, etc..?

**Comment by PaysGaming** [comment]
Yes i installed the latest python version. It worked good for few time but in one moment it got crash and then it isn't writing "connecting to the channel". It says "cannot import name utils", and i don't know why.

**Comment by how2vim** [comment]
Trying running the `update_deps.bat` file in the `MusicBot` folder. Then run `runbot.bat` or `run.py`, whichever you use.

**Comment by PaysGaming** [comment]
No it didn't help. Maybe u want screenshots?

**Comment by how2vim** [comment]
Check to maybe see if you accidentally altered your `requirements.txt`.

**Comment by how2vim** [comment]
Long and the short, I'd say maybe try reinstalling python and it's dependencies. Run it again and see what's up. `cannot import name 'utils'` is not a super common error from what I've seen from python.

**Comment by PaysGaming** [comment]
![image](https://user-images.githubusercontent.com/29201958/26891497-7e674de2-4bb5-11e7-8413-8d6952be4ad7.png)

**Comment by PaysGaming** [comment]
ooooow

**Comment by PaysGaming** [comment]
it works

**Comment by PaysGaming** [comment]
thanks

**Comment by PaysGaming** [comment]
but one more problem

**Comment by PaysGaming** [comment]
it sometimes dont want to play some songs

**Comment by PaysGaming** [comment]
![image](https://user-images.githubusercontent.com/29201958/26892034-4b9233b2-4bb7-11e7-933b-6733a889847a.png)

**Comment by PaysGaming** [comment]
messeges me like that

**Comment by how2vim** [comment]
Take bot offline, run `update_deps.bat` then run the bot again. If that error still shows up, try re-downloading the bot files (just bring over the config files) and try again.
