### ISSUE TITLE
MusicBot on RPi, eating disk space

### ISSUE THREAD

**Issue by Droopox** [Just-Some-Bots/MusicBot#1178]
Hi All.

I'm fairly new to musicbot and raspberry pi.  Ive installed musicbot on mi Pi3 v. B (running headless) and I've noticed that the disk space on the pi is getting smaller and smaller.
i've installed it lets say around last week thursday (it was at 5.5GB used) and today monday it's at 11.3Gb used.
Ive cleared the audio_cache folder already, but the disk usage keeps growing (also set save videos = no)
Anyone know where else i can see whats eating up the space.  Only thing running on the pi is musicbot.
Thanks.

**Comment by TBK** [comment]
You could try to investigate it with this command:
`du -sm * | sort -`
