### ISSUE TITLE
Permissions don't work.

### ISSUE THREAD

**Issue by datKaspah** [Just-Some-Bots/MusicBot#1182]
Hi, I'm trying to give my friends all permissions. But it won't work.
I follow the instructions 100%
What could the problem be?

**Comment by jayktaylor** [comment]
Did you look at https://github.com/Just-Some-Bots/MusicBot/wiki/Permissions?

**Comment by datKaspah** [comment]
Yeah I did, it won't work :(

**Comment by ghost** [comment]
Dude. PEBKAC means Problem exists between keyboard and chair basically, you're the problem.

**Comment by jayktaylor** [comment]
@datKaspah Please ask for help on our Discord server where we have helpers that can guide you through permissions fast and easily rather than commenting on this issue: https://discord.gg/bots
