### ISSUE TITLE
How do I add a "playing" Status to my bot?

### ISSUE THREAD

**Issue by maxcorreia** [Just-Some-Bots/MusicBot#1183]

**Comment by FatalMerlin** [comment]
What do you mean by "playing Status"? Normally the bot does display something like this:
![image](https://user-images.githubusercontent.com/14237330/26993595-11d559fc-4d64-11e7-9c5a-f51822ca40fd.png)

**Comment by jayktaylor** [comment]
This feature already exists. Custom ones require modification: https://github.com/Just-Some-Bots/MusicBot/wiki/Modification
