### ISSUE TITLE
[config] Config file not found, copying example_options.ini An error has occured: Problem: Your config files are missing. Neither options.ini nor example_options.ini were found. even tho I have those files

### ISSUE THREAD

**Issue by caves123** [Just-Some-Bots/MusicBot#1188]
[config] Config file not found, copying example_options.ini An error has occured: Problem: Your config files are missing. Neither options.ini nor example_options.ini were found. Solution: Grab the files back from the archive or remake them yourself and copy paste the content from the repo. Stop removing important files!

**Comment by jayktaylor** [comment]
Reinstall the bot using the guides: https://github.com/Just-Some-Bots/MusicBot/wiki
