### ISSUE TITLE
auto announce whats not playing

### ISSUE THREAD

**Issue by jaschuu** [Just-Some-Bots/MusicBot#1189]
is it possible to add when a song starts playing for the bot the say in the chat what is playing and when song is finished delete that message and announce the next song now playing?

**Comment by chuushi** [comment]
Doesn't the bot do that already?

**Comment by jaschuu** [comment]
mine doesn't seem too, only when i do !np it tells me whats now playing,

**Comment by jaschuu** [comment]
if its playing from the person enqueued list then yes, however if it's playing from the autoplaylist then no

**Comment by jaschuu** [comment]
when is starts playing i want it to tell everyone whats playing, then when it plays the next song delete that message and update to the new song playing

**Comment by jayktaylor** [comment]
This should happen. Try updating your bot and dependencies.
