### ISSUE TITLE
python isnt installed?

### ISSUE THREAD

**Issue by holtby** [Just-Some-Bots/MusicBot#1190]
i installed python and gave it every permission and followed every step perfectly, but when i try to use ''runbot.bat'' it turns blinks for about half a second with no text. After that, I tried to run ''runbot_mac'' and it said that python was not installed.

HOW DOES ANY OF THIS WORK?!

**Comment by jayktaylor** [comment]
Well `runbot_mac` obviously won't work if you're running it on Windows. Try deleting the text shown below inside runbot.bat:

![Text](http://i.imgur.com/jJxSuwc.png)

Join our Discord server if you require help, as we check that more often: https://discord.gg/bots
