### ISSUE TITLE
runbot.bat says owner id is not set when it is

### ISSUE THREAD

**Issue by itscalebfags** [Just-Some-Bots/MusicBot#1191]
I have set the owner id and when I run runbot.bat it says 

An error has occured reading the config:

  Problem:  OwnerID was not set.
  Solution: Please set the OwnerID in the config.  If you don't know what that is, use the !id command

**Comment by jayktaylor** [comment]
Hi. So we can help you easier with this issue, please ask for help in our Discord server: https://discord.gg/bots
