### ISSUE TITLE
music bot ( "you may need to run as admin to install dependencies  

### ISSUE THREAD

**Issue by lavish21** [Just-Some-Bots/MusicBot#1192]
Command "C:\Users\ladi6\AppData\Local\Programs\Python\Python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ladi6\\AppData\\Local\\Temp\\pip-build-qme3_cm9\\cffi\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ladi6\AppData\Local\Temp\pip-c5eays6c-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ladi6\AppData\Local\Temp\pip-build-qme3_cm9\cffi\

You may need to run as admin to install dependencies.

plz help

**Comment by jayktaylor** [comment]
This isn't an error and won't be helpful to letting us help you get the bot up and running. Please ask for help in our Discord server where our volunteers will be able to help you: https://discord.gg/bots
