### ISSUE TITLE
Make a song repeat?

### ISSUE THREAD

**Issue by Rejdesu** [Just-Some-Bots/MusicBot#1193]
Is there anyway to make a song loop/repeat?

**Comment by Zenrac** [comment]
#112 #486

**Comment by jayktaylor** [comment]
Dupe of #128 etc. No loop method currently exists besides PRs/forks.

**Comment by boredofbordom** [comment]
I applied the repeat option changes to my player.py file and I get no errors when running my bot, but the command doesn't register/react within discord. Any reason why? My file is attached. Thanks.
[player.zip](https://github.com/Just-Some-Bots/MusicBot/files/1240731/player.zip)
