### ISSUE TITLE
Trying to update depnedencies in Ubuntu, getting weird error

### ISSUE THREAD

**Issue by iznotros** [Just-Some-Bots/MusicBot#1197]
Hi all,

Iḿ trying to set up the music bot and when I try to install the Python dependencies using `python3 -m pip install -U -r requirements.txt`, I get this error:

`Could not import runpy module
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/runpy.py", line 14, in <module>
    import importlib.machinery # importlib first so we can test #15386 via -m
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 57, in <module>
    import types
  File "/usr/local/lib/python3.5/types.py", line 166, in <module>
    import functools as _functools
  File "/usr/local/lib/python3.5/functools.py", line 23, in <module>
    from weakref import WeakKeyDictionary
  File "/usr/local/lib/python3.5/weakref.py", line 12, in <module>
    from _weakref import (
ImportError: cannot import name '_remove_dead_weakref'`

I tried running as sudo and it says this:
 `/usr/local/bin/python3: No module named pip`

I made sure pip was installed and the latest version and it was. I have no clue what to do next. Any ideas? Forgive me if I missed something blatant

**Comment by laurentksh** [comment]
Try this: `sudo python3.5 -m pip install --upgrade pip`
It worked for me !

**Comment by iznotros** [comment]
I tried that and it told me this:
`/usr/local/bin/python3.5: No module named pip`

**Comment by laurentksh** [comment]
Are you on Ubuntu ?
