### ISSUE TITLE
Python 3.5+ is required. This version is 3.4.3+

### ISSUE THREAD

**Issue by DrVagax** [Just-Some-Bots/MusicBot#12]
I started a completely clean Ubuntu install and tried to install the bot, after editing the config and trying to launch the bot i get the following:

root@SymphonyLinux:~/MusicBot-develop# python3 run.py
Python 3.5+ is required. This version is 3.4.3+
Attempting to locate python 3.5...
Traceback (most recent call last):
  File "run.py", line 58, in main
    subprocess.check_output('py -3.5 -c "exit()"')
  File "/usr/lib/python3.4/subprocess.py", line 607, in check_output
    with Popen(_popenargs, stdout=PIPE, *_kwargs) as process:
  File "/usr/lib/python3.4/subprocess.py", line 859, in **init**
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1459, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'py -3.5 -c "exit()"'
Press any key to continue . . .python3 run.py
root@SymphonyLinux:~/MusicBot-develop#

I tried to redo the Python 3.5 install but it says it is already installed.

**Comment by imayhaveborkedit** [comment]
Try using `python3.5 run.py`

**Comment by arunesh90** [comment]
having same problem.
Using `python3.5 run.py` gave me a console full of nonstop spam
![Screenshot](http://i.imgur.com/vimVoJz.png)
And I followed the exact commands giving at the linux tutorial, even with a full server rebuild

**Comment by deansheather** [comment]
No module named `pip`?... Houston, we have a problem.

**Comment by arunesh90** [comment]
Hmmm for some reason `pip`is not installed. While I did TOTALY nothing besides the install commands at the guide.... strange

**Comment by arunesh90** [comment]
Installed pip but still getting the same error

**Comment by deansheather** [comment]
Do you mind joining the Discord help server @arunesh90 (or should I say, _Lord Gaben_) so we can have a closer look without spamming the GitHub issues? https://discord.gg/0iqN3da4zqrSz036

**Comment by imayhaveborkedit** [comment]
The develop branch has been updated.  Please remake the issue if you're still having problems.
