### ISSUE TITLE
Stop playing when channel empty

### ISSUE THREAD

**Issue by iMxAndyy** [Just-Some-Bots/MusicBot#120]
It would be neat if the bot would not play any more songs until a user joins the channel. 
(i think it should finish playing the current song in-case someone leave by mistake and comes back.)

maybe just add something so that before starting to play a new song it checks the channel. If empty = pause

**Comment by imayhaveborkedit** [comment]
I literally started working on this yesterday.

**Comment by lavender-sys** [comment]
I would like this because it would save Internet a little bit. Because when no ones listening, then the bot isn't playing music, meaning that it isn't sending audio though the Discord Music Channel. Which saves a little bit Internet.

**Comment by arunesh90** [comment]
@Dog2puppy this is already implemented in the review branch

**Comment by lavender-sys** [comment]
@arunesh90 Okay. I have downloaded the bot using the link in the Windows setup, but I still don't know how to find stuff for other branches.

**Comment by arunesh90** [comment]
https://github.com/SexualRhinoceros/MusicBot/releases/tag/v1.9.5rc5
