### ISSUE TITLE
Weird Error when attempting to play music from youtube

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1202]
I have redownloaded the zip, reconfigured the config file, reinstalled python, tried different discord botts/apps, but it still gives me this message:
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1070, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 958, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfle90bgw/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfle90bgw/en_US/base.js'",))

**Comment by ghost** [comment]
same

**Comment by Gwindol** [comment]
Hello, you want to run "update_deps.bat" which is located in bot directory. This helped me with same issue you had.

**Comment by cesarubejr** [comment]
@Gwindol just tried it. It's still not working.

**Comment by cesarubejr** [comment]
@aokuma did it work for you?
