### ISSUE TITLE
Permissions.ini changes don't seem to apply

### ISSUE THREAD

**Issue by TicWE** [Just-Some-Bots/MusicBot#1203]
I added people in MusicMaster group, but the bot says they are still in Default group.
Here is the group in Permissions.ini :
"
[MusicMaster]
; GrantToRoles = 323768016661643266 326400248660492300
; UserList = 298784194383839232 177832788760854528
MaxSongLength = 0
MaxSongs = 0
MaxPlaylistLength = 0
AllowPlaylists = yes
InstaSkip = yes
"
My friends can't use the command from #1010 #1196

**Comment by TicWE** [comment]
My friends can't use the command from #1010 #1196

**Comment by IceViper04** [comment]
Hello TicWE you might have changed the default role to something else. You might have revert the document and add a new section pererebly named after wich role you want to limit it to. Or you can try changing [Music Master] back to what permissions it had before. If you dont remeber those perms i can try finding them. If you need any more help contact me on discord. My name is IceViper04#0970

**Comment by stoopedgamertag** [comment]
Looks to me like you have the IDs commented out still. Remove the semicolon before 'GrantToRoles' and 'UserList' and they should apply.

**Comment by TicWE** [comment]
I have changed the groups to :
"; This group has full permissions.
[MusicMaster]
CommandWhitelist = add blacklist clean clear disconnect id joinserver listids np pause perms play pldump queue restart resume search setavatar setname setnick shuffle shutdown skip summon volume
 GrantToRoles = 323768016661643266 
MaxSongLength = 0
MaxSongs = 0
MaxPlaylistLength = 0
AllowPlaylists = yes
InstaSkip = yes

; This group can't use the blacklist and listids commands, but otherwise has full permissions.
[DJ]
CommandWhitelist = play pause np perms clear clean id add queue search skip volume
CommandBlacklist = blacklist listids
 GrantToRoles = 326400248660492300 327430484562935820
MaxSongLength = 0
MaxSongs = 0
MaxPlaylistLength = 0
AllowPlaylists = yes
InstaSkip = no"
But the bots still sends back :
"You don't have permission to use that command.
Reason: This command is not enabled for your group (Default)."

**Comment by TicWE** [comment]
The problem comes from the Role's ID, I've been able to give the permission by adding each person's ID, ty all

**Comment by Zenrac** [comment]
@TicWE don't forget to close
