### ISSUE TITLE
Youtube Autoplaylist won't work.

### ISSUE THREAD

**Issue by patricknoah** [Just-Some-Bots/MusicBot#1204]
I've entered the YouTube playlist link in the autoplaylist.txt file and the .bat file spams the same message over and over again: "**Error adding song from autoplaylist: ('This is a playlist.', True, 'https://www.youtube.com/playlist?list=PLfIPpIShkjYpyj_bz2gP-F2ORG7oaw4xo')**". I don't think there's any problem with that particular playlist as I have two bots with two different YT playlist and they say the same stuff (just the link is different)

**Comment by Zenrac** [comment]
You have to use !pldump 
> Collects URLs from a YouTube playlist or Soundcloud set and dumps them into a text file to allow use in an autoplaylist

from https://github.com/Just-Some-Bots/MusicBot/wiki/Commands#pldump-playlist
