### ISSUE TITLE
playlist feature

### ISSUE THREAD

**Issue by boldfacedape** [Just-Some-Bots/MusicBot#1205]
My vision for the playlist feature is when someone comes into the chat room, they are greeted by my bot either by DM or General Chat and then the bot lists the available playlists, i.e rock playlist, punk rock playlist etc and the command to play the playlist, is this possible?

**Comment by Zenrac** [comment]
With coding everything is possible, you only have to add something like :
```
async def on_member_join(self, author, channel):
    await self.safe.send_message(author/channel, "yourmessage")
```
With author to send a dm or channel to send a message in the channel (or server to send to the main channel)

- To displays differents playlist easilly you can take a look here #921 (cmd_listpl) It should help you
