### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by IceViper04** [Just-Some-Bots/MusicBot#1209]
I cant update my bot! I have tried following the instructions at: [https://github.com/Just-Some-Bots/MusicBot/wiki/Updating] but it does not seam to work. I tried pasting "git pull" into the git command prompt but theirs an error message stating the following: "Not a git repository (or any of the parent directories): .git". is there a way to fix this. Btw does updating the bot this way give you the new stream command?

Email:jonathan.nybom@outlook.com
Discord Server: [http://bit.ly/IVDInvite]
Discord Username: IceViper04#0970
![gitivmbupdateerror](https://user-images.githubusercontent.com/27918287/27509474-f3ecaea4-58fd-11e7-9282-7d7ed553c6c7.png)

**Comment by junhui-f** [comment]
Make sure you are in the right folder
e.g.
`cd C:\Users\Jonathan\MusicBot`
