### ISSUE TITLE
not an issue just a suggestion 

### ISSUE THREAD

**Issue by DrSloth12** [Just-Some-Bots/MusicBot#121]
sorry dont know if this is the right place to leave this, but here is my suggestion.
i wold love to be able to summon the bot to a different server that it already knows from the server

for example the bot account is part of server a and server b it is currently in server a but every one is in server b, so instead of restarting i should be able to "!summon" the bot to server b.

a plus would be if it keeps the same queue when moving severs

**Comment by imayhaveborkedit** [comment]
I've added moving between channels in review, but not servers yet.  I'll see if I can get that working after this update.

**Comment by DrSloth12** [comment]
Great cant wait for the next update!!!

**Comment by imayhaveborkedit** [comment]
The bot can move between channels on a server and has multiserver support with bot accounts now.
