### ISSUE TITLE
Will Not Start on Raspbian Bootup

### ISSUE THREAD

**Issue by Arineon** [Just-Some-Bots/MusicBot#1211]
I have the bot starting on bootup of my Raspberry Pi through Crontab. Here is the launcher script, Crontab execution, and the Crontab log showing the failure message. 

launcher.sh
```
#!/bin/sh
#launcher.sh
#Launches the MusicBot

cd /home/pi/MusicBot
/usr/local/bin/python3.5 run.py &
```

crontab
`reboot sh /home/pi/MusicBot/launcher.sh >/home/pi/logs/cronlog 2>&1`

crontab log

> Connecting...Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/site-packages/aiohttp/connector.py", line 304, in connect
>     yield from self._create_connection(req)
>   File "/usr/local/lib/python3.5/site-packages/aiohttp/connector.py", line 578, in _create_connection
>     transport, proto = yield from self._create_direct_connection(req)
>   File "/usr/local/lib/python3.5/site-packages/aiohttp/connector.py", line 589, in _create_direct_connection
>     hosts = yield from self._resolve_host(req.host, req.port)
>   File "/usr/local/lib/python3.5/site-packages/aiohttp/connector.py", line 561, in _resolve_host
>     self._resolver.resolve(host, port, family=self._family)
>   File "/usr/local/lib/python3.5/site-packages/aiohttp/resolver.py", line 29, in resolve
>     host, port, type=socket.SOCK_STREAM, family=family)
>   File "/usr/local/lib/python3.5/asyncio/futures.py", line 385, in __iter__
>     yield self  # This tells Task to wait for completion.
>   File "/usr/local/lib/python3.5/asyncio/tasks.py", line 288, in _wakeup
>     value = future.result()
>   File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
>     raise self._exception
>   File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.5/socket.py", line 728, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -2] Name or service not known
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "run.py", line 165, in main
>     m.run()
>   File "/home/pi/MusicBot/musicbot/bot.py", line 551, in run
>     self.loop.run_until_complete(self.start(*self.config.auth))
>   File "/usr/local/lib/python3.5/asyncio/base_events.py", line 342, in run_until_complete
>     return future.result()
>   File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
>     raise self._exception
>   File "/usr/local/lib/python3.5/asyncio/tasks.py", line 237, in _step
>     result = coro.throw(exc)
>   File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 458, in start
>     yield from self.login(*args, **kwargs)
>   File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 384, in login
>     yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
>   File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 314, in _login_1
>     data = yield from self.http.static_login(token, bot=is_bot)
>   File "/usr/local/lib/python3.5/site-packages/discord/http.py", line 195, in static_login
>     data = yield from self.get(self.ME)
>   File "/usr/local/lib/python3.5/site-packages/discord/http.py", line 105, in request
>     r = yield from self.session.request(method, url, **kwargs)
>   File "/usr/local/lib/python3.5/site-packages/aiohttp/client.py", line 555, in __iter__
>     resp = yield from self._coro
>   File "/usr/local/lib/python3.5/site-packages/aiohttp/client.py", line 198, in _request
>     conn = yield from self._connector.connect(req)
>   File "/usr/local/lib/python3.5/site-packages/aiohttp/connector.py", line 314, in connect
>     .format(key, exc.strerror)) from exc
> aiohttp.errors.ClientOSError: [Errno -2] Cannot connect to host discordapp.com:443 ssl:True [Name or service not known]
> Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x756c3770>

**Comment by ghost** [comment]
This could  be caused by the bot trying to connect before your raspberry pi is connected to the internet. Possibly try delaying the startup of the bot by a minute or so.
