### ISSUE TITLE
Error when trying to play certain songs on youtube. (Yes I have tried to use the Updates_deps multiple times

### ISSUE THREAD

**Issue by Yuhhuh** [Just-Some-Bots/MusicBot#1212]
This the the error
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "E:\lib\site-packages\youtube_dl\extractor\youtube.py", line 1070, in _decrypt_signature
    video_id, player_url, s
  File "E:\lib\site-packages\youtube_dl\extractor\youtube.py", line 958, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflmgXZN3/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflmgXZN3/en_US/base.js'",))

**Comment by ghost** [comment]
This is usually caused by an old version of youtube-dl, so it is possible the update script provided is not working.
    Open command prompt and type in `youtube-dl --version`, if the date is significantly old (or you could try it anyway) open command prompt as administrator and type `pip install youtube-dl --upgrade`, this should hopefully fix it.
