### ISSUE TITLE
[Request] Ability to add songs to the default autoplaylist live

### ISSUE THREAD

**Issue by Dubzie** [Just-Some-Bots/MusicBot#1219]
like a command !ap (url)
Will append the url to the end of the Auto playlist file.

**Comment by MeepCastana** [comment]
#1196 try this

**Comment by Zenrac** [comment]
and #1010 (and my comments above)

**Comment by Injusticecraft** [comment]
use what zenrac put on #1010 cuz it works like magic and i havent had any problems with it so far
