### ISSUE TITLE
!skip is no longer a vote to skip

### ISSUE THREAD

**Issue by iMxAndyy** [Just-Some-Bots/MusicBot#122]
no matter what i set the config to it will skip after 1 vote as though everyone is owner.
it used to work in previous versions but doesn't seem to anymore

**Comment by Ivoz** [comment]
:+1:

**Comment by imayhaveborkedit** [comment]
I'm sure this is a you problem, not a bot problem.  This issue is also two weeks old.  Reopen if you can't get it to work even after downloading the latest version.

**Comment by Ivoz** [comment]
@imayhaveborkedit I have also found the same issue, using the RC5 release. I have in my config:

```
; Skips required to skip a song.  Whichever is lower will be used.
; Skip ratio refers to the percent of non-deafened, non-owner users
; in the voice channel needed to skip a song.
;SkipRatio = 0.5
SkipsRequired = 2
```

And only 1 person needs to type `.skip` for the bot to skip.

**Comment by dbkynd** [comment]
The bot and the bot owner don't count towards the skip command. So if you (owner), the bot and 2 others are in a channel and 1 of those other people runs skip, that is 50% of 'counted' users.

**Comment by imayhaveborkedit** [comment]
That's for `SkipRatio`.  `SkipsRequired` should be as it says.  Uncomment `SkipRatio` and set it to 1.0, see if that fixes it.
