### ISSUE TITLE
Not working on Raspberry Pi 3 Model B

### ISSUE THREAD

**Issue by sanstzu** [Just-Some-Bots/MusicBot#1220]
I have followed all the instruction on https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Raspbian#1-dependencies, but it still doesn't work when I try to run on the last step.

I typed `python3.5 run.py` but its out put like this:
`No module named 'aiohttp'
Attempting to install dependencies...`
It doesn't install the aiohttp stuff but it cancel its proccess. How to fix this

**Comment by Masonrf** [comment]
It might work if you try using `sudo python3.5 run.py` the first time you run it to install the dependancies.
