### ISSUE TITLE
Is it possible to have a bot connect to two channels 

### ISSUE THREAD

**Issue by ikifar2012** [Just-Some-Bots/MusicBot#1221]
Is it possible to have a bot connect to two channels at once

**Comment by TimmyTheRat** [comment]
Yes. Just invite it on the second server. But it will play the same music on both servers. If you want it  to run separately on 2 different servers make a copy of your bot folder, go to discord make a new bot account and change the token for the second bot. That way you will have the same bot version running on 2 different servers separately

**Comment by MeepCastana** [comment]
No

**Comment by HikKiXIII** [comment]
If you'd like to do so, it is recommended that you use two separate instance of the bot to achieve what you're looking for.

**Comment by FIERCEDINO080** [comment]
If you are talking about two channels on the same server: no
If you're talking about two channels on different servers (eg. Connecting to general on your server at the same time as the bot being on a voice channel on your friends server), yes.
