### ISSUE TITLE
[Request] Status message when not playing music

### ISSUE THREAD

**Issue by MeepCastana** [Just-Some-Bots/MusicBot#1222]
Hey, can somebody tell me how do i make the bot have a status message when not playing music ? Currently the status shows the music that i'm playing, and when the music stops the status is no longer showing anything.

**Comment by Zenrac** [comment]
If you meant the status message below the name of the bot, this is the answer
In a**sync def update_now_playing**
You only have to add something like
```
if activeplayers == 0:
    game = discord.Game(name="i'm not playing")
    entry = None
```

**Comment by MeepCastana** [comment]
thanks
