### ISSUE TITLE
Music Bot does not let my moderator use !disconnect or !clear 

### ISSUE THREAD

**Issue by RAMSTER678** [Just-Some-Bots/MusicBot#1225]
As you can see from these images the bot will not give my mod permission to use certain commands, any help would be greatly appreciated!

![unsure](https://user-images.githubusercontent.com/29823204/27765103-285265b4-5ea1-11e7-8110-ce6290b8e2ec.PNG)
![notsure](https://user-images.githubusercontent.com/29823204/27765105-3329ef0c-5ea1-11e7-8a48-e41be2f97595.PNG)

**Comment by MeepCastana** [comment]
delete the ; in front of GrantToRoles and UserList
having the text like this ;Example will get ignored as it will be considered as a comment.

**Comment by RAMSTER678** [comment]
I deleted the ; but the same message pops up. Any other suggestions?

![capture](https://user-images.githubusercontent.com/29823204/27771946-41bd19b2-5f51-11e7-9252-b03bd04e2438.PNG)

**Comment by MeepCastana** [comment]
Try to remove their id's. That way they will be automatically assigned to default group.

**Comment by RAMSTER678** [comment]
Unfortunately this hasn't worked either. Could it be becuase he does not have admin persmissions? I can use these commands and I'm admin but he's just a mod.

![capture](https://user-images.githubusercontent.com/29823204/27772011-6cce39dc-5f52-11e7-9922-e81d241a7b25.PNG)

**Comment by MeepCastana** [comment]
Hmm... could you please send me a picture of your Permission file ?

**Comment by RAMSTER678** [comment]
![capture](https://user-images.githubusercontent.com/29823204/27772145-1e8007a4-5f54-11e7-9a85-d2141b0756a4.PNG)

**Comment by MeepCastana** [comment]
Does your folder look like this ? 
![capture](https://user-images.githubusercontent.com/29717481/27772166-2e25d286-5f65-11e7-8a53-b58c218bf63b.PNG)

**Comment by RAMSTER678** [comment]
Ohhh
I'm assuming that i was using the example which does nothing?

**Comment by RAMSTER678** [comment]
and yes it does look like that

**Comment by MeepCastana** [comment]
Make every change you want on example_options.ini / permissions_options.ini then save them as 

options.ini / permissions.ini

**Comment by RAMSTER678** [comment]
THANK YOU SO MUCH
If I were with you in person i would hug you rn

**Comment by MeepCastana** [comment]
Ayo thank you brother! Glad i was able to help!

**Comment by MeepCastana** [comment]
Also can you close the issue ?
