### ISSUE TITLE
autoplaylist.txt

### ISSUE THREAD

**Issue by fallenfrost** [Just-Some-Bots/MusicBot#1229]
how do i play an autoplaylist?

**Comment by MeepCastana** [comment]
Edit options.ini file UseAutoPlaylist = yes

If you want your own songs to be played by the autoplaylist go to autoplaylist.txt and delete everything. Then add youtube urls with the songs, each link has to be on a DIFFERENT line

**Comment by fallenfrost** [comment]
ty!
