### ISSUE TITLE
Bot crash when it gets spammed

### ISSUE THREAD

**Issue by Zenrac** [Just-Some-Bots/MusicBot#1230]
![ssss](https://user-images.githubusercontent.com/19573589/27860334-70cd4c36-617c-11e7-8e85-10f447597307.png)

As you can see, when someone spam =play with one music, an error occurs, it's because the bot try to delete the file while it's used. 

On Linux the bot will crash, on Windows the bot will have some weird issues such as sound saturated etc...
Well in both cases, the bot stops to answer because it think that it's downloading
![ss 2017-07-05 at 12 24 53](https://user-images.githubusercontent.com/19573589/27860466-0d6aea26-617d-11e7-8974-b88dca1af22a.png)

For the moment the only way to prevent from this issue is to set the **SaveVideos = yes** otherwise it will try to delete an used file.

**Comment by MeepCastana** [comment]
doesn't happen to me 
![capture](https://user-images.githubusercontent.com/29717481/27864634-07df77be-6198-11e7-9434-2ed7d8300d6a.PNG)

**Comment by Zenrac** [comment]
Did you try with a link instead of keywords ?
Btw i've only tested on the master branch

**Comment by MeepCastana** [comment]
im on review branch. Tested with links too

**Comment by Zenrac** [comment]
With SaveVideos = no ?

**Comment by MeepCastana** [comment]
no

**Comment by MeepCastana** [comment]
tested with save videos false 
![capture](https://user-images.githubusercontent.com/29717481/27866002-62e3c598-619d-11e7-8253-d25f762796e3.PNG)

**Comment by Zenrac** [comment]
I've understand the problem, when you send too fast the same command, it will add the same song twice at the same time.
It plays the two songs at the same time (weird) and after a couple of time it crash. 
Maybe we should add a check to prevent this to happening
