### ISSUE TITLE
ERROR: This playlist is private, use --username or --netrc to access it.

### ISSUE THREAD

**Issue by magn0053** [Just-Some-Bots/MusicBot#1232]
There's no way in the source code nor on the wiki site I could find a work around for this, I'll fix this by making the playlist unlisted, but I'd still like an explanation on how I fix this.

**Comment by chuushi** [comment]
From what I speculate, the MusicBot itself needs to change configuration in order to hook or link YouTube accounts to the bot.

**Comment by jayktaylor** [comment]
We don't support private playlists as we don't pass account information to youtube-dl.
