### ISSUE TITLE
Error when running update_deps

### ISSUE THREAD

**Issue by VengfulSnp** [Just-Some-Bots/MusicBot#1233]
Have had a look in the already made issues but could't find this exact problem. when I try to run the "Updat_deps.exe" CMD i get,
H:\Discord bot\python\python.exe: No module named pip
H: \DISCOR~1\MUSICB~1>

Also when I run the "runbot.bat" CMD I get 
No module named 'aiohttp'
Attempting to install dependencies...
H: \Discord bot\MusicBot-master>

If anyone could give us a hand with this issue that would be great I'm not to computer savy so if you need more info ect, just let us know and ill send more screen shots
Thanks!
![discord bot troubles](https://user-images.githubusercontent.com/29942854/27901284-100e7350-6264-11e7-8151-2d7f739c4ef9.png)

**Comment by alps101** [comment]
I suspect python installation.
Have you checked all installation check box?
like below
Install launcher for all users (recommended)
Add Python 3.5 to PATH

**Comment by VengfulSnp** [comment]
Cool that worked thanks I forgot to check the add to PATH box :/
