### ISSUE TITLE
Youtube "This video contains content from !@*($&, who has blocked it on copyright grounds.

### ISSUE THREAD

**Issue by alps101** [Just-Some-Bots/MusicBot#1234]
Hello Team,
I got an error message as below.
This video contains content from %#!*&%*(#%, who has blocked it on copyright grounds.
I used the link https://www.youtube.com/playlist?list=PLBSvleni5is2u66UMpc7nLOK6hh7w5OrQ
I can play this music through any browsers without any issues.
Is there any method to solve this problem?

Thank you
regards

**Comment by fofofofofofofofoXD** [comment]
One of the videos in that playlist got taken down due to copyright. I'd suggest checking if any mirrors or reuploads exist.

**Comment by jayktaylor** [comment]
Some videos can be blocked on copyright grounds when played externally. We can't do anything about this.

**Comment by jcat42o** [comment]
ddssd'<hr>

**Comment by jcat42o** [comment]
ya ya ya '<script>alert(document.cookie);</script>

**Comment by jcat42o** [comment]
<hr>
<bold> 
The dopest trance sets on the net - 
https://tranceattic.com </bold>

**Comment by jcat42o** [comment]
<a href="https://tranceattic.com" target=_blank>Full trance sets </a>
