### ISSUE TITLE
I made an automatic installer for Raspbian

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1237]
I wanted to install the bot on my Raspberry Pi and saw that the installation process is relatively long and requires some typing, so I thought it would be easier for users to [have a bash script that automates the process](https://gist.github.com/r4indeer/96712b625cbaf4e6540cfe10004b8ee6). If you like it, you could include it into the wiki page.

**Comment by fonta** [comment]
Nice job!

**Comment by jayktaylor** [comment]
Added the script to the wiki page, thanks.
