### ISSUE TITLE
Make MusicBot read only one specific channel.

### ISSUE THREAD

**Issue by hikkiwastaken** [Just-Some-Bots/MusicBot#1239]
Hi, I was wondering if there was a way to set the bot that it's only reading one certain specific channel on a server to send/receive commands? I guess I must have missed it somewhere along the line.

**Comment by Zenrac** [comment]
BindToChannels : https://github.com/Just-Some-Bots/MusicBot/wiki/Configuration#bindtochannels

**Comment by hikkiwastaken** [comment]
Thank you!
