### ISSUE TITLE
Music constantly cutting out

### ISSUE THREAD

**Issue by Xeroes** [Just-Some-Bots/MusicBot#124]
I receive the following error about every song:

File "C:\Users\Xeroes\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 649, in play_audio
    sent = self.socket.sendto(packet, (self.endpoint_ip, self.voice_port))
BlockingIOError: [WinError 10035] A non-blocking socket operation could not be completed immediately

Is there any fix for this?

**Comment by imayhaveborkedit** [comment]
This is a discord.py related issue.  Supposedly this happens because the send buffer gets too full.  Perhaps you have a slow connection.  When this gets fixed, the library will simply drop packets.
