### ISSUE TITLE
How to set the bot to not stop music if noone is in the channel?

### ISSUE THREAD

**Issue by DarioNCS** [Just-Some-Bots/MusicBot#1242]
Hello guys,
I have never used pyton, but I think the general file of the bot is working (if i dont touch the files). The only thing I want to ask is how to make sure that music is not interrupted if there is no one in the channel?

**Comment by MeepCastana** [comment]
go in options.ini 
AutoPause = no

**Comment by Zenrac** [comment]
https://github.com/Just-Some-Bots/MusicBot/wiki/Configuration#autopause
