### ISSUE TITLE
Bot does not join server when using !joinserver <link>

### ISSUE THREAD

**Issue by yannickkordel** [Just-Some-Bots/MusicBot#1245]
The bot does not join the server when sending the !joinserver <link> via DM.
I set the Owner-ID and I'm using an actual Discord account (ofc)

The bot replies with a thumbs up, and the following is printed in console:

[Command] numberid/name (!joinserver link)

**Comment by Zenrac** [comment]
Not only in DM, everywhere, it's a discord.py issue, client.accept_invite is now "outdated", you cannot use it anymore.
![capture](https://user-images.githubusercontent.com/19573589/28146157-f5c9fba4-6777-11e7-8794-95f8bb68ba1b.PNG)

**Comment by yannicktf** [comment]
Hi, thanks for letting me know. 
It should probably be removed from the wiki then: https://github.com/Just-Some-Bots/MusicBot/wiki/Commands

**Comment by Zenrac** [comment]
I think we should wait and see if it can be replaced by something else

**Comment by Rainbowdashboygamer** [comment]
else if (message.content.startsWith('')) {//Check if command is hi
  message.channel.send('two snipers walk into a bar. One says I like to sniper metal and the other one says I like to snipe steal.'); //Say hi back 
here's what I'm trying to do. I want the bot to introduce itself after it is invited to the server some of the commands in discord.js are not working any other ideas?

**Comment by Rainbowdashboygamer** [comment]
this caused my bot to spam in my channel and may have spammed in other channels as well

**Comment by jayktaylor** [comment]
@Rainbowdashboygamer this is not the repo for discord.js.
