### ISSUE TITLE
ffmpeg: error while loading shared libraries: libx265.so.95: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by corombb** [Just-Some-Bots/MusicBot#1246]
Tried playing music and it pops out this error. Tried purging ffmpeg and reinstalling it and all it did was change .90 to .95

**Comment by jayktaylor** [comment]
See https://github.com/Kwoth/NadekoBot/issues/1394, your issue can likely be resolved the same way.

**Comment by darkterrorooo** [comment]
https://github.com/Kwoth/NadekoBot/issues/1394

see my answer
