### ISSUE TITLE
How to set bot to announce "Now playing:" when in auto playlist.

### ISSUE THREAD

**Issue by Herobrice** [Just-Some-Bots/MusicBot#1248]
I am using the bot to play an auto playlist of NCS music as I am helping a streamer and every now and them someone asks what was queued and i would have to /queue to show them, I was wondering if there was a way to announce what is being played currently and delete that message when the next song is queued just like as if you queued the music yourself. The only difference is that the bot is on an auto playlist.

**Comment by MeepCastana** [comment]
async def cmd_np(self, player, channel, server, message):
    """
    Usage:
        {command_prefix}np

    Displays the current song in chat.
    """

    if player.current_entry:
        if self.server_specific_data[server]['last_np_msg']:
            await self.safe_delete_message(self.server_specific_data[server]['last_np_msg'])
            self.server_specific_data[server]['last_np_msg'] = None

        # TODO: Fix timedelta garbage with util function
        song_progress = ftimedelta(timedelta(seconds=player.progress))
        song_total = ftimedelta(timedelta(seconds=player.current_entry.duration))

        streaming = isinstance(player.current_entry, StreamPlaylistEntry)
        prog_str = ('`[{progress}]`' if streaming else '`[{progress}/{total}]`').format(
            progress=song_progress, total=song_total
        )
        prog_bar_str = ''

        # percentage shows how much of the current song has already been played
        percentage = 0.0
        if player.current_entry.duration > 0:
            percentage = player.progress / player.current_entry.duration
        """
        This for loop adds  empty or full squares to prog_bar_str (it could look like
        [■■■■■■■■■■□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□]
        if for example the song has already played 25% of the songs duration
        """
        progress_bar_length = 37
        for i in range(progress_bar_length):
            if (percentage < 1 / progress_bar_length * i):
                prog_bar_str += '▁'
            else:
                prog_bar_str += '▂'

        action_text = 'Streaming' if streaming else 'Playing'

        if player.current_entry.meta.get('channel', False) and player.current_entry.meta.get('author', False):
            np_text = "**Song:** [ <{url}> ] queued by **{author}** \n```{progress} Song: {title}  \n {progress_bar}```".format(

                action=action_text,
                title=player.current_entry.title,
                author=player.current_entry.meta['author'].name,
                progress_bar=prog_bar_str,
                progress=prog_str,
                url=player.current_entry.url
            )
        else:
            np_text = "**Song:** [ <{url}> ] \n```{progress} Song: {title}  \n {progress_bar}```".format(
                action=action_text,
                title=player.current_entry.title,
                progress_bar=prog_bar_str,
                progress=prog_str,
                url=player.current_entry.url
            )

        self.server_specific_data[server]['last_np_msg'] = await self.safe_send_message(channel, np_text)
        await self._manual_delete_check(message)
    else:
        return Response(
            'There are no songs queued! Queue something with {}play.'.format(self.config.command_prefix),
            delete_after=30
        )

**Comment by MeepCastana** [comment]
from #674.

**Comment by Herobrice** [comment]
Where do i put this?

**Comment by MeepCastana** [comment]
in bot.py

**Comment by Herobrice** [comment]
ik but anywhere in there particular

**Comment by Herobrice** [comment]
ive attempted this multiple times and it doesn't change the bot in anyway, and there seems to be a lot of extra files missing, do i need to download something extra for this to work?

**Comment by MeepCastana** [comment]
in bot.py put it between commands

**Comment by MeepCastana** [comment]
you don't need to download anything/add anything other than the code i sent you

**Comment by MeepCastana** [comment]
also im using Review branch

**Comment by Herobrice** [comment]
ya i did put it in between commands but when i run it, it keeps saying there are multiple errors in the coding, i keep trying to fix it but once i fix one issue anotherone comes up :/

**Comment by MeepCastana** [comment]
Send me the errors

**Comment by Herobrice** [comment]
actually is there a way u can just send me a completed file, i didnt personalise it that much i can fix it myself after.

**Comment by MeepCastana** [comment]
Why don't you send me errors u get when u try to launch the bot? I edited my bot so many times i'll have to send you a zip folder. Make it simple.. send me errors u get and i will tell you what to fix.

**Comment by Herobrice** [comment]
![error 1](https://user-images.githubusercontent.com/30158250/28265612-e10e9c1e-6b1a-11e7-8005-ef6ada3a1349.png)
This is the first error that starts the chain when i try to fix it. I may have fixed it wrong. But i just reset it and freshly copied and pasted it so u can tell me :)

**Comment by MeepCastana** [comment]
you need to respect indentations

**Comment by MeepCastana** [comment]
send me ur bot.py file
and i will edit it for you...

**Comment by Herobrice** [comment]
[bot.zip](https://github.com/Just-Some-Bots/MusicBot/files/1153047/bot.zip)
Here it is.

**Comment by Herobrice** [comment]
i probs put the coding in the wrong place in the first place xD

**Comment by MeepCastana** [comment]
[New WinRAR ZIP archive.zip](https://github.com/Just-Some-Bots/MusicBot/files/1153808/New.WinRAR.ZIP.archive.zip)
should work

**Comment by Kyrandix** [comment]
@TimmyTheRat i have the same problem too, could you pls tell me what should i add in my bot.py?

**Comment by MeepCastana** [comment]
async def cmd_np(self, player, channel, server, message):
"""
Usage:
{command_prefix}np

Displays the current song in chat.
"""

if player.current_entry:
    if self.server_specific_data[server]['last_np_msg']:
        await self.safe_delete_message(self.server_specific_data[server]['last_np_msg'])
        self.server_specific_data[server]['last_np_msg'] = None

    # TODO: Fix timedelta garbage with util function
    song_progress = ftimedelta(timedelta(seconds=player.progress))
    song_total = ftimedelta(timedelta(seconds=player.current_entry.duration))

    streaming = isinstance(player.current_entry, StreamPlaylistEntry)
    prog_str = ('`[{progress}]`' if streaming else '`[{progress}/{total}]`').format(
        progress=song_progress, total=song_total
    )
    prog_bar_str = ''

    # percentage shows how much of the current song has already been played
    percentage = 0.0
    if player.current_entry.duration > 0:
        percentage = player.progress / player.current_entry.duration
    """
    This for loop adds  empty or full squares to prog_bar_str (it could look like
    [■■■■■■■■■■□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□]
    if for example the song has already played 25% of the songs duration
    """
    progress_bar_length = 37
    for i in range(progress_bar_length):
        if (percentage < 1 / progress_bar_length * i):
            prog_bar_str += '▁'
        else:
            prog_bar_str += '▂'

    action_text = 'Streaming' if streaming else 'Playing'

    if player.current_entry.meta.get('channel', False) and player.current_entry.meta.get('author', False):
        np_text = "**Song:** [ <{url}> ] queued by **{author}** \n```{progress} Song: {title}  \n {progress_bar}```".format(

            action=action_text,
            title=player.current_entry.title,
            author=player.current_entry.meta['author'].name,
            progress_bar=prog_bar_str,
            progress=prog_str,
            url=player.current_entry.url
        )
    else:
        np_text = "**Song:** [ <{url}> ] \n```{progress} Song: {title}  \n {progress_bar}```".format(
            action=action_text,
            title=player.current_entry.title,
            progress_bar=prog_bar_str,
            progress=prog_str,
            url=player.current_entry.url
        )

    self.server_specific_data[server]['last_np_msg'] = await self.safe_send_message(channel, np_text)
    await self._manual_delete_check(message)
else:
    return Response(
        'There are no songs queued! Queue something with {}play.'.format(self.config.command_prefix),
        delete_after=30
    )

**Comment by Kyrandix** [comment]
ok.. but i copied this before put it in my bot.py and i get that identation error

**Comment by MeepCastana** [comment]
download the zip file i sent and look how i made the np command. The spaces are VERY important

**Comment by Kyrandix** [comment]
still get the error, but i noticed in the file i downloaded ■■■■■■■■■■□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□ these squares of the progress bar display. meanwhile in my bot.py these squares are all "???????????????????" idk if you understand what i said

**Comment by Kyrandix** [comment]
![notepad _18-07-2017_00-17-33](https://user-images.githubusercontent.com/22823557/28292266-92acb798-6b4e-11e7-9099-dd790b593427.png)
i see this in the file i downloaded

**Comment by Kyrandix** [comment]
![notepad _18-07-2017_00-17-49](https://user-images.githubusercontent.com/22823557/28292275-9dbbc91c-6b4e-11e7-810d-86b886181d26.png)
this is what i see in my file

**Comment by MeepCastana** [comment]
send me ur bot.py file

**Comment by Kyrandix** [comment]
[bot.zip](https://github.com/Just-Some-Bots/MusicBot/files/1154147/bot.zip)

**Comment by MeepCastana** [comment]
does it work ?

**Comment by TimmyTheRat** [comment]
https://discord.gg/AhSMg join this to make it easier

**Comment by Kyrandix** [comment]
you are a faggot. really i had to say this after you banned me because i used 1 of your server emojis

**Comment by Herobrice** [comment]
uh, whatever happened here.. ok then.. anywayy..... Timmy, the file u gave me it says IndentationError: unident does not match any outer indentation level

**Comment by MeepCastana** [comment]
send me the whole error

**Comment by Pesoen** [comment]
just tried getting it to work, but i get this error now.
`[Command] 167062581658255361/Pesoen (!!np)
Traceback (most recent call last):
  File "E:\GIT\MusicBot\musicbot\bot.py", line 1968, in on_message
    response = await handler(**handler_kwargs)
  File "E:\GIT\MusicBot\musicbot\bot.py", line 1698, in cmd_np
    song_progress = ftimedelta(timedelta(seconds=player.progress))
NameError: name 'ftimedelta' is not defined`

any ideas? want to get this function working as well :)

**Comment by Pesoen** [comment]
also Herobrice. the line numer is very important, had the same error, took me two seconds after finding the line to fix it. here is my bot.py file, no errors, unless np is called.
[https://www.dropbox.com/s/3ckje27270w7xzk/bot.zip?dl=0](url)

if you want to fix it yourself, go to line 1684 and remove a single space. that will fix it :)

**Comment by MeepCastana** [comment]
It doesn't work because you're using the default branch. Switch to review if u want the command to work properly

**Comment by Pesoen** [comment]
got the review version. still not showing now playing unless called. but hey no errors at least.

other than this one, after skip is used, but its at random, not always showing.
`[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "V:\MusicBot\musicbot\bot.py", line 2464, in on_message
    response = await handler(**handler_kwargs)
  File "V:\MusicBot\musicbot\bot.py", line 1866, in cmd_skip
    or author == player.current_entry.meta.get('author', None):
AttributeError: 'NoneType' object has no attribute 'meta'`

**Comment by AMNYST** [comment]
Hey , could you guys PLEASE , post a working one ?

This is what i'am having right now tried to paste it myself and tried the file giveen by @TimmyTheRat 

Without sucess

http://i.imgur.com/ZzhXLQF.png

**Comment by MeepCastana** [comment]
Its working. You have spacing errors. 
Since so many people have issues with indentation click here https://hastebin.com/pijetetuji.py

**Comment by AMNYST** [comment]
Guess i should say thanks , buuuut no :>

http://i.imgur.com/kd8LUgT.png

**Comment by MeepCastana** [comment]
Because you don't have "Review" branch. The command will not work on the normal version

**Comment by AMNYST** [comment]
Mh , i tried i swear.

File are identical and still

http://i.imgur.com/pilFgoe.png

**Comment by MeepCastana** [comment]
Send me  a ss. I wanna see the start of the command

**Comment by AMNYST** [comment]
Alright , well nevermind i got some progress.

http://i.imgur.com/Sv6oVLr.png

I can slove it alone , though when a new song start from the playlist the bot doesn't say anything :/

**Comment by MeepCastana** [comment]
Its a command. It doesn't show the message unless you call it

**Comment by MeepCastana** [comment]
If you are using notepad++ make sure this is enabled http://imgur.com/a/ViiIy

**Comment by AMNYST** [comment]
That was it thank you!

http://i.imgur.com/uCuNePF.png

**Comment by LunaChann** [comment]
I dont understand a thing o-o
