### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by Kinekai** [Just-Some-Bots/MusicBot#1249]
Basicly I was using the bot today when suddenly it stopped playing, i checked on it and the console said this 
![image](https://user-images.githubusercontent.com/30160518/28187696-8323aa00-6817-11e7-888e-0888bb33b801.png)
I tried to restart it, download the updates, download it again from the website.. but no luck.. any help ??

**Comment by jayktaylor** [comment]
This is a common Discord issue but may be helped by recent updates to the bot, so try updating and seeing if it helps.
