### ISSUE TITLE
Autoplaylist doesn't continue after failing to play a song

### ISSUE THREAD

**Issue by kminhc** [Just-Some-Bots/MusicBot#125]
Like when your bot is located in germany, and some videos are blocked by GEMA. The bot just outputs the error message in the console and stops autoplaylisting.

**Comment by imayhaveborkedit** [comment]
Is this with the develop version or the RC version?

**Comment by kminhc** [comment]
on the develop version

**Comment by imayhaveborkedit** [comment]
See if still happens on the RC version, it may have been fixed.

**Comment by kminhc** [comment]
Yep seems to be resolved in rc. Thanks.
