### ISSUE TITLE
OwnerID was not set

### ISSUE THREAD

**Issue by Svas88** [Just-Some-Bots/MusicBot#1253]
Hey...
I did everything good, and when I launch the runbot.bat, 
It says "OwnerID was not set"
....
What can I do ?
Thanks,
Maxime

**Comment by Zenrac** [comment]
In options.ini ensure you have write correctly your ID in OwnerID =

**Comment by BaiqingL** [comment]
Enable dev options, go and copy your own id and paste that number next to the OwnerID =

**Comment by sub-1337** [comment]
Had same problem, everything set just perfectly. Same error whether file exist and filled or not

**Comment by jayktaylor** [comment]
Can't reproduce this. Ensure that you have filled out options.ini correctly. Make sure it is not named options.ini.ini (file extensions may be hidden on your system).
