### ISSUE TITLE
Music bot wont play certain songs

### ISSUE THREAD

**Issue by Foresaw** [Just-Some-Bots/MusicBot#1255]
MY bot wont play certain songs like https://www.youtube.com/watch?v=m0TNW9ZHvuA
it just comes up with this error
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\jemjs\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\jemjs\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflL_WLGI/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflL_WLGI/en_US/base.js'",))

**Comment by MeepCastana** [comment]
![capture](https://user-images.githubusercontent.com/29717481/28252342-c4e2f9b2-6a99-11e7-9906-d985e81fc881.PNG)
works for me just fine. update dependencies

**Comment by Zenrac** [comment]
Same issue fixed after updating youtube-dl

**Comment by danfinlay** [comment]
Confirmed @zenrac's claim that updating fixed this on Ubuntu, using this command:

`pip install youtube-dl --upgrade`
