### ISSUE TITLE
Bot display offline, please

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1258]
can I say to the bot that it should be displayed as offline??? 

Sorry for my bad english

**Comment by Zenrac** [comment]
```
current_game = server.me.game if server is not None else None
await self.bot.change_presence(status=discord.Status.invisible, game=current_game)
```

Should change your bot's status to invisible , you can put that at the beggening of on_ready in bot.py

**Comment by alfredmak** [comment]
sorry replying an old thread, but it seems the current version does not support change_presence anymore, is there any other way to change the bot's status?

**Comment by jayktaylor** [comment]
@alfredmak update your bot, this should be fixed.
