### ISSUE TITLE
How to add multiple bot controllers

### ISSUE THREAD

**Issue by GourmetChef** [Just-Some-Bots/MusicBot#1259]
I've looked at the things in the files and readme's but  I still can't figure out how to make 2 people able to control the bots like !resume, !pause, and just every feature. Please help.

**Comment by IceViper04** [comment]
You have to edit the permissions.ini file in your music bot master folder. Click the link to get a guide on how to configure the permissions.ini file: [Click this blue text](https://github.com/Just-Some-Bots/MusicBot/wiki/Permissions) 

If you'r having any issues with the guide i sent you you can contact me on Discord, my name on discord is IceViper04#0970.
