### ISSUE TITLE
Bot won't search

### ISSUE THREAD

**Issue by ProfessorShroom** [Just-Some-Bots/MusicBot#126]
This is the error I get when I try to search with text: https://gyazo.com/a9a8acfa91cd096de2368183b4820925

**Comment by arunesh90** [comment]
use !search instead of !play

**Comment by imayhaveborkedit** [comment]
That won't work if you're using the develop version.  The new play command and search command are in the RC version.  If no one finds any more issues with that i'll merge it into develop in a day or two.
