### ISSUE TITLE
Doesn't work on Python 3.6

### ISSUE THREAD

**Issue by TahirMia** [Just-Some-Bots/MusicBot#1262]
Just installed Python 3.6 and noticed that this doesn't work.
3.5 is required

**Comment by IceViper04** [comment]
You have to download Python 3.5 from this link if your on Mac: [Python.org/versions/3.5.0](https://www.python.org/ftp/python/3.5.0/python-3.5.0-macosx10.6.pkg) or this one if your on Windows: [python.org/versions/3.5.0](https://www.python.org/ftp/python/3.5.0/python-3.5.0.exe)

**Comment by MeepCastana** [comment]
Review branch works with 3.6

**Comment by IceViper04** [comment]
The bot does not work in any versions of python 3.6 or later

**Comment by MeepCastana** [comment]
again 
Review branch works with 3.6

**Comment by junhui-f** [comment]
https://github.com/Just-Some-Bots/MusicBot/commit/7b38765b1ebce36467d3b895bda88d9e5baf2878

**Comment by TahirMia** [comment]
Seems to have worked.
