### ISSUE TITLE
Goes Offline upon shutdown of Sys32

### ISSUE THREAD

**Issue by DAVID47624** [Just-Some-Bots/MusicBot#1263]
Hello, team.
I just heard of this Github today, and I am glad I came along it.

Now, I have finished setting up the bot, it's in my server, had it play some songs and stuff. ```DisgraceBot#3014``` I set up the BOT on my PC, and I use my MacBook more than my PC. Whenever I'd close the System32, the bot would cut the music and go Offline. Is that normal? Must be PC always remain on on the System32 screen for it to stay Online and play music non-stop? 

Thanks!

**Comment by BaiqingL** [comment]
Um yes of course the PC must be on in order for the bot to keep running. I just use a headless Linux Server to host it instead. You just want to ensure that Python3 is running for Windows I guess....

**Comment by chuushi** [comment]
If you want to keep the music bot up, you must keep the machine with the bot on.

In addition, "System32" is not synonymous to "Windows 10" or "PC".  You don't "close" System32; it's just a directory that contains files that helps Windows run.
