### ISSUE TITLE
Feature Request. interaction on host.

### ISSUE THREAD

**Issue by Pesoen** [Just-Some-Bots/MusicBot#1264]
some way to interact with the bot on the host machine would be greatly appreciated. so i can send the shutdown, restart and stuff like that, using the interface we get to monitor the bot, or some separate interface. would be nice with some kind of control, without having to go through discord..

**Comment by jayktaylor** [comment]
This won't be added as this is purely a Discord bot. You can shutdown/restart by ending the process and starting it again.
