### ISSUE TITLE
Why does the bot save to disk?

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1265]
I was having a problem with the bot saving everything to disk. Is this necessary for the bot to work? I have to periodically clear the folder b/c it eats up so much disk space

**Comment by junhui-f** [comment]
in  

> options.ini


```
70   ; If no, delete videos after they've played, if the video
71   ; isn't still in the queue, to avoid redownloading it.
72   SaveVideos = yes
```

**Comment by Zenrac** [comment]
Btw by using ffmpeg you can avoid downloading the song. (!stream of the review branch)

**Comment by alessio-ds** [comment]
i can't install ffmpeg on ubuntu 14.04.
when i do `sudo apt-get install ffmpeg` it says it's obsolete or not found

any suggestions?

**Comment by dude22072** [comment]
@AlessioScarlet 
https://www.faqforge.com/linux/how-to-install-ffmpeg-on-ubuntu-14-04/
