### ISSUE TITLE
Python loading error

### ISSUE THREAD

**Issue by PepeQuaza** [Just-Some-Bots/MusicBot#1267]
It will not let me play a youtube song using link or name 

Heres the message -

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Guy\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1070, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Guy\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 958, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflGD0HaZ/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflGD0HaZ/en_US/base.js'",))

Any help would be apreciated 👍

**Comment by MeepCastana** [comment]
update your dependencies

**Comment by PepeQuaza** [comment]
@TimmyTheRat sorry, whats a dependencie?

**Comment by MeepCastana** [comment]
![capture](https://user-images.githubusercontent.com/29717481/28498373-a67d73ac-6fa4-11e7-9443-b94b21e97287.PNG)
its in your bot folder
