### ISSUE TITLE
Permissions are not working ?

### ISSUE THREAD

**Issue by MeepCastana** [Just-Some-Bots/MusicBot#1268]
So i tried to disable a command for a specific user but it didn't work. 
![capture](https://user-images.githubusercontent.com/29717481/28491961-7e89b984-6f02-11e7-8b26-edacec5744f7.PNG)
![capture](https://user-images.githubusercontent.com/29717481/28491969-a080ff98-6f02-11e7-8886-17f863719b9e.PNG)

The dude was able to skip the song even tho he had no permissions

**Comment by IceViper04** [comment]
Try removing the semicolon (;) before the GrantToRoles text.

**Comment by MeepCastana** [comment]
I used UserList

**Comment by MeepCastana** [comment]
Tried GrantToRoles and didn't work

**Comment by IceViper04** [comment]
Can u send me your permissions.ini so I can help you further? @TimmyTheRat

**Comment by MeepCastana** [comment]
Its old. I don't need help anymore
