### ISSUE TITLE
How can i add a Playlist?

### ISSUE THREAD

**Issue by Trentox** [Just-Some-Bots/MusicBot#1269]
Hello,
i already put my music which i want to play in the autoplaylist.txt file.
But the Bot playes random music. It doesn't play the music in a order.
How can i fix this.
Please help me.
Thank you!

PS: Sorry for my terrible english :(

**Comment by sypion** [comment]
The bot shuffles whatever is in the `autoplaylist.txt` file.

**Comment by Trentox** [comment]
Okay thank you ^^

**Comment by Zenrac** [comment]
See #964 to 'fix' it, but it keeps random
