### ISSUE TITLE
No Module Named 'Music Bot'

### ISSUE THREAD

**Issue by MingjoFiox** [Just-Some-Bots/MusicBot#127]
Iv followed the instructions left by SexualRhinoceros's Music Bot for Discord. But after running the bot check "runbot" this happened. 
![2016-03-01](https://cloud.githubusercontent.com/assets/17584504/13450411/098d0e4a-e003-11e5-8839-ed5101cefd6a.png)
![2016-03-01 1](https://cloud.githubusercontent.com/assets/17584504/13450420/163e2c3c-e003-11e5-8aaf-90fc5ea3d03d.png)
I'm not sure weather I had somehow made a mistake in following the instructions procedures or its an error. Help in this issue is much appreciated.

**Comment by imayhaveborkedit** [comment]
Can you post a picture of your musicbot folder?

**Comment by MingjoFiox** [comment]
![2016-03-02](https://cloud.githubusercontent.com/assets/17584504/13472946/2a71bdc2-e085-11e5-9c9b-2211dd864bd2.png)
![2016-03-02 1](https://cloud.githubusercontent.com/assets/17584504/13472954/2d28b02a-e085-11e5-985e-184fb2a65f65.png)
In the second picture I had changed the "Example_Options" to options.ini

**Comment by imayhaveborkedit** [comment]
You have extracted the bot incorrectly.  I don't know what Zip Opener is, or why you need it, but all you need to do is extract the contents of the zip file to a folder.  There should be a folder called `musicbot` with a bunch of `.py` files in it.  That's the bot's code.  That folder should be in the folder with all the other files shown there.

**Comment by MingjoFiox** [comment]
I used a different method to open the zip file which solved the No Module Named issue. Thanks for the help @imayhaveborkedit
