### ISSUE TITLE
RuntimeError: Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib

### ISSUE THREAD

**Issue by ThePortalMaster** [Just-Some-Bots/MusicBot#1270]
I've seen this happen to other people but they were fixed by installing opus. Well I have opus installed and still get the same problem. 
<img width="566" alt="screen shot 2017-07-24 at 12 11 32 pm" src="https://user-images.githubusercontent.com/30416995/28538341-34047dee-706b-11e7-8b56-f5c61c0d1e2e.png">
<img width="343" alt="screen shot 2017-07-24 at 12 11 21 pm" src="https://user-images.githubusercontent.com/30416995/28538335-2e491ff4-706b-11e7-9793-3785dc39d64f.png">

**Comment by alessio-ds** [comment]
Fixed by doing
`cd <your music bot folder>`
`cp /usr/lib/*/libopus.so.0 .`

**Comment by discolight99** [comment]
i had the same problem but when i do what you told him it said this 
cp: /usr/lib/*/libopus.so.0: No such file or directory

**Comment by alessio-ds** [comment]
my command has a dot at the end of it. 
are you sure you wrote it with the dot?

**Comment by discolight99** [comment]
i copy and pasted it

**Comment by discolight99** [comment]
-MacBook-Pro:MusicBot-master 
$ cp /usr/lib/*/libopus.so.0 .
cp: /usr/lib/*/libopus.so.0: No such file or directory

**Comment by discolight99** [comment]
<img width="984" alt="screen shot 2017-07-31 at 09 00 18" src="https://user-images.githubusercontent.com/22660633/28768226-be809026-75ce-11e7-9c5e-6d266fc2b34e.png">

**Comment by alessio-ds** [comment]
try this
`sudo apt-get update`
`sudo apt-get upgrade`
`sudo apt-get install libopus0`

then

`cd <your music bot folder>`
`cp /usr/lib/*/libopus.so.0 .`

**Comment by discolight99** [comment]
<img width="238" alt="screen shot 2017-08-01 at 01 34 42" src="https://user-images.githubusercontent.com/22660633/28804204-a3271062-7659-11e7-94c5-4e5f88f6c023.png">

**Comment by alessio-ds** [comment]
then try all the commands but without `sudo`

**Comment by discolight99** [comment]
<img width="242" alt="screen shot 2017-08-02 at 00 31 02" src="https://user-images.githubusercontent.com/22660633/28851373-e9ad1886-7719-11e7-815b-8993a61373bd.png">

**Comment by discolight99** [comment]
hello and i looked up the sudo command and it is for ubuntu and i am on a mac

**Comment by alessio-ds** [comment]
use the mac command then

**Comment by discolight99** [comment]
do you know what it is?

**Comment by alessio-ds** [comment]
i think it's `yum -code here-`
