### ISSUE TITLE
Youtube live

### ISSUE THREAD

**Issue by M0RC** [Just-Some-Bots/MusicBot#1271]
Hi, Can I play youtube live?

**Comment by Zenrac** [comment]
Yes use !stream from the review branch.

**Comment by M0RC** [comment]
Ok thanks !

**Comment by IRONJJ** [comment]
Where can i find the review branch ?

**Comment by codc3** [comment]
Where can i find the review branch ?

**Comment by chuushi** [comment]
Use `git checkout review` if using git. If downloading:

![image](https://user-images.githubusercontent.com/13530989/29429871-2d59779e-8360-11e7-8ec2-cda58da7ec10.png)

Then download it.

**Comment by jayktaylor** [comment]
This is now supported in master, but may not be fully functional.
