### ISSUE TITLE
Feature Request: Bot leaves server on command.

### ISSUE THREAD

**Issue by sypion** [Just-Some-Bots/MusicBot#1273]
For example, if I, the owner of my self-hosted music bot, uses a command like `!leaveserver`, the bot will leave the server until someone re-invites it using the OAthu2 link.

I think it would be a neat idea-- thanks in advance!

**Comment by MeepCastana** [comment]
umm isn't kick an option ?

**Comment by sypion** [comment]
@TimmyTheRat What if I don't have server permissions to kick a user/bot? I'd rather have the ability as the owner myself to get rid of my bot on any server it's on.

**Comment by MeepCastana** [comment]
async def cmd_leaveserver(self, id):
        """
        Usage:
            {command_prefix}leaveserver <id>
        Removes the bot from a specific server via ID
        """
        target = self.get_server(id)
        if target is None:
            raise exceptions.CommandError('The server {} does not exist'.format(id), expire_in=30)
        else:
            await self.leave_server(target)
            return Response("Left server successfully: {0.name} ({0.id})".format(target))

**Comment by MeepCastana** [comment]
if u wanna restrict this command to the owner of the bot add this at the beginning @owner_only

**Comment by sypion** [comment]
Ah, yes. Bless your soul. 

Thank you!

**Comment by sypion** [comment]
@TimmyTheRat Oh quick side question, how will I know the server ID if I'm not in the server?

**Comment by sypion** [comment]
Never mind, I can just look at the `server_names.txt` file under the `data/` folder.

**Comment by Zenrac** [comment]
You can also leave one with his name : (args is your search)
`server = discord.utils.find(lambda s: s.name == args, self.servers)`
