### ISSUE TITLE
ffmpeg/avconv was not found in your PATH environment variable

### ISSUE THREAD

**Issue by alessio-ds** [Just-Some-Bots/MusicBot#1275]
The **MAIN** problem is that when I do `apt-get install ffmpeg` , this happens

root@alessiosca:~/musicbotto# apt-get install ffmpeg
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package ffmpeg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ffmpeg' has no installation candidate

**causing this:**

![image](https://user-images.githubusercontent.com/16420921/28741674-07c8a94e-741c-11e7-82bc-58279bc72850.png)

**Comment by jayktaylor** [comment]
`sudo apt-get install libav-tools` may work, see https://askubuntu.com/questions/432542/is-ffmpeg-missing-from-the-official-repositories-in-14-04.
