### ISSUE TITLE
Suggestion.

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1276]
Sorry to post this as an issue.

I was wondering if it was possible to seperate bot commands with newlines.

e.g.

    !play Test1
    !play Test2

Would queue Test1, then queue Test2.

**Comment by jadedtdt** [comment]
I've been working on something similar, but haven't quite figure it out without a lot of redundant code. I too would really appreciate this!

**Comment by ghost** [comment]
Closing this issue as I'm pretty sure it's a problem with the discord API and not the bot.
The discord api uses callbacks per command, instead of giving you a string with the full message.
