### ISSUE TITLE
[Suggestion, not an issue] Loop song

### ISSUE THREAD

**Issue by aidowalnut** [Just-Some-Bots/MusicBot#128]
type !loop to loop the currently playing song until either the bot owner executes !endloop or the server votes on it.

**Comment by imayhaveborkedit** [comment]
Something like that is coming with local playlists.

**Comment by ChristophHenckens** [comment]
I really need exactly that feature! :) Is there maybe an ETA?

**Comment by Pre1** [comment]
hmmmm this suggestion was in 2016 and still not implemented? or have I miss something?

**Comment by Pre1** [comment]
should I file another suggestion for a `loop queue` cmd?

**Comment by MattBSG** [comment]
It means no one has PRed a feature for this and that development was inactive for most of 2017. Please feel free to submit a PR if you make your own

**Comment by ImLunaUwU** [comment]
@imayhaveborkedit Is this still planned?
