### ISSUE TITLE
The search command isn't functioning properly.

### ISSUE THREAD

**Issue by sypion** [Just-Some-Bots/MusicBot#1284]
Maybe I'm doing something wrong, or maybe I'm not.

Upon using the command and the bot responds with the first video relevant to my query, if I either say `y` or `n`, the bot deletes its message and doesn’t do anything else. It’s like I told it to `exit` but not intentionally. Nothing pops in the command prompt as well.

**Comment by MeepCastana** [comment]
any errors?

**Comment by sypion** [comment]
If there was an error I would have solved it myself 😆

**Comment by sypion** [comment]
Found the issue; the bot won't continue searching if you have no prefix set. Using the `Review` branch by the way. If anyone happens to find a solution to this, that'd be great!

**Comment by jayktaylor** [comment]
We don't recommend or support using the bot without a prefix.
