### ISSUE TITLE
Can bot keep on active when i'm offline? Please HELP!!!

### ISSUE THREAD

**Issue by aryramadhans** [Just-Some-Bots/MusicBot#1286]
And what is the command? tell me please master.

**Comment by chuushi** [comment]
You need to host the bot on a computer or VPS that does not shut down.

[Duplicate of #1263 #1051 #458 ]

**Comment by 0x78f1935** [comment]
I have a modified version running on a server, if you are interested message me. You can view the source code on my github page.

**Comment by tilda** [comment]
@aryramadhans You cannot do that unless you get a VPS/Raspberry Pi/a 24/7 computer.
