### ISSUE TITLE
Error when starting bot.

### ISSUE THREAD

**Issue by sypion** [Just-Some-Bots/MusicBot#1287]
For some reason when I start `runbot.bat`, it starts throwing this error and saying the bot cannot join the channel when indeed, it's in the voice channel upon startup. This happens again when trying to use a command and just says, "The bot is not in a voice channel. Use !summon to summon it..."

Here's the error:

```python
[ERROR:bot] Failed to join Safehouse/Jukebox
[ERROR:bot] Exception in on_voice_state_update
Traceback (most recent call last):
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Chris\Documents\Music Bot\musicbot\bot.py", line 2895, in on_voice_state_update
    player = await self.get_player(state.my_voice_channel)
  File "C:\Users\Chris\Documents\Music Bot\musicbot\bot.py", line 564, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use -summon to summon it to your voice channel.

**Comment by 0x78f1935** [comment]
Look @ your error `musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use -summon to summon it to your voice channel.`

If you linked your bot to a text channel just type !summon in that text channel. You can bind the bot to a channel in the config/option file. You need to be in a voice channel as you use this command. Aswell a voice channel can be autobind in the config file.

**Comment by sypion** [comment]
The issue is that it's already connected to a voice channel, and if I try to use any command, it says it has to be summoned.
