### ISSUE TITLE
When using "!help", only list the commands the user currently has permission for

### ISSUE THREAD

**Issue by Ivoz** [Just-Some-Bots/MusicBot#129]
Hopefully the title is self explanatory.

Or, alternatively, give the commands the user has permission for in a first line, and the ones they don't in a second line.

**Comment by imayhaveborkedit** [comment]
Yeah yeah I know, the current help command is just sort of a place holder until I make a proper one.  The old was was literally just a link to the commands page.

**Comment by MattBSG** [comment]
This has been introduced in #1495 and was merged to review. It will be included in the next release. Gonna go ahead and close.
