### ISSUE TITLE
Allow controlling bot through command line

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1291]
Would it be possible to implement a feature to let the bot be controlled via command line?
If running in a bot account it would be necessary to specify the server to act on. Would be useful if you wanted to schedule commands to run, or order it around via fifo file or bash

**Comment by IceViper04** [comment]
It'l take a load off time to imploment a feature like that and the thing is that if they imploment one off these features it'l just be a waste of time becuase there is already a working way to control the bot dirrectly from Discord chat! I understand that there may be some positives to implomet a feature lime this but it's just a waste of time for the contributers/developers.

**Comment by jayktaylor** [comment]
This won't be added to the bot because of complications that would arise from trying to do this.
