### ISSUE TITLE
MusicBot

### ISSUE THREAD

**Issue by SeriouslyKnowNothing** [Just-Some-Bots/MusicBot#1292]
Hi All

Serious noob to coding and working my way around some aspects of software. Own and manage a discord server and got the amazing MusicBot to work.

Only thing I would like to know is how to load a playlist at startup instead of the bots random searches. Would preffer a set youtube playlist.

Thanks in advance

**Comment by Xylems** [comment]
Thats easy, the bot doesnt do a random search is has an autoplaylist.txt file in the config location with about 6000 some odd songs to start with

Also, people here get a little uppity about answering questions that are plain and simple in the comments. If you found out how to enable auto play list you skipped the comment that tells you where to pull it from.

Let me know if you have more questions i have been running 6 bots now for about 3 months.
