### ISSUE TITLE
TabError when trying to add new commands

### ISSUE THREAD

**Issue by xDxS** [Just-Some-Bots/MusicBot#1298]
Every time I try to add a new simple ping pong command i get TabError: inconsistent use of tabs and spaces in indention

![capture2](https://user-images.githubusercontent.com/30963071/29244246-6cd2a9aa-7f81-11e7-8a68-c5431a701901.PNG)

![capture](https://user-images.githubusercontent.com/30963071/29244243-49e405f6-7f81-11e7-8cd9-d3b774638a84.PNG)

I was using the example pong command found here https://gist.github.com/jaydenkieran/8cf64f91fec73ba0bd127a08f6578988

**Comment by chuushi** [comment]
Python is tab/space sensitive.  Make sure the indentation is proper.

basically, the `async def cmd_ping(self);` line is two tabs higher than it should be.

**Comment by MeepCastana** [comment]
also use this if u want an actual ping command - credits to @zenrac

    async def cmd_ping(self, channel):
        """
        Usage:
            {command_prefix}ping
        Displays the ping
        """
        start = time.time()
        msg = await self.safe_send_message(channel, "Pong!")        
        end = int((time.time() - start)*1000)
        return await self.edit_message(msg, "Time taken! **%sms**" % end

**Comment by Zenrac** [comment]
Thx for the credits, btw, I've made the same command by using timestamp instead.
```
    async def cmd_ping(self, message, channel):
        """
        Usage:
            {command_prefix}ping
        Displays the ping
        """
        msg = await self.safe_send_message(channel, "Pong!")        
        ms = int(float(str(msg.timestamp - message.timestamp)[-9:])*1000)
        return await self.edit_message(msg, "Pong ! **%sms**" % ms)  
```
Hope it can be helpful

**Comment by xDxS** [comment]
Thanks for the help! :3
