### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by Esp10n** [Just-Some-Bots/MusicBot#1299]
Hey guys,

Musicbot doesn't seem to work for me no idea why... not getting any issues on cmd connects fine says song downloaded complete and it says song is now playing but I hear nothing and the musicbot doesn't have the green circle around it... i used the update file as well everything is updated...

Requirement already up-to-date: discord.py[voice]~=0.12.0 in c:\users\imad\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: youtube_dl in c:\users\imad\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: pip in c:\users\imad\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: cffi==1.6.0 in c:\users\imad\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: aiohttp<1.1.0,>=1.0.0 in c:\users\imad\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: websockets<4.0,>=3.1 in c:\users\imad\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: PyNaCl==1.0.1 in c:\users\imad\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: pycparser in c:\users\imad\appdata\local\programs\python\python35\lib\site-packages (from cffi==1.6.0->-r requirements.txt (line 4))
Requirement already up-to-date: chardet in c:\users\imad\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: async-timeout in c:\users\imad\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: multidict>=2.0 in c:\users\imad\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: six in c:\users\imad\appdata\local\programs\python\python35\lib\site-packages (from PyNaCl==1.0.1->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))

No idea whats going on...

**Comment by IceViper04** [comment]
You might not have given the bot the correct permissions in the specified channel.

**Comment by Esp10n** [comment]
But it has been working for several months on the same channels... it doesn't make sense to me and I haven't touched the text file for musicbot in ages...

**Comment by ghoch04** [comment]
@Esp10n I found the issue for me.  What is happening is, the song is getting added to the queue, so it is sitting as the next song.  So I am guessing you paused the auto queue, then typed "!play URL".  This does add it to the queue.  But because you have the current song paused it never plays.

Try resuming the song then, using !skip.  This will skip to next in queue, aka the song that you added to queue with !play.

I simply just put in my own !playnow command to fix this.  I like an option of playing a song right way.
