### ISSUE TITLE
Bot cannot switch between servers

### ISSUE THREAD

**Issue by dsmaugy** [Just-Some-Bots/MusicBot#130]
The bot cannot switch between servers for me. If it is a voice channel of one server and I go to another server that the bot is connected to and do !summon while in the voice channel of that server, it gives me an error: http://puu.sh/nzIGF/0725475e91.png

The only way to fix this is to close the bot, join the server I want it to join, and have the bot auto-summon to me. Once it joins a server, it is hard anchored to that server until I restart.

**Comment by imayhaveborkedit** [comment]
This is noted on the `!summon` entry on the commands page.  Proper multiserver support will come after the discord api allows for it.
