### ISSUE TITLE
Music Bot wont display what song is playing.

### ISSUE THREAD

**Issue by Foxtrot1823** [Just-Some-Bots/MusicBot#1304]
Didnt change any scripts woke up and saw it isnt working. Dont know what to do :(

I am talking about on their name in discord in will usually say
Bot name
now playing : blah blah blah

it doesnt display now playing

**Comment by finalchance531** [comment]
Same here. I have no clue.

**Comment by pedroricardo** [comment]
It's the same here, too.
Any general bug ??

**Comment by rafaelwastaken** [comment]
IIRC from what I read in the Discord API server, something changed today and now requires you to specify type=0 when changing the playing status. This is most likely why this is no longer working.

**Comment by pedroricardo** [comment]
Where should this modification be done? @fofofofofofofofoXD 

`    async def update_now_playing_status(self, entry=None, is_paused=False):
        game = None

        if self.user.bot:
            activeplayers = sum(1 for p in self.players.values() if p.is_playing)
            if activeplayers > 1:
                game = discord.Game(name="music on %s servers" % activeplayers)
                entry = None

            elif activeplayers == 1:
                player = discord.utils.get(self.players.values(), is_playing=True)
                entry = player.current_entry

        if entry:
            prefix = u'\u275A\u275A ' if is_paused else ''

            name = u'{}{}'.format(prefix, entry.title)[:128]
            game = discord.Game(name=name)

        async with self.aiolocks[_func_()]:
            if game != self.last_status:
                await self.change_presence(game=game)
                self.last_status = game
`

**Comment by rafaelwastaken** [comment]
Change the following things: 
`game = discord.Game(name="music on %s servers" % activeplayers)` to 
`game = discord.Game(type=0, name="music on %s servers" % activeplayers)`
and also change
`game = discord.Game(name=name)` to 
`game = discord.Game(type=0, name=name)`

**Comment by pedroricardo** [comment]
Thank you very much! 

Already we are talking about the subject, how to implement this feature in MusicBot? @fofofofofofofofoXD 

![image](https://user-images.githubusercontent.com/25847896/29391630-f23a08d6-82ce-11e7-95f9-04f0733b7339.png)

**Comment by rafaelwastaken** [comment]
@pedroricardo That's type=1. Pretty easy to do, you have to change
`game = discord.Game(name="music on %s servers" % activeplayers)` to
`game = discord.Game(type=1, url=<insert twitch url here>, name="music on %s servers" % activeplayers)` and also change
`game = discord.Game(name=name)` to
`game = discord.Game(type=1, url=<insert twitch url here>, name=name)`

also, it only accepts twitch.tv urls, if you try to add a non-twitch link it will display a normal playing status.
![image](https://user-images.githubusercontent.com/26192097/29391974-c942fbfa-82c8-11e7-9630-99ee2861fdbe.png)

**Comment by pedroricardo** [comment]
Thank you very much!

**Comment by Foxtrot1823** [comment]
AWESOME thank you so much!

**Comment by IceViper04** [comment]
How do you open and edit the document you told to change a few lines in? @fofofofofofofofoXD

**Comment by rafaelwastaken** [comment]
@IceViper04 Since your only adding type=0 to two lines, something as simple as Notepad++ would probably work.

**Comment by FatRagdoll** [comment]
@fofofofofofofofoXD What file are we referring to?

**Comment by IceViper04** [comment]
@FatRagdoll they are refering to the bot.py file.

**Comment by jayktaylor** [comment]
Updating discord.py should fix this. Update the bot and then update the dependencies.
