### ISSUE TITLE
 Number of servers

### ISSUE THREAD

**Issue by codc3** [Just-Some-Bots/MusicBot#1305]
Is there a command that shows the number of servers the bot is on?

**Comment by MeepCastana** [comment]
Your bot status will change to "Playing music on x servers"

**Comment by codc3** [comment]
@TimmyTheRat 
Yes, but it shows only the servers where the bot is playing some music on the voice channel!

I wanted the general amount of servers, even the servers where the bot is idle

**Comment by MeepCastana** [comment]
what branch are you using

**Comment by codc3** [comment]
master

**Comment by MeepCastana** [comment]
I think the bot shows you when you start it the Server List 
![capture](https://user-images.githubusercontent.com/29717481/29413190-32c1a662-8364-11e7-8132-d81686537bd9.PNG)

**Comment by codc3** [comment]
Yes it shows but you will have to restart every time you want to see the servers, and if they are many it gets difficult;

**Comment by MeepCastana** [comment]
If you restart it once you get the full list

**Comment by MeepCastana** [comment]
+ you can always scroll up

**Comment by codc3** [comment]
As I run my bot on a vps this list adds up as the bot logs appear

**Comment by MeepCastana** [comment]
🙁 damn

**Comment by Zenrac** [comment]
We're not supposed to answer to that type of question : 
See: https://github.com/Just-Some-Bots/MusicBot/wiki/Modification#support
The discord.py doc: http://discordpy.readthedocs.io/en/latest/api.html
And if you need help with the lib you can go on the discord api server: https://discord.gg/discord-api

To answer you, you can get your servers with ``self.servers`` 
Simply create a command with: 
`return Response("I'm currently on %s servers" % len(self.servers))`
