### ISSUE TITLE
Not recognizing/noticing other files?

### ISSUE THREAD

**Issue by Cold-Stream** [Just-Some-Bots/MusicBot#1306]
When I try to follow the directions of the installation guide (here-https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Windows)

I find problems near the end of the guide when I run update_deps.bat it errors and looks like this http://i.imgur.com/rrmyCZC.png

So that confuses me so maybe im dumb and I've done it previously? Probably not. 

Next I run runbot.bat and get this http://i.imgur.com/rk60Jhs.png where it doesnt recognize the run.py but this may be an error because the previous step hasnt completed?

is the "Does not support UNC paths" Etc. the problem?

**Comment by Zenrac** [comment]
You have to cd to your path before open the update_deps or run.bat

**Comment by Cold-Stream** [comment]
Sorry, I am pretty inept at console commands, how I would be able to do that?

**Comment by Zenrac** [comment]
type : `cd complete/path/to/the/file`
the file that i'm talking about is the file that contains config musicbot run.py etc

**Comment by jayktaylor** [comment]
You're trying to run the bot from a UNC path, such as a network path. Please try and put it in a local directory instead.
