### ISSUE TITLE
Soundcloud not working

### ISSUE THREAD

**Issue by Flumess** [Just-Some-Bots/MusicBot#1307]
Whenever i try to play a song from soundcloud the bot starts typing, then it stops and doesn't play the song. This has happened for at least a month

**Comment by Flumess** [comment]
This is the message it sends about 2 minutes later 

```
[0;31mERROR:[0m Unable to download JSON metadata: HTTP Error 504: Gateway Time-out (caused by <HTTPError 504: 'Gateway Time-out'>)
```

**Comment by rafaelwastaken** [comment]
Your IP address has been blocked from Soundcloud. I've recently seen other people say they also got their IP blocked, presumably for downloading too many songs with youtube-dl. (https://www.reddit.com/r/DataHoarder/comments/6t5nxg/soundcloud_blocking_my_home_ip/)

If you don't have a static IP, try seeing if you can force an IP change.

**Comment by Flumess** [comment]
my ip isnt banned from soundcloud. I am able to use it all the time from the website. I run my bots on a VPS and we havent been able to use it for a month. Its nothing to do with running it off my computer

**Comment by rafaelwastaken** [comment]
Try accessing the site with curl on your VPS and see what happens, if it gives the same error then your VPS' IP is most likely blocked, not your home IP.

**Comment by jayktaylor** [comment]
Not an issue with our bot.
