### ISSUE TITLE
I can't run the bot

### ISSUE THREAD

**Issue by ratkinq** [Just-Some-Bots/MusicBot#1311]
I followed the guide [here](https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Windows) step for step and everything seems fine until I hit runbot.bat, the command window pops up for a second then dissapears and my bot will not come online when I try to use the commands with it. I've uninstalled and reinstalled everything, redoing the whole process, twice and i'm still having this issue, can anybody help?

**Comment by xxczaki** [comment]
open `runbot.bat` as Admin
