### ISSUE TITLE
Bot Stopped Playing and Couldn't Start Songs

### ISSUE THREAD

**Issue by acollierr17** [Just-Some-Bots/MusicBot#1312]
About 10 minutes from posting this issue our bot simply stopped playing and new songs couldn't be played from the queue. I was notified a few minutes later about it and saw console threw some here. However, the issue fixed itself but I do feel it could happen again. Link to the console log: https://hastebin.com/xohefoyaza.vbs

**Comment by jayktaylor** [comment]
I've just pushed an update for the bot, see if that makes any difference to help combat these problems.
