### ISSUE TITLE
Bot Lags in discord

### ISSUE THREAD

**Issue by shivia** [Just-Some-Bots/MusicBot#1314]
The bot lags extremely bad in discord. Music downloads and plays. but there is lag.
Will randomly stop and skip songs.. slows down and speeds up.
Is this happening to anyone else? 

How do you fix this? I did edit the text file in order to have the "now playing function" to work again. Is that causing the issue?
Did a speed test and my internet connection is fine.

**Comment by MeepCastana** [comment]
Might be your pc
