### ISSUE TITLE
bot clicks ip grabber links(fix)

### ISSUE THREAD

**Issue by toxicRavioli** [Just-Some-Bots/MusicBot#1320]
I have a very fooking ugly fix, here it is (not all ip grabber links are in it but a sh*t ton of them are)

`        if song_url.startswith('https://grabify.link'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://grabify.link'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('https://goo.gl/'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://goo.gl/'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('grabify.link'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('goo.gl/'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('bmwforum.co'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('leancoding.co'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('quickmessage.io'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('spottyfly.com'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('stopify.co'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('yoütu.be'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('yoütübe.co'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('yoütübe.com'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('xda-developers.io'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('starbucksiswrong.com'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('starbucks.bio'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('starbucksisbadforyou.com'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('bucks.as'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('discörd.com'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('minecräft.com'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('shört.co'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://bmwforum.co'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://leancoding.co'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://quickmessage.io'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://spottyfly.com'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://stopify.co'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://yoütu.be'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://yoütübe.co'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://yoütübe.com'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://xda-developers.io'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://starbucksiswrong.com'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://starbucks.bio'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://starbucksisbadforyou.com'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://bucks.as'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://discörd.com'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://minecräft.com'):
            return Response("plz dont try to grab my ip its pathetic :joy:")

        if song_url.startswith('http://shört.co'):
            return Response("plz dont try to grab my ip its pathetic :joy:")`

this is where you put this code http://prntscr.com/ggrnsk right under song_url = song_url.strip('<>')

now listen, i know its ugly but if youre so smart give me another fix

**Comment by rafaelwastaken** [comment]
Jesus christ... So many if statements lmfao

**Comment by toxicRavioli** [comment]
@fofofofofofofofoXD :joy:

**Comment by MistChristmas** [comment]
If your so paranoid, just have YouTube links the only thing it accepts.
