### ISSUE TITLE
Cannot establish connection to voice chat.  Something may be blocking outgoing UDP connections.

### ISSUE THREAD

**Issue by borgqueenx** [Just-Some-Bots/MusicBot#1322]
What UDP Port do i allow for this to work? 
I already tried disabling the firewall and that fixed my problems, but i need to know what port to allow so the bot stays working.

**Comment by Alloc86** [comment]
Yeah, would be nice if the ports used where specified somewhere so one can actually properly configure the firewall :)

**Comment by jayktaylor** [comment]
There is no set port, connection to Discord uses various different ports. Easiest solution is to allow all outgoing UDP connections.
