### ISSUE TITLE
Unable to start bot on raspberry pi due to missing aiohttp

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1327]
Hello, followed the guide on how to install the bot on raspbian and I think I missed something.

When I run the bot, it kicks out an error saying that it could hot find the aiohttp repository.
Here is a screenshot: https://i.imgur.com/prs5tww.png

How do I get aiohttp?

**Comment by Chanteyousei** [comment]
I see that you are attempting to use python 3.4, try updating it to 3.5 and then see if that works.

**Comment by ghost** [comment]
Am using python 3.5.

**Comment by HyperGaming18** [comment]
Try this.


pip install python-aiohttp
or
pip install aiohttp

( Ubuntu 16.04 )

apt-get install aiohttp

**Comment by ghost** [comment]
@HyperGaming18 aiohttp is already installed (https://i.imgur.com/VOI5YsA.png)

I might try a new install if I have too.

**Comment by xFoxx** [comment]
Same exact issue here, I'm starting to think it's because the FFmpeg installation screwing up at some point...

**Comment by jayktaylor** [comment]
It looks like you're using multiple versions of Python, including 3.4. The bot only supports 3.5 and higher, so this may be causing issues. Your pip command seems to be installing the dependencies for 3.4, not 3.5.
