### ISSUE TITLE
Bot playing status

### ISSUE THREAD

**Issue by Alex-Thunderhunter** [Just-Some-Bots/MusicBot#1328]
Are you guys planning on adding the ability to say "Playing: Song name" as what it's playing, or is that a side modification that one would have to do?

![e0c7aa6f10ca3d3f39bfc4ece5ea690b](https://user-images.githubusercontent.com/25190612/30243288-009e9874-956c-11e7-8d26-c973986d6efc.png)

**Comment by MeepCastana** [comment]
The bot already does that

**Comment by gnuttenx** [comment]
My bot has stopped showing this, not sure if Discord has made some changes in update.

**Comment by Chanteyousei** [comment]
Probably something to do with the version of Discord API the musicbot uses being really out of date. I managed to fix it, by going to requirements.txt and removing the "-= 0.12.0" line that keeps the Discord API at version 0.12.0. Then running update_deps.bat(or the relevant pip command in linux) to update the discord.py to 0.16.0. This fixes it, but will throw out a change_status being deprecated warning. You can ignore this.

However, If that warning bugs you and are confident in editing python files, you can open bot.py in Notepad++ or something, then change "await self.change_status(game)" at line 467 to "await self.change_presence(game=game)"

**Comment by MeepCastana** [comment]
If you're running the default version, update requirements to discord.py v16.9. If you have review version add type=0 to the command

**Comment by Alex-Thunderhunter** [comment]
Okay, will do. Thank you.

**Comment by Alex-Thunderhunter** [comment]
That worked, Thank you guys.
