### ISSUE TITLE
add !undo command

### ISSUE THREAD

**Issue by shrx** [Just-Some-Bots/MusicBot#133]
If someone changes his mind or the bot finds a wrong song, it would be useful to have an `!undo` command. It should work only if there is more than one item stored in the queue, and remove the last queued item from the queue immediately. The permissions for the command should be: bot's owner and last song's author.

**Comment by shrx** [comment]
Probably a duplicate (or a special case of) #91

**Comment by imayhaveborkedit** [comment]
I was considering giving whoever queued a song additional permissions related to that song but I still haven't decided on it yet.

**Comment by imayhaveborkedit** [comment]
Additionally, this requires the bot to track state, or at least a history of songs.  It's not something super simple to add, but not impossible.
