### ISSUE TITLE
Skip only your queued tracks

### ISSUE THREAD

**Issue by 0XE4** [Just-Some-Bots/MusicBot#1335]
Is it possible to make the skip command instantly skip the currently playing track if the person who runs the skip command also queued the track?  

This way people who want to skip a song they added don't have to wait for others to vote on it.

**Comment by jayktaylor** [comment]
This is not currently a feature of the bot but you're welcome to modify it to do this. We don't provide support for modification here though, this is only a place for actual bugs and problems.
