### ISSUE TITLE
Python has either not been installed or not added to your PATH.

### ISSUE THREAD

**Issue by JAVENINSJ** [Just-Some-Bots/MusicBot#1336]
ERROR: Python has either not been installed or not added to your PATH. was the error i got from trying to launch the runbot file. I think i did everything right and didnt mess anything up, BUT knowing my self i probobly did. So if you have even the smallest idea about how is this fixable please dont be afraid to help.

**Comment by HyperGaming18** [comment]
Try this.


cd /path/to/directory

python run.py


Then the bot should run correctly. let me know i'll try help.

**Comment by Chanteyousei** [comment]
I assume that you are using Windows, You need to edit the "path" variable in Environment Variables.
https://superuser.com/questions/143119/how-to-add-python-to-the-windows-path

**Comment by JAVENINSJ** [comment]
Worked! Thanks hypergaming18
