### ISSUE TITLE
modify bot to respond

### ISSUE THREAD

**Issue by loobing** [Just-Some-Bots/MusicBot#1339]
async def cmd_greet(self):
        greet2 = input("hello")
            if(greet2 == "hello"):
                return response ("how are you doing")

i just kinda started coding help me out pls how am i suppose to make it respond if somebody else says hello

**Comment by mixieculez** [comment]
input() is a built-in function that creates a prompt in console. If you want to make a greet function for Discord members, I recommend that you find a way to pull discord messages and set an if-then statement that way. Also, `cmd_` makes it visible as a command in [p]help and therefore means that it would only work if it was invoked by someone as [p]greet. Make it only `async def greet(self)`.

**Comment by MeepCastana** [comment]
if message.content.startswith('hello'):
            await self.send_message(message.channel, 'how are you doing')

under on_message

**Comment by loobing** [comment]
Doesnt that means when the bot join the server it will say hello by itself?

**Comment by MeepCastana** [comment]
No, it means every time you say hello in chat, the bot will respond

**Comment by loobing** [comment]
what if i want to continue the chat example the bot responds how are you doing and the guy says fine and the bot replys do i make a new line for that respond and also what if other people said fine but to their friends and the bot repond

**Comment by loobing** [comment]
and also the code doesnt work

**Comment by MeepCastana** [comment]
What issue do u have

**Comment by loobing** [comment]
i place it under the on_message as you said but i tried saying hello in chat nothing happened

**Comment by MeepCastana** [comment]
Send me a screenshot of ur code

**Comment by loobing** [comment]
![image](https://user-images.githubusercontent.com/31998999/30579444-4e41b778-9d4b-11e7-921d-99743fc060f2.png)

**Comment by MeepCastana** [comment]
Remove message_content = message.content.strip()

**Comment by MeepCastana** [comment]
Class started ill help u in 1 hr

**Comment by loobing** [comment]
![image](https://user-images.githubusercontent.com/31998999/30579622-005281ea-9d4c-11e7-85f6-90a04633004f.png)
tried already still nothing happened

**Comment by loobing** [comment]
cool

**Comment by MeepCastana** [comment]
Whats the error?

**Comment by loobing** [comment]
Tried nothing happen

**Comment by MeepCastana** [comment]
U should have an error

**Comment by loobing** [comment]
So what now

**Comment by loobing** [comment]
ok now the hello respond worked but i cant command the bot

**Comment by loobing** [comment]
and i also put the message_content = message.content.strip() back its now fine(i can command again) but there is still one i need is how do i let the bot respond to the 2nd message example if that the bot says "how are you doing" and the person replies fine then the bot only reply that message fine and not other fine if other people says it

**Comment by MeepCastana** [comment]
Make another command that responds to fine

**Comment by MeepCastana** [comment]
if message.content.startswith('fine'):
        await self.send_message(message.channel, 'cool')

so like that

**Comment by loobing** [comment]
Some additional stuff do you know how to let the bot play live stream on youtube

**Comment by MeepCastana** [comment]
get the review version

**Comment by loobing** [comment]
Where?

**Comment by mixieculez** [comment]
@loobing The review branch should be here: https://github.com/Just-Some-Bots/MusicBot/tree/review

**Comment by loobing** [comment]
thanks for all your help really appreciated
