### ISSUE TITLE
Turn off TTS

### ISSUE THREAD

**Issue by grizzogor** [Just-Some-Bots/MusicBot#134]
I would like if I can turn off TTS from the bot. I tried to turn the TTS off in the role settings but that didn't stop the bot saying things with /tts.

**Comment by imayhaveborkedit** [comment]
The bot does not use tts for anything.  If someone else is hosting the bot they may have changed the code, and ensure your tts is disabled: ![](http://i.imgur.com/hkZUbv3.png)
