### ISSUE TITLE
Does the autoplaylist.txt support URL with playlist or just a single "watch" URL?

### ISSUE THREAD

**Issue by alfredmak** [Just-Some-Bots/MusicBot#1342]
I put something like "https://www.youtube.com/playlist?list=abcde" in autoplaylist.txt but when it restarted it didn't play anything. However, if I put like "https://www.youtube.com/watch?v=abcde", it is okay, so I think the autoplaylist.txt does not support playlist?

**Comment by loobing** [comment]
No it doesnt support playlist

**Comment by Pesoen** [comment]
you can use the !pldump command to dump the playlist into watch url's. so long as they are user created list's.

**Comment by alfredmak** [comment]
No problem, I just want to verify that, I have a workaround to use youtube-dl to convert the playlist to multiple URLs and paste them to autoplaylist.txt. As it is a one-time job, the problem is solved.
Thanks all.
