### ISSUE TITLE
Python Crashing

### ISSUE THREAD

**Issue by ZuvaDeity** [Just-Some-Bots/MusicBot#1344]
Hi Guys

Every time I try to run the 'Update_Deps.bat' File, my Python crashes almost immediately. 

[https://imgur.com/a/9yJhq](url)

I made sure I am using the correct version of Python (64 bit)

I am positive I followed all of the steps correctly, but clearly I must have messed something up on the way. 

Any help would be appreciated, I am new to programming and am unable to figure this out myself. 

Many thanks :)

**Comment by jayktaylor** [comment]
Not entirely sure what your issue is here but it doesn't look like an issue with the bot. Seems like an issue with your Python installation. Try reinstalling the latest version of Python and seeing if that helps. Closing this as it's not something we could fix
