### ISSUE TITLE
Change to Sanity Checks and startup of review bot

### ISSUE THREAD

**Issue by OzzyHelix** [Just-Some-Bots/MusicBot#1345]
since I can't figure out how to make a pull request I wanted to share my startup script for the review branch bot I wrote it to show the python version and this could help with debugging and troubleshooting
I will attach the script to this 
[run.zip](https://github.com/Just-Some-Bots/MusicBot/files/1322806/run.zip)
sorry I had to compress it to a zip

**Comment by jayktaylor** [comment]
This is not a valid issue.
