### ISSUE TITLE
After Moving PC, Music Bot Refuses To Start.

### ISSUE THREAD

**Issue by SarzeLight** [Just-Some-Bots/MusicBot#1346]
I have tried to get Music Bot to run as I recently finished the transfer to my new PC, however, the bot is refusing to run. After doing all that it has asked of me and multiple google searches, I decided I should ask here. The following link is a pastebin of the command prompt after attempting to run the bot: https://pastebin.com/8YfkJfLc

**Comment by pkajan** [comment]
python -m pip install --upgrade pip

then run dep update

**Comment by SarzeLight** [comment]
Entering this just tells me that "'python' is not recognized as an internal or external command, operable program or batch file."

**Comment by pkajan** [comment]
try reinstall python and check:
"Add Python to PATH" and "Install launcher for all users"
![clipboard05](https://user-images.githubusercontent.com/2750891/30780757-e9378b84-a112-11e7-9e57-5e419dec6a93.jpg)

**Comment by SarzeLight** [comment]
After a few attempts, this worked. thanks!
