### ISSUE TITLE
Bot refuses to play playlists on Youtube.

### ISSUE THREAD

**Issue by Mechalomaniac20** [Just-Some-Bots/MusicBot#1347]
It says that it processes '0' videos (There are four in the playlist) and then gives me an error:

Error queuing playlist:
float division by zero

**Comment by loobing** [comment]
Bot can't play playlist

**Comment by loobing** [comment]
I mean the bot doesnt support playing playlist

**Comment by Alloc86** [comment]
It does: https://github.com/Just-Some-Bots/MusicBot/wiki/FAQ#how-do-i-play-a-youtube-playlist

**Comment by loobing** [comment]
Only user playlists are supported by the bot, YouTube's generated playlists do not count as this.

**Comment by jayktaylor** [comment]
We can't help you without info about what playlist you're trying to use, otherwise we can't repro this. Closing this issue.
