### ISSUE TITLE
Help Me With evry thing 

### ISSUE THREAD

**Issue by xnuken** [Just-Some-Bots/MusicBot#1348]
No module named 'websockets'
Attempting to install dependencies...
Requirement already up-to-date: aiohttp<1.1.0,>=1.0.0 in c:\users\jacks\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 1))
Collecting websockets<4.0,>=3.1 (from -r requirements.txt (line 2))
  Using cached websockets-3.4.tar.gz
Requirement already up-to-date: chardet in c:\users\jacks\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->-r requirements.txt (line 1))
Requirement already up-to-date: multidict>=2.0 in c:\users\jacks\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->-r requirements.txt (line 1))
Requirement already up-to-date: async-timeout in c:\users\jacks\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->-r requirements.txt (line 1))
Installing collected packages: websockets
  Running setup.py install for websockets
    Complete output from command C:\Users\jacks\AppData\Local\Programs\Python\Python35\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\jacks\\AppData\\Local\\Temp\\pip-build-u2xvz3tm\\websockets\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\jacks\AppData\Local\Temp\pip-d2aso9fn-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\websockets
    copying websockets\client.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\compatibility.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\exceptions.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\framing.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\handshake.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\http.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\protocol.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\server.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\test_client_server.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\test_framing.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\test_handshake.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\test_http.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\test_protocol.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\test_speedups.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\test_uri.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\test_utils.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\uri.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\utils.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\version.py -> build\lib.win-amd64-3.5\websockets
    copying websockets\__init__.py -> build\lib.win-amd64-3.5\websockets
    creating build\lib.win-amd64-3.5\websockets\py35
    copying websockets/py35\client.py -> build\lib.win-amd64-3.5\websockets/py35
    copying websockets/py35\client_server.py -> build\lib.win-amd64-3.5\websockets/py35
    copying websockets/py35\server.py -> build\lib.win-amd64-3.5\websockets/py35
    copying websockets/py35\__init__.py -> build\lib.win-amd64-3.5\websockets/py35
    running build_ext
    building 'websockets.speedups' extension
    error: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command "C:\Users\jacks\AppData\Local\Programs\Python\Python35\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\jacks\\AppData\\Local\\Temp\\pip-build-u2xvz3tm\\websockets\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\jacks\AppData\Local\Temp\pip-d2aso9fn-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\jacks\AppData\Local\Temp\pip-build-u2xvz3tm\websockets
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

You may need to run as admin to install dependencies.

C:\Users\jacks\MusicBot>

C:\Users\jacks\MusicBot>

C:\Users\jacks\MusicBot>

**Comment by Colink02** [comment]
How did you fix it i have this same error
just with the discord module
