### ISSUE TITLE
Cant Summon Bot

### ISSUE THREAD

**Issue by xnuken** [Just-Some-Bots/MusicBot#1349]
Connected!  Musicbot v1.9.5_2

Bot:   362208502917365760/skrtt.xyz#1869
Owner: 198240897354170368/ジャクソン#5040

Server List:
 - skrrt.xyz

Not bound to any text channels
Not autojoining any voice channels

Options:
  Command prefix: !
  Default volume: 25%
  Skip threshold: 4 votes or 50%
  Now Playing @mentions: Disabled
  Auto-Summon: Disabled
  Auto-Playlist: Enabled
  Auto-Pause: Enabled
  Delete Messages: Enabled
    Delete Invoking: Disabled
  Debug Mode: Disabled
  Downloaded songs will be saved

[Command] 198240897354170368/ジャクソン (!summon)
Traceback (most recent call last):
  File "C:\Users\jacks\MusicBot\musicbot\bot.py", line 1931, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Users\jacks\MusicBot\musicbot\bot.py", line 1325, in cmd_summon
    player = await self.get_player(author.voice_channel, create=True)
  File "C:\Users\jacks\MusicBot\musicbot\bot.py", line 362, in get_player
    voice_client = await self.get_voice_client(channel)
  File "C:\Users\jacks\MusicBot\musicbot\bot.py", line 249, in get_voice_client
    voice_client = VoiceClient(**kwargs)
  File "C:\Users\jacks\MusicBot\discord\voice_client.py", line 217, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice
[Command] 198240897354170368/ジャクソン (!play https://www.youtube.com/watch?v=AEatxOYocQs)
<class 'musicbot.exceptions.CommandError'>: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.

**Comment by agraubert** [comment]
sounds like it could be a requirements issue `pip install -r requirements.txt`

**Comment by jayktaylor** [comment]
Try updating the bot and seeing if that helps you, a release was just pushed.
