### ISSUE TITLE
Bot stopped showing which song is played

### ISSUE THREAD

**Issue by Backyusa** [Just-Some-Bots/MusicBot#1350]
Since something changed on discord and the change_status isn't valid anymore I tried to change it but the bot is still not showing what song is being played on the right in the userlist.

**Comment by rafaelwastaken** [comment]
Did you try updating to discord.py 0.16.11?

**Comment by Backyusa** [comment]
I didn't.
So I just did that and it still doesn't show up.

**Comment by Backyusa** [comment]
Okay someone helped me the fix was something in the bot.py
