### ISSUE TITLE
Bot working fine but does not display "playing:"

### ISSUE THREAD

**Issue by Ctrl-Elt-Del** [Just-Some-Bots/MusicBot#1352]

**Comment by Backyusa** [comment]
What do you mean by that? Are you talking about it not showing what song it's playing in the Userlist ?

**Comment by Backyusa** [comment]
If that is the problem. Open cmd as admin enter "pip install discord.py --upgrade" to upgrade discord.py. Also if you haven't done it yet, change await self.change_status(game) to 
await self.change_presence(game=game, status=None, afk=False) in the bot.py

**Comment by Ctrl-Elt-Del** [comment]
"Also if you haven't done it yet, change await self.change_status(game) to
await self.change_presence(game=game, status=None, afk=False) in the bot.py"

YES! I believe that is it! I've been looking through the lines of code that displays the "playing:" and dont remember self.change_presence. I guess I haven't been updated/updating the discord.py.

**Comment by Backyusa** [comment]
If that fixed your problem go ahead and close this issue.

**Comment by Ctrl-Elt-Del** [comment]
AHH! So the problem seems to be that the requirements were set to only update discord.py to 0.12.0 and currently it is at 0.16.0. I updated that and now it runs fine. I also changed that line of code too.
