### ISSUE TITLE
Cant Run Bot

### ISSUE THREAD

**Issue by shenshendei** [Just-Some-Bots/MusicBot#1353]
No module named 'musicbot.bot'
Attempting to install dependencies...
Requirement already up-to-date: discord.py[voice]~=0.12.0 in c:\users\bonso\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: youtube_dl in c:\users\bonso\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: pip in c:\users\bonso\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: cffi==1.6.0 in c:\users\bonso\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: aiohttp<1.1.0,>=1.0.0 in c:\users\bonso\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: websockets<4.0,>=3.1 in c:\users\bonso\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: PyNaCl==1.0.1 in c:\users\bonso\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: pycparser in c:\users\bonso\appdata\local\programs\python\python35\lib\site-packages (from cffi==1.6.0->-r requirements.txt (line 4))
Requirement already up-to-date: chardet in c:\users\bonso\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: multidict>=2.0 in c:\users\bonso\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: async_timeout in c:\users\bonso\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: six in c:\users\bonso\appdata\local\programs\python\python35\lib\site-packages (from PyNaCl==1.0.1->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))

Ok lets hope it worked

**Comment by shenshendei** [comment]
please help ToT

**Comment by shenshendei** [comment]
it turned to this now




Traceback (most recent call last):
  File "run.py", line 162, in main
    from musicbot import MusicBot
  File "D:\Desktop\MusicBot-master\musicbot\__init__.py", line 1, in <module>
    from .bot import MusicBot
  File "D:\Desktop\MusicBot-master\musicbot\bot.py", line 2
    os
    ^
IndentationError: unexpected indent

D:\Desktop\MusicBot-master>

**Comment by rafaelwastaken** [comment]
Redownload bot.py and place it in the musicbot folder

**Comment by jayktaylor** [comment]
Reinstall the bot using the guides on the wiki. Do not manually download the bot.
