### ISSUE TITLE
Bot randomly restarting, and locking up

### ISSUE THREAD

**Issue by justandras** [Just-Some-Bots/MusicBot#1354]
The bot randomly restarts, and the log throws an exception, something to do with deleting the music cache.
![1](https://user-images.githubusercontent.com/32372119/30985743-82fe74cc-a491-11e7-8a16-3a8672f62f01.PNG)

**Comment by agraubert** [comment]
:+1: Having the same issue:
```
/home/ubuntu/MusicBot/musicbot/bot.py:467: DeprecationWarning: change_status is
deprecated, use change_presence instead.
  await self.change_status(game)
/home/ubuntu/MusicBot/musicbot/bot.py:467: DeprecationWarning: change_status is
deprecated, use change_presence instead.
  await self.change_status(game)
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f6417809ba8>
Cleaning up... Done.
Restarting in 6 seconds...
Connected!  Musicbot v1.9.5_2

Bot:   310112310100361216/Tenno DJ#9082
Owner: 142063091692208128/Jroot#8988
```

**Comment by Pesoen** [comment]
agraubert, looks fairly easy to fix.. from what i can see from you, simply open up the bot.py file in a text editor(notepad ++ would be preffered, for the line numbers, and syntax highlighting) and go to line 467 and change the "change_status" to "change_presence" instead, see if that helps.

however justandras, not sure what your problem could be.. try running the bot, and posting the logs if it still locks up/restarts, and we can take it from there. this is generally a good thing to do when a log is created, and you have a problem, look it over, and if that fails, post it along with a description of the error.

**Comment by justandras** [comment]
I've enabled DebugMode right now, next time the bot locks up I will be posting the logs. I totally forgot that there is a debug mode, thanks for reminding.

**Comment by justandras** [comment]
@Pesoen The bot went offline tomorrow again, and here is the log.
https://imgur.com/a/GM5mJ

**Comment by Pesoen** [comment]
Hmm, it keeps complaining that it cannot delete the audio cache. That could be the problem. Try removing the audio cache folder and see if that helps, will look over the other errors when I get home.

**Comment by justandras** [comment]
If I restart the bot I don't get the error message, so It's kinda strange

**Comment by Pesoen** [comment]
Odd. So it only comes after it stops working, and then starts working again?

also what version are you running? Stable dev or review?

**Comment by justandras** [comment]
How can I check the version? I have installed it in the summer, so it's fom that time period, but this problem existed when I installed it. Windows says that the files have been modified @ 2016.09.28.

**Comment by Pesoen** [comment]
Then i guess you are using the master version.. But maybe one that is outdated. Try moving your current bot to another location on your pc, and follow the instructions on installing it again, could help you find a sollution. Simply copy the configuration folder into the new bot folder to keep current settings.

**Comment by jayktaylor** [comment]
You're using an outdated version of the bot. Try and update and see if it helps.
