### ISSUE TITLE
Online

### ISSUE THREAD

**Issue by Rg2901** [Just-Some-Bots/MusicBot#1356]
Hello

Is there a way to make the bot work for other users? that I know the bot stops working when closing the "run.py"

**Comment by Chriscox462** [comment]
if you are using linux, you could run it in a program like "screen".

**Comment by doamatto** [comment]
Since your locally hosting the bot, you might want to consider hosting options so your internet and computer don't get bogged down and you don't have said issue. Some of these hosting options for small Discord servers are Amazon AWS Free, Google Cloud Platform, MS-Azure, Heroku, and more.
