### ISSUE TITLE
Shows as song is playing but no sound

### ISSUE THREAD

**Issue by Cryzin** [Just-Some-Bots/MusicBot#136]
This happens usually after not being used for few hours, and when you go type !play <url> it shows as song is playing but no audio.

**Comment by RCambier** [comment]
Yeah i have the same issue. I need to reboot the bot each time. Is there a solution ?

**Comment by shrx** [comment]
I have the same issue.

**Comment by zpl-zak** [comment]
Yea, same issue here.

**Comment by Dark583** [comment]
same any idea why it occurs? otherwise its great!

**Comment by imayhaveborkedit** [comment]
This was probably the "voice websocket dies and sound stops" issue, which should be fixed now.
