### ISSUE TITLE
ERROR: not well-formed (invalid token): line 1, column 6

### ISSUE THREAD

**Issue by Bkamahl** [Just-Some-Bots/MusicBot#1365]
ERROR: not well-formed (invalid token): line 1, column 6
When I try playing anything I get that

**Comment by Pesoen** [comment]
looked at the log? problems are sometimes explained better there..

**Comment by jayktaylor** [comment]
This is not a valid issue. Please give information about reproduction steps when making issues, along with a full log of your error.
