### ISSUE TITLE
Bot reqiures code grant

### ISSUE THREAD

**Issue by zakriyakhan** [Just-Some-Bots/MusicBot#1366]
i configured all my stuff, ran the run thing and did the other stuff, but when i try to authorize my bot it says ERROR: BOT REQIURES CODE GRANT, so the code is maybe this.

**Comment by rafaelwastaken** [comment]
Nothing wrong with the code, you checked off a box you weren't supposed to check off in the application's page.

**Comment by PvtHaggard** [comment]
Go to `https://discordapp.com/developers/applications/me/BOT_ID` and untick `Require OAuth2 Code Grant`

**Comment by zakriyakhan** [comment]
@fofofofofofofofoXD k

**Comment by zakriyakhan** [comment]
@PvtHaggard ok thank u

**Comment by zakriyakhan** [comment]
ok it works

**Comment by ghost** [comment]
Where can you disable code grant?

**Comment by AutumnClove** [comment]
https://just-some-bots.github.io/MusicBot/using/configuration/

**Comment by ghost** [comment]
> https://just-some-bots.github.io/MusicBot/using/configuration/

So I asked how to disable code grant not a bot template I can install.

**Comment by AutumnClove** [comment]
`require 0Auth2 Grant` needs to be unchecked, a few comments up this was said, on the guide you'll notice it's also unticked :shrug:

**Comment by MattBSG** [comment]
Please don't necro-post in an issue that's already solved, and the solution clearly posted.
