### ISSUE TITLE
Incorrect Credentials?

### ISSUE THREAD

**Issue by poocie** [Just-Some-Bots/MusicBot#137]
I'm putting in the credentials, but it keeps coming up as Incorrect credentials passed.

**Comment by imayhaveborkedit** [comment]
If you're editing the config file with notepad, it breaks the file.  Each section needs to be on their own line too.  Also remember to save the file.

**Comment by poocie** [comment]
I'm using Notepad++.

**Comment by poocie** [comment]
Finally, I got it. Sorry for wasting your time.
