### ISSUE TITLE
run.py error after reinstall of windows

### ISSUE THREAD

**Issue by Pesoen** [Just-Some-Bots/MusicBot#1370]
just had to reinstall my windows due to having 20+ network connections, from out of nowhere, and wanted to get the music bot going again.

found the folder, checked i had all the required programs installed, and ran it.

>   File "run.py", line 314
    def pyexec(pycom, *args, pycom2=None):
                                  ^
SyntaxError: invalid syntax

okay, could be something is wrong, downloading it all again and i still get that error message.. the arrow points to the end of pycom2 just before the equals sign.

it was working fine before my reinstall, so what am i missing/what have i done to make it not work?

Info:
python installed as required, as well as git.
running review version, as it seems more stable at most times(and was told to use that instead of master)
have not tried other versions(master/development)

**Comment by Pesoen** [comment]
Have now tried the other versions, develop and master both work, so for now i use one of them.

**Comment by jayktaylor** [comment]
Please ensure you are using Python 3.5 or higher and have installed the bot correctly.

**Comment by Pesoen** [comment]
i have 3.5.1 installed, and the bot is correctly installed. for some reason after reinstalling visual studio, it now works for some reason.. so feel free to close it.
