### ISSUE TITLE
AutoPlaylist Extensions

### ISSUE THREAD

**Issue by TheBrambleShark** [Just-Some-Bots/MusicBot#1372]
These ideas were left in the Discord server, but it was advised that I open an issue here. This Idea takes the form of three separate commands, though really only two have to be written on the back-end...

All commands would fall under the `!ap` command. | means or.
1. Add song to AutoPlaylist: `!ap add|+ <url>`
2. Remove song from AutoPlaylist: `!ap remove|- <url>`
3. Add playlist to AutoPlaylist `!ap add|+ <playlist url>`

The third command would, in its most simplistic form, would take the output from `!pldump` and pipe it to the `!ap add` method, adding each video to the autoplaylist.

Credits:
Discord: Kerv17 - Add and remove commands
Discord Foxtrek_64 (@Foxtrek64) - Pipe to add command

**Comment by tzhongyan** [comment]
This comment is kinda on topic and helpful:
https://github.com/Just-Some-Bots/MusicBot/pull/1010#issuecomment-287314600

**Comment by MattBSG** [comment]
@tzhongyan https://github.com/Just-Some-Bots/MusicBot/blob/review/musicbot/bot.py#L1333

**Comment by tzhongyan** [comment]
Yea but this only saves current song, whilst that supports inputting song URL that is not currently playing in the playlist. I was mentioning the comment instead of the PR 🤣

**Comment by obi23lipnik** [comment]
@tzhongyan Made a pull request with `!autoplaylist [ + | - | add | remove] <optional:url>` and `!unsave <optional:url>`  here: https://github.com/Just-Some-Bots/MusicBot/pull/1544

The appending whole playlist I'll look into aswel, sorry for not doing it yet -- Developed this for myself, wasn't aware of this request :(

**Comment by obi23lipnik** [comment]
@tzhongyan If you're too eager to wait you can get the "WIP" branch from my repo here: https://github.com/obi23lipnik/MusicBot/tree/playlist_manipulations

**Comment by MattBSG** [comment]
We implemented saving specific links already in the cmd_save function. If you provide a link it adds the link, otherwise the current song (if any).
