### ISSUE TITLE
Bot will not play music nor show song name in status after update.

### ISSUE THREAD

**Issue by AbstractUmbra** [Just-Some-Bots/MusicBot#1374]
I updated my Raspberry Pi (apt get update | upgrade) and then used `git pull` within the bot directory and updated.
I then used `sudo -H pip3.5 install --upgrade -r requirements.txt` to update the dependencies of the bot.

After it was all completed I then launched it and now it will not output to Discord Voice, nor update it's status with what it's playing. 

Any ideas?

**Comment by Raze67** [comment]
You can use the research function, you know? This should solve half of your problem.
https://github.com/pkajan/MusicBot/commit/a4b7f0744fbad8368ab02a5b74b111c2ab5b90d9

**Comment by AbstractUmbra** [comment]
It's all good, I just reinstalled the bot on a ubuntu server.
