### ISSUE TITLE
Repeat command don't work

### ISSUE THREAD

**Issue by Licons** [Just-Some-Bots/MusicBot#1375]
I called command "repeat" to repeat my songs but nothing happened.

This is my picture.
https://imgur.com/a/tEZBh

Thanks.

**Comment by Zenrac** [comment]
Come on, how we're supposed to help you ?

**Comment by FIERCEDINO080** [comment]
they never put a repeat command in so it's basically classed as a "modified bot". You can't be helped with modified bots so don't post this here. thanks

**Comment by computergeek125** [comment]
duplicate of #486
