### ISSUE TITLE
"Failed to join <Voice chat>"

### ISSUE THREAD

**Issue by Noobot9k** [Just-Some-Bots/MusicBot#1377]
When I first start the bot I get this error:
`Attempting to autojoin THE_MUSIC_CORNER in gamersunited`
`Failed to join THE_MUSIC_CORNER`

some help would be nice, I've been working on this for almost a week now and really want it to work.
Thanks.

**Comment by davidgomesdev** [comment]
This might seem like I'm trolling or stupid but are you sure the bot has permission to join the channel?
@Noobot9k

**Comment by Noobot9k** [comment]
@LegendL3n Yes. I have the same bot running on another computer and it works fine.
I suppose I should give more detail as to what happens when I run the bot.
When I run the bot it starts up as normal until it tries to auto-join the voice channel. Then it gives the before mentioned error. When I look in Discord I see that the bot is in the voice channel and just isn't playing anything and is completely silent and will even listen to commands though it will complain that it's not in a voice channel with most of them even though it is.
So when I try to use commands like !np, !play... etc it says it's not in a voice channel but commands like !shutdown and - I would assume - !setname work fine.

Thank you for responding. I've been working on this for over a week now and am so close to getting it right I can _feel_ it!

**Comment by jayktaylor** [comment]
Please try updating your bot and seeing if that helps.
