### ISSUE TITLE
Reading playlist from php file?

### ISSUE THREAD

**Issue by Mudsaf** [Just-Some-Bots/MusicBot#1379]
Hello, i have no experience in Python coding and im wondering if its possible to read the playlist from URL everytime bot is restarted?

Currently i have this url: https://mudsaf.com/gdiscord-listr.php
^Pretty much has playlist in text

Tried to do some random coding that i really dont understand about
import urllib
link = "https://mudsaf.com/gdiscord-listr.php"
f = urllib.urlopen(link)
myFile = f.read()
lines = f.readlines()
random.shuffle(lines)
open('config/autoplaylist.txt', 'w').writelines(lines)

But this didn't do anything at bot.py file. Didnt get error, but said playlist is empty.

Also im not sure if this is the correct place to request support etc so forgive me if not.

**Comment by loobing** [comment]
go to autoplaylist.txt in config edit with Notepad++ then replace everything inside with your playlist

**Comment by Mudsaf** [comment]
Thanks for the answer, but its not what im searching for. I'm thinking of making playlist that can be easily be modified via website. With people having permissions can edit & so on.

(Since the musicbot is not on my actual pc, it takes time when people add songs to my website discord bot)

**Comment by loobing** [comment]
ohhh there was a command that allow you to do that in #1010 that let u add song website into the playlist and the remove one was somewhere in pull request i think

**Comment by jayktaylor** [comment]
We don't give support for modification here. As you're new to Python coding, I'd recommend reading up a little about the language before trying to modify a bot, especially as you're trying to use `urllib` in an asynchronous code environment.
