### ISSUE TITLE
bot responding to emoji

### ISSUE THREAD

**Issue by loobing** [Just-Some-Bots/MusicBot#1380]
anyone know how to let the bot respond to discord emoji?

**Comment by sheenkatz** [comment]
check out some of the discord bots that allow you to alias commands. For example, "!q" instead of "!queue". Or maybe even "!:grinning:" to "!play".

https://twentysix26.github.io/Red-Docs/red_guide_aliases/

haven't used that but it looks like it could accomplish what you want.

**Comment by Crafteri** [comment]
It doesn’t. As far as i know. The text (for example) :joy: turns into a picture before the bot recognizes it.

**Comment by Chriscox462** [comment]
:joy: Discord shows emoji like this. so try placing the keyword in your config for the emote you want in that format.

**Comment by jayktaylor** [comment]
This is probably possible by using the actual ID representation of the emoji, but we don't recommend doing that - just use standard characters for prefixes.
