### ISSUE TITLE
Aiohttp module not seen

### ISSUE THREAD

**Issue by NickMatthews-1** [Just-Some-Bots/MusicBot#1381]
No module named 'aiohttp'
Attempting to install dependencies...

Its installed but for some strange reason the bot isnt seeing it. Its also taken two days to get a response from "The Help" only to get accused of shitposting. Others have waited longer and I think its stupid.

**Comment by Hengstigal** [comment]
Are u using a Linux Server and maybe used the manual to install for "Debian" instead of "Ubuntu" (if your server is using this)? This was my problem. Try to connect via. Filezilla to your Server: sftp://YOURIP and delete the folder "MusicBot" and use the correct manual.

**Comment by jayktaylor** [comment]
Please ensure you have followed the guides correctly for your system. Update your bot and try it as an administrator to see if that helps.
