### ISSUE TITLE
"no module named 'discord'" Error

### ISSUE THREAD

**Issue by Owez** [Just-Some-Bots/MusicBot#1382]
Hello,

I am VERY new to discord bots and just wanted to make a custom bot for my server. I am getting an error when I run runbot.bat. I have got everything set up correctly (followed this tutorial: https://www.youtube.com/watch?v=A6bY7P8FaZA). It is saying something about no module named discord for some reason. Bot tokens and owner tokens are in correctly and everything looks like it is running order. Here are the screenshots of what is happening, got a fresh version of python as well:

Part 1: https://gyazo.com/7cf206e6ac0a13a681caeedb92fbbcd9
Part 2: https://gyazo.com/a9747d5f692d75205b8e0e9bf5268368﻿

Thanks in advance, Owez

**Comment by rafaelwastaken** [comment]
If installing deoendencies doesn't work, then I'd recommend reinstalling the bot using the installation guide in the wiki.

**Comment by sheenkatz** [comment]
this happened to me as well but with the error

"no module named 'musicbot' found"

It happened when I tried moving my MusicBot directory. I moved it back to where it was and it was fixed.

Hope that helps.

**Comment by jayktaylor** [comment]
Please follow the guide on our repo's wiki, not a video tutorial by a third party.
