### ISSUE TITLE
My Discord Bot Cuts out

### ISSUE THREAD

**Issue by IsCoffeeTho** [Just-Some-Bots/MusicBot#1386]
My Discord Bot for my server that i host keeps cutting out while the command prompt is open. Is there any code to make the bot restart instantly **USING JavaScript**

**Comment by rafaelwastaken** [comment]
The bot is written in python...

**Comment by IsCoffeeTho** [comment]
@fofofofofofofofoXD im using javascript its called node.js and if you don't use javascript how the actual hell is that useful. p.s. i've been writing bots for ages so i'm pretty sure i'm using javascript

**Comment by rafaelwastaken** [comment]
@CoffeeGamerYT You posted an issue on the github page for a musicbot that's written in python and are asking for help on a completely different bot that's written in a completely different language.

I'd suggest asking this in the node js channel on the Discord API server instead.

**Comment by santaryan** [comment]
Use pm2, and have it monitor the bot and restart as necessary.

**Comment by jayktaylor** [comment]
@santaryan's solution is your best bet.
