### ISSUE TITLE
Make it so only the owner can !skip

### ISSUE THREAD

**Issue by ZRanger999** [Just-Some-Bots/MusicBot#1389]
i have tried everything but users can still skip songs. I want to make it so only i the server owner can skip songs

**Comment by Deadlesszombie** [comment]
then edit the [DEFAULT] in the permissions.ini???

**Comment by elevenrax** [comment]
I don't think this is possible. Given how it was designed, the person who adds the song is not seen as the owner. But you can disable skipping for all but admin as follows:

options.ini - change the skip ratio such that your group mathematically cannot achieve consensus. Lines 67 - 68 will help.

**Comment by MistChristmas** [comment]
I concur with Deadlesszombie, just go into permissions.ini with notepad++ or whatever. Head down to [Defualt], and just remove skip from the whitelists, and add it to the blacklists for the other permission levels as required. And then only the owner can use it.

Alternatively you can go into bot.py to cmd_skip, and add @owner_only on the line just before it, with the proper indent.


    @owner_only #So put it like here, properly indented, without anything past the hashtag
    async def cmd_skip(self, player, channel, author, message, permissions, voice_channel):
        """
        Usage:
            {command_prefix}skip
        Skips the current song when enough votes are cast, or by the bot owner.
        """
