### ISSUE TITLE
How do I make the Bot stop talking?

### ISSUE THREAD

**Issue by KaireFeare** [Just-Some-Bots/MusicBot#139]
Basically, I want to get the bot to stop talking, or rather not use TTS / be able to hear the voice when it says something, I'd like it to chat, but not to use TTS.
I'd mute them, but then I cant play a playlist.

**Comment by imayhaveborkedit** [comment]
The bot doesn't use TTS at all.  Look in your settings for this:

![](http://i.imgur.com/hkZUbv3.png)

**Comment by KaireFeare** [comment]
If it doesn't use TTS, then why does that setting affect that though?

**Comment by jhgg** [comment]
Because it applies to all messages sent in the channel. Bot or not.
