### ISSUE TITLE
Raspberry Pi error with run.py

### ISSUE THREAD

**Issue by Crafteri** [Just-Some-Bots/MusicBot#1391]
When i try to run ”run.py” in the folder it starts to install some shit even though i did everything in order. Then it hits me with an error:

”Command ”python setup.py egg_info failed with error code 1 in /tmp *something i don’t remember the whole folder*”

But the main problem is why is there an error and why is it talking about some egg info? Like i give a damn about an egg!!!

**Comment by ghost** [comment]
Sorry for taking so long to get to your issue. I have a Pi but haven't used it. To me it looked like you typed in`python run.py` instead of `python3.5 run.py`. Is that correct?

**Comment by jayktaylor** [comment]
Please provide additional info for your issue to be resolved.
