### ISSUE TITLE
Can we add "Status" to the bot

### ISSUE THREAD

**Issue by sakshatshinde** [Just-Some-Bots/MusicBot#1393]
Basically wanted to add a status to the bot, especially if we can use the new rich presence feature which was recently introduced in the discord update. That would really great if we can use it!

**Comment by MistChristmas** [comment]
change_status is already utilized in the bot. And lots of people switch that to change_presence.

**Comment by sakshatshinde** [comment]
Oh can you tell me where that particular snippet of the code is located? Thank you.

**Comment by 0XE4** [comment]
This is what you are looking for I believe: https://github.com/Just-Some-Bots/MusicBot/issues/1352#issuecomment-332870555

**Comment by jayktaylor** [comment]
change_presence has been added as of https://github.com/Just-Some-Bots/MusicBot/commit/ee8be2ac6af305a79b55cc51f4ddf29f2a6232bf, was already in review.
