### ISSUE TITLE
Can not get bot to use discord.py 0.16.12

### ISSUE THREAD

**Issue by chrisnick26** [Just-Some-Bots/MusicBot#1395]
Afternoon all 

I have been trying to use discord.py 0.16.9 or 0.16.12 I can use discord.py 0.15.1 with out errors but when i try and use 0.16.9 or 0.16.12 i keep getting errors like this and it keeps trying to install the dependencies any ideas (using review version of the bot). Thanks in advance.

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right folder
[INFO] launcher: Checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 344, in main
    from musicbot import MusicBot
  File "/home/pi/MusicBot/musicbot/__init__.py", line 74, in <module>
    from .bot import MusicBot
  File "/home/pi/MusicBot/musicbot/bot.py", line 26, in <module>
    from discord.http import _func_
ImportError: cannot import name '_func_'
[INFO] launcher: Attempting to install dependencies...
Requirement already up-to-date: discord.py[voice]~=0.16.12 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: pip in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: youtube_dl in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: colorlog in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: cffi in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: websockets<4.0,>=3.1 in /usr/local/lib/python3.6/site-packages (from discord.py[voice]~=0.16.12->-r requirements.txt (line 1))
Requirement already up-to-date: aiohttp<1.1.0,>=1.0.0 in /usr/local/lib/python3.6/site-packages (from discord.py[voice]~=0.16.12->-r requirements.txt (line 1))
Requirement already up-to-date: PyNaCl==1.0.1; extra == "voice" in /usr/local/lib/python3.6/site-packages (from discord.py[voice]~=0.16.12->-r requirements.txt (line 1))
Requirement already up-to-date: pycparser in /usr/local/lib/python3.6/site-packages (from cffi->-r requirements.txt (line 5))
Requirement already up-to-date: chardet in /usr/local/lib/python3.6/site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.16.12->-r requirements.txt (line 1))
Requirement already up-to-date: multidict>=2.0 in /usr/local/lib/python3.6/site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.16.12->-r requirements.txt (line 1))
Requirement already up-to-date: async_timeout in /usr/local/lib/python3.6/site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.16.12->-r requirements.txt (line 1))
Requirement already up-to-date: six in /usr/local/lib/python3.6/site-packages (from PyNaCl==1.0.1; extra == "voice"->discord.py[voice]~=0.16.12->-r requirements.txt (line 1))

[INFO] launcher: Ok lets hope it worked

[INFO] launcher: All done.
root@raspberrypi:/home/pi/MusicBot#

**Comment by jayktaylor** [comment]
Fixed by https://github.com/Just-Some-Bots/MusicBot/commit/7c617ec1d7d54202fcd94a190ca621408fba31f6.
