### ISSUE TITLE
playing local music?

### ISSUE THREAD

**Issue by Reylor** [Just-Some-Bots/MusicBot#1399]
i didn't see anything under commands for it but, would it be difficult to make it respond an execute a command that makes it play local files myself? i've not really fiddled around with bots much but this is the only one i could get to stream audio properly.

Any help with this would be appreciated!

**Comment by KingGold171** [comment]
We don't help you modify the bot.

But playing local music files is a planned feature with NO ETA.

**Comment by hardykyle** [comment]
Just host the files on a local server and play from the web address.

**Comment by jayktaylor** [comment]
We don't give support for modification here. See #43 for our active issue on this topic.
