### ISSUE TITLE
Unable to type in the cmd when the bot opens?

### ISSUE THREAD

**Issue by Peachyyy** [Just-Some-Bots/MusicBot#14]
So the bot starts up successfully using the runbot.bat.

However when the cmd opens saying:

Connected!

Username: MusicBot
ID: 135374938088538112
--Server List--
[My Server]

I am unable to type in the cmd.

Also another issue I have, is that I can see the bot as 'online' in discord, however i cannot move it to my voice channel.

Thanks

**Comment by imayhaveborkedit** [comment]
Typing in in the command prompt wouldn't do anything anyways because the bot doesn't read anything from stdin.  To move the bot into your voice channel you have to use the `!summon` command, assuming you didn't change the command prefix.
