### ISSUE TITLE
Bot wont play music

### ISSUE THREAD

**Issue by markus200331** [Just-Some-Bots/MusicBot#1403]
Every time I try to play a song this happens
![screenshot_1](https://user-images.githubusercontent.com/33598817/33224743-0250fde6-d16d-11e7-9f2b-ebcb2b05c625.png)
I am running the bot on a Debian server and I used this tutorial: https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Debian

**Comment by jayktaylor** [comment]
Have you tried installing ffmpeg on your Debian server?
