### ISSUE TITLE
CMD Instantly closes after opening "runbot.bat"

### ISSUE THREAD

**Issue by FR3SHPR1NCE** [Just-Some-Bots/MusicBot#1404]
So yeah, the title pretty much says everything. When I open the "runbot.bat" file it instantly closes. It doesn't provide text on the cmd and I am clueless as to why this happens.

I get the following message when I type python run.py into lazy_cmd.bat :

python is not recognized as an internal or external command, operable program or batch file.

I had originally installed python 3.5 last year and I just now updated it to 3.5.1. I have also run update_deps.bat and there were no issues. However, the runbot.bat file still won't open, it immediately closes when trying to open.

**Comment by KingGold171** [comment]
[RESOLVED]
https://github.com/Just-Some-Bots/MusicBot/blob/master/runbot.bat#L6-L20
