### ISSUE TITLE
Error when making container 

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1407]
Step 6/7 : RUN pip3 install -r requirements.txt
 ---> Running in 24fc7b4bd1f7
Collecting discord.py[voice]~=0.16.0 (from -r requirements.txt (line 1))
  Downloading discord.py-0.16.12.tar.gz (414kB)
Requirement already satisfied (use --upgrade to upgrade): pip in /usr/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Collecting youtube-dl (from -r requirements.txt (line 3))
  Downloading youtube_dl-2017.11.26-py2.py3-none-any.whl (1.7MB)
Collecting colorlog (from -r requirements.txt (line 4))
  Downloading colorlog-3.1.0-py2.py3-none-any.whl
Collecting cffi (from -r requirements.txt (line 5))
  Downloading cffi-1.11.2.tar.gz (435kB)
    Complete output from command python setup.py egg_info:
    gcc: error trying to exec '/usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../x86_64-alpine-linux-musl/bin/as': execv: Exec format error
    gcc: error trying to exec '/usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../x86_64-alpine-linux-musl/bin/as': execv: Exec format error

        No working compiler found, or bogus compiler options passed to
        the compiler from Python's standard "distutils" module.  See
        the error messages above.  Likely, the problem is not related
        to CFFI but generic to the setup.py of any Python package that
        tries to compile C code.  (Hints: on OS/X 10.8, for errors about
        -mno-fused-madd see http://stackoverflow.com/questions/22313407/
        Otherwise, see https://wiki.python.org/moin/CompLangPython or
        the IRC channel #python on irc.freenode.net.)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zj35idpo/cffi/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip3 install -r requirements.txt' returned a non-zero code: 1

**Comment by ghost** [comment]
Just want to add that pip is already at it's latest. I also installed pip3 as well.

**Comment by ghost** [comment]
Anyone have any ideas? Resorted to just installing onto Ubuntu but would really like to use the container on this host.

**Comment by jayktaylor** [comment]
May be fixed with https://github.com/Just-Some-Bots/MusicBot/commit/b19f5070ab5e692c89b9545db69be74b829b5941. Will be in the next release.
