### ISSUE TITLE
Same thing plays after skip autoplaylist

### ISSUE THREAD

**Issue by Bkamahl** [Just-Some-Bots/MusicBot#1409]
I am on the most recent update. So I have an autoplaylist enabled, I know for a fact there isnt any duplicates. When I skip something from the autoplaylist it will sometimes play the same thing, I dont know if this is fixable because maybe it just picks a random song from the playlist and might accidentally hit the same song, I dont know. Is it fixable? If possible please do <3 if not its cool this is an amazing creation anyway

**Comment by Bookrage001** [comment]
I also have this issue sometimes it also happens when i don't have a constant queue. so if the queue runs dry and then i queue a song it will play the auto queue first before the queued one

**Comment by Zenrac** [comment]
#964 

Duplicate of : #616 #936 ... and more...
