### ISSUE TITLE
You don't have permission to use that command. 

### ISSUE THREAD

**Issue by EstherTMB** [Just-Some-Bots/MusicBot#141]
In the permission.ini file I created a group of users that can use all the commands, but the bot writes them `"You don't have permission to use that command. Reason: only the owner can use this command"`

> ```
> [Admins]
> CommandWhitelist = play perms queue np skip search id help summon clean clear shuffle volume pause resume blacklist whitelist listroles perms joinserver
> GrantToRoles = 125582157115555840 125582736961306624
> ; UserList =
> MaxSongLength = 0
> MaxSongs = 0
> MaxPlaylistLength = 0
> AllowPlaylists = yes
> ```

The command "CheckWhiteList" is disabled.
Maybe I'm doing something wrong?

**Comment by imayhaveborkedit** [comment]
The whitelist check option in `options.ini` is different from command whitelists.  The `options.ini` option is a user id check before anything happens for if they can use the bot at all.  Permissions `CommandWhiteList`s determine which commands a group can use.  There are two commands that are hardcoded to be owner only though, `!joinserver` and `!clean`.  The clean command is owner only to prevent abuse, I have to fix it up anyways.

**Comment by EstherTMB** [comment]
I got it. Thanks.
