### ISSUE TITLE
Bot not showing "now playing message"

### ISSUE THREAD

**Issue by noirscape** [Just-Some-Bots/MusicBot#1410]
I am using the review branch. Basically the bot does not show a now playing status while active. I know it used to be able to, but it doesn't do it anymore.

Has this been changed to a configuration option or is it a bug?

**Comment by noirscape** [comment]
Update: now playing status works normal when using python3.6

I would suggest bumping up the required python version for the bot to 3.6,

**Comment by jayktaylor** [comment]
Python version should not affect this. As long as you're using the latest version of the bot (which was updated a few days ago), and you have updated your dependencies using the update scripts, you should be good. There aren't any differences between 3.5 and 3.6 that'd break the bot so we won't require people to use 3.6. Glad you got it sorted.
