### ISSUE TITLE
Two songs playing at once?

### ISSUE THREAD

**Issue by Yeikee** [Just-Some-Bots/MusicBot#142]
Every so often two songs start playing at the same time, overlapping each other. I can't !skip but I can !pause and it will stop one song. The other will continue playing. Once the song stops, no commands work.

**Comment by deansheather** [comment]
This is a known issue. Thank you for putting it onto GitHub, though.

**Comment by imayhaveborkedit** [comment]
This is fixed in review, and will be included in RC6.
