### ISSUE TITLE
Can't run run.py after install

### ISSUE THREAD

**Issue by ville1001** [Just-Some-Bots/MusicBot#1422]
I am using Debian(kali-rolling) with and I have tried booth python 2.7.14+ and Python3.5.4. When trying to run "python run.py"I get the error message.
"
  File "run.py", line 314
    def pyexec(pycom, *args, pycom=None):
                                 ^
SyntaxError: invalid syntax
"
I have tried reinstalling: both python and pip and nothing seems to work. I also tried googling and got to error message #1370 but nothing seems to work!

**Comment by MCApollo** [comment]
Using a older verison of run.py fixed this for me.


(It’s declared as a variable- “pycom = None” -extactly)

**Comment by jayktaylor** [comment]
This is an issue to do with your system trying to run the bot using the wrong version of Python.
