### ISSUE TITLE
Error with `update_dependencies` 

### ISSUE THREAD

**Issue by JGriffin34432** [Just-Some-Bots/MusicBot#1424]
Collecting discord.py[voice]~=0.16.0 (from -r requirements.txt (line 1))
  Using cached discord.py-0.16.12.tar.gz
Requirement already up-to-date: pip in c:\users\josht\.windows-build-tools\python27\lib\site-packages (from -r requirements.txt (line 2))
Collecting youtube_dl (from -r requirements.txt (line 3))
  Using cached youtube_dl-2017.12.14-py2.py3-none-any.whl
Collecting colorlog (from -r requirements.txt (line 4))
  Using cached colorlog-3.1.0-py2.py3-none-any.whl
Collecting cffi (from -r requirements.txt (line 5))
  Using cached cffi-1.11.2-cp27-cp27m-win32.whl
Collecting aiohttp<1.1.0,>=1.0.0 (from discord.py[voice]~=0.16.0->-r requirements.txt (line 1))
  Using cached aiohttp-1.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\josht\appdata\local\temp\pip-build-ax4eho\aiohttp\setup.py", line 60, in <module>
        raise RuntimeError("aiohttp requires Python 3.4.2+")
    RuntimeError: aiohttp requires Python 3.4.2+

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\josht\appdata\local\temp\pip-build-ax4eho\aiohttp\

Also unmarked CMD Error: [https://pastebin.com/LstXmSpP](url)

**Comment by JGriffin34432** [comment]
Sometimes their are lines through it so here is another copy: [https://pastebin.com/LstXmSpP](url)

**Comment by katiras** [comment]
I had the same issue. I uninstalled python and installed it again (3.5).
Seems ok now

**Comment by jayktaylor** [comment]
`RuntimeError: aiohttp requires Python 3.4.2+`

Update Python.
