### ISSUE TITLE
Syntax error when trying to run on Ubuntu 16.04

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1427]
When im trying to run it im getting this error : 

/MusicBot# python3 run.py
  File "run.py", line 319
    pyexec(sys.executable, *args, *sys.argv, pycom2='python')
                                  ^
SyntaxError: invalid syntax

**Comment by jayktaylor** [comment]
If you're still having this issue, join http://discord.gg/bots for support.
