### ISSUE TITLE
[Suggestion] !reboot command

### ISSUE THREAD

**Issue by Bomberlux** [Just-Some-Bots/MusicBot#143]
Sometimes, there might be an issue with the bot, but you're not at home or in front of the computer, so a !reboot button available to the Owner(or to a specified group) could fix the bot's current issue. Also, this way I could reboot the bot from my phone if I'm far from the computer by just typing the command in chat. 
It could also be easier, if I just changed something in the config, and instead of having to close the cmd i just type reboot to spare some time

**Comment by imayhaveborkedit** [comment]
A restart command is planned, and a command to reload configs is also planned.

**Comment by ImthePeach** [comment]
When will the next update be out? (rough estimated time)

**Comment by imayhaveborkedit** [comment]
Right now we have 1.9.5RC5, RC meaning release candidate, and there might be an RC 6 once I figure out how to squash a few rather irritating bugs.  Things that affect core functionality are obviously higher priority than simple feature additions.  I usually mention my progress on such things in the musicbothelp channel on the rhino help server.

**Comment by ImthePeach** [comment]
Great! Thank you and I just now saw the link to the discord server and will be exploring that for answers to my question now, thanks for the help. Cheers!

**Comment by imayhaveborkedit** [comment]
Added in review.

**Comment by pullup** [comment]
What we really need is a default script that restarts the bot every <specified amount of time>, because my bots break so frequently they're almost never responsive when someone joins and wants to execute a chat command...

#gravediggingallday2k17
