### ISSUE TITLE
can anyone help me with .ini full example files?

### ISSUE THREAD

**Issue by nirvanaruns** [Just-Some-Bots/MusicBot#144]
hi, is there any example of the .ini files? 
where i should put thems?
why the !np command doesn't work?

thanks a lot for any help

**Comment by kojitsari** [comment]
https://github.com/SexualRhinoceros/MusicBot/blob/review/config/example_options.ini
https://github.com/SexualRhinoceros/MusicBot/blob/review/config/example_permissions.ini
Put them here: https://github.com/SexualRhinoceros/MusicBot/tree/review/config
Use the rc5 build: https://github.com/SexualRhinoceros/MusicBot/releases/tag/v1.9.5rc5

**Comment by nirvanaruns** [comment]
ok i already create it but it doesn't work... can anyone help me?

code:

;[SuperAdmin]
;MaxSongLength = 0
;MaxSongs = 0
;MaxPlaylistLength = 0
;AllowPlaylists = yes

[Admins]
GrantToRoles = 83409356325916672 100338376141467648 104247003638145024 82986424676126720
CommandWhitelist = play perms queue np skip search id shuffle clear pause resume volume clean blacklist whitelist 
MaxSongLength = 0
MaxSongs = 0
AllowPlaylists = yes

[Users]
CommandWhitelist = play queue np skip search
IgnoreNonVoice = play queue np skip search
MaxSongLength = 300
MaxSongs = 5
AllowPlaylists = no

problem: http://prntscr.com/agod0g <--- it's a screenshot

**Comment by nirvanaruns** [comment]
i already fix it... how can i add a : delete_after_play_song command?

**Comment by kojitsari** [comment]
If you want to add things to the bot, learn python.

**Comment by nirvanaruns** [comment]
another question... is there any option to use the bot in only a single text channel? i want to create a special channel only for the bot but idk how to send him to that channel...

**Comment by arunesh90** [comment]
https://github.com/SexualRhinoceros/MusicBot/blob/review/config/example_options.ini#L34

Explanation is in the comment
