### ISSUE TITLE
Bot can't connect to server and then crashes

### ISSUE THREAD

**Issue by Trustmega** [Just-Some-Bots/MusicBot#1440]
Using the latest version
Did all the steps on this page, even git reset: https://github.com/Just-Some-Bots/MusicBot/wiki/Updating

This is the error:
[ERROR:bot] Failed to join Wetfjord Universe/Jukebox
[ERROR:bot] Exception in on_voice_state_update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/home/discordbots/MusicBot/musicbot/bot.py", line 2548, in on_voice_state_update
    player = await self.get_player(state.my_voice_channel)
  File "/home/discordbots/MusicBot/musicbot/bot.py", line 553, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.
[ERROR:bot] Exception in on_voice_state_update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/home/discordbots/MusicBot/musicbot/bot.py", line 2548, in on_voice_state_update
    player = await self.get_player(state.my_voice_channel)
  File "/home/discordbots/MusicBot/musicbot/bot.py", line 553, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.
[ERROR:bot] Exception in on_voice_state_update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/home/discordbots/MusicBot/musicbot/bot.py", line 2548, in on_voice_state_update
    player = await self.get_player(state.my_voice_channel)
  File "/home/discordbots/MusicBot/musicbot/bot.py", line 553, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.
  File "run.py", line 314
    def pyexec(pycom, *args, pycom2=None)

EDIT:

So the bot joins the voice channel at first, but then doesnt respond to certain commands. !help works, and !restart makes the bot leave the channel but then it crashes. The bot also joins the correct voice channel but there isn't coming any sound.

**Comment by jayktaylor** [comment]
Are you running the latest version of the bot? (1.9.6_1)

**Comment by Toqaro** [comment]
I've had the same issue with the latest version running on Docker with AutoJoin enabled.
Disabling AutoJoin & AutoSummon made it work for me though.

**Comment by melitran** [comment]
@jaydenkieran how to have the latest version of the bot? which is (1.9.6_1) bc  mine's Musicbot v1.9.5_2 and im having same  problem.

**Comment by jayktaylor** [comment]
@melitran https://github.com/Just-Some-Bots/MusicBot/wiki/Updating

**Comment by jbfriedrich** [comment]
I have the same issue with the latest version 1.9.6_2. The bot connects, seems to join the voice channel and text channels. Then you see a "failed to connect" message, followed by a critical message that the voice client is unable to connect:

```
xxxxxxxxxxxxxxxxxxxxx/musicbot#6201 has joined Discord Server/Room name
WARNING: Failed to connect, retrying (1/5)
WARNING: Failed to connect, retrying (2/5)
WARNING: Failed to connect, retrying (3/5)
WARNING: Failed to connect, retrying (4/5)
WARNING: Failed to connect, retrying (5/5)
[CRITICAL:bot] Voice client is unable to connect, restarting...
[ERROR:bot] Exception in on_voice_state_update
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/discord/client.py", line 273, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/usr/src/MusicBot/musicbot/bot.py", line 2584, in on_voice_state_update
    player = await self.get_player(state.my_voice_channel)
  File "/usr/src/MusicBot/musicbot/bot.py", line 563, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.
```

I am using a Docker image built from the Dockerfile that is included in the repo. I tried several versions of discord.py, just to see if there was maybe a bug introduced. But I got the same results, no matter which version I was using.

Here is the version information from pip:

```
/usr/src/MusicBot # pip list
aiohttp (1.0.5)
async-timeout (2.0.0)
cffi (1.11.4)
chardet (3.0.4)
colorlog (3.1.0)
discord.py (0.16.12)
multidict (4.0.0)
pip (9.0.1)
pycparser (2.18)
PyNaCl (1.0.1)
setuptools (20.10.1)
six (1.11.0)
websockets (3.4)
youtube-dl (2018.1.18)
````

Disabling auto-join or auto-summon doesnt help either in my case.

**Comment by Trustmega** [comment]
Alright guys, i think i solved this. 

It seems to be an issue with the bot being located on a server in Germany. I found another issue thread here a while ago #1499 where the poster was located in Germany.

Am i correct to assume that @jbfriedrich is also located in Germany?

Anyway, i tried running the music bot from my home network in Sweden and it works as expected. Not sure exactly what makes it go belly up in Germany though.

Steps to reproduce would be to rent a VPS in germany and install the bot.

EDIT: found the other issue where the server is located in germany: #1499

**Comment by jbfriedrich** [comment]
@Trustmega You are correct, I am located in Germany. I have the problem with several providers. I tested DigitalOcean VPS with their data center in Frankfurt and Hetzner Cloud who have their datacenter in Nürnberg and have no connection with each other. The server region where my Discord is located is "Amsterdam". I tried a direct installation and a Docker container. Both show the same issue for me.

**Comment by Trustmega** [comment]
@jbfriedrich Interesting, that would mean my assumption of something in Germany making the bot disconnect correct. @jaydenkieran any idea what might cause that?

**Comment by jbfriedrich** [comment]
@Trustmega But I would think the server location for the Discord is the same for you, right? Are you using Amsterdam as well or another Discord region?

**Comment by Trustmega** [comment]
@jbfriedrich yes exactly i'm also using Amsterdam as my discord region.

Germany has some wierd youtube-restrictions right? Perhaps that's part of the problem? Even though it seems to fail at connecting to the discordserver the youtube stuff might result in that kind of wierd behaviour.

I haven't dived into the code so i'm just speculating right now.

**Comment by mwallis45** [comment]
some time when trying to connect the bot will not be able to connect to most server locations. this is a discord thing with no fix from are end. If you do look around you may be able to find places that the bot works fine in. Your probably already do. Happy listening. also keep talking if you want dont mind me.

**Comment by jbfriedrich** [comment]
> Germany has some wierd youtube-restrictions right? Perhaps that's part of the problem? Even though it seems to fail at connecting to the discordserver the youtube stuff might result in that kind of wierd behaviour.
> I haven't dived into the code so i'm just speculating right now.

That is the complete wrong direction IMHO 😃. Yes, there are weird restrictions on Youtube's side, but that means the video is either not listed at all or you get an error the video is not available. But the issue itself is with the registration with the Discord before any music is played at all.

**Comment by MattBSG** [comment]
Going to close this issue as it appears to be narrowed down to a discord issue (especially with Amsterdam voice region). If you have any other updates to this or believe otherwise please feel free to reopen.
