### ISSUE TITLE
Music Bot Won't run because wasn't installed using Git

### ISSUE THREAD

**Issue by MotherUdder** [Just-Some-Bots/MusicBot#1443]
![please help](https://user-images.githubusercontent.com/34903354/34399003-74074154-eb51-11e7-9a6c-243b5b64f31a.png)     idk what to do to get it running again

**Comment by jayktaylor** [comment]
The bot wasn’t installed using Git. As in, you haven’t properly installed it using the guides on our wiki. Use https://github.com/Just-Some-Bots/MusicBot/wiki.
