### ISSUE TITLE
Problems with Bot

### ISSUE THREAD

**Issue by Juz311** [Just-Some-Bots/MusicBot#1444]
When I load up the bot, it comes on, then disconnects and tries to autosummon back to the channel. After it does that, when I request music (!play *youtube link*), it disconnect and reconnect to play nothing. When I request music again, it tells me that I'm in queue for some reason. I've tried updating the bot with "update_deps.bat", I've tried deleting and making a new file for the bot, but none of them work.

**Comment by leepage87** [comment]
I'm also having the same problem.  I'm running the bot off my Windows 10 machine and off my Raspberry Pi, both stopped working at about the same time with the same symptoms as Juz311 had.

**Comment by BraTaylor** [comment]
Same for me, I've tried updating and then running the dependency updates. Now it plays music for a second and then stops, before updating I was having the exact same Disconnect reconnect issue, *update - After a few more tries of kicking it from the server, re-inviting it, updating and reinstalling dependencies it still just disconnects and reconnects from the server when adding a song to the list.

**Comment by jayktaylor** [comment]
update_deps.bat does not update the bot, it updates the dependencies required for the bot to work. If you start your bot and it says ‘Connected! MusicBot v1.9.5_2’, you need to update to 1.9.6 using these steps: https://github.com/Just-Some-Bots/MusicBot/wiki/Updating

**Comment by BraTaylor** [comment]
Resolved by backing up config files, turfing the whole thing and reinstalling it, Still had to manually reisnstall the youtube-dl and websockets, the youtube-dl was fine but websockets gave a bit of trouble
