### ISSUE TITLE
Update PPA url for deadsnakes on wiki

### ISSUE THREAD

**Issue by asottile** [Just-Some-Bots/MusicBot#1445]
Hello, deadsnakes maintainer here :)

from https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Raspbian

You can now add the ppa with the following command:

```bash
add-apt-repository ppa:deadsnakes
```

**Comment by asottile** [comment]
Also here it seems: https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Ubuntu

**Comment by jayktaylor** [comment]
Hey Anthony,

Thanks for raising this. I've updated the respective guides.
