### ISSUE TITLE
My Discord Bot connects to the server, receives command but doesn't play any music. 

### ISSUE THREAD

**Issue by yusketamura** [Just-Some-Bots/MusicBot#1446]
Title saids it all. It connects to the server responds to commands but doesn't play any music even auto ones. It just stops at auto-playing.... or play youtube.com/(insert).. and stops

**Comment by jayktaylor** [comment]
Can you post your logs/musicbot.log file?

**Comment by yusketamura** [comment]
I can't find a log folder as far as I can see. I can post the console of it running.

**Comment by yusketamura** [comment]
![image](https://user-images.githubusercontent.com/34957467/34452966-acffdcce-ecfe-11e7-8ece-d11546ffe41d.png)

**Comment by jayktaylor** [comment]
Can you update your bot and dependencies to 1.9.6? It looks like you might be using an old version. https://github.com/Just-Some-Bots/MusicBot/wiki/Updating
