### ISSUE TITLE
Update_Dependencies.bat Error

### ISSUE THREAD

**Issue by EronVirson** [Just-Some-Bots/MusicBot#1450]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have (tried to) updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x] I am running version 1.9.6_1 of MusicBot

----

### Description of issue
Hi,
I'm trying to update to the newest version of MusicBot but I'm having some issues. I've gotten to the step where you are to run update_dependencies.bat but its giving an error I'm not sure how to fix. I followed all the steps up to this point, even un/re-installed Python to see if that was the problem.

### Steps to reproduce

1. Run update_dependencies.bat

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.
![-dependencieserror](https://user-images.githubusercontent.com/29404954/34464041-255356de-ee3e-11e7-9a00-ea93330c5528.png)

**Comment by jayktaylor** [comment]
Hi, it looks like your system is trying to update the dependencies using Python 2.7, which we don't support (we support 3.5+). Either consider uninstalling Python 2, or try running `py -3 -m pip install -r requirements.txt` inside the musicbot folder (right-click inside => 'Git Bash here')

**Comment by EronVirson** [comment]
Seems I had a number of old Python versions left in my files.... Thanks for the help.

**Comment by jayktaylor** [comment]
No problem :)
