### ISSUE TITLE
JSON DECODE error

### ISSUE THREAD

**Issue by Wisperer** [Just-Some-Bots/MusicBot#1451]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [X ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X ] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x] I am running version 1.9.6_1 of MusicBot

----

### Description of issue
I'm currently have an issue with the bot accepting searches or YouTube URLs. I get a JSON decoding error. I've followed the guide to a Tee. 
This is the Debug output when it starts up: https://pastebin.com/BUw20p9N

And this is the output when !play <Anything> is tried: https://pastebin.com/UyycrKR0
I used test as a test. Anything with cause this error.
### Steps to reproduce

1. Installed a Fresh Arch Linux system.

2. Followed (Ubuntu) guide to the letter. I did have to identify a few dependencies by searching with pacman -Ss. I substituted commends as needed as well. Before you ask it DOES run on Arch systems. I set it up on a different Arch system for testing and it worked with no issue.

3. Do python3 run.py

4. search with anything with !play <Search>

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

**Comment by jayktaylor** [comment]
This seems like a youtube-dl issue that isn't confined to just Arch, however with my tests (on Windows), `!play https://youtube.com/watch?v=i-YykLXxTzk` worked fine. What version of youtube-dl are you using? You should be able to use `python3 -m pip list` or similar to determine.

**Comment by Wisperer** [comment]
Hm. Well as i said above I did get it running on a different Arch system. I tested it on my Home PC before trying to set it up on a Dedi Server I'm renting out from Kimsufi. I run a file server/seedbox off it as well. I shut that down though to eliminate anything. 
 I'm running youtube-dl (2017.12.31)

Here's the full output for reference: https://pastebin.com/qf5xqn4k

**Comment by Wisperer** [comment]
Manually running youtube-dl seems to work. So somehow the string isn't getting passed to youtube-dl from the bot.

**Comment by amit177** [comment]
Closing this as it's most likely fixed on the newer versions, let us know if you see it again.
