### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by KoreanAsian** [Just-Some-Bots/MusicBot#1455]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [X] I am running version 1.9.6_1 of MusicBot

----

### Description of issue

The bot is joining just fine, seems to be downloading and and caching videos just fine but no audio is going through. It says in the chat that the song is playing and there's voice activity as well. The volume is also turned up.

### Steps to reproduce

1. Used *git clone https://github.com/Just-Some-Bots/MusicBot.git MusicBot -b master cd MusicBot* to download the bot onto my server
2. Tried both "python3 run.py" and "python3.5 run.py"

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1607681/musicbot.log)

**Comment by jayktaylor** [comment]
Does this happen with every song or just one? It's just that from your log you only seem to be trying to play a particular song. Also check to see if deleting the `audio_cache` folder and then trying to play the song again has an impact.

**Comment by KoreanAsian** [comment]
I have tried other songs as well, it was just that one song in the logs because i tried downloading the bot files just in case something was corrupted.

**Comment by v1nicin** [comment]
I have the same problem, even the green voice indicator wont turn on, i don't get any errors inside the cmd tho.

**Comment by KoreanAsian** [comment]
I get the green indicator but no sound, even with the bot volume at 1.0 and user setting on max

**Comment by ScubaDiving** [comment]
I had this problem too, just reinstall the bot entirely (you can keep permissions and options config files).

**Comment by KoreanAsian** [comment]
I have tried that as well as getting another server and reinstalling my OS

**Comment by KoreanAsian** [comment]
So, I literally have no idea what happened but it is working normally now. I did not change anything at all, I left the server exactly the way it was when I filed this help thread and decided to try it again today just in case it might have been on the server host side, which seems like it might have been.

**Comment by jayktaylor** [comment]
Sounds good. I'll close this, let us know if there are more issues.
