### ISSUE TITLE
Two servers and status

### ISSUE THREAD

**Issue by falcon4fun** [Just-Some-Bots/MusicBot#1458]
Review build.
Bot shows wrongs status if:
1. on two servers through BindToChannels and AutojoinChannels
2. playing random from autoplaylist.

If autopaused (on exiting all users) it will show 1 track in status for 2 servers
I.e.

1st srv: Now Playing: Elohim & Whethan - Sleepy Eyes [0:00:3/0:03:23]
2nd srv: Now Playing: DJ Envy - Text Ur Number (feat. DJ Sliink & Fetty Wap) [Audio Only] [0:00:51/0:04:2]
Pausing all servers. Status on two servers: https://i.imgur.com/uEVolWc.png
Skip track on 2nd -> status changes -> Exit voice -> Enter voice on 1st -> skip track -> nth changes on status
So, status song = 2nd server song.

Maybe any solution to show correct track to every server? (:

**Comment by jayktaylor** [comment]
First, in future please create your issue using the template that is provided. It is there for a reason for you to fill in. Secondly, I'm not really sure what you're asking for here, but this seems like intended behaviour. If the bot is only **playing** music on one server, it will only have that song in its 'Playing' status. If it is playing on more than one, it will use the 'Playing on x servers' status.

If the music is paused, that server counts as 'not playing' and therefore, if one server is paused and the other plays a new song, it will display that song as its status.

**Comment by falcon4fun** [comment]
>  If the bot is only playing music on one server, it will only have that song in its 'Playing' status

Nope. It will not. Look at first post
> If one server is paused and the other plays a new song, it will display that song as its status.

Yes. It will. BUT that music which is paused ON 2nd server ( : Look at first post

And it will always show the status of music on 2nd server, even if 1st playing.
Steps to reproduce was before. Look at first post. Try them.
I tryed to describe as much as posible to check this situation

> First, in future please create your issue using the template that is provided

Every developers wants to play with my bears, drink vodka, gamble blackjack with putanas and play on balalayka a.k.a "their specific rules for bugreport". Sry, but I can't make them all complete. Steps to reproduce are step by step. Ver is included as latest. Writing fcuking simple bugrep cause VERY HUGE time for me, so it is ASIS : ¯\_(ツ)_/¯ Moreover, DEV is more interested in his cocroaches, ants and other insects, than I. ( :
Finally, I can live with them or wait another user to make "feng-shui" rep which and only which dev can read. (( : Follow the crumb trail :D 

P.S. More screenshots for god of screenshots
https://i.imgur.com/8P62y6c.png

P.P.S. Hm. There is a tricky situation.
Something is with the status updating events I think.
1. Enter 2nd srv channel. Wait status playing and NP is correct
2. Exit 2nd srv. Wait status shows "paused"
3. Enter 1st srv channel.
..
5. Profit. Music will play. But status will not update upon track skip/end. As u can see it shows paused, but music playing on 1st server: https://i.imgur.com/XD3SOiB.png
But after the track skip/end it works correctly: https://i.imgur.com/tfcw3zl.png
Look at the event updating or smth (don't know how it works really) : )

P.P.P.S. If not worked try this: Repeat x2+ times {enter first, exit first, enter second, exit second} For me after second interation status updating will break and show "paused" when music starts to play (: 
 

I SUPPOSE THIS TONN OF TEXT WILL BE ENOUGH TO UNDERSTAND THE PROBLEM, ISN'T? :DD

**Comment by jayktaylor** [comment]
The bug report template asks you to tick literally just four checkboxes, describe your issue, add repro steps, and provide your log. You never actually sent your log either, which has information about when events like pausing and resuming occur so that I can help debug the issue. Maybe you should be more appreciative of the bot you are using which other people have developed for you, rather than complaining about having to provide some **basic information** for a bug report.

Alas, I've located a potential source of the issue you're raising and will look into fixing it for 1.9.7. Thanks.

**Comment by falcon4fun** [comment]
@jaydenkieran Sorry for causing problems :D

**Comment by jayktaylor** [comment]
Hi again. I've looked into this further and the issue I found was actually unrelated. I think the cause of the problem you're experiencing is because Discord rate limits presence updates (e.g changing your 'Playing' status) to something like 5 every 60 seconds. If your bot is exceeding this limit, it will not change its status.

**Comment by falcon4fun** [comment]
Hm. Tryed to simulate many status changes. Yeap. Really. ;/ Sorry for bothering then ¯\_(ツ)_/¯
