### ISSUE TITLE
Bot used to work fine, now will not connect.

### ISSUE THREAD

**Issue by Nathan-Bunge** [Just-Some-Bots/MusicBot#1459]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x] I am running version 1.9.6_1 of MusicBot

----

### Description of issue
Recently the bot will connect to a server, but once it tries to join any voice channel, it will turn off and reset. 

### Steps to reproduce

1. I tried different versions of python 3.5, but they all have the same result.
2. Re-downloading the bot, same result

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.
Cant find the logs/musicbot.log, but here is a screenshot of the runbot.bat
https://www.python.org/ftp/python/3.5.3/python-3.5.3-embed-win32.zip

**Comment by jayktaylor** [comment]
Can you attach a screenshot of your console if you don't have a log file (which you definitely should)? Your link is for the Python download.

**Comment by Nathan-Bunge** [comment]
![code](https://user-images.githubusercontent.com/35204317/34659300-2d9a0bd6-f3ec-11e7-8d50-b3907ee1eaf5.JPG)

Sorry, not sure what happened there

**Comment by Nathan-Bunge** [comment]
![capture](https://user-images.githubusercontent.com/35204317/34659309-55fd4872-f3ec-11e7-92c6-1d04331e2162.JPG)
This is what it first says

Also, where can you find the log?

**Comment by jayktaylor** [comment]
You ticked `I am running version 1.9.6_1 of MusicBot` when creating your issue but you aren't, you're running 1.9.5_2. Please update: https://github.com/Just-Some-Bots/MusicBot/wiki/Updating.
