### ISSUE TITLE
[Suggestion] Autoclean feature

### ISSUE THREAD

**Issue by pete-nerantzinis** [Just-Some-Bots/MusicBot#146]
Autoclean the users chat commands right after they are used like !play or !np to keep command chat clean and show bot text and user normal chat.

**Comment by lavender-sys** [comment]
This already happens. It just doesn't erase the command. So it would be like this. 

Dog2puppy: !np
Bot: playing: unknown
[5Minutes later]
Dog2puppy: !np
[Message Deleted]

**Comment by imayhaveborkedit** [comment]
Implemented in review.
