### ISSUE TITLE
Autoplaylist songs auto removed during service instability.

### ISSUE THREAD

**Issue by alexixiv** [Just-Some-Bots/MusicBot#1461]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x ] I am running version 1.9.6_1 of MusicBot

----

### Description of issue
Please add a feature allowing songs to be commented out when they are unplayable so they can be reviewed and manually removed as the current feature causes songs to be removed when there is any interruption in service resulting in packet loss. This would be helpful as my ISP is not very reliable.

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

**Comment by jayktaylor** [comment]
The current system moves removed songs to another txt file. If commenting out is something you want instead, I guess we can change it to that.
