### ISSUE TITLE
Stream Links to Work in Autoplaylist

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1462]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x] I am running version 1.9.6_1 of MusicBot

----

### Description of issue

Hi all,
we can stream online radio via !stream command, but after some time bot stops playing streamed radio. Can we add online radio link in autoplaylist to permanently play the radio? Currently seems it doesn't work if I put the link in the autoplaylist.txt.

**Comment by ImthePeach** [comment]
The autoplaylist is currenly designed to work like the normal `!play` command and is for individual songs so adding an stream link will not work in the autoplaylist. Adding the ability for the bot to play streams via the autoplaylist would be a feature request.
