### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by comosaw** [Just-Some-Bots/MusicBot#1464]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [ ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [ ] I am running version 1.9.6_1 of MusicBot

----

### Description of issue
it just shuts down the bot and calls an error
i dont know if i did something wrong cause i followed what i was told in the help text

### Log ###
Python 3.5.2
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 346, in main
    from musicbot import MusicBot
  File "/Users/pontusmoller/Desktop/MusicBot/musicbot/__init__.py", line 74, in <module>
    from .bot import MusicBot
  File "/Users/pontusmoller/Desktop/MusicBot/musicbot/bot.py", line 44, in <module>
    load_opus_lib()
  File "/Users/pontusmoller/Desktop/MusicBot/musicbot/opus_loader.py", line 17, in load_opus_lib
    raise RuntimeError('Could not load an opus lib. Tried %s' % (', '.join(opus_libs)))
RuntimeError: Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib

[INFO] launcher: All done.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Processen slutförd]

**Comment by jayktaylor** [comment]
Invalid issue - you didn't check any boxes. To solve your issue, follow https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Windows carefully (or whatever is applicable for your system).
