### ISSUE TITLE
GrantToRoles command not working with several role ids

### ISSUE THREAD

**Issue by Einherier** [Just-Some-Bots/MusicBot#1465]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [ x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x ] I am running version 1.9.6_1 of MusicBot

----

### Description of issue
hey guys, I got the issue that the music bot is not able to give out the same permission group to several role ids on my server. It says in the config infos that you can use several role ids when you seperate them with a blank space, but everyone except one of our groups(which has only one group id assigned) got the default group. So i went ahead and double checked every line of code to make sure that i didn't messed up anywhere, but it turned out that all groups were properly written, and the only difference was that the one working group only had one role id assigned. So i deleted all but one role id's out of the GrantToRoles command, and viola, it worked. Question now is: Is there a way to fix it so i can grant the permission group to several role id's or do i have to make a group for each role id seperatly? 
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1626957/musicbot.log)
code of one of the non working groups in question: [Regular User]
 GrantToRoles = 327190703430172674,327190778357219328,334362834068832257
CommandBlacklist = blacklist listids
;UserList = 
MaxSongLength = 0
MaxSongs = 0
MaxPlaylistLength = 0
AllowPlaylists = yes
InstaSkip = yes

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

**Comment by jayktaylor** [comment]
Separate the IDs using spaces, not commas.

**Comment by Einherier** [comment]
allready did that, didn't worked either

**Comment by jayktaylor** [comment]
Did you restart the bot entirely when changing it? Also, make sure not to remove or rename your `[Default]` group from the file, as that is necessary to remain the same name. If it still isn't working, send your permissions file here and I'll take a look.

**Comment by Einherier** [comment]
jeah i restarted it several time, and i didn't touched the default group. as i said it is working if there is only one group id asigned to the permissions group, but it doesn't want to work with several ones. 
[Default]
CommandWhitelist = play perms queue np skip search id help clean
; CommandBlacklist =
IgnoreNonVoice = play skip search
MaxSongLength = 1200
MaxSongs = 0
AllowPlaylists = yes
; MaxPlaylistLength = 20
InstaSkip = no

; This group has full permissions.
[Mastermind]
 GrantToRoles = 327190669779271681
; UserList =
MaxSongLength = 0
MaxSongs = 0
MaxPlaylistLength = 0
AllowPlaylists = yes
InstaSkip = yes

; This group can't use the blacklist and listids commands, but otherwise has full permissions.
[Regular User]
 GrantToRoles = 327190703430172674 327190778357219328 334362834068832257
CommandBlacklist = blacklist listids
;UserList = 
MaxSongLength = 0
MaxSongs = 0
MaxPlaylistLength = 0
AllowPlaylists = yes
InstaSkip = yes

; This group can only use the listed commands, can only use play/skip when in the bot's voice channel,
; can't request songs longer than 5 minutes, and can only request a maximum of 8 songs at a time.
[Limited User]
CommandWhitelist = play queue np perms help skip
; CommandBlacklist =
IgnoreNonVoice = play skip
 GrantToRoles = 332646428356640770 327190813853483008 334362834068832257 327190778357219328
MaxSongLength = 300
MaxSongs = 8
AllowPlaylists = yes
InstaSkip = no
