### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by christiancadz** [Just-Some-Bots/MusicBot#1466]
![image](https://user-images.githubusercontent.com/35401083/34907065-f3a556ce-f85f-11e7-9642-dbb249228cd8.png)

**Comment by jayktaylor** [comment]
Follow the guide for your system on https://just-some-bots.github.io/MusicBot/. The message is fairly self explanatory - if you downloaded a ZIP file to install the bot, rather than using Git, then you have installed the bot incorrectly.
