### ISSUE TITLE
The music bot does not pre-load songs from autoplaylist

### ISSUE THREAD

**Issue by marco2310** [Just-Some-Bots/MusicBot#1468]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x] I am running version 1.9.6_1 of MusicBot

----

### Description of issue

The music bot does not preload songs from autoplaylist when the current music is playing. It does works in preloading music when I placed a song requires to the bot. But the music bot then starts to download a new song from the auto playlist after the required song is played. So now there is a space about 30 to 60 seconds between current song and the coming song, it does not play anything until the song is downloaded.

Thanks,

### Steps to reproduce

1. 
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1635029/musicbot.log)

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

**Comment by MattBSG** [comment]
Hi. Due to the way the autoplaylist only runs if nothing else is queued when the last song ends, it only starts after that check runs (else it might download still in the background if you queued a song last second before the current one ended). Tagged as feature request.

**Comment by marco2310** [comment]
Hi Matt,

But in the last version, I had installed the bot(before the discord updated), The music bot did not have any problems like this. Even when I play a new video/song that I had never played, it doesn't have such a long space/delay. I just ask my friend about this issue, then he told me that he doesn't have such problem in his bot, the bot works perfectly on his computer. So I am wondering if this is any problem/error in my bot.

**Comment by MattBSG** [comment]
The autoplaylist has never pre-downloaded to my knowledge, but your speed issue may be related to #1469 (which seems to be a youtube-dl thing, so we can’t do anything). I know the download time is frustrating. Could you run a Speedtest for me to make sure it isn’t a network issue on your end?

**Comment by amit177** [comment]
Closing this as we've received no reply.
