### ISSUE TITLE
Queue fo commans

### ISSUE THREAD

**Issue by EstherTMB** [Just-Some-Bots/MusicBot#147]
If the send to the bot !skip command, you get an error:

> ```
> Exception in thread Thread-36:
> Traceback (most recent call last):
>   File "C:\Users\Esther\AppData\Local\Programs\Python\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "C:\Users\Esther\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 87, in run
>     data = self.buff.read(self.frame_size)
>   File "C:\Users\Esther\Desktop\MusicBot-review\musicbot\player.py", line 24, in read
>     frame = self.buff.read(frame_size)
> ValueError: read of closed file
> ```

**Comment by imayhaveborkedit** [comment]
Are you sure this was caused by using a command?  If you can reliably reproduce this, please tell me how.
