### ISSUE TITLE
Songs Disconnecting the Bot.

### ISSUE THREAD

**Issue by W1Ndextor** [Just-Some-Bots/MusicBot#1470]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [X] I am running version 1.9.6_1 of MusicBot

----

### Description of issue
Music bot will take a song request, then disconnect from voice channel before playing, then reconnect. when the bot reconnects using the command !np will indicate the requested song is playing but no audio can be heard. Volumes are up so it is not a volume issue.

### Steps to reproduce

1. go activate the bot.
2.request a song.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

Searched entire hard drive. no log file found for whatever reason.

**Comment by jayktaylor** [comment]
You ticked the `I am running version 1.9.6_1 of MusicBot` checkbox, but considering you have no log file (which was introduced in 1.9.6) and are having this issue, I suspect you are using the older version, 1.9.5_2 instead. See https://github.com/Just-Some-Bots/MusicBot/issues/1433#issuecomment-353684748 for help.
