### ISSUE TITLE
Cannot play SoundCloud songs.

### ISSUE THREAD

**Issue by ac96789** [Just-Some-Bots/MusicBot#1471]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x] I am running version 1.9.6_1 of MusicBot

----

### Description of issue
Cannot play SoundCloud songs.

[0;31mERROR:[0m Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>)

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1642955/musicbot.log)

**Comment by MattBSG** [comment]
This is a youtube-dl issue, you can follow the issue at [#15306](https://github.com/rg3/youtube-dl/issues/15306)

**Comment by jayktaylor** [comment]
youtube-dl resolved this in release 2018.01.18. Update your dependencies.
