### ISSUE TITLE
Losing internet connection causes the bot to loop through the autoplaylist

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1472]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [ x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x ] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [ x ] I am running version 1.9.6_1 of MusicBot

----

### Description of issue
Losing internet connection causes the bot to loop through the autoplaylist after reconnecting **but not playing any songs**. Also when there is no connection the bot seems to remove the songs that couldn't be downloaded from the autoplaylist which isn't ideal.

### Aditional information

- I am running the bot on a Raspberry Pi 3

### Steps to reproduce

1. Start bot
2. Disable internet connection

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1644130/musicbot.log)

**Comment by ghost** [comment]
So I just did a small fix for myself. I don't have much knowledge about python nor have I the time to study/analysis your code **so this isn't very thought out**... But its working for me
_A real fix would be appreciated!_

I added this small code into the _reconnect_voice_client method_ which restarts the bot completely.
For small disconnects, this works as it should. If the internet connection is down for a long time it won't work but the bot seems so throw some exception/or error signal which restarts my service automatically.
So running the bot as a systemd service is required for this fix and you should also set the restart parameter in your .service file.

```python
async def reconnect_voice_client(self, server, *, sleep=0.1, channel=None):
tasks = [
asyncio.ensure_future(self.restart())
]
self.loop.run_until_complete(asyncio.wait(tasks))

```

**Comment by Munzy** [comment]
Might be able to check a online resource exists before deleting a song from autoplaylist. 


if song failed to download, then check to see if we have valid internet connection, then delete else skip to next song.

**Comment by jayktaylor** [comment]
An option has been added to turn off the removing from autoplaylist behaviour in https://github.com/Just-Some-Bots/MusicBot/commit/3910cc6d601a97bbc6d6dd8284aabf478bfc0afa.

**Comment by AutumnClove** [comment]
Closing because Option was added to stop this.
