### ISSUE TITLE
Need to rejoin to hear bot

### ISSUE THREAD

**Issue by chromoboi** [Just-Some-Bots/MusicBot#1473]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x] I am running version 1.9.6_1 of MusicBot

----

### Description of issue
Whenever the bot joins a channel the users have to rejoin the channel to be able to actually hear the bot, doesnt matter whether it was dragged or !summoned

### Steps to reproduce

1. have bot leave a channel and then join that channel

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1644490/musicbot.log)

**Comment by Seth-Revz** [comment]
I second this

**Comment by MattBSG** [comment]
This seems like a discord bug, not a problem with our bot. It only sends to audio to discord, if certain people can't hear and need to rejoin that is most certainly a Discord problem. They accept bug reports over at https://discord.gg/discord-testers

If you have other details to provide, comment and we'll reopen the issue if warranted.
