### ISSUE TITLE
Autoplaylist is not checking user present on start

### ISSUE THREAD

**Issue by falcon4fun** [Just-Some-Bots/MusicBot#1477]
I have found quite an old bug. It's like a bot doesn't verifies if there is somebody in the voice while using:
1. Autoconnect to channel on start
2. Autoplay enabled
3. Autopause enabled

I have found that every time when bot starts/relaunches, it starts to play music on all servers even nobody in the voice. And the solution is enter to voice and exit, then bot see that
Can you try reproduce? (: If ya, add initial checking. I tryed to do it by my self, but failed (: 

To reproduce:
1. Enable ^ 3 options
2. Add some tracks to autoplaylist.txt
3. Launch bot
4. Go to your TEXT channel and write !np and see, that music is playing but it should not :)
Tryed on review build. Still present.. :)
[https://i.imgur.com/bV88mLx.png](https://i.imgur.com/bV88mLx.png)

https://cdn.discordapp.com/attachments/252967574168535040/404804293648973835/unknown.png
https://pastebin.com/hMrNFYYT

**Comment by itsTheFae** [comment]
I've noticed this as well.    
There is a check coded in `_join_startup_channels()` but the conditions as they are now have a little issue which prevents the one-shot lambda from being run.  I've created a patch for this as well as Issue #1482 targeting the latest review branch.   

Devs can find the patch commits here:  https://github.com/itsTheFae/DiscordMusicBot/tree/patch-auto-pause

**Comment by falcon4fun** [comment]
I have found that sometimes it works.. I disabled equalisation.

In log:

> Initial autopause in empty channel
> Initial autopause in empty channel

**Comment by itsTheFae** [comment]
In my case, the bot is always restoring a serialized queue when it starts.  I suspect the restoration of the queue might contribute to the auto-pause failure condition on this issue as well as mine..   
Not totally sure, I trust the devs here would know better than me.

**Comment by jayktaylor** [comment]
Should've been fixed by the above PR.
