### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by streamkiller** [Just-Some-Bots/MusicBot#1479]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [ x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [ x] I am running version 1.9.6_1 of MusicBot (im running latest)

----

### Description of issue
Suggestion download all song in autoplaylist. So it's cached for example !download autoplaylist 

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

**Comment by MattBSG** [comment]
That would need an awfully large amount of network transfer (bad for people on hosts). The current implementation that just downloads and caches on first play of each song is much better as it downloads as it goes along
