### ISSUE TITLE
Auto playlist

### ISSUE THREAD

**Issue by ExtendedTigris** [Just-Some-Bots/MusicBot#148]
So when I would load a song with !play https://www.youtube.com/watch?v=85ftfVUTzM4 (Just a song) when the AutoPlaylist is going it will stay going from that list not the one you set

**Comment by imayhaveborkedit** [comment]
If you add a song to the queue when an autoplaylist song is going, the song will continue to play, but the queued song should play when it finishes.  If the song is listed in the queue (`!queue`), it should work fine.
