### ISSUE TITLE
Reconnecting for no reason

### ISSUE THREAD

**Issue by streamkiller** [Just-Some-Bots/MusicBot#1480]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x ] I am running version 1.9.6_2 of MusicBot

----

### Description of issue
Error in ssl transport,

This is console error: Download cached: https://www.youtube.com/watch?v=Bs3f2kyi2F0
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x06FA7A10>
transport: <_SelectorSocketTransport closing fd=528 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "C:\Users\denni\AppData\Local\Programs\Python\Python36-32\lib\asyncio\sslproto.py", line 636, in _process_write_backlog
    ssldata, offset = self._sslpipe.feed_appdata(data, offset)
AttributeError: 'NoneType' object has no attribute 'feed_appdata'
Task exception was never retrieved
future: <Task finished coro=<VoiceClient.poll_voice_ws() done, defined at C:\Users\denni\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\voice_client.py:269> exception=ConnectionClosed('WebSocket connection is closed: code = 4014, reason = Disconnected..',)>
Traceback (most recent call last):
  File "C:\Users\denni\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\gateway.py", line 676, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "C:\Users\denni\AppData\Local\Programs\Python\Python36-32\lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "C:\Users\denni\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py", line 319, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4014, reason = Disconnected..

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\denni\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\voice_client.py", line 276, in poll_voice_ws
    yield from self.ws.poll_event()
  File "C:\Users\denni\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\gateway.py", line 679, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4014, reason = Disconnected..
WARNING: Failed to connect, retrying (1/5)
WARNING: Failed to connect, retrying (2/5)
405104231964737536/DJ_Sir#1154 has joined GGsirGaming/24/7 Boosted music!!!!
Connected to GGsirGaming/24/7 Boosted music!!!!

### Steps to reproduce

1. It happens now and then

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

Look at time 2018-01-23 05:08:15,705
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1654706/musicbot.log)

**Comment by AutumnClove** [comment]
I think this has more to do with discords API, than the code. However, I'm not a dev. I can confirm that the discord API went down 4 times the other day, it goes down quite a bit unfortunately. The code has gotten better at handling, but still needs some work.

**Comment by endms3231** [comment]
the condition of this error is when more than thirty minutes of video is played

**Comment by MattBSG** [comment]
Can you confirm this is still happening?

**Comment by Harmon758** [comment]
> Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x06FA7A10>
transport: <_SelectorSocketTransport closing fd=528 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
File "C:\Users\denni\AppData\Local\Programs\Python\Python36-32\lib\asyncio\sslproto.py", line 636, in _process_write_backlog
ssldata, offset = self._sslpipe.feed_appdata(data, offset)
AttributeError: 'NoneType' object has no attribute 'feed_appdata'

This was an [issue with asyncio](https://bugs.python.org/issue33037) and should be fixed in Python 3.6.5 now.

**Comment by MattBSG** [comment]
The only issue is we currently have some campatibility issues with 3.6, which is why we currently direct to use 3.5.x so we’ll have to look into getting fixes. I’m going to leave this open for now as a current standing solution, thank you @Harmon758

**Comment by jayktaylor** [comment]
This should be okay now. Reconnects should be handled by discord.py.
