### ISSUE TITLE
Error 503 command play

### ISSUE THREAD

**Issue by Giikuzawa** [Just-Some-Bots/MusicBot#1485]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [yes ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [yes ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [yes ] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [ yes] I am running version 1.9.6_2 of MusicBot

----

### Description of issue
I have a problem: the bot gives an error when I write the command to play a song. Error text: 
ERROR: Unable to download API page: HTTP Error 503: Service Unavailable (caused by <HTTPError 503: 'Service Unavailable'>)
Can anyone help? I would be grateful.

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1671369/musicbot.log)

**Comment by jayktaylor** [comment]
Please provide reproduction steps.

**Comment by Giikuzawa** [comment]
@jaydenkieran What?

**Comment by jayktaylor** [comment]
You need to provide the steps that you took for this bug to occur, such as the command(s) you used, the URL(s) you used, in what order you did the commands in. Essentially, give a step-by-step guide of reproducing the bug.

**Comment by Giikuzawa** [comment]
@jaydenkieran The error itself after some time after the work of the bot on the hosting linux ubuntu 16. The error is: write a command to play, the bot writes in the chat error which says error 502, which was described above in the description of the issue. If you write a team to play and the name of the song, there was an error, but if write command and a link to the song (e.g. YouTube), then there is no error. That is, the error only appears when song search on YouTube using the name. (Example: /play Marshmallo - Alone)

**Comment by MattBSG** [comment]
Please attempt to update your dependencies and bot anyway by running `update_dependencies.bat` and following this guide https://just-some-bots.github.io/MusicBot/#guidesupdating then report back.

**Comment by MattBSG** [comment]
Closing due to no response. Feel free to reopen if you did as I said above and still have problems.
