### ISSUE TITLE
[Feature request] skipto command

### ISSUE THREAD

**Issue by Leomelonseeds** [Just-Some-Bots/MusicBot#1486]
I have a suggestion for more commands that would certainly be helpful for everyone:

!seek: Go to a certain point in a song
!ap (from #1372 )
!clear [number]: Clear a certain entry in the queue
!skipto: Skip to a certain entry in queue
!move: Move an entry in queue to a different position
!forward: Foward by certain amount in track
!replay: Resets progress of song
!rewind: Rewind certain amount in song
!loop [amount]: Loops current song
These are mostly commands from Rythm :P

The most useful commands would certainly be !clear [number] and !replay.
Let me know what you think 😄

**Comment by jayktaylor** [comment]
seeking: #452 
removing a song: in review
forward: same as seeking
rewind: same as seeking
replay: #486 
loop: #128 

----

As a result, going to change this issue to a request for 'skipto' only.

**Comment by Leomelonseeds** [comment]
Thanks for the quick reply! 
I hope these get implemented soon, I also just looked at the new wiki, and it seems like some of these commands are already being implemented :P

**Comment by Stephanoao** [comment]
Hello, i think that the skipto or a "get intro" a poweramp plug in thal allow to listen just few seconds of a track it could be just GREAT to find a music between tons.

**Comment by AutumnClove** [comment]
I merged review into #1580 so you can try that out sorry it's been like a year lol
