### ISSUE TITLE
Bot not responding to commands

### ISSUE THREAD

**Issue by heolthetic** [Just-Some-Bots/MusicBot#1489]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1672589/musicbot.log)
 ] I am running version 1.9.6_2 of MusicBot

----

### Description of issue
The bot is working perfectly, but it just doesn't respond to any command I put in.

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

**Comment by AutumnClove** [comment]
Is it just not responding to you, or is it not responding to anyone who tries to use it?

**Comment by heolthetic** [comment]
It's not responding to me and everyone else that's trying to use it.

**Comment by MattBSG** [comment]
@heolthetic This problem is best suited to be fixed on our discord server, where we can give immediate support and ask questions to try and fix this without waiting hours like an issue will take. Head on over to https://discord.gg/bots and ask away there
