### ISSUE TITLE
YouTube searching not working

### ISSUE THREAD

**Issue by ObsidiousD** [Just-Some-Bots/MusicBot#149]
I'm trying to get this music bot set up and for some reason when I type "!play" and then put something I want to search for, it just says "Unable to queue up song at _____ to be played."

In the command prompt is says there's an error that ____ is not a valid URL. Set --default-search "ytsearch". I'm especially concerned because my friend told me that my options file is not the same as his. Anyone know what I need to do to fix it?

**Comment by imayhaveborkedit** [comment]
You're using the develop version, which doesn't have that feature.  Use RC5, under Releases.

**Comment by ObsidiousD** [comment]
Thanks!
