### ISSUE TITLE
Epic Crash, Have to reinstall to get it going again

### ISSUE THREAD

**Issue by BannanaHero** [Just-Some-Bots/MusicBot#1491]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [ x] I am running version 1.9.6_2 of MusicBot

----

### Description of issue

Bot crashes and I can't use it anymore. Reinstalled, same thing happened.
I type !play "anything" I get that error. The playlist will work fine first time on install, but after I do the command !play it all breaks. !restart crashes the bot as well.

### Steps to reproduce

1. Install the music bot the official way.
2. Type !restart the bot crashes
3. Start it again type !play whateveryouwanthere get that error and it never works again. Updating restarting everything doesn't work.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1676496/musicbot.log)

**Comment by MattBSG** [comment]
Please attempt to update your dependencies and bot anyway by running update_dependencies.bat and following this guide https://just-some-bots.github.io/MusicBot/#guidesupdating then report back. Can you also tell me what link you used to get the error (ie did you play a link, just use text to search etc.).

**Comment by BannanaHero** [comment]
I conducted all of the updates, did a hard reset and updated  again. Everything says that its already up to date. The first time it crashed I typed "!play full nocopyrightsounds" the second time I put "!play https://www.youtube.com/watch?v=qODMVRDehXE" could this be an issue where I had multiple musicbots installed? Is there a way to completely uninstall the bot and start from scratch, other than delete the folder I created?

**Comment by MattBSG** [comment]
The folder itself is the bot. Can you upload your autoplaylist.txt and options.ini files after redacting your token from it?

**Comment by BannanaHero** [comment]
The latest update seems to have fixed everything.

**Comment by MattBSG** [comment]
Glad it’s working for you, I’m gonna go ahead and close this then
