### ISSUE TITLE
(feature-help) Multiple Hosts

### ISSUE THREAD

**Issue by itsRems** [Just-Some-Bots/MusicBot#1497]
Hey.
I was wondering if it was possible to make the bot run on multiple pcs to have a nice stability (I run a lot of discord servers where I use this cutsom bot at).
How am I supposed to do it whitout having every instance doing the request?
Thx.

**Comment by MattBSG** [comment]
I think what you are really looking for is sharding. Short answer, that most likely won’t happen as the bot was designed with a small amount of servers using it in mind. Long answer, maybe; a rewrite is underway and this could be something integrated at the base of it so I don’t know.
