### ISSUE TITLE
Servers

### ISSUE THREAD

**Issue by itsRems** [Just-Some-Bots/MusicBot#1498]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x] I am running version 1.9.6_2 of MusicBot

----

I recently re-added my bot to almost all of my servers but I got a BIG issue wich is that the bot only bounds to 2 of 6 servers, being connected to the others but the console saying he's not.

**Comment by MattBSG** [comment]
Hi, sorry for late really late response. Is this still an occurring issue for you? If so can you update your bot and dependencies then send your options.ini (removing your token)?

**Comment by itsRems** [comment]
Thx for the reply.
However, I'm not using the bot anymore (coding on my own)
Idk about the error tho
