### ISSUE TITLE
help command

### ISSUE THREAD

**Issue by Arzte** [Just-Some-Bots/MusicBot#15]
People are lazy and don't like to look up commands. I'd recommend having the bot pm the user who did !help in order to avoid spam of commands in whatever channel the bot is in.

**Comment by imayhaveborkedit** [comment]
There's a basic help command but a dynamically generated help command will come at some point.

**Comment by Arzte** [comment]
If its planned, might want to leave it open.

**Comment by imayhaveborkedit** [comment]
It's more a like "planned enhancement" but it's not a big deal right now.
