### ISSUE TITLE
Need help with Command list & music keep looping the same one

### ISSUE THREAD

**Issue by wanfir019** [Just-Some-Bots/MusicBot#150]
i tried to search for how to do the command list but i can't find any i tried to do the "!skip" and all from the wiki [https://github.com/SexualRhinoceros/MusicBot/wiki/Commands-list](url) and i can't seems to done any of it...? 

it also seems like i have problem with the playlist because it kept looping the same music even tho i already put other youtube music link on the autoplaylist.

anyone can help me out? i really don't know much how to mess up with the coding,any help would be appreciate :)

**Comment by deansheather** [comment]
There are some easy to follow guides in the wiki for Windows and Ubuntu 14.04. If you're having trouble with your bots (and it's not an actual issue with the code), please join our help server so one of our friendly helpers can assist you. Invite link: https://discord.gg/0iqN3da4zqpJpuY0
