### ISSUE TITLE
Can't run runbot.bat

### ISSUE THREAD

**Issue by StarkEvan** [Just-Some-Bots/MusicBot#1502]
- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x] I am running version 1.9.6_3 of MusicBot

----

### Description of issue
I can't run the bot. When I run runbot.bat, it gets failed, "[CRITICAL] launcher: Failed environment check, bot was not installed using Git. If you downloaded a ZIP, you did it wrong. Open http://bit.ly/dmbguide on your browser for official install steps."
I have installed it properly, but when I run the bot, same error message happened. What should I do?

----

[UPDATE]
Nevermind, I redownloaded and reinstalled like all of them and it worked.

**Comment by MattBSG** [comment]
Glad you figured it out, gonna close
