### ISSUE TITLE
Update script failed, twice.

### ISSUE THREAD

**Issue by diveyez** [Just-Some-Bots/MusicBot#1504]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [ x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ]x I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [ x] I am running version 1.9.6_3 of MusicBot

----

### Steps to reproduce

1. I reinstalled pip just to be sure, there is no luck.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

Setting up python-pip (9.0.1-2) ...
Setting up python2.7-dev (2.7.13-2+deb9u2) ...
Setting up python-all (2.7.13-2) ...
Setting up python-xdg (0.25-4) ...
Setting up python-secretstorage (2.3.1-2) ...
Setting up libpython-dev:amd64 (2.7.13-2) ...
Setting up python-keyring (10.1-1) ...
Setting up python-dev (2.7.13-2) ...
Setting up libpython-all-dev:amd64 (2.7.13-2) ...
Setting up python-gi (3.22.0-2) ...
Setting up python-all-dev (2.7.13-2) ...
root@base:/home/diveyez/discordbot/MusicBot# ls
bin           musicbot          runbot_osx.command
bootstrap.py  README.md         run.py
config        requirements.txt  update_dependencies.bat
Dockerfile    runbot.bat        update_dependencies_linux.sh
LICENSE       runbot_linux.sh   update_dependencies_osx.command
root@base:/home/diveyez/discordbot/MusicBot# ./update_dependencies_linux.sh
/usr/bin/python3.5: No module named pip
root@base:/home/diveyez/discordbot/MusicBot#

**Comment by jayktaylor** [comment]
Install python3-pip using your package manager.

**Comment by diveyez** [comment]
That is what I did, Here was the fix.
apt remove python2.6 -y
apt install python3-pip -y
(apt did not remove the previous version on upgrade)

**Comment by MattBSG** [comment]
Because python3-pip is an entirely new package, not an upgrade. Using `pip3` would most likely have worked without uninstalling Python 2. Good it works for you now.
