### ISSUE TITLE
No token to add to options.ini

### ISSUE THREAD

**Issue by DevCraftProductions** [Just-Some-Bots/MusicBot#1507]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [ x] I am running version 1.9.6_3 of MusicBot

----

### Description of issue

Discord does not use bot tokens anymore. How do I get the bot to work without it? The Client ID and secret does not work as the token

### Steps to reproduce

1.  Create Discord bot and see

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

![image](https://user-images.githubusercontent.com/9030370/36343328-71b6dfe8-13d0-11e8-83b4-3491436cc2cb.png)

**Comment by MattBSG** [comment]
You need to make a Bot App User on that page.
