### ISSUE TITLE
Cant start bot

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1508]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [ X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ X] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [ X] I am running version 1.9.6_3 of MusicBot

----

### Description of issue

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1734024/musicbot.log)

### Steps to reproduce

Hello, it seems I cant start my bot. I've tried to run both start and update_depencies as admin.

----

### Log file

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 346, in main
    from musicbot import MusicBot
  File "D:\Discord\BOTs\Bardi Squad Music 3\musicbot\__init__.py", line 6, in <module>
    from discord.ext.commands.bot import _get_variable
ImportError: cannot import name '_get_variable'
[INFO] launcher: Attempting to install dependencies...
Collecting discord.py[voice]~=0.16.0 (from -r requirements.txt (line 1))
  Using cached discord.py-0.16.12.tar.gz
Requirement already up-to-date: pip in c:\users\liam tuhuteru\appdata\local\programs\python\python35-32\lib\site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: youtube_dl in c:\users\liam tuhuteru\appdata\local\programs\python\python35-32\lib\site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: colorlog in c:\users\liam tuhuteru\appdata\local\programs\python\python35-32\lib\site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: cffi in c:\users\liam tuhuteru\appdata\local\programs\python\python35-32\lib\site-packages (from -r requirements.txt (line 5))
Collecting aiohttp<1.1.0,>=1.0.0 (from discord.py[voice]~=0.16.0->-r requirements.txt (line 1))
  Using cached aiohttp-1.0.5-cp35-cp35m-win32.whl
Collecting websockets<4.0,>=3.1 (from discord.py[voice]~=0.16.0->-r requirements.txt (line 1))
  Using cached websockets-3.4-cp35-cp35m-win32.whl
Requirement already up-to-date: PyNaCl==1.0.1 in c:\users\liam tuhuteru\appdata\local\programs\python\python35-32\lib\site-packages (from discord.py[voice]~=0.16.0->-r requirements.txt (line 1))
Requirement already up-to-date: colorama; sys_platform == "win32" in c:\users\liam tuhuteru\appdata\local\programs\python\python35-32\lib\site-packages (from colorlog->-r requirements.txt (line 4))
Requirement already up-to-date: pycparser in c:\users\liam tuhuteru\appdata\local\programs\python\python35-32\lib\site-packages (from cffi->-r requirements.txt (line 5))
Requirement already up-to-date: chardet in c:\users\liam tuhuteru\appdata\local\programs\python\python35-32\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.16.0->-r requirements.txt (line 1))
Requirement already up-to-date: async-timeout in c:\users\liam tuhuteru\appdata\local\programs\python\python35-32\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.16.0->-r requirements.txt (line 1))
Requirement already up-to-date: multidict>=2.0 in c:\users\liam tuhuteru\appdata\local\programs\python\python35-32\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.16.0->-r requirements.txt (line 1))
Requirement already up-to-date: six in c:\users\liam tuhuteru\appdata\local\programs\python\python35-32\lib\site-packages (from PyNaCl==1.0.1->discord.py[voice]~=0.16.0->-r requirements.txt (line 1))
Installing collected packages: aiohttp, websockets, discord.py
  Found existing installation: aiohttp 2.2.5
    Uninstalling aiohttp-2.2.5:
      Successfully uninstalled aiohttp-2.2.5
  Rolling back uninstall of aiohttp
Exception:
Traceback (most recent call last):
  File "C:\Users\Liam Tuhuteru\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Liam Tuhuteru\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\Liam Tuhuteru\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Users\Liam Tuhuteru\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\Users\Liam Tuhuteru\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\Users\Liam Tuhuteru\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Users\Liam Tuhuteru\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "C:\Users\Liam Tuhuteru\AppData\Local\Programs\Python\Python35-32\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Liam Tuhuteru\\AppData\\Local\\Programs\\Python\\Python35-32\\Lib\\site-packages\\aiohttp\\_websocket.cp35-win32.pyd'

[CRITICAL] launcher: You may need to run as admin to install dependencies.

[INFO] launcher: All done.

D:\Discord\BOTs\Bardi Squad Music 3>

**Comment by MattBSG** [comment]
`PermissionError: [Errno 13] Permission denied: 'C:\Users\Liam`Did you run as administrator as it says at the end?

**Comment by ghost** [comment]
yep still didnt work

**Comment by MattBSG** [comment]
You should install the bot on the same driver python is. So try on your C: drive (I know it’s prob a low capacity drive though)

**Comment by ghost** [comment]
The problem is, the 2 other (same) bots are working. just this one isnt.

**Comment by MattBSG** [comment]
I told you what the problem is. Specifically, if you look at the (full) error message you’ll see a pip dependancy is breaking, not the bot. We can’t do anything about that, now if it doesn’t work on your C: drive it’s another rabbit hole. aiohttp:
```
PermissionError: [Errno 13] Permission denied: 'C:\Users\Liam Tuhuteru\AppData\Local\Programs\Python\Python35-32\Lib\site-packages\aiohttp\_websocket.cp35-win32.pyd'
```

**Comment by ghost** [comment]
It's fixed. sorry for bothering.

**Comment by rrmad** [comment]
I m not getting
