### ISSUE TITLE
Output window repeating the last letter of commands or actions [Windows]

### ISSUE THREAD

**Issue by Noremon** [Just-Some-Bots/MusicBot#1509]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x] I am running version 1.9.6_3 of MusicBot

----

In the output console window, the last letter of commands like "!np" or "!skip f" will be repeated as "!npp" or "!skip ff". Also if a user leaves or enters the Voice Chat, the last letter of the Channel name will be repeated such as "Radioo" for "Q-Comm Radio".

<img width="499" alt="bot typo" src="https://user-images.githubusercontent.com/7649598/36503480-a5876a12-1723-11e8-8c75-02512890df96.PNG">

### Steps to reproduce

1. Have a user enter or leave the Voice Chat causing the bot to pause/unpause, or a user enters a command.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1745578/musicbot.log)

**Comment by Noremon** [comment]
The bot otherwise is working fine. It's more annoyance.

**Comment by Noremon** [comment]
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1755802/musicbot.log)

<img width="499" alt="bot typo 2" src="https://user-images.githubusercontent.com/7649598/36639252-0f89d69e-19df-11e8-85a9-dd31993ea560.PNG">

It didn't occur for 1 user tonight, but is still happening on it joining the server and if I enter or leave the Voice Chat

**Comment by MattBSG** [comment]
What version of Windows are you on?

**Comment by Noremon** [comment]
Windows 7

**Comment by Noremon** [comment]
I have the bot and Python installed on C:\ if that helps

**Comment by jayktaylor** [comment]
Literally have no idea why this is happening - looks like it's just a visual/terminal bug.

**Comment by Noremon** [comment]
No idea either. It's only occurred since updating to 1.9.6_3 too. It's just annoying!

**Comment by Noremon** [comment]
Still occurring since the update, it makes it seem excitable

**Comment by Noremon** [comment]
I changed Python's install location to C:\ and did a fresh MusicBot install. It seems to have sorted the issue!

<img width="419" alt="hlkhl" src="https://user-images.githubusercontent.com/7649598/37692310-816daf3c-2c96-11e8-8770-65bb3a8d46c7.PNG">

**Comment by Noremon** [comment]
The repeated character bug has reoccurred :-/ It happens with True Type font set for the output window but not raster font. I'm really annoyed that it returned.

**Comment by MattBSG** [comment]
I am fairly sure this is not a problem with our bot as strings aren't formatted like that. I'm gonna close this as this is most likely a windows bug. I'm sorry this is occurring to you though
