### ISSUE TITLE
[Feature Request] Shared playlist through Google Drive. (Load playlist from link or such?)

### ISSUE THREAD

**Issue by jacobmix** [Just-Some-Bots/MusicBot#151]
I'd love to have a link people can click on, and suggest songs to the autoplaylist.
My plan is to use a symbolic link from my Drive folder to the MusicBot config folder.
But Google Drive will always change the txt file to a gdoc file.
(Because it has to open in Google Docs for suggestions, ect to work.
And Google Docs automatically makes a gdoc copy of the file, and uses that instead.)
https://support.google.com/docs/answer/6033474?hl=en

Will gdoc auto playlist support or something be a feature in the future?
Maybe just a thing in the options we can turn on or off. Like:
AutoPlaylistGdoc = yes
(Make it look for a "autoplaylist.gdoc" instead of "autoplaylist.txt")

**Comment by imayhaveborkedit** [comment]
Can you upload a gdoc file for me to look at.  I have to know the format to even consider this.

**Comment by jacobmix** [comment]
Can't seem to upload the file here. No matter what file type. So here's a link to it on Google Drive:
https://drive.google.com/file/d/0B0WFA9YZKBygWXItV1IzUlJMNVU/view?usp=sharing
Here's how the file looks in the online Gdoc editor: https://docs.google.com/document/d/1--bl8sTRGnC-2HLQ1j-VYpG4QX40UUpjD_To90adTNE/edit?usp=sharing

**Comment by imayhaveborkedit** [comment]
This is what's in that file:

``` json
{
  "url": "https://docs.google.com/open?id=1--bl8sTRGnC-2HLQ1j-VYpG4QX40UUpjD_To90adTNE",
  "doc_id": "1--bl8sTRGnC-2HLQ1j-VYpG4QX40UUpjD_To90adTNE",
  "email": "[your_email]@gmail.com",
  "resource_id": "document:1--bl8sTRGnC-2HLQ1j-VYpG4QX40UUpjD_To90adTNE"
}
```

That's not useful to me.

**Comment by jacobmix** [comment]
Guess loading the songs from the link:
https://docs.google.com/open?id=1--bl8sTRGnC-2HLQ1j-VYpG4QX40UUpjD_To90adTNE
Would be asking too much. Damn. Guess making a shared playlist won't be that easy.
Thanks for helping anyways.

**Comment by aidant** [comment]
I don't know if this helps but google have a python API for google drive.
https://developers.google.com/drive/v3/web/quickstart/python#notes

I think loading songs from a shared file is great. (if possible)

**Comment by imayhaveborkedit** [comment]
I'm not going to write anything with any external api, but playlist stuff will have something similar to what I think you want.
