### ISSUE TITLE
Bot error after joining voice channel

### ISSUE THREAD

**Issue by jupiter1390** [Just-Some-Bots/MusicBot#1511]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [ x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x ] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [ x ] I am running version 1.9.6_3 of MusicBot

----

### Description of issue

Bot worked normal yesterday, but after reboot bot doesn't work properly
Bot joins voice channel and it is on the voice channel but has error
I already joined voice channel before the bot

### Steps to reproduce

1. 
start bot
summon the bot
and it produces the error message below
----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1753992/musicbot.log)

**Comment by MattBSG** [comment]
Gonna combine this with #1512
