### ISSUE TITLE
[1.9.7] Looks like there is a small problem with the search command!

### ISSUE THREAD

**Issue by endms3231** [Just-Some-Bots/MusicBot#1513]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [ ] I am running version 1.9.6_3 of MusicBot

----

### Description of issue
When you use the search command, no explanation is given and only error logs are output to the dos.

### Steps to reproduce

1. [1.9.7] !summon - !search error log occurrence! in dos
----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1754437/musicbot.log)

**Comment by MattBSG** [comment]
Please attach the actual log file, that is only a partial trace back and I cannot get anything meaningful from that

**Comment by endms3231** [comment]
Ahhh ... Okay! Sorry!

**Comment by MattBSG** [comment]
You should also explain *how* it is not working, because "it’s not working" is as good as nothing at all.

**Comment by endms3231** [comment]
I uploaded the log file!

**Comment by jayktaylor** [comment]
This isn't happening for me. Have you modified [this section](https://github.com/Just-Some-Bots/MusicBot/blob/review/musicbot/bot.py#L1789-L1804) of the bot?

**Comment by endms3231** [comment]
Sorry for the late mail
I found out that I didn't write "\n%s" on the json...
I couldn't find a circle in the error log.
Windows 10용 메일에서 보냄

보낸 사람: Jayden Bailey
보낸 날짜: 2018년 2월 28일 수요일 오전 6:21
받는 사람: Just-Some-Bots/MusicBot
참조: 이리에; Author
제목: Re: [Just-Some-Bots/MusicBot] [1.9.7] Looks like there is a smallproblem with the search command! (#1513)

This isn't happening for me. Have you modified this section of the bot?

**Comment by endms3231** [comment]
I realized this in six hours.

**Comment by MattBSG** [comment]
So this is resolved? The issue looked like it was from a voice connect error. If not, have you modified the bot?

**Comment by endms3231** [comment]
So I solved it. It was a very strange problem because I didn't write the formula in the "i18n" file.

Windows 10용 메일에서 보냄

보낸 사람: Matthew Cohen
보낸 날짜: 2018년 2월 28일 수요일 오후 11:04
받는 사람: Just-Some-Bots/MusicBot
참조: 이리에; Author
제목: Re: [Just-Some-Bots/MusicBot] [1.9.7] Looks like there is a smallproblem with the search command! (#1513)

So this is resolved? The issue looked like it was from a voice connect error. If not, have you modified the bot?

**Comment by MattBSG** [comment]
Huh, gotcha. I’ll go ahead close this if you’re all set

**Comment by endms3231** [comment]
Ok I see!
Windows 10용 메일에서 보냄

보낸 사람: Matthew Cohen
보낸 날짜: 2018년 3월 1일 목요일 오전 1:56
받는 사람: Just-Some-Bots/MusicBot
참조: 이리에; Author
제목: Re: [Just-Some-Bots/MusicBot] [1.9.7] Looks like there is a smallproblem with the search command! (#1513)

Huh, gotcha. I’ll go ahead close this if you’re all set
