### ISSUE TITLE
audio_cache and how it is managed?

### ISSUE THREAD

**Issue by Munzy** [Just-Some-Bots/MusicBot#1514]
This is more over a question, but how is the audio cache managed. Does it just delete on startup like I am seeing? Does it actively manage the cache? What happens when you get maxed out on disk size? What initiates clearing of the cache?

**Comment by MattBSG** [comment]
The cache is not deleted or managed. When `SaveVideos` is on in options.ini all music is permanently saved. You can manually delete files if you desire. If that option is off, it deletes the song immediately after finishing playing
