### ISSUE TITLE
[Feature request] Discord login with email

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1516]
Hey i have an feature request. In the beginning of the bot development it was possible to connect the bot via email credentials. Could you pls add this feature again?

**Comment by AutumnClove** [comment]
This is no longer supported by discord itself and can result in getting your account banned.

**Comment by MattBSG** [comment]
Short answer, no. Long answer no with this stance by Discord https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-

Sorry if this disappoints you.

**Comment by MattBSG** [comment]
Also: the only reason it was usable is because bot accounts did not exist back then and it was fine to make bots on normal accounts.
