### ISSUE TITLE
{command_prefix}clean is no longer cleaning user messsages.

### ISSUE THREAD

**Issue by BuccoBruce** [Just-Some-Bots/MusicBot#1519]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x] I am running version 1.9.6_3 of MusicBot

----

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

**Comment by BuccoBruce** [comment]
{command_prefix}clean no longer removes user messages, just messages from the bot.

**Comment by AutumnClove** [comment]
Please attach your log as that let's us see if it's a problem with the bot, or if you just have missing permission. Thank you.

**Comment by BuccoBruce** [comment]
Closing issue, I had forgotten about the manage messages permission on the text channel.
