### ISSUE TITLE
[bug] Online radio stuck

### ISSUE THREAD

**Issue by jacobmix** [Just-Some-Bots/MusicBot#152]
Adding an online radio with !play makes it get stuck.
( Like: http://stream.myrock.fm/myrock128 )

**Comment by imayhaveborkedit** [comment]
[Streams are not supported yet.](https://github.com/SexualRhinoceros/MusicBot/wiki/FAQ#can-i-have-the-bot-play-a-stream)

**Comment by jacobmix** [comment]
I know they're not supported. But i had to restart. It just told me it was playing a song from the auto-playlist. But there was no sound, and it seemed stuck. !skip didn't work. Seemed like restarting the bot was the only option.
