### ISSUE TITLE
i18n file

### ISSUE THREAD

**Issue by MrUnknownDE** [Just-Some-Bots/MusicBot#1520]
Hay,

I tried to translate the bot through the "i18n" template and there I created a new file "de.json". So I set in the "options.ini" that he should query the files but he does not.

Please answer

Best regards
Johannes

**Comment by MattBSG** [comment]
Hi @MrUnknownDE 

Please make sure your `de.json` file is in the `config/i18n` directory, and your `options.ini` file has the following for the i18n path:
```ini
[Files]
# Path to your i18n file. Do not set this if you do not know what it does.
i18nFile = de.json
```

If this still does not work, please attach your `de.json` to this issue.

**Comment by MrUnknownDE** [comment]
Hello,

Yes, I did that as you wrote it. The problem is still there.

The "de.json" is just a copy of the "en.json" just ebend almost in German.

Best regards
Johannes

**Comment by MattBSG** [comment]
If you would please attach your `de.json` file I would appreciate that. Also, what version of the bot are you on? It shows at the top when you run it

**Comment by MrUnknownDE** [comment]
Hello,

The bot version is the "1.9.7-rc1"
[de.zip](https://github.com/Just-Some-Bots/MusicBot/files/1776564/de.zip)

Best regards
Johannes

**Comment by MattBSG** [comment]
Hi again

You need to specify the full path. ie if on my VPS I wanted to specify it I would do `/root/MusicBot/config/i18n/de.json`

**Comment by Argos-Rho** [comment]
@MrUnknownDE 

You should open a Pull Request and add this onto one, I'm sure this would be extremely helpful for the devs so they don't need to make many Locales.
Danke schön

**Comment by MattBSG** [comment]
Assuming that this is resolved now after trying the direct path. If you are still having issues please feel free to reopen
