### ISSUE TITLE
ERROR WHEN UPDATE DEPENDENCIES

### ISSUE THREAD

**Issue by Mulstr** [Just-Some-Bots/MusicBot#1522]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x ] I am running version 1.9.6_3 of MusicBot

----

### Description of issue
this happens when I start update_dependencies.bat

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.
![screenshot_329](https://user-images.githubusercontent.com/32112170/36947634-ec9925b6-1fdf-11e8-8b10-ab7a3bb77b6d.png)
this problem

**Comment by AutumnClove** [comment]
Based on the launcher fail check in the background, it looks like you have a bad install. Make sure you installed correctly: 
https://just-some-bots.github.io/MusicBot/#installationwindows

**Comment by Mulstr** [comment]
I did all how it said in the guide but this happens, so should I try to reinstall it?(on my computer when I installed in the same way all was ok)

**Comment by Mulstr** [comment]
I did all how it said in the guide so there r still this problem

**Comment by Mulstr** [comment]
I got wat the problem, the new version of a bot doesn't work with 8 windows, cuz new version of plugins which update deps downloads doesn't work with 8 windows
