### ISSUE TITLE
Bot no working

### ISSUE THREAD

**Issue by zenX15** [Just-Some-Bots/MusicBot#1523]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [/] I am using Python 3.5 or higher (run `python --version` on the command line)
- [/] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [/] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [/] I am running version 1.9.6_3 of MusicBot

----

### Description of issue
All my Options and permissions are set and the bot is verified and selected on the correct channel but when i open runbot.bat the bot does not load into the channel i have spoken to a competent user by the name of Amit and he say they said that it was weird that it was not working. 

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

**Comment by AnnsAnns** [comment]
**Please attach your MusicBot log file (located at logs/musicbot.log) to this issue. You can do so by dragging and dropping the file to your reply.**

**Comment by MattBSG** [comment]
Closing due to lack of response when asked to provide more information
