### ISSUE TITLE
[Feature] Make songs getting skipped when not in voice optional

### ISSUE THREAD

**Issue by n1tr0-5urf3r** [Just-Some-Bots/MusicBot#1524]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x ] I am running version 1.9.6_3 of MusicBot

----

### Description of issue

Make "songs get skipped if queuer not in voice" optional, if people Auto disconnect because they are afk their whole songs get skipped. Annoying if you queued a 50 song Playlist and each one sends a message. 
Also all Songs in the queue get skipped on restart when no one is in the voice Channel. 

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

**Comment by jayktaylor** [comment]
It is optional. Check your permissions file.

**Comment by n1tr0-5urf3r** [comment]
I don't think you got me right as I can't find anything related in my permissions .ini
So Steps to reproduce
1. Be alone with your bot in the voice channel
2. Queue a playlist with several songs
3. Leave the voice channel
4. Restart the bot
5. For every single song in the playlist a message is send that it was skipped because the queuer is not in the voice channel

**Comment by jayktaylor** [comment]
https://github.com/Just-Some-Bots/MusicBot/blob/review/config/example_permissions.ini#L94

**Comment by n1tr0-5urf3r** [comment]
How could I be this blind, I must have read an older example_permissions.ini
Sorry for bothering and thanks for the help.
