### ISSUE TITLE
bot wont start

### ISSUE THREAD

**Issue by ubgg** [Just-Some-Bots/MusicBot#1526]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x] I am running version 1.9.6_3 of MusicBot
python3.5 run.py
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 346, in main
    from musicbot import MusicBot
  File "/home/ee/ee/MusicBot/musicbot/__init__.py", line 6, in <module>
    from discord.ext.commands.bot import _get_variable
ImportError: cannot import name '_get_variable'
[INFO] launcher: Attempting to install dependencies...
Requirement already up-to-date: discord.py[voice]~=0.16.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1))
  discord.py 0.16.12 does not provide the extra 'voice'
Requirement already up-to-date: pip in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: youtube_dl in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: colorlog in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: cffi in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: pycparser in /usr/local/lib/python3.5/dist-packages (from cffi->-r requirements.txt (line 5))

[INFO] launcher: Ok lets hope it worked

[INFO] launcher: All done.

----

### Description of issue
using Ubuntu 16.04

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

**Comment by MattBSG** [comment]
I see nothing wrong. Just start the bot again
