### ISSUE TITLE
cant run.bat

### ISSUE THREAD

**Issue by boss007as** [Just-Some-Bots/MusicBot#1530]
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[CRITICAL] launcher: Bot wasn't installed using Git. Reinstall using http://bit.ly/musicbotdocs.
Press enter to continue . . .

**Comment by jayktaylor** [comment]
The problem and solution are on the last line.
