### ISSUE TITLE
playlist

### ISSUE THREAD

**Issue by mickael49300fr** [Just-Some-Bots/MusicBot#1531]
Please tick all applicable boxes.

- [ ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [X] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

unable to play playlist with permission I have as message
"
  error
You do not have permission to use that command.
Reason: You do not have permission to play media from this service. "
unless we are "owner" of the bot he reads the playlist

### Steps to reproduce

1. 

----

### Log file

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1807388/musicbot.log)

**Comment by jayktaylor** [comment]
Add `soundcloudset` to https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_permissions.ini#L96.
