### ISSUE TITLE
Bot joins channel but isn't "connected"

### ISSUE THREAD

**Issue by mojamm11** [Just-Some-Bots/MusicBot#1532]
Please tick all applicable boxes.

- [x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [x ] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
The bot recently stopped working when I tried running it. It joins the channel but isn't responding to commands. When I check the terminal I see this https://puu.sh/zGZo0/4d2cda681e.png and then it says "attempting to reconnect 1/5" (something like that) but always fails.

### Steps to reproduce

1. Simply running the bot easily reproduces it for me now.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1808810/musicbot.log)

**Comment by mojamm11** [comment]
okay the bot joins the channel now (but still occasionally disconnects and reconnects) however the author skip (and musicmaster roles with skip permissions) won't skip a song instantly even though they should be able to.

**Comment by jayktaylor** [comment]
Please read 'Important changes' on https://github.com/Just-Some-Bots/MusicBot/releases/tag/1.9.7.

**Comment by mojamm11** [comment]
Ahh, I see. Well my issue has been resolved and the bot works normally. Thanks for the help!
