### ISSUE TITLE
Auto Update Deps

### ISSUE THREAD

**Issue by LynkGX** [Just-Some-Bots/MusicBot#1534]
Please tick all applicable boxes.

- [ x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x ] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [ ] The latest `master` version (1.9.7)
- [ x ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ x ] Feature request
- [ ] Question

----

### Description of Feature

Auto update dependencies on bot startup/restart (via !restart) then maybe a switch in the options.ini to disable it for special cases

**Comment by AnnsAnns** [comment]
Auto-Updating all dependencies on every restart will slow the startup-time immensely down. 

This feature sounds pretty annoying, I'm sorry.

**Comment by MattBSG** [comment]
This is more of a laziness utility request, and for the most part almost no applications, discord bot or not, function this way. We will probably never implement this, thank you for the suggestion however.
