### ISSUE TITLE
Bot can't connect on one server on discord.

### ISSUE THREAD

**Issue by Geesmen** [Just-Some-Bots/MusicBot#1536]
![error](https://user-images.githubusercontent.com/28143153/37499367-4a170ba4-2891-11e8-8963-af1e8e13690d.png)

**Comment by AutumnClove** [comment]
This has been an ongoing issue with discords voice servers, change your server region to fix it, is the best we have for a fix so far.

**Comment by Geesmen** [comment]
i got it fixed thanks though
