### ISSUE TITLE
[CRITICAL] launcher: Bot wasn't installed using Git.

### ISSUE THREAD

**Issue by Teeeeeeeee** [Just-Some-Bots/MusicBot#1541]
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[CRITICAL] launcher: Bot wasn't installed using Git. Reinstall using http://bit.ly/musicbotdocs.
Press enter to continue .

**Comment by jayktaylor** [comment]
The error tells you what to do.

**Comment by wave1sda** [comment]
how to fix it????

**Comment by MattBSG** [comment]
@wave1sda Install the bot correctly according to the guide as it says.
