### ISSUE TITLE
Updating bot via the .BAT gives a modified files error

### ISSUE THREAD

**Issue by Noremon** [Just-Some-Bots/MusicBot#1545]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Running the update.BAT gives:
 
_Starting...
Passed Git checks...
You have modified files that are tracked by Git (e.g the bot's source files).
We can try to reset your folder to a clean version for you. Continue? (y/n):_

I most certainly haven't modified anything, as this is a fresh install (I changed Python's install location to C:\), and entering yes allows it to tell me everything is up to date. The only things I added back were the options/permissions & autoplaylist.

<img width="419" alt="ighiooi" src="https://user-images.githubusercontent.com/7649598/37691990-90f8e46e-2c94-11e8-8de1-3d7c19325649.PNG">

GIT BASH doesn't give an error if I run "git pull", it just tells me it's up to date.

### Steps to reproduce

1. run update.BAT in MusicBot folder

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1831860/musicbot.log)

**Comment by AutumnClove** [comment]
I would assume it's detecting the autoplaylist as modified.

**Comment by Noremon** [comment]
"git reset --hard" gives:

_$ git reset --hard
HEAD is now at 91dc2ed Update issue template_

<img width="458" alt="ighiooi b" src="https://user-images.githubusercontent.com/7649598/37692152-a113322c-2c95-11e8-8c38-54a9153c31a6.PNG">

**Comment by Noremon** [comment]
@AutumnClove Possibly!

**Comment by AutumnClove** [comment]
It's not really an error so much as warning, as long as the bot is working then you should be fine.

**Comment by Noremon** [comment]
It doesn't actually clear the autoplaylist though

**Comment by jayktaylor** [comment]
If you run update.py and it tells you you've modified files, enter 'n' and then run `git status` inside of Git Bash. It will tell you which files you've modified that are tracked by Git.

**Comment by Noremon** [comment]
@jaydenkieran Yep, that was it. The file was a copy of the default autoplaylist & permissions/options

**Comment by Noremon** [comment]
_Starting...
Passed Git checks...
You have modified files that are tracked by Git (e.g the bot's source files).
We can try to reset your folder to a clean version for you. Continue? (y/n): n
Okay. Cancelling update process for now.

C:\MusicBot>git status
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        config/default autoplaylist.txt
        config/options - Copy.ini
        config/permissions - Copy.ini

nothing added to commit but untracked files present (use "git add" to track)

C:\MusicBot>_

**Comment by jayktaylor** [comment]
Yeah that'd probably make sense then. update.py wants to reset the folder because Git has noticed that there are new files in there. This is actually somewhat intended behaviour, but the wording in the error the script throws ("You have modified files that are tracked by Git (e.g the bot's source files).") could probably do with changing.

At some point, I'll make it so that you can opt to skip update.py's reset and instead try to force the update anyway. The reason why update.py prompts you to reset if it detects that you've modified or added files that are "out of the ordinary" is so that we can always ensure that the update will complete correctly.
