### ISSUE TITLE
"git reset --hard" gives an error

### ISSUE THREAD

**Issue by Noremon** [Just-Some-Bots/MusicBot#1546]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

"git reset --hard" gives:

_$ git reset --hard
HEAD is now at 91dc2ed Update issue template_

<img width="458" alt="ighiooi b" src="https://user-images.githubusercontent.com/7649598/37692152-a113322c-2c95-11e8-8c38-54a9153c31a6.PNG">

### Steps to reproduce

1. Run BASH
2. Give code for "git reset --hard"

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1831890/musicbot.log)

**Comment by AutumnClove** [comment]
Have you recently done a git pull to ensure you're on the right version of music bot?

**Comment by Noremon** [comment]
@AutumnClove Yep, it gives me that it's up to date. This is a fresh install

**Comment by jayktaylor** [comment]
That isn't an error. That's Git telling you that it has reset the repository to the last commit, which was 91dc2ed. That's what `git reset --hard` does.

**Comment by Noremon** [comment]
Thank-you! I have never used it before so I expected it to wipe the folder
