### ISSUE TITLE
[Feature request] Separate option to cache autoplaylist.txt

### ISSUE THREAD

**Issue by noirscape** [Just-Some-Bots/MusicBot#1549]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [ ] The latest `master` version (1.9.7)
- [x] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

(Removed rest of template since its irrelevant for a Feature Request I think)
----

At the moment, when putting the `audio_cache` setting to `no`, the bot will not save any tracks.

While this is favorable as my personal hosting has limited disk space, this unfortunately runs into the issue that the autoplaylist (which is used if no songs are queued) will gobble up (in my opinion unneccesary) bandwith for a few files that are in most cases, redownloaded within the same hour.

It would therefore be useful to be able to have the option to have the files downloaded from the autoplaylist be kept, regardless of the audio_cache setting.

**Comment by PolyacovYury** [comment]
Did a similar thing locally.
Commented out the lines 915-919 in bot.py and changed the if statement on line 196 in player.py to contain `and entry.url not in self.bot.autoplaylist`. This was enough, but I would think that it would be more flexible to make another folder for autoplaylist cache and add a config option for this feature.
