### ISSUE TITLE
[Feature request] Add songs to auto playlist (either single links or full playlists)

### ISSUE THREAD

**Issue by krazyito65** [Just-Some-Bots/MusicBot#155]
title says it all.  I have some programming experience, so I'm going to look into doing this for myself at the moment, but do you think you could point me in the right direction where the commands are called?  I'll be sure to come back and give you what I did if you wish to tweak/improve it to add to the bot.

**Comment by krazyito65** [comment]
http://pastebin.com/raw/s9juvFWK

here is a python script that will parse a playlist and output the links (if needed)

**Comment by imayhaveborkedit** [comment]
https://gist.github.com/imayhaveborkedit/1ad7b4c99c5698072b34

**Comment by krazyito65** [comment]
yea that looks better. how hard would that be to implement into a command to append to a text file?

**Comment by imayhaveborkedit** [comment]
Trivial.  I was considering doing this at some point.  If I do it'll be something like:
- DM the user the list of links
- DM the user a link to a pastebin/hastebin/etc with the list of links
- DM the user a file with the links
- Be part of the playlist controls, meaning you can add all the items from a youtube playlist to a local playlist.

**Comment by imayhaveborkedit** [comment]
This was added as the `pldump` command.
