### ISSUE TITLE
Issue with new bot update - can't instaskip and no audio?

### ISSUE THREAD

**Issue by AbstractUmbra** [Just-Some-Bots/MusicBot#1550]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Hi there! I updated to the latest version of the bot today and after re-creating the options.ini and permissions.ini with the new options, I'm experiencing a few issues...

Firstly, any role within the MusicMaster role cannot instaskip any longer, and the bot won't output audio to Discord. (Region EUW and EUC tried).
Even the owner (me) can't instaskip.

Log attached.

I'm running on a Ubuntu instance on a free tier AWS Instance.

### Steps to reproduce

1. Update
2. Create new permissions.ini and options.ini based on example files.
3. Run bot and get MusicMaster member to attempt to skip.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1839542/musicbot.log)

**Comment by jayktaylor** [comment]
Your instaskip problem isn’t an issue, the behaviour has changed. See https://github.com/Just-Some-Bots/MusicBot/releases/tag/1.9.7

As for your audio issue, try running update.py to update your dependencies.

**Comment by AbstractUmbra** [comment]
The one time I skip reading a change log... Thanks a lot. I'll give it a
whirl.
