### ISSUE TITLE
Error python 3.5

### ISSUE THREAD

**Issue by M0RC** [Just-Some-Bots/MusicBot#1554]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
When I play a youtube music that lasts a long time, an error appears.
Anyone can explain to me where this error comes from ?

![error musicbot](https://user-images.githubusercontent.com/23026811/37841214-75f5d898-2ebf-11e8-806d-760a949e0c3c.png)

Thanks you !

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1842574/musicbot.log)

**Comment by AutumnClove** [comment]
Discord issues with load balancing, you can try changing your server region.

**Comment by M0RC** [comment]
I try to change server region and it doesn't work :/

**Comment by Argos-Rho** [comment]
As pointed out in the error code, `line 5` which says `WebSocket connection is closed: code = 1001` 

> indicates that an endpoint is "going away", such as a server going down or a browser having navigated away from a page.

So what this means is like Autumn Said, 

> issues with load balancing

This is on Discord's side and times out/closes the WebSocket, I guess in certain cases it gets tired of loading the song for you or has a time out where it closed the socket before completing.

If you are trying to load Live Content then it is currently an experimental feature.

**Comment by Argos-Rho** [comment]
So try something wild for me, (I don't know if this will work at all.)

- Go into your bot settings by navigating to `config/options.ini` 
- Scrolling down to `Line 81` which contains the code `SaveVideos = yes` 
- Switch it to `SaveVideos = no`

Restart your bot and try again. Hope this works.

**Comment by MattBSG** [comment]
This issue won’t  be affected by `SaveVideos` in the config; if anything it would put more load on the bot redownloading the song each time with youtube-dl, which has nothing to do with Discord.

There is not a whole lot we can do if this error arises other than better reconnection logic (which we should do). Changing voice region somewhere else then changing it back has been a fix for some people, but nothing you do client side is going to *prevent* Discord from closing the websocket.

**Comment by ImthePeach** [comment]
Cloudflare amirite?
