### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Kore-Development** [Just-Some-Bots/MusicBot#1555]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
I tried to get the Music Bot but there is a problem with requirements

### Steps to reproduce

1. Get Python 3.5.4
2. Use Git to download
3. Put in bot token in options.ini
4. Open update.bat

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
https://paste.ee/p/oK7Od

**Comment by mwallis45** [comment]
run "update.bat" then let it load. then put "py -3 -m pip install -U colorlog" in there. then reopen "update.bat" let it load close it then run "run.bat".
