### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by PLOliwier** [Just-Some-Bots/MusicBot#1556]
Please tick all applicable boxes.

- [+] I am using Python 3.5 or higher (run `python --version` on the command line)
- [+] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [+] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [+] The latest `master` version (1.9.7)
- [-] The latest `review` version

What type of issue are you creating?

- [+] Bug
- [-] Feature request
- [-] Question

----

### Description of issue

![obraz](https://user-images.githubusercontent.com/30889917/37869079-97c527e2-2fb1-11e8-9acb-3804d074be82.png)
:/

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by jayktaylor** [comment]
Read your error message.
