### ISSUE TITLE
Problem:     Bot cannot login, bad credentials.

### ISSUE THREAD

**Issue by Qwerty-Space** [Just-Some-Bots/MusicBot#1557]
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1846064/musicbot.log)
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
```
Starting MusicBot 1.9.7
Loaded autoplaylist with 2531 entries
.[INFO] launcher:
An error has occured:
  Problem:
    Bot cannot login, bad credentials.

  Solution:
    Fix your token in the options file.  Remember that each field should be on their own line.



[INFO] launcher: All done.
```

### Steps to reproduce

1.  Run the bot with Docker command `docker run -it musicbot:0.1`

----

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1846063/musicbot.log)

**Comment by AutumnClove** [comment]
You're using an invalid token, please make sure that a) this is a bot account b)your using token not secret and c)the token is still valid. 
If you've done all this and it's still not working please regenerate your token and use the new one. If this also fails make sure you've made a copy of `example_options.ini` and renamed it `options.ini` if you've done this then make sure your showing file extension so that your not having an issue of `options.ini.ini`

**Comment by Qwerty-Space** [comment]
@AutumnClove I have done all of those things.

**Comment by Qwerty-Space** [comment]
```
boba@blueberry:~/bots/MusicBot$ ls config/
_autoplaylist.txt  example_options.ini  example_permissions.ini  i18n  options.ini  permissions.ini
```

![image](https://user-images.githubusercontent.com/6967592/37905269-391ee3cc-30f6-11e8-89d3-d37c425285f3.png)

**Comment by AutumnClove** [comment]
As far as I know bot tokens start with ND

**Comment by MattBSG** [comment]
@AutumnClove There are multiple prefixes, idk if that’s one of them

**Comment by Strift** [comment]
I just tried using the bot, within a docker container. I had the same error. I was already using the bot this way with a previous version, and it used to work well.

What I did:
- Cloned this repo
- Copied the options.ini file, and edited the Token
- Built the docker image and ran it

I'm on Ubuntu, too.

**Comment by Qwerty-Space** [comment]
ohh I think I might know the problem.
The Docker container doesn't have access to the options file.  The same thing happened with Group Butler in a Docker container.

How can I give it access?

**Comment by Strift** [comment]
I don't think it's the problem.

The whole directory is copied during the image build process
```dockerfile
# Add project source
WORKDIR /usr/src/musicbot
COPY . ./
```
 And a volume is actually mounted to map the the config directory from the hard disk
```dockerfile
# Create volume for mapping the config
VOLUME /usr/src/musicbot/config
```

And by the way, my token starts with "cTRkq", even though I don't think it has something to do with the issue.

**Comment by Qwerty-Space** [comment]
@Strift something similar happened with Group Butler in Docker.  It copied the directory, but I had to force it to use the environment variable file in a docker-compose file.

**Comment by MattBSG** [comment]
Appears resolved. If you have any further questions please feel free to reopen :)
