### ISSUE TITLE
Logging error

### ISSUE THREAD

**Issue by Dioptrick** [Just-Some-Bots/MusicBot#1559]
Please tick all applicable boxes.

 I am using Python 3.5 or higher (run `python --version` on the command line)
 I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
 I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

 The latest `master` version (1.9.7)

What type of issue are you creating?

 Question

----

### Description of issue

I have done everything like tutorial on the official site and just stuck here:

----

### Log file

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

Starting MusicBot 1.9.7
Loaded autoplaylist with 2531 entries

Connected: ******************/*********#****
Owner:     ******************/**************#****

Server List:
 - Serberer
 - servver

Not bound to any text channels

Autojoining voice chanels:
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\logging\__init__.py", line 994, i
n emit
    stream.write(msg)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\colorama\ansitowin3
2.py", line 40, in write
    self.__convertor.write(text)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\colorama\ansitowin3
2.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\colorama\ansitowin3
2.py", line 166, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\colorama\ansitowin3
2.py", line 175, in write_plain_text
    self.wrapped.flush()

**Comment by AutumnClove** [comment]
Please uninstall python 3.6.x and get python 3.5.4 and report back.

**Comment by jayktaylor** [comment]
This is a known problem on Windows with Python 3.6. Use Python 3.5.
