### ISSUE TITLE
Normalize audio

### ISSUE THREAD

**Issue by tahahawa** [Just-Some-Bots/MusicBot#156]
It would be a nice feature to normalize the audio, either on the fly (if that's even possible) or run a util on it like mp3gain or normalize-audio or something like this: https://github.com/slhck/audio-normalize so that audio doesn't kill someone's ears if the source video is super loud.

**Comment by imayhaveborkedit** [comment]
On the fly, highly unlikely.  That lib you linked is just a wrapper to use ffmpeg/avconv to process files.  I wanted to add normalization but it's not that easy to do unless you preprocess files, which sounds more like a liability for something to break.

**Comment by tahahawa** [comment]
Apparently there's an ffmpeg filter for that http://muldersoft.com/docs/dyauno_readme.html it may or may not work on the fly, I didn't look too deeply into it

**Comment by rrbailey89** [comment]
I agree this would be really nice.

**Comment by insert3coins** [comment]
so how would one implement the command line normalization of ffmpeg on the musicbot?

**Comment by MrManlyPrincess** [comment]
So has this been dropped or is it a feature that will be looked into?
Thanks.

**Comment by jayktaylor** [comment]
https://github.com/Just-Some-Bots/MusicBot/commit/0659da8c60880840bd767a96a893ec1ecc603076
