### ISSUE TITLE
Error skip or fail InstaSkip

### ISSUE THREAD

**Issue by Giikuzawa** [Just-Some-Bots/MusicBot#1562]
Please tick all applicable boxes.

- [+] I am using Python 3.5 or higher (run `python --version` on the command line)
- [+] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [+] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [+] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [+] Question

----

### Description of issue
I have a problem. Bot does not want to miss songs without a vote. I added the instaskip on item to one of the roles, but they still can not skip without a vote, even I, the owner, can not miss without voting. Maybe I should use something else instead of InstaSkip in Permissions?

### Steps to reproduce

1. Turn on the bot
2. Many people enter the channel
3. I'm trying to write skip
4. The voting comes out
----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1861869/musicbot.log)

**Comment by jayktaylor** [comment]
Use `!skip f`.

**Comment by AutumnClove** [comment]
This isn't an issue read the release notes `!skip f` has superseded instaskip allowing DJs and owners to still participate in vote skipping.

**Comment by Giikuzawa** [comment]
thanks for the help
