### ISSUE TITLE
Problem with playing a song

### ISSUE THREAD

**Issue by Aerodymeus** [Just-Some-Bots/MusicBot#1564]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

When i use the !play command and try to play some music with the bot it throws out this text into the command line:

```
!play https://www.youtube.com/watch?v=3JzN5x6U-OY
Download started: https://www.youtube.com/watch?v=3JzN5x6U-OY
Download complete: https://www.youtube.com/watch?v=3JzN5x6U-OY
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at /home/MusicBot/musicbot/player.py:293> exception=TypeError("Can't convert 'NoneType' object to str implicitly",)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/MusicBot/musicbot/player.py", line 323, in _play
    mean, maximum = self.get_mean_volume(entry.filename)
  File "/home/MusicBot/musicbot/player.py", line 270, in get_mean_volume
    cmd = '"' + self.get('ffmpeg') + '" -i "' + input_file + '" -af "volumedetect" -f null /dev/null'
TypeError: Can't convert 'NoneType' object to str implicitly
```

Google always brings me to other issues around a year ago where the fixing was an bot update.
But i got this now with the fresh installed and cloned git version.

### Steps to reproduce

1. starting the bot via ./run.sh
2. using the !play command in discord

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1864345/musicbot.log)

**Comment by AutumnClove** [comment]
Turn off experimental eq

**Comment by Aerodymeus** [comment]
Okay thanks, this worked.
And after this I also missed to intall ffmpeg at my debian. 

Thank you!
