### ISSUE TITLE
People not being able to queue up YouTube playlists

### ISSUE THREAD

**Issue by DeustDew** [Just-Some-Bots/MusicBot#1568]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
Everyone but me (because I am the owner) cannot queue up YouTube playlists. Whenever they try it gives the error "You don't have permission to use that command. Reasons: You do not have permissions to play media from this service." I have triple checked the permissions.ini file along with options.ini just to make sure. I have allowed the default group to queue up playlists that come from YouTube, Soundcloud, and also generic. I didn't touch the extractors line. So I am questioning if I am not changing a value of something that I should be to allow the default group to queue up playlists. To be honest, I feel like an idiot not being able to figure this out for the past 3 hours.

### Steps to reproduce

1. Simply coded the bot step by step changing or leaving values the way I would want my bot to run. Everything works but this.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1867590/musicbot.log)

**Comment by mwallis45** [comment]
have you made it so they are able to queue playlists in permissions.ini . If you have gone through and changed them make sure "AllowPlaylists" is yes but also check "MaxPlaylistLength" if its green then its fine and doesnt matter, If not then change that to 0 for unlimited songs. Please also check that you have done this in Default or have added there role ID or user ID to the other roles in the right place in permissions.ini

**Comment by DeustDew** [comment]
![image](https://user-images.githubusercontent.com/37999326/38190223-2445b94a-3618-11e8-9550-30a3256be788.png)
Yes I have gone through these changes within Default.

**Comment by mwallis45** [comment]
now just run update.bat and let it finnish then run run.bat. Please also make sure that they are using the right url
https://www.youtube.com/watch?v=P_84rA1KupM&list=PLe8jmEHFkvsYuYm1x5t3RZ5WyGrfF8bkg
will not work
https://www.youtube.com/playlist?list=PLe8jmEHFkvsYuYm1x5t3RZ5WyGrfF8bkg
this will. Its the same playlist but there is a different. Look for ".com/**playlist?list**" and not ".com/**watch?**v". Also youtube auto "mix" will not work.

**Comment by DeustDew** [comment]
![image](https://user-images.githubusercontent.com/37999326/38190641-08dc7962-361a-11e8-8576-b526a82f8f09.png)
I've actually tried this before, probably should have mentioned it within the post. This popped up and I didn't want to say yes because I am paranoid. Do I need to say yes?

**Comment by mwallis45** [comment]
if you have changed the bot(the program) then "n". If you have only changed the options and permissions then click "y"

**Comment by DeustDew** [comment]
So I asked a friend of mine to test it again and it still says the same thing. This is getting quite..frustrating.  
(;﹏;)

**Comment by mwallis45** [comment]
can you send a picture of the cmd

**Comment by DeustDew** [comment]
![image](https://user-images.githubusercontent.com/37999326/38190912-44e8d008-361b-11e8-9086-e3778c794588.png)

**Comment by mwallis45** [comment]
if you have "UseExperimentalEqualization" on in config turn that off restart the bot and give it a go

**Comment by DeustDew** [comment]
![image](https://user-images.githubusercontent.com/37999326/38191141-551a7c14-361c-11e8-953a-cd4db9513696.png)
Nope..

**Comment by mwallis45** [comment]
This is going to sound a bit dumb but I have to make sure. One re check your permissions file. two make sure that once you have changed them save them. three redo the update.bat and run.bat. and last get your friend to do !perms and send me what it comes up with

**Comment by DeustDew** [comment]
![image](https://user-images.githubusercontent.com/37999326/38191613-48a29be0-361e-11e8-89da-02ab9eac407a.png)

**Comment by mwallis45** [comment]
change "Extractors = " to blank in permissions and do the restart processes again. Then give it another go

**Comment by DeustDew** [comment]
Woo, finally works! Guess it was extractors this entire time. Thank you for telling me to change that value. I was afraid that if I messed with it it would break the bot. Ha-ha. Thank you!!!!! (ﾉ´ヮ´)ﾉ*:･ﾟ✧
