### ISSUE TITLE
direct streamable output

### ISSUE THREAD

**Issue by seilexta** [Just-Some-Bots/MusicBot#1571]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

Is it possible to make the bot outputs a direct mp3 stream? provided the host server can handle it
so there will be dual output, one into discord, one as streamable mp3 link
it might be nice to be able to keep quality for some user, while maintaining playlist control via discord for community interaction

thank you ~

**Comment by MattBSG** [comment]
The !stream command is what you are looking for

**Comment by seilexta** [comment]
thanks for reply !
ah i mean as output not input xD
like there's 2 output, one audio via discord music, other one into streamable mp3 / other format file with higher quality

**Comment by MattBSG** [comment]
Oh I’m sorry, I misinterpreted that. At this time, no, the bot cannot output a stream of the currently playing song

**Comment by MattBSG** [comment]
Although an interesting idea, we unfortunately will probably never create or accept PRs for this as it breaks a fundamental concept we try to keep: keep it as simple for the user as possible. That’s also why we don’t have a web control panel.
