### ISSUE TITLE
Owner/Musicmaster permissions not being granted even though ID has been set. 

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1572]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [X ] Bug
- [ ] Feature request
- [X ] Question

----

### Description of issue
Put my own ID as owner and as group MusicMaster (wich has auto skip enabled). Still unable to instaskip my sons. 

### Steps to reproduce

1. Run my bot 
2. Try to skip
3. Get asked to add another skip to qeue so it will actually skip

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1881263/musicbot.log)
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AutumnClove** [comment]
As of the latest update the bot no longer insta-skips when you skip normally if you have permission to do so. This is so you are able to contribute to the vote skip. The new way to insta-skip is by running `skip f`
