### ISSUE TITLE
Strange volume behaviour (runs at 100% and requires to click the volume bar to have it at the actual level)

### ISSUE THREAD

**Issue by Girard-Arnold** [Just-Some-Bots/MusicBot#1577]
Please tick all applicable boxes.

- [X ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X ] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

When first joining the bot's channel, the volume plays at 100% for all users, both normal discord users and better discord users. Users need to right-click > click the volue bar to have it go back to the selected volume. Note that the bar displays as the % the user had chosen evne though the volume clearly plays at a higher volume.
For instance, my volume is at 8%, i need to click on it for it to actually be set to 100%.

Additional infos : 
OS : Raspbian
Hardware : Raspberry Pi 3 B+
Network : Wired, optic fiber WAN, copper LAN
The bot is ran as a service.

### Steps to reproduce

1. Join channel, and have music playing.
2. Until the volume is changed client-side, it remains at 100% even though it shows something else.
3. Click on the volume dot.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1911460/musicbot.log)

**Comment by AutumnClove** [comment]
1) better Discord breaks Discord ToS and we will not provide help with that.
2) discord has known volume issues such as settings client side volume to say 50 closing and re opening then it'll be at 100 this might be related. 
Lastly the Musicbot has a default volume in options.ini as well as the volume command

**Comment by Jimgersnap** [comment]
The bot cannot control personal client-side volume settings. It can only control the volume of which it broadcasts at. As AutumnClove mentioned, this volume issue is a known bug with Discord and not MusicBot.

**Comment by Girard-Arnold** [comment]
The volume issue mentioned by AutomnClove does seem to hit the nail, I'll just close this then.
