### ISSUE TITLE
Video not available.

### ISSUE THREAD

**Issue by SeasonalFerret** [Just-Some-Bots/MusicBot#1582]
https://github.com/Just-Some-Bots/MusicBot/blob/7c617ec1d7d54202fcd94a190ca621408fba31f6/config/_autoplaylist.txt#L2470

ERROR: KT-d_3SvyCc: YouTube said: This video is not available.
[ERROR:bot] Error processing youtube url:
ERROR: KT-d_3SvyCc: YouTube said: This video is not available.
Removing unplayable song from autoplaylist: https://youtube.com/watch?v=KT-d_3SvyCc
Updating autoplaylist

Suggest replacing with: https://www.youtube.com/watch?v=ZHBvFDPz0J0

**Comment by MattBSG** [comment]
Thanks for the information, updated
