### ISSUE TITLE
Command to check storage used.

### ISSUE THREAD

**Issue by SeasonalFerret** [Just-Some-Bots/MusicBot#1588]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

### Feature request

I'm curious about how many videos my bot has downloaded and saved in audio_cache, how big the folder is, and how much room is left on my storage device.

I don't want to login to my VPS and turn off the bot just to check the file size, so it'd be super interesting to quarry the bot about it's environment.

Suggested/Example command would be !space.
Bot could respond with: "I have downloaded 23 songs for a total of 120MB. There is XGB left on the hard drive."
If integrated with #1584, it would say how much space is left that it's allowed to use instead of entire space left.

This command would simply be used for information/debugging, and could be used to get a kick out of if you have an overly insane amount of songs saved. Though, further information could possibly be giving to the user, such as total up-time, a ping test, average song duration, etc.

**Comment by amit177** [comment]
Thank you, this will be added once the merge request will be finalized.
