### ISSUE TITLE
Output debug into selected text channel.

### ISSUE THREAD

**Issue by SeasonalFerret** [Just-Some-Bots/MusicBot#1589]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

### Feature request
![ipfvy7v 1](https://user-images.githubusercontent.com/17802843/39006321-50f76732-43c8-11e8-9222-6a4e50105fc8.png)

Allow a setting in options.ini to output the console into a selected text channel.
This would allow server owners (and others with permission) to view the bot's output, so that they can understand who played what song and any errors.

My server has a dedicated text channel used for bots. In it is a log of stuff that bots log, such as when a user joins the server, message deletion reasons, etc. Not being able to set MusicBot to output the log into a logging channel was actually quite surprising, as I was looking for the specific setting for a bit before giving up.

Since my bot is hosted in a VPS, I do not wish to constantly ssh into the server just to check the logs. Being able to see what's happening, if something goes wrong, and if someone's been naughty with the bot _inside_ of discord would be super helpful, as it is with the other bots on my server.

Bot logging to these servers should be limited to INFO, but should be changable in config.ini.
It would be nice to also be able to change the logging info in-chat, something like ?log WARNING or something - restricted to the bot owner, of course.

To help not spam Discord's API, I'd like to suggest a method to send the output in grouped packages instead of instantly.
Bot logs something in console -> Bot waits 3 seconds to see if something else becomes logged. If nothing else gets logged after the 3 seconds, or 10 seconds passes, output all of the log into the selected output channel with the separate outputs separated by \n.

PS: Is there a logging setting to only output what users request what songs? If not, it may be interesting to have the bot only output what songs are requested by what users (and maybe other commands) in the logging channel, instead of all of console output. 
We could even make proper warnings / errors @ the bot owner in emergencies.

**Comment by ImthePeach** [comment]
This is kind of already built into the bot in a way. 
Selecting `yes` on `NowPlayingMentions` in the options file (https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_options.ini#L83-L84) will always say "Now playing <songname> requested by <requester_name>"
Selecting `no` on `DeleteMessages` will keep the bot from deleting it's own messages, and if you select `no` on `DeleteInvoking` it will keep the song requester's message while selecting `yes` for this option will simply keep that channel slightly cleaner.
(https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_options.ini#L101-L106)

Example of how this looks:
![image](https://user-images.githubusercontent.com/17447156/40919906-98df656e-67d0-11e8-98e7-8440849c1c1e.png)

**Comment by SeasonalFerret** [comment]
I want to lot what songs were requested in a separate channel not visible
to other users, as well as output any errors.

**Comment by AutumnClove** [comment]
Closing because @TheerapakG implemented it. Might not be merged until a later time.
