### ISSUE TITLE
Bot stopped playing after long "video not available in" error

### ISSUE THREAD

**Issue by jacobmix** [Just-Some-Bots/MusicBot#159]
Here's the full log: http://prnt.sc/ajmq5e | http://prnt.sc/ajmpxj
Happened again: http://prntscr.com/ak2qvi | http://prntscr.com/ak2r36
Happens a lot... Here's another log: http://prntscr.com/ambglf

**Comment by jacobmix** [comment]
If this is an issue with youtube-dl should i just post something on their github or what?

**Comment by imayhaveborkedit** [comment]
Doesn't look like this happens very often.  If its still happening consider making an issue on the ytdl repo.
