### ISSUE TITLE
[CRITICAL] launcher: Bot wasn't installed using Git

### ISSUE THREAD

**Issue by superxtrafrancyz228** [Just-Some-Bots/MusicBot#1591]
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[CRITICAL] launcher: Bot wasn't installed using Git. Reinstall using http://bit.ly/musicbotdocs.
Press enter to continue .

And the site itself does not work

**Comment by jayktaylor** [comment]
Follow the instructions on https://just-some-bots.github.io/MusicBot/MusicBot/

**Comment by superxtrafrancyz228** [comment]
![duck](https://user-images.githubusercontent.com/38562439/39054422-401c97b4-44ba-11e8-803f-7262b410d742.png)

**Comment by MattBSG** [comment]
Sorry about that, correct link: https://just-some-bots.github.io/MusicBot/
