### ISSUE TITLE
[CRITICAL] launcher: Bot wasn't installed using Git

### ISSUE THREAD

**Issue by superxtrafrancyz228** [Just-Some-Bots/MusicBot#1592]
Sorry for re-sending the question...

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[CRITICAL] launcher: Bot wasn't installed using Git. Reinstall using http://bit.ly/musicbotdocs.
Press enter to continue .

And the site itself does not work - https://just-some-bots.github.io/MusicBot/MusicBot/
![duck](https://user-images.githubusercontent.com/38562439/39054578-b39f7ad0-44ba-11e8-8677-19be11df894f.png)

**Comment by jayktaylor** [comment]
You can click one of the guides on the left side of the page.
