### ISSUE TITLE
Spotify Autoplaylist

### ISSUE THREAD

**Issue by terning20** [Just-Some-Bots/MusicBot#1593]
So is there a way for the autoplaylist to read the URI from my spotify playlist? So that i can easily manage the auto played songs by adding/removing in the Spotify library?

I have added Spotify and i can use uri's for request's, but it wont read in the auto file...

Help is much appreciated!

**Comment by jayktaylor** [comment]
It is not currently possible to add Spotify URIs to the autoplaylist. They are only supported through playing them with a command.

**Comment by Jeroeni** [comment]
I'd love to be able to save the queue made from a spotify playlist, or have the same spotify -> youtube conversion for pldump

**Comment by BabyBoySnow** [comment]
Duplicate of #1587
