### ISSUE TITLE
Where is runbot.bat

### ISSUE THREAD

**Issue by qlife1146** [Just-Some-Bots/MusicBot#1594]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
Where is runbot.bat file?
(and I don't find logs/musicbot.log too.)
I downloaded MusicBot-master from here and unzip. but, runbot.bat is not in zip.

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AutumnClove** [comment]
You appear to have installed the bot incorrectly.
If you followed a video guide, or downloaded a ZIP file, then you have installed the bot incorrectly. As a result, we will not provide support to you until you install the bot correctly, using the appropriate guide here: https://just-some-bots.github.io/MusicBot/. An error will be thrown if you have installed the bot incorrectly.

**Comment by qlife1146** [comment]
well... I'd done. It is good before. I ran update.bat and installed.
but, I can't find runbot.bat yet.

**Comment by qlife1146** [comment]
thank you so much, I solved it.
