### ISSUE TITLE
Update.bat spazzes out causing me to have to restart computer.

### ISSUE THREAD

**Issue by IoIxD** [Just-Some-Bots/MusicBot#1595]
Please tick all applicable boxes **(I don't know how to do this)**.

- I am using Python 3.5 or higher (run `python --version` on the command line)
- I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system

Which version are you using?

- The latest `master` version (1.9.7)

What type of issue are you creating?

- Bug

----

### Description of issue

I was told somewhere (can't remember exactly where) that after changing the settings I needed to run update.bat to change them. Considering the settings for the default music list haven't changed even though I saved the file, I assume something needs to be done to update the file. Problem is, running update.bat causes an infinite loop of the program opening and closing causing me to have to restart the computer.

### Steps to reproduce

1. Open update.bat

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1940994/musicbot.log)

**edit:** I just checked and it seems the bot generated a new playlist file ("_autoplaylist.txt") after I changed the old one. This one has all the old default songs in it. Not sure if that's related but I thought I'd mention that.

**Comment by AutumnClove** [comment]
Try uninstalling python 3.6 and getting 3.5.4 make sure to click install to path. Update.bat is for updating the dependencies such as YouTube-dl not for the options files. the `_autoplaylist.txt` is a fall back for if something is wrong with the current one iirc. As for the file not saving that's rather odd
 This issue might be better addressed on our support server, which can be found on the readme.

**Comment by IoIxD** [comment]
Here's my options file. Note that I tried it with and without the "www". It is formatted exactly like the fallback file.

[autoplaylist.txt](https://github.com/Just-Some-Bots/MusicBot/files/1941055/autoplaylist.txt)
[_autoplaylist.txt](https://github.com/Just-Some-Bots/MusicBot/files/1941054/_autoplaylist.txt)

Downgrading to Python 3.5 did not work.

_On a side note, whoever set up the default music has terrible taste in music. The song that plays first is a generic dubstep beat with a guy screaming over it. Is this supposed to be death metal? This is the worst thing I've heard in my life._

**Comment by IoIxD** [comment]
I got it to work by accident. Used !skip on the song to try and find out what it was and now suddenly it's playing my playlist? Weird.

**Comment by AutumnClove** [comment]
It was probably persistentqueue lol

**Comment by AutumnClove** [comment]
Also the original autoplaylist is just taken from discord.fm it's all of the categories iirc
