### ISSUE TITLE
Possible Missing Dependency in Debian Documentation

### ISSUE THREAD

**Issue by Ranigad** [Just-Some-Bots/MusicBot#1598]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.7)
- [ ] The latest `review` version
- [x] Forked version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue

On Debian Linux 9 (Stretch), I recently went through the installation of a forked version of the bot that refers to the documentation of this original version for installation. After finishing installing all the dependencies as listed in the Debian section of the guide (https://just-some-bots.github.io/MusicBot/installing/debian/) the bot was erroring with a missing dependency of `ffmepg` which seems to be in every installation instruction except Debian. 

Running `sudo apt-get install ffmpeg` fixed it. Was this intentional or was it a minor oversight in the documentation?

Thanks.

**Comment by jayktaylor** [comment]
Hi, thanks. This seems to be an oversight from whoever originally wrote that guide. I've added it to the guide.
