### ISSUE TITLE
[1.9.5 RC7] Freezing without error message

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#160]
I don't know if this problem is a known one but I noticed that the bot is freezing sometimes without any error indicating what's wrong.

When I'm leaving the server in the evening which let's the bot pause the current song everything is fine. The next day when I'm joining the server again I'm automatically joining the voice channel which I left the evening before. 
Now the bot wants to continue the song but no sound is played. Also the green indication around the avatar isn't there. Switching debugging to on doesn't produce any error outputs or so on. The last entry on the terminal is: 

```
[config:autopause] Pausing (from leaving the server in the evening)
[config:autopause] Unpausing (rejoining the next day)
```

**Comment by tpanajott** [comment]
I've noticed the same problem after playing a few songs :/ Sad becuse it works great otherwise!

**Comment by imayhaveborkedit** [comment]
This should be fixed now.
