### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by OzzyHelix** [Just-Some-Bots/MusicBot#1600]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.7)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
when queuing songs of spotify and YouTube player does not move on to the next song in the queue
I should also mention this is of my own fork however the Spotify integration was not changed at all

### Steps to reproduce

1. the description makes reproduction self-explanatory
----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot_2018-04-28_22-43.log](https://github.com/Just-Some-Bots/MusicBot/files/1958382/musicbot_2018-04-28_22-43.log)

**Comment by AleanaA** [comment]
Duplicate of #1581
