### ISSUE TITLE
RemoveFromAPOnError Function not working correctly

### ISSUE THREAD

**Issue by Hakurye** [Just-Some-Bots/MusicBot#1601]
Please tick all applicable boxes.

-  I am using Python 3.5 or higher (run `python --version` on the command line)
-  I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
-  I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

-  Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
Cheers, I found a "possible problem" with the function->RemoveFromAPOnError in the bot options.ini file, maybe isn't working properly cause i have wrote the "no" option  but when I disconnected the ethernet cable from the pc and I left the bot turned on without noticing, i saw the console with a lot of nice red lines saying that (obviously) there was an error downloading the webpage, but just under a white line saying that he would remove the link from the autoplaylist

### Steps to reproduce

1. Set RemoveFromAPOnError = no (into  options.ini)
2. Add an autoplaylist with 2 or + songs (yt link)
3. Turn on the bot and let him play a song
4. while playing a song, unplug the ethernet cable or try to disconnect from a Wi-Fi Network
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1964774/musicbot.log)
![botpb](https://user-images.githubusercontent.com/38891133/39486837-b8559afc-4d7d-11e8-957e-279b75f846e3.PNG)

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by Hakurye** [comment]
Critical update of the problem I have reported above. The bot actually did not delete anything of the links in the autoplaylist, although it created a file named "autoplaylist_removed.txt" and both in the log file that in the console showed the deletion of links
Close the problem if you think it is normal, for now it remains a superfluous and non-critical problem as described above
(Sorry for bad english and thank you for patience)

**Comment by jayktaylor** [comment]
The console message about removing the song from the autoplaylist means the current session autoplaylist, rather than the file. The bot still won't modify your autoplaylist file if you have that option in the config turned off.
