### ISSUE TITLE
YouTube API changed

### ISSUE THREAD

**Issue by kevin-lucas-simon** [Just-Some-Bots/MusicBot#1605]
Please tick all applicable boxes.

- [ x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ x ] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ x ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Today, YouTube has changed its API.
If you want to play a video on the Musicbot with !play, nothing will be played. The bot does not give an error message.
With !skip but an error message is issued, which says that the bot is currently playing nothing.

----

### Log file

[Userchat]: !play mgmt
Download started: https://www.youtube.com/watch?v=rtL5oMyBHPsWolfsschanze
Download complete: https://www.youtube.com/watch?v=rtL5oMyBHPs

[Userchat]: !skip
[ERROR:bot] Error in skip: CommandError: Can't skip! The player is not playing!
Traceback (most recent call last):
  File "/home/pi/MusicBot/musicbot/bot.py", line 2841, in on_message
    response = await handler(**handler_kwargs)
  File "/home/pi/MusicBot/musicbot/bot.py", line 2158, in cmd_skip
    raise exceptions.CommandError(self.str.get('cmd-skip-none', "Can't skip! The player is not playing!"), expire_in=20)
musicbot.exceptions.CommandError: Can't skip! The player is not playing!

**Comment by AutumnClove** [comment]
send log please

**Comment by AleanaA** [comment]
Not sure where you got this information about an API change, I tested both the command you used, https://www.youtube.com/watch?v=rtL5oMyBHPsWolfsschanze and https://www.youtube.com/watch?v=vvtRtxHAKg0
All of which worked perfectly fine on two separate bots.
As asked above, send your log file. This will give us a better understanding as to what's wrong.

**Comment by kevin-lucas-simon** [comment]
Strange, today it works again. I thought it was the API because thirdparty apps had problems as well, like the MyTube app.
I think it's no longer needed to send the log file, because it works again. 
Anyway, thanks for the replies. This thread can be closed.
