### ISSUE TITLE
Extend Owner only commands

### ISSUE THREAD

**Issue by Cornelious11** [Just-Some-Bots/MusicBot#1606]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

### Description of issue

Only the owner is capable of running the command `!option autoplaylist on/off`

As the owner of the bot cannot be present at all times that users are active in the server being able to assign a group to execute this command would be extremely useful.

**Comment by mwallis45** [comment]
why would you want to turn it on and off over and over again?

**Comment by AleanaA** [comment]
A good alternative, if this is really necessary, is to allow for multiple owners.
With that said, I don't see a good reason for this kind of thing as the `option` command affects the bot globally, and shouldn't be used too often.

**Comment by ImthePeach** [comment]
Would be something we already would plan to do after per server playlists are implemented.
