### ISSUE TITLE
Bring an old feature on next versions

### ISSUE THREAD

**Issue by Chaos21** [Just-Some-Bots/MusicBot#1608]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

Hello, I'll want that an old feature'll came back.
It's about the "queue" command.

Before, when using queue command, the bot shows the entire list. Now, it shows just show what's playing and a "And x more" underneath.

Please, can you bring that feature back?

Thanks for reading,
Chaos21

**Comment by AutumnClove** [comment]
??? It's always been that way? Even on 1.9.5 it was done that way. I'm assuming you're list is longer than ones you tried to use before.

**Comment by Chaos21** [comment]
Is the list long? With Like 3 songs?

**Comment by mwallis45** [comment]
it was a max of 25 in 1.9.5 so now you can change it. but if you put 0 it doesnt show them all

**Comment by Chaos21** [comment]
I can change it by setting MaxSongs = x (x =/= 0)
In the permissions.ini file?

**Comment by AutumnClove** [comment]
see here: https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_options.ini#L140

**Comment by Chaos21** [comment]
Thanks a lot AutumnClove. Thanks for helping.
This issue is now closen, thanks for answering too fast!

Chaos21

**Comment by AutumnClove** [comment]
Thank @mwallis45 lul
