### ISSUE TITLE
DJ Group not Working

### ISSUE THREAD

**Issue by thundercookie15-old** [Just-Some-Bots/MusicBot#1609]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

I set up my DJ permissions in the permissions.ini file but when someone tries to use a command with the assigned role it tells them they have no permission to use it, it tells they are in default group.

### Steps to reproduce

1. Assign a group or user to the DJ permissions.
2. Start the bot
3. Use one of the assigned commands to the DJ group.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1977610/musicbot.log)

**Comment by AleanaA** [comment]
Have the user run `!perms`
If the `name:` field is not DJ then send the DJ group section here.

**Comment by AutumnClove** [comment]
Please check the following:
1) You're editing the right section, the first bit of lines which all start with `;` are comments
2) when you put them in the Granttousers or Granrtorolws didu make sure to uncomment it?
3) This might sound stupid but I'm including it because it's something we've seen on the support server, did you save the file and then fully restart, where as fully restart is closing the CMD running and then do the run file for your os.
4) please include a picture or if your comfortable with it upload the actual file itself too allow for better help.
5) You're not using notepad, rather at the very minimal, notepad++

**Comment by thundercookie15-old** [comment]
My Permissions file for the groups:
[Default]
CommandWhitelist = play perms queue np skip search id help clean
; CommandBlacklist =
IgnoreNonVoice = play skip search
MaxSongLength = 1200
MaxSongs = 0
AllowPlaylists = yes
; MaxPlaylistLength = 20
InstaSkip = no
Remove = no
SkipWhenAbsent = no
BypassKaraokeMode = no
Extractors = generic youtube soundcloud

; This group has full permissions.
[MusicMaster]
 GrantToRoles = 180351441913774080 180381818820755456 174138845401579521 367024803258826755 367028074858151956
 UserList = 171624880066789376
MaxSongLength = 0
MaxSongs = 0
MaxPlaylistLength = 0
AllowPlaylists = yes
InstaSkip = yes
Remove = yes
SkipWhenAbsent = no
BypassKaraokeMode = yes
Extractors = 

; This group can't use the blacklist and listids commands, but otherwise has full permissions.
[DJ]
CommandBlacklist = blacklist listids
 GrantToRoles = 412729682530926625
; UserList =
MaxSongLength = 0
MaxSongs = 0
MaxPlaylistLength = 0
AllowPlaylists = yes
InstaSkip = no
Remove = yes
SkipWhenAbsent = no
BypassKaraokeMode = yes
Extractors = generic youtube soundcloud

; This group can only use the listed commands, can only use play/skip when in the bot's voice channel,
; can't request songs longer than 3 and a half minutes, and can only request a maximum of 8 songs at a time.
[Limited]
CommandWhitelist = play queue np perms help skip
; CommandBlacklist =
IgnoreNonVoice = play skip
; GrantToRoles =
MaxSongLength = 210
MaxSongs = 8
AllowPlaylists = yes
InstaSkip = no
Remove = no
SkipWhenAbsent = yes
BypassKaraokeMode = no
Extractors = youtube

I always use Notepad++ to edit things

**Comment by thundercookie15-old** [comment]
When they use !perms it tells them they are in the default group.

**Comment by AleanaA** [comment]
After modifying the permissions file make sure you fully restarted the bot (not the restart command).
Also ensure that the Role ID is correct, and that the user has the Role that was set in the permissions file

**Comment by thundercookie15-old** [comment]
I did fully restart the bot and they have the role that was set in the file.

**Comment by ImthePeach** [comment]
is this issue still valid/open? did you save the file + restart the bot? key  word is save.

**Comment by ImthePeach** [comment]
Closing this issue as it seems to be an issue on your end only, if you still need help feel free to re-open and comment on it.

**Comment by Fluffyhoneybadger** [comment]
I actually have the exact same issue to..

**Comment by AleanaA** [comment]
@Fluffyhoneybadger I'd recommend joining [The Help Server](https://discordapp.com/invite/bots) or making a new issue, as this one is both inactive and closed.
