### ISSUE TITLE
Bot crash

### ISSUE THREAD

**Issue by Chaos21** [Just-Some-Bots/MusicBot#1611]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

When the bot joins a vocal channel by using the summon command, unfortually, the bot summons, but what's hapenns:
-After entering the voice channel, the bot doesn't sends a message that he bounded into
-It compltely ignores commands
-The bot haves permission to speak, to chat, to view the channel and the prefix and the command are correct
-Bot crashes sometimes after that

**Comment by AutumnClove** [comment]
Send log

**Comment by Chaos21** [comment]
Unfortually there's no one error in the log

**Comment by mwallis45** [comment]
could you send the log still

**Comment by Chaos21** [comment]
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

Starting MusicBot 1.9.7
Loaded autoplaylist with 1631 entries
Authenticated with Spotify successfully using client ID and secret.

Connected: **Confidential** #9199
Owner:     **Confidential** #6532

Server List:
**Confidential**

Not bound to any text channels
Not autojoining any voice channels

**Comment by mwallis45** [comment]
thats not the log file but you havent bound the bot to any text channels. send a picture of your `bindtochannel` in option.ini (hide any secrets or tokens that get in the picture)

**Comment by Chaos21** [comment]
![bind2channels](https://user-images.githubusercontent.com/39013902/39709898-74103bb6-521b-11e8-915f-51a857a2a252.png)

**Comment by mwallis45** [comment]
you havent added the channel id to `BindToChannels`

**Comment by Chaos21** [comment]
So I need to place each ID of each text channel that I'll want that the bot only listens to these channels?
It worked very fine before without it

**Comment by mwallis45** [comment]
well you said that you wanted it only bound to set channels `the bot doesn't sends a message that he bounded into`. You havent bound it to any.

**Comment by Chaos21** [comment]
So I guess it's mandatory?

**Comment by mwallis45** [comment]
if you want it to only go to set channels you have to say which ones it will only listen to

**Comment by Chaos21** [comment]
The bot is in multiple servers and many channels. I don't think I'll waste my time to asking to people to give the id of their channels

**Comment by Chaos21** [comment]
Oh also.
The CMD wrote that: 
![task destroy](https://user-images.githubusercontent.com/39013902/39710597-89bc7bd0-521d-11e8-8b8b-276116018cb7.png)

**Comment by mwallis45** [comment]
try using python 3.5.4 and not 3.6

**Comment by Chaos21** [comment]
And now, it's still the same problem. After summoning, bot doesn't recognize any command and disconnects after 2 minutes

**Comment by Chaos21** [comment]
I could reinstall all the composants

**Comment by AutumnClove** [comment]
Do you get an error code 1001 or something like that saying closed reason = no reason?
