### ISSUE TITLE
Improve the help command

### ISSUE THREAD

**Issue by Chaos21** [Just-Some-Bots/MusicBot#1613]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

### Description of issue

It would be cool if the "help" command was more clean, like a list, or something like this. An example from a bot:
**(Note that's just an example, I'm not saying to add these features)**
![project melody commands](https://user-images.githubusercontent.com/39013902/39744727-8a66dbec-52a5-11e8-9ab7-8bb1a3bd5a4a.png)

**Comment by owocado** [comment]
yeah, making the help output into a neat paginated embed would be the work of art indeed. It will look much cleaner to the eyes.

**Comment by BabyBoySnow** [comment]
Given current state, I don't see this being done. A rewrite of MusicBot is needed.
