### ISSUE TITLE
Link MusicBot to my current program.

### ISSUE THREAD

**Issue by olivercool103** [Just-Some-Bots/MusicBot#1615]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.7)
- [x] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
I already have a bot with different commands and functions, and I would also love it to have music functionality. How do I run my code so it will link into the music bot program and it runs as one program.

### Steps to reproduce

1. N/A

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by mwallis45** [comment]
The bot is open source and licensed under MIT which means you can modify it, but we’re not here to give you help with doing so. This server is for help setting up and running the bot. We will not help you with modifying it or with errors that occur by modifying it. 
But you could add your commands into the musicbots main function. `bot.py`. But we will not really help you with this. Others "may" help but thats there own time and dont have to help.

**Comment by AutumnClove** [comment]
Just use the same token and prefix in options.ini as your other bot. Or use a different prefix so they don't clash.

**Comment by olivercool103** [comment]
Yes, thank you. It works perfectly!
