### ISSUE TITLE
aiohttp.errors.ClientOSError not handled properly

### ISSUE THREAD

**Issue by glego** [Just-Some-Bots/MusicBot#1619]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
We had a network update in our datacenter and the connection was briefly interrupted. Musicbot seemed to have handled the disconnection properly but, upon reconnection, it could not connect to discordapp.com:443 due to a DNS issue. After that, the bot came to a complete halt.

```
aiohttp.errors.ClientOSError: [Errno -3] Cannot connect to host discordapp.com:443 ssl:True [Temporary failure in name resolution]
```

Actually, the issue is the error was handled but nothing was done with it. If the process just crashed, my service would have restarted it. So either exit the app or handle it properly... Handeling exceptions and doing nothing with it, are the worst of them all 🤕 

### Steps to reproduce

Don't know maybe disable DNS?

----

### Log file
* [musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1998292/musicbot.log)

```
# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0    192     4 ?        Ss   Apr21   0:00 s6-svscan /app/s6/
root        69  0.0  0.0    192     4 ?        S    Apr21   0:00 s6-supervise musicbot
root        70  0.0  0.0   4500    72 ?        Ss   Apr21   0:00 /bin/sh ./run
root        71  0.0  4.8 710256 49268 ?        Sl   Apr21   4:19 python3 /app/musicbot/run.py
root        98  0.0  0.8 460392  8188 ?        S    Apr21   0:02 ffmpeg -nostdin -i audio_cache/youtube-M8JUWVgIYgM-Remember_Rudy_Van_Gelder_Editio
root       108  1.2  0.0   4500   784 pts/0    Ss   09:09   0:00 /bin/sh
root       112  0.0  0.2  34420  2692 pts/0    R+   09:09   0:00 ps aux
```

**Comment by AleanaA** [comment]
I believe the issue lies in your setup, or where you're looking. I tested this on my end, which the steps to reproduce would be to turn off your internet, or cut internet off from the computer hosting the bot, and run the bot. Nothing worked incorrectly, and even in your log, it seems to work fine going by the `All done.`

The error is definitely being handled correctly, and the app is being exited as it should, I would recommend looking into how your setup is handling it's auto restarts.

**Comment by glego** [comment]
Hi,

I've tested it myself and it seems to work fine?!?

1. Starting the musicbot
2. Changing the `/etc/resolv.conf` to `nameserver 0.0.0.0`
3. Kill python3 run.py `kill <PID>`
4. Changing the `/etc/resolv.conf` to `nameserver 8.8.8.8`
5. Service restored

Logs:
* [musicbot-docker.log](https://github.com/Just-Some-Bots/MusicBot/files/1998721/musicbot-docker.log) (Terminal output not the musicbot.log)

I think the problem is caused by a memory issue (my system only had like a couple of MB free and no swap). 

Looking at the log files after `[INFO] launcher: All done.` it tries to `Unclosed client session` at a specific memory address.

So concluding the issue might be caused by something else, e.g. low memory issue. So I've added 2 GB of swap, changed swappiness to 10 and hope it wont happen again.

Thanks for the support and sorry for wasting your time... 

```
[INFO] launcher: All done.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f6cf85be048>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f6cf95dc080>
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
```
