### ISSUE TITLE
[SUGGESTION] Cutomisable Discord messages

### ISSUE THREAD

**Issue by bindingflare** [Just-Some-Bots/MusicBot#162]
Sometimes I want the bot to be more human-like (Change the messages it prints)

so..
If it is possible, can you clump all the messages for the Dchat (mabye also the console) to one python code file? or separate config.ini?

Thank you for taking your time for this awesome creation!
- Flint

**Comment by ghost** [comment]
agreed!
it would be great to edit the messages without staggering through the source code for them. xD

**Comment by jayktaylor** [comment]
Submitted a pull request which handles this. #287

**Comment by brawaru** [comment]
Hmm, how about set time before deleting or disable deleting?

**Comment by jayktaylor** [comment]
@DaFri-Nochiterov I can add that in as a configurable option

**Comment by brawaru** [comment]
For every message? It's will be cool :o

**Comment by jayktaylor** [comment]
@DaFri-Nochiterov Added it in to the pull request. :+1:

**Comment by amit177** [comment]
This feature was implemented (i18n)
