### ISSUE TITLE
Can't get help info from disconnect

### ISSUE THREAD

**Issue by GriffinG1** [Just-Some-Bots/MusicBot#1620]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.7)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

See traceback below

### Steps to reproduce

1. Use %help disconnect

----

### Log file
177939404243992578/Griffin#5250: *help disconnect
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "C:\Users\gpgro\GitHub\MusicBot\musicbot\bot.py", line 2684, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Users\gpgro\GitHub\MusicBot\musicbot\bot.py", line 1108, in cmd_help
    dedent(cmd.\_\_doc\_\_)
  File "C:\Users\gpgro\AppData\Local\Programs\Python\Python36-32\lib\textwrap.py", line 430, in dedent
    text = _whitespace_only_re.sub('', text)
TypeError: expected string or bytes-like object

**Comment by AutumnClove** [comment]
Please use python 3.5.4 as 3.6 has issues on windows
