### ISSUE TITLE
Autoleave option

### ISSUE THREAD

**Issue by GriffinG1** [Just-Some-Bots/MusicBot#1621]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.7)
- [x] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

Just an option for the bot to automatically leave the VC when it's empty, possibly after a certain period of time.

**Comment by jayktaylor** [comment]
Similar to #647. Will move discussion there.
