### ISSUE TITLE
Question | How DJ group works?

### ISSUE THREAD

**Issue by Chaos21** [Just-Some-Bots/MusicBot#1623]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

Hi there!
I have a question.

How did DJ group works?
Because I am placing the ID of an user in the "; UserList =" line.
In "CommandWhiteList" there's blacklist command, so basically he can blacklist users.

After closing the running cmd and run it again, the person don't have any permission to do that.

**Comment by AleanaA** [comment]
Did you remove `; ` from the `UserList =` line?

**Comment by Chaos21** [comment]
@AleanaA No I'm not.
Should I remove that? And that means like this group'll be "turned on"?

**Comment by jayktaylor** [comment]
Yes.
