### ISSUE TITLE
Lyrics command

### ISSUE THREAD

**Issue by Chaos21** [Just-Some-Bots/MusicBot#1624]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

What's about a !lyrics command?
Bot uses google search and uses first result to get lyrics, or a particular website.

**Comment by AutumnClove** [comment]
```
	async def cmd_google(self, message, args, leftover_args):
		"""
		Usage: {command_prefix}google "word"

		Grab some info from google. Give you a url 
		"""
		member = message.author
		filt = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890$-_.+!*'(),"
		url = "https://www.google.com/search?q=lyrics%20to%20"
		temp = message.content
		if leftover_args:
		    args = temp[7:].strip()
		else:
		    args = args
		word = args
		for c in word:
		    if c not in filt:
		        url += "%" +  str(hex(ord(c))).replace("0x", "")
		    else:
		        url += c
		e = discord.Embed(title="Lyrics", color=member.colour, description="[Lyrics to {0}]({1})".format(word, url), timestamp=datetime.datetime.utcnow())
		e.set_footer(text='{}'.format(message.author.name), icon_url=message.author.avatar_url if message.author.avatar else message.author.default_avatar_url)
		await self.send_message(message.channel, embed=e)
		await self.update_now_playing()```
?

**Comment by jayktaylor** [comment]
There are no plans to include lyrics. It'd be hard to sync them up to the music if we wanted to, and pasting the full lyrics just seems messy. There are no proper APIs to support this, and I'd rather not scrape HTML to get this stuff.
