### ISSUE TITLE
Bot using a Discord account.

### ISSUE THREAD

**Issue by Backyusa** [Just-Some-Bots/MusicBot#1626]
Please tick all applicable boxes.

- [ ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [- ] Question

----

### Description of issue
I have updated the bot after a long time now is it still possible to you a Discordaccount instead of a bot token? If yes, how? Because I am seeing Token where there was a slot to type it account data.

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AutumnClove** [comment]
Discord no longer will tolerate user bots, and doing so is a bannable offense now. As such, the option to use email and password has been removed. 
https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-
