### ISSUE TITLE
Does not play linked video correctly

### ISSUE THREAD

**Issue by Sieabah** [Just-Some-Bots/MusicBot#1628]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

The issue I'm running into on my server is that when any user plays specific videos it plays some arbitrary video. It consistently plays specific videos though.

### Steps to reproduce

1. `!play  https://www.youtube.com/watch?v=M5625-IKTXk` becomes `PIORES intros do Youtube`
2. `!play https://www.youtube.com/watch?v=lEMljqDrgMY` becomes `Sucker for Pain - Lil Wayne, Wiz Khalifa & Imagine Dragons w/ Logic & Ty Dolla $ign ft X Ambassadors`

----

### Log file

Here is the relevant log messages

```
[186.4312684535980225] 2018-05-25 23:39:21,582 - INFO - musicbot.bot | In bot.py::MainThread(140689413682944), line 2734 in on_message: <id>/<user>: !play  https://www.youtube.com/watch?v=M5625-IKTXk
[186.4833190441131592] 2018-05-25 23:39:21,634 - DEBUG - musicbot.bot | In bot.py::MainThread(140689413682944), line 1517 in cmd_play: {'_type': 'url', 'url': 'ytsearch: https:%2F%2Fwww.youtube.com%2Fwatch?v=M5625-IKTXk', 'ie_key': None, 'extractor': 'generic', 'webpage_url': ' https:%2F%2Fwww.youtube.com%2Fwatch?v=M5625-IKTXk', 'webpage_url_basename': ' https:%2F%2Fwww.youtube.com%2Fwatch', 'extractor_key': 'Generic'}
[189.7359869480133057] 2018-05-25 23:39:24,886 - DEBUG - musicbot.entry | In entry.py::MainThread(140689413682944), line 54 in get_ready_future: Created future for None
[189.7396049499511719] 2018-05-25 23:39:24,890 - DEBUG - musicbot.bot | In bot.py::MainThread(140689413682944), line 825 in serialize_queue: Serializing queue for <id>
[189.7403049468994141] 2018-05-25 23:39:24,891 - INFO - musicbot.entry | In entry.py::MainThread(140689413682944), line 220 in _really_download: Download started: https://www.youtube.com/watch?v=AiwxMGTBuuo
[191.1594419479370117] 2018-05-25 23:39:26,310 - INFO - musicbot.bot | In bot.py::MainThread(140689413682944), line 2734 in on_message: <id>/<user>: !clear
[192.0447630882263184] 2018-05-25 23:39:27,195 - INFO - musicbot.entry | In entry.py::MainThread(140689413682944), line 230 in _really_download: Download complete: https://www.youtube.com/watch?v=AiwxMGTBuuo
```

Looking at the logs, it looks like there is a bug in the generic extractor where it'll search youtube with the url that should just be recognized as a youtube link.

**Comment by Sieabah** [comment]
Doing a little bit more digging and it looks like when youtube links play it's just by luck that it works for some of them. Some URLs result in direct results where it's not a search, for example [this](https://www.youtube.com/watch?v=HtOuP-j7WYk)

However some youtube links seem to be encoded and searched for directly. Here is the result list which seems to change over time to be the correct result. [Youtube Search](https://www.youtube.com/results?search_query=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DM5625-IKTXk&page=&utm_source=opensearch)

**Comment by AleanaA** [comment]
I wasn't able to reproduce the issue with the commands provided. The result ended up as intended.

**Comment by jayktaylor** [comment]
Note in your logs this:

```
[186.4312684535980225] 2018-05-25 23:39:21,582 - INFO - musicbot.bot | In bot.py::MainThread(140689413682944), line 2734 in on_message: <id>/<user>: !play  https://www.youtube.com/watch?v=M5625-IKTXk
```

Your users are using the play command with two spaces between `!play` and the URL, rather than one. Two spaces causes unintended behavior where the bot will treat the URL like a search query rather than playing it directly. As the bot intends for search queries to be playable too, there's not really too much I can do to prevent users accidentally doing this, so it might be wise to advise them that only one space is needed between the command and the URL.

**Comment by Sieabah** [comment]
@jaydenkieran I mean that's pretty lazy parsing, if there is absolutely nothing when you split on spaces then shouldn't it be expected behavior that the first argument of value be the first passed argument to the extrator?

i.e. Given a list ['play', '', 'http://youtube.....'], after popping the command you're left with ['', 'youtube...'] and filter from the left empty values.

If it's not a bug then it's just a bad design choice to allow two spaces (which is nearly invisible to the user) to act as a search query. In general I don't think any real search command would start with two spaces. This only affects people who don't see they may have mistakenly copied a link or copied a previously played string.

If it looks like a bug, acts like a bug, and it's not a bug, then it's a design flaw.

**Comment by jayktaylor** [comment]
Sure. You’re welcome to submit a patch. I have no real interest in improving design flaws (or in this case - something that has simply been overlooked) at the moment and would rather focus on critical bugs.

That said, I’ll reopen the issue.

**Comment by Sieabah** [comment]
When I have time I'll submit a PR.

**Comment by Sieabah** [comment]
@jaydenkieran Created a [PR](https://github.com/Just-Some-Bots/MusicBot/pull/1632) with a simple enough fix for this.

**Comment by Sieabah** [comment]
@ImthePeach Any particular reason it's on hold?

**Comment by AleanaA** [comment]
Most likely because this doesn't need to be a priority, and any occurence of this is, realistically, just user error. There are other, far larger issues in review that should be fixed before introducing extra things.

**Comment by Sieabah** [comment]
Sure I guess, but it's also such a minor change that it doesn't and shouldn't impede anyone...

**Comment by Sieabah** [comment]
I've forked it and fixed it locally because it's an annoying bug that is nearly invisible.

**Comment by ImthePeach** [comment]
It's on hold because we are busy doing other things right now, we will check out your PR when we get to it but because this issue only occurs when you accidentally double space instead of hitting it once this issue isn't of a high enough priority to get taken care of immediately. When we do implement it, it would sit in the review branch for some time anyways before we would have it pushed to the master branch based on other developments being worked on. Simply put we will test it and add it near the time we do the next push from review to master.

**Comment by ImthePeach** [comment]
This issue is fixed in the review branch. See merge [here](https://github.com/Just-Some-Bots/MusicBot/pull/1632).
