### ISSUE TITLE
Installation guide for Ubuntu

### ISSUE THREAD

**Issue by mitch619911** [Just-Some-Bots/MusicBot#163]
Followed the guide about 300 times for 7 hours and I get errors..

`root@155347:~/MusicBot-develop# sudo apt-get install python3.5
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3.5
E: Couldn't find any package by regex 'python3.5'
`

Please help...

**Comment by mitch619911** [comment]
E: Unable to locate package python3.5 
E: Couldn't find any package by regex 'python3.5'

**Comment by jord-nijhuis** [comment]
What version of Ubuntu are you running? According to [Ubuntu Packages](http://packages.ubuntu.com/wily/python3.5) the package does exist...

**Comment by mitch619911** [comment]
Its only, I got it fixed - had to buy a new VPS tho.
The version was Ubuntu14.04

**Comment by abalabahaha** [comment]
For future reference, you didn't add the deadsnakes PPA properly.
