### ISSUE TITLE
Docker: RuntimeError: PyNaCl library needed in order to use voice

### ISSUE THREAD

**Issue by mjsir911** [Just-Some-Bots/MusicBot#1630]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system <- the wiki doesnt exist anymore
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script <- using docker

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Currently docker setup does not work at all

### Steps to reproduce

1. `docker build . -t musicbot`
2. `docker run -v $PWD/config:/usr/src/musicbot/config musicbot`
```
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.

Starting MusicBot 1.9.7
Loaded autoplaylist with 2531 entries
.

Not autojoining any voice channels

[ERROR:bot] Unknown error attempting to connect to voice
Traceback (most recent call last):
  File "/usr/src/musicbot/musicbot/bot.py", line 456, in get_voice_client
    vc = await self.join_voice_channel(channel)
  File "/usr/src/musicbot/musicbot/bot.py", line 416, in join_voice_channel
    voice = discord.VoiceClient(**kwargs)
  File "/usr/lib/python3.6/site-packages/discord/voice_client.py", line 217, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice
```

----

Debugging:
```
$ docker run -it --entrypoint=python3 -v $PWD/config:/usr/src/musicbot/config musicbot
Python 3.6.4 (default, Apr  6 2018, 05:23:32) 
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nacl.secret
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/nacl/secret.py", line 18, in <module>
    import nacl.bindings
  File "/usr/lib/python3.6/site-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_box import (
  File "/usr/lib/python3.6/site-packages/nacl/bindings/crypto_box.py", line 17, in <module>
    from nacl._sodium import ffi, lib
ImportError: Error loading shared library libsodium.so.23: No such file or directory (needed by /usr/lib/python3.6/site-packages/nacl/_sodium.cpython-36m-x86_64-linux-gnu.so)
```

Looks like it wants libsodium installed

**Comment by mjsir911** [comment]
Yea, just got to add libsodium to installed packages, attaching patch
[0001-Add-libsodium-as-dependency.patch.gz](https://github.com/Just-Some-Bots/MusicBot/files/2042962/0001-Add-libsodium-as-dependency.patch.gz)

Let me know if you want me to file a PR

**Comment by ImthePeach** [comment]
The docker file should already have the lines to have libsodium installed in the review version, see: https://github.com/Just-Some-Bots/MusicBot/blob/review/Dockerfile#L14
If this is no longer working properly you can feel free to submit a PR to the review branch of the bot with a way it will work properly. 
We don't officially support docker anymore but the file still exists for those who do use it and can mainly figure it out on their own.

**Comment by mjsir911** [comment]
Yea I can confirm that this issue doesn't exist on the review branch.

I'm disappointed that you don't really support docker anymore, I think it's a great addition and an easier way to install and configure this.
