### ISSUE TITLE
[DOCS] Update raspbian install instructions

### ISSUE THREAD

**Issue by vico93** [Just-Some-Bots/MusicBot#1631]
Python 3.5 is available for raspbian via the package `python3` ([proof](https://www.reddit.com/r/raspberry_pi/comments/8hq4ij/what_version_of_of_python_comes_with_the_newest/dylqw4b/?context=3)). So no need to compile it from scratch anymore.

**Comment by ImthePeach** [comment]
Need more proof than random Reddit comments. Currently this is the best option to install Python 3.5 on raspbian. Other methods have proved to have outdated/unreliable packages, and ssl issues.

**Comment by vico93** [comment]
This is not just a "random comment" lol.
Anyway here you go, some from official raspberry pi forums:

https://www.raspberrypi.org/forums/viewtopic.php?t=145706

https://www.raspberrypi.org/documentation/linux/software/python.md

https://raspberrypi.stackexchange.com/questions/15244/installing-python-3-4-on-raspberry-pi

**Comment by AleanaA** [comment]
The point wasn't that it didn't work or that you couldn't, it was that installing through apt-get, at one point, was outdated and had ssl issues which prevented it from being reliable. I tested it earlier for them and proved that installing in apt-get worked fine and lacked the ssl issues described.

**Comment by ImthePeach** [comment]
Will update once approved by head developer now that more proof has shown that we aren't experiencing SSL issues and other unreliabilities. Thanks @AleanaA for the digging.
