### ISSUE TITLE
Issue with Permission for Instant Skip

### ISSUE THREAD

**Issue by AnsonKoh** [Just-Some-Bots/MusicBot#1633]
Please tick all applicable boxes.

- [/ ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [/ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ /] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [/ ] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- /[ ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
I have added my ID under Music Master but I still can't seem to have the permission to instant 
skip. I still have to wait for multiple people to type .skip before i am able to skip the song.

[config.zip](https://github.com/Just-Some-Bots/MusicBot/files/2058019/config.zip)
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2058022/musicbot.log)

### Steps to reproduce

1. -

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by mwallis45** [comment]
you should try `!skip f`. it was added in the latest notes please make sure to read them

**Comment by MattBSG** [comment]
Yes, force skip has been changed to `!skip f`. Please check documentation before submitting and issue in the future
