### ISSUE TITLE
Unable to instaskip as owner

### ISSUE THREAD

**Issue by reverie888** [Just-Some-Bots/MusicBot#1635]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
Unable to instaskip as owner , putting my  userid in the both option and permission config does not work too

### Steps to reproduce
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2063539/musicbot.log)

1.
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2063536/musicbot.log)
 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by mwallis45** [comment]
try `!skip f`. Please read the release note next time.

**Comment by reverie888** [comment]
thanks
