### ISSUE TITLE
no git command

### ISSUE THREAD

**Issue by CharlesCanlom** [Just-Some-Bots/MusicBot#1636]
my Windows 10 command prompt is not recongnized my git clone command

**Comment by AutumnClove** [comment]
Install git to your path

**Comment by Argos-Rho** [comment]
> Install git to your path

To add onto that, git should ask you to add it during install.

If you installed Git Bash, Find that executable and use that instead of reinstalling.

**Comment by MattBSG** [comment]
Pebkac.
