### ISSUE TITLE
Not Responding to Commands

### ISSUE THREAD

**Issue by H2Owe** [Just-Some-Bots/MusicBot#1637]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
The music bot wont respond to commands. I've restarted, and reinstalled

### Steps to reproduce

1. Run via MusicBot/run.bat
2. Use !skip/!play [link]/!help
3. No response

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2068009/musicbot.log)

**Comment by MattBSG** [comment]
Can the bot read messages for the channel which you are trying to run the command in?

**Comment by H2Owe** [comment]
wow, I cant believe I didn't think of this, thank you so much <3
