### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Naterbater0703** [Just-Some-Bots/MusicBot#1639]
i have everything correctly installed even my bot is in y discord but when i run the consle it says Bot was not installed using git. what do i do

**Comment by AleanaA** [comment]
If you followed a video guide, or downloaded a ZIP file, then you have installed the bot incorrectly. As a result, we will not provide support to you until you install the bot correctly, using the appropriate guide here: https://just-some-bots.github.io/MusicBot/. An error will be thrown if you have installed the bot incorrectly.
