### ISSUE TITLE
Request: Write messages in the name of the bot

### ISSUE THREAD

**Issue by daniel-san-fried** [Just-Some-Bots/MusicBot#1644]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (1.9.7)
- [X ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [X] Feature request
- [ ] Question

----

### Request

Hi together, is it possible to print a message into the chat in the bot's name? We have some polls going on for music and update the playlist once in a while, would be nice to announce that "as the bot iteself". Is that possible in some way? Thanks!

**Comment by MattBSG** [comment]
Not at this time and probably won’t ever be as there no practical need. If you add yourself to the dev ids in options.ini you can do an eval command to send a message, but that involves knowing some python at the least
