### ISSUE TITLE
Bot joining problem

### ISSUE THREAD

**Issue by Sterminous** [Just-Some-Bots/MusicBot#1645]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
I'm using CentOS 7.4 and Python 3.5.4
Bot appears in voice server but then that error count starts. I have tried changing server region, doesn't work.
http://prntscr.com/jww7yy

Also when I directly download that same MusicBot folder to my pc and then run "run.py" it works. 
### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2116815/musicbot.log)

**Comment by Sterminous** [comment]
Still same problem

**Comment by AleanaA** [comment]
You said you downloaded it and running it works, that indicates to me that the issue has nothing to do with the bot, but is an issue with your hosts connection to discord's voice servers.

**Comment by Sterminous** [comment]
The problem was with Hetzner hosting. They are still blocking Hetzner ips, but only in voice servers, text servers work just fine. Also there is no workaround.
