### ISSUE TITLE
BOT DOES NOT COME ONLINE!!!!!

### ISSUE THREAD

**Issue by goncazevedo** [Just-Some-Bots/MusicBot#1646]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue

I installed everything as it was in the guide. The bot joined the server, but it don`t go online and don`t responds anyone. It has admin permissions. PLEASE HELP ME

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2125557/musicbot.log)

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AleanaA** [comment]
Make sure your spotify information is correct. To see if that's the issue, remove your spotify info and try starting the bot. If it works fine after removing that information, you'll have to make sure that what you put in is correct.

**Comment by goncazevedo** [comment]
Thanks a lot it actually worked!! I´ll look for the correct information

**Comment by AutumnClove** [comment]
https://just-some-bots.github.io/MusicBot/using/spotify/
