### ISSUE TITLE
This command is not enabled for your group (Default)

### ISSUE THREAD

**Issue by Aushuna** [Just-Some-Bots/MusicBot#1647]
Please tick all applicable boxes.

- [Y] I am using Python 3.5 or higher (run `python --version` on the command line)
- [Y] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [Y] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [Y] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [Y] Question

----

### Description of issue

You don't have permission to use that command.
Reason: This command is not enabled for your group (Default).

before the bot did not have this issue where it would listen to everyone but now it will only listen to me, the server owner.

**Comment by AleanaA** [comment]
You most likely messed up somewhere in the permissions file.

**Comment by MattBSG** [comment]
Please post your permissions.ini file here as an attachment

**Comment by ImthePeach** [comment]
Non reproducible issue left open for nearly a week, reopen if you continue to experience a problem or join the support server for more help http://discord.gg/bots
