### ISSUE TITLE
Failed to update dependencies.

### ISSUE THREAD

**Issue by Max-Spec** [Just-Some-Bots/MusicBot#1648]
Please tick all applicable boxes.

- [!] I am using Python 3.5 or higher (run `python --version` on the command line)
- [!] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [!] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [!] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
update.bat just closes and reopens itself when i try to open it. I've installed everything i needed, configured everything right... But when i try to do the last step, it just stops there.

### Steps to reproduce

1. Open update.bat

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2130082/musicbot.log)

**Comment by Max-Spec** [comment]
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

Starting MusicBot 1.9.7
Loaded autoplaylist with 2531 entries

[INFO] launcher: All done.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x06660C10>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x06660D70>
That's what happens when i run it.
My Python version is 3.5.4.

**Comment by AleanaA** [comment]
Try removing your Spotify information, if it works afterwards, you put in
the wrong info.

**Comment by Max-Spec** [comment]
Wait, then what Spotify info should i put instead?

**Comment by AutumnClove** [comment]
https://just-some-bots.github.io/MusicBot/using/spotify/

**Comment by Max-Spec** [comment]
After removing Spotify info, MusicBot launched, but update.bat doesn't work..

**Comment by AleanaA** [comment]
If the bot started, there's no reason to run update.bat

**Comment by Max-Spec** [comment]
Well, okay. I think we need to close this issue. Thank you.
