### ISSUE TITLE
Users requesting playlist are being blocked somehow

### ISSUE THREAD

**Issue by Dradonis** [Just-Some-Bots/MusicBot#1651]
Please tick all applicable boxes.

- [ y] I am using Python 3.5 or higher (run `python --version` on the command line)
- [y ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [y ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [y ] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [y ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
I have tried in both musicmaster role and default role to allow playlists but it just gives "Error
You don't have permission to use that command.
Reason: You do not have permission to play media from this service."

However requesting a single song works and if I request the playlist as the owner it works fine

### Steps to reproduce

1. The permissions settings are as follows
[Default]
CommandWhitelist = play perms queue np skip search id help clean
; CommandBlacklist =
IgnoreNonVoice = play skip search
MaxSongLength = 0
MaxSongs = 0
AllowPlaylists = yes
MaxPlaylistLength = 0
InstaSkip = no
Remove = yes
SkipWhenAbsent = no
BypassKaraokeMode = no
Extractors = generic youtube soundcloud

; This group has full permissions.
[MusicMaster]
; GrantToRoles =
UserList =166286604992905221 123794355247906816 132475045107859456 124243180005621761 148122148626497536 123751781447499776
IgnoreNonVoice = play skip search queue np skip search clean id
MaxSongLength = 0
MaxSongs = 0
AllowPlaylists = yes
MaxPlaylistLength = 0
InstaSkip = no
Remove = yes
SkipWhenAbsent = yes
BypassKaraokeMode = no
Extractors = generic youtube soundcloud

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2145761/musicbot.log)

**Comment by AleanaA** [comment]
Add youtube:playlist to the extractors list.

**Comment by Dradonis** [comment]
Thanks
