### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Bagiii** [Just-Some-Bots/MusicBot#1652]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [x] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [x] Question

----

### Description of issue

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 347, in main
    from musicbot import MusicBot
  File "C:\Users\ljiki\Desktop\musicbot\MusicBot\musicbot\__init__.py", line 6, in <module>
    from discord.ext.commands.bot import _get_variable
ModuleNotFoundError: No module named 'discord'
[INFO] launcher: Attempting to install dependencies...
Collecting discord.py[voice]~=0.16.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/97/3c/2a97b47fd8839f8863241857bbd6a3998d1de1662b788c8d9322e5a40901/discord.py-0.16.12.tar.gz
Requirement already up-to-date: pip in e:\python\lib\site-packages (from -r requirements.txt (line 2)) (10.0.1)
Collecting youtube_dl (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/3c/dd/e2d14546fa79ce964d0f689905c595469aad1c5fd3d5c328b8d8a737593b/youtube_dl-2018.6.25-py2.py3-none-any.whl
Collecting colorlog (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/69/eb/58ae10d3c46a0195ffdd0e3943d255d0d5029d71e5457785ecd665bcf0f3/colorlog-3.1.4-py2.py3-none-any.whl
Requirement already up-to-date: cffi in e:\python\lib\site-packages (from -r requirements.txt (line 5)) (1.11.5)
Requirement not upgraded as not directly required: aiohttp<1.1.0,>=1.0.0 in e:\python\lib\site-packages (from discord.py[voice]~=0.16.0->-r requirements.txt (line 1)) (1.0.5)
Requirement not upgraded as not directly required: websockets<4.0,>=3.1 in e:\python\lib\site-packages (from discord.py[voice]~=0.16.0->-r requirements.txt (line 1)) (3.4)
Collecting PyNaCl==1.0.1 (from discord.py[voice]~=0.16.0->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/dd/99/bc86d40c88c1e1c6c9338d5afa91e3126d1ae28ad1bdfac79ab5b01803df/PyNaCl-1.0.1.tar.gz
Collecting colorama; sys_platform == "win32" (from colorlog->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
Requirement not upgraded as not directly required: pycparser in e:\python\lib\site-packages (from cffi->-r requirements.txt (line 5)) (2.18)
Requirement not upgraded as not directly required: chardet in e:\python\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.16.0->-r requirements.txt (line 1)) (3.0.4)
Requirement not upgraded as not directly required: multidict>=2.0 in e:\python\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.16.0->-r requirements.txt (line 1)) (4.3.1)
Requirement not upgraded as not directly required: async_timeout in e:\python\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.16.0->-r requirements.txt (line 1)) (3.0.0)
Requirement not upgraded as not directly required: six in e:\python\lib\site-packages (from PyNaCl==1.0.1->discord.py[voice]~=0.16.0->-r requirements.txt (line 1)) (1.11.0)
Installing collected packages: PyNaCl, discord.py, youtube-dl, colorama, colorlog
  Running setup.py install for PyNaCl ... error
    Complete output from command E:\Python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ljiki\\AppData\\Local\\Temp\\pip-install-bzq1kp0u\\PyNaCl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ljiki\AppData\Local\Temp\pip-record-9ohtn592\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\nacl
    copying src\nacl\encoding.py -> build\lib.win32-3.7\nacl
    copying src\nacl\exceptions.py -> build\lib.win32-3.7\nacl
    copying src\nacl\hash.py -> build\lib.win32-3.7\nacl
    copying src\nacl\public.py -> build\lib.win32-3.7\nacl
    copying src\nacl\secret.py -> build\lib.win32-3.7\nacl
    copying src\nacl\signing.py -> build\lib.win32-3.7\nacl
    copying src\nacl\utils.py -> build\lib.win32-3.7\nacl
    copying src\nacl\__init__.py -> build\lib.win32-3.7\nacl
    creating build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_box.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_hash.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_scalarmult.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_secretbox.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_sign.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\randombytes.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\sodium_core.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\__init__.py -> build\lib.win32-3.7\nacl\bindings
    running build_clib
    error: [WinError 193] %1 is not a valid Win32 application

    ----------------------------------------
Command "E:\Python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ljiki\\AppData\\Local\\Temp\\pip-install-bzq1kp0u\\PyNaCl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ljiki\AppData\Local\Temp\pip-record-9ohtn592\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ljiki\AppData\Local\Temp\pip-install-bzq1kp0u\PyNaCl\

[CRITICAL] launcher: You may need to run as admin to install dependencies.

[INFO] launcher: All done.

### Steps to reproduce

1. just run update.bat

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2147224/musicbot.log)

**Comment by AleanaA** [comment]
What does `python -v` in a command prompt output?

**Comment by Bagiii** [comment]
This i guess

import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'zipimport' # <class '_frozen_importlib.BuiltinImporter'>
# installed zipimport hook
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'nt' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import 'winreg' # <class '_frozen_importlib.BuiltinImporter'>
# E:\Python\lib\encodings\__pycache__\__init__.cpython-37.pyc matches E:\Python\lib\encodings\__init__.py
# code object from 'E:\\Python\\lib\\encodings\\__pycache__\\__init__.cpython-37.pyc'
# E:\Python\lib\__pycache__\codecs.cpython-37.pyc matches E:\Python\lib\codecs.py
# code object from 'E:\\Python\\lib\\__pycache__\\codecs.cpython-37.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x053C8EF0>
# E:\Python\lib\encodings\__pycache__\aliases.cpython-37.pyc matches E:\Python\lib\encodings\aliases.py
# code object from 'E:\\Python\\lib\\encodings\\__pycache__\\aliases.cpython-37.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x053E00F0>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x053C87B0>
# E:\Python\lib\encodings\__pycache__\utf_8.cpython-37.pyc matches E:\Python\lib\encodings\utf_8.py
# code object from 'E:\\Python\\lib\\encodings\\__pycache__\\utf_8.cpython-37.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x053EAF90>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# E:\Python\lib\encodings\__pycache__\latin_1.cpython-37.pyc matches E:\Python\lib\encodings\latin_1.py
# code object from 'E:\\Python\\lib\\encodings\\__pycache__\\latin_1.cpython-37.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0x053EE1F0>
# E:\Python\lib\__pycache__\io.cpython-37.pyc matches E:\Python\lib\io.py
# code object from 'E:\\Python\\lib\\__pycache__\\io.cpython-37.pyc'
# E:\Python\lib\__pycache__\abc.cpython-37.pyc matches E:\Python\lib\abc.py
# code object from 'E:\\Python\\lib\\__pycache__\\abc.cpython-37.pyc'
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x053EE450>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x053EE2B0>
# E:\Python\lib\__pycache__\site.cpython-37.pyc matches E:\Python\lib\site.py
# code object from 'E:\\Python\\lib\\__pycache__\\site.cpython-37.pyc'
# E:\Python\lib\__pycache__\os.cpython-37.pyc matches E:\Python\lib\os.py
# code object from 'E:\\Python\\lib\\__pycache__\\os.cpython-37.pyc'
# E:\Python\lib\__pycache__\stat.cpython-37.pyc matches E:\Python\lib\stat.py
# code object from 'E:\\Python\\lib\\__pycache__\\stat.cpython-37.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x054F0E30>
# E:\Python\lib\__pycache__\ntpath.cpython-37.pyc matches E:\Python\lib\ntpath.py
# code object from 'E:\\Python\\lib\\__pycache__\\ntpath.cpython-37.pyc'
# E:\Python\lib\__pycache__\genericpath.cpython-37.pyc matches E:\Python\lib\genericpath.py
# code object from 'E:\\Python\\lib\\__pycache__\\genericpath.cpython-37.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x054F7FB0>
import 'ntpath' # <_frozen_importlib_external.SourceFileLoader object at 0x054F0F30>
# E:\Python\lib\__pycache__\_collections_abc.cpython-37.pyc matches E:\Python\lib\_collections_abc.py
# code object from 'E:\\Python\\lib\\__pycache__\\_collections_abc.cpython-37.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x054FE370>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x053FA770>
# E:\Python\lib\__pycache__\_sitebuiltins.cpython-37.pyc matches E:\Python\lib\_sitebuiltins.py
# code object from 'E:\\Python\\lib\\__pycache__\\_sitebuiltins.cpython-37.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x053FAC30>
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x053EEC70>
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>

**Comment by AleanaA** [comment]
Uninstall python 3.7, and please use python 3.5.4, as per the guide.
edit: Also please for use code blocks, that's cancerous to look at.

**Comment by Bagiii** [comment]
oh ok
