### ISSUE TITLE
Unable to set/change avatar (for the bot)

### ISSUE THREAD

**Issue by HaydenJM** [Just-Some-Bots/MusicBot#1655]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)

What type of issue are you creating?

- [x] Bug

----

### Description of issue

Unable to set/change the avatar of the bot using the -setavatar command.
I attempted to use a direct URL to the image. (http://img.sugarcookie.org/i/rnbw-paw.png)
I also tried using a smaller version of the image, as well as the same image in the jpeg format.

### Steps to reproduce

Invoking setavatar, followed by a direct image URL

Ex. -setavatar http://img.sugarcookie.org/i/rnbw-paw.png

----

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2160663/musicbot.log)

**Comment by MattBSG** [comment]
Hi there,

I was unable to reproduce that bug, can you send the full unaltered musicbot.log for me?

**Comment by HaydenJM** [comment]
I have no clue what I did different this time around, but the command worked for me as I went to reproduce the same error I was getting before. Bravo! Haha.. I feel silly now - Will mark as closed.
