### ISSUE TITLE
AllowAuthorSkip/Invoking the skip command as bot owner

### ISSUE THREAD

**Issue by HaydenJM** [Just-Some-Bots/MusicBot#1656]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)

What type of issue are you creating?

- [x] Bug

----

### Description of issue

Although 'AllowAuthorSkip' is set as 'yes' the author, the original poster, and even the bot owner (myself) are unable to skip the song in queue without a majority vote from the channel. As the "bot owner," in the past, I was able to skip any song in the queue without the help of the channel majority, but it seems that this is no longer the case. Whether this is intentional or otherwise, I am creating a post anyways.

### Steps to reproduce

Instance 1
1. User A queues a song.
2. User A attempts to skip the song that they posted.
3. The bot specifies that it requires 1-2 more votes before that song can be skipped in queue.

Instance 2
1. Bot Owner attempts to skip a song in queue, whether they are the original poster, or not.
2. The bot specifies that it requires 1-2 more votes before the song can be skipped in queue.

----

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2160713/musicbot.log)

**Comment by AleanaA** [comment]
use `!skip f`

**Comment by HaydenJM** [comment]
I feel thoroughly silly now, thank you! Will close this issue.
