### ISSUE TITLE
Running the bot as a Windows Service

### ISSUE THREAD

**Issue by HaydenJM** [Just-Some-Bots/MusicBot#1657]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)

What type of issue are you creating?

- [x] Question

----

Should I just not ever do this, and is there good reason behind why or why not?
What might be the pros/cons to running the bot as a Windows Service?
Would running the bot as a Windows Service be viable?

I'm interested if anyone has any insight on running the bot as a Windows Service.

----

**Comment by MattBSG** [comment]
In my experience making a windows service is not ideal at all. It has caused some pain for some people setting up and you just don't get the nice usage of the like of pm2 or tmux on windows. Although certainly possible the reason we don't have a guide on it is none of the maintainers use MusicBot natively in a Windows environment.

It *could* be viable, but you have to note that it will be hard to control for example if it hard crashes etc. Making a batch file and setting that as a startup program might be a better option (windows has a start parameter to start a window minimized as well). You can google a bit, but I am very unaware of the instability it may have as a Windows service. Feel free to experiment and try it out though!

**Comment by HaydenJM** [comment]
Alright, that all makes sense. I already have a batch file to start the bot, so I guess I was just curious about any alternatives. Thank you for your insight and assistance.

**Comment by MattBSG** [comment]
No problem 👍
