### ISSUE TITLE
Bad Credentials issue please send help ._.

### ISSUE THREAD

**Issue by AlfonsoXL** [Just-Some-Bots/MusicBot#1661]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
Bad credentials I have repeatedly changed my token to try to fix the "bad credentials" but it doesn't work even though i am giving the correct token that i was given by the discord dev site were the bot token is generated from. 

![image](https://user-images.githubusercontent.com/40882130/42401029-ca53c1fa-8141-11e8-9cd5-0379221e2355.png)

**Comment by AutumnClove** [comment]
Did you use secret by mistake?

**Comment by AlfonsoXL** [comment]
?

**Comment by AlfonsoXL** [comment]
oh i didn't

**Comment by AlfonsoXL** [comment]
I used bot token under "App Bot User"

**Comment by AleanaA** [comment]
If using notepad++, did *you* save? It doesn't save on it's own.

**Comment by AlfonsoXL** [comment]
hmm

**Comment by AlfonsoXL** [comment]
oh thanks!

**Comment by AlfonsoXL** [comment]
im such a idiot and a moron
