### ISSUE TITLE
use @bot as commandprefix

### ISSUE THREAD

**Issue by nawey** [Just-Some-Bots/MusicBot#1662]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [X] Question

----

I would like to invoke the bot using a @name command, but im not sure if this would fall under modifications?

**Comment by AutumnClove** [comment]
Set prefix to <@BOT_ID> I think would do this?

**Comment by AutumnClove** [comment]
The option to change your prefix is in `config/options.ini`

**Comment by nawey** [comment]
using <@BOT_ID> its not working, would i need to modify the code? or can i do this just with the options.ine file

**Comment by AleanaA** [comment]
To make it work properly would require modifying the code, and is
relatively simple to do for what you're asking.

**Comment by ImthePeach** [comment]
This is something we have talked about before for proper bot practices. It may be implemented in the future when the bot is fully reworked but include "short hand" command prefixes as an option. Hopefully this answers your question, any other questions about this you can feel free to re-open the thread or ask on our support server at http://discord.gg/bots
