### ISSUE TITLE
MusicBot on Raspian won't run.

### ISSUE THREAD

**Issue by XFlawless1** [Just-Some-Bots/MusicBot#1664]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

```
pi@master:~/MusicBot $ ./run.sh
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
### [ERROR] launcher: Syntax error (this is a bug, not your fault)
Traceback (most recent call last):
  File "run.py", line 347, in main
    from musicbot import MusicBot
  File "/home/pi/MusicBot/musicbot/__init__.py", line 6, in <module>
    from discord.ext.commands.bot import _get_variable
  File "/usr/local/lib/python3.7/site-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 38, in <module>
    from .state import ConnectionState
  File "/usr/local/lib/python3.7/site-packages/discord/state.py", line 36, in <module>
    from . import utils, compat
  File "/usr/local/lib/python3.7/site-packages/discord/compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax

[INFO] launcher: All done.


```
### Steps to reproduce

1. Oh, just sudo or not sudo ./run.sh on your raspian with python 3.7.0 pip3.5 or pip3.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

> [116.614103317] 2018-07-09 12:31:23,726 - INFO - launcher: Starting sanity chec$
> [117.436408997] 2018-07-09 12:31:23,727 - INFO - launcher: Checking for Python $
> [117.907285690] 2018-07-09 12:31:23,727 - INFO - launcher: Checking console enc$
> [118.368864059] 2018-07-09 12:31:23,727 - INFO - launcher: Ensuring we're in th$
> [121.848106384] 2018-07-09 12:31:23,731 - INFO - launcher: Required checks pass$
> [122.842073441] 2018-07-09 12:31:23,732 - INFO - launcher: Optional checks pass$
> [123.770236969] 2018-07-09 12:31:23,733 - INFO - launcher: Moving old musicbot $
> 
> ######################### PRE-RUN SANITY CHECKS PASSED #########################
> 
> [385.220527649] launcher-ERROR: Syntax error (this is a bug, not your fault)
> Traceback (most recent call last):
>   File "run.py", line 347, in main
>     from musicbot import MusicBot
>   File "/home/pi/MusicBot/musicbot/__init__.py", line 6, in <module>
>     from discord.ext.commands.bot import _get_variable
>   File "/usr/local/lib/python3.7/site-packages/discord/__init__.py", line 20, i$
>     from .client import Client, AppInfo, ChannelPermissions
>   File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 38, in $
>

**Comment by AleanaA** [comment]
I don't know that the bot is compatible with python 3.7, use 3.5.4 or higher, or 3.6

**Comment by XFlawless1** [comment]
I tried the same with 3.5.0 same error.

**Comment by AleanaA** [comment]
Log output?

**Comment by ImthePeach** [comment]
Due to dependency issues python 3.5.x is the only recommended version currently. Please try using a version of python 3.5 to install dependencies and then try running the bot.

**Comment by XFlawless1** [comment]
It was written python 3.5 or above.. I recommend to update the installation notes/documentation.

**Comment by AleanaA** [comment]
Supported versions of python for the bot are 3.5 and 3.6, there is an
indicator on the main repo page with this information.
It should also be noted that the raspi guide is outdated, and at some point
should be rewritten.
