### ISSUE TITLE
Installing bot

### ISSUE THREAD

**Issue by mrmiijo** [Just-Some-Bots/MusicBot#1665]
I have problem with installing bot.. i setting it with this introduction: https://just-some-bots.github.io/MusicBot/installing/debian/

But, when i want write these commands:

`sudo -H python3.5 -m pip install --upgrade pip
`
`sudo -H python3.5 -m pip install --upgrade -r requirements.txt
`
it doesn't work...

it writes:
`~/MusicBot# sudo -H python3.5 -m pip install --upgrade pip
`
`/usr/bin/python3.5: No module named pip
`
`/MusicBot# sudo -H python3.5 -m pip install --upgrade -r requirements.txt
`
`/usr/bin/python3.5: No module named pip
`

Where is the problem? Thanks..

**Comment by AleanaA** [comment]
Run `sudo apt install python3-pip`

**Comment by mrmiijo** [comment]
Thank you, everything now work!
