### ISSUE TITLE
Cannot use stream on anything anymore

### ISSUE THREAD

**Issue by nolsen42** [Just-Some-Bots/MusicBot#1666]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.7)
- [X] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

the stream command, despite being able to play any video without having to download it, will not work for ANY video link.

### Steps to reproduce

1. Stream any video

----

### Log file

[ERROR:bot] Error in stream: ExtractionError: This is not a stream.
Traceback (most recent call last):
  File "/raid1/MusicBot/musicbot/bot.py", line 2706, in on_message
    response = await handler(**handler_kwargs)
  File "/raid1/MusicBot/musicbot/bot.py", line 1631, in cmd_stream
    await player.playlist.add_stream_entry(song_url, channel=channel, author=author)
  File "/raid1/MusicBot/musicbot/playlist.py", line 144, in add_stream_entry
    raise ExtractionError("This is not a stream.")
musicbot.exceptions.ExtractionError: This is not a stream.

**Comment by MattBSG** [comment]
Stream is **only** for live streams and radio streams. Not for streaming a video so it does not download through cache

**Comment by ImthePeach** [comment]
!play command is for videos 
!stream command is for streams
stream means it's constant/live where as playing a standard video means it is not a stream.
supported sites: https://rg3.github.io/youtube-dl/supportedsites.html
