### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1667]
Please tick all applicable boxes.

- [x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ x] The latest `master` version (1.9.7)
- [ x] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [ x] Question

----

### Description of issue

Multiple Errors:
1. [ERROR] launcher: Error starting bot
2. error: [WinError 193] %1 ist keine zul\xe4ssige Win32-Anwendung (the text is german, it says that something is not a win 32 application)
3. a red text:

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2182059/musicbot.log)
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2182061/musicbot.log)
Command "C:\Users\Jonas\AppData\Local\Programs\Python\Python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Jonas\\AppData\\Local\\Temp\\pip-install-dtte7t2j\\PyNaCl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Jonas\AppData\Local\Temp\pip-record-qkmpkiw9\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Jonas\AppData\Local\Temp\pip-install-dtte7t2j\PyNaCl\

### Steps to reproduce

1.  I just did everything like the tutorial said.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AutumnClove** [comment]
Did you even read the guide install python 3.5.4 and uninstall 3.7

**Comment by ghost** [comment]
I have 4 different versions of python on my computer, but the newest i installed is 3.5.4

**Comment by ghost** [comment]
i uninstalled the other ones and it works now, thank u man!
