### ISSUE TITLE
Issues getting the bot to work initially

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1668]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue

I have two issues, issue 1 
![image](https://user-images.githubusercontent.com/30348562/42734927-e7377a4c-8843-11e8-87be-3fb45ef4fd37.png)

and issue 2

![error 2](https://user-images.githubusercontent.com/30348562/42734925-ddaed1be-8843-11e8-8cbf-afc77ddc6416.png)

Both still happen when running as an admin, not entirely sure what I've done wrong

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2195770/musicbot.log)

**Comment by AutumnClove** [comment]
Run the update file

**Comment by AutumnClove** [comment]
O wait didn't see the second screenshot, please uninstall python 3.7 and install 3.5.4

**Comment by ghost** [comment]
that worked perfectly, thanks!
