### ISSUE TITLE
How to remove "Just-Some-Bots/MusicBot (1.9.7)" under the commands?

### ISSUE THREAD

**Issue by Livux** [Just-Some-Bots/MusicBot#1669]
Hello,

how to remove the "Just-Some-Bots/MusicBot (1.9.7)" under the command texts?

![image](https://user-images.githubusercontent.com/1157735/42818920-62803754-89d2-11e8-8400-0112e28dc833.png)

**Comment by jayktaylor** [comment]
https://github.com/Just-Some-Bots/MusicBot/blob/master/musicbot/bot.py#L1227

**Comment by Livux** [comment]
Man, you are awesome. Is there a way to donate ?

**Comment by MattBSG** [comment]
Thank you for the consideration, but we do not accept donations :)
