### ISSUE TITLE
[CRITICAL] launcher: You may need to run as admin to install dependencies.

### ISSUE THREAD

**Issue by XanderKho** [Just-Some-Bots/MusicBot#1670]
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 347, in main
    from musicbot import MusicBot
  File "C:\Users\Xande-Kho\Desktop\Music Bot\MusicBot\MusicBot\musicbot\__init__.py", line 6, in <module>
    from discord.ext.commands.bot import _get_variable
ModuleNotFoundError: No module named 'discord'
[INFO] launcher: Attempting to install dependencies...
Collecting discord.py[voice]~=0.16.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/97/3c/2a97b47fd8839f8863241857bbd6a3998d1de1662b788c8d9322e5a40901/discord.py-0.16.12.tar.gz
Requirement already up-to-date: pip in c:\users\xande-kho\appdata\local\programs\python\python37-32\lib\site-packages (from -r requirements.txt (line 2)) (10.0.1)
Collecting youtube_dl (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/5f/d5/a279c682e5614ca21a77a40b83c9b72ce200426eeda7c0e7978b3537bb3e/youtube_dl-2018.7.10-py2.py3-none-any.whl
Collecting colorlog (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/69/eb/58ae10d3c46a0195ffdd0e3943d255d0d5029d71e5457785ecd665bcf0f3/colorlog-3.1.4-py2.py3-none-any.whl
Requirement already up-to-date: cffi in c:\users\xande-kho\appdata\local\programs\python\python37-32\lib\site-packages (from -r requirements.txt (line 5)) (1.11.5)
Requirement not upgraded as not directly required: aiohttp<1.1.0,>=1.0.0 in c:\users\xande-kho\appdata\local\programs\python\python37-32\lib\site-packages (from discord.py[voice]~=0.16.0->-r requirements.txt (line 1)) (1.0.5)
Requirement not upgraded as not directly required: websockets<4.0,>=3.1 in c:\users\xande-kho\appdata\local\programs\python\python37-32\lib\site-packages (from discord.py[voice]~=0.16.0->-r requirements.txt (line 1)) (3.4)
Collecting PyNaCl==1.0.1 (from discord.py[voice]~=0.16.0->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/dd/99/bc86d40c88c1e1c6c9338d5afa91e3126d1ae28ad1bdfac79ab5b01803df/PyNaCl-1.0.1.tar.gz
Collecting colorama; sys_platform == "win32" (from colorlog->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
Requirement not upgraded as not directly required: pycparser in c:\users\xande-kho\appdata\local\programs\python\python37-32\lib\site-packages (from cffi->-r requirements.txt (line 5)) (2.18)
Requirement not upgraded as not directly required: chardet in c:\users\xande-kho\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.16.0->-r requirements.txt (line 1)) (3.0.4)
Requirement not upgraded as not directly required: multidict>=2.0 in c:\users\xande-kho\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.16.0->-r requirements.txt (line 1)) (4.3.1)
Requirement not upgraded as not directly required: async_timeout in c:\users\xande-kho\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.16.0->-r requirements.txt (line 1)) (3.0.0)
Requirement not upgraded as not directly required: six in c:\users\xande-kho\appdata\local\programs\python\python37-32\lib\site-packages (from PyNaCl==1.0.1->discord.py[voice]~=0.16.0->-r requirements.txt (line 1)) (1.11.0)
Installing collected packages: PyNaCl, discord.py, youtube-dl, colorama, colorlog
  Running setup.py install for PyNaCl ... error
    Complete output from command C:\Users\Xande-Kho\AppData\Local\Programs\Python\Python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\XANDE-~1\\AppData\\Local\\Temp\\pip-install-r876wdx3\\PyNaCl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\XANDE-~1\AppData\Local\Temp\pip-record-lrau8ycm\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\nacl
    copying src\nacl\encoding.py -> build\lib.win32-3.7\nacl
    copying src\nacl\exceptions.py -> build\lib.win32-3.7\nacl
    copying src\nacl\hash.py -> build\lib.win32-3.7\nacl
    copying src\nacl\public.py -> build\lib.win32-3.7\nacl
    copying src\nacl\secret.py -> build\lib.win32-3.7\nacl
    copying src\nacl\signing.py -> build\lib.win32-3.7\nacl
    copying src\nacl\utils.py -> build\lib.win32-3.7\nacl
    copying src\nacl\__init__.py -> build\lib.win32-3.7\nacl
    creating build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_box.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_hash.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_scalarmult.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_secretbox.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_sign.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\randombytes.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\sodium_core.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\__init__.py -> build\lib.win32-3.7\nacl\bindings
    running build_clib
    error: [WinError 193] %1 is not a valid Win32 application

    ----------------------------------------
Command "C:\Users\Xande-Kho\AppData\Local\Programs\Python\Python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\XANDE-~1\\AppData\\Local\\Temp\\pip-install-r876wdx3\\PyNaCl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\XANDE-~1\AppData\Local\Temp\pip-record-lrau8ycm\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\XANDE-~1\AppData\Local\Temp\pip-install-r876wdx3\PyNaCl\

[CRITICAL] launcher: You may need to run as admin to install dependencies.

[INFO] launcher: All done.

**Comment by AutumnClove** [comment]
Uninstall 3.7 and install 3.5.4

**Comment by XanderKho** [comment]
@AutumnClove Ty Sir
