### ISSUE TITLE
Playing In x Servers

### ISSUE THREAD

**Issue by KyleFardy-zz** [Just-Some-Bots/MusicBot#1672]
Please tick all applicable boxes.

- [X ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X ] The latest `master` version (1.9.7)
- [X ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [X ] Question

----

### Description of issue

looking to make it say playing {bot name] in x servers

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by MattBSG** [comment]
This is not possible without modifying the bot (we do not provide help with modifying or give support to users who modify their bots). You can find the relevant section of code here: https://github.com/Just-Some-Bots/MusicBot/blob/master/musicbot/bot.py#L759

For simpler questions like this, please join our discord server found [here](https://discord.gg/bots) instead.

**Comment by KyleFardy-zz** [comment]
thanks, managed to do it!
