### ISSUE TITLE
[Minor Bug] missing word "skip" in config.ini | ln126

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1673]
Please tick all applicable boxes.

- [ x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ x ] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ x ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
a word is missing.

example_options.ini | ln126
`# Allows the person who queued a song to their OWN songs instantly, similar to the`
`>`
`# Allows the person who queued a song to skip their OWN songs instantly, similar to the`

**Comment by AleanaA** [comment]
Already fixed, please see #1618

**Comment by ghost** [comment]
I see, couldn't find an issue so I added it.
sorry for not checking the pull requests, this can be closed then.

**Comment by ImthePeach** [comment]
Note, you can also close your own issues you open
