### ISSUE TITLE
Bot will not launch or update correctly.

### ISSUE THREAD

**Issue by Grendald** [Just-Some-Bots/MusicBot#1674]
The update.bat keeps coming up with this 'Command "python setup.py egg_info" failed with error code 1 in C:\Users\grend\AppData\Local\Temp\pip-build-luvbgq14\cffi'

**Comment by AutumnClove** [comment]
Please provide a full traceback

**Comment by Grendald** [comment]
Alright here you go.  
![image](https://user-images.githubusercontent.com/29141130/43374906-a265b7aa-9377-11e8-9b34-dcd311da8a37.png)

**Comment by AutumnClove** [comment]
Please install python to path
