### ISSUE TITLE
BUG IN SETAVATAR

### ISSUE THREAD

**Issue by OzzyHelix** [Just-Some-Bots/MusicBot#1678]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.7)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
a bug in the setavatar command
there was someone who's case was not reproducible
in particular module 'aiohttp' has no attribute 'Timeout'
in the setavatar command changing
this
```
        try:
            with aiohttp.Timeout(10):
                async with self.aiosession.get(thing) as res:
                    await self.user.edit(avatar=await res.read())
```
to this
```
        try:
            with async_timeout.timeout(10):
                async with self.aiosession.get(thing) as res:
                    await self.user.edit(avatar=await res.read())
```
will fix the problem
however it might not be a long term solution however it does make the link uploading work at the very least 
### Steps to reproduce

1.  attempting to change the avatar from a link
note: uploading images as an avatar doesn't work because of this bug
----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2248117/musicbot.log)

**Comment by AleanaA** [comment]
I didn't test your solution, however 5 seconds in the aiohttp documentation, I found [this](http://docs.aiohttp.org/en/latest/client_quickstart.html#timeouts), and made 


        try:  
            timeout = aiohttp.ClientTimeout(total=10)  
            async with aiohttp.ClientSession(timeout=timeout):  
                async with self.aiosession.get(thing) as res:  
                    await self.user.edit(avatar=await res.read())
  
Although this works, it led to  

168118999337402368/Aleana#2643: !setavatar
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
File "/mnt/secondary/aleana/test/MusicBot/musicbot/bot.py", line 2726, in on_message
    response = await handler(**handler_kwargs)
  File "/mnt/secondary/aleana/test/MusicBot/musicbot/bot.py", line 137, in wrapper
    return await func(self, *args, **kwargs)
  File "/mnt/secondary/aleana/test/MusicBot/musicbot/bot.py", line 2445, in cmd_setavatar
    thing = message.attachments[0]['url']
TypeError: 'Attachment' object is not subscriptable
  
Once I work out the kinks with set avatar here, I'll make a PR to solve this issue.

edit: formatting is hard pepehands

**Comment by AutumnClove** [comment]
See the above PR @OzoneHelix

**Comment by OzzyHelix** [comment]
@AutumnClove thank you

**Comment by OzzyHelix** [comment]
what I discover was a partial fix it fixed links but not uploading an image

**Comment by AleanaA** [comment]
I tested your solution and got this result in VSC before even starting the bot

`Undefined variable 'async_timeout'`

**Comment by OzzyHelix** [comment]
its odd because when I tried your solution it was looking in __init__.py for it which makes no sense

**Comment by OzzyHelix** [comment]
darn github's formatting

**Comment by AleanaA** [comment]
Error given when trying my solution?

**Comment by OzzyHelix** [comment]
Unable to change avatar: module 'aiohttp' has no attribute 'ClientTimeout'

**Comment by OzzyHelix** [comment]
its really weird

**Comment by OzzyHelix** [comment]
I should probably say I'm using Pycham and not VSC

**Comment by AleanaA** [comment]
If you update your dependencies for review, you'll most likely solve that error. The current requirements.txt for d.py rewrite requires `aiohttp>=3.3.0,<3.4.0` which has `ClientTimeout`

**Comment by OzzyHelix** [comment]
so I should add aiohttp to requirements.txt

**Comment by AleanaA** [comment]
No, d.py rewrite already requires it, and as such, doesn't need to be added to the requirements file.

**Comment by OzzyHelix** [comment]
No matching distribution found for aiohttp<3.4.0,>=3.3.0 (from -r requirements.txt) 
this happens when trying to update

**Comment by AleanaA** [comment]
This is a current issue that will eventually be fixed. I've found that using Python 3.6 solves this issue, however it should be noted that 3.6 can cause issues on Windows.

**Comment by OzzyHelix** [comment]
its odd because I'm trying to update on python 3.5 but I have python3.6 and python3.5 installed on my windows machine

**Comment by OzzyHelix** [comment]
wait correction I have python 3.5.2 installed

**Comment by OzzyHelix** [comment]
ok after installing python 3.6.6 your solution works completely my solution half worked so this is much better

**Comment by OzzyHelix** [comment]
I removed python 3.5.2 and now using python 3.6.6 the setavatar command works completely

**Comment by OzzyHelix** [comment]
travis also seemed to have failed when trying to use python3.5

**Comment by AleanaA** [comment]
That's a known issue.

**Comment by OzzyHelix** [comment]
well lets hope it will be resolved in the future
