### ISSUE TITLE
[Suggestion] !playmp3 <song title>.mp3 and autoexec config

### ISSUE THREAD

**Issue by grizzogor** [Just-Some-Bots/MusicBot#168]
I was thinking of suggesting !playmp3 for the owner to play mp3 files in a local folder. The folder would be named 'mp3songs' or 'localsongs'. I was also thinking of a autoexec feature (in the config) to automatically execute commands on voice channel connect or when the owner starts up the bot.

**Comment by deansheather** [comment]
Local playlists coming soon :tm:.

As with the other thing, if you mean sending messages into chat (to other bots or something), :+1:.

**Comment by Pyroglyph** [comment]
Other than MP3, what other formats are likely to be supported for the local player? I have some .XM and .MOD chiptune tracks that would be cool to play but they aren't widely supported.

**Comment by benoxoft** [comment]
Not the same but there is a workaround for this.  You can upload your songs somewhere (dropbox for example) and give the link to the bot.  I tried to give it a local file url like !play file://C:/test.mp3 but it didn't work unfortunately.

**Comment by Pyroglyph** [comment]
Ah okay, that's a good thing to know, I think you can set up a local web server and do it from there (so it would be http://localhost/test.mp3 or something)

**Comment by imayhaveborkedit** [comment]
The autoexec thing is probably not going to happen.

**Comment by grizzogor** [comment]
@imayhaveborkedit, maybe you can add a option to the autoplaylist to automatically shuffle the playlist?
