### ISSUE TITLE
Modifying commands

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1686]
Please tick all applicable boxes.

- [ ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue

Hello, I would like to know where to change the name of the commands?

**Comment by AutumnClove** [comment]
`musicbot/bot.py`
