### ISSUE TITLE
Doesnt let me run it cause it says it wasnt downloaded from here when it was.

### ISSUE THREAD

**Issue by PrepareForMayhem** [Just-Some-Bots/MusicBot#1688]
Please tick all applicable boxes.

- [Yes ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ Yes] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ]Yes I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ Yes] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
when I run the run.bat it says it wasn't downloaded from git but it was.

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
there isn't one,

**Comment by AleanaA** [comment]
This is intended. If you downloaded a zip file, you have installed the bot incorrectly. There's even a note about this at the bottom of the windows guide.

**Comment by PrepareForMayhem** [comment]
@AleanaA Umm I did download as a zip

I even downloaded it again and it didn't work when I set it up again
and I also followed this along with the steps on the git https://www.youtube.com/watch?v=aquRQk2-0YU

**Comment by AleanaA** [comment]
As said, if you downloaded a zip file, you have installed the bot incorrectly.

**Comment by PrepareForMayhem** [comment]
@AleanaA how do I do it correctly then

**Comment by AleanaA** [comment]
Read the windows guide, and clone it using git.

**Comment by PrepareForMayhem** [comment]
@AleanaA ok

**Comment by PrepareForMayhem** [comment]
@AleanaA so I run it in the desktop app cause that's the only other option in clone other than zip

**Comment by AleanaA** [comment]
No. Please read the windows guide for information regarding cloning using git. You don't download anything from github.

**Comment by PrepareForMayhem** [comment]
@AleanaA Tysm it worked help me use it if u want lol. http://discord.me/ChillMayhem

**Comment by PrepareForMayhem** [comment]
@AleanaA ty if u don't mind help me test out the bot and such in the link above
