### ISSUE TITLE
Feature request Own music per server

### ISSUE THREAD

**Issue by Taelyn** [Just-Some-Bots/MusicBot#1692]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

### Description of issue
a way that every server the bot is on can listen to its own music insteed all servers the same music

**Comment by AleanaA** [comment]
Uh?
All servers *can* listen to their own music with `!play`.
No server would be listening to the same music as another server unless the two queued a song at the same time.

**Comment by ImthePeach** [comment]
If this is in regards to each server having it's own playlist then that is already a work in progress.

**Comment by Taelyn** [comment]
If server A does !play test. and the song test starts to play. on Server B also the song test plays. They cant listen to there own music at the same time.

But thanks seems its a WIP what i mean :)

**Comment by AleanaA** [comment]
Uh, no, that's not how it works, at all.

What peach was talking about in terms of 'playlist' is server specific
autoplaylist.

Servers can have their own songs playing.
Numerous people use the bot on multiple servers, myself included, and this
isn't an issue.

I'd recommend sending a log file, and giving information on your setup, as,
going by your example, Server B's music should be independent from Server A.

**Comment by Taelyn** [comment]
here a link to my log files
https://1drv.ms/u/s!ArVTDzrCWVTXiNZUbuKFI0Os4XmQqg

atm i have a test server and my normal server. when i que music on my normal discord server
my test discord server gets the same music. Bot says playing music on 2 server. The bot it self
is running on my dedicated server. If i pause it on one server its paused on the other too

**Comment by AleanaA** [comment]
Going by your log file, the bot is only in one server.

**Comment by Taelyn** [comment]
Here a screenshot : https://1drv.ms/u/s!ArVTDzrCWVTXiNZWRBfvHv6m-pm_QA

Defently on 2 servers :D

If u need anything els let me know :)

**Comment by AleanaA** [comment]
Then it would be preferable to send a more up to date log file, as the one
sent only shows the bot recognizing one server.

**Comment by Taelyn** [comment]
Those 2 i send are the only 2 logs files in the log folder of the bot. where can i find others?

**Comment by AleanaA** [comment]
You only sent one log file.

**Comment by Taelyn** [comment]
sorry was pretty sure both where in it.

https://1drv.ms/u/s!ArVTDzrCWVTXiNZYvyTzHWBr9wcHGw
here is the other one

**Comment by AleanaA** [comment]
I would personally recommend fully restarting the bot to see if that solves
it, as, at least at first glance at 2:45 in the morning, I don't see
anything particularly wrong in that log.

**Comment by Taelyn** [comment]
oh thanks. Now both my servers can play there own music
