### ISSUE TITLE
Error while updating MusicBot for Discord

### ISSUE THREAD

**Issue by markvarga21** [Just-Some-Bots/MusicBot#1693]
Im getting always this message while im trying to update my musicbot in musicbot folder. I reinstalled Python to ah=nother directory etcetc. But nothing worked for me. I get this message always in command prompt:

Command "C:\Python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Mark\\AppData\\Local\\Temp\\pip-install-m0hgr0_r\\PyNaCl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Mark\AppData\Local\Temp\pip-record-j3g_84wa\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Mark\AppData\Local\Temp\pip-install-m0hgr0_r\PyNaCl\
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "update.py", line 51, in main
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-U', '-r', 'requirements.txt'], shell=True)
  File "C:\Python\lib\subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'requirements.txt']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update.py", line 65, in <module>
    main()
  File "update.py", line 53, in main
    raise OSError("Could not update dependencies. You will need to run '{0} -m pip install -U -r requirements.txt' yourself.".format(sys.executable))
OSError: Could not update dependencies. You will need to run 'C:\Python\python.exe -m pip install -U -r requirements.txt' yourself.

**Comment by AutumnClove** [comment]
Please uninstall this version of python and install 3.5.4 and make sure to click `add to path`

**Comment by markvarga21** [comment]
Thanks for the help it worked for me :))
