### ISSUE TITLE
Cant' convert NoneType or what

### ISSUE THREAD

**Issue by Biznizmuff** [Just-Some-Bots/MusicBot#1695]
Please tick all applicable boxes.

- I am using Python 3.5.6 [GCC 4.8.4] on linux
- I have followed the https://just-some-bots.github.io/MusicBot/installing/ubuntu/ to install the bot for my system
- I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- The latest `master` version (1.9.7)

What type of issue are you creating?

- Bug

----

### Description of issue

Hi. I have tried install the bot on my Ubuntu 14.04 and it's working, but can't play the music
Upd.: I have already this version on Windows Server and have no problems

### Steps to reproduce

1. Installed the build tools
2. Added external repositories
3. Installed system dependencies
4. Cloned the MusicBot to my home directory
5. Installed python dependencies
6. Updated with "sudo sh update.sh"
7. Rebooted the VDS
8. Opened with "python3.5 run.py" (I can't do "sh run.sh" or "./run.py", I am getting an error that 1 have no 3.5+ python installed, but when i type "python3.5" - I can see, that i have version 3.5.6. On my VDS now installed 2.7+, 3.4+, and 3.5.6)
9. Bot connects to my channel and after the caching music - crashs

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2291467/musicbot.log)

**Comment by Biznizmuff** [comment]
Issue was fixed with installing ffmpeg
Good guide for it - https://www.faqforge.com/linux/how-to-install-ffmpeg-on-ubuntu-14-04/
Also turn off "UseExperimentalEqualization" in config

**Comment by jaydenkieran** [comment]
Glad to hear you got it sorted.
