### ISSUE TITLE
Could not find a version that satisfies the requirement aiohttp [Updating Dependencies]

### ISSUE THREAD

**Issue by HaydenJM** [Just-Some-Bots/MusicBot#1698]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (1.9.8)

What type of issue are you creating?

- [X] Bug

----

### Description of issue

I tried running the bot normally, typed 'y' and 'enter' to agree with cleaning the directory using the github repository, and then I got the error telling me that my version of discord.py was out of date.

I attempted to update the dependencies which led me to this error:

Could not find a version that satisfies the requirement aiohttp<3.4.0,>=3.3.0 (from discord.py[voice]->-r requirements.txt (line 2)) (from versions: 0.1, 0.2, 0.3, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.18.4, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.21.0, 0.21.1, 0.21.2, 0.21.4, 0.21.5, 0.21.6, 0.22.0a0, 0.22.0b0, 0.22.0b1, 0.22.0b2, 0.22.0b3, 0.22.0b4, 0.22.0b5, 0.22.0b6, 0.22.0, 0.22.1, 0.22.2, 0.22.3, 0.22.4, 0.22.5, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.6.post1, 2.0.7, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0a1, 2.3.0a2, 2.3.0a4, 2.3.0, 2.3.1a1, 2.3.1, 2.3.2b2, 2.3.2b3, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 3.0.0b0)
No matching distribution found for aiohttp<3.4.0,>=3.3.0 (from discord.py[voice]->-r requirements.txt (line 2))

The reason why I was unable to get the full error is because my PuTTY terminal went inactive and closed out whenever I acknowledged it. Also, there is no log file since this was my first time attempting to run the bot on this specific machine.

I have the bot's source files on a different machine which I've never needed to reset the files using the repo, and it works perfectly fine. It's a Windows 10 PC, the machine that I'm having my specific issue on is an Ubuntu 16.04 server with Python 3.5.2

### Steps to reproduce

As described above..

1. sudo ./run.sh (Returned "Your version of discord.py is not up-to-date..")
2. sudo python3 update.py (Returned the second error that I mentioned above)

----

As mentioned above..

There is no log file since this was my first time attempting to run the bot on this specific machine, and it was never able to get past the initial "discord.py is not up-to-date" error.

**Comment by AleanaA** [comment]
Update python to at least 3.5.4

**Comment by HaydenJM** [comment]
It's saying that I have the most recent version of python3 available, but I tried it again after installing Python 3.6 and got the same error(s). This time I copied the entire error - I edited into my original post.

**Comment by AleanaA** [comment]
after installing python 3.6, `python3 --version` outputs that it's using 3.6, correct?

**Comment by HaydenJM** [comment]
python3 --version returns the current version of python3, which is still 3.5.2
However, python3.6 --version returns Python 3.6.6

I don't think that python3 --version is supposed to return the version for python3.6 unless you're on to something..

**Comment by HaydenJM** [comment]
My error is "Could not find a version that satisfies the requirement aiohttp<3.4.0,>=3.3.0 (from discord.py[voice]->-r requirements.txt"

Are you certain that the issue is Python? I use Python version 3.5.2 on my Windows PC, and the bot runs just fine although I have not updated the dependencies, or reset the directory so that I don't start getting the same error I'm getting on the Ubuntu machine..

**Comment by AleanaA** [comment]
The version of aiohttp required by discord.py rewrite, does not support python 3.5.2

**Comment by HaydenJM** [comment]
In my .bashrc file, I created an alias for python and python3 that will use python3.6 instead. So now whenever I type python3 --version it returns Python 3.6.6

**Comment by HaydenJM** [comment]
When attempting to update dependencies I'm now getting "No module named pip," and whenever I attempted to install pip for Python 3.6 it says that there's no such package. I'm having issues now trying to install Python 3.5.4 because it's adamant that 3.5.2 is the most recent version available.

**Comment by AleanaA** [comment]
`curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6` this command should install pip to python 3.6

**Comment by HaydenJM** [comment]
I was successful with updating dependencies, however now whenever I run sudo ./run.sh I get:

It seems like it's still trying to use Python 3.5

"[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client_reqrep.py", line 25, in <module>
    import cchardet as chardet
ImportError: No module named 'cchardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 365, in main
    from musicbot import MusicBot
  File "/root/MusicBot/musicbot/__init__.py", line 7, in <module>
    from .utils import _get_variable
  File "/root/MusicBot/musicbot/utils.py", line 3, in <module>
    import aiohttp
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/__init__.py", line 11, in <module>
    from .connector import *  # noqa
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 17, in <module>
    from .client import ClientRequest
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 18, in <module>
    from .client_reqrep import ClientRequest, ClientResponse
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client_reqrep.py", line 27, in <module>
    import chardet
ImportError: No module named 'chardet'
[INFO] launcher: Attempting to install dependencies...
Collecting pynacl==1.2.1 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/c9/9c/c8d4ae0f590faded4af55381131ad4db8729214eba6537c520622ba3548a/PyNaCl-1.2.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting discord.py[voice] from git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice] (from -r requirements.txt (line 2))
  Cloning https://github.com/Rapptz/discord.py (to revision rewrite) to /tmp/pip-install-4kvito8v/discord.py
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-4kvito8v/discord.py/

[CRITICAL] launcher: You may need to use sudo to install dependencies.

[INFO] launcher: All done."

**Comment by HaydenJM** [comment]
Should I uninstall Python3?

**Comment by AleanaA** [comment]
You don't have to uninstall it, launching the bot by running `python3.6 run.py` should work fine.

**Comment by HaydenJM** [comment]
My bot is up and functioning as intended. I truly appreciate your help, and thank you for your patience with me. One last question then I'll close the thread: In the future, how should I go about updating dependencies? Would I use `python3.6 update.py` ?

**Comment by AleanaA** [comment]
`python3.6 -m pip install -U -r requirements.txt` is the preferred method. The update script is known to have issues.

**Comment by HaydenJM** [comment]
That worked for me, thanks again! Have a good day rest of the day! @AleanaA
