### ISSUE TITLE
Full logging option

### ISSUE THREAD

**Issue by Arzte** [Just-Some-Bots/MusicBot#17]
Can we get a option to enable the bot to post the full log output? There are weird bugs (like some songs not playing) that would be easier to fix and send upstream if the bot logging would output everything when set. (possibly as a config option.)

**Comment by jayktaylor** [comment]
https://github.com/SexualRhinoceros/MusicBot/commit/1623506d2089a2d8d5a533299a6225d294c2f7a1 and later commits to `review` have implemented logging. It'll be in the next release version.
