### ISSUE TITLE
MusicBot start-up on Linux

### ISSUE THREAD

**Issue by andrewsemm** [Just-Some-Bots/MusicBot#170]
Whenever executing
`python3.5 run.py`

I get this in return
`Command "/usr/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vod6swyy/PyNaCl/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-o7fnj2l1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-vod6swyy/PyNaCl/`

Screenshot
http://i.imgur.com/el6z5aJ.png

**Comment by Echoskope** [comment]
How did you fix this?

**Comment by andrewsemm** [comment]
@Echoskope wiki page got updated, only thing additional is
`sudo apt-get install python3.5-dev -y`
