### ISSUE TITLE
Error when attempting to play a Spotify playlist using the playlist URI

### ISSUE THREAD

**Issue by HaydenJM** [Just-Some-Bots/MusicBot#1701]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)

What type of issue are you creating?

- [x] Bug

----

### Description of issue

Error whenever attempting to queue a Spotify playlist using the playlist URI.

```
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/root/MusicBot/musicbot/bot.py", line 2705, in on_message
    response = await handler(**handler_kwargs)
  File "/root/MusicBot/musicbot/bot.py", line 1313, in cmd_play
    procmesg = await self.safe_send_message(channel, self.str.get('cmd-play-spotify-playlist-process', 'Processing playlist `{0}` (`{1}`)').format(res['name']), song_url)
IndexError: tuple index out of range
```

### Steps to reproduce

1. Attempt to play a Spotify playlist

----

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2312761/musicbot.log)

**Comment by karmafreediet** [comment]
you can fix this by changing line 1313 in bot.py from

> `procmesg = await self.safe_send_message(channel, self.str.get('cmd-play-spotify-playlist-process', 'Processing playlist `{0}` (`{1}`)').format(res['name'], song_url))`

to

> `procmesg = await self.safe_send_message(channel, self.str.get('cmd-play-spotify-playlist-process', 'Processing playlist `{0}` (`{1}`)').format(res['name']), song_url)`

there's a stray bracket at the end there.
you're welcome :)

**Comment by RealFriesi** [comment]
same here, also with the revised line 1313

**Comment by jayktaylor** [comment]
Fixed in https://github.com/Just-Some-Bots/MusicBot/commit/8fad33263e7ba4f981d53a347efb292e13c201f3.
