### ISSUE TITLE
Commands do not function with Discord.py's rewrite

### ISSUE THREAD

**Issue by slever903** [Just-Some-Bots/MusicBot#1704]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

The discord.py rewrite [changed the type of ID attributes from string to int](https://github.com/Rapptz/discord.py/commit/45c729b167509deb5e389a7812d0ae8f4cbc4e72#diff-4bf211894f00dbdc0e9644aef6cbffda) (I only looked at the user class and the role class of discord.py). This causes `for_user` in permissions.py to break. 

Specifically, the following stack trace is generated:

```
[43.5788252353668213] 2018-08-25 15:57:31,300 - ERROR - musicbot.bot | In bot.py::MainThread(140475975407424), line 901 in on_error: Exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/client.py", line 220, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/MusicBot/musicbot/bot.py", line 2600, in on_message
    user_permissions = self.permissions.for_user(message.author)
  File "/home/ubuntu/MusicBot/musicbot/permissions.py", line 93, in for_user
    if role.id in group.granted_to_roles:
TypeError: 'in <string>' requires string as left operand, not int
```
The following code is where the issue comes up:

https://github.com/Just-Some-Bots/MusicBot/blob/1adb604e2e775e383b35b00271e7b8850a61054f/musicbot/permissions.py#L76-L96

A quick and dirty way would be to just cast `user.id` and `role.id` to string (aka what I did to get my instance working again), but I think recasting `group.user_list` and `group.granted_to_roles` as int arrays could work too. I haven't really tested the performance impact of either case. 

I also didn't check to see if any other classes have the same issue. 

### Steps to reproduce

1. Start the bot
2. Have any user try to use any command

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2320867/musicbot.log)

**Comment by jayktaylor** [comment]
Weird, we've already fixed this issue before with commit https://github.com/Just-Some-Bots/MusicBot/commit/4f09e6bb0444bbadcba1367758448c9c60c5f02f. I've tried reproducing the issue again today and no luck.

**Comment by slever903** [comment]
I realized that I emptied out a GrantToRoles section of one of my permission groups because it wasn't needed anymore. It looks like the the null entry wasn't getting converted to int then causing the failure.
