### ISSUE TITLE
Streaming works, but buffers relentlessly

### ISSUE THREAD

**Issue by HaydenJM** [Just-Some-Bots/MusicBot#1709]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)

What type of issue are you creating?

- [x] Bug

----

### Description of issue

Stream command produces no errors, but when streaming live YouTube videos it buffers relentlessly.

### Steps to reproduce

1. Use the stream command to play a live audio feed from YouTube.

----

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2326179/musicbot.log)

**Comment by AutumnClove** [comment]
There's nothing to be done about this really unfortunately, as it's not downloading, it has to fetch the audio, decode it, equalize it, and then play it through discord, to top it off ffmpeg(the software the bot uses to play the music) is notoriously terrible at streaming, faster internet on your end might help, however that's really all that can be done.

**Comment by HaydenJM** [comment]
The Spotify URI that I used was `spotify:user:alltrapnation:playlist:0NCspsyf0OS4BsPgGhkQXM`

Using the same URI with "Dyno Bot" seems to work just fine.
