### ISSUE TITLE
[ERROR:bot] Exception in on_message

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1711]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [x] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue

[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Discord Bots\♫ Maestro ♫\musicbot\bot.py", line 2698, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Users\User\Desktop\Discord Bots\♫ Maestro ♫\musicbot\bot.py", line 1742, in cmd_search
    await self.cmd_play(message, player, channel, author, permissions, [], e['webpage_url'])
AttributeError: 'MusicBot' object has no attribute 'cmd_play'

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2328187/musicbot.log)

**Comment by AutumnClove** [comment]
Hi, are you still experiencing this issue?

**Comment by Csriso** [comment]
Same problem here when i play a song.

**Comment by AutumnClove** [comment]
Have both of you ran the update file as admin to try to fix this?

**Comment by Csriso** [comment]
Tried it yesterday and nothing changed. The error only happens when i try to skip the song with !skip f. Sometimes i play a song and it dosent play, and it play automatically when i restart the bot.

**Comment by AutumnClove** [comment]
Hello, looking at this again, it might appear you're running a modified version of the bot or have made changes. If you're still having issues feel free to come to the discord server and talk about this in real time. 
https://www.discord.gg/bots
