### ISSUE TITLE
premissions

### ISSUE THREAD

**Issue by hrtrd** [Just-Some-Bots/MusicBot#1715]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue

Hello, i think my bot cant read premission.ini

in options.ini    - OwnerID set my id
in premission file (use standart groups) i want give all commands to some users(Not role):

[MusicMaster]
UserList = MyID Friend1ID Friend2ID
MaxSongLength = 0
MaxSongs = 0
MaxPlaylistLength = 0
MaxSearchItems = 20
AllowPlaylists = yes
InstaSkip = yes
Remove = yes
SkipWhenAbsent = no
BypassKaraokeMode = yes
Extractors = 

restart bot, and if Friend1ID try  "skip"   he got msg "need one more user for skip song"

Platform: Windows Server, Ubuntu 16.04

**Comment by AutumnClove** [comment]
Change logs are cool.
Use `skip f`
