### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by stampysmith** [Just-Some-Bots/MusicBot#1717]
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[CRITICAL] launcher: Bot wasn't installed using Git. Reinstall using http://bit.ly/musicbotdocs.
Press enter to continue . . .

**Comment by AutumnClove** [comment]
Click the link, follow the guide, reading c o m p r e h e n s i o n

**Comment by stampysmith** [comment]
i did

**Comment by AutumnClove** [comment]
Uninstall the zip one

**Comment by stampysmith** [comment]
k
