### ISSUE TITLE
Problem with my bot

### ISSUE THREAD

**Issue by Zerb3rus** [Just-Some-Bots/MusicBot#1718]
![bot fehler 1](https://user-images.githubusercontent.com/42847226/45201707-a477cd80-b276-11e8-9422-1ab9fbfb4fbb.png)
![bot fehler 2](https://user-images.githubusercontent.com/42847226/45201708-a477cd80-b276-11e8-9b10-ad28719787eb.png)
![bot fehler 3](https://user-images.githubusercontent.com/42847226/45201709-a477cd80-b276-11e8-99cb-38aff0c2db40.png)

Please tick all applicable boxes.

- [x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x ] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x ] Question

----

### Description of issue

How can I fix the problem as seen on the pictures?

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2359790/musicbot.log)

**Comment by AutumnClove** [comment]
Hi there could you try to run update.bat as admin (right click the update.bat file, select "run as admin")

**Comment by Yeehawlerz101** [comment]
I had this Issue also on my Amazon EC2 instance. +1

**Comment by AutumnClove** [comment]
Please assure you've updated your bot to the latest version. This issue should now be fixed as I'm pretty positive this was with ytdl
