### ISSUE TITLE
Error when playing music - Unable to extract Initial JS player signature function name

### ISSUE THREAD

**Issue by felix920506** [Just-Some-Bots/MusicBot#1722]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
Cannot play music
Already ran update.bat but still the same

### Steps to reproduce

1. start up the bot
2. use the play command to play a song

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2362801/musicbot.log)

**Comment by AleanaA** [comment]
Duplicate of #1721

**Comment by felix920506** [comment]
Ran Update as Administrator
Issue Solved Thx
