### ISSUE TITLE
can you no longer use "send_message" ? 

### ISSUE THREAD

**Issue by Cuteminded** [Just-Some-Bots/MusicBot#1725]
Please tick all applicable boxes.

- [ x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x ] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x ] Question

----

### Description of issue

can you no longer use "send_message" ? 

 

### Steps to reproduce

1. 

----

### Log file

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2372134/musicbot.log)

Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AleanaA** [comment]
This isn't the place for help regarding d.py. Please see the [documentation pages](https://discordpy.readthedocs.io/en/rewrite/) for information on how to use it.
