### ISSUE TITLE
[Feature Request] Keep (only) playlist songs cach.

### ISSUE THREAD

**Issue by jacobmix** [Just-Some-Bots/MusicBot#173]
An option to only keep songs from the playlist would be nice.
Right now you can keep every song ever played.
Or delete any song not in the queue. (Guess for if you have songs in the queue more than once?)
Keeping playlist songs would be a welcome feature. (Don't care much for random songs people queue.)

**Comment by imayhaveborkedit** [comment]
When I write local playlists, this will be one of the special playlists, like the autoplaylist.
