### ISSUE TITLE
My Discord Music Bot Doesnt Want To Start

### ISSUE THREAD

**Issue by callumdunn676** [Just-Some-Bots/MusicBot#1731]
Please tick all applicable boxes.

- [ ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 368, in main
    m = MusicBot()
  File "C:\Users\callu\Documents\Coding Links\MusicBot\musicbot\bot.py", line 71, in __init__
    self.config = Config(config_file)
  File "C:\Users\callu\Documents\Coding Links\MusicBot\musicbot\config.py", line 81, in __init__
    self.run_checks()
  File "C:\Users\callu\Documents\Coding Links\MusicBot\musicbot\config.py", line 186, in run_checks
    self.autojoin_channels = set(int(item.replace(',', ' ').strip()) for item in self.autojoin_channels)
  File "C:\Users\callu\Documents\Coding Links\MusicBot\musicbot\config.py", line 186, in <genexpr>
    self.autojoin_channels = set(int(item.replace(',', ' ').strip()) for item in self.autojoin_channels)
ValueError: invalid literal for int() with base 10: 'no'

[INFO] launcher: All done.

C:\Users\callu\Documents\Coding Links\MusicBot>

**Comment by AleanaA** [comment]
Remove `no` from the area after autojoinchannels in your options file and leave it blank.

**Comment by callumdunn676** [comment]
> Remove `no` from the area after autojoinchannels in your options file and leave it blank.
Do i remove no from WhiteListCheck ?

**Comment by AleanaA** [comment]
No, only the autojoinchannels option caused your issue.

**Comment by callumdunn676** [comment]
> No, only the autojoinchannels option caused your issue.

yeah i changed that and it fixed my problem thank you so much !
