### ISSUE TITLE
How can i add a radio station for my bot to play ?

### ISSUE THREAD

**Issue by callumdunn676** [Just-Some-Bots/MusicBot#1732]
- [Yes ] question

i want to know how to make my bot be able to  play radio stations because my bot is called "Uncle Barry's Radio" so its only fitting if i can make it play radio stations preferably Australian Radio Stations

**Comment by AutumnClove** [comment]
You're free to try and implement this yourself using api's however we won't assist in this as it's modification.

**Comment by AleanaA** [comment]
web streams and the stream command also exist
