### ISSUE TITLE
Audio will not play

### ISSUE THREAD

**Issue by Nihlus** [Just-Some-Bots/MusicBot#1734]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
In similar vein to #1384, the bot does not play any audio, but no errors are present in the log. I've tried playing both YouTube and Spotify links with no results.

I'm using the latest version pulled from Github.

### Steps to reproduce

1. Install according to the Ubuntu installer.
2. Configure the bot with a Discord token, and a Spotify token
3. Run the bot.
4. Play any link.

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2386683/musicbot.log)

**Comment by AleanaA** [comment]
did you try disconnecting and reconnecting to the voice channel the bot is in

**Comment by Nihlus** [comment]
Yes. When testing it today, the issue went away when I connected to the bot's default channel after it had joined. However, it still occurs if the bot joins after I've joined the channel. The queue command also fails when the bot is in this state, producing the following error:

```
135347310845624320/Jax#7487: !queue
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/home/discord-music-bot/MusicBot/musicbot/bot.py", line 2705, in on_message
    response = await handler(**handler_kwargs)
  File "/home/discord-music-bot/MusicBot/musicbot/bot.py", line 2172, in cmd_queue
    song_progress = ftimedelta(timedelta(seconds=player.progress))
TypeError: unsupported type for timedelta seconds component: NoneType
```

**Comment by AleanaA** [comment]
This is a discord problem, and not an issue with the bot.

**Comment by Nihlus** [comment]
Actually, looking at it, it seems that the bot joining after me does work as long as it's the bot's default autojoin channel. Strange.

**Comment by MattBSG** [comment]
If you encounter anymore issues, please feel free to reopen
