### ISSUE TITLE
Sequenced User Play Order Feature

### ISSUE THREAD

**Issue by KershSoftware** [Just-Some-Bots/MusicBot#1735]
What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

### Description of issue

An options config flag to enable a mode that sequentially plays queued songs by all users, where the sequence of songs consists of taking turns between all users who have queued music.

e.g. User A queues 3 songs, User B queues 1 song, User C queues 2 songs.
Song order:
User A: Song 1
User B: Song 1
User C: Song 1
User A: Song 2
User C: Song 2
User A: Song 3

**Comment by BabyBoySnow** [comment]
#2361
