### ISSUE TITLE
Audio np counter bug

### ISSUE THREAD

**Issue by BanditJr28** [Just-Some-Bots/MusicBot#1738]
Please tick all applicable boxes.

- [✔️] I am using Python 3.5 or higher (run `python --version` on the command line)
- [✔️] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [✔️] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [✔️] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [✔️] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Pausing the music, then resuming it resets the np counter.

### Steps to reproduce

1. Play a song with the play command.
2. Run the np command and note how many seconds the music has played for.
3. Pause the music.
4. Resume the music.
5. Run the np command again and you'll see the counter reset.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2390904/musicbot.log)

**Comment by TAG-Epic** [comment]
Close?
