### ISSUE TITLE
Docker container (1.9.8) has an old youtube-dl

### ISSUE THREAD

**Issue by Olical** [Just-Some-Bots/MusicBot#1742]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

The latest build of the Docker container has an out of date `youtube-dl`, this means the bot can't interact with YouTube.

### Steps to reproduce

1. Start the bot through the Docker container (I'm using kube `kubectl run musicbot --image=justsomebots/musicbot:1.9.8`)
2. Attempt to `!play` a song
3. Observe a `youtube-dl` regex error in the logs

----

### Log file

```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1210, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1121, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1182, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name',))
```

### Possible solution

Rebuild the Docker container from further up the file, maybe by editing a comment before the `youtube-dl` package is installed. This will fetch the latest version.

**Comment by AutumnClove** [comment]
Just run the update file lol

**Comment by Olical** [comment]
I don't appreciate the lol and that's not how Docker containers work. You must rebuild it from an earlier step because the deb (I presume) package needs updating. The old version is cashed in a layer. I could just build my own fixed container but I thought I'd try to help you out.

**Comment by TheerapakG** [comment]
Our docker images are built automatically on each commit via Travis CI. never by human.

The easiest solution for this problem would be, to set the entry point for docker to run the script that would run the update script and then run the actual run script. This would add some startup time. __OR__ we just tag into repo the image before dependencies installation and let the user does the manual work (currently we tag the result image, with deps, into repo).

Anyway, a temporary fix, for now, would be to use the review image. review image should be working as it just been built a week ago. Youtube_dl was updated on Sep 17, 2018. not-so-current 1.9.8 branch/tag was built in August. The review branch currently does not have any significant difference from the master 1.9.8_1 branch/tag.

Why I said 1.9.8 is not current?
Actually 1.9.8_1 is out but https://travis-ci.org/Just-Some-Bots/MusicBot/jobs/421023989 . As you can see, Travis build doesn't complete. Docker doesn't push but it is `after_success` so it not failed. We need to fix this too.

**Comment by Olical** [comment]
Excellent, thank you! That `review` tag does indeed work. I guess I was mistaken with the original issue, it just requires a new version, not rebuilding the container in some different way. I was under the impression that the `RUN apk add...` lines would be cached until a build step changed above those lines.

**Comment by Olical** [comment]
You can close this if you want or maybe leave it open as a warning about the current version until the new one is out.
