### ISSUE TITLE
AllowAuthorSkip and InstaSkip do not work

### ISSUE THREAD

**Issue by Blir** [Just-Some-Bots/MusicBot#1745]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
AllowAuthorSkip in options.ini and InstaSkip in permissions.ini do not work as described.

### Steps to reproduce

InstaSkip
1. Configure user in role in permissions.ini with InstaSkip = yes
2. Restart bot, queue song and observe that the song does not instaskip

AllowAuthorSkip
1. Configure setting in options.ini with AllowAuthorSkip = yes
2. Restart bot, queue song and attemtp to skip with the same user
3. Observe that the song does not instaskip

Also, other users should be present in voice, otherwise the songs will skip regardless because of the skip ratio being met.

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2409123/musicbot.log)
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AleanaA** [comment]
Use `skip f` instead of `skip`

**Comment by Blir** [comment]
Ah, thanks! Did not realize that had changed.
