### ISSUE TITLE
I cant start music bot

### ISSUE THREAD

**Issue by anu7779** [Just-Some-Bots/MusicBot#1746]
Please tick all applicable boxes.

- [ ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "C:\Users\Anushka\MusicBot\musicbot\__init__.py", line 74, in <module>
    from .bot import MusicBot
  File "C:\Users\Anushka\MusicBot\musicbot\bot.py", line 17, in <module>
    import colorlog
ModuleNotFoundError: No module named 'colorlog'
[INFO] launcher: Attempting to install dependencies...
Requirement already up-to-date: pynacl==1.2.1 in c:\users\anushka\appdata\local\programs\python\python37-32\lib\site-packages (from -r requirements.txt (line 1)) (1.2.1)
Collecting discord.py[voice] from git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice] (from -r requirements.txt (line 2))
  Cloning https://github.com/Rapptz/discord.py (to revision rewrite) to c:\users\anushka\appdata\local\temp\pip-install-kdsxak8c\discord.py
Requirement already up-to-date: pip in c:\users\anushka\appdata\local\programs\python\python37-32\lib\site-packages (from -r requirements.txt (line 3)) (18.0)
Collecting youtube_dl (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/5e/a9/112c66ce67d03896ef2d8094715aa3c7abb1b6959021eb273af96a206433/youtube_dl-2018.9.26-py2.py3-none-any.whl
Collecting colorlog (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/69/eb/58ae10d3c46a0195ffdd0e3943d255d0d5029d71e5457785ecd665bcf0f3/colorlog-3.1.4-py2.py3-none-any.whl
Requirement already up-to-date: cffi in c:\users\anushka\appdata\local\programs\python\python37-32\lib\site-packages (from -r requirements.txt (line 6)) (1.11.5)
Requirement already satisfied, skipping upgrade: six in c:\users\anushka\appdata\local\programs\python\python37-32\lib\site-packages (from pynacl==1.2.1->-r requirements.txt (line 1)) (1.11.0)
Requirement already satisfied, skipping upgrade: aiohttp<3.5.0,>=3.3.0 in c:\users\anushka\appdata\local\programs\python\python37-32\lib\site-packages (from discord.py[voice]->-r requirements.txt (line 2)) (3.4.4)
Requirement already satisfied, skipping upgrade: websockets<7.0,>=6.0 in c:\users\anushka\appdata\local\programs\python\python37-32\lib\site-packages (from discord.py[voice]->-r requirements.txt (line 2)) (6.0)
Collecting colorama; sys_platform == "win32" (from colorlog->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: pycparser in c:\users\anushka\appdata\local\programs\python\python37-32\lib\site-packages (from cffi->-r requirements.txt (line 6)) (2.19)
Requirement already satisfied, skipping upgrade: chardet<4.0,>=2.0 in c:\users\anushka\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in c:\users\anushka\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (18.2.0)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in c:\users\anushka\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (1.2.6)
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.0 in c:\users\anushka\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (4.4.2)
Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in c:\users\anushka\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (3.0.0)
Requirement already satisfied, skipping upgrade: idna>=2.0 in c:\users\anushka\appdata\local\programs\python\python37-32\lib\site-packages (from yarl<2.0,>=1.0->aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (2.7)
Installing collected packages: discord.py, youtube-dl, colorama, colorlog
  Found existing installation: discord.py 1.0.0a1580+g836ae73
    Uninstalling discord.py-1.0.0a1580+g836ae73:
      Successfully uninstalled discord.py-1.0.0a1580+g836ae73
  Running setup.py install for discord.py ... done
Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\Anushka\\AppData\\Local\\Temp\\pip-uninstall-u6k80nio\\users\\anushka\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\discord\\bin\\libopus-0.x86.dll'
Consider using the `--user` option or check the permissions.

[CRITICAL] launcher: You may need to run as admin to install dependencies.

[INFO] launcher: All done.

**Comment by TheerapakG** [comment]
Try running `python -m pip install --user -U -r requirements.txt` in cmd in musicbot directory

**Comment by anu7779** [comment]
how to fix it

**Comment by TheerapakG** [comment]
What is the output when you run `python -m pip install --user -U -r requirements.txt` in cmd in musicbot directory?

**Comment by anu7779** [comment]
C:\Users\Anushka\MusicBot

**Comment by TheerapakG** [comment]
I meant the output of `python -m pip install --user -U -r requirements.txt`. Type `python -m pip install --user -U -r requirements.txt` into the command prompt that you openned in the directory.

**Comment by anu7779** [comment]
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 368, in main
    m = MusicBot()
  File "C:\Users\Anushka\MusicBot\musicbot\bot.py", line 71, in __init__
    self.config = Config(config_file)
  File "C:\Users\Anushka\MusicBot\musicbot\config.py", line 81, in __init__
    self.run_checks()
  File "C:\Users\Anushka\MusicBot\musicbot\config.py", line 186, in run_checks
    self.autojoin_channels = set(int(item.replace(',', ' ').strip()) for item in self.autojoin_channels)
  File "C:\Users\Anushka\MusicBot\musicbot\config.py", line 186, in <genexpr>
    self.autojoin_channels = set(int(item.replace(',', ' ').strip()) for item in self.autojoin_channels)
ValueError: invalid literal for int() with base 10: 'yes'

**Comment by TheerapakG** [comment]
Remove 'yes' after 'AutojoinChannels' in 'config/options.ini'
