### ISSUE TITLE
Error starting bot

### ISSUE THREAD

**Issue by anu7779** [Just-Some-Bots/MusicBot#1747]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 368, in main
    m = MusicBot()
  File "C:\Users\Anushka\MusicBot\musicbot\bot.py", line 71, in __init__
    self.config = Config(config_file)
  File "C:\Users\Anushka\MusicBot\musicbot\config.py", line 81, in __init__
    self.run_checks()
  File "C:\Users\Anushka\MusicBot\musicbot\config.py", line 186, in run_checks
    self.autojoin_channels = set(int(item.replace(',', ' ').strip()) for item in self.autojoin_channels)
  File "C:\Users\Anushka\MusicBot\musicbot\config.py", line 186, in <genexpr>
    self.autojoin_channels = set(int(item.replace(',', ' ').strip()) for item in self.autojoin_channels)
ValueError: invalid literal for int() with base 10: 'yes'

[INFO] launcher: All done.

C:\Users\Anushka\MusicBot>

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AleanaA** [comment]
`autojoinchannels` should be a voice channel id, not yes or no. Before opening new issues for things that relate to a previous issue you had ( #1746 ), it's important to read the options.ini comments for what things in the file do.

**Comment by AutumnClove** [comment]
Hi there! Looking at this traceback error I can see that you want to auto join a channel you need to use the channel ID for autojoining to work properly

**Comment by anu7779** [comment]
![image](https://user-images.githubusercontent.com/43716347/46254029-9ba99e80-c4a6-11e8-9fb2-2e2458e62a69.png)

But again the same error

**Comment by AleanaA** [comment]
As previously stated
`autojoinchannels should be a voice channel id, not yes or no.`

**Comment by anu7779** [comment]
It's fixed. sorry for bothering. 
thankQ very much all
