### ISSUE TITLE
[To Close]!play Youtube Playlist error

### ISSUE THREAD

**Issue by LiderKonmils** [Just-Some-Bots/MusicBot#1748]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
After many months without using my bot, i've tried to reuse it. I've reinstall all for it (Python, Git and the bot). After replacing all the configurations, i've start it and try to add a Youtube playlist : !play https://www.youtube.com/playlist?list=PLjK-NMwQ4FptN6Zca5IW1yCSJiMCePpmC [Enter] and the bot gave me that error: You don't have the permission to play media from this service. I can add an url of an individual youtube video, but not a playlist. What did i miss?

P.S.: I am the owner and i've set the owner id to mine (!id).

### Steps to reproduce

1. !play [any Youtube Playlist url]

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2432001/musicbot.log)

**Comment by AutumnClove** [comment]
In permissions ads youtube:playlist u probably added yourself to a permission group

**Comment by LiderKonmils** [comment]
Thanks, that fix it. I don't know how i put myself anywhere, but that works.

**Comment by ghost** [comment]
If that happens again, add yourself to the Music Masters group & everything will work as it should. :)
