### ISSUE TITLE
freeze bot

### ISSUE THREAD

**Issue by RubyTemple** [Just-Some-Bots/MusicBot#1750]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

root@ItaSkyGames:~# cd MusicBot/
root@ItaSkyGames:~/MusicBot# python3.5 run.py
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment

help me i start bot and it freez

**Comment by RubyTemple** [comment]
root@ItaSkyGames:~/MusicBot# ./run.sh 
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "/root/MusicBot/musicbot/__init__.py", line 7, in <module>
    from .utils import _get_variable
  File "/root/MusicBot/musicbot/utils.py", line 3, in <module>
    import aiohttp
ImportError: No module named 'aiohttp'
[INFO] launcher: Attempting to install dependencies...
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "/root/MusicBot/musicbot/__init__.py", line 7, in <module>
    from .utils import _get_variable
  File "/root/MusicBot/musicbot/utils.py", line 3, in <module>
    import aiohttp
ImportError: No module named 'aiohttp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 388, in main
    err = PIP.run_install('--upgrade -r requirements.txt')
  File "run.py", line 83, in run_install
    return cls.run("install %s%s" % ('-q ' if quiet else '', cmd), check_output)
  File "run.py", line 36, in run
    raise RuntimeError("Could not import pip.")
RuntimeError: Could not import pip.

[INFO] launcher: All done.


if i try to do ./run.sh

**Comment by RubyTemple** [comment]
ubuntu 16.04

**Comment by MattBSG** [comment]
What is the output of `python3 --version`

**Comment by RubyTemple** [comment]
root@ItaSkyGames:~# python3 --version
Python 3.5.2

**Comment by MattBSG** [comment]
Use `python3.6 run.py` instead now. If pip is also not installed, install pip: 
https://pip.pypa.io/en/stable/installing/

**Comment by RubyTemple** [comment]
...

**Comment by RubyTemple** [comment]
SEEEE
root@ItaSkyGames:~/MusicBot# python3.6 run.py
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment

**Comment by RubyTemple** [comment]
and it freeze

**Comment by RubyTemple** [comment]
root@ItaSkyGames:~# cd MusicBot/
root@ItaSkyGames:~/MusicBot# python3.6 run.py
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C

**Comment by RubyTemple** [comment]
is unstopable

**Comment by RubyTemple** [comment]
pl fix

**Comment by RubyTemple** [comment]
pls* it not start.

**Comment by MattBSG** [comment]
Determined as system issue
