### ISSUE TITLE
help bot freeze

### ISSUE THREAD

**Issue by RubyTemple** [Just-Some-Bots/MusicBot#1751]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by RubyTemple** [comment]
root@ItaSkyGames:# cd MusicBot/
root@ItaSkyGames:/MusicBot# python3.5 run.py
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment


root@ItaSkyGames:~/MusicBot# ./run.sh
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
File "run.py", line 367, in main
from musicbot import MusicBot
File "/root/MusicBot/musicbot/init.py", line 7, in
from .utils import _get_variable
File "/root/MusicBot/musicbot/utils.py", line 3, in
import aiohttp
ImportError: No module named 'aiohttp'
[INFO] launcher: Attempting to install dependencies...
Traceback (most recent call last):
File "run.py", line 367, in main
from musicbot import MusicBot
File "/root/MusicBot/musicbot/init.py", line 7, in
from .utils import _get_variable
File "/root/MusicBot/musicbot/utils.py", line 3, in
import aiohttp
ImportError: No module named 'aiohttp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "run.py", line 388, in main
err = PIP.run_install('--upgrade -r requirements.txt')
File "run.py", line 83, in run_install
return cls.run("install %s%s" % ('-q ' if quiet else '', cmd), check_output)
File "run.py", line 36, in run
raise RuntimeError("Could not import pip.")
RuntimeError: Could not import pip.

[INFO] launcher: All done.

if i try to do ./run.sh


ubuntu 16.04


root@ItaSkyGames:~# python3 --version
Python 3.5.2


root@ItaSkyGames:~/MusicBot# python3.6 run.py
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment

doesnt work :(

**Comment by RubyTemple** [comment]
root@ItaSkyGames:~/MusicBot# python3.7 run.py 
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment

**Comment by MattBSG** [comment]
Do not post duplicate issues, it only causes more issues for you. We are not online 24/7 to immediately provide help. You can post in the MusicBot help channel on our [discord server](https://discord.gg/bots) too.

**Comment by MattBSG** [comment]
#1750
