### ISSUE TITLE
I dont get the !clean command ?

### ISSUE THREAD

**Issue by clear12kc** [Just-Some-Bots/MusicBot#177]
[http://i.imgur.com/76uysLJ.png](I dont know how to use the clean command! can anyone help me?
![discord_2016-04-04_09-03-04]%28https://cloud.githubusercontent.com/assets/18252752/14236206/27dc03a0-fa44-11e5-9aaa-296de846ccfe.png%29)
I dont know how to use the clean command! can anyone help me?

**Comment by imayhaveborkedit** [comment]
The clean command in the `develop` version does nothing.  I don't know why you're using that version, but use a newer one.  https://github.com/SexualRhinoceros/MusicBot/releases
