### ISSUE TITLE
Bot Not Responding To Commands

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1770]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
I have just (re)installed my bot and every time I attempt to play a song via "!play" and it does not respond in discord and no output in the console.

(edit) It seems to think that it is not in a Discord Channel via !summon

### Steps to reproduce

N/A

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2499507/musicbot.log)

**Comment by amit177** [comment]
It looks like the bot is trying to join the voice channel, but it fails.
What host are you using?

**Comment by ghost** [comment]
sorted:
Hetzner is blocked by discord.
