### ISSUE TITLE
Musicbot not responding to commands.

### ISSUE THREAD

**Issue by wellivea1** [Just-Some-Bots/MusicBot#1771]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.8)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
The bot does not respond to commands, but does output an error in the console. I have the channel bound in the config, and the bot has the relevant permissions. I did reinstall the bot recently due to me updating all the dependencies with pip-review breaking the bot, and when I finished this started happening. Music from the autoplaylist does play just fine though.

### Steps to reproduce

1. Try to use the bot with the latest review version,

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2499556/musicbot.log)

**Comment by wellivea1** [comment]
Hopefully that fixes it. I haven't thought to use someone else to test it since barely anybody uses my bot xD.
>246571108214636544/wellivea1#7625: !np
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "C:\Users\welli\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\welli\MusicBot\musicbot\bot.py", line 2625, in on_message
    user_permissions = self.permissions.for_user(message.author)
  File "C:\Users\welli\MusicBot\musicbot\permissions.py", line 104, in for_user
    if user.id in group.user_list:
TypeError: 'in <string>' requires string as left operand, not int

**Comment by wellivea1** [comment]
I'm not sure if the latest update was supposed to fix this, but it's still happening.

**Comment by TheerapakG** [comment]
Because the fix is not merged yet. The PR that supposedly will fix this is still open. The recently merged PR is supposed to fix other things.

**Comment by dcheng0** [comment]
Try making a text channel, voice channel, and linking the two. Give bot appropriate permissions. I had the same / a similar issue. My bot was in General, and I was trying to communicate with it on a separate text channel that it had the appropriate permissions on.

**Comment by wellivea1** [comment]
You mean syncing the permissions? I guess I could do that, but that shouldn't make a difference since the bot has permissions in both places. And I just tested it, it doesn't work. Even with non-owner users.

**Comment by TheerapakG** [comment]
@wellivea1 I'm almost certain that the fix I am trying to merge into the bot should solve this problem. Can you try cloning the bot from the mentioned PR branch and test it?

**Comment by wellivea1** [comment]
I can sometime next week...hopefully

**Comment by wellivea1** [comment]
It fixed it. 😄
