### ISSUE TITLE
Commands cause huge error

### ISSUE THREAD

**Issue by Backyusa** [Just-Some-Bots/MusicBot#1773]
Please tick all applicable boxes.

- [x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.8)
- [ x] The latest `review` version

What type of issue are you creating?

- [ x] Bug
- [ ] Feature request
- [ ] Question

----

### Steps to reproduce

1. !play (any link)

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2521778/musicbot.log)

**Comment by AutumnClove** [comment]
Run the update file

**Comment by Backyusa** [comment]
I did that before, but now that you said it I did it again BUT I did it as an admin and now it worked!
