### ISSUE TITLE
Bot wont go online.

### ISSUE THREAD

**Issue by smolbeann** [Just-Some-Bots/MusicBot#1775]
Please tick all applicable boxes.

- [ ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
I tried all I could do to get the bot online. Nothing will work. I went through as many tuts as I could find and nothing worked to get the bot online. I went through every step in every tut and when it came to getting the bot online it still didn't work. I spent 3-5 hours trying to find a solution to the problem but I haven't found anything. I'm close to giving up and seeing if someone else can script the bot for me. Im still new to this whole developing discord bots of my own thingy but I legit tried everything I could do for a straight 3-5 hours and nothing seems to work.

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2523683/musicbot.log)

**Comment by TheerapakG** [comment]
from comment above AutoJoinChannel
> Allows the bot to automatically join servers on startup. To use this, __add the IDs__
> __of the voice channels__ you would like the bot to join on startup, seperated by a
> space. Each server can have one channel. If this option and AutoSummon are
> enabled, this option will take priority.

You put `no` after AutoJoinChannel, which is not what it expected. To not automatically join voice channels you simply leave it blank

**Comment by smolbeann** [comment]
> from comment above AutoJoinChannel
> 
> > Allows the bot to automatically join servers on startup. To use this, **add the IDs**
> > **of the voice channels** you would like the bot to join on startup, seperated by a
> > space. Each server can have one channel. If this option and AutoSummon are
> > enabled, this option will take priority.
> 
> You put `no` after AutoJoinChannel, which is not what it expected. To not automatically join voice channels you simply leave it blank

thank you so much. It worked!
