### ISSUE TITLE
Fix This i Can't Fix It 

### ISSUE THREAD

**Issue by LeomKane** [Just-Some-Bots/MusicBot#1779]
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "C:\Users\ibrahim\Desktop\Music Bot\musicbot\__init__.py", line 7, in <mo
dule>
    from .utils import _get_variable
  File "C:\Users\ibrahim\Desktop\Music Bot\musicbot\utils.py", line 3, in <modul
e>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
[INFO] launcher: Attempting to install dependencies...
pip is configured with locations that require TLS/SSL, however the ssl module in
 Python is not available.
Collecting pynacl==1.2.1 (from -r requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'SSLError("Can't connect to HTTPS URL because the SS
L module is not available.")': /simple/pynacl/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'SSLError("Can't connect to HTTPS URL because the SS
L module is not available.")': /simple/pynacl/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'SSLError("Can't connect to HTTPS URL because the SS
L module is not available.")': /simple/pynacl/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'SSLError("Can't connect to HTTPS URL because the SS
L module is not available.")': /simple/pynacl/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'SSLError("Can't connect to HTTPS URL because the SS
L module is not available.")': /simple/pynacl/
  Could not fetch URL https://pypi.org/simple/pynacl/: There was a problem confi
rming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max r
etries exceeded with url: /simple/pynacl/ (Caused by SSLError("Can't connect to
HTTPS URL because the SSL module is not available.")) - skipping
  Could not find a version that satisfies the requirement pynacl==1.2.1 (from -r
 requirements.txt (line 1)) (from versions: )
No matching distribution found for pynacl==1.2.1 (from -r requirements.txt (line
 1))
pip is configured with locations that require TLS/SSL, however the ssl module in
 Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming
 the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retrie
s exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS UR
L because the SSL module is not available.")) - skipping

[CRITICAL] launcher: You may need to run as admin to install dependencies.

[INFO] launcher: All done.

C:\Users\ibrahim\Desktop\Music Bot>

**Comment by jayktaylor** [comment]
This looks like an issue with your network configuration when using pip, Python's package manager. You should take this up with pip's developers.
