### ISSUE TITLE
discord music bot installing on DO ubuntu server problem

### ISSUE THREAD

**Issue by bobjaeger** [Just-Some-Bots/MusicBot#178]
Hello im bobby i just now moving your music bot to my DO server and already follow your guide. but i had problem at step 6C, i cant run bot with ssh then ssh give error message like this

:
please see attachment run python

ok as you said this:
If you see an error, you might want to try installing dependencies by hand. You can do this by executing the command pip3.5 install -r requirements.txt

now i run pip requirement, then i got this error

:
please see attachment install pip

well i done 2 times redo all the things but still getting error on this step, please help me bro thanks very much!!! :)

[installpip.txt](https://github.com/SexualRhinoceros/MusicBot/files/201694/installpip.txt)

[runpython.txt](https://github.com/SexualRhinoceros/MusicBot/files/201693/runpython.txt)

**Comment by imayhaveborkedit** [comment]
The dockerfile was updated earlier today, but in to fix this you need to install libffi-dev.  Run `sudo apt-get install libffi-dev`

**Comment by bobjaeger** [comment]
emm ic the problem ahha ok now its working. nice shoot man thanks very much looking forward your work hard man appreciate that
