### ISSUE TITLE
Can't play playlist from Spotify that contains more than 100 tracks

### ISSUE THREAD

**Issue by Matx1002** [Just-Some-Bots/MusicBot#1780]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8_1)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
Can't play playlist from Spotify that contains more than 100 tracks.

**Comment by AutumnClove** [comment]
This is a known issue and a PR has been made to address it

**Comment by jayktaylor** [comment]
Should've been fixed by #1690.
