### ISSUE TITLE
Exception occurs when trying to play from queue

### ISSUE THREAD

**Issue by Meowners** [Just-Some-Bots/MusicBot#1781]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
The bot fails to play the next song in the queue instead it outputs an exception however remains funcional.
After the error occurs issuing another play command will cause the song to play like normal.
The error occurs 100% of the time

### Steps to reproduce

1. Start the music bot
2. queue 2 songs

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2551507/musicbot.log)

**Comment by AutumnClove** [comment]
I think this is fixed in review?
