### ISSUE TITLE
Not a Git repository

### ISSUE THREAD

**Issue by TalonTheRogue** [Just-Some-Bots/MusicBot#1784]
I am using Python 3.5 or higher (run `python --version` on the command line)
I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system

I keep getting this
Starting...
Traceback (most recent call last):
  File "update.py", line 75, in <module>
    main()
  File "update.py", line 35, in main
    raise EnvironmentError("This isn't a Git repository.")
OSError: This isn't a Git repository.

**Comment by AleanaA** [comment]
You didn't use git to clone the bot, odds are you downloaded a zip file.

Read through the guides to clone the bot properly.
