### ISSUE TITLE
Error: says Need to be in channel to play while its already in channel

### ISSUE THREAD

**Issue by realsepehrz** [Just-Some-Bots/MusicBot#1788]
Please tick all applicable boxes.

- [√] I am using Python 3.5 or higher (run `python --version` on the command line)
- [√] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [√] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [√] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [√] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
i installed the bot on a vps with windows server 2016 and from https://just-some-bots.github.io/MusicBot/installing/windows/ .
after pasting my config from the last server that i have made ( 4 months ago ) ( options.ini and permissions.ini  ) after that i ran the bot and waited and saw it works fine , i closed the vps session and after some hours it started to get bugged , when i tried to play music while the bot is already in the channel it says You need to summon to play .... and  i tried to !disconnect and !restart but it didnt work and when i tried to restart it manualy after using update thing it gave me this error after lot of time on attempting to join ....
![image](https://user-images.githubusercontent.com/45466228/49242372-d0db5a00-f41f-11e8-973e-6c56c48de871.png)

and cant play again
![image](https://user-images.githubusercontent.com/45466228/49242769-d4bbac00-f420-11e8-878a-de82c2d81f90.png)

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2630386/musicbot.log)

**Comment by AleanaA** [comment]
The bot was attempting to join, but failed to connect. Odds are this is an issue with the host you have.

**Comment by realsepehrz** [comment]
> The bot was attempting to join, but failed to connect. Odds are this is an issue with the host you have.
it was fine a while ago :|

**Comment by realsepehrz** [comment]
![image](https://user-images.githubusercontent.com/45466228/49243982-f1a5ae80-f423-11e8-8e07-1c12c7615f47.png)
what is this error for ?

**Comment by AleanaA** [comment]
The bot never fully connected, and as such, isn't actually in the voice channel.

**Comment by CgGroph** [comment]
I have the same problem. Is there any Port to open?

**Comment by AutumnClove** [comment]
Fixed in review.
