### ISSUE TITLE
Cant find owner

### ISSUE THREAD

**Issue by Keyb0ardsmasher** [Just-Some-Bots/MusicBot#1790]
Please tick all applicable boxes.

- [x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ x] The latest `master` version (1.9.8)
- [x ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [ x] Question

----

### Description of issue
Bot launches but says "WARNING: Owner could not be found on any guild (id: XXXXXXXX)

Guild List:
- None (unavailable)

Not bound to any text channels

### Steps to reproduce

1.  Everytime I use the run.bat I have tried updating/doing several fresh installs and changing nothing but token+owner nothing seems to fix it 

----
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2637419/musicbot.log)

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AutumnClove** [comment]
You just need to invite the bot to your server, when starting it should give you an invite link

**Comment by Keyb0ardsmasher** [comment]
> 
> 
> You just need to invite the bot to your server, when starting it should give you an invite link

its in the server and seems to be working just wont bind to a text channel

**Comment by TheerapakG** [comment]
> its in the server and seems to be working just wont bind to a text channel

In config/options.ini, add channel ids that you want the bot to bind to in the option BindtoChannels

**Comment by Keyb0ardsmasher** [comment]
> 
> 
> > its in the server and seems to be working just wont bind to a text channel
> 
> In config/options.ini, add channel ids that you want the bot to bind to in the option BindtoChannels

Thats done as well I think it might just be the bot lagging behind in load time as the server its in is 100k+ people although in the command prompt it appears to be not correct aside from that after kicked the bot and re inviting everything else appears to be working fine.

**Comment by TheerapakG** [comment]
Actually, after I read the code again I think the BindtoChannels and
AutojoinChannels are bugged at the moment. I can't test my hypothesis right
now (I'm away from my home) but I think this is another "rewrite id is an
int not a string" bug.

**Comment by Keyb0ardsmasher** [comment]
> 
> Actually, after I read the code again I think the BindtoChannels and AutojoinChannels are bugged at the moment. I can't test my hypothesis right now (I'm away from my home) but I think this is another "rewrite id is an int not a string" bug.

Bot appeared to have fixed itself after waiting for awhile I think it was just lagging due to the amount of users

**Comment by TheerapakG** [comment]
Now that I really look at it it should work as intended, albeit verifying config like this is a little bit "strange" so I'll fix that. Your issue might really be the amount of users
