### ISSUE TITLE
update.bat not working properly

### ISSUE THREAD

**Issue by benkouts** [Just-Some-Bots/MusicBot#1791]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script **Cannot do this**

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue

**update.bat meets an error and fails to update dependencies**
**this also makes run.bat display an error**

Starting...
Passed Git checks...
Checking if we need to update the bot...
Already up to date.
Attempting to update dependencies...
Collecting pynacl==1.2.1 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/6c/93/29931e02f3add7952f2e
a1976960c8a591a92dcc57a76cd3d736e1c554d0/PyNaCl-1.2.1-cp37-cp37m-win_amd64.whl (
165kB)
Could not install packages due to an EnvironmentError: [WinError 31] A device at
tached to the system is not functioning
Consider using the `--user` option or check the permissions.

You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-
8'>
PermissionError: [WinError 31] A device attached to the system is not functionin
g
Traceback (most recent call last):
  File "update.py", line 17, in update_deps
    subprocess.check_call('{} -m pip install -U -r requirements.txt'.format(sys.
executable), shell=True)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python37\lib\subprocess.py",
line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Users\Ben\AppData\Local\Programs\Pyth
on\Python37\python.exe -m pip install -U -r requirements.txt' returned non-zero
exit status 120.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update.py", line 75, in <module>
    main()
  File "update.py", line 71, in main
    update_deps()
  File "update.py", line 19, in update_deps
    raise OSError("Could not update dependencies. You will need to run '{0} -m p
ip install -U -r requirements.txt' yourself.".format(sys.executable))
OSError: Could not update dependencies. You will need to run 'C:\Users\Ben\AppData\Local\Programs\Python\Python37\python.exe -m pip install -U -r requirements.txt' yourself.

C:\Users\Ben\Desktop\MusicBot>

### Steps to reproduce

1. run update.bat
2. run run.bat

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2646238/musicbot.log)

**Comment by AleanaA** [comment]
This is an error with your setup. The only known fix for this issue as of now is to just use python 3.5.4 instead of 3.7.
