### ISSUE TITLE
Configing the bot from ubuntu

### ISSUE THREAD

**Issue by realsepehrz** [Just-Some-Bots/MusicBot#1795]
i just got a Ubuntu 18.04 vps and followed instruction in http://just-some-bots.github.io/MusicBot/installing/ubuntu/ but right now idont know how to config files and edit bot.py file to customize !!! (   never used terminals :<   )

**Comment by AleanaA** [comment]
use nano and google things.

**Comment by realsepehrz** [comment]
iam trying to but its not the easy you know .... 
can anyone just say how to open and edit files ? and saving and  closing ( if there is  saving ?? )

**Comment by AleanaA** [comment]
I believe [this](https://wiki.gentoo.org/wiki/Nano/Basics_Guide) will help you a lot.
