### ISSUE TITLE
Can't start bot 

### ISSUE THREAD

**Issue by ronaldosantanna** [Just-Some-Bots/MusicBot#1803]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

I use the bot on raspberry pi for a while and it worked ok. But i updated the bot because of some bugs (disconnecting and reconnecting all the time).

So i make it to autorun just running "/home/pi/MusicBot/run.sh" on "/etc/rc.local" and it was fine.

And now v1.9.8_2 it doesn't work because:  (((comando não encontrado = command not found)))
>~ $ /home/pi/MusicBot/run.sh
>/home/pi/MusicBot/run.sh: linha 7: python3.6: comando não encontrado
>/home/pi/MusicBot/run.sh: linha 8: python3.7: comando não encontrado
>python3: can't open file '/run.py': [Errno 2] No such file or directory

And when i do: 
>~ $ cd MusicBot/
>~ $ ./run.sh

it works.

I just reinstall it to make sure it was all ok. But i think it is something of the recent update.

### Steps to reproduce

1.  /home/pi/MusicBot/run.sh

----

### Log file
Log of the step i said it works.

**Comment by ronaldosantanna** [comment]
I tried to change the file "run.sh" like this
>.14: pyhon "run.py" to "/home/pi/MusicBot/run.py"

so it returns:
>[INFO] launcher: Starting sanity checks
>[INFO] launcher: Checking for Python 3.5+
>[INFO] launcher: Checking console encoding
>[INFO] launcher: Ensuring we're in the right environment
>[CRITICAL] launcher: Bot wasn't installed using Git. Reinstall using http://bit.ly/musicbotdocs.
>Press enter to continue . . .

I tried to run on terminal:
>~ $ python3 /home/pi/MusicBot/run.py

it returns the same:
>[INFO] launcher: Starting sanity checks
>[INFO] launcher: Checking for Python 3.5+
>[INFO] launcher: Checking console encoding
>[INFO] launcher: Ensuring we're in the right environment
>[CRITICAL] launcher: Bot wasn't installed using Git. Reinstall using http://bit.ly/musicbotdocs.
>Press enter to continue . . .

**Comment by AutumnClove** [comment]
As stated by the output please reinstall using git

**Comment by TheerapakG** [comment]
@AutumnClove it works when he/she is in the musicbot directory so that's not the case

about the issue: That it's because bash's working directory is wherever you invoke bash, so it can't find the `run.py`. When bash start the Python process, the Python process also start in that whatever directory and it can't find `.git` folder, hence the message `Bot wasn't installed using Git.`

But according to [the guide](https://just-some-bots.github.io/MusicBot/installing/raspbian/) you're supposed to run it in the musicbot directory so it does not really count as a bug (does an earlier version of the run script really work without requiring you to be in the directory? weird)

**Comment by ronaldosantanna** [comment]
> But according to [the guide](https://just-some-bots.github.io/MusicBot/installing/raspbian/) you're supposed to run it in the musicbot directory (does an earlier version of the run script really work without requiring you to be in the directory? weird)

Yes. It worked without being on  music bot directory.
Because of this i thought it was a bug, sorry.

So, now i cant autorun?
or do you know other way to do that?

**Comment by ronaldosantanna** [comment]
Well after a long time looking to a script to add on `/etc/init.d` and it doesn't work. I just back to run.sh file and add a simple line on it. 
>cd /home/pi/MusicBot/

The bot back to autorun with no problems. Thanks for trying to help me. 

Anyone who have doubts of how autorun it on raspberry is just edit the file run. 

>[...]
>PYTHON37_VERSION=python3.7 -c 'import sys; version=sys.version_info[:3]; print({0}".format(version[1]))' || { echo "no py37"; }
>
>`cd /home/pi/MusicBot`
>
>if [ "${python[0]}" -eq "3" ]; then # Python = 3
>[...]


And on `/etc/rc.local` add on the last line the directory of the run.sh file like this:
>`"/home/pi/MusicBot/run.sh"`(in my case).

**Comment by jayktaylor** [comment]
Thanks.
