### ISSUE TITLE
Doesnt work "/play"

### ISSUE THREAD

**Issue by x1tko0** [Just-Some-Bots/MusicBot#1804]
Doesnt work "/play" command https://service.crazypanda.ru/v/monosnap/2018-12-17-15-00-00-igk4w.png
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2686095/musicbot.log)

**Comment by AleanaA** [comment]
Update your dependencies using the update script.

**Comment by x1tko0** [comment]
How i need to do that?

**Comment by AleanaA** [comment]
the update batch script
just double click it

**Comment by x1tko0** [comment]
https://service.crazypanda.ru/v/monosnap/2018-12-17-15-06-44-ywdhv.png This error

**Comment by AleanaA** [comment]
The actual error would be above that.

**Comment by x1tko0** [comment]
> The actual error would be above that.

https://service.crazypanda.ru/v/monosnap/2018-12-17-15-11-19-qloha.png https://service.crazypanda.ru/v/monosnap/2018-12-17-15-12-30-l7jdr.png

**Comment by AleanaA** [comment]
Uninstall python and use this version. Remember to check Add to Path.
https://www.python.org/ftp/python/3.5.4/python-3.5.4.exe

**Comment by x1tko0** [comment]
> Uninstall python and use this version. Remember to check Add to Path.
> https://www.python.org/ftp/python/3.5.4/python-3.5.4.exe

i have 3.7 python, still need to reinstall?

**Comment by AleanaA** [comment]
Yes. Uninstall it and install the version I linked.

**Comment by x1tko0** [comment]
> Yes. Uninstall it and install the version I linked.

Last time i have issue - https://github.com/Just-Some-Bots/MusicBot/issues/1741 see that - https://service.crazypanda.ru/v/monosnap/2018-12-17-15-18-38-zzdx8.png wtf?

**Comment by MattBSG** [comment]
That’s why they instructed you to use 3.5.**4**.

**Comment by x1tko0** [comment]
> That’s why they instructed you to use 3.5.**4**.

They instructed me to use python 3.7!!!! https://service.crazypanda.ru/v/monosnap/2018-12-17-15-21-46-xdlkk.png

**Comment by AleanaA** [comment]
He was referencing me. If you don't install the version I linked, there's nothing we can do for you.

**Comment by x1tko0** [comment]
> He was referencing me. If you don't install the version I linked, there's nothing we can do for you.

okay, but thas so missunderstanding

**Comment by x1tko0** [comment]
> Remember to check Add to Path.

Btw what u mean this?

**Comment by AleanaA** [comment]
It's a checkbox in the installer, I'm telling you to remember to check it.

**Comment by x1tko0** [comment]
> It's a checkbox in the installer, I'm telling you to remember to check it.

Thanks a lot! Works now, Have a nice day!

**Comment by TheerapakG** [comment]
Normally I told people (that use outdated Python) to use 3.7 because that's the version that the bot is maintained with. But in case that 3.7 doesn't work I also would instruct them to use 3.5.4 instead of 3.7. 3.7 do have habits of breaking on some machine but I generally encourage people to use up-to-date software hence I said 'update to 3.7' to you in that issue.

**Comment by x1tko0** [comment]
> Normally I told people (that use outdated Python) to use 3.7 because that's the version that the bot is maintained with. But in case that 3.7 doesn't work I also would instruct them to use 3.5.4 instead of 3.7. 3.7 do have habits of breaking on some machine but I generally encourage people to use up-to-date software hence I said 'update to 3.7' to you in that issue.

Got it! Thanks!
