### ISSUE TITLE
Setting it Up

### ISSUE THREAD

**Issue by Fextem** [Just-Some-Bots/MusicBot#181]
http://prntscr.com/ap3cgv

It says the owner could not be found in the server. I have the bot with its associated account in the server, but it just doesn't work. pls help

**Comment by Echoskope** [comment]
You are the owner; were you in a voice channel or in the discord server when you started the script? Can you provide more details on why "it just doesn't work"?

**Comment by Fextem** [comment]
The bot is in the server with me. It is not in the voice channel, it is in the discord server when I started the script.

**Comment by Echoskope** [comment]
Have you tried joining a voice channel with your own account and executing *summon? Looks like it tried to auto-summon but since you were not in a voice channel it gave up.

**Comment by Fextem** [comment]
I might be confused on certain steps. The owner is the account associated with the bot itself... correct? And yes, I am in the voice channel upon executing *summon. http://prntscr.com/ap3esj This is what things look like.

**Comment by Echoskope** [comment]
The owner is the person who owns the bot, i.e. in your case you would put your own ID in there given to you by running \@your_user_name where your_user_name is your discord user name.

**Comment by Fextem** [comment]
Thanks, it's working! I had the actual bot's ID be the owner ID. And thank you for the quick replies.

**Comment by Echoskope** [comment]
Fantastic! Glad to hear things worked out :)
