### ISSUE TITLE
Unable to access - SSL Error

### ISSUE THREAD

**Issue by Elosity** [Just-Some-Bots/MusicBot#1810]
Please tick all applicable boxes.

- [-] I am using Python 3.5 or higher (run `python --version` on the command line)
- [-] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script
update script not working
Which version are you using?

- [-] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [-] Bug
- [ ] Feature request
- [-] Question

----

### Description of issue
I setup my discord bot and put in my token but when i click update it cant access the website for download for some error involving SSL. Heres what it says:

Starting...
Passed Git checks...
Checking if we need to update the bot...
fatal: unable to access 'https://github.com/Just-Some-Bots/MusicBot.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Traceback (most recent call last):
  File "update.py", line 68, in main
    subprocess.check_call('git pull', shell=True)
  File "C:\Users\elo20\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git pull' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update.py", line 76, in <module>
    main()
  File "update.py", line 70, in main
    raise OSError("Could not update the bot. You will need to run 'git pull' yourself.")
OSError: Could not update the bot. You will need to run 'git pull' yourself.

Please help

### Steps to reproduce

1. Produce MusicBot Folder
2. use the options file to insert your token
3. click update 
Log:
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2716878/musicbot.log)

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AutumnClove** [comment]
Did you install git to path?

**Comment by Elosity** [comment]
Does that mean i have to select 'Use Git and Optional Unix tools from the Command Prompt' during installation? @AutumnClove

**Comment by AutumnClove** [comment]
Yea

**Comment by Elosity** [comment]
@AutumnClove do i use the OpenSSL library or native Windows Secure Channel Library

**Comment by AleanaA** [comment]
All default settings in the git installer work fine.

**Comment by Elosity** [comment]
@AleanaA does that mean i should still check Use Git and Optional Unix tools from the Command Prompt or what is the original one for it

**Comment by jayktaylor** [comment]
This looks like an issue with your Git installation (or GitHub) and you'd be better off taking it up with the developers behind Git [for Windows] rather than us.
