### ISSUE TITLE
Question: Bot deleting now playing messages even with DeleteMessages and DeleteInvoking disabled, how can this be turned off?

### ISSUE THREAD

**Issue by suprstarrd** [Just-Some-Bots/MusicBot#1812]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
Hello there!

I've been using your bot for a few days now, and now playing messages are being deleted after the song has been finished, but I've disabled DeleteMessages and DeleteInvoking in the `options.ini` file.

I'm assuming this is intentional, as I'm receiving no errors in the console, but I'd like to make sure it doesn't delete what was playing before in my server. How do I turn this off?

Seems it might be related to #1090. Unsure.

Thank you!

### Steps to reproduce
This isn't really applicable, but...
1. Play two or more songs
2. Wait for the first song to end
3. That's it

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by TheerapakG** [comment]
Automatic deletion of now playing messages can't be turn off in the current (1.9.8_3) version of MusicBot. There is a PR (#1808) that will make this  possible.
