### ISSUE TITLE
Clone Error

### ISSUE THREAD

**Issue by Tayfinford** [Just-Some-Bots/MusicBot#1813]
Please tick all applicable boxes.

- [. ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [. ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ .] The latest `master` version (1.9.8)
- [. ] The latest `review` version

What type of issue are you creating?

- [. ] Bug
- [ ] Feature request
- [ ] Question

----

When I run the clone bit into Git Bash I get this error:

error: RPC failed; curl 18 transfer closed with outstanding read data remaining 
fatal: the remote end hung up unexpectedly                                       
fatal: early EOF                                                                 
fatal: index-pack failed

**Comment by jayktaylor** [comment]
This looks like an issue with your Git installation and you'd be better off taking it up with the developers behind Git [for Windows] rather than us.
