### ISSUE TITLE
Bot not joining channel

### ISSUE THREAD

**Issue by FailureGuy** [Just-Some-Bots/MusicBot#1814]
I'm having a little problem. My bot is not joining my channel
Error message after typing "!join" : 

-@KacPonadWszystkoWilku, An error occurred while running the command: ReferenceError: servers is not defined
You shouldn't ever receive an error like this.
Please contact the bot owner.

And thats how my code for joining looks like:

const commando = require('discord.js-commando');
const YTDL = require('ytdl-core')

function Play(connection, message)
{
    var server = servers[message.guild.id]
    server.dipatcher = connection.playStream(YTDL(server.queue[0], {filter: "audioonly"}));
    server.queue.shift();
    server.dipatcher.on('end', function(){
        if(server.queue[0])
        {
            Play(connection,message);
        }
        else
        {
            connection.disconnect();
        }
    });
}

class JoinChannelCommand extends commando.Command
{
    constructor(client)
    {
        super(client,{
            name: 'join',
            group: 'music',
            memberName: 'join',
            description: 'Dołącza do twojego kanału'
        });
    }

    async run(message, args)
    {
        if(message.member.voiceChannel)
        {
            if(!message.guild.voiceConnection)
            {
                if(!servers[nessage.guild.id])
                {
                    servers[message.guild.id] = {queue: []}
                }
                message.member.voiceChannel.join()
                    .then(connection =>{
                        var server = servers[message.guild.id];
                        message.reply("Dołączono do kanału :wolf::headphones:!");
                        server.queue.push(args);
                        Play(connection, message);
                    })
            }
        }
        else
        {
            message.reply("Musisz być na kanale głosowym!!");
        }
    }
}

module.exports = JoinChannelCommand;

**Comment by AleanaA** [comment]
This repo is for MusicBot, not a bot you made on your own.

**Comment by MattBSG** [comment]
Please find help elsewhere, such as discord-api or a programming server. Issues here should only be for our code base.
