### ISSUE TITLE
Can't run the bot

### ISSUE THREAD

**Issue by bipolarr** [Just-Some-Bots/MusicBot#1821]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

I try to run the bot and i get an error, I even tried to run as administrator as it says to do so, and it doesn't work.

### Steps to reproduce

1. 

----

### Log file

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "C:\Users\Ascenção\Documents\MusicBot\musicbot\__init__.py", line 74, in <module>
    from .bot import MusicBot
  File "C:\Users\Ascenção\Documents\MusicBot\musicbot\bot.py", line 17, in <module>
    import colorlog
ModuleNotFoundError: No module named 'colorlog'
[INFO] launcher: Attempting to install dependencies...
Requirement already up-to-date: pynacl==1.2.1 in c:\users\ascenção\appdata\local\programs\python\python37-32\lib\site-packages (from -r requirements.txt (line 1)) (1.2.1)
Collecting discord.py[voice] from git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice] (from -r requirements.txt (line 2))
  Cloning https://github.com/Rapptz/discord.py (to revision rewrite) to c:\users\asceno~4\appdata\local\temp\pip-install-jmknv6pd\discord.py
Switched to a new branch 'rewrite'
Branch 'rewrite' set up to track remote branch 'rewrite' from 'origin'.
Requirement already up-to-date: pip in c:\users\ascenção\appdata\local\programs\python\python37-32\lib\site-packages (from -r requirements.txt (line 3)) (18.1)
Collecting youtube_dl (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/be/de/70803c90db365e54ad429daed420846862bf0039276727fe40588c1004b4/youtube_dl-2019.1.16-py2.py3-none-any.whl
Collecting colorlog (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/68/4d/892728b0c14547224f0ac40884e722a3d00cb54e7a146aea0b3186806c9e/colorlog-4.0.2-py2.py3-none-any.whl
Requirement already up-to-date: cffi in c:\users\ascenção\appdata\local\programs\python\python37-32\lib\site-packages (from -r requirements.txt (line 6)) (1.11.5)
Requirement already satisfied, skipping upgrade: six in c:\users\ascenção\appdata\local\programs\python\python37-32\lib\site-packages (from pynacl==1.2.1->-r requirements.txt (line 1)) (1.12.0)
Requirement already satisfied, skipping upgrade: aiohttp<3.5.0,>=3.3.0 in c:\users\ascenção\appdata\local\programs\python\python37-32\lib\site-packages (from discord.py[voice]->-r requirements.txt (line 2)) (3.4.4)
Requirement already satisfied, skipping upgrade: websockets<7.0,>=6.0 in c:\users\ascenção\appdata\local\programs\python\python37-32\lib\site-packages (from discord.py[voice]->-r requirements.txt (line 2)) (6.0)
Collecting colorama; sys_platform == "win32" (from colorlog->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: pycparser in c:\users\ascenção\appdata\local\programs\python\python37-32\lib\site-packages (from cffi->-r requirements.txt (line 6)) (2.19)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in c:\users\ascenção\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (1.3.0)
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.0 in c:\users\ascenção\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (4.5.2)
Requirement already satisfied, skipping upgrade: chardet<4.0,>=2.0 in c:\users\ascenção\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in c:\users\ascenção\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (3.0.1)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in c:\users\ascenção\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (18.2.0)
Requirement already satisfied, skipping upgrade: idna>=2.0 in c:\users\ascenção\appdata\local\programs\python\python37-32\lib\site-packages (from yarl<2.0,>=1.0->aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (2.8)
Installing collected packages: discord.py, youtube-dl, colorama, colorlog
  Found existing installation: discord.py 1.0.0a1634+g7f4c57d
    Uninstalling discord.py-1.0.0a1634+g7f4c57d:
      Successfully uninstalled discord.py-1.0.0a1634+g7f4c57d
  Running setup.py install for discord.py ... done
Could not install packages due to an EnvironmentError: [WinError 5] Acesso negado: 'C:\\Users\\ASCENO~4\\AppData\\Local\\Temp\\pip-uninstall-gbb25ksd\\users\\ascenção\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\discord\\bin\\libopus-0.x86.dll'
Consider using the `--user` option or check the permissions.

[CRITICAL] launcher: You may need to run as admin to install dependencies.

[INFO] launcher: All done.

**Comment by bipolarr** [comment]
I am sorry if i missed something, i am a bit new to this.

**Comment by AutumnClove** [comment]
Try running `python -m pip install --user -U -r requirements.txt`

**Comment by bipolarr** [comment]
I think it worked, there was no error, but the bot doesn't go online.. I'm sorry but could you explain me or send me a link with what i should do if there is one? Thank you very much

**Comment by AutumnClove** [comment]
The guides linked on the main part should tell you everything but just click run.bat to start your bot

**Comment by bipolarr** [comment]
I clicked on the run.bat that was where the error was coming from. I'll do some more research on the links thank you for your fast response

**Comment by AutumnClove** [comment]
Did you click on it after running the python command and it still gave u that error?

**Comment by AutumnClove** [comment]
https://just-some-bots.github.io/MusicBot/

**Comment by bipolarr** [comment]
That command you sent here? There was no error when i used it, but the bot didn't go online

**Comment by AleanaA** [comment]
The command Autumn sent was to update your dependencies. Afterwards, run.bat will run as expected.

**Comment by bipolarr** [comment]
I will try once again

**Comment by bipolarr** [comment]
Oh it's working now, thank you very much
