### ISSUE TITLE
some music stoped working after reboot

### ISSUE THREAD

**Issue by AlexMayne5** [Just-Some-Bots/MusicBot#1824]
Please tick all applicable boxes.

- [/ ] I am using Python 3.5 or higher (run `python --version` on the command line) 
- [/ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [/ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ /] The latest `master` version (1.9.8)
- [ /] The latest `review` version

What type of issue are you creating?

- [ /] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

missing songs out that usedto work intell i rebooted 

### Steps to reproduce

1.  ? 
![image](https://user-images.githubusercontent.com/46424598/51411337-62816100-1b5f-11e9-8e63-3a7c3e917372.png)

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2774421/musicbot.log)

**Comment by AutumnClove** [comment]
Run the update file and try again

**Comment by AlexMayne5** [comment]
THANK YOU by updating the bot it reinstalled all of the YouTube files and
now the bot works 😀
