### ISSUE TITLE
Cannot play Bandcamp albums

### ISSUE THREAD

**Issue by prenetic** [Just-Some-Bots/MusicBot#1827]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (1.9.8)
- [X] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Cannot play all-up album playlists from various Bandcamp-style sites. Playing songs individually does work, however this tends to be rather cumbersome. It seems like youtube-dl itself has no issues parsing the request as a Bandcamp album and downloading the various files.

I also took a look at https://github.com/Just-Some-Bots/MusicBot/issues/217 which seemed similar at first, yet different exceptions are thrown here.

### Steps to reproduce

1. Issue the command "!play https://rushjet1.com/album/mega-man-3-remade", as an example. I am unable to get any root album page to play as a playlist

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.txt](https://github.com/Just-Some-Bots/MusicBot/files/2789388/musicbot.txt)
[youtube-dl.txt](https://github.com/Just-Some-Bots/MusicBot/files/2789389/youtube-dl.txt)

**Comment by MattBSG** [comment]
Thanks! Just for a sanity sake, can you do the following for me?
* Git pull
* Update dependencies
* Upload your full uncropped bot log

This very much appears to be a bug, I want be sure and have as much information as possible.

**Comment by prenetic** [comment]
Sorry for the delay in getting back to you. I've gone ahead and performed the requested steps, under the review branch since the behavior persists in both anyway. In the bot log you can see what occurs when I first issue the !play command against the all-up album (where it fails), followed by a successful attempt to play an individual song from that album.

Please let me know if you need any additional information.

[setup.txt](https://github.com/Just-Some-Bots/MusicBot/files/2805892/setup.txt)
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2805901/musicbot.log)

**Comment by prenetic** [comment]
Also, I may be completely mistaken here, but are we logging the OAuth bearer tokens for Spotify in plaintext? Bearer tokens rely on TLS for security and is probably something users should be aware of and scrub before uploading their logs. I noticed a little too late, but thankfully this is an account I created for the bot.

**Comment by MattBSG** [comment]
I'm looking at the logs right now, but just for your peace of mind it only logs for debug issues, and spotify bearer tokens expire soon after creation (the expires_in key), fully invalidating them as you can see here: 
```
[2.4842541217803955] 2019-01-28 19:12:05,312 - DEBUG - musicbot.spotify | In spotify.py::MainThread(11040), line 74 in get_token: Created a new access token: {'access_token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxx', 'token_type': 'Bearer', 'expires_in': 3600, 'scope': '', 'expires_at': 1548735125}
```

**Comment by MattBSG** [comment]
I've confirmed your issue and we'll look into it, the *actual* exception thrown is actually a typo missing an arg. When I fixed that I realized another issue I'll get looked at. For now, you **can** play bandcamp albums through links formatted as subdomains to bandcamp such as: https://rushjet1.bandcamp.com/album/mega-man-3-remade

**Comment by prenetic** [comment]
Good to know, and thanks for the workaround for the time being! Appreciate all your help.

**Comment by MattBSG** [comment]
Pushed to review #1835
