### ISSUE TITLE
Skip autoplaylist when song is requested and queue is empty

### ISSUE THREAD

**Issue by aalhitennf** [Just-Some-Bots/MusicBot#1829]
- [ x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x ] The latest `master` version (1.9.8)

What type of issue are you creating?

- [ x] Feature request

----

Just a minor tweak that i think would be great. When adding song to playlist with !play while autoplaylist is playing, you have to wait for the current autoplaylist song to be over or skip it manually. I think bot should skip autoplaylist song automatically and start playing what user requested, or at least have option for this kind of behaviour.

**Comment by TheerapakG** [comment]
#1727
