### ISSUE TITLE
Bot won't start

### ISSUE THREAD

**Issue by ProfessorShroom** [Just-Some-Bots/MusicBot#183]
I'm not sure what's going on but one day the bot working and next it won't start, here's what comes up when I try to start it https://gyazo.com/bdd15e2bf71a97fb656d06c1ee879674

I've even tried re-downloading the bot and I get the same thing so I presume it's something to do with Python but I've already tried reinstalling that with no luck.

**Comment by imayhaveborkedit** [comment]
You're using review.  I'm in the middle of sorting the restart loop out in review, which is what you're seeing there.  Use rc7 for now.
