### ISSUE TITLE
I can`t  run my bot 

### ISSUE THREAD

**Issue by gwongibeom** [Just-Some-Bots/MusicBot#1832]
Please tick all applicable boxes.

- [O] I am using Python 3.5 or higher (run `python --version` on the command line)
- [O] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [O ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [O ] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [O] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
I try to run the bot and i get an error, I even tried to run as administrator as it says to do so, and it doesn't work. Im try run admin to 
( My English is very poor. sorry :/ )

### Steps to reproduce

1. 

----

### Log file
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "C:\Users\LG\Desktop\MusicBot\musicbot\__init__.py", line 7, in <module>
    from .utils import _get_variable
  File "C:\Users\LG\Desktop\MusicBot\musicbot\utils.py", line 3, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
[INFO] launcher: Attempting to install dependencies...
Collecting pynacl==1.2.1 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/28/44/577007ec0e7c05ebf667
9a1d8f98e53576b337c3e87af2619d9e249ff20b/PyNaCl-1.2.1-cp37-cp37m-win32.whl (158k
B)

[CRITICAL] launcher: You may need to run as admin to install dependencies.

[INFO] launcher: All done.

**Comment by AutumnClove** [comment]
`python -m pip install -U -r requirements.txt`

**Comment by k201gun** [comment]
> `python -m pip install -U -r requirements.txt`
