### ISSUE TITLE
AutoSummon not working

### ISSUE THREAD

**Issue by Quack6765** [Just-Some-Bots/MusicBot#1836]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8) The latest docker image
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
When setting the AutoSummon to yes, it's my understanding that when using !play the bot should automatically join my voice channel and start playing but this is not the case. I'm not sure if this is permission related or intented but my bot is admin in his role

### Steps to reproduce

1. Set AutoSummon to yes
2. !play something

----

### Log file
```
[ERROR:bot] Error in play: CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.
Traceback (most recent call last):
  File "/usr/src/musicbot/musicbot/bot.py", line 2672, in on_message
    handler_kwargs['player'] = await self.get_player(message.channel)
  File "/usr/src/musicbot/musicbot/bot.py", line 431, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channe
```

**Comment by AleanaA** [comment]
As the options file describes; `Automatically joins the owner's voice channel on startup, if possible.`

**Comment by TheerapakG** [comment]
AutoSummon option information excerpt from the option file:
Automatically joins the owner's voice channel **on startup**, if possible. The bot must be on
the same server and have permission to join the channel.

Tbh I think summon on play option would be a nice addition to the bot.

**Comment by Quack6765** [comment]
Thanks for the precision. I was under the impression that 'on startup' meant when queuing the first play. Like @TheerapakG mentioned, I think the auto summon on !play would be a good feature to add.

I'm not sure how to add a label to mark this as an improvement.

**Comment by TheerapakG** [comment]
In that case it would be duplicate of #837

**Comment by Quack6765** [comment]
Thanks will close this
