### ISSUE TITLE
After a little while running some people can't give it commands

### ISSUE THREAD

**Issue by iMxAndyy** [Just-Some-Bots/MusicBot#184]
So i run the bot and all is fine. After a while (sometimes a few minutes sometimes a few hours but its never not happened).
Some or all members stop being able to issue !play, !search, !pause, !resume or !skip commands to the bot. However !np, !queue and !volume still work. 
The bot starts spitting out this error whenever they try those commands:

"Traceback (most recent call last):
  File "C:\Users\andy-\Desktop\Music Bot\MusicBot-Current\musicbot\bot.py", line 1337, in on_message
    await self._check_ignore_non_voice(message)
  File "C:\Users\andy-\Desktop\Music Bot\MusicBot-Current\musicbot\bot.py", line 159, in _check_ignore_non_voice
    if not vc or vc == msg.author.voice_channel:
AttributeError: 'User' object has no attribute 'voice_channel'"

I've not looked into bot.py and i doubt very much i'd understand most of it if i did. 
But hopefully this gives you enough information to either see where i went wrong or fix whatever is wrong. 

I thought maybe something i did wrong with the permissions but i don't see how. 
Right now as i am writing this i have the bot doing this. One member (User A) is in the default group which was assigned by default, he his able to issue all of the commands he should be able to. While another member (User B) is also in the default group again assigned by default but he is not able to access to above listed commands. 

If any further info is needed to help with this issue feel free to ask.

**Comment by iMxAndyy** [comment]
Oh, Also i realize that in the error it mentions the like check_ignore_non_voice(message). 
Both User A and User B were in the voice channel with the bot.
And this problem has been something I've had happen for quite a few updates now.

**Comment by imayhaveborkedit** [comment]
The discord API was changed recently to change how data is sent to the clients on startup and discord.py hasn't been updated to deal with this properly yet.

**Comment by iMxAndyy** [comment]
I commented out the "IgnoreNonVoice =" list in the permissions file for now. 
It was just commands listed there that didn't work. Like the bot selectively didn't know if they were in the channel or not. So not requiring them to be seems to solve the issue for now. Just means people will be able to issue all commands from everywhere (not the end of the world)

**Comment by imayhaveborkedit** [comment]
discord.py has reconnecting now.
