### ISSUE TITLE
Code Language

### ISSUE THREAD

**Issue by SerenModz21** [Just-Some-Bots/MusicBot#1841]
can you make a js version of this please

**Comment by MattBSG** [comment]
That’s not how this works. We are python developers making a python bot. If you don’t want to use it, there are some alternatives. In any case, you can learn python (in the case you wanted to add a feature or change), find a bot made in js, or recreate it yourself in js (a very large undertaking!)

Sorry, however this is not on our roadmap nor will it be in the future as it would require a full rewrite.
