### ISSUE TITLE
[Feature request] Play video on bilibili.com

### ISSUE THREAD

**Issue by popeyaho001** [Just-Some-Bots/MusicBot#1843]
Just like the tittle, plz support bilibili.com
Just found python-bot can do that
https://github.com/criyle/bilibili_discord_bot
Thank you so much!

**Comment by TheerapakG** [comment]
YouTube-DL support bilibili. You should be able to pass bilibili URLs to the play command.

**Comment by popeyaho001** [comment]
I got this when pasting this link: https://www.bilibili.com/video/av7128767/?p=15
https://i.imgur.com/hiZhYkP.png

**Comment by TheerapakG** [comment]
rg3/youtube-dl#19233 fixed by https://github.com/rg3/youtube-dl/commit/c9a0ea6e51eff28b9a383a47215870fd5875fc3e
Run the update script.

**Comment by popeyaho001** [comment]
thank you, it works but seems can't play the playlist, always play the first track.

**Comment by TheerapakG** [comment]
Idk, I will probably test it on Friday.

**Comment by natsupy** [comment]
was fix this issue? seems only play 1 track in list

**Comment by TheerapakG** [comment]
Ytdl can only extract a track in the list. This seems to be a limitation of bilibili's api. I tried to read through the bilibili api documentation I found (which I can only found those in Chinese language) but I couldn't find anything related to playlist.

**Comment by jayktaylor** [comment]
This is something that should be taken up with youtube-dl, not us.
