### ISSUE TITLE
I can't run the bot

### ISSUE THREAD

**Issue by y3toripuru** [Just-Some-Bots/MusicBot#1847]
Please tick all applicable boxes.

- [x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [x] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x ] Question

----

I'm trying to run the bot, but every-time I try, It is not working. 

### Steps to reproduce

1. 

----

### Log file
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[CRITICAL] launcher: Bot wasn't installed using Git. Reinstall using http://bit.ly/musicbotdocs.
Press enter to continue . . .

**Comment by AleanaA** [comment]
Bot wasn't installed using Git. Reinstall using http://bit.ly/musicbotdocs

**Comment by y3toripuru** [comment]
How do I install using http://bit.ly/musicbotdocs. There's no install link

**Comment by AleanaA** [comment]
Read the guides provided on the left.

**Comment by y3toripuru** [comment]
It is now saying that 
fatal: destination path 'MusicBot' already exists and is not an empty directory.
what should I do?

**Comment by MattBSG** [comment]
It means you are trying to clone with git to a folder that already exists. Assuming you did not setup anything in the original bot, delete the old folder and try to reclone.

**Comment by y3toripuru** [comment]
I've already deleted the old files, but it is still showing me the same massage.

**Comment by AleanaA** [comment]
@y3toripuru Then you're probably using the wrong folder. Make sure you're not using a folder you got from extracting a zip file.

**Comment by y3toripuru** [comment]
Wait,so I downloaded a zip folder from git hub, but did I downloaded a wrong thing?

**Comment by TheerapakG** [comment]
You don't download zip folder. You need to follow instructions from the [link](http://bit.ly/musicbotdocs) given.

**Comment by y3toripuru** [comment]
Thanks so much. I was finally able to download it correctly

**Comment by y3toripuru** [comment]
But now, my bot won't play a music

**Comment by AutumnClove** [comment]
Please provide more information then "my bot won't play music", what's going on? What are you trying to play? Any errors in the console, have you checked that you're not deafend and the bot isn't muted? Have you tried disconnected, reconnecting, both you and the bot. Have you tried a simple `!restart`

**Comment by y3toripuru** [comment]
Thanks, I finally downloaded the bot correctly, but since it's prefix ! is same as MEE6, is there a way to change a prefix?

**Comment by AutumnClove** [comment]
https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_options.ini#L50

**Comment by y3toripuru** [comment]
Is there also a way to disable a playing... thing?

**Comment by AutumnClove** [comment]
https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_options.ini#L98

**Comment by y3toripuru** [comment]
When I start the bot.py file, it gonna just start, do something and close automatically, but my commands are not working why?

**Comment by AutumnClove** [comment]
I got an email about your last commit about the bot not working or something, are you still having issues?

**Comment by eDaMAmeeee** [comment]
hi, how do I change the command for help code?I want to change !help to !musichelp.

**Comment by AutumnClove** [comment]
Use the alias.json file

**Comment by MattBSG** [comment]
@eDaMAmeeee Please open a new issue next time as this is completely unrelated to your issue. Commands are based on the function name, modifying it’s name will change the command name. I recommend either changing your bot prefix in options if it’s because you are triggering others bots, or making an alias instead. See 
https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_aliases.json for syntax

**Comment by eDaMAmeeee** [comment]
I'm sorry about that and thanks for answering. By the way, there is no help on the alias.json.
