### ISSUE TITLE
Update.bat not running 

### ISSUE THREAD

**Issue by ar06x** [Just-Some-Bots/MusicBot#1848]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script 
Can't do this one...

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
Error in running update.bat

### Steps to reproduce

1.  Run update.bat

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

I don't have one... I tried to run update.bat and got an error, I did this a few days ago and it worked fine. I uninstalled it and installed it again, downloaded the correct version of python and everything, but now i can't even use the bot anymore.. so here is what happened.. 

Here Is the error 
---------------------
[Error running update.bat.TXT](https://github.com/Just-Some-Bots/MusicBot/files/2907705/Error.running.update.bat.TXT)

**Comment by TheerapakG** [comment]
cffi need a c++ compiler. You need to install the visual c++ build tools. You can download them here: https://visualstudio.microsoft.com/visual-cpp-build-tools/

Note that while the error is calling for vc++ 14.0 - everything will work with newer versions of visual c++.

**Comment by ar06x** [comment]
Thanks!
