### ISSUE TITLE
Multiple Instances on Raspbian

### ISSUE THREAD

**Issue by okidokay** [Just-Some-Bots/MusicBot#1849]
Please tick all applicable boxes.

- [x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x ] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x ] Question

----

### Description of issue

Is it possible to run more than one instance of MusicBot on raspbian? I want to have two separate bots on my discord server. I have tried just installing in a second folder with a different name, it won't run however.

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AutumnClove** [comment]
You'll need a second bot application, and a second token, but this should be possible if you have good enough specs.

**Comment by AleanaA** [comment]
Providing logs of 'it won't run' would be appreciated.

**Comment by okidokay** [comment]
I have it runnung now. I simply related it not running to me trying to run two instances, when really it was due to a mistake I made in the config file.
Sorry, my mistake.
