### ISSUE TITLE
Change Command

### ISSUE THREAD

**Issue by stanma9107** [Just-Some-Bots/MusicBot#1857]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----
Can I Change "summon" Command to "join"?
### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AutumnClove** [comment]
Use the newly added [alias file](https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_aliases.json) for this

**Comment by stanma9107** [comment]
> Use the newly added [alias file](https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_aliases.json) for this

I don't know how to do...
Can I say a little more

**Comment by AutumnClove** [comment]
It's pretty self explanatory if you look at the file. 
`"summon" : ["join"]`

**Comment by stanma9107** [comment]
ok 
thanks
