### ISSUE TITLE
Bot gone invisible...?

### ISSUE THREAD

**Issue by Bomberlux** [Just-Some-Bots/MusicBot#186]
I have no idea how to explain this, but basically, my bot joined my voice channel, but is seen as offiline. And if he indeed is show as online, the bot says it has a certain music paused, while it isn't the case at all... I have no idea what to do to fix this.

**Comment by imayhaveborkedit** [comment]
Don't trust the user list.  This issue appeared a few days ago.  When you kill the bot it doesn't disappear from the user list immediately.  Just ignore it for now.

**Comment by Bomberlux** [comment]
Alright, it's a bit disturbing not having the bot show up in the user list... Thanks for the quick reply
