### ISSUE TITLE
24/7 running bot not possible

### ISSUE THREAD

**Issue by Kenuux** [Just-Some-Bots/MusicBot#1861]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

After running the bot for a long time (maybe 12 hours) the bot is still online but it doesn't reconnect to it's channel.

### Steps to reproduce

1. Let the bot run 24/7

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

I don't have the exact log. But here's the error that I saved before restarting:

> Task exception was never retrieved
future: <Task finished coro=<ConnectionState._delay_ready() done, defined at /root/miniconda3/lib/python3.7/site-packages/discord/state.py:286> exception=AttributeError("'ConnectionState' object has no attribute '_ready_state'")>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/discord/state.py", line 302, in _delay_ready
    for guild, unavailable in self._ready_state.guilds:
AttributeError: 'ConnectionState' object has no attribute '_ready_state'

**Comment by TheerapakG** [comment]
Seems like this is a discord.py bug for me. The error seems to caused by what discord.py do internally.

**Comment by AutumnClove** [comment]
In agreement with thee, try running the update file, and make sure you're on the latest version of the bot.

**Comment by Kenuux** [comment]
Bot is already updated to the latest version. This time I got an different error:

> SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f9b680d88d0>
transport: <_SelectorSocketTransport fd=15 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/root/miniconda3/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/root/miniconda3/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2592)

**Comment by TheerapakG** [comment]
possibly https://github.com/aio-libs/aiohttp/issues/3535
It seems to be a bug that only affects aiohttp/asyncio in python 3.7. It doesn't seem like there is a fix currently.

**Comment by AutumnClove** [comment]
python: Having issues with python 3.6 or 3.7?
If you're having trouble using the bot, it's possible that an older version of python might help, and you can find the recommended downgrade version here:
https://www.python.org/ftp/python/3.5.4/python-3.5.4.exe

**Comment by G3VV** [comment]
I had mine running for 3 days, it then stopped responding, noticed it had a big error message and, well, we all know what happened next.

**Comment by amit177** [comment]
If this is still an issue, please retry in the latest version and let us know.
