### ISSUE TITLE
Autoplay enabled, but appears to play everywhere when only one server is occupied

### ISSUE THREAD

**Issue by nate2014jatc** [Just-Some-Bots/MusicBot#1862]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [X] Question

----

### Description of issue
While the bot is online, he is instructed to connect to two different Voice Channels and text channels, on two different 'servers.'

We have also enabled the "AutoPause" feature, and when both servers are empty, it functions as expected.

However, when one of the servers is empty, and the other has any number of members in the VC, the bot will appear to 
play music to both channels.

Is this a bug, or expected behavior?

### Steps to reproduce

1. Start bot
2. Have uneven server occupancy
3. Mystery Music on unoccupied channel
4. Profit?

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3020761/musicbot.log)

**Comment by AutumnClove** [comment]
Hello, due to the way discord works. The bot might appear to be playing audio, however if you join the channel, you should find that there's no mystery music.
