### ISSUE TITLE
is there anyway to remove this?

### ISSUE THREAD

**Issue by MysticWasTaken** [Just-Some-Bots/MusicBot#1863]
.

**Comment by AleanaA** [comment]
no

**Comment by ghost** [comment]
there also will never be a way of removing that without breaching the MIT license. Nor will we help you do so, anyways.

**Comment by ghost** [comment]
yes, but i don't think i have the right to tell how here

**Comment by ghost** [comment]
You don't.

**Comment by ghost** [comment]
that's what i thought
