### ISSUE TITLE
Bot not loading

### ISSUE THREAD

**Issue by jonathan651** [Just-Some-Bots/MusicBot#1864]
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[CRITICAL] launcher: Failed environment check, musicbot module is not importable
Press enter to continue . . .

**Comment by AutumnClove** [comment]
Run the update file

**Comment by jonathan651** [comment]
the update file says this:

Starting...
'git' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "update.py", line 40, in main
    subprocess.check_call('git --version', shell=True, stdout=subprocess.DEVNULL)
  File "C:\Users\Jonathan Haberman\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git --version' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update.py", line 76, in <module>
    main()
  File "update.py", line 42, in main
    raise EnvironmentError("Couldn't use Git on the CLI. You will need to run 'git pull' yourself.")
OSError: Couldn't use Git on the CLI. You will need to run 'git pull' yourself.

**Comment by AutumnClove** [comment]
Please ensure git is installed to your path

**Comment by jonathan651** [comment]
how do i do that?

**Comment by AutumnClove** [comment]
Follow the guides

**Comment by AutumnClove** [comment]
Follow the official guides

**Comment by jonathan651** [comment]
Sorry, but i cant find any

**Comment by AleanaA** [comment]
https://just-some-bots.github.io/MusicBot/

**Comment by AutumnClove** [comment]
https://just-some-bots.github.io/MusicBot/

**Comment by jonathan651** [comment]
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[CRITICAL] launcher: This version of MusicBot requires a newer version of discord.py (1.0+). Your version is 0.12.0. Try running update.py.
Press enter to continue . . .

I have ran update.py after that but it says the same thing.

**Comment by AutumnClove** [comment]
please run `python -m pip install -U -r --user requirements.txt` in the same prompt you get the error in

**Comment by jonathan651** [comment]
back to saying this
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[CRITICAL] launcher: Failed environment check, musicbot module is not importable

**Comment by AutumnClove** [comment]
Try update.bat if windows or else update.sh

**Comment by jonathan651** [comment]
update.bat says this:
Starting...
'git' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "update.py", line 40, in main
    subprocess.check_call('git --version', shell=True, stdout=subprocess.DEVNULL)
  File "C:\Users\Jonathan Haberman\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git --version' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update.py", line 76, in <module>
    main()
  File "update.py", line 42, in main
    raise EnvironmentError("Couldn't use Git on the CLI. You will need to run 'git pull' yourself.")
OSError: Couldn't use Git on the CLI. You will need to run 'git pull' yourself.

**Comment by jonathan651** [comment]
back to saying this again:
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[CRITICAL] launcher: This version of MusicBot requires a newer version of discord.py (1.0+). Your version is 0.12.0. Try running update.py.
Press enter to continue . . .

and 

update.bat says this:

Starting...
'git' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "update.py", line 40, in main
    subprocess.check_call('git --version', shell=True, stdout=subprocess.DEVNULL)
  File "C:\Users\Jonathan Haberman\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git --version' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update.py", line 76, in <module>
    main()
  File "update.py", line 42, in main
    raise EnvironmentError("Couldn't use Git on the CLI. You will need to run 'git pull' yourself.")
OSError: Couldn't use Git on the CLI. You will need to run 'git pull' yourself.

**Comment by AutumnClove** [comment]
You still haven't installed git... please use the official guides and start from scratch

**Comment by jonathan651** [comment]
![Help](https://user-images.githubusercontent.com/44928269/55445798-f7a2cc00-558a-11e9-9f10-f2cb23bc60a9.PNG)

Did I install the right git?

**Comment by AutumnClove** [comment]
Yes, but please make sure it's installed to path

**Comment by jonathan651** [comment]
What should I path the file to? maybe that could help,

**Comment by jonathan651** [comment]
I redid the process and it is still not working

**Comment by jonathan651** [comment]
Now it says this

[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "C:\Users\Jonathan Haberman\Desktop\New folder\MusicBot\musicbot\__init__.py", line 7, in <module>
    from .utils import _get_variable
  File "C:\Users\Jonathan Haberman\Desktop\New folder\MusicBot\musicbot\utils.py", line 3, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
[INFO] launcher: Attempting to install dependencies...
Collecting pynacl==1.2.1 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/28/44/577007ec0e7c05ebf6679a1d8f98e53576b337c3e87af2619d9e249ff20b/PyNaCl-1.2.1-cp37-cp37m-win32.whl
Collecting discord.py[voice] from git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice] (from -r requirements.txt (line 2))
  Cloning https://github.com/Rapptz/discord.py (to revision rewrite) to c:\users\jonath~1\appdata\local\temp\pip-install-e_2a5nub\discord.py
  Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/Rapptz/discord.py C:\Users\JONATH~1\AppData\Local\Temp\pip-install-e_2a5nub\discord.py
Cannot find command 'git' - do you have 'git' installed and in your PATH?
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

[CRITICAL] launcher: You may need to run as admin to install dependencies.

[INFO] launcher: All done.

C:\Users\Jonathan Haberman\Desktop\New folder\MusicBot>

**Comment by AutumnClove** [comment]
Any luck with this issue, try installing review. `git checkout review` and running update.py
