### ISSUE TITLE
Music bot joins channel but doesn't play audio and is not "connected"

### ISSUE THREAD

**Issue by dotsanguine** [Just-Some-Bots/MusicBot#1866]
Please tick all applicable boxes.

- [ x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ x ] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [ x ] Question

----

### Description of issue

I summoned the bot and it pops into my voice channel. However, upon trying to !play a song it says the bot isn't connected. I !summon one more time, and then it "connects." I tried to !play a song after and the bot says it's playing but there is no sound. 

### Steps to reproduce

1. Update the bot
2. Summon the bot onto the channel

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3056885/musicbot.log)

**Comment by wellivea1** [comment]
I am having the same issue but with the review branch.
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3057152/musicbot.log)

**Comment by AutumnClove** [comment]
Hello, this is an issue with discord.py wrapper, and is not an issue with a bot, a fix is already in place and will be pushed soon.

**Comment by TheerapakG** [comment]
Discord.py is fixed. Affected users could either run the update script or `python -m pip install -U discord.py[voice]` command to fix it.

**Comment by dotsanguine** [comment]
> Discord.py is fixed. Affected users could either run the update script or `python -m pip install -U discord.py[voice]` command to fix it.

Thank you so much for the replies. I ran the update script and the bot finally works again.
