### ISSUE TITLE
[Feature Request] User can delete own suggested song from queue

### ISSUE THREAD

**Issue by Loafabreadly** [Just-Some-Bots/MusicBot#187]
So I have some people in my servers accidentally pasting the wrong URL's when using the !play command and then they have to wait for it to become the current song and then skip.  

Let the user who suggests a song to be play be able to delete their suggestion from the queue. Something like !delete #inqueue

**Comment by imayhaveborkedit** [comment]
Yep yep, that'll be part of the better playlist controls/commands when I write playlists.

**Comment by Loafabreadly** [comment]
Awesome!
