### ISSUE TITLE
Can't play spotify playlist

### ISSUE THREAD

**Issue by pweedos** [Just-Some-Bots/MusicBot#1871]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Can't play spotify playlists.

### Steps to reproduce

1. Summon the bot
2. Play a playlist from spotify

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3065827/musicbot.log)

**Comment by AutumnClove** [comment]
Working fine for me, have you made sure your up to date with all the current dependencies

**Comment by pweedos** [comment]
I found why i was using the wrong url
