### ISSUE TITLE
Google play music support

### ISSUE THREAD

**Issue by hrtrd** [Just-Some-Bots/MusicBot#1872]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----
What about support google play music, its planned?

**Comment by AutumnClove** [comment]
The bot uses ytdl and as such supports nearly everything they support, [supported sites]( https://rg3.github.io/youtube-dl/supportedsites.html). If you want Google play music, I'd suggest opening an issue on their GitHub.

**Comment by hrtrd** [comment]
> The bot uses ytdl and as such supports nearly everything they support, [supported sites](https://rg3.github.io/youtube-dl/supportedsites.html). If you want Google play music, I'd suggest opening an issue on their GitHub.

but https://github.com/necroguemancer/google-play-discord-bot  or that https://github.com/BjoernPetersen/MusicBot

**Comment by AleanaA** [comment]
As previously stated, the bot uses yt-dl, and gets it's supported sites
from there. another bot supporting that is great, but we're not going to
redesign a major part of the bot to add google music functionality. as
previously mentioned, if you'd like to see google music, please open a
feature request with yt-dl.

**Comment by sarisia** [comment]
I implemented GPM playback feature based on this MusicBot it long before... but not maintained anymore.
At least it works now and I use it in my own server

https://github.com/sarisia/MusicBot

**Comment by AutumnClove** [comment]
Since this might be handled better by ytdl then us I'm closing.
