### ISSUE TITLE
Unable to play music after summoning

### ISSUE THREAD

**Issue by HaydenJM** [Just-Some-Bots/MusicBot#1873]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
After I've used the 'summon' command to made the bot join the channel I am in, I then go to use the 'play' command, and I get an error message telling me that I need to first use the 'summon' command to bring the bot into the same channel which it is already in..

### Steps to reproduce

1. Use the 'summon' command to make the bot join the same channel as yourself.
2. Use the 'play' command to attempt to play a song.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3071751/musicbot.log)

**Comment by TheerapakG** [comment]
Duplicate #1866

**Comment by HaydenJM** [comment]
> Duplicate #1866

Thank you very much. Sorry for wasting your time.
