### ISSUE TITLE
cant run the bot!

### ISSUE THREAD

**Issue by llh1187** [Just-Some-Bots/MusicBot#1878]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
look at the pic:
![捕获](https://user-images.githubusercontent.com/40154001/56076112-5f64dc80-5dff-11e9-9302-a3493934a27e.PNG)
the chinese means:Signal lamp timeout and time is up

### Steps to reproduce

1. i dont know~

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3075896/musicbot.log)

**Comment by AutumnClove** [comment]
Who's your host?

**Comment by llh1187** [comment]
u mean 'who is my master?' ?

**Comment by AutumnClove** [comment]
No like where is the bot being ran on

**Comment by llh1187** [comment]
when i ran the run.bat, something happened just like the pic i 've shown.

**Comment by llh1187** [comment]
win10 64bit

**Comment by AutumnClove** [comment]
It's a personal computer?

**Comment by llh1187** [comment]
yes, lenovo thinkpad e450, very old laptop.

**Comment by AutumnClove** [comment]
Ok, so, looking into this, I think the best option is to try a lower version of python I'd recommend 3.5.4

**Comment by llh1187** [comment]
thanks a lot, tomorrow morning i will have a try~

**Comment by llh1187** [comment]
I am sorry. My laptop now have python37, python 3.5.4, python2, and the way I run python3.5.4 is 'python35' , and I have replaced all 'python' to 'python35' in the 'run.bat'. But it doesn't work...
![image](https://user-images.githubusercontent.com/40154001/56095506-426bfe80-5f10-11e9-9cff-44841734a4ed.png)
just the same proplem. How can I Fix it?
I really need help~

**Comment by llh1187** [comment]
The way I run python3.5.4 just like this:
![image](https://user-images.githubusercontent.com/40154001/56095522-7a734180-5f10-11e9-8801-58023265519f.png)

**Comment by AutumnClove** [comment]
Install this: https://support.comodo.com/index.php?/Knowledgebase/Article/GetAttachment/969/821026.
Hopefully this will fix your issue.

**Comment by AutumnClove** [comment]
Closing assuming ssl cert fixed it, will reopen if problem consist.
