### ISSUE TITLE
No audio if starting the bot while in a voice channel

### ISSUE THREAD

**Issue by infinitepower18** [Just-Some-Bots/MusicBot#1885]
Please tick all applicable boxes.

* [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
* [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
* [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

* [x] The latest `master` version (1.9.8_4)
* [ ] The latest `review` version

What type of issue are you creating?

* [x] Bug
* [ ] Feature request
* [ ] Question

----

### Description of issue

When the bot process is terminated on the PC while it's in the voice channel, and if you try to start the bot again within the time Discord makes the bot status offline and removes the bot from the voice channel, the bot successfully rejoins the voice channel, but there is no audio coming out of it. To fix it, you need to disconnect and summon the bot again.

### Steps to reproduce

1. Terminate the bot process on the PC without using `shutdown` command.
2. Start the bot within the time Discord takes the bot offline and removes it from the voice channel.
3. Try to play a song.
4. No audio is output unless you disconnect and resummon the bot to the voice channel.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by Roadhog360** [comment]
This is a Discord issue, we can't fix this. Discord's voice implementation is weird, to say the least, and has 
occasional issues like this.
Resummoning (as you've done), rejoining the voice, or restarting again is really the only way around it.

**Comment by infinitepower18** [comment]
Isn’t it possible when the bot rejoins the channel on boot, it automatically disconnects from the VC and reconnects? Then this problem won’t occur.

**Comment by AutumnClove** [comment]
That seems a bit unnecessary, as this error doesn't happen all the time. I don't mean to be picky but doing that would take extra time we don't really need to use. As suggested the ideal solution is:
- Try `!restart` to restart the bot or `!disconnect` and then `!summon` to reconnect the bot.
- Try moving the bot to a new voice channel and then back, or using `!disconnect`, `!summon`, and then `!play your music`.
