### ISSUE TITLE
Auto summon using play command

### ISSUE THREAD

**Issue by infinitepower18** [Just-Some-Bots/MusicBot#1887]
Please tick all applicable boxes.

- [ ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8_4)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

### Description of issue

Please add an option for the bot to auto summon to the user's currently connected voice channel when using the `play` command, instead of having to do `summon` manually.

### Steps to reproduce

This is a feature request.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

This is a feature request.

**Comment by TheerapakG** [comment]
#1850
