### ISSUE TITLE
!perms User ID

### ISSUE THREAD

**Issue by infinitepower18** [Just-Some-Bots/MusicBot#1888]
Please tick all applicable boxes.

- [ ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.8_4)
- [x] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

### Description of issue

Allow to see perms of other users by using `!perms User ID`. Currently it only lets you check if you mention them.

### Steps to reproduce

This is a feature request.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

This is a feature request.

**Comment by AutumnClove** [comment]
Not for ID's but server nicknames, still useful and can probably be edited to work for id's as well side by side. 
```Suggestion
    async def cmd_perms(self, author, user_mentions, channel, guild, permissions):
        """
        Usage:
            {command_prefix}perms [@user]

        Sends the user a list of their permissions, or the permissions of the user specified.
        """

        lines = ['Command permissions in %s\n' % guild.name, '```', '```']

        if not user_mentions:
            stripped = len(self.config.command_prefix)+6
            int(stripped)
            ph = message.content[stripped:]
            str(ph)
            user = server.get_member_named(ph)
            if user == None:
                user = message.author
        else:
            user = user_mentions[0]

        permissions = self.permissions_for_user(user)

        for perm in permissions.__dict__:
            if perm in ['user_list'] or permissions.__dict__[perm] == set():
                continue

            lines.insert(len(lines) - 1, "%s: %s" % (perm, permissions.__dict__[perm]))

        await self.safe_send_message(author, '\n'.join(lines))
        return Response("\N{OPEN MAILBOX WITH RAISED FLAG}", delete_after=20)
