### ISSUE TITLE
[0;31mERROR:[0m This video is unavailable.

### ISSUE THREAD

**Issue by hddnninja** [Just-Some-Bots/MusicBot#1891]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
Bot does not play some playlists for some unknown reason. This is the error that pops up:

Error
[0;31mERROR:[0m This video is unavailable.

Just-Some-Bots/MusicBot (release-260419)

I've updated all dependencies and even tried uninstalling/reinstalling.

### Steps to reproduce

1. Play a playlist. (https://www.youtube.com/playlist?list=PLWVJCKVGEJYEzKeFXWCooAK5Nl4ALOZVJ) for example.
2. Wait for bot to queue in songs
3. Get error mentioned above.
4. No songs end up being played.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3133812/musicbot.log)

**Comment by TheerapakG** [comment]
#1860
