### ISSUE TITLE
Auto playlist won't go away

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1895]
Please tick all applicable boxes.

- [x ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x ] Bug
- [ ] Feature request
- [x ] Question

----

### Description of issue
I've installed the bot, and gone through the configuration steps listed on your site.  I've disabled the auto playlist, but as soon as the bot is summoned is starts playing a song anyways.  I do NOT want this feature as I'd rather the bot just play requested songs

### Steps to reproduce

1. Install bot, deps etc
2. go into config-rename example_options to options
3. edit, turn off autoplaylist and auto summon
4. when summoning bot into channel it immediately starts playing a song anyways, even without an active request.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AutumnClove** [comment]
This is probably persistent queue, try clearing your queue and using skip.

**Comment by ghost** [comment]
After some dicking around I just changed the code myself, thanks anyways man!
