### ISSUE TITLE
Musicbot is not outputting audio

### ISSUE THREAD

**Issue by nate2014jatc** [Just-Some-Bots/MusicBot#1897]
Please tick all applicable boxes.

- [ X ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ X ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ X ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ X ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ X ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
The bot appears to be playing music, and the logs suggest that he is doing so.
The "Speak Activity" indicator in Discord is also lit up, as if he were "speaking."
There is no sound coming from him, on any of the three servers he is present in.

A note that may be significant,
MusicBot is running as a Service on my Ubutnu 18.04 install.

### Steps to reproduce

1. Restart service `sudo systemctl restart bot.service`
2. Everything appears to load as it should.
3. The bot attaches to the channel and take commands properly.
4. Despite stating that there is a song playing, there is no sound.
(He is not locally muted, or server muted. We have tried turning up the volume)

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[bot.service.txt](https://github.com/Just-Some-Bots/MusicBot/files/3145113/bot.service.txt)
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3145114/musicbot.log)

**Comment by nate2014jatc** [comment]
Apparently running `!shutdown` fixed him?

**Comment by infinitepower18** [comment]
I reported this before and it's a Discord issue apparently. #1885
