### ISSUE TITLE
Cached Audio Files not Being Used, Redownloads Every Time

### ISSUE THREAD

**Issue by SoaringChris** [Just-Some-Bots/MusicBot#1908]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Despite caching songs new copies are downloaded every time a play is requested.

### Steps to reproduce
1. Ensure caching is enabled
2. Play a song
3. Skip it
4. Play it again
5. Observe that the console indicates that the song has been redownloaded.
----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3198909/musicbot.log)

**Comment by TheerapakG** [comment]
In the log it only shows that the player is using the cached file. "Download cache**d**" means that it is using cached file. If it output "Download started" and "Download completed" then it is really being download.
