### ISSUE TITLE
MIDI playback issues

### ISSUE THREAD

**Issue by dfault-user** [Just-Some-Bots/MusicBot#1909]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue

The current release of MusicBot currently cannot play MIDIs due to an error occurring inside of FFmpeg itself. I am unable to listen to onestop.midi for 24 hours straight due to this.

### Steps to reproduce

1. Upload a MIDI file to Discord.
2. Copy file link.
3. [prefix][play] [midi file]
4. ??
5. non profit!

----

### Log file
[musicbot.log](https://owo.sh/5Vs7H3b.txt)

**Comment by TheerapakG** [comment]
If ffmpeg can't read the file then we probably couldn't do anything about it.

**Comment by amit177** [comment]
Please open a new issue if this is still an issue you are experiencing in the latest version.
