### ISSUE TITLE
"Owner not found in a voice channel, could not autosummon"

### ISSUE THREAD

**Issue by WeeabooX** [Just-Some-Bots/MusicBot#191]
Can someone help me fix this issue? I am connected to the voice channel.

**Comment by Echoskope** [comment]
Do you see the bot listed as a user in the server?

**Comment by WeeabooX** [comment]
yes

**Comment by Echoskope** [comment]
In the the options.ini file, do you have your user ID listed as the bot owner?

**Comment by WeeabooX** [comment]
Thank you so much! I got it working! :)
