### ISSUE TITLE
Bot connected to Channel but console doesnt see it as connected

### ISSUE THREAD

**Issue by TakuyaSan420** [Just-Some-Bots/MusicBot#1910]
Please tick all applicable boxes.

- [ x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [ x] Question

----

### Description of issue

The bot is connected to the channel but in the console it says Attempting to join /VADN UNIVERSE/Ö3 . After about 15 seconds it says : [ERROR:bot] Failed to join VADN UNIVERSE/Ö3 even though its already connected to the channel

### Steps to reproduce

1. Start the Bot

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3218793/musicbot.log)

**Comment by AleanaA** [comment]
Host is Hetzner, and discord blocks them. Not an issue that we can solve.
