### ISSUE TITLE
Log in failed

### ISSUE THREAD

**Issue by jspain93** [Just-Some-Bots/MusicBot#192]
it keeps saying the log in information is wrong, ive changed the password a few times but it still wont work

**Comment by Echoskope** [comment]
Have you made sure you can log in via the discordapp website as the bot? When you put the login info under the options.ini after the ='s sign don't include anything but the info i.e. don't put "Abc@123" when your password is just Abc@123

**Comment by jspain93** [comment]
i dont have any extra things on there, and i can log in on the site just fine.

**Comment by Echoskope** [comment]
can you screenshot the error?

**Comment by jspain93** [comment]
raise LoginFailure('Improper credentials have been passed.')
discord.errors.LoginFailure: Improper credentials have been passed.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x015B6650>

**Comment by Echoskope** [comment]
Hmm only other thing I can think of is to erase your login creds from the options file and re-enter them. 
For reference it should look like this:

Username = my_bot_email@provider.com
Password = mYbOtpAsSwOrD1

**Comment by jspain93** [comment]
even though i have it like that still says its wrong i just changed the password again and i made sure there is no extra spaces or symbols

**Comment by Echoskope** [comment]
if you can log in as your bot via the discord website or the discord app you shouldn't need to keep changing the password. Double check your email address. If your email and password are correct somebody with a deeper understanding of why this would occur will have to step in. Sorry.

**Comment by arunesh90** [comment]
1) Don't use Notepad to edit your options,ini
2) Use Notepad++ to edit options.ini
3) Make sure that the email and password are bot on a seperate line:
Email = abc@example.com
Password = invalid.

**Comment by jspain93** [comment]
yup, thats how mine looks and i did use notepad++ i even tried changing accounts so idk what im doing wrong

**Comment by jspain93** [comment]
still trying to figure this out

**Comment by arunesh90** [comment]
https://discord.gg/0iqN3da4zqpDcBBN
hop on the server for more help

**Comment by jspain93** [comment]
i figured it out, the tutorial that the creator put up says it needs to be and ini file. but it needs to be a txt file

**Comment by link2110** [comment]
@jspain93 You are still using develop, update to the newest build. 

https://github.com/SexualRhinoceros/MusicBot/releases/tag/v1.9.5rc7

**Comment by MattBSG** [comment]
This ticket is done then
