### ISSUE TITLE
How to change what is bot doing?

### ISSUE THREAD

**Issue by Zero5G** [Just-Some-Bots/MusicBot#1920]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)

- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----
Hello this is not issue, but I dont know where I can ask this.
I want the bot say "Listening to", but I cannot find where I can change it.
Can someone tell me how?

**Comment by kdev** [comment]
Take a look in the config like [here](https://github.com/Just-Some-Bots/MusicBot/blob/0e353506f2b03ae1f7162ac55d3689f3a29ed6ef/config/example_options.ini#L146)

**Comment by AutumnClove** [comment]
There was a pull request but it was closed because it's more suited for a general purpose bot https://github.com/Just-Some-Bots/MusicBot/pull/1881
