### ISSUE TITLE
I dont know what I did wrong in configurating activity and status

### ISSUE THREAD

**Issue by Zero5G** [Just-Some-Bots/MusicBot#1921]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [x] Question

----

### Steps to reproduce

----

Hello I have followed this guide https://github.com/Just-Some-Bots/MusicBot/pull/1881/files.
But its sending me this bug can someone tell me what I did wrong?

----

[833.295106888] launcher-ERROR: Syntax error (this is a bug, not your fault)
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "D:\Discord\MusicBot\MusicBot\MusicBot\musicbot\__init__.py", line 74, in <module>
    from .bot import MusicBot
  File "D:\Discord\MusicBot\MusicBot\MusicBot\musicbot\bot.py", line 635
    async def update_now_playing_status(self, is_paused=False):
                                                              ^
IndentationError: unindent does not match any outer indentation level
[836.285591125] launcher-INFO: All done.

**Comment by AutumnClove** [comment]
As the pr was closed it's not supported but this is a tab issue either it's not lined up right or you used spaces instead of tabs
