### ISSUE TITLE
[Feature Request] Improve the help command

### ISSUE THREAD

**Issue by ar06x** [Just-Some-Bots/MusicBot#1923]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

**Comment by ar06x** [comment]
It would be much nicer if the help list was cleaner. Since sometimes it's not easy to spot some commands, people get confused of why there is not a command, but really they don't see the command do to the ugliness of the help list. 

It would be much easier to use the bot if the help list was clean, it would also be more enjoyable.

**Comment by AutumnClove** [comment]
Idk if it'll help but try #1856 out

**Comment by TheerapakG** [comment]
Those PR that are based on the cog PR should have help list that commands are divided into categories.

**Comment by BabyBoySnow** [comment]
Duplicate of #1613
