### ISSUE TITLE
Make the "play" command make the bot join the channel you are currently in

### ISSUE THREAD

**Issue by ar06x** [Just-Some-Bots/MusicBot#1924]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

**Comment by ar06x** [comment]
It would be nice to just do "!play <song>" and have the bot join the current voice channel you are in, instead of doing "!summon" then "!play <song>"

**Comment by TheerapakG** [comment]
#1850, #1915 / duplicate of #837
