### ISSUE TITLE
the __ini__.py is empty

### ISSUE THREAD

**Issue by roselanesan** [Just-Some-Bots/MusicBot#1925]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by roselanesan** [comment]
.

**Comment by AutumnClove** [comment]
Ini.py? Wot?

**Comment by TheerapakG** [comment]
If you're talking about the __init__.py, it is required by Python for that directory to be recognised as a regular package.

**Comment by TheerapakG** [comment]
If you're talking about the \_\_init\_\_.py, it is required by Python for that directory to be recognised as a regular package.
