### ISSUE TITLE
!search shows list of results at once rather than one at a time

### ISSUE THREAD

**Issue by Ozak93** [Just-Some-Bots/MusicBot#1929]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [x] Question

----

### Description of issue

Am just wondering if it's possible to make the !search function respond the same way[ Rythm bot does ?](https://rythmbot.co/assets/img/features/play-search.png)

i checked the configuration guide and there was no relevant search settings !

**Comment by AutumnClove** [comment]
It kinda already does? Just instead it's one at a time?

**Comment by Ozak93** [comment]
> It kinda already does? Just instead it's one at a time?

well. yes but to be honest Rythm's method is quicker and better, shows more results  aswell, while MB is limited to 3 options only, i don't know if there is an option to increase that cap aswell

**Comment by AutumnClove** [comment]
https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_permissions.ini#L111 for the limit

**Comment by Ozak93** [comment]
> https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_permissions.ini#L111 for the limit

thank you for that ! but it is 10 in both permissions.ini and example_permissions.ini,yet i only get 3 options.... sort of weird isn't it ?

**Comment by AutumnClove** [comment]
Put a number like `!search 10 x`

**Comment by Ozak93** [comment]
> Put a number like `!search 10 x`

Ok that worked thanks ! but isn't it possible to make it output the entire list and choose a song like [this](https://rythmbot.co/assets/img/features/play-search.png) ?
