### ISSUE TITLE
Bot will not pause on second server.

### ISSUE THREAD

**Issue by rrbailey89** [Just-Some-Bots/MusicBot#193]
I summon the bot like normal in the first server. Leave the first server (bot pauses) and enter the voice channel for a second server. Summon the bot there and then leave. The bot will not pause in the second server. 

http://goo.gl/LcISNi

Gif of the action.

**Comment by imayhaveborkedit** [comment]
The autopause code was never built for multiserver, so it won't work properly with that.  I'll fix that soon and add an option for it.

**Comment by rrbailey89** [comment]
Good to go. And thank you for your hard work.

**Comment by imayhaveborkedit** [comment]
This has been fixed (for a while).
