### ISSUE TITLE
Download is capped at 100 Kib/s

### ISSUE THREAD

**Issue by mojo123410** [Just-Some-Bots/MusicBot#1931]
Please tick all applicable boxes.

- [* ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ *] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ *] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [ *] The latest `review` version

What type of issue are you creating?

- [ *] Bug
- [ ] Feature request
- [ *
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3459327/musicbot.log)
] Question

----

### Description of issue
The bot can only download music at 100 Kib/s I have a 300 Mbps down connection

### Steps to reproduce

1.  Run the bot in a Ubuntu 18.04 LTS virtual machine with virtual box 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AutumnClove** [comment]
What brings you to this conclusion?

**Comment by mojo123410** [comment]
It takes forever for songs to load and when I look in the resources manager the only network traffic is from the bot and it never exceeds 100 Kib/s there is no bandwidth limit set on the VM so i dont think it has anything to do with that

**Comment by AutumnClove** [comment]
All your dependency are up to date and you're using Review?

**Comment by ar06x** [comment]
This happens to me too, even with the latest version and just using it directly off of windows 10 with no limit to how much bandwidth it can use

**Comment by AutumnClove** [comment]
[No problems here](http://prntscr.com/ovv3vn), although it seems that being low is normal, considering my bot takes ~18 seconds to process 15 songs. On 200Mbps internet 🤔

**Comment by AutumnClove** [comment]
Bad screenshot lol but yea my receive was 200 kbps so idk I think looking at that isn't very accurate, and instead see how fast it plays playlist. If you're still having issues Maybe you should join the [discord server](https://discordapp.com/invite/bots) and someone(probably me, I love doing it) can teamview with you and try to fix it.
