### ISSUE TITLE
not displaying song just _

### ISSUE THREAD

**Issue by shotty46290** [Just-Some-Bots/MusicBot#1934]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Assuming it is a bug, my bot used to say what was playing now all it says is playing: _. I have tried restarting the bot and that didn't help.

### Steps to reproduce

1. No idea, just used the bot as normal and at some point I realized it only showed _

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3466026/musicbot.log)

**Comment by TheerapakG** [comment]
Run the update script to update dependency (youtube-dl)

**Comment by shotty46290** [comment]
does the youtube-dl update that much? I have only had the bot installed for about 5-7 days. and it is showing correctly now

**Comment by AutumnClove** [comment]
Not usually, it's just coincidence
