### ISSUE TITLE
Activity

### ISSUE THREAD

**Issue by hrtrd** [Just-Some-Bots/MusicBot#1937]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

Hello!
How possible change activity  from PLAYING  to LISTENING?

**Comment by AutumnClove** [comment]
#1881
