### ISSUE TITLE
Error in line 367

### ISSUE THREAD

**Issue by B-Newt** [Just-Some-Bots/MusicBot#1939]
Please tick all applicable boxes.

- [. ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [. ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [. ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [. ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [. ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
I am getting an error when trying to run the .bat file 

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by B-Newt** [comment]
also, when i am trying to run the update.bat file its saying 'no module named pip'

**Comment by B-Newt** [comment]
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3519044/musicbot.log)

**Comment by B-Newt** [comment]
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "D:\MusicBot\musicbot\__init__.py", line 7, in <module>
    from .utils import _get_variable
  File "D:\MusicBot\musicbot\utils.py", line 3, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
[INFO] launcher: Attempting to install dependencies...
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "D:\MusicBot\musicbot\__init__.py", line 7, in <module>
    from .utils import _get_variable
  File "D:\MusicBot\musicbot\utils.py", line 3, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 388, in main
    err = PIP.run_install('--upgrade -r requirements.txt')
  File "run.py", line 83, in run_install
    return cls.run("install %s%s" % ('-q ' if quiet else '', cmd), check_output)
  File "run.py", line 36, in run
    raise RuntimeError("Could not import pip.")
RuntimeError: Could not import pip.

[INFO] launcher: All done.

**Comment by AutumnClove** [comment]
Try reinstalling python? It seems your missing pip.

**Comment by B-Newt** [comment]
i reinstalled, but now its saying python isnt added to my path

**Comment by AutumnClove** [comment]
When installing python there should be an option that says install to path make sure to click it, all the options you're supposed to do are said in our [guides](https://github.com/Just-Some-Bots/MusicBot/wiki)

**Comment by B-Newt** [comment]
okay so i got everything working up until the when it is about to start. I copy/pasted the options and inserted my bots token where it says to, yet it says bad credentials, cannot log in

**Comment by B-Newt** [comment]
nevermind, i got it to work thank you for the help
