### ISSUE TITLE
Will there be support for API bots?

### ISSUE THREAD

**Issue by Xarren** [Just-Some-Bots/MusicBot#194]
So I turned my bot (which was using an email and password) into an API bot (via Discord Application); however, it no longer is associated with the email and password I created my bot anymore. I was wondering whether in a future update, that the API bot will be able to be used to summon the MusicBot?

I apologize for my explanation of this as I am still new to the community and I am willing to learn more about this.

**Comment by imayhaveborkedit** [comment]
This already works in review, but I haven't finished converting everything that assumed single user server stuff yet, like status messages and autopause.

**Comment by Xarren** [comment]
Amazing! Thanks for the quick response!
