### ISSUE TITLE
discord music bot

### ISSUE THREAD

**Issue by kenny0912** [Just-Some-Bots/MusicBot#1943]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
cant play music at discord using bot
I set the token and owner id
how can i fix this
I already try run as admin
but this is what happens when I hit run
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

Starting MusicBot release-260819
Loaded autoplaylist with 2531 entries

Connected: 617657457837342750/初音ミク#0123
Owner: 476728233547792402/kenny0912#4571

Guild List:

Gaming Friends Club
happygayfriends
Not bound to any text channels
Not autojoining any voice channels

Found owner in "musics"
Attempting to join happygayfriends/musics
Joined happygayfriends/musics
Download started: https://youtube.com/watch?v=TKZUhs9Gcdo
Download complete: https://youtube.com/watch?v=TKZUhs9Gcdo
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at C:\Users\Long\Desktop\git\MusicBot\musicbot\player.py:259> exception=PermissionError(13, 'Access is denied', None, 5, None)>
Traceback (most recent call last):
File "C:\Users\Long\Desktop\git\MusicBot\musicbot\player.py", line 301, in _play
stderr=subprocess.PIPE
File "C:\Users\Long\AppData\Roaming\Python\Python37\site-packages\discord\player.py", line 164, in init
self._process = subprocess.Popen(args, stdin=stdin, stdout=subprocess.PIPE, stderr=stderr)
File "C:\Program Files\Python37\lib\subprocess.py", line 769, in init
restore_signals, start_new_session)
File "C:\Program Files\Python37\lib\subprocess.py", line 1172, in _execute_child
startupinfo)
PermissionError: [WinError 5] Access is denied

**Comment by AutumnClove** [comment]
Try running update.bat as admin

**Comment by kenny0912** [comment]
Description of issue
cant play music
Tried run both update.bat and run.bat by admin
still cant play music
help

Steps to reproduce
1.Running run.bat
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

Starting MusicBot release-260819
Loaded autoplaylist with 2530 entries

Connected: 617657457837342750/初音ミク#123
Owner: 476728233547792402/kenny0912#4571

Guild List:

Gaming Friends Club
happygayfriends
Not bound to any text channels
Not autojoining any voice channels

Found owner in "魔獸"
Attempting to join happygayfriends/魔獸
Joined happygayfriends/魔獸
ERROR: Content Warning
If the owner of this video has granted you access, please sign in.
This video is private.
[ERROR:bot] Error processing "https://youtube.com/watch?v=p0PlMNt02Ck": ERROR: Content Warning
If the owner of this video has granted you access, please sign in.
This video is private.
Removing unplayable song from session autoplaylist: https://youtube.com/watch?v=p0PlMNt02Ck
Updating autoplaylist
Download started: https://youtube.com/watch?v=hRK7PVJFbS8
Download complete: https://youtube.com/watch?v=hRK7PVJFbS8
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at D:\Music botttttttt\MusicBot\musicbot\player.py:259> exception=PermissionError(13, 'Access is denied', None, 5, None)>
Traceback (most recent call last):
File "D:\Music botttttttt\MusicBot\musicbot\player.py", line 301, in _play
stderr=subprocess.PIPE
File "C:\Users\Long\AppData\Roaming\Python\Python37\site-packages\discord\player.py", line 164, in init
self._process = subprocess.Popen(args, stdin=stdin, stdout=subprocess.PIPE, stderr=stderr)
File "D:\bot\lib\subprocess.py", line 775, in init
restore_signals, start_new_session)
File "D:\bot\lib\subprocess.py", line 1178, in _execute_child
startupinfo)
PermissionError: [WinError 5] Access is denied

run update.bat
Starting...
Passed Git checks...
Checking if we need to update the bot...
Already up to date.
Attempting to update dependencies...
Requirement already up-to-date: pynacl==1.2.1 in c:\users\long\appdata\roaming\python\python37\site-packages (from -r requirements.txt (line 1)) (1.2.1)
Requirement already up-to-date: discord.py[voice] in c:\users\long\appdata\roaming\python\python37\site-packages (from -r requirements.txt (line 2)) (1.2.3)
Requirement already up-to-date: pip in c:\users\long\appdata\roaming\python\python37\site-packages (from -r requirements.txt (line 3)) (19.2.3)
Requirement already up-to-date: youtube_dl in c:\users\long\appdata\roaming\python\python37\site-packages (from -r requirements.txt (line 4)) (2019.9.1)
Requirement already up-to-date: colorlog in c:\users\long\appdata\roaming\python\python37\site-packages (from -r requirements.txt (line 5)) (4.0.2)
Requirement already up-to-date: cffi in c:\users\long\appdata\roaming\python\python37\site-packages (from -r requirements.txt (line 6)) (1.12.3)
Requirement already satisfied, skipping upgrade: six in c:\users\long\appdata\roaming\python\python37\site-packages (from pynacl==1.2.1->-r requirements.txt (line 1)) (1.12.0)
Requirement already satisfied, skipping upgrade: websockets<7.0,>=6.0 in c:\users\long\appdata\roaming\python\python37\site-packages (from discord.py[voice]->-r requirements.txt (line 2)) (6.0)
Requirement already satisfied, skipping upgrade: aiohttp<3.6.0,>=3.3.0 in c:\users\long\appdata\roaming\python\python37\site-packages (from discord.py[voice]->-r requirements.txt (line 2)) (3.5.4)
Requirement already satisfied, skipping upgrade: colorama; sys_platform == "win32" in c:\users\long\appdata\roaming\python\python37\site-packages (from colorlog->-r requirements.txt (line 5)) (0.4.1)
Requirement already satisfied, skipping upgrade: pycparser in c:\users\long\appdata\roaming\python\python37\site-packages (from cffi->-r requirements.txt (line 6)) (2.19)
Requirement already satisfied, skipping upgrade: chardet<4.0,>=2.0 in c:\users\long\appdata\roaming\python\python37\site-packages (from aiohttp<3.6.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in c:\users\long\appdata\roaming\python\python37\site-packages (from aiohttp<3.6.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (3.0.1)
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.0 in c:\users\long\appdata\roaming\python\python37\site-packages (from aiohttp<3.6.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (4.5.2)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in c:\users\long\appdata\roaming\python\python37\site-packages (from aiohttp<3.6.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (1.3.0)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in c:\users\long\appdata\roaming\python\python37\site-packages (from aiohttp<3.6.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (19.1.0)
Requirement already satisfied, skipping upgrade: idna>=2.0 in c:\users\long\appdata\roaming\python\python37\site-packages (from yarl<2.0,>=1.0->aiohttp<3.6.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (2.8)
The current MusicBot version is release-260819.
Done!

**Comment by kenny0912** [comment]
I try to reinstall everything on C
And now the bot cant even join my voice channel
I am sure that i have give role and right to connect to the voice channel
it said this
Attempting to join Gaming Friends Club/Awesome Gaming Friends
[ERROR:bot] Failed to join Gaming Friends Club/Awesome Gaming Friends
