### ISSUE TITLE
youtube: HTTP Error 429: Too Many Requests/ Unable to extract video data

### ISSUE THREAD

**Issue by monstermatt2** [Just-Some-Bots/MusicBot#1947]
can no longer download videos using youtube-dl,  using a OVH server " Error
[0;31mERROR:[0m Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>)" 

how do i fix this?

screenshot below of the error in ubuntu terminal

https://i.imgur.com/dxfplmG.png

**Comment by TheerapakG** [comment]
![image](https://user-images.githubusercontent.com/11155914/71082157-37661e00-21c3-11ea-9c84-a2d4a3224d92.png)

**Comment by computergeek125** [comment]
so follow-up on this discussion- is there some sort of rate-limiting that could be done?  The problem sort of makes itself worse once it triggers since the bot then starts requesting a BUNCH of things in playlist order

**Comment by TheerapakG** [comment]
We can, but with the tradeoff of not being able to get title and duration of the entry until we chose to get it later. This behavior is one of the features implemented in #1973 (untested) which can be enabled as an option. It is not a solution though.

**Comment by fmohican** [comment]
We can't use google API to prevent ip blacklist?
