### ISSUE TITLE
Cannot play music anymore, restart command not working

### ISSUE THREAD

**Issue by RCambier** [Just-Some-Bots/MusicBot#195]
When using the command "!play", the bot now crashed with this error:

> Task exception was never retrieved
> future: <Task finished coro=<MusicPlayer._play() done, defined at /MusicBot-develop/musicbot/player.py:210> exception=TypeError("create_ffmpeg_player() got an unexpected keyword argument 'before_options'",)>
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
>     result = coro.send(None)
>   File "/MusicBot-develop/musicbot/player.py", line 241, in _play
>     after=lambda: self.loop.call_soon_threadsafe(self._playback_finished)
> TypeError: create_ffmpeg_player() got an unexpected keyword argument 'before_options'

Also, the restart command just make the bot leave but not come back. I have to ctrl+c the processus in the terminal then it will come back by itself.

Here is a quick example of what i mean: 

> [Command] 142634193996873728/BloodSkull (!restart)
> ^CCleaning up... Done.
> Connected!

(notice the ^C needed inbetween)

I'm not complaining here, just reporting errors I face, it's the best music bot !

**Comment by RCambier** [comment]
I needed to upgrade dependencies (using update_deps.bat).

**Comment by arunesh90** [comment]
1 thing if you stumble upon more errors, you're running a very outdated version.
Consider updating to RC7.
https://github.com/SexualRhinoceros/MusicBot/releases
