### ISSUE TITLE
Bot is not clearing Queue generated from Spotify

### ISSUE THREAD

**Issue by finia2NA** [Just-Some-Bots/MusicBot#1950]
Please tick all applicable boxes.

- [✔] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [✔] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [✔] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [✔] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [✔] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
after calling !play on a spotify playlist, then calling !clear, !queue says the queue has been cleared, but after calling !skip, the next song from the queue (which should have been deleted) starts playing.

Also, it says "<bot-name> is typing" the whole time anything is playing.

### Steps to reproduce
1. Start the bot
2. !play a spotify playlist (i used https://open.spotify.com/playlist/10Md6SiDnQQ6th3B6U5uUp?si=K24WK0wBSNSLXbaSOYknSw and https://open.spotify.com/playlist/5FmmxErJczcrEwIFGIviYo?si=JINHuMEuRS6gpBsItUH4eA)
3. !clear
4. !queue
5. !skip

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3682075/musicbot.log)

**Comment by k1m0ch1** [comment]
do you configure the spotify integration, or follow this https://just-some-bots.github.io/MusicBot/using/spotify/ section ?
the playlist/ track is it played by bot? mine is not played :/

I also have the same case :/, the bot is always "typing" and never resolve my track, he just play another audio, I don't know from where, but I disable the autoplaylist.

gotta figure this out.

**Comment by finia2NA** [comment]
Yeah, I generated the API token and inserted it into the config as described in the link.
Mine is playing the tracks just fine, it’s just not clearing the queue properly and always „typing“

**Comment by amit177** [comment]
What I think is happening is that the playlist's tracks are being added in the background.
By the time you execute `!clear`, it adds more tracks from the playlist.
This is not a bug
