### ISSUE TITLE
permission 

### ISSUE THREAD

**Issue by boyo33gaming2017** [Just-Some-Bots/MusicBot#1954]
I am trying to add my mate to be able to use permission as he cant like turn up the volume up or restart the bot with the commands but it wont let him do anything other than skip songs and play songs to here is the permission can anyone help [MusicMaster]
; GrantToRoles =578618650223706132
; UserList =578618650223706132
MaxSongLength = 10	
MaxSongs = 10
MaxPlaylistLength = 0
MaxSearchItems = 20
AllowPlaylists = yes
InstaSkip = yes
Remove = yes
SkipWhenAbsent = no
BypassKaraokeMode = yes
Extractors = 

and this is what it says 
578618650223706132/Colonel_Erax#4090: /volume 100
[ERROR:bot] Error in volume: PermissionsError: You don't have permission to use that command.
Reason: This command is not enabled for your group (Default).
Traceback (most recent call last):
  File "C:\Users\home\Desktop\discord bot\MusicBot\musicbot\bot.py", line 2788, in on_message
    expire_in=20)
musicbot.exceptions.PermissionsError: This command is not enabled for your group (Default).

**Comment by AleanaA** [comment]
Uncomment the lines by removing the `; ` from the start of the lines with id's
