### ISSUE TITLE
Song duration exceeds limit

### ISSUE THREAD

**Issue by JyoRyeong** [Just-Some-Bots/MusicBot#1955]
https://imgur.com/fJeGgrF

song duration exceeds limit (3795>1200)

how to fix 1200(seconds) to more than 3795 ?

im struggle on here any one help me pls ? :D

**Comment by JyoRyeong** [comment]
problem has been solved :P

**Comment by notyourbusiness9484** [comment]
Permissions.ini
MaxSongLength = 1200 change that
