### ISSUE TITLE
Youtube update

### ISSUE THREAD

**Issue by fsnaix** [Just-Some-Bots/MusicBot#1957]
Please tick all applicable boxes.

- [x ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
Youtube updated so all the bots have stopped working 

### Steps to reproduce

1. using the play commend 

----

### Log file
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at C:\Users\server\Desktop\Pantsumuisc\musicbot\player.py:259> exception=ClientException('Not connected to voice.')>
Traceback (most recent call last):
  File "C:\Users\server\Desktop\Pantsumuisc\musicbot\player.py", line 307, in _play
    self.voice_client.play(self._source, after=self._playback_finished)
  File "C:\Users\server\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\voice_client.py", line 363, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.

**Comment by vegeta897** [comment]
Playing from youtube still works for me.

**Comment by MattBSG** [comment]
Can you attach your full log file? That error doesn't have anything to do with your issue.

**Comment by Raspberrys3212** [comment]
As the Youtube operating policy changed, the bot didn't work and no logs were left.

**Comment by AleanaA** [comment]
@Raspberrys3212 Logs are left regardless of Youtube's policy, and can be found in the `logs` folder. This will have what Youtube returns in response to the request, and Youtube's policy will not cause no response to be given.

**Comment by Raspberrys3212** [comment]
[http://www.raspberrys.co.kr:7801/logs/](http://www.raspberrys.co.kr:7801/logs/)
This link is a log of the remaining Music Bots on my server.
Please check if there is any problem.

**Comment by AleanaA** [comment]
links to the logs returns a 404, nothing to check there.
if you have an issue, create a new issue regarding it including your log uploaded to github @Raspberrys3212

**Comment by neonoxd** [comment]
log doesn't show anything, bot just wouldn't do anything when the !play/!search command is issued. No errors just the bot doesn't respond to play command.

It responds to some other commands though like !help

**Comment by POPLOPUK** [comment]
Can confirm. No logs indicating any issues. No music playing. Youtube has changed something that broke the bot.
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3735893/musicbot.log)

**Comment by AleanaA** [comment]
@neonoxd Don't care if you don't think the log shows nothing or not, provide the log file else we've got nothing to go on to assist you
@POPLOPUK The bot's not running, install your dependencies and run it again

**Comment by neonoxd** [comment]
@AleanaA go on assist me.

[bot.log](https://github.com/Just-Some-Bots/MusicBot/files/3736039/bot.log)

**Comment by AleanaA** [comment]
@neonoxd Bot never joined the voice channel, hence the `Attempting to join` and not `Joined`.
See the announcements channel in the discord for more information regarding that issue.

**Comment by neonoxd** [comment]
ah nice, thanks!

**Comment by srhinos** [comment]
Looks like the issue was discovered. Closing this issue
