### ISSUE TITLE
The bot can't start

### ISSUE THREAD

**Issue by Greenglobin** [Just-Some-Bots/MusicBot#1958]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
the bot can't start and i have no idea why 

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3720661/musicbot.log)

**Comment by Mauher** [comment]
Same Problem here

**Comment by amit177** [comment]
If this is still an issue (I know, the reply is a bit delayed...)
Go to `%appdata%` --> `Python` --> `Python37` --> `site-packages`.
Delete the folder `youtube_dl` and run `update.bat`, that should fix the issue.
