### ISSUE TITLE
Error on Crash after running for two days

### ISSUE THREAD

**Issue by Loafabreadly** [Just-Some-Bots/MusicBot#196]
`Task was destroyed but it is pending!
task: <Task pending coro=<VoiceClient.keep_alive_handler() running at /usr/local/lib/python3.5/dist-packages/discord/voice_client.py:194> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.run() running at /usr/local/lib/python3.5/dist-packages/websockets/protocol.py:302> wait_for=<Future pending cb=[Task._wakeup()]>>
`

I get this error printed to my console, first time I noticed it crash entirely. I don't know who was doing what to the bot at the time but when I got home from work, this was the error and it was offline. If you need more info I can try to find it!

Running  Ubuntu 14.04.4 x64 512 MB Memory / 20 GB Disk Digital Ocean server

**Comment by imayhaveborkedit** [comment]
Discord went down earlier today, when that happens usually all the bots disconnect and crash.  There's no reconnect code in discord.py yet and the one I wrote is still in review.

**Comment by Loafabreadly** [comment]
Alright i thought it was a bot issue, thank you!
