### ISSUE TITLE
It appears to be blocked by the Youtube operating policy.

### ISSUE THREAD

**Issue by Raspberrys3212** [Just-Some-Bots/MusicBot#1961]
Please tick all applicable boxes.

- [ ✔ ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ ✔ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ✔ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ✔ ] The latest `master` version (release-260419)
- [  ] The latest `review` version

What type of issue are you creating?

- [  ] Bug
- [  ] Feature request
- [ ✔ ] Question

----

### Description of issue

This link is a log of the remaining Music Bots on my server.
Please check if there is any problem.

### Steps to reproduce

1. I used the play command but the bot didn't send any messages.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3729235/musicbot.log)

**Comment by AleanaA** [comment]
Issue is related to discord.py
Information regarding this issue can be found in the discord, and is not something we are able to resolve until discord.py is updated with the fix.
