### ISSUE TITLE
Bot stuck at Attempting to Join

### ISSUE THREAD

**Issue by Katevolution** [Just-Some-Bots/MusicBot#1962]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

For some reason, the bot will not "connect" to the voice channel. It does show as online and connected on the Discord though, just doesn't play sound or respond to music commands. It was working fine last night and nothing had changed since then other than turning off the PC for the night. It has all the proper Permissions on Discord in both Role Permissions and the Channel Permissions. Being on OneDrive isn't the issue, as I had uploaded it to OneDrive on one computer then launched it from OneDrive on the other (was not previously on the other before launch) and it worked. Will not join if launched from either computer and will not join if launched from the original location in the C: Drive.

### Steps to reproduce

1. Launch run.bat
2. Wait for it to complete and the bot shows as joined in the VC.
3. Connect to the VC.
4. Wait and nothing happens.
5. Run a queue command.
6. No response.
7. Change VC and run summon and it changes channels with no sound.
8. Run shutdown and it leaves.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3731193/musicbot.log)

**Comment by Katevolution** [comment]
Joined the support Discord and it seems to be a Discord issue. Guess it's time to play the waiting game.

**Comment by ken3b** [comment]
how long do you think it'll take for discord to fix this

**Comment by AleanaA** [comment]
@CaptCaboose See the announcements channel in the discord.
