### ISSUE TITLE
Bot doesn't respond to commands and thinks he's outside voice channel

### ISSUE THREAD

**Issue by gegtor** [Just-Some-Bots/MusicBot#1968]
- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

So about two days ago this issue started where i paused my bot for a night and the next day it wen't silent 

**!resume**
**!play**

Did nothing because bot thougt he's outside the voice channel 
Tried kicking him out of voice channel and rejoining and kicking him out of the server 

Then i tried to wipe the bot saving only configuration and that did nothing too

And after that bot stoped responding too only (!restart, !shutdown, !summon) worked

So i tried different OS's with it's config
Ubuntu 18.04
Ubuntu 16.04
and even macOS

Same behaviour 

Then i wiped bot's config and did clean install configuring only the bot's token

Same thing

Then i tried making new bot account resoulting in the same thing

So i upgraded all my packages and moved from python 3.5 to 3.7 and that did nothing too

I'm out of ideas what could go wrong and what i could troubleshoot next 

I'm not including bot's log because it contains nothing usefull (no errors no nothing) just bot not responding to my commands and standard startup messages

**Comment by Abel-Arias** [comment]
I've encoutered the same issue these last days, could be about a week or so.

I'm on raspbian, last master version of MusicBot, all dependencies updated.

The bot responds to commands that aren't related to the queue (!summon, !clean, !help, !perms, etc. working fine) but doesn't play anything and won't add nor remove songs from the playlist/queue.

Log doesn't show any kind of error, it just logs the "!play" messages and such.

**Comment by crichton32** [comment]
I've had this issue for the past couple of days as well. There was a new update today (10/17) that seems to have fixed it for me.

**Comment by Abel-Arias** [comment]
The update does indeed seem to solve this issue, it's fixed for me.

**Comment by AleanaA** [comment]
Duplicate of #1962
