### ISSUE TITLE
Will it ever be possible to customize/change the output from the music bot?

### ISSUE THREAD

**Issue by atticusdungeon** [Just-Some-Bots/MusicBot#197]
for example instead of saying "User, your song "song name" is now playing in "voice channel", we could personalize it to say anything.

For all things the bot outputs as well, not just my example.

If this is possible by editing the code, which files would I need to change?

Thank you! (Love the bot btw, our who channel loves it)

**Comment by Echoskope** [comment]
What I've done is edit bot.py and look for "cmd_" prefixes to the commands. I looked at "cmd_help" for an example since it only returns a text block.

**Comment by imayhaveborkedit** [comment]
At some point I'm going to create a sort of "responses" file where you can change what the bot says and if/when it gets deleted, etc.
