### ISSUE TITLE
I got a new pc and would like to use my old bot

### ISSUE THREAD

**Issue by LuxCromwell** [Just-Some-Bots/MusicBot#1972]
Please tick all applicable boxes.

- [x ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [ x] Question

----

### Description of issue
I just got a new pc and downloaded my old files off of my google drive but they don't work is there any way to fix this?

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3766118/musicbot.log)

**Comment by Roadhog360** [comment]
You will need to follow the guide to set-up the bot again. Once you have the bot cloned again and you're at the configuration step, you can simply copy all of your configs over. 
If you need a link to the guide, you can follow it here: https://just-some-bots.github.io/MusicBot/
