### ISSUE TITLE
dockerfile appears to have an inconsistent python setup

### ISSUE THREAD

**Issue by carycodes** [Just-Some-Bots/MusicBot#1974]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Dockerfile attempts to install incompatible Python components, resulting in a non-working image.

### Steps to reproduce

1. clone repository `git clone https://...`
2. build a docker image `docker build -t musicbot .`
3. attempt to run docker container `docker run musicbot`

Expected: musicbot runs
Observed: python exception on startup:

```
Traceback (most recent call last):
  File "run.py", line 438, in <module>
    main()
  File "run.py", line 345, in main
    sanity_checks()
  File "run.py", line 206, in sanity_checks
    req_check_deps()
  File "run.py", line 268, in req_check_deps
    import discord
  File "/usr/lib/python3.7/site-packages/discord/__init__.py", line 23, in <module>
    from .client import Client
  File "/usr/lib/python3.7/site-packages/discord/client.py", line 35, in <module>
    import websockets
  File "/usr/lib/python3.7/site-packages/websockets/__init__.py", line 3, in <module>
    from .client import *
  File "/usr/lib/python3.7/site-packages/websockets/client.py", line 20, in <module>
    from .protocol import WebSocketCommonProtocol
  File "/usr/lib/python3.7/site-packages/websockets/protocol.py", line 18, in <module>
    from .compatibility import asyncio_ensure_future
  File "/usr/lib/python3.7/site-packages/websockets/compatibility.py", line 15
    asyncio_ensure_future = asyncio.async           # Python < 3.5
```

Further observations: 

1. The dockerfile explicitly installs version 4.0.1 of websockets, which is sort of ancient and not compatible with Python 3.7 and the async keyword.  Removing this line and letting pip have whatever version of websockets it naturally wants fixes the bug and lets musicbot work as expected.

2. Theorizing why this happened: the dockerfile uses `alpine:edge` as a base.  That seems needlessly reckless.  Perhaps the version of Python included with `alpine:edge` changed at some point, resulting in this problem?  Not sure but regardless, I strongly recommend pinning a version like 3.10.  At the very least stick with `latest`.  Using `edge` is just asking for trouble.

3. Is the dockerfile not a recommended way of running musicbot?  I was surprised to not see a guide for that.  Biased opinion: docker is a superior way of running this than native on most platforms.

**Comment by TheerapakG** [comment]
I do agree that docker needs some love but I haven't really used docker for this thing for a long time now. I have an unofficial guide for running MusicBot on docker but that was what I have written a year ago. I haven't touched the Dockerfile but I have pushed stuff related to docker into this in the past and I'm not sure why it is using `edge` either (and I still am), but (seems like at that point) I decided to leave it be.

(edit)
`docker run -it musicbot -update` can update python dependencies using requirements.txt. This is not a solution but should solve the issue.

**Comment by rwky** [comment]
This is what I'm using as the docker run command to work around this:

`/usr/bin/docker run --net musicbot --rm --name musicbot -v /srv/musicbot:/usr/src/musicbot/config --entrypoint=/bin/sh justsomebots/musicbot:release-260819 -c 'pip3 install --upgrade websockets && python3 dockerentry.py'`

**Comment by thunderlight411** [comment]
After some searching it learns me that alpine:edge does not have any older python version available.
I have build a docker myself by using ubuntu:18.04 and that seems to work correctly.
Only need to put all of them in a new dockerfile so it can be made automaticly

**Comment by thunderlight411** [comment]
If you like to have a working docker you can use the one with this build.
or you can download : https://hub.docker.com/r/marcoonline/musicbot
There is just 1 extra option added and that placing the folder audio_cache outside the docker to prevent redownload a track if you want to flush / upgrade your docker
