### ISSUE TITLE
Stops playing after Copyright issue

### ISSUE THREAD

**Issue by LordOsslor** [Just-Some-Bots/MusicBot#198]
#101  Germany, there is the GEMA (They do the whole copyright thing). If the GEMA says, "you're not allowed to hear that" , the Bot freeses and you have to !play an other video (the Autoplay doesn't work)

File is locked
ERROR: J91ti_MpdHA: YouTube said: Unfortunately, this video is not available in your country because it could contain music, for which we could not agree on conditions of use with GEMA.
Task exception was never retrieved

I hope, you are going to fix it soon ;D

**Comment by imayhaveborkedit** [comment]
These kinds of errors aren't new.  Youtube videos have a bunch of other errors like this, like removed for copyright strikes, video unavailable, etc.  The bot shouldn't break when it hits one of these, but something else might have gone wrong that you didn't post.
