### ISSUE TITLE
Why is my bot not starting

### ISSUE THREAD

**Issue by DestinyofYeet** [Just-Some-Bots/MusicBot#1985]
Please tick all applicable boxes.

- [✓] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [✓] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [✓] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [✓] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [ ✓] Question

----

### Description of issue

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
Traceback (most recent call last):
  File "run.py", line 438, in <module>
    main()
  File "run.py", line 347, in main
    finalize_logging()
  File "run.py", line 179, in finalize_logging
    dlh.setFormatter(logging.Formatter('.'))
  File "C:\Python\Python38\lib\logging\__init__.py", line 576, in __init__
    self._style.validate()
  File "C:\Python\Python38\lib\logging\__init__.py", line 429, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '.' for '%' style

### Steps to reproduce

1. I started the run.bat script
----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3827772/musicbot.log)

**Comment by TheerapakG** [comment]
You are using Python 3.8, which is not supported yet (#1969). Use any Python within the version 3.5.4 - 3.7 instead.

**Comment by DestinyofYeet** [comment]
thank you

**Comment by bobi32** [comment]
Should not be closed until fixed in master.

**Comment by AleanaA** [comment]
@bobi32 The issue is resolved in review, this has no impact on the bot aside that py3.8 is not supported on the master branch, thus the issue can remain closed.
