### ISSUE TITLE
Bot disconnects but no error message given

### ISSUE THREAD

**Issue by Bomberlux** [Just-Some-Bots/MusicBot#199]
Sometimes, I'm playing some games or just watching some videos, and when I check my discord server, I realize that the bot disconnected, but I still have the command window open. I open it, to see if I have any error messages on it, but nothing. It's like, nothing happened, but the bot still disappeared.

**Comment by Echoskope** [comment]
Are you hosting the bot locally on your machine? Could it be your internet doesn't support enough bandwidth for the bot plus other activities causing the bot to disconnect?

**Comment by imayhaveborkedit** [comment]
Stop giving bad advice please.  Bandwidth is very rarely relevant, unless you have very bad internet to begin with, in which case you should probably know that you shouldn't really be hosting a music bot.  The disconnect you noticed was probably something that happened earlier.  Something happened with cloudflare and bots DC'd from discord.  There's reconnect logic in the review branch and the library doesn't have reconnect logic built in yet.  It's also not hard to write a little batch/sh loop to rerun the bot when it crashes.

**Comment by junhui-f** [comment]
Had the bot crash multiple times recently with errors similar to #196 . Swapped out "screen" for "supervisor" to restart the bot when it crashes, hope it works.

**Comment by deansheather** [comment]
### **`pm2` master race...**

https://pm2.keymetrics.io/

**Comment by Cryzin** [comment]
@imayhaveborkedit This is what I get as the error

http://i.imgur.com/0JWyGPf.png
