### ISSUE TITLE
Errors with spotify playlists

### ISSUE THREAD

**Issue by rwilliams** [Just-Some-Bots/MusicBot#2000]
Please tick all applicable boxes.

- [✔] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [✔] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [✔] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [✔] The latest `master` version (release-260419)

What type of issue are you creating?

- [✔] Bug

----

### Description of issue
![image](https://user-images.githubusercontent.com/29144/70574511-1f562500-1b59-11ea-82fa-19a38a54187d.png) 

It was working fine a few days ago with the same playlist. I'm not sure what changed.

### Steps to reproduce

1.  !play spotify:playlist:37i9dQZF1E4mmDxZR2bY1X

----

### Log file

I'll re add the log file soon i need to redact it a bit apparently.
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3947594/musicbot.log)

**Comment by azcoigreach** [comment]
I am receiving these errors as well.  You have trigger YouTube into thinking you are a bot, it is expecting a captcha.  I believe this is the same API change that is affecting the other Music Bots.

**Comment by rwilliams** [comment]
@azcoigreach How do you make YouTube think you're a bot?

**Comment by rwilliams** [comment]
For others

> 

RH1-N0 BOT Today at 4:36 AM
YouTube has suddenly started fighting against ripping services and music bots, and is banning VPS services and machines that generate a large number of traffic. If you are affected, this means your bot won't be able to interact with YouTube or pick up any songs or their info. If your bot is affected, you might be seeing it start producing one of two errors:
YouTube said: 429: Too many requests
or Unable to extract video data
The latter isn't guaranteed to be the issue though, to confirm you have been blocked, open CMD or your terminal, and type `youtube-dl (any video url here)
`

**What can I do about this?**
Unfortunately, this is a tricky situation, and there isn't much that can be done without a lot of work. If your hosts allow using multiple IPs, you should try making your machine use one of the alternate IPs to see if YouTube banned the whole host service you're using, or just one single IP.
Another way around this would be using a VPN service, but there's a chance that YouTube could have blocked some VPN services too. A VPN could be slow, and might stunt download speeds, but if it's your only option, it's better than nothing.
Another bypass could be moving to another host, but nothing stops YouTube from blocking a new host that you've switched to.
However, one thing to note is that not all of these YouTube blocks are permanent. Some might be temporary. To see if your IP can be unblocked, simply leave the bot off, or don't use that IP for a few days. Then, try using the bot after that wait. If it works, your block was temporary and you can continue using the bot after this time.
```

**Comment by rwilliams** [comment]
Closing this as it's a youtube throttling issue not a Musicbot issue.
