### ISSUE TITLE
Unable To Extract REALLY ANNOYING

### ISSUE THREAD

**Issue by timmy-time** [Just-Some-Bots/MusicBot#2006]
Please tick all applicable boxes.

- [x ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Im getting unable to extract issue And how can i fix it?

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.txt](https://github.com/Just-Some-Bots/MusicBot/files/4038898/musicbot.txt)

**Comment by AleanaA** [comment]
see #1947
