### ISSUE TITLE
Alguien Me Ayuda A Crear Un Bot

### ISSUE THREAD

**Issue by vladimir1212b** [Just-Some-Bots/MusicBot#2013]
Mi Discord es vladimir12#4602 es para un servidor Gracias.
Ah y el Bot que dice BOB ese es uno que me dio alguien que me ayuda con los comandos aun que nose como modificarlo aun que si pueden ayudenme ok? Gracias
![Screenshot_1](https://user-images.githubusercontent.com/57573360/74886994-6716db00-5358-11ea-95f8-08969f5a0dd1.png)

**Comment by amit177** [comment]
Issues must be in English and follow the template.
