### ISSUE TITLE
Bot won't launch using Python 3.8

### ISSUE THREAD

**Issue by c4nzin** [Just-Some-Bots/MusicBot#2015]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x ] run.bat not working
- [ ] Question

----

### Description of issue

when i hit run.bat shows error message 

----
ERROR MESSAGE:
### Log file
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
Traceback (most recent call last):
  File "run.py", line 438, in <module>
    main()
  File "run.py", line 347, in main
    finalize_logging()
  File "run.py", line 179, in finalize_logging
    dlh.setFormatter(logging.Formatter('.'))
  File "C:\Users\Can\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 576, in __init__
    self._style.validate()
  File "C:\Users\Can\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 429, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '.' for '%' style

C:\Users\Can\Desktop\Apps\Bot\MusicBot>

**Comment by AleanaA** [comment]
Python 3.8 is not supported at the moment in the master branch, use Python with a version between Python 3.5.3 and Python 3.7, or alternatively, use the review branch.
