### ISSUE TITLE
[Feature Request] Add an option for the bot to say something periodically

### ISSUE THREAD

**Issue by iMxAndyy** [Just-Some-Bots/MusicBot#202]
The way i imagine this working would be there would be another commented out option or two in the config by default. Something like ";Auto speech = " and ";Auto speech frequency = "

What this would do is every so often the bot just outputs whatever you enter in the auto speech option. 

Ideally used for giving users rules or help because at present there is no real way to give people information. 
Ideally it would allow formatting like \n for line breaks and so on.

**Comment by lauriys** [comment]
that doesn't really make sense for a _music bot_

**Comment by imayhaveborkedit** [comment]
Yeah uh... no.
