### ISSUE TITLE
Allow Dev group to use restart command

### ISSUE THREAD

**Issue by RickeyJLancaster** [Just-Some-Bots/MusicBot#2021]
Please tick all applicable boxes.

- [✔️] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [✔️] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [✔️] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [✔️] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [✔️] Feature request
- [ ] Question

### Description of issue

Devs should be able to restart the bot to apply changes in the files, also, in my server the bot isn't stable, after some time online it stop reproducing the songs and need to be restarted to work again.
Dev Group could be able to use the command as default or this could be a option in options.ini

### Steps to reproduce

NaN

----

### Log file

NaN

**Comment by Jcodeerd** [comment]
you can edit this in the permissions.ini file
