### ISSUE TITLE
can't run, config is correct

### ISSUE THREAD

**Issue by 0t4u** [Just-Some-Bots/MusicBot#2022]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
Cant run, python version 3.7.0, logs:
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "/Users/---/Desktop/MusicBot/musicbot/__init__.py", line 74, in <module>
    from .bot import MusicBot
  File "/Users/---/Desktop/MusicBot/musicbot/bot.py", line 45, in <module>
    load_opus_lib()
  File "/Users/---/Desktop/MusicBot/musicbot/opus_loader.py", line 8, in load_opus_lib
    opus._load_default()
AttributeError: module 'discord.opus' has no attribute '_load_default'

[INFO] launcher: All done.

### Steps to reproduce

1. type in terminal (already cd to folder) python3.7 run.py

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by adopting** [comment]
this happened to me. just upgrade discord.py. if you are on linux use: pip3 install --upgrade discord.py
windows: pip install --upgrade discord.py
