### ISSUE TITLE
Blacklist does not work

### ISSUE THREAD

**Issue by LypticZ** [Just-Some-Bots/MusicBot#2028]
Please tick all applicable boxes.

- [ ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
If I blacklist a URL from a YouTube video and then restart the bot, another user can still play that video.

### Steps to reproduce

1. Adding video to blacklist.
2. Restarting the bot.
3. User still can play it.

----

### Log file
https://pasting.ml/url/7ri3YS2

**Comment by AleanaA** [comment]
There's no video blacklist, what you may be referring to is the command blacklist in the permissions file.
