### ISSUE TITLE
Http error 403: Forbidden

### ISSUE THREAD

**Issue by yinkiu602** [Just-Some-Bots/MusicBot#2031]
Please tick all applicable boxes.

 [✓ ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
 [✓ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
 [✓ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

 [✓ ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

 [✓ ] Bug
 [✓ ] Feature request
- [ ] Question

----

### Description of issue
If i asked the bot to play a music from youtube that are age restricted, the bot will print HTTP 403 error on the console.

### Steps to reproduce

1.  Find a youtube video that are age restricted.
2.  Try to ask the bot to play that video

----

### Feature requests
Is it able to add a option for me too add google account, and so bypass the age restriction thing? Thanks

**Comment by AleanaA** [comment]
ytdl-org/youtube-dl#22188 is relevant to this issue, at this time there's no way to add an account to bypass age restriction

**Comment by yinkiu602** [comment]
Ok, thanks for your help :)
