### ISSUE TITLE
TypeError: 'in <string>' requires string as left operand, not int

### ISSUE THREAD

**Issue by kulpsin** [Just-Some-Bots/MusicBot#2039]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (release-260819-4-gf7d0d74)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

```
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/home/discord/.local/lib/python3.6/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "/opt/discord/MusicBot/musicbot/bot.py", line 2661, in on_message
    if message.author.bot and message.author.id not in self.config.bot_exception_ids:
TypeError: 'in <string>' requires string as left operand, not int
```
The `self.config.bot_exception_ids` is an empty string (no BotExceptionIDs defined) and `message.author.id`is an int. Basically the error happens when program tries to evaluate boolean of `1234 in ""`. Not sure if the intention was to evaluate `1234 in []` (empty list instead of string) or `"1234" in ""` (id as string instead of int), but both should work.

### Steps to reproduce

1. Keep bot running and periodically this error pops up. On options.ini I have the `BotExceptionIDs =
` as in example: no entries.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
Restarted bot a few times, so logs are lost. I'll post 'em when issue pops up again if needed.

**Comment by amit177** [comment]
Make sure you don't have any spaces in there
