### ISSUE TITLE
''The bot is not in a voice channel.''

### ISSUE THREAD

**Issue by ChipFlexes** [Just-Some-Bots/MusicBot#204]
Whenever I try to play a song the bot says: ''_The bot is not in a voice channel.  Use !summon to summon it to your voice channel._'' But the bot is clearly in the same voice channel as me. https://gyazo.com/f8a8ac511331b440d58a4216b1abdb3c (DixBot being the bot)
- Anyone that can help me?
  
  https://gyazo.com/4205d8806a292ea348a8430ba7fb2cc2

**Comment by Echoskope** [comment]
Had same problem; I just logged into the discord web interface and manually left the channel then did !summon again from my main account and it fixed itself.

**Comment by ChipFlexes** [comment]
It didn't work for me... Maybe I'm missing a step? - Try to tell me more exactly :)

**Comment by Echoskope** [comment]
Sorry I forgot to mention that when you log into discord as the bot you have to join the voice channel where it is currently "stuck" and then disconnect (so you no longer see the bot in the voice channel) before issuing the !summon command again from your other account. If that didn't work does the bot auto join the voice channel when you restart the script?

**Comment by ChipFlexes** [comment]
Thank you, man! It worked! :)

**Comment by banegaming** [comment]
Hey, Guy's I have the same problem, what did you did to fix it?

**Comment by GWolv** [comment]
How do you login as the bot?
I know that you use the bot token as the password, but what do you use as the email?
