### ISSUE TITLE
How to disable youtube playlist links

### ISSUE THREAD

**Issue by kevzettler** [Just-Some-Bots/MusicBot#2042]
Our chat members keep accidentally copy/pasting Youtube playlist links when they want an individual song which causes the bot to queue up all songs in the play list. Some times they will copy paste multiple urls form the play list causing bot to queue up the full play list multiple times

**Comment by AutumnClove** [comment]
You can change allowplaylist in the permissions file, or tell your members to use individual song links instead of ones from a playlist or have them take off the `&list=blahblahblah`
