### ISSUE TITLE
How to force bot to to finish autoplay and go to queue?

### ISSUE THREAD

**Issue by VladoCC** [Just-Some-Bots/MusicBot#2043]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue

I can't understand how to force bot to stop playing autoplaylist.
I want it to play autoplaylist after summon, but I can't find any command to force bot to play queue.

### Steps to reproduce

1. Setup bot.
2. !play anything
3. It's in queue, but it will be played only after autplaylist and that is sad ;'(

----

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4420084/musicbot.log)

**Comment by AleanaA** [comment]
`!skip`
