### ISSUE TITLE
Feature Request: More Custom Status

### ISSUE THREAD

**Issue by MainMusicDeveloper** [Just-Some-Bots/MusicBot#2045]
Please tick all applicable boxes.

- [y ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [y ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [y ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [y ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ y] Feature request
- [ ] Question

----

### Description of issue

You should add more custom status for the Music Bot. That would be awesome if we could set to "Listening to [something]" or "Watching [something]".

### Steps to reproduce

1. 

----

**Comment by AutumnClove** [comment]
I pr'ed something like this but it was denied.

**Comment by Roadhog360** [comment]
Weird, why? Seems like a good idea, I don't see why that'd get denied.

**Comment by AutumnClove** [comment]
Was deemed more appropriate for a general purpose bot

**Comment by Roadhog360** [comment]
That doesn't really make sense. I can't set the music bot's status to "listening" with a general purpose bot. I feel like that comparison would be valid with some sort of moderation command suggestion.

**Comment by AutumnClove** [comment]
You can see for yourself #1881

**Comment by Jcodeerd** [comment]
we could try again?

**Comment by Roadhog360** [comment]
I didn't say I didn't believe you, I'm saying why it was denied makes literally no sense.
