### ISSUE TITLE
Make it possible to add a song to the TOP of the queue (!playnow URL)

### ISSUE THREAD

**Issue by totsudon** [Just-Some-Bots/MusicBot#205]
When dealing with huge queues/playlists sometimes we want to hear a song right away without waiting for all the other songs to finish. It would be a nice addition. #

**Comment by Noctimor** [comment]
Yeah, I'd love a !playnext (clearer wording imo) command, sometimes we'll remember something all of a sudden that we want to hear without clearing the queue

**Comment by imayhaveborkedit** [comment]
There are a whole bunch of utility commands that i'll write up with playlist stuff, playnow, playnext, etc.  Names pending.

**Comment by berkuhlee** [comment]
[remove.undo.playnext.zip](https://github.com/SexualRhinoceros/MusicBot/files/289369/remove.undo.playnext.zip)

replace bot.py and playlist.py with the ones in this .zip, new commands are !undosong, !remove [x], and !playnext

!playnext is the command you want (!playnow), adds to the top of the playlist
