### ISSUE TITLE
disappears game status

### ISSUE THREAD

**Issue by troit5ky** [Just-Some-Bots/MusicBot#2054]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
disappears game status after ~2-3 hours

### Steps to reproduce

1. Start bot with ./run.sh
2. Wait ~3-4 hours
3. The status has disappeared

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4498901/musicbot.log)

**Comment by LegalSmeagol** [comment]
I too have had this occur. Very frustrating but temporarily fixed with {prefix}restart.

**Comment by 3booo6** [comment]
i also have this problem.
the bot keeps working for around 3-4 hours then the status disappears, but the bot still keeps working.

**Comment by AutumnClove** [comment]
Does doing `python -m pip install -U discord.py[voice]` fix this?

**Comment by amit177** [comment]
Please let us know if this is still happening on the latest version of discord.py and the bot itself.
If it is, we'll reopen the issue.
