### ISSUE TITLE
 Error after playing song

### ISSUE THREAD

**Issue by JoniniDev** [Just-Some-Bots/MusicBot#2057]
Please tick all applicable boxes.

 [+] I am using Python 3.5.3 or higher (run python --version on the command line)
 [+] I have followed the official guides to install the bot for my system
 [+] I have updated my dependencies to the latest version using the appropriate update script
Which version are you using?

The latest master version (release-260419)
What type of issue are you creating?
[+] Bug

Steps to reproduce
I turn on the bot, it plays 1-2 songs and writes an error.

Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4503812/musicbot.log)

**Comment by AleanaA** [comment]
Run one of the following depending on your setup:
`youtube-dl --rm-cache-dir`
`python -m youtube_dl --rm-cache-dir`
`python3 -m youtube_dl --rm-cache-dir`

**Comment by JoniniDev** [comment]
> Run one of the following depending on your setup:
> `youtube-dl --rm-cache-dir`
> `python -m youtube_dl --rm-cache-dir`
> `python3 -m youtube_dl --rm-cache-dir`

Oh, yeah it's worked! Thx you!
