### ISSUE TITLE
Youtube: 403 Forbidden Error

### ISSUE THREAD

**Issue by Oskarhb** [Just-Some-Bots/MusicBot#2060]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

The bot stops working after using the !skip command or the song ends. After closing the bot and opening it again, it still won't play a song. The cmd notes a problem with youtube_dl. ERROR: unable to download video data: HTTP Error 403: Forbidden

### Steps to reproduce

1. Run Musicbot
2. Execute !skip
3. Bot stops working.

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4531281/musicbot.log)

**Comment by TOoSmOotH** [comment]
I am seeing this same issue.

**Comment by vonDassendorf** [comment]
this is a problem with the youtube cache.
You can fix it by running `python -m youtube_dl --rm-cache-dir` as the same user you are running the bot with.

Maybe it would be good to look into making the bot detect this error and clear the ytdl cache by it self.

**Comment by Oskarhb** [comment]
Thank You! That worked.

**Comment by zxphet2540** [comment]
Doing this correctly or not.
<img src="https://s3-ap-southeast-1.amazonaws.com/img-in-th/a97f1c683d172182f2cff0d28a678c73.png" alt="a97f1c683d172182f2cff0d28a678c73.png" border="0" />
