### ISSUE TITLE
Error updating and running

### ISSUE THREAD

**Issue by acfin** [Just-Some-Bots/MusicBot#2068]
Please tick all applicable boxes.

- [!] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [!] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [!] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [!] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [!] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

I get this error when I run run.bat
I also get several errors when running update.bat

Traceback (most recent call last):
  File "run.py", line 438, in <module>
    main()
  File "run.py", line 347, in main
    finalize_logging()
  File "run.py", line 179, in finalize_logging
    dlh.setFormatter(logging.Formatter('.'))
  File "C:\Users\acfin\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 576, in __init__
    self._style.validate()
  File "C:\Users\acfin\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 429, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '.' for '%' style

### Steps to reproduce

1. 

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4555938/musicbot.log)

**Comment by AleanaA** [comment]
See pinned issue regarding python 3.8
