### ISSUE TITLE
Bot not working with Python 3.7

### ISSUE THREAD

**Issue by acfin** [Just-Some-Bots/MusicBot#2069]
Please tick all applicable boxes.

- [! ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [! ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [! ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [! ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [! ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Errors whenever I run update.bat and run.bat. Was experiencing errors earlier that I thought would be fixed by downgrading to Python 3.7, but the errors have only changed.

### Steps to reproduce

1. 

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4555991/musicbot.log)

**Comment by Jcodeerd** [comment]
try `python -m pip install -U -r requirements.txt`
