### ISSUE TITLE
[1.9.5 RC7] Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by EmeliaK** [Just-Some-Bots/MusicBot#207]
![](http://i.imgur.com/gj8hlFG.png)

Bot crashes to command line. This has happened semi-frequently; roughly daily. Can happen at any time.

**Comment by gfrewqpoiu** [comment]
Can confirm that that happens here as well, also with RC7. This is the reason why I am running the version from the review branch, which EDIT: also haves this problem.

**Comment by Loafabreadly** [comment]
Yeah im getting the same error, it crashes rather often. `[Download] Started: https://www.youtube.com/watch?v=PI2GauQ1eiU
[Download] Complete: https://www.youtube.com/watch?v=PI2GauQ1eiU
Task was destroyed but it is pending!
task: <Task pending coro=<VoiceClient.keep_alive_handler() running at /usr/local/lib/python3.5/dist-packages/discord/voice_client.py:194> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.run() running at /usr/local/lib/python3.5/dist-packages/websockets/protocol.py:302> wait_for=<Future pending cb=[Task._wakeup()]>>
`

**Comment by EmeliaK** [comment]
![](http://i.imgur.com/HUFwtuM.png)

This occurred even after all dependencies were updated. It might seem to be that the bot is stable while being used.

**Comment by jayktaylor** [comment]
This seems to be a problem with discord.py's handling of Discord's (and CloudFlare)'s disconnects. Better off seeking help from the guys that develop it.

**Comment by arunesh90** [comment]
Do: `pip3.5 install -r requirements.txt --upgrade`
