### ISSUE TITLE
The bot shows me error message when I update the bot.

### ISSUE THREAD

**Issue by TheDaekLord1989** [Just-Some-Bots/MusicBot#2074]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)

- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

It shows me ERROR message when I update and start the bot

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.lo
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4641259/musicbot.log)
g`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by Jeroeni** [comment]
I dont see any error messages. Could you specify the error message?

**Comment by AutumnClove** [comment]
Upload your log please

**Comment by Nicalicious** [comment]
I noticed the update.sh is not executable. Run "chmod +x update.sh" to correct the issue.

**Comment by TheDaekLord1989** [comment]
> I noticed the update.sh is not executable. Run "chmod +x update.sh" to correct the issue.

got it, the update.sh run smoothly after chmod +x update.sh, thanks
