### ISSUE TITLE
SSL cert failure

### ISSUE THREAD

**Issue by wellivea1** [Just-Some-Bots/MusicBot#2075]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
I was having issues with the bot failing to stay connected to discord and decided to reinstall musicbot (deleting everything except config, reinstalling python). Now it is saying that it is "unable to get local issuer certificate". I don't see how anything could have changed to make that happen other than an issue on discord's side but there's no other bug report for this...

### Steps to reproduce

1. Attempt to run MusicbBot on Windows

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.** 
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4669590/musicbot.log)

**Comment by AleanaA** [comment]
Open discord in Internet Explorer and accept/trust the new certificates.

**Comment by wellivea1** [comment]
Ah, that worked. Thanks!

**Comment by mnmt** [comment]
@AleanaA I think I am having the same problem; if possible please could you elaborate a little on "Open discord in Internet Explorer and accept/trust the new certificates.". 

I've opened the site, viewed the certificates in the certification path, but they all seem valid to me, padlock symbol displays as usual, no prompt to accept/trust certificates.

**Comment by thestrangehosterr** [comment]
You marked mine as a dupe, but I cannot trust the certs in IE, I am on a mac.

**Comment by thestrangehosterr** [comment]
And I don't see how to trust them in safari, I've tried and it just shows as secure.

**Comment by AleanaA** [comment]
https://crt.sh/?id=2835394
Install the certificate manually from the link above, if you can't find the download link, refer to the following image.
https://beans-took-my-kids.reeee.ee/38qB2n.png

Your issue was marked as duplicate because this error has been brought up several times.
@thestrangehosterr
