### ISSUE TITLE
Guild List: --Logging Error-

### ISSUE THREAD

**Issue by thatfugue** [Just-Some-Bots/MusicBot#2077]
Please tick all applicable boxes.

- [+] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [+] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [+] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [+] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [+] Question

----

### Description of issue
My bot its working, but console its giving me this error and i dont see my guild list.

### Steps to reproduce

1. run "run.bat"

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4673859/musicbot.log)

**Comment by AutumnClove** [comment]
That's a lot of servers, but I'm thinking it has to do with some of the text not being traditional characters.
