### ISSUE TITLE
SSL Certificate Error when starting bot

### ISSUE THREAD

**Issue by Ksdsk** [Just-Some-Bots/MusicBot#2078]
Please tick all applicable boxes.

- [+] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [+] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [+] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [+] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [+] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Error starting bot and on the bottom gives an SSL Certificate Error. Already tried reinstalling the discord.com SSL certificate: COMODOECCAddTrustCA.crt

### Steps to reproduce

1. running sh run.sh on MacOS

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4702470/musicbot.log)

**Comment by ghost** [comment]
Same here, it's because Discord has changed their domain name from discordapp.com to discord.com but the bot is hardcoded to look at discordapp.com for the certificate.

**Comment by AleanaA** [comment]
For windows users, see #2075 
Mac or linux users need to accept new certs however works for them.
