### ISSUE TITLE
[Feature Request] Support environmental variable for token

### ISSUE THREAD

**Issue by khionu** [Just-Some-Bots/MusicBot#2080]
For the sake of k8s deployment, I'd like to be able to pull my token from the secrets store and insert it as an environmental variable, as a security precaution.

**Comment by AleanaA** [comment]
See #1978

**Comment by khionu** [comment]
I see the PR, and it was rejected for lack of use case and discussion. I have stated my use case. Unless I add a script to my deployment for editing the config file, I have no secure way of inserting my token into the pod on deployment.

**Comment by srhinos** [comment]
I'm gonna tend to agree that this request, while a niche one, is valid.

@khionu, would you mind resubmitting an MR in a similar style and doing a small bit of documenting on it? if not I can work on it in a few days when I have time

**Comment by khionu** [comment]
I guess it'll be a matter of who can find time first, I can't make any guarantees either, with my new job starting tomorrow :D

**Comment by srhinos** [comment]
I'll hit you up on discord if I start working on a fix for this and will edit this comment for other parties interested in this feature.

**Comment by tripulse** [comment]
Khionu tisava '-v
