### ISSUE TITLE
pip3 not found when building from Dockerfile in Raspbian

### ISSUE THREAD

**Issue by Chipsnet** [Just-Some-Bots/MusicBot#2091]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

When I build from Dockerfile in Raspbian, I get this `/bin/sh: pip3: not found` error and stop.

### Steps to reproduce

1. Clone repository `git clone https://github.com/Just-Some-Bots/MusicBot.git`
1. Move to repo's dir `cd MusicBot`
1. Build docker image from Dockerfile `docker build -t musicbot`
1. Got error `/bin/sh: pip3: not found`

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[log.log](https://github.com/Just-Some-Bots/MusicBot/files/4832669/log.log)

**Comment by phknot** [comment]
It should work with the review branch. Try that first

**Comment by Chipsnet** [comment]
I changed the first line of the Dockerfile to the following and it worked for me.
```
FROM alpine
```

**Comment by arond1** [comment]
> 
> 
> I changed the first line of the Dockerfile to the following and it worked for me.
> 
> ```
> FROM alpine
> ```

I confirm that the image finish the build when I remove ":edge".
i'm on Debian 9 x64
