### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Giuseh** [Just-Some-Bots/MusicBot#2092]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Steps to reproduce

1. 
i have just a question, is there any method to get the bot into your same channel just when you want to play a song and not into the startup of it?
----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by Mikeythebeast** [comment]
I am currently using review. It is like master, but review is like the updated version of master. I don't recommend cogs right now, for it is experiencing some bugs. The devs are currently working on them. For right now I suggest review. Hope this helps!

**Comment by AutumnClove** [comment]
Turn off `AutoSummon` in the options file.
