### ISSUE TITLE
Bot won't connect due to SSL error.

### ISSUE THREAD

**Issue by itoncek4** [Just-Some-Bots/MusicBot#2093]
Please tick all applicable boxes.

- [ X ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ X ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ X ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ X ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ X ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Bot won't connect to voice due to new address of discord.

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4904718/musicbot.log)

**Comment by AleanaA** [comment]
Sectigo provides this link to download the cert manually: https://crt.sh/?id=2835394
---> How to find the download link: https://beans-took-my-kids.reeee.ee/38qB2n.png
---> This shouldn't need said, but you need to install the certificate after you download it.
