### ISSUE TITLE
Error Starting Bot

### ISSUE THREAD

**Issue by ArchaicWraith** [Just-Some-Bots/MusicBot#2097]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
Everytime I try to activate it, it doesn't and gives me Error starting bot.

### Steps to reproduce

1. Execute run.bat, run.py, or run.sh

----

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4958057/musicbot.log)

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by vegeta897** [comment]
I had this error too. Googling brought me to [this question on SO](https://stackoverflow.com/questions/63027848/discord-py-glitch-or-random-error-typeerror-new-got-an-unexpected-keywor). 

> Discord pushed a new change that changes the overwrites object.
> 
> Just reinstall the latest version of Discord.py

So I updated my `requirements.txt` with `discord.py[voice]==1.3.4`, updated dependencies, and now the bot is running.

**Comment by mickael49300fr** [comment]
thank you vegeta897 it worked
I had the same problem as ArchaicWraith

**Comment by lilchancep** [comment]
I had the same issue, @vegeta897 solution solved it for me as well.
