### ISSUE TITLE
Some Suggestions :)

### ISSUE THREAD

**Issue by greendogblue** [Just-Some-Bots/MusicBot#21]
1) It would be great if there was some way to remove songs from the queue, maybe '!remove 4' for example would remove song #4 in the queue, just an idea, but I know it is something my group has wanted.

2) A way to view the blacklist/whitelist through a command would be nice too.  For example, '!blacklist view' could work.

3) A way to change the text channel that the bot posts song names into would be cool too.  It may already be a thing but I'm not sure to how if it is.  Not being plagued by songnames in the general chat and instead posting in a DJ chat would be good if you wanted to mute the notifications for it specifically.

We've only been using it for one night so far, but it's very nice so far :) One last question is if, when this is updated, how do I update the bot?  Is there an update checker built in or do I need to reinstall?  Thanks ahead of time
- Green

**Comment by imayhaveborkedit** [comment]
1. More commands and subcommands will be added, i'm still trying to get the last two main features in so I can release V2 and delete the awful old version.
2. ^
3. The bot will reply in whatever channel the message was posted in.  You can do something like limit the bot to only read text in one channel, but I might add a config option to specify a dedicated channel in the future, provided I don't have to change too much to do so.

I've been meaning to do something like that, but I'm not really supporting that until V2 is out.  To update it you just download it again, there's not really an installation process besides setting up the dependencies the first time.  You just need to set the config file again, and copy the white/blacklist, and the audio_cache folder if you want.
