### ISSUE TITLE
My music bot is playing random songs that no one qued or ever has qued

### ISSUE THREAD

**Issue by huntere01** [Just-Some-Bots/MusicBot#210]

**Comment by Echoskope** [comment]
Autoplaylist, it's a normal function when nothing is in the queue.

**Comment by huntere01** [comment]
is there anyway to turn this off? cause it play's some pretty weird stuff, i looked under the backuplist.txt in the config folder, if i removed all of those youtube links would it not play them randomly?

**Comment by dbkynd** [comment]
There is an yes/no setting in the options file for the Autoplaylist. Simply set it to 'no' and restart the bot. Please make sure not to use notepad when editing the options file as it borks the formatting. Notepad++ is a common choice.

**Comment by salsichinha** [comment]
hello, i have the same issue, even though i have disabled autoplaylist and also deleted all the links on the playlist files just in case, but the bot still plays when nothing is queued. any way to solve it?

this is what i have:

; Play random songs from the autoplaylist when nothing is queued.
UseAutoPlaylist = no
