### ISSUE TITLE
Music Bot wont run.

### ISSUE THREAD

**Issue by riggers-logan-1229** [Just-Some-Bots/MusicBot#2101]
starting today I am getting this error message upon starting up the bot:

[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 373, in main
    m.run()
...
...

self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'

**Comment by harbinger1080** [comment]
Getting the same

**Comment by Runion1337** [comment]
try running this: py -m pip install -U discord.py[voice]

**Comment by Runion1337** [comment]
that's what worked for me

**Comment by the-prism** [comment]
It worked for me as well, looks like it installed version 1.3.4 instead of the 1.2.5 listed in the requirements

**Comment by ghost** [comment]
this worked for me thanks!

**Comment by AutumnClove** [comment]
Closing because information on how to fix is available.
