### ISSUE TITLE
[Question] bot encounts "discord.opus.OpusNotLoaded" exception

### ISSUE THREAD

**Issue by TenTakano** [Just-Some-Bots/MusicBot#2102]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
When the bot starts to play a song, the following exception raised.

```
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at /home/MusicBot/musicbot/player.py:259> exception=OpusNotLoaded()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/home/MusicBot/musicbot/player.py", line 307, in _play
    self.voice_client.play(self._source, after=self._playback_finished)
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 406, in play
    self.encoder = opus.Encoder()
  File "/usr/local/lib/python3.5/site-packages/discord/opus.py", line 231, in __init__
    raise OpusNotLoaded()
discord.opus.OpusNotLoaded
```

Downloading the song seems to succeed. My docker file to deploy the bot is as follows. The version of `websockets` is different from the official docker file because of the dependency issue.

```
FROM python:3.5.9-alpine3.12

WORKDIR /home
COPY ./config ./config

# Install dependencies
RUN apk update \
&& apk add --no-cache \
  ca-certificates \
  ffmpeg \
  opus \
  opus-dev \
  libsodium-dev \
\
# # Install build dependencies
&& apk add --no-cache --virtual .build-deps \
  gcc \
  git \
  libffi-dev \
  make \
  musl-dev \
  python3-dev \
\
# Expand musicbot files
&& git clone https://github.com/Just-Some-Bots/MusicBot.git \
&& rm -r MusicBot/config \
&& mv config MusicBot/ \
\
# Install pip dependencies
&& python3 -m pip install --no-cache-dir -U -r MusicBot/requirements.txt \
&& python3 -m pip install --upgrade --force-reinstall --version websockets==6.0 \
&& python3 -m pip install -U git+https://github.com/Rapptz/discord.py@master#egg=discord.py[voice] \
\
# Clean up build dependencies
&& apk del .build-deps

ENV APP_ENV=docker

WORKDIR /home/MusicBot
ENTRYPOINT ["python3", "dockerentry.py"]

```

Now I don't have any idea to solve the issue. Could you give me some advice?

**Comment by lilchancep** [comment]
This might be related to the version of discord.py that requirements.txt installs try the changes I mentioned in my pull request #2103

**Comment by TenTakano** [comment]
Thank you for your information. And sorry for the late reply.
I start to watch your PR and close this issue.
