### ISSUE TITLE
bot is not working again

### ISSUE THREAD

**Issue by Deblin-Mallick** [Just-Some-Bots/MusicBot#2104]
![Annotation 2020-07-27 011445](https://user-images.githubusercontent.com/68825366/88487896-cc759480-cfa6-11ea-8caf-f6e9e0742600.png)
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by lilchancep** [comment]
Try the changes mentioned in #2103

**Comment by AutumnClove** [comment]
Caused by outdated discord.py run `python -m pip install -U discord.py[voice]`
