### ISSUE TITLE
line 939 in on_error: Exception in on_ready

### ISSUE THREAD

**Issue by papa2007hd** [Just-Some-Bots/MusicBot#2105]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

the server giving me only Traceback
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4978613/musicbot.log)

### Steps to reproduce

1. 
I am starting the run.bat on Windows
2.
giving my much red errors
3.
saing "[INFO] launcher: All done." but he is not there on the server
----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by papa2007hd** [comment]
i am now at that point
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4978982/musicbot.log)

**Comment by lilchancep** [comment]
Try the changes mentioned in #2103

**Comment by papa2007hd** [comment]
Thx
