### ISSUE TITLE
Bot can't load the music

### ISSUE THREAD

**Issue by papa2007hd** [Just-Some-Bots/MusicBot#2106]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Bot can load the music

### Steps to reproduce

1.
Starting the bot with .bat on Winows

2.
puting the link in the CH
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4984611/musicbot.log)

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by papa2007hd** [comment]
one song is playing but all other not
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4984714/musicbot.log)

**Comment by papa2007hd** [comment]
i down´t now how but if fix it

**Comment by Jcodeerd** [comment]
what do you mean?

**Comment by Jcodeerd** [comment]
maybe try `python -m pip install -U discord.py[voice]`?

**Comment by Callumpy** [comment]
Seems to be a change to the Youtube APIs 

`python -m pip install -U youtube_dl=2020.07.28`
