### ISSUE TITLE
Error when attempting to load a playlist or song.

### ISSUE THREAD

**Issue by bencerda1** [Just-Some-Bots/MusicBot#2109]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
Attempting to play playlists throws "all songs were over max duration (0s)" and attempting to play individual songs throws seemingly cascading exceptions

### Steps to reproduce

1. Playing any song or playlist

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4997770/musicbot.log)

**Comment by twosevenska** [comment]
This is an issue with the youtube-dl dependency, which is not pinned in the requirements. Rebuilding/updating it fixed it on my side.

**Comment by bencerda1** [comment]
Ah, yep. Uninstalling and reinstalling youtube-dl with pip did the trick.
