### ISSUE TITLE
[1.9.5 RC7] Extensively logged TypeError

### ISSUE THREAD

**Issue by EmeliaK** [Just-Some-Bots/MusicBot#211]
![](http://i.imgur.com/HUli71Z.png)

Bot crashes to command line. This issue seems to be separate from the [Task was destroyed but it is pending!](https://github.com/SexualRhinoceros/MusicBot/issues/207), since this is the first time it has happened. The bot was not interacted with between being launched and crashing.

**Comment by imayhaveborkedit** [comment]
I don't know why the logging module freaked out, but the error above that should stop happening now.  Use review and update deps.
