### ISSUE TITLE
Bot not works (fix toturial)

### ISSUE THREAD

**Issue by mstudio45** [Just-Some-Bots/MusicBot#2110]
Please tick all applicable boxes.

- [✓ ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [✓ ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [✓] Bug
- [ ] Feature request
- [ ] Question

----

### Steps to reproduce

1. Bot not works

---------------------------------------------------------------------------------

I Fixed #2107 error with@BritishBenji#0420 on discord here is toturial:
you must replace everything in requirements.txt with this text:

pynacl==1.4.0
discord.py[voice]==1.3.4
pip
youtube_dl
colorlog

Then run python -m pip install -U -r requirements.txt
A When install is downloaded run update.bat
say n and y
and after you run update.bat run run.bat and works good

Thats all!

**Comment by zxphet2540** [comment]
thank you
