### ISSUE TITLE
Feature Request: Display Video Thumbnail

### ISSUE THREAD

**Issue by brah** [Just-Some-Bots/MusicBot#2112]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

### Description of suggestion
Most public bots have video thumbnails displayed when /nowplaying or /queue is entered, it'd be a nice addition

e.g
![e.g](https://dnm.wtf/sx/54mwldmzjlrr0ta9.png)

**Comment by AutumnClove** [comment]
Definitely something that's possible if we embed now playing.

**Comment by Mohtion** [comment]
Hey, I'm a student take a software development methodology course, and one of our assignments for the semester si to contribute to a github project. Is it cool for me to be assigned to this issue and contribute to the project?

**Comment by AutumnClove** [comment]
@Mohtion I've gone ahead and assigned you, you're free to take a crack at this and submit a PR.

**Comment by Mohtion** [comment]
What in the bot code makes the help command embedded? I looked at the Response class and that didn't get me closer to answers
![image](https://user-images.githubusercontent.com/44117718/115585332-7fa2be00-a299-11eb-819e-1130c43219a1.png)
![image](https://user-images.githubusercontent.com/44117718/115585368-87faf900-a299-11eb-9c78-0e72d5b5ad5d.png)

**Comment by AleanaA** [comment]
@Mohtion This is a pull request, this comment does not contribute to the pull request in any way.

**Comment by AleanaA** [comment]
Missed the above comments, actually, my bad.

Help entries should be added without the need to add them yourself.

**Comment by leeh-nix** [comment]
Hello,
If this issue/feature request is still up, can I get assigned?

**Comment by Jcodeerd** [comment]
I believe that it's been resolved by https://github.com/Just-Some-Bots/MusicBot/commit/3ab260bdf091b0e8910b1ca866acf3fdcf1d4c68

**Comment by BabyBoySnow** [comment]
It should be noted that this is set up to only display with embeds
