### ISSUE TITLE
Error with following.

### ISSUE THREAD

**Issue by BetterDiscordDev** [Just-Some-Bots/MusicBot#2113]
Please tick all applicable boxes.

- [ Yes] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ yes] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [yes ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [yes ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [yes ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

[INFO] launcher: 
An error has occured parsing the config:

  Problem:
    One or more required config sections are missing.

  Solution:
    Fix your config.  Each [Section] should be on its own line with nothing
    else on it.  The following sections are missing: [Credentials]

### Steps to reproduce

1. 
Maybe tell us how to do it
----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5038164/musicbot.log)

**Comment by AleanaA** [comment]
Your config file was messed up, either as a result of using Notepad or Wordpad, or simply by removing something incorrectly. Delete your config file and reconfigure it after re-obtaining it using an editor such as Notepad++.
