### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by hwake-tech** [Just-Some-Bots/MusicBot#2117]
Please tick all applicable boxes.

- [ ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [ ] Question

----

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 368, in main
    m = MusicBot()
  File "D:\바탕 화면\MusicBot\musicbot\bot.py", line 74, in __init__
    self.config = Config(config_file)
  File "D:\바탕 화면\MusicBot\musicbot\config.py", line 17, in __init__
    self.find_config()
  File "D:\바탕 화면\MusicBot\musicbot\config.py", line 287, in find_config
    if not config.read(self.config_file, encoding='utf-8'):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\configparser.py", line 1079, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'config/options.ini', line: 1
'<NotepadPlus>\n'

[INFO] launcher: All done.

what should I do ?

**Comment by Jcodeerd** [comment]
Your config.ini file is broken

Try to reinstall the file / the whole bot

**Comment by gyul492** [comment]
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[CRITICAL] launcher: Bot wasn't installed using Git. Reinstall using http://bit.ly/musicbotdocs.
Press enter to continue. . . And an error pops up.. Any help would be appreciated.

**Comment by Jcodeerd** [comment]
it says what you need to doe:
 Reinstall using http://bit.ly/musicbotdocs.

**Comment by AutumnClove** [comment]
As stated you've installed the bot not by cloning with git but most likely by downloading a zip file, please follow the guides to correctly install it.
