### ISSUE TITLE
Unable to extract video data, connecting cookies file

### ISSUE THREAD

**Issue by Tachykir** [Just-Some-Bots/MusicBot#2118]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [X] Question

----

### Description of issue

Hello!
Is there a way to connect youtube-dl config file to bot, or somehow let the bot use --cookies command from youtube-dl?
I wanted to get rid of "Unable to extract video data" error, i managed to get rid of it when i used youtube-dl manually, but the error is still there when i'm trying to download the same video with MusicBot

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

ERROR: gnIO6ve4_uk: YouTube said: Unable to extract video data

**Comment by Jcodeerd** [comment]
is it with one video or multiple?

if one: that's just the video that maybe is deleted

if multiple:

change your static ip or wait multiple days to see wheter yt has unbanned you

**Comment by Tachykir** [comment]
> is it with one video or multiple?
> 
> if one: that's just the video that maybe is deleted
> 
> if multiple:
> 
> change your static ip or wait multiple days to see wheter yt has unbanned you


That's not really what i meant, my problem is that MusicBot is not using youtube-dl config file, so its not using my cookies file to pass age-restrictions on videos.

**Comment by AutumnClove** [comment]
Well I suppose you could use cookies in the downloaded.py file which handles the ytdl settings MusicBot/MusicBot/downloader.py there's a section labeled `ytdl_format_options` not sure if it would work or not though since it's format and not like configure, but use netrc is in there so I would assume you could do cookies as well.

**Comment by Tachykir** [comment]
> Well I suppose you could use cookies in the downloaded.py file which handles the ytdl settings MusicBot/MusicBot/downloader.py there's a section labeled `ytdl_format_options` not sure if it would work or not though since it's format and not like configure, but use netrc is in there so I would assume you could do cookies as well.

Oh nice, thank you for this, ill check that

**Comment by Tachykir** [comment]
I've solved it, after @AutumnClove message, if you want to use cookies file in order to bypass age-restriction on videos you need to download you cookies file from youtube in netscape format (i used "Get cookies.txt" extension to a browser).
In order to use the cookies in MusicBot you need to add 'cookiefile': 'Cookies location', in downloader.py file located in MusicBot/musicbot/downloader.py in ytdl_format_options.
Im not getting Unable to extract video data error anymore, so if you have that problem try doing that.

**Comment by Jinhjy** [comment]
I've tried this but I get this syntaxError for some reason when trying to run the bot any advice?
![image](https://user-images.githubusercontent.com/19521370/105622961-d35d5280-5de3-11eb-8e01-6d5a3d2aa49f.png)

**Comment by AutumnClove** [comment]
> I've tried this but I get this syntaxError for some reason when trying to run the bot any advice?
> ![image](https://user-images.githubusercontent.com/19521370/105622961-d35d5280-5de3-11eb-8e01-6d5a3d2aa49f.png)

Make sure you're using tabs instead of spaces, and make sure it's in line with everything else.

**Comment by Jinhjy** [comment]
That was part of my issue, another thing was a silly mistake I did that was I missed adding a comma to the line above (ops). Thanks for your help!
