### ISSUE TITLE
error

### ISSUE THREAD

**Issue by methsv** [Just-Some-Bots/MusicBot#2122]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Steps to reproduce

1.  ( run )
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
Traceback (most recent call last):
** IDLE Internal Exception: 
  File "C:\Users\qazws\AppData\Local\Programs\Python\Python38\lib\idlelib\run.py", line 548, in runcode
    exec(code, self.locals)
  File "C:\Users\qazws\Desktop\server\봇\MusicBot\run.py", line 438, in <module>
    main()
  File "C:\Users\qazws\Desktop\server\봇\MusicBot\run.py", line 345, in main
    sanity_checks()
  File "C:\Users\qazws\Desktop\server\봇\MusicBot\run.py", line 197, in sanity_checks
    req_ensure_encoding()
  File "C:\Users\qazws\Desktop\server\봇\MusicBot\run.py", line 284, in req_ensure_encoding
    sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding='utf8', line_buffering=True)
io.UnsupportedOperation: detach

2. ( run.bat )
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
Traceback (most recent call last):
  File "run.py", line 438, in <module>
    main()
  File "run.py", line 347, in main
    finalize_logging()
  File "run.py", line 179, in finalize_logging
    dlh.setFormatter(logging.Formatter('.'))
  File "C:\Users\qazws\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 576, in __init__
    self._style.validate()
  File "C:\Users\qazws\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 429, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '.' for '%' style

3. ( config )
options < I made
example_options
example_permissions
example_aliases
----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5111755/musicbot.log)
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5111761/musicbot.log)

**Comment by Jcodeerd** [comment]
you are using python 3.8?

**Comment by AutumnClove** [comment]
Hello, yes this is an issue with using python3.8 on master branch, I suggest switching to review which is easy to do just open a cmd in the file of your musicbot and type `git checkout review` if you don't want to use review though you can downgrade to the last version of python 3.7
