### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kaden97** [Just-Some-Bots/MusicBot#2128]
Please tick all applicable boxes.

- [x ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Steps to reproduce

1.  Error queuing playlist:
`float division by zero`
when trying to use youtube auto gen playlist
----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5185317/musicbot.log)

**Comment by AutumnClove** [comment]
Last I checked youtube playlist aren't supported by ytdl.

**Comment by Kaden97** [comment]
Oddly enough I've always been able to play auto gen playlist from youtube till this last update. but okay.
