### ISSUE TITLE
I dont understand what is breaking here?

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#2131]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Cannot run code:

iMac:MusicBot smackintosh$ ./run.sh

./run.sh: line 7: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
./run.sh: line 8: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
./run.sh: line 9: python3.5: command not found
./run.sh: line 10: python3.6: command not found
./run.sh: line 11: python3.7: command not found
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
Traceback (most recent call last):
  File "run.py", line 438, in <module>
    main()
  File "run.py", line 347, in main
    finalize_logging()
  File "run.py", line 179, in finalize_logging
    dlh.setFormatter(logging.Formatter('.'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 576, in __init__
    self._style.validate()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 429, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '.' for '%' style

### Steps to reproduce

1. 

Running script normally
----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5250152/musicbot.log)

**Comment by AutumnClove** [comment]
**Help! I'm getting an error! Invalid format '.' for '%' style**

This is a result of using python 3.8, please either downgrade to a version below that such as 3.7.x, switch to review, or switch to team-jsb. 

__**How do I switch to review?**__
If you have already cloned MusicBot master branch, simply navigate to your MusicBot folder through a terminal, or even easier, go to your MusicBot folder, and click open git bash here. Once there you can type git checkout review.

Don't have MusicBot yet? No worries.
use `git clone https://github.com/Just-Some-Bots/MusicBot.git ~/MusicBot -b review`

__**How do I use team-jsb?**__
The process of doing this is very easy, surprisingly! The commands listed below will set the git repo of the bot to the Team-JSB branch, and pull the latest version.
`git remote set-url origin https://github.com/Team-JSB/MusicBot.git`
Then do a `git pull.`
