### ISSUE TITLE
Auto-Disconnecting Issue

### ISSUE THREAD

**Issue by ArchaicWraith** [Just-Some-Bots/MusicBot#2133]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
I summon the bot and attempt to play a youtube playlist. It then disconnects after putting in the play command and it produces this wall of text.

### Steps to reproduce

1. Summon the Bot
2. Use !play to play something

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5280146/musicbot.log)

**Comment by AutumnClove** [comment]
Try doing `git checkout review` then `python -m pip install -U -r requirements.txt` and go to the [Discord Developer Portal](https://discord.com/developers/docs/intro) and enable intents
