### ISSUE TITLE
Task exception was never retrieved Error

### ISSUE THREAD

**Issue by ADMCrossfire** [Just-Some-Bots/MusicBot#2135]
Please tick all applicable boxes.

- [x ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [ ] The latest `review` version

- [x] It's running release 260819-5-gc87dc05

What type of issue are you creating?

- [ x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
Bot launches and successfully joins the voice channel but doesn't respond when asked to play a song. 
Gives the following error in the console: 

Task exception was never retrieved
future: <Task finished coro=<VoiceClient._create_socket() done, defined at C:\Users\Admin_Anthoros\AppData\Roaming\Python\Python36\site-packages\discord\voice_client.py:172> exception=gaierror(11001, 'getaddrinfo failed')>
Traceback (most recent call last):
  File "C:\Users\Admin_Anthoros\AppData\Roaming\Python\Python36\site-packages\discord\voice_client.py", line 191, in _create_socket
    self.endpoint_ip = socket.gethostbyname(self.endpoint)
socket.gaierror: [Errno 11001] getaddrinfo failed

Before this error I followed another forum when having and issue in which my bot wouldn't launch at all. This forum solution asked to change 'requirements.txt' with this:

pynacl==1.4.0
discord.py[voice]==1.3.4
pip
youtube_dl
colorlog

The bot is now able to launch but is unresponsive to music commands and only listens to extraneous commands such as, 'clean' 'clear' 'shutdown' etc.

### Steps to reproduce

1. run 'Run.bat'

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5283808/musicbot.log)

Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by Jcodeerd** [comment]
Try this:

`py -3.6 -m pip install websockets`

EDIT: change 3.7 to 3.6

**Comment by ADMCrossfire** [comment]
It says:

Installed Pythons found by C:\WINDOWS\py.exe Launcher for Windows *

Requested Python version (3.7) not installed, use -0 for available pythons
Python 3.7 not found!

 -3.6-64

**Comment by Jcodeerd** [comment]
my fault, I wrote it wrong
Try:
`py -3.6 -m pip install websockets`

**Comment by ADMCrossfire** [comment]
No worries. Tried it and it says

Requirement already satisfied: websockets in c:\users\admin_anthoros\appdata\roa    ming\python\python36\site-packages (6.0)

**Comment by Jeroeni** [comment]
Hi, my bot did always fully work. But I'm getting a TimeoutError too today. It's a bit different to yours but probably something changed/broke in the discord handshake.

**Comment by ADMCrossfire** [comment]
I do remember that discord was in the process of changing a lot for bots and such. Might have to just wait this out but I'm willing to try solutions.

**Comment by Jeroeni** [comment]
In requirements.txt change discord.py version to discord.py[voice]==1.4.1
Update dependencies after. That fixed it for me :)

**Comment by ADMCrossfire** [comment]
Worked like a charm. Thank you so much!
