### ISSUE TITLE
Crash on launch on Ubuntu 20.04 Server - Fresh install

### ISSUE THREAD

**Issue by silentdis** [Just-Some-Bots/MusicBot#2136]
Please tick all applicable boxes.

- [✔️] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [✔️] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [✔️] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [✔️] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [✔️] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Fresh install from instructions at https://just-some-bots.github.io/MusicBot/installing/ubuntu/ yields crash with python errors.

### Steps to reproduce

1. Install / update OS dependencies.
2. Install MusicBot.
3. Update MusicBot Dependencies.
4. Copy over config that was working before (template was identical, just filled in).
5. Run.
6. Watch it crash out:
`juk3box@JukeBox:~/MusicBot$ sudo ./run.sh
./run.sh: line 9: python3.5: command not found
./run.sh: line 10: python3.6: command not found
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.

Starting MusicBot release-260819-5-gc87dc05
Loaded autoplaylist with 182 entries
Authenticated with Spotify successfully using client ID and secret.
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 373, in main
    m.run()
  File "/home/juk3box/MusicBot/musicbot/bot.py", line 902, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/root/.local/lib/python3.7/site-packages/discord/client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "/root/.local/lib/python3.7/site-packages/discord/client.py", line 457, in connect
    await self._connect()
  File "/root/.local/lib/python3.7/site-packages/discord/client.py", line 421, in _connect
    await self.ws.poll_event()
  File "/root/.local/lib/python3.7/site-packages/discord/gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "/root/.local/lib/python3.7/site-packages/discord/gateway.py", line 423, in received_message
    func(data)
  File "/root/.local/lib/python3.7/site-packages/discord/state.py", line 663, in parse_guild_create
    guild = self._get_create_guild(data)
  File "/root/.local/lib/python3.7/site-packages/discord/state.py", line 638, in _get_create_guild
    guild._from_data(data)
  File "/root/.local/lib/python3.7/site-packages/discord/guild.py", line 391, in _from_data
    self._sync(guild)
  File "/root/.local/lib/python3.7/site-packages/discord/guild.py", line 418, in _sync
    self._add_channel(TextChannel(guild=self, data=c, state=self._state))
  File "/root/.local/lib/python3.7/site-packages/discord/channel.py", line 107, in __init__
    self._update(guild, data)
  File "/root/.local/lib/python3.7/site-packages/discord/channel.py", line 131, in _update
    self._fill_overwrites(data)
  File "/root/.local/lib/python3.7/site-packages/discord/abc.py", line 271, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'

[INFO] launcher: All done.`

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5287300/musicbot.log)

**Comment by silentdis** [comment]
Forgot, requires some changes to requirements.

Applied these changes: https://github.com/Just-Some-Bots/MusicBot/issues/2107#issuecomment-667638287

And now it launches, joins the proper voice channel, and responds in the proper text channel, but then fails out shortly after.

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5287310/musicbot.log)

**Comment by Jcodeerd** [comment]
try this: `pip3 install -U asyncio websockets`

**Comment by silentdis** [comment]
Both now installed, same issue.

```
juk3box@JukeBox:~/MusicBot$ sudo pip3 install -U asyncio websockets
Requirement already up-to-date: asyncio in /usr/local/lib/python3.7/dist-packages (3.4.3)
Requirement already up-to-date: websockets in /usr/local/lib/python3.7/dist-packages (8.1)
```
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5287313/musicbot.log)

**Comment by Jcodeerd** [comment]
hmm

**Comment by Jcodeerd** [comment]
and `pip3 install -U aiohttp` ?

**Comment by silentdis** [comment]
```
juk3box@JukeBox:~/MusicBot$ sudo pip3 install -U aiohttp
Requirement already up-to-date: aiohttp in /usr/local/lib/python3.7/dist-packages (3.6.2)
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.5 in /usr/local/lib/python3.7/dist-packages (from aiohttp) (4.7.5)
Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp) (3.0.1)
Requirement already satisfied, skipping upgrade: chardet<4.0,>=2.0 in /usr/lib/python3/dist-packages (from aiohttp) (3.0.4)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp) (1.4.2)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp) (19.3.0)
Requirement already satisfied, skipping upgrade: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp) (2.6)
```
Appears to be already installed.

Same issue when running again.

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5287320/musicbot.log)

**Comment by Jcodeerd** [comment]
uch, and ` pip3 install -U discord.py[voice]==1.4.1 discord.py`?

**Comment by silentdis** [comment]
discord.py[voice]==1.3.4 per that old requirements.txt.

Updating my requirements.txt with all the stuff we've added. Updated now.

That seemed to get it!

**Comment by silentdis** [comment]
For the record, here's the "new" requirements.txt:

```
pynacl==1.4.0
discord.py[voice]==1.4.1
pip
youtube_dl
colorlog
aiohttp
websockets
asyncio
```
