### ISSUE TITLE
Bot not playing music 

### ISSUE THREAD

**Issue by jvelasq** [Just-Some-Bots/MusicBot#2137]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

About 3 months ago the bot stopped working and I updated the bots Discord.py to 1.3.4. A few Days ago the bot stopped working. After launching the bot it will join voice but not play any audio (Nothing on discord muting the bot or denying audio rights). Sometimes after a few seconds it will auto disconnect and tell you to re summon it when people are still in Voice chat. I tried running the updater but still the same problem. 

### Steps to reproduce

1.  Unsure it was a random thing.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5287895/musicbot.log)

**Comment by he01457474** [comment]
I changed Discord.py to 1.4.0 and it works

**Comment by jvelasq** [comment]
That Worked. Thank you.
