### ISSUE TITLE
Bot cant connect to voice channel

### ISSUE THREAD

**Issue by NoLuckNoWin** [Just-Some-Bots/MusicBot#2140]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Bot cannot properly connect to voice channel, waits like a minute and then exits the channel.

### Steps to reproduce

1. Summon

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5307197/musicbot.log)

**Comment by Jcodeerd** [comment]
try updating: `pip install -U aiohttp discord.py[voice]`

Otherwise:
_maybe_
https://github.com/aio-libs/aiohttp/issues/1207 , but  idk then

**Comment by NoLuckNoWin** [comment]
Thank you it fixed the problem
