### ISSUE TITLE
Not running a bot

### ISSUE THREAD

**Issue by Ludvi01** [Just-Some-Bots/MusicBot#2146]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

---

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5333564/musicbot.log)

**Comment by norhu1130** [comment]
I had the same problem and I solved it by upgrading discord.py.

**Comment by BRAVO68WEB** [comment]
Reinstall Dependencies and Check ENV or run with Privileges

**Comment by AutumnClove** [comment]
`python -m pip install -U discord.py[voice]` should fix this
