### ISSUE TITLE
Can't skip music

### ISSUE THREAD

**Issue by Razorbackfr** [Just-Some-Bots/MusicBot#2147]
Please tick all applicable boxes.

- [ x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

When a member or me use the skip command, an error occurs and the command is not taken into account.

### Steps to reproduce

1. use the skip command

----

### Log file

Traceback (most recent call last):
  File "/home/valentin/MusicBot/musicbot/bot.py", line 2823, in on_message
    response = await handler(**handler_kwargs)
  File "/home/valentin/MusicBot/musicbot/bot.py", line 2111, in cmd_skip
    num_skips = player.skip_state.add_skipper(author.id, message)
  File "/home/valentin/MusicBot/musicbot/constructs.py", line 36, in add_skipper
    self.skip_msgs.add(msg)
TypeError: unhashable type: 'Message'

**Comment by Jcodeerd** [comment]
windows: `py -m pip install -U discord.py[voice]`
Linux: `python -m pip install -U discord.py[voice]`

**Comment by Razorbackfr** [comment]
Hi @Jcodeerd 

I use this command before each bot start, unfortunately it doesn't change anything

**Comment by niflostancu** [comment]
Hello,
This is the official problem: https://github.com/Rapptz/discord.py/issues/5866

The code that requires that is at https://github.com/Just-Some-Bots/MusicBot/blob/master/musicbot/constructs.py#L36
```
self.skip_msgs.add(msg)
```
Where msg is a `discord.Message` and `self.skip_msgs` is a set.
You can workaround that by modifying it to:
```
self.skip_msgs.add(msg.jump_url)
```
After this, the skip command starts working again ;)

**Comment by AleanaA** [comment]
See #2143 
Per discord.py staff, messages were not intended to be hashable, therefore we should not try to hash them.

**Comment by AleanaA** [comment]
This error is resolved in discord.py 1.5.1
