### ISSUE TITLE
MusicBot Cannot Download Bandcamp Links

### ISSUE THREAD

**Issue by inexosino** [Just-Some-Bots/MusicBot#2149]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature Request
- [x] Question

----

### Description of issue

As the title implies, the bot does not seem to be able to download and play Bandcamp links; it spits out what appears to be a generic `ERROR: No video formats found` message. Even after updating dependencies, this issue persists. I'm not even certain it's a bug, per se; it could just be that Bandcamp has changed the way its video/music files are accessed.

### Steps to reproduce

1. Queue any track from Bandcamp.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5375596/musicbot.log)

**Comment by DestinyofYeet** [comment]
Update the youtube_dl package using pip. This often happens when websites change their layout or change a minimalistic thing about their website.

**Comment by amit177** [comment]
We use youtube-dl for processing all links, make sure you're running the latest version of it.
If you are, I would recommend bringing this up in https://github.com/ytdl-org/youtube-dl
