### ISSUE TITLE
my bot aint responding to my commands

### ISSUE THREAD

**Issue by kweeperdotjs** [Just-Some-Bots/MusicBot#2150]
hi so im a beginner which means idk alot abt coding i use node.js version 12.19 and heres my problem my bot isnt responding to commands pls help and yea i used the right prefix the bot is online and when i execute the command no error showed up help pls my first time seeing this heres my code

`const Discord = require('discord.js');

const client = new Discord.Client();

const prefix = 'c!';

const fs = require('fs');

client.commands = new Discord.Collection();
 
const commandFiles = fs.readdirSync('./commands/').filter(file => file.endsWith('.js'));
for(const file of commandFiles){
    const command = require(`./commands/${file}`);
 
    client.commands.set(command.name, command);
}

client.once('ready' , () => {
	console.log('I am Online!');
});

client.on('message', message =>{
	if(message.content.startsWith(prefix) || message.author.bot) return;

	const args = message.content.slice(prefix.length).split(/ +/);
	const command = args.shift().toLowerCase();

	if(command === 'ping'){
		client.commands.get('ping').execute(message, args)
	};
	if (command === 'youtube'){
		client.commands.get('youtube').execute(message, args)
	}; 
	if (command === 'help'){
		client.command.get('help').execute(message, args)
    };
    if (command === 'nitro'){
		client.commands.get('gibnitro').execute(message, args)
    };
});

client.login('NzY1NTY1MDU4NjU0NDA0NjEx.X4WqBQ.-5_T-col3fwtyIhOvtJxyMQEFPU');`

**Comment by AleanaA** [comment]
1: Never post your token
2: This is not the place for help regarding your own code.
