### ISSUE TITLE
Bot says "failed to parse JSON" when getting music.

### ISSUE THREAD

**Issue by jvelasq** [Just-Some-Bots/MusicBot#2152]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
I tell the bot to play a Spotify playlist and it says "Failed to parse Json".
First time I have seen this issue. 

### Steps to reproduce

1. Take a month long brake from using computer.
2. Run music bot.
3.Update dependencies.
4. Run music bot.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5427132/musicbot.log)

**Comment by Jcodeerd** [comment]
the one month brake is not the issue here.
See: [HERE](https://github.com/ytdl-org/youtube-dl/issues/26920)

**Comment by Jeroeni** [comment]
Youtube-dl is taken down due to an official DMCA notice. There is no fix.

**Comment by monty-dev** [comment]
Youtube-DL is still fully functional - the takedown ONLY effected the Github repo. https://youtube-dl.org/ . Having issues with MusicBot myself but YoutubeDL still works locally outside of MusicBot.

**Comment by Jimgersnap** [comment]
A fix for this was pushed to youtube-dl within an hour prior to it being taken down. A fork was found containing the committed change here:
https://github.com/nrdmn/youtube-dl/commit/416da574ec0df3388f652e44f7fe71b1e3a4701f

To install this fix: Clone the repo above, uninstall youtube-dl, use pip to install youtube-dl using the repo you just cloned, and restart your bot. Until there's an official repo for youtube-dl again this fix should pull you through.
