### ISSUE TITLE
Youtube-dl is taken down

### ISSUE THREAD

**Issue by Jeroeni** [Just-Some-Bots/MusicBot#2153]
Youtube-dl, the core of all musicbots is taken down with a DMCA notice and doesn't work anymore.

**Comment by monty-dev** [comment]
Youtube-DL is still fully functional - the takedown ONLY effected the Github repo. https://youtube-dl.org/ . Having issues with MusicBot myself but YoutubeDL still works locally outside of MusicBot.

**Comment by Jeroeni** [comment]
Yes, I should have added that YouTube authentication (only) fails in the MusicBot. Youtube-dl can obviously still be distributed and maintained on other platforms than GitHub (and is still up on pyPI I believe).
But it does mean that the RIAA means business and is trying it's hardest to kill bots like this one.

**Comment by AleanaA** [comment]
https://canary.discord.com/channels/129489631539494912/143334341500600320/769420461741965352
Until Youtube-DL is completely taken down, we will continue to support MusicBot based on Youtube-DL.
