### ISSUE TITLE
webM youtube video problem

### ISSUE THREAD

**Issue by nandadytm** [Just-Some-Bots/MusicBot#216]
Everytime the bot load video from youtube, if it's webm file and opus audio, it can't be played and just skipped. Bot runs on Centos 6.7 x64 using OpenVZ virtualization.

![eas](https://cloud.githubusercontent.com/assets/18608855/14732896/d642ec0e-0888-11e6-8991-04bbd7baa0ea.JPG)

**Comment by imayhaveborkedit** [comment]
If you could show me what `ffmpeg -codecs | grep vp` outputs that'd help.
Edit: and I guess `ffmpeg -codecs | grep opus` for that matter too

**Comment by nandadytm** [comment]
This is a screen shot for `ffmpeg -codecs | grep vp`

![1vp](https://cloud.githubusercontent.com/assets/18608855/14765777/7e365386-0a1b-11e6-8e46-32547f3396c1.JPG)

This is a screen shot for `ffmpeg -codecs | grep opus` 
![1opus](https://cloud.githubusercontent.com/assets/18608855/14765779/8d9c807a-0a1b-11e6-8ca5-0f37f07029f5.JPG)

There is nothing viewed in opus, though I have it installed
![3opus](https://cloud.githubusercontent.com/assets/18608855/14765786/c9ae3496-0a1b-11e6-83dd-7fe916ea0142.JPG)

**Comment by imayhaveborkedit** [comment]
The libopus dev headers don't do anything, they're used for compiling things that depend on libopus.  Your version of ffmpeg seems a bit old.  You might want to find a newer version or compile it yourself.
