### ISSUE TITLE
Starting... 'git' is not recognized as an internal or external command, operable program or batch file. Traceback (most recent call last):   File "C:\Users\PC\Documents\GitHub\MusicBot\update.py", line 40, in main     subprocess.check_call('git --version', shell=True, stdout=subprocess.DEVNULL)   File "C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call     raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command 'git --version' returned non-zero exit status 1.  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "C:\Users\PC\Documents\GitHub\MusicBot\update.py", line 76, in <module>     main()   File "C:\Users\PC\Documents\GitHub\MusicBot\update.py", line 42, in main     raise EnvironmentError("Couldn't use Git on the CLI. You will need to run 'git pull' yourself.") OSError: Couldn't use Git on the CLI. You will need to run 'git pull' yourself.

### ISSUE THREAD

**Issue by R3sTr0** [Just-Some-Bots/MusicBot#2168]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

-  X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Starting...
'git' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\PC\Documents\GitHub\MusicBot\update.py", line 40, in main
    subprocess.check_call('git --version', shell=True, stdout=subprocess.DEVNULL)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git --version' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PC\Documents\GitHub\MusicBot\update.py", line 76, in <module>
    main()
  File "C:\Users\PC\Documents\GitHub\MusicBot\update.py", line 42, in main
    raise EnvironmentError("Couldn't use Git on the CLI. You will need to run 'git pull' yourself.")
OSError: Couldn't use Git on the CLI. You will need to run 'git pull' yourself.

Run.bat is not working and update.bat is giving me that 

----

**Comment by onTDB** [comment]
You need to install git-scm or make sure your pc have the path on git.exe
