### ISSUE TITLE
error in player.py

### ISSUE THREAD

**Issue by shotty46290** [Just-Some-Bots/MusicBot#2169]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

I keep getting

Task exception was never retrieved
future: <Task finished name='Task-29' coro=<MusicPlayer._play() done, defined at C:\Users\swift\Desktop\MusicBot\musicbot\player.py:258> exception=TypeError("object Lock can't be used in 'await' expression")>
Traceback (most recent call last):
  File "C:\Users\swift\Desktop\MusicBot\musicbot\player.py", line 268, in _play
    with await self._play_lock:
TypeError: object Lock can't be used in 'await' expression

I try doing python --version in the cmd, and it says Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

But python is in the app execution aliases and if I disable it I get

python' is not recognized as an internal or external command,
operable program or batch file.

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5588713/musicbot.log)

**Comment by Jcodeerd** [comment]
Python 3.9 is not supported
And I recommend that you use python not via the ms store, but via the website and installer of 3.7

**Comment by shotty46290** [comment]
I did get python through the website not the MS store, I will uninstall 3.9 and get 3.7

**Comment by shotty46290** [comment]
I had both 3.9 and 3.7 installed, I got rid of 3.9 and I get the "deny new" error. Which I know ur suppose to use the python -m pip install -U discord.py[voice] command, but then I get that same message. Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was installed through their site not the MS store

**Comment by Jcodeerd** [comment]
>  Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
did you check the tickbox "add python to PATH"?

**Comment by shotty46290** [comment]
I think it was checked by default I can uninstall python and reinstall it to double check

**Comment by Jcodeerd** [comment]
fine

**Comment by shotty46290** [comment]
it was not checked by default, this had fixed it for me thank you. I saw in another post of auto joining not working is that a know bug right now? Because it didn't auto join.

**Comment by Jcodeerd** [comment]
auto joining isn't working?

**Comment by Jcodeerd** [comment]
can you send a log / screenshot

**Comment by shotty46290** [comment]
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5592838/musicbot.log)
![owner not found](https://user-images.githubusercontent.com/17259843/100152879-3704e700-2e58-11eb-8972-48049a0b0052.png)
It says that the owner is not found, I put up as well the picture of me in discord, verified that it was the right ID which it is

**Comment by Jcodeerd** [comment]
that owner is a bug, you need to use these intents in your developer options:
![image](https://user-images.githubusercontent.com/68161666/100155746-15335080-2ea8-11eb-8582-0db1e0d66c21.png)

**Comment by shotty46290** [comment]
![show](https://user-images.githubusercontent.com/17259843/100156500-e1333d80-2e5d-11eb-971c-eaf7c1a14aad.png)
here it shows them both being enabled, it is still failing to find the owner

**Comment by Jcodeerd** [comment]
huh, weird

**Comment by AutumnClove** [comment]
Fixed in review, run `git checkout review` and the error should go away.
