### ISSUE TITLE
[ERROR] launcher: Error starting bot

### ISSUE THREAD

**Issue by Mr-Robot-ops** [Just-Some-Bots/MusicBot#2170]
Please tick all applicable boxes.

- [ default Python 2.7.16] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [ ] The latest `review` version
- [x] release-260819-5-gc87dc05

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue

[ERROR] launcher: Error starting bot

### Steps to reproduce

pi@raspberrypi:~/Musicbot/MusicBot $ sudo ./run.py
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

Starting MusicBot release-260819-5-gc87dc05
Loaded autoplaylist with 2531 entries
Authenticated with Spotify successfully using client ID and secret.
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "./run.py", line 373, in main
    m.run()
  File "/home/pi/Musicbot/MusicBot/musicbot/bot.py", line 902, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 457, in connect
    await self._connect()
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 421, in _connect
    await self.ws.poll_event()
  File "/usr/local/lib/python3.7/dist-packages/discord/gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "/usr/local/lib/python3.7/dist-packages/discord/gateway.py", line 423, in received_message
    func(data)
  File "/usr/local/lib/python3.7/dist-packages/discord/state.py", line 663, in parse_guild_create
    guild = self._get_create_guild(data)
  File "/usr/local/lib/python3.7/dist-packages/discord/state.py", line 638, in _get_create_guild
    guild._from_data(data)
  File "/usr/local/lib/python3.7/dist-packages/discord/guild.py", line 391, in _from_data
    self._sync(guild)
  File "/usr/local/lib/python3.7/dist-packages/discord/guild.py", line 420, in _sync
    self._add_channel(VoiceChannel(guild=self, data=c, state=self._state))
  File "/usr/local/lib/python3.7/dist-packages/discord/channel.py", line 504, in init
    self._update(guild, data)
  File "/usr/local/lib/python3.7/dist-packages/discord/channel.py", line 535, in _update
    self._fill_overwrites(data)
  File "/usr/local/lib/python3.7/dist-packages/discord/abc.py", line 271, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'

[INFO] launcher: All done.
pi@raspberrypi:~/Musicbot/MusicBot $ git reset --hard
HEAD is now at c87dc05 add rhino
pi@raspberrypi:~/Musicbot/MusicBot $ git pull
Already up to date.
pi@raspberrypi:~/Musicbot/MusicBot $ python -m pip install -U -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pynacl==1.2.1 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/08/19/cf56e60efd122fa6d2228118a9b345455b13ffe16a14be81d025b03b261f/PyNaCl-1.2.1.tar.gz
Collecting discord.py[voice]==1.2.5 (from -r requirements.txt (line 2))
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement discord.py[voice]==1.2.5 (from -r requirements.txt (line 2)) (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.16.7, 0.16.8, 0.16.9, 0.16.10, 0.16.11, 0.16.12)
No matching distribution found for discord.py[voice]==1.2.5 (from -r requirements.txt (line 2))
pi@raspberrypi:~/Musicbot/MusicBot $

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5591552/musicbot.log)

**Comment by Jcodeerd** [comment]
__I started my bot, but there's and error!__
 
`__new__() got an unexpected keyword argument: 'deny_new'`



If you are on windows, simply do `py -m pip install -U discord.py[voice]` and that should fix it.
If you are on linux or mac os, do `pythonx.x -m pip install -U discord.py[voice]` and replace x.x with your python version, for example python3.7 and your error should be gone aswell.

You can also change the requirements.txt file so that it looks like this: 
```pynacl==1.4.0
discord.py[voice]==1.4.1
pip
youtube_dl
colorlog
```


Then run update.bat (If you're on windows, if not chose the appropriate update file for your system OS) once it's all up to date, then do run.bat (Same note as before). Please make sure to press n when asked if you'd like to reset files then y when asked if you'd still like to update dependencies.
