### ISSUE TITLE
Issue with running the bot

### ISSUE THREAD

**Issue by Supermarcel10** [Just-Some-Bots/MusicBot#2171]
Please tick all applicable boxes.

- [ x ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ x ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ x ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Current python version: 3.7.1. All dependencies are updated.

`[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
Traceback (most recent call last):
  File "run.py", line 438, in <module>
    main()
  File "run.py", line 347, in main
    finalize_logging()
  File "run.py", line 179, in finalize_logging
    dlh.setFormatter(logging.Formatter('.'))
  File "D:\Python 3.8.3\lib\logging\__init__.py", line 576, in __init__
    self._style.validate()
  File "D:\Python 3.8.3\lib\logging\__init__.py", line 429, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '.' for '%' style`

### Steps to reproduce

1. Run update.bat
2. Run run.bat

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5597852/musicbot.log)

**Comment by onTDB** [comment]
By looking on the log, you are using python 3.8.3 version. (Or 3.7 is requesting 3.8 pip packages)
So check, you are really using python 3.7.1

**Comment by AutumnClove** [comment]
As mentioned above you're using python 3.8 which currently doesn't work with the master branch, use review `git checkout review`
