### ISSUE TITLE
Bot fails to join the voice channel

### ISSUE THREAD

**Issue by NonDesu** [Just-Some-Bots/MusicBot#2172]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Bot fails to join the channel set to auto-join and errors on summon command

### Steps to reproduce

1. Run the bot
2. See it fail to join the voice channel
3. Attempt to summon it to the channel
4. See an error in the cmd

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5645885/musicbot.log)

**Comment by Jcodeerd** [comment]
run `py -3.7 -m pip install -U PyNaCl`

**Comment by NonDesu** [comment]
Still fails to join
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5645978/musicbot.log)

**Comment by Jcodeerd** [comment]
and `py -3.7 -m pip install -U discord.py[voice]`?

**Comment by NonDesu** [comment]
Same error
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5646837/musicbot.log)

**Comment by Jcodeerd** [comment]
can you try `pip install -U pynacl` (without the caps)

**Comment by NonDesu** [comment]
Still the same error
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5647089/musicbot.log)

**Comment by Jcodeerd** [comment]
could you send the other log?

**Comment by NonDesu** [comment]
What do you mean by the other?

**Comment by Jcodeerd** [comment]
isnt there a musicbot.log.lastest (or smth like that) in the logs folder?

**Comment by NonDesu** [comment]
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5647169/musicbot.log)

**Comment by NonDesu** [comment]
It seems the problem was with my python install, did a clean reinstall and now it is working
