### ISSUE TITLE
[ERROR] on bot startup

### ISSUE THREAD

**Issue by TamimTheWise** [Just-Some-Bots/MusicBot#2173]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [x] Feature request
- [x] Question

----

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by TamimTheWise** [comment]
ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xn7cga90/colorlog_c114fb9e48264375ba179b4f24f4ce1c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xn7cga90/colorlog_c114fb9e48264375ba179b4f24f4ce1c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-0luvwted
         cwd: /tmp/pip-install-xn7cga90/colorlog_c114fb9e48264375ba179b4f24f4ce1c/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xn7cga90/colorlog_c114fb9e48264375ba179b4f24f4ce1c/setup.py", line 2, in <module>
        from colorlog import __version__
      File "/tmp/pip-install-xn7cga90/colorlog_c114fb9e48264375ba179b4f24f4ce1c/colorlog/__init__.py", line 5, in <module>
        from colorlog import ColoredFormatter
    ImportError: cannot import name 'ColoredFormatter' from partially initialized module 'colorlog' (most likely due to a circular import) (/tmp/pip-install-xn7cga90/colorlog_c114fb9e48264375ba179b4f24f4ce1c/colorlog/__init__.py)

**Comment by onTDB** [comment]
Umm.. What python version are you using?

**Comment by tommyruen** [comment]
> Umm.. What python version are you using?

Similar to OP, I have the issue as well. I'm currently using python version 3.7.3.

**Comment by AutumnClove** [comment]
Try using review, and tell me what happens, the requirements.txt folder has been updated in review so might fix.

**Comment by AutumnClove** [comment]
I never got a response on using review so I'm closing, two people out of several isn't enough for me to keep this open.
