### ISSUE TITLE
why it can,t find owner i tryed everything but it can,t find it's owner pls help me to solve this problem

### ISSUE THREAD

**Issue by Senpai899** [Just-Some-Bots/MusicBot#2174]
Please tick all applicable boxes.

- [ ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
WARNING: Owner could not be found on any guild (id: 66656858557755986)

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by Jcodeerd** [comment]
enable 
![image](https://user-images.githubusercontent.com/68161666/102695130-b3a39f00-4225-11eb-8417-5a00eeb4ebe1.png) in the discord developer thing

**Comment by AutumnClove** [comment]
Fixed in review, just make sure to go to [Discord Developer Portal](https://discord.com/developers/docs/intro) and enable intents as shown in the above image.
