### ISSUE TITLE
musicbot module is not importable

### ISSUE THREAD

**Issue by N1h1l1sT** [Just-Some-Bots/MusicBot#2175]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
When the bot starts on Windows, I get the error that these 2 guys were getting (musicbot module is not importable):
* https://github.com/Just-Some-Bots/MusicBot/issues/1864
* https://github.com/Just-Some-Bots/MusicBot/issues/1553

The way I solved this error was to rename the "MusicBot" folder inside the MusicBot installpath to "musicbot" all-lowercase.
As soon as I did that, the problem was fixed. I got the idea by opening "run.py" and seeing that it checked for "musicbot" subfolder, not "MusicBot".

### Steps to reproduce

1. On a Windows 10 system, follow the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for your system
2. After you get the error that `version of discord.py[voice] in requirements.txt depends on a different pynacl version than the pynacl version mentioned on requirements.txt and pip cannot resolve the issue`, delete the version requirement of pynacl and only leave the name. now retry installing requirements.txt via update.py which will work now.
3. Rename the subfolder "MusicBot" to "musicbot" so that run.py doesn't give you `musicbot module is not importable`
4. find and open file "voice_client.py" (use the programme "Everything" if you can't find the file) and now seach for ".replace(':80', '')" and add ".replace(':443', '')" just after it without any spaces. This will fix error `gaierror(11001, 'getaddrinfo failed')` where even though the bot is up and has joined your channel, it won't be able to play any music (at least from youtube which is how i used it).
5. Enjoy!

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by Jcodeerd** [comment]
I can't find "MusicBox" or "musicbot" in run.py?
And btw, I think this solution is too complicated for most users.

**Comment by N1h1l1sT** [comment]
Open run.py with an advanced notepad like notepad++
Ctrl+F to open search, and search for "musicbot"
There it is! (currently line 305) under def req_ensure_env():

However, I'm not saying to change anything inside the run.py script! I merely say, rename the actual folder.
I'm pretty sure that renaming the "MusicBot" subfolder to "musicbot" is not too complicated for most users.
But that's just my opinion.

**Comment by Jcodeerd** [comment]
> However, I'm not saying to change anything inside the run.py script 
well, I was talking about the changes in voice_client.py


and, I cant find "musicbox" in run.py?

![image](https://user-images.githubusercontent.com/68161666/102711922-85719e00-42bd-11eb-9dbe-de9e54e88eb9.png)

**Comment by N1h1l1sT** [comment]
Oh, I see where the confusion lies. I apologise. "voice_client.py" is a file in its own right.

I don't expect people know where to find it, for instance, for me it's located in: C:\Users\GiannisM\AppData\Roaming\Python\Python37\site-packages\discord\voice_client.py
That's why I suggest that people download the programme "Everything" which is a powerful search programme and they just type "voice_client.py".
"Everything" will instantly locate it.

Remember however, that this fix is not for "musicbot module is not importable", it's a bonus fix for:
```
Task exception was never retrieved
future: <Task finished coro=<VoiceClient._create_socket() done, defined at C:\Users\GiannisM\AppData\Roaming\Python\Python37\site-packages\discord\voice_client.py:171> exception=gaierror(11001, 'getaddrinfo failed')>
Traceback (most recent call last):
  File "C:\Users\GiannisM\AppData\Roaming\Python\Python37\site-packages\discord\voice_client.py", line 190, in _create_socket
    self.endpoint_ip = socket.gethostbyname(self.endpoint)
socket.gaierror: [Errno 11001] getaddrinfo failed
```

**Comment by Jcodeerd** [comment]
`py -3 -m pip install -U discord.py discord.py[voice]` is an more easy fix for the getaddrinfo error

**Comment by N1h1l1sT** [comment]
Yeah, that seems a straightforward solution for it.
However, for me personally, it introduces another problem: `WARNING: Owner could not be found on any guild (id: {MyIDWhichIDeleted})`
I'll stick to my solution for now but for the rest of the people, if this problem does not arise, your solution is definitely much better.

**Comment by Jcodeerd** [comment]
You need to enable this 2 options

![image](https://user-images.githubusercontent.com/68161666/102713024-6a0a9100-42c5-11eb-839d-462bd98ea19d.png)

**Comment by N1h1l1sT** [comment]
Unfortunately I still get `WARNING: Owner could not be found on any guild (id: {DeletedIDHere})`
On the "Bot" tab, my permissions are exactly like yours on the picture. Pushed save and refreshed the page to be sure. They're saved.

**Comment by AutumnClove** [comment]
Updated in review, make sure to go to the [Discord Developer Portal](https://discord.com/developers/docs/intro) and enable intents on your bot application settings
