### ISSUE TITLE
Bro

### ISSUE THREAD

**Issue by GeeBoo-Rgb** [Just-Some-Bots/MusicBot#2178]
What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [how do I enable requires grant code in DISCORD BOT ] Question

----

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by Roadhog360** [comment]
Bro
![image](https://user-images.githubusercontent.com/11903511/103396091-230b6f80-4aff-11eb-8f9f-945826208d4b.png)
