### ISSUE TITLE
cannot use Play command

### ISSUE THREAD

**Issue by GysStar** [Just-Some-Bots/MusicBot#2188]
Please tick all applicable boxes.

- [ ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [V ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

I set up a MusicBot on Raspberry Pi. when i run the Bot , its still ok until i use Play command, nothing happen and the bot disconnnect the channel and said that the bot is not in the channel , i need to use !summon. then i do it again but still got that problem

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by Jcodeerd** [comment]
log?
