### ISSUE TITLE
Suddenly cannot play SoundCloud links

### ISSUE THREAD

**Issue by Sambish** [Just-Some-Bots/MusicBot#219]
Hi,

As of recently, I have been unable to play SoundCloud links and only YouTube ones when attempting to add songs to the queue of the bot. When doing so, I get a 403 forbidden error in the console suggesting that the resource cannot be accessed. Any solutions to this? 

![error](https://cloud.githubusercontent.com/assets/7619629/14754851/050460ac-08d6-11e6-84f1-cdf2bdc3817e.png)

Thanks.

**Comment by arunesh90** [comment]
Make sure you're running RC7. If you're still having problems with that, try review branch.
And if that doesn't work, then youtube has temporarily blocked you're server because it's making too many requests in a short time.

**Comment by Sambish** [comment]
I tried the bot on multiple servers and SoundCloud doesn't work on any of them. I'll have a look at the review branch, thanks. :)

**Comment by imayhaveborkedit** [comment]
Not discord server, the computer that you're running the bot from.  This may just be a case of "something changed and youtubedl needs an update" or it might be completely random and will go away at some point.

**Comment by Sambish** [comment]
When referring to the server I meant the computer that it was running off of. Apologies for not being clear enough.
