### ISSUE TITLE
Spotify (guest) broken

### ISSUE THREAD

**Issue by Jcodeerd** [Just-Some-Bots/MusicBot#2190]
Please tick all applicable boxes.

- [V ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [V ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [V ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [V ] The latest `review` version

What type of issue are you creating?

- [V ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

![image](https://user-images.githubusercontent.com/68161666/107350675-01bc7c80-6aca-11eb-830b-28e8e44f7c55.png)

you get an 404 error, while trying to use spotify (atleast: in guest mode)

I might Spotify might have changed how their API works, but im not sure.

### Steps to reproduce

1.  setup the bot
2. run the bot
3. get the error

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

-

**Comment by amit177** [comment]
I'm not seeing that issue.
Please attach your log file.

**Comment by Jcodeerd** [comment]
[log.txt](https://github.com/Just-Some-Bots/MusicBot/files/5978106/log.txt)

**Comment by amit177** [comment]
What do you see when you open https://open.spotify.com/get_access_token?reason=transport&productType=web_player in browser?

**Comment by Jcodeerd** [comment]
![image](https://user-images.githubusercontent.com/68161666/107934975-07f6a100-6f81-11eb-9142-9117f9aa4a03.png)

**Comment by sarker727** [comment]
sorry to use

**Comment by Jcodeerd** [comment]
> sorry to use

wdym, @sarker727

**Comment by amit177** [comment]
Thank you, fixed in #2201
Hopefully will be merged soon to review.
