### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by shchan618** [Just-Some-Bots/MusicBot#2191]
Please tick all applicable boxes.

- [ ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

The following error occurs when running update.bat:

Starting...
'git' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "update.py", line 40, in main
    subprocess.check_call('git --version', shell=True, stdout=subprocess.DEVNULL)
  File "C:\Users\ChoMu\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git --version' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update.py", line 76, in <module>
    main()
  File "update.py", line 42, in main
    raise EnvironmentError("Couldn't use Git on the CLI. You will need to run 'git pull' yourself.")
OSError: Couldn't use Git on the CLI. You will need to run 'git pull' yourself.

### Steps to reproduce

1. run update.bat

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by Jcodeerd** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/2168

Install Git for Windows.
During the setup, tick Git from the command line and also 3rd-party software, Checkout Windows-style, commit Unix-style endings, and Use MinTTY (the default terminal MSYS2).

https://just-some-bots.github.io/MusicBot/installing/windows/

**Comment by shchan618** [comment]
Thank you. I solved the problem.
