### ISSUE TITLE
[FEATURE REQUEST] Music Speed Command

### ISSUE THREAD

**Issue by JackCloudman** [Just-Some-Bots/MusicBot#2192]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

### Description
Can you add an option to set speed like 1.5x to play music?
Thanks.

**Comment by StefanLapointe** [comment]
Should this function like youtube's speed setting where the pitch does not change or should the natural pitch change that occurs with a speed change be allowed to happen? (I think the latter is a lot simpler and sounds better.)

**Comment by JackCloudman** [comment]
some years ago I modified the source code, very easy for the second method :D

**Comment by BabyBoySnow** [comment]
There is now an option for default speed and a command to adjust on the fly
