### ISSUE TITLE
Batch scripts are not working

### ISSUE THREAD

**Issue by nkrth** [Just-Some-Bots/MusicBot#2195]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
The scripts are not working on Windows 10.
pynacl 1.2.1 is not installable.
I've tried `python -m pip install -U -r requirements.txt` but even still it fails.
The `run.bat` also returns errors but it looks unrelated to the update failure.
```
>run.bat
Traceback (most recent call last):
  File "run.py", line 438, in <module>
    main()
  File "run.py", line 347, in main
    finalize_logging()
  File "run.py", line 179, in finalize_logging
    dlh.setFormatter(logging.Formatter('.'))
  File "C:\Python39\lib\logging\__init__.py", line 570, in __init__
    self._style.validate()
  File "C:\Python39\lib\logging\__init__.py", line 423, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '.' for '%' style
```

### Steps to reproduce

1. run `update.bat` in cmd.exe and receive unresolvable errors
2. run `run.bat` in cmd.exe

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5992353/musicbot.log)

**Comment by Jcodeerd** [comment]
Change to review `git checkout review `
Or uninstall python 3.8 and use 3.7
