### ISSUE TITLE
Project is dead. 

### ISSUE THREAD

**Issue by monty-dev** [Just-Some-Bots/MusicBot#2196]
I just wanted to share for others that this project is dead. This code is broken and does not work as is.

**Comment by AutumnClove** [comment]
The review branch is being updated, we're working on having the github page updated to the correct version of python as we're updating to 3.8 as the minimum, and changing all the guides, as well as adding intents somewhere in the guide, it's a process, it's not dead, it just takes time, especially when there's still a pandemic being recovered over.
