### ISSUE TITLE
Trying to download the bot code and then change it to my old bot but can't even get to there

### ISSUE THREAD

**Issue by LuxCromwell** [Just-Some-Bots/MusicBot#2197]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
ERROR: Cannot install discord-py[voice]==1.2.5 and pynacl==1.2.1 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

### Steps to reproduce

1. Run update.bat after downloading the clone 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/6026855/musicbot.log)

**Comment by AutumnClove** [comment]
Edit requirements.txt so that there's no equals after it, or if you want you can switch to review just make sure to enable intents in the discord developer portal, and have python 3.8+
