### ISSUE TITLE
Bot Conflict Error

### ISSUE THREAD

**Issue by RyuujiTakasu025** [Just-Some-Bots/MusicBot#2199]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "C:\Users\Johann\Downloads\Music Bot\MusicBot\musicbot\__init__.py", line
 7, in <module>
    from .utils import _get_variable
  File "C:\Users\Johann\Downloads\Music Bot\MusicBot\musicbot\utils.py", line 3,
 in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
[INFO] launcher: Attempting to install dependencies...
Collecting pynacl==1.2.1
  Using cached PyNaCl-1.2.1-cp37-cp37m-win32.whl (158 kB)
Collecting discord.py[voice]==1.2.5
  Using cached discord.py-1.2.5-py3-none-any.whl (655 kB)
Requirement already satisfied: pip in c:\users\johann\appdata\local\programs\pyt
hon\python37-32\lib\site-packages (from -r requirements.txt (line 3)) (21.0.1)
Collecting youtube_dl
  Using cached youtube_dl-2021.3.3-py2.py3-none-any.whl (1.9 MB)
Collecting colorlog
  Using cached colorlog-4.7.2-py2.py3-none-any.whl (10 kB)
Collecting cffi
  Using cached cffi-1.14.5-cp37-cp37m-win32.whl (166 kB)
Collecting websockets<7.0,>=6.0
  Using cached websockets-6.0-cp37-cp37m-win32.whl (83 kB)
Collecting aiohttp<3.6.0,>=3.3.0
  Using cached aiohttp-3.5.4-cp37-cp37m-win32.whl (583 kB)
ERROR: Cannot install discord-py[voice]==1.2.5 and pynacl==1.2.1 because these p
ackage versions have conflicting dependencies.

The conflict is caused by:
    The user requested pynacl==1.2.1
    discord-py[voice] 1.2.5 depends on PyNaCl==1.3.0; extra == "voice"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_g
uide/#fixing-conflicting-dependencies

[CRITICAL] launcher: You may need to run as admin to install dependencies.

[INFO] launcher: All done.

C:\Users\Johann\Downloads\Music Bot\MusicBot>

### Steps to reproduce

1.  run.bat

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by Jcodeerd** [comment]
__**Change the requirements.txt file so that it looks like this:**__
```
pynacl
discord.py[voice]
pip
youtube_dl
colorlog
```

Then run update.bat(if your on windows, if not chose the appropriate update file for your system OS) once it's all up to date, then do run.bat(same note as before). Make to to press `n` and then `y` that way it doesn't reset the requirements.txt file back to the original.

__**Why do I need to change the**__ requirements.txt file?
Discord pushed an update that broke discord.py, it was fixed in a new version of discord.py however we haven't updated the requirements.txt file to target the latest version of discord.py with the fix.

**Comment by AutumnClove** [comment]
You can also use review, but you'll need to turn on [intents](https://cdn.discordapp.com/attachments/157598062020132865/805018713358729216/unknown.png)
