### ISSUE TITLE
Errors shouldn't be sent to Discord

### ISSUE THREAD

**Issue by wang429** [Just-Some-Bots/MusicBot#22]
Slightly separate from the other issue about logging, but error messages shouldn't be visible in discord chat. Mention that an error has occurred, but not the stacktrace.

**Comment by Neddz** [comment]
I totally agree with this. That information is unnecessary to common users and the owner can easily access the log.

**Comment by deansheather** [comment]
+1

**Comment by imayhaveborkedit** [comment]
That was added so it was easier to figure out what happened when something broke when we were building the bot.  That can be changed at any time.

**Comment by t-v** [comment]
I really found it a very handy feature.
But maybe you can make a var out of it and put it in the config file?
Something like 
if debug == True:
  post the error output.

**Comment by imayhaveborkedit** [comment]
When I add logging for everything i'll have a debug option

**Comment by Chew** [comment]
Maybe add the option to PM the owner the log issues?

**Comment by jayktaylor** [comment]
If the `DebugLevel` in the config is set to `DEBUG`, messages will be printed to Discord with tracebacks. Otherwise, they won't.
