### ISSUE TITLE
pynacl and discord.py error

### ISSUE THREAD

**Issue by DoyunShin** [Just-Some-Bots/MusicBot#2200]
Please tick all applicable boxes.

- [v] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [v] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [v] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [v] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

python3.7 -m pip install -U -r requirements.txt

ERROR: Cannot install discord-py[voice]==1.2.5 and pynacl==1.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pynacl==1.2.1
    discord-py[voice] 1.2.5 depends on PyNaCl==1.3.0; extra == "voice"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by Jcodeerd** [comment]
Change the requirements.txt file so that it looks like this:
pynacl
discord.py[voice]
pip
youtube_dl
colorlog


Then run update.bat(if your on windows, if not chose the appropriate update file for your system OS) once it's all up to date, then do run.bat(same note as before). Make to to press n and then y that way it doesn't reset the requirements.txt file back to the original.

Why do I need to change the requirements.txt file?
Discord pushed an update that broke discord.py, it was fixed in a new version of discord.py however we haven't updated the requirements.txt file to target the latest version of discord.py with the fix.

**Comment by DoyunShin** [comment]
```
tklco@servicevm02:~/MusicBot$ ./update.sh
./update.sh: line 7: python: command not found
./update.sh: line 7: python: command not found
./update.sh: line 7: python: command not found
./update.sh: line 9: python3.5: command not found
./update.sh: line 10: python3.6: command not found
./update.sh: line 14: [: no py: integer expression expected
Starting...
Passed Git checks...
You have modified files that are tracked by Git (e.g the bot's source files).
Should we try resetting the repo? You will lose local modifications. (y/n): y
HEAD is now at c87dc05 add rhino
Checking if we need to update the bot...
Already up to date.
Attempting to update dependencies...
Collecting pynacl==1.2.1
  Downloading PyNaCl-1.2.1-cp34-abi3-manylinux1_x86_64.whl (690 kB)
     |████████████████████████████████| 690 kB 1.4 MB/s
Collecting discord.py[voice]==1.2.5
  Using cached discord.py-1.2.5-py3-none-any.whl (655 kB)
Requirement already satisfied: pip in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 3)) (21.0.1)
Requirement already satisfied: youtube_dl in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 4)) (2021.3.14)
Requirement already satisfied: colorlog in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 5)) (4.7.2)
Requirement already satisfied: cffi in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 6)) (1.14.5)
Collecting websockets<7.0,>=6.0
  Downloading websockets-6.0.tar.gz (70 kB)
     |████████████████████████████████| 70 kB 7.0 MB/s
Collecting aiohttp<3.6.0,>=3.3.0
  Downloading aiohttp-3.5.4.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 42.9 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
ERROR: Cannot install discord-py[voice]==1.2.5 and pynacl==1.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pynacl==1.2.1
    discord-py[voice] 1.2.5 depends on PyNaCl==1.3.0; extra == "voice"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
Traceback (most recent call last):
  File "update.py", line 17, in update_deps
    subprocess.check_call('"{}" -m pip install --no-warn-script-location --user -U -r requirements.txt'.format(sys.executable), shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"/usr/bin/python3" -m pip install --no-warn-script-location --user -U -r requirements.txt' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update.py", line 76, in <module>
    main()
  File "update.py", line 72, in main
    update_deps()
  File "update.py", line 19, in update_deps
    raise OSError("Could not update dependencies. You will need to run '\"{0}\" -m pip install -U -r requirements.txt' yourself.".format(sys.executable))
OSError: Could not update dependencies. You will need to run '"/usr/bin/python3" -m pip install -U -r requirements.txt' yourself.

```

**Comment by DoyunShin** [comment]
hmn.. i'm using python3.7 but update.sh script use python3.8

**Comment by DoyunShin** [comment]
i changed requirements.txt to

_pynacl
discord.py[voice]
pip
youtube_dl
colorlog_

and updated these libraries
and bot cannot find owner id
```
tklco@servicevm2:~/MusicBot$ python3.7 run.py
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

Starting MusicBot release-260819-5-gc87dc05
Loaded autoplaylist with 2531 entries

Connected: 51616183******4671/************ (βeta)#1***
WARNING: Owner could not be found on any guild (id: 6490747931******58)

Guild List:
 - Twi**********
 - Emoji-DB

Not bound to any text channels
Not autojoining any voice channels
```


(Config file)
`OwnerID = 57338063******1570`

(And bot is under the teams)

**Comment by Jcodeerd** [comment]
use this command: git checkout review
and:


![image](https://user-images.githubusercontent.com/68161666/111068813-96037000-84ca-11eb-9c13-a86fdceeb7a0.png)

**Comment by AutumnClove** [comment]
I'm assuming everything is working now I'll reopen if there's more questions

**Comment by Artemis21** [comment]
Sorry to bump this but for anyone with the same issue: I also had to add `websockets` to `requirements.txt`.

**Comment by AutumnClove** [comment]
HOW DARE YOU...LOL jk you cool. Websockets is weird because sometimes you need to install it and other times you don't.

**Comment by jaykimjay06** [comment]
누구세요

2021년 6월 6일 (일) 오전 10:10, Winter ***@***.***>님이 작성:
