### ISSUE TITLE
[FEATURE REQUEST] Loop the queue.

### ISSUE THREAD

**Issue by benjjvi** [Just-Some-Bots/MusicBot#2205]
Please tick all applicable boxes.

- [✔️] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [✔️] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [✔️] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [✔️] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [✔️] Feature request
- [ ] Question

----

### Description of request
Hey :)

I've been trying to implement a repeat/loop function into the bot for a while now, but I have always found it confusing to maneuver, so I am putting in this issue.

Would it be possible for you to implement this repeater/loop function to the bot? Where essentially at the end of a song, it copies that request's data from the queue.json file, and moves it to the end of the file.

**Comment by nate2014jatc** [comment]
This would be incredibly convenient for our DnD campaigns.

If the maintainer is up for it, I'd be willing to talk to my group about sending a bug bounty or something.

**Comment by AutumnClove** [comment]
#1677 although outdated I'd look into resourcing that as a starting point.
