### ISSUE TITLE
play command not working

### ISSUE THREAD

**Issue by cornelab0** [Just-Some-Bots/MusicBot#2210]
Please tick all applicable boxes.

- [✔ ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [✔ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [✔ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [✔ ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [✔ ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

When i want to play something doesn't work. idk what i am doing wrong, please help.

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/6457066/musicbot.log)

**Comment by DestinyofYeet** [comment]
You have to !join the bot into your  channel, it won't autojoin into your channel if you want to play something.

If you do !join and it still fails, check if the bot has permission to join the channel.

**Comment by cornelab0** [comment]
the bot is joining in my channel, but !play, !search, !np etc is not working.

**Comment by DestinyofYeet** [comment]
The thing is, in the log, it doesn't even attempt to download  / search anything. Maybe double check your bot prefix.

**Comment by cornelab0** [comment]
the prefix in ok, cause another commands are working like !summon, !help, only youtube commands are not working.
