### ISSUE TITLE
Error You don't have permission to use that command. Reason: This command is not enabled for your group (Default).

### ISSUE THREAD

**Issue by GitHubIchiGo** [Just-Some-Bots/MusicBot#2211]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by GitHubIchiGo** [comment]
owner owner can summon not any members can summon
please help

**Comment by DestinyofYeet** [comment]
I'd recommend to read through the [permissions page](https://just-some-bots.github.io/MusicBot/using/permissions/) on our tutorial.

**Comment by GitHubIchiGo** [comment]
how to give all permission @DestinyofYeet 
Error
You don't have permission to use that command.
Reason: This command is not enabled for your group (Default).

**Comment by DestinyofYeet** [comment]
Did you read the permissions page i linked?

**Comment by GitHubIchiGo** [comment]
yeah but i didnt get it pls explain

**Comment by DestinyofYeet** [comment]
what didn't you get

**Comment by GitHubIchiGo** [comment]
like users cant even pause and summon the bot in vc pls say me the commands

**Comment by GitHubIchiGo** [comment]
other servers owners adding the bot but they cant summon in vc

**Comment by DestinyofYeet** [comment]
1. Delete that comment, you just published your token

**Comment by GitHubIchiGo** [comment]
how can i send you in private pls say

**Comment by GitHubIchiGo** [comment]
im sure that you have seened the Permissions and option file pls say now wht to do

**Comment by DestinyofYeet** [comment]
If you give the permissions.ini file a read you will stumble over this line here:
```
;    CommandWhitelist = play skip pause
;    List of commands users are allowed to use, separated by spaces.  Don't include the prefix, i.e. !  Overrides CommandBlacklist if set.
```

Now that you know that, do you have an idea of what you could do to make your bot the way you want it to?

**Comment by GitHubIchiGo** [comment]
see bro i just want that other servers owner adding my bot should have permission to summon in their vc

**Comment by DestinyofYeet** [comment]
Change
```
[Default]
CommandWhitelist = play perms queue np skip search id help clean
; CommandBlacklist =
IgnoreNonVoice = play skip search
MaxSongLength = 1200
MaxSongs = 0
MaxSearchItems = 10
AllowPlaylists = yes
; MaxPlaylistLength = 20
InstaSkip = no
Remove = no
SkipWhenAbsent = no
BypassKaraokeMode = no
Extractors = generic youtube youtube:playlist soundcloud
```
to
```
[Default]
CommandWhitelist = play perms queue np skip search id help clean
; CommandBlacklist =
IgnoreNonVoice = play skip search join
MaxSongLength = 1200
MaxSongs = 0
MaxSearchItems = 10
AllowPlaylists = yes
; MaxPlaylistLength = 20
InstaSkip = no
Remove = no
SkipWhenAbsent = no
BypassKaraokeMode = no
Extractors = generic youtube youtube:playlist soundcloud
```

**Comment by GitHubIchiGo** [comment]
it works Thanks
