### ISSUE TITLE
how do i run the bot?

### ISSUE THREAD

**Issue by MasonTheMong** [Just-Some-Bots/MusicBot#2215]
ive done all config but idk how to start the bot?

**Comment by AutumnClove** [comment]
run.bat (windows) run.sh (Linux) for mac you'd have to navigate to your MusicBot folder then `python3.7 run.py` however you'll probably run into some issues if you're not using the review branch so I'd suggest that, as well as heading over to our [server](https://www.discord.gg/bots) so we can quickly help to our best abilities.
