### ISSUE TITLE
MusicBot is not working in vc

### ISSUE THREAD

**Issue by Sar-1124** [Just-Some-Bots/MusicBot#2219]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
When the Discord bot enters the voice channel, it fails to function with the following error:
I am using Google Cloud Hosting now and the operating system is Ubuntu 20.04.2 LTS.

### Steps to reproduce

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
Starting MusicBot release-260819-5-gc87dc05
Loaded autoplaylist with 2531 entries
Connected: 864498472573075487/GalaxyBot#0153
Owner:     385396101030608896/사르_#3712
Guild List:
 - 나락
Not bound to any text channels
Not autojoining any voice channels
726079050455449702/Xigncode#3333: *j
Task exception was never retrieved
future: <Task finished coro=<VoiceClient._create_socket() done, defined at /home/twitchgudok/.local/lib/python3.7/site-pac
kages/discord/voice_client.py:172> exception=gaierror(-2, 'Name or service not known')>
Traceback (most recent call last):
  File "/home/twitchgudok/.local/lib/python3.7/site-packages/discord/voice_client.py", line 191, in _create_socket
    self.endpoint_ip = socket.gethostbyname(self.endpoint)
socket.gaierror: [Errno -2] Name or service not known
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/home/twitchgudok/MusicBot/musicbot/bot.py", line 2813, in on_message
    response = await handler(**handler_kwargs)
  File "/home/twitchgudok/MusicBot/musicbot/bot.py", line 1927, in cmd_summon
    player = await self.get_player(author.voice.channel, create=True, deserialize=self.config.persistent_queue)
  File "/home/twitchgudok/MusicBot/musicbot/bot.py", line 421, in get_player
    voice_client = await self.get_voice_client(channel)
  File "/home/twitchgudok/MusicBot/musicbot/bot.py", line 386, in get_voice_client
    return await channel.connect(timeout=60, reconnect=True)
  File "/home/twitchgudok/.local/lib/python3.7/site-packages/discord/abc.py", line 1080, in connect
    await voice.connect(reconnect=reconnect)
  File "/home/twitchgudok/.local/lib/python3.7/site-packages/discord/voice_client.py", line 218, in connect
    await self.start_handshake()
  File "/home/twitchgudok/.local/lib/python3.7/site-packages/discord/voice_client.py", line 154, in start_handshake
    await asyncio.wait_for(self._handshake_complete.wait(), timeout=self.timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by DestinyofYeet** [comment]
Stop your bot, run `python3.7 -m pip install -U discord.py[voice]`, then start your bot again.

**Comment by Sar-1124** [comment]
> 봇을 중지하고 실행한 다음 봇을 다시 시작합니다.`python3.7 -m pip install -U discord.py[voice]`

The same error occurs when you run the command above. What should I do?
///Works after reinstalling discord.py [music]. Thank you!

**Comment by DestinyofYeet** [comment]
Ok nice, np :D
