### ISSUE TITLE
[Feature Request] Apply cookies at the start of the bot from a config file

### ISSUE THREAD

**Issue by LiderKonmils** [Just-Some-Bots/MusicBot#2221]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

### Description of issue

As i've been told (https://github.com/Just-Some-Bots/MusicBot/issues/2220) , to play restricted videos from Youtube, we need to apply cookies to a running Youtube-dl... First, i don't understand how to do that, and second, needing to do that every time i need to restart the bot is not an option for me. 

Can you add a line in any config file to apply it when starting the bot?

### Steps to reproduce

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AutumnClove** [comment]
I've solved it, after @AutumnClove message, if you want to use cookies file in order to bypass age-restriction on videos you need to download you cookies file from youtube in netscape format (i used "Get cookies.txt" extension to a browser).
In order to use the cookies in MusicBot you need to add 'cookiefile': 'Cookies location', in downloader.py file located in MusicBot/musicbot/downloader.py in ytdl_format_options.
Im not getting Unable to extract video data error anymore, so if you have that problem try doing that.
See #2118 I'll keep this open as an possible PR for someone in hactober 🤣

**Comment by LiderKonmils** [comment]
I've tried it, but since i don't have clear explainations and examples, i'Ve done something and now the bot refuse to start.
<details>
<summary>Pics of what happen</summary>

![001](https://user-images.githubusercontent.com/1256145/126992989-4eba6e72-4e5c-4d53-a92d-c800b69ad029.png)
![002](https://user-images.githubusercontent.com/1256145/126993007-6907dcdd-50be-445d-86ca-a13af2a5be21.png)
![003](https://user-images.githubusercontent.com/1256145/126993013-643fd91e-62c7-4f82-8c11-4214d604e529.png)
![004](https://user-images.githubusercontent.com/1256145/126993026-d6ee94e4-8b3b-4757-980e-9650f28a6a98.png)
![005](https://user-images.githubusercontent.com/1256145/126993036-3d1cbec2-e94e-443e-a4ae-182c5eb3c4b1.png)
</details>

**Comment by AutumnClove** [comment]
Don't use notepad use something like notepad++, sublime text, VSC, etc and tabs not spaces.

**Comment by Jcodeerd** [comment]
its not notepad tho :P

**Comment by LiderKonmils** [comment]
What i did:
<details>

![006](https://user-images.githubusercontent.com/1256145/127008133-8adc9ce8-1bfb-46ba-a0b1-581c19fdcd5a.png)

</details>

**Comment by DestinyofYeet** [comment]
You need to escape the `'\'` when writing in the path in the .py file using `'\\'`. So for every `'\'` in your path, you need to put another `'\'` in so you have `'\\'` in the end.

Example:

`Raw: C:\Users\Admin\Desktop`
`Escaped: C:\\Users\\Admin\\Desktop`

**Comment by SimonDKiller** [comment]
Still not working.
<details>
![image](https://user-images.githubusercontent.com/1256145/127030158-1197b168-36e9-452f-b33c-f9fcdc8c5515.png)
![image](https://user-images.githubusercontent.com/1256145/127030212-a4ce6232-1b18-4175-8d9e-9e3525e8e83c.png)
</details>

**Comment by DestinyofYeet** [comment]
Can you send in a screenshot of what you currently have in your editor?

**Comment by LiderKonmils** [comment]
Ok, i made a change, by adding a "," at the end of the line before:
<details>

![image](https://user-images.githubusercontent.com/1256145/127030900-794b655e-f93d-4a81-93a6-31d15ac860fa.png)

</details>

and now, i have this:
<details>

![image](https://user-images.githubusercontent.com/1256145/127030987-8b419142-2755-4d10-9489-e93300274dc0.png)

</details>

**Comment by DestinyofYeet** [comment]
i think you need to specify the full path to your cookie file, like `...\\Cookie\\cookies.txt` or whatever you named the file.

**Comment by LiderKonmils** [comment]
Goooood, now that's working... but yeah... please, Devs, add a line in the options.ini to get the cookie file easier... for a non-programmer like me, it was a pain in the a**. And THANK YOU a lot @DestinyofYeet for your help.

**Comment by BabyBoySnow** [comment]
So I was looking into making this an option for users, but it turns out to be a bit of a pain, when  trying to add the option to the downloader handler, as I can't do something like self config in ytdl setttings. I am going to close this.
