### ISSUE TITLE
Can not start the MusicBot on CentOS7

### ISSUE THREAD

**Issue by vccl3595** [Just-Some-Bots/MusicBot#2222]
Please tick all applicable boxes.

- [* ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [* ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [* ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [* ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [* ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Can not run the MusicBot by Python 3.5.7

[root@music MusicBot]# python run.py
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "/home/github/MusicBot/musicbot/__init__.py", line 74, in <module>
    from .bot import MusicBot
  File "/home/github/MusicBot/musicbot/bot.py", line 31, in <module>
    from .player import MusicPlayer
  File "/home/github/MusicBot/musicbot/player.py", line 17, in <module>
    from websockets.exceptions import InvalidState
ImportError: No module named 'websockets'
[INFO] launcher: Attempting to install dependencies...
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Requirement already satisfied: pynacl in /root/.pyenv/versions/3.5.7/lib/python3.5/site-packages (from -r requirements.txt (line 1)) (1.4.0)
Collecting pynacl
  Using cached PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl (961 kB)
  Using cached PyNaCl-1.3.0-cp34-abi3-manylinux1_x86_64.whl (759 kB)
Requirement already satisfied: discord.py[voice] in /root/.pyenv/versions/3.5.7/lib/python3.5/site-packages (from -r requirements.txt (line 2)) (1.7.3)
Collecting discord.py[voice]
  Using cached discord.py-1.7.3-py3-none-any.whl (786 kB)
  Using cached discord.py-1.7.2-py3-none-any.whl (786 kB)
Requirement already satisfied: pip in /root/.pyenv/versions/3.5.7/lib/python3.5/site-packages (from -r requirements.txt (line 3)) (20.3.4)
Collecting pip
  Using cached pip-20.3.4-py2.py3-none-any.whl (1.5 MB)
  Using cached pip-20.3.3-py2.py3-none-any.whl (1.5 MB)
Requirement already satisfied: youtube_dl in /root/.pyenv/versions/3.5.7/lib/python3.5/site-packages (from -r requirements.txt (line 4)) (2021.6.6)
Collecting youtube_dl
  Using cached youtube_dl-2021.6.6-py2.py3-none-any.whl (1.9 MB)
  Using cached youtube_dl-2021.5.16-py2.py3-none-any.whl (1.9 MB)
Requirement already satisfied: colorlog in /root/.pyenv/versions/3.5.7/lib/python3.5/site-packages (from -r requirements.txt (line 5)) (5.0.1)
Collecting colorlog
  Using cached colorlog-5.0.1-py2.py3-none-any.whl (10 kB)
  Using cached colorlog-5.0.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: aiohttp<3.8.0,>=3.6.0 in /root/.pyenv/versions/3.5.7/lib/python3.5/site-packages (from discord.py[voice]->-r requirements.txt (line 2)) (3.6.3)
Requirement already satisfied: six in /root/.pyenv/versions/3.5.7/lib/python3.5/site-packages (from pynacl->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: cffi>=1.4.1 in /root/.pyenv/versions/3.5.7/lib/python3.5/site-packages (from pynacl->-r requirements.txt (line 1)) (1.14.6)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /root/.pyenv/versions/3.5.7/lib/python3.5/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py[voice]->-r requirements.txt (line 2)) (3.0.1)
Requirement already satisfied: typing-extensions>=3.6.5 in /root/.pyenv/versions/3.5.7/lib/python3.5/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py[voice]->-r requirements.txt (line 2)) (3.10.0.0)
Requirement already satisfied: attrs>=17.3.0 in /root/.pyenv/versions/3.5.7/lib/python3.5/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py[voice]->-r requirements.txt (line 2)) (21.2.0)
Requirement already satisfied: chardet<4.0,>=2.0 in /root/.pyenv/versions/3.5.7/lib/python3.5/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py[voice]->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: multidict<5.0,>=4.5 in /root/.pyenv/versions/3.5.7/lib/python3.5/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py[voice]->-r requirements.txt (line 2)) (4.7.6)
Requirement already satisfied: idna-ssl>=1.0 in /root/.pyenv/versions/3.5.7/lib/python3.5/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py[voice]->-r requirements.txt (line 2)) (1.1.0)
Requirement already satisfied: yarl<1.6.0,>=1.0 in /root/.pyenv/versions/3.5.7/lib/python3.5/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py[voice]->-r requirements.txt (line 2)) (1.5.1)
Requirement already satisfied: pycparser in /root/.pyenv/versions/3.5.7/lib/python3.5/site-packages (from cffi>=1.4.1->pynacl->-r requirements.txt (line 1)) (2.20)
Requirement already satisfied: idna>=2.0 in /root/.pyenv/versions/3.5.7/lib/python3.5/site-packages (from idna-ssl>=1.0->aiohttp<3.8.0,>=3.6.0->discord.py[voice]->-r requirements.txt (line 2)) (3.2)

[INFO] launcher: Ok lets hope it worked

[INFO] launcher: All done.

After this, nothing happened, and the bot never came online.
I ran update.py , replaced requirements.txt, and switched Privileged Gateway Intents. 

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/6941437/musicbot.log)

**Comment by DestinyofYeet** [comment]
run `python3.5 -m pip install websockets` and try to run the bot again.

**Comment by vccl3595** [comment]
Thank you very much.  worked well !!

**Comment by CodingNation1** [comment]
nice
