### ISSUE TITLE
ERROR: No video formats found

### ISSUE THREAD

**Issue by lowcamuch** [Just-Some-Bots/MusicBot#2228]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

Hi,
I've set my MusicBot on my VPS on Debian 10, im using Python 3.8.
When I queue a song with !play song_name everything goes smoothly, but instead if i use !play playlist_URL bot shows presented Error.
ERROR: No video formats found
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/home/MusicBot/musicbot/bot.py", line 4065, in on_message
    response = await handler(**handler_kwargs)
  File "/home/MusicBot/musicbot/bot.py", line 1656, in cmd_play
    return await self._cmd_play(
  File "/home/MusicBot/musicbot/bot.py", line 2059, in _cmd_play
    entry_list, position = await player.playlist.import_from(
  File "/home/MusicBot/musicbot/playlist.py", line 212, in import_from
    position = 1 if head else len(self.entries) + 1
NameError: name 'head' is not defined

I've tried a lot of playlist with my friends, but none are working
Youtube_dl is updated . Also playlist aren't premade by YT, they are ours lists
### Steps to reproduce

1. Run bot
2. use !play https://www.youtube.com/playlist?list=
3. read Bot CMD line

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/7085716/musicbot.log)

**Comment by AutumnClove** [comment]
Trying to develop a fix right now, have found the issue. Will update you when I have the fix.

**Comment by AutumnClove** [comment]
#2229 should fix this try a git pull and lmk

**Comment by lowcamuch** [comment]
#2229 worked! Thank you very much. Both single songs an playlists are working.
