### ISSUE TITLE
Error starting bot.

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#2231]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

I can't get my bot to start. Instead of blabbing on about it, I'll tell you this. It says error starting bot, see the log files for the full fandango.

### Steps to reproduce

1. run the run.bat

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/7106777/musicbot.log)

**Comment by AutumnClove** [comment]
Switch to review`git checkout review` from within the musicbot folder. Go to the [discord development portal](https://discord.com/developers/docs/intro) and enable intents.

**Comment by ghost** [comment]
> Switch to review`git checkout review` from within the musicbot folder. Go to the [discord development portal](https://discord.com/developers/docs/intro) and enable intents.

What do you mean by 'Switch to reviewgit checkout review from within the musicbot folder.'??? i don't get what you want me to switch???

**Comment by AutumnClove** [comment]
The branch of the bot you're using, you've stated you're using the master branch, I'd like you to switch to the review branch as it contains various fixes, (plus new features like the ability to use `!play` without doing `!summon` first!) To do this you will need to open a terminal either from the musicbot folder by opening the folder and right click on then doing `open git bash here` then typing `git checkout review` or by just opening a terminal and navigating to the musicbot folder either by doing CD path-to-musicbot or if you're on Linux ls path-to-musicbot
