### ISSUE TITLE
Continued errors when starting bot.

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#2232]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Steps to reproduce

1. i just run.bat.

----

### Log file

[musicbot (2).log](https://github.com/Just-Some-Bots/MusicBot/files/7107040/musicbot.2.log)

**Comment by AutumnClove** [comment]
Would appear you need to navigate to the musicbot folder from an elevated terminal with admin privileges and then do `python3.8 -m pip install -U -r --user requirements.txt`

**Comment by AutumnClove** [comment]
Did this work?

**Comment by AutumnClove** [comment]
Closing because no reply from op
