### ISSUE TITLE
Owner could not be found on any guild

### ISSUE THREAD

**Issue by sihyun-mity** [Just-Some-Bots/MusicBot#2237]
Please tick all applicable boxes.

- [ O ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ O ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ O ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ O ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ O ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
I have all enabled Privileged Gateway Intents option in Discord Developer Portal, but every time I start the bot I get an error stating that the owner could not be found on any guild, the number of members in the server voice channel cannot be counted so if the AutoPause option is enabled, only one person can access the voice channel Even if you leave, the currently playing music will be paused.

### Steps to reproduce
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

Starting MusicBot release-260819-5-gc87dc05
Loaded autoplaylist with 2531 entries
Authenticated with Spotify successfully using client ID and secret.

Connected: 887704365475958794/Jade vine#0722

WARNING: Owner could not be found on any guild (id: 394791989616443393)

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/7172137/musicbot.log)

**Comment by AutumnClove** [comment]
intents aren't in the master branch yet, switch to review using `git checkout review` enjoy the new features on there as well!
