### ISSUE TITLE
Issue with the autosummoning and regular summoning

### ISSUE THREAD

**Issue by plushkinn** [Just-Some-Bots/MusicBot#224]
The problem: bot in the voice channel, but it write he isnt there. Anyway I summon him in other voice channel, it happanes again. How can i get him play music, cause it stucks on "Attempting to autosummon..."

Connected!

Bot:   160833021019291648/Music Bot
Owner: 156748517543510016/plushkinn

Server List:
- etozhemad

Bound to channels:
- etozhemad/music_requests
- etozhemad/musicbot_dj_panel

Command prefix is !
Whitelist check is disabled
Skip threshold at 4 votes or 50%
Now Playing message @mentions are enabled
Autosummon is enabled
Auto-playlist is enabled
Downloaded songs will be deleted after playback

Attempting to autosummon...
[Command] 156748517543510016/plushkinn (!summon)
Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 268, in _run_event
    yield from getattr(self, event)(_args, *_kwargs)
  File "/root/MusicBot/musicbot/bot.py", line 1434, in on_voice_state_update
    player = await self.get_player(my_voice_channel)
  File "/root/MusicBot/musicbot/bot.py", line 244, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.

**Comment by arunesh90** [comment]
Did you try review? Borked even said that to you.
![prntscr](http://i.imgur.com/RjNY4Ze.png)

**Comment by plushkinn** [comment]
Bot stopped playing music day ago. What does review mean?

**Comment by arunesh90** [comment]
https://github.com/SexualRhinoceros/MusicBot/archive/review.zip

**Comment by Alonso245** [comment]
Hi I am having a problem my bot tells me this The bot is not in a voice channel.  Use !summon to summon it to your voice channel.

**Comment by arunesh90** [comment]
@Alonso245 This issue is 2 months old....
