### ISSUE TITLE
[bug] The bot doesn't play anything

### ISSUE THREAD

**Issue by GalacticGreenLemon** [Just-Some-Bots/MusicBot#2244]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

I have just downloaded the bot, did everything like the guide said. The bot starts, it joins on summon, but when I wanna play anything it waits a couple of seconds then it just leaves and tells me that I need to use -summon.

I added the options I have as well tho github doesn't let me put an ini file so I changed it to a txt.

### Steps to reproduce

1.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/7189461/musicbot.log)
[example_options.txt](https://github.com/Just-Some-Bots/MusicBot/files/7189479/example_options.txt)

**Comment by Jcodeerd** [comment]
try `py -3 -m pip install -U discord.py[voice] websockets`

**Comment by GalacticGreenLemon** [comment]
still does the same thing
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/7189534/musicbot.log)

**Comment by myNameArnav** [comment]
I tried running ```sudo python3 -m pip install --upgrade -r requirements.txt``` again, and it threw me this error:

```
Collecting discord.py[voice]==1.2.5
  Downloading discord.py-1.2.5-py3-none-any.whl (655 kB)
     |████████████████████████████████| 655 kB 8.5 MB/s
INFO: pip is looking at multiple versions of pynacl to determine which version is compatible with other requirements. This could take a while.
Collecting pynacl==1.2.1
  Downloading https://www.piwheels.org/simple/pynacl/PyNaCl-1.2.1-cp37-cp37m-linux_armv7l.whl (460 kB)
     |████████████████████████████████| 460 kB 230 kB/s
ERROR: Cannot install discord-py[voice]==1.2.5 and pynacl==1.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pynacl==1.2.1
    discord-py[voice] 1.2.5 depends on PyNaCl==1.3.0; extra == "voice"
    The user requested pynacl==1.2.1
    discord-py[voice] 1.2.5 depends on PyNaCl==1.3.0; extra == "voice"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Comment by jdhayes** [comment]
I had issues running this with python 3.9.
Can you try using Python 3.7, that worked for me.

If your OS does not Python 3.7, you can always install it via conda.

**Comment by jayktaylor** [comment]
The latest `master` release may fix this issue.
