### ISSUE TITLE
run.sh fails

### ISSUE THREAD

**Issue by SteindelSE** [Just-Some-Bots/MusicBot#2247]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
```
$ python --version
Python 3.9.7
```
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
https://just-some-bots.github.io/MusicBot/installing/arch/
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

```
$ ./run.sh
./run.sh: line 9: python3.5: command not found
./run.sh: line 10: python3.6: command not found
./run.sh: line 11: python3.7: command not found
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
Traceback (most recent call last):
  File "/servers/MusicBot/run.py", line 438, in <module>
    main()
  File "/servers/MusicBot/run.py", line 347, in main
    finalize_logging()
  File "/servers/MusicBot/run.py", line 179, in finalize_logging
    dlh.setFormatter(logging.Formatter('.'))
  File "/usr/lib/python3.9/logging/__init__.py", line 574, in __init__
    self._style.validate()
  File "/usr/lib/python3.9/logging/__init__.py", line 427, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '.' for '%' style
```

### Steps to reproduce

1. Follow guide: https://just-some-bots.github.io/MusicBot/installing/arch/
2. Update dependencies in requirements because master branch requirements.txt was bugged per issue #2245 
3. Created venv with `python3 -m venv .` inside MusicBot folder
4. Set token in option.ini
5. `./run.sh`

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/7199959/musicbot.log)

**Comment by AleanaA** [comment]
Already resolved in review, the master branch is not compatible with Python 3.8+

**Comment by SteindelSE** [comment]
@AleanaA I assume the install process is the same, just with the review branch .git cloned?

**Comment by AleanaA** [comment]
Correct, or clone the master branch, and run `git checkout review` while in the main MusicBot folder.
