### ISSUE TITLE
Bot Cannot Join VC - Can't find pynacl

### ISSUE THREAD

**Issue by HaloSam296** [Just-Some-Bots/MusicBot#2248]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
I keep running run.sh and after several hours of differing issues, the one I cannot seem to get working is that it says I do not have pynacl installed. I've installed it multiple times using pip and I've also used the discord server for help, to no avail (though they were incredibly kind and helpful for the other issues). The bot will run and do most commands, but anything related to joining a VC is impossible and produces errors.

### Steps to reproduce

1.  I honestly have no idea. I do not know what's causing this.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/7200464/musicbot.log)

**Comment by Bradjaaaaah** [comment]
Could you copy and paste the error(s) that you are getting?
Also try pip freeze to see if you have actually installed it.
otherwise try this: **pip install pynacl** (or for a specific version try) **pip install pynacl==1.2.1** (<-- Example)

If the bot is unable to connect to a voice channel: make sure you have installed **discord.py[voice]==(version)** and not just: **discord.py==(version)**

**Comment by HaloSam296** [comment]
![Screenshot 2021-09-21 115409](https://user-images.githubusercontent.com/30218977/134214057-fd257d43-0f15-4177-8049-eb3ffd380554.png)
`
315565100226576394/AGrapplerNamedSam#5801: !j
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/home/pi/MusicBot/musicbot/bot.py", line 4056, in on_message
    response = await handler(**handler_kwargs)
  File "/home/pi/MusicBot/musicbot/bot.py", line 2803, in cmd_summon
    player = await self.get_player(
  File "/home/pi/MusicBot/musicbot/bot.py", line 534, in get_player
    voice_client = await self.get_voice_client(channel)
  File "/home/pi/MusicBot/musicbot/bot.py", line 486, in get_voice_client
    client = await channel.connect(timeout=60, reconnect=True)
  File "/home/pi/.local/lib/python3.9/site-packages/discord/abc.py", line 1277, in connect
    voice = cls(client, self)
  File "/home/pi/.local/lib/python3.9/site-packages/discord/voice_client.py", line 199, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice
`

I've tried reinstalling PyNaCl and have made sure discord.py[voice] was installed. Still received the same error. I'm not sure which version of PyNaCl to install if I did a specific vers.

**Comment by AleanaA** [comment]
Issue resolved in MBH, user switched from Py3.9 to Py3.8.7
