### ISSUE TITLE
I can't start bot

### ISSUE THREAD

**Issue by Kaczka212** [Just-Some-Bots/MusicBot#2250]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
I can't start bot

### Steps to reproduce

1. idk

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

PS C:\Users\Komputer123\Desktop\Musicbot\MusicBot> & C:/Users/Komputer123/AppData/Local/Programs/Python/Python39/python.exe c:/Users/Komputer123/Desktop/Musicbot/MusicBot/run.py
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
Traceback (most recent call last):
  File "c:\Users\Komputer123\Desktop\Musicbot\MusicBot\run.py", line 438, in <module>
    main()
  File "c:\Users\Komputer123\Desktop\Musicbot\MusicBot\run.py", line 347, in main
    finalize_logging()
  File "c:\Users\Komputer123\Desktop\Musicbot\MusicBot\run.py", line 179, in finalize_logging
    dlh.setFormatter(logging.Formatter('.'))
  File "C:\Users\Komputer123\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 574, in __init__
    self._style.validate()
  File "C:\Users\Komputer123\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 427, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '.' for '%' style
PS C:\Users\Komputer123\Desktop\Musicbot\MusicBot>

**Comment by Nubstex** [comment]
Bro, look https://just-some-bots.github.io/MusicBot/using/troubleshooting/

**Comment by AleanaA** [comment]
> 
> 
> Bro, look https://just-some-bots.github.io/MusicBot/using/troubleshooting/
