### ISSUE TITLE
Discord bot status

### ISSUE THREAD

**Issue by Nubstex** [Just-Some-Bots/MusicBot#2251]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [X] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue

How can i change discord bot status? I mean when i play song the title is in the status. I want to write static status in file. Where can i find it?

**Comment by AleanaA** [comment]
https://github.com/Just-Some-Bots/MusicBot/blob/c87dc05d93d7257cd7eae85daf118bbf8a1dc6eb/config/example_options.ini#L153
