### ISSUE TITLE
Bot recognizes Stage channels as Text channels

### ISSUE THREAD

**Issue by AleanaA** [Just-Some-Bots/MusicBot#2252]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
As of now, attempts to play to a Stage channel results in an error saying you can't play in a text channel `STAGENAME`
The bot will play for a bit, but ends up disconnecting after some time.

### Steps to reproduce

1. Attempt to play music within a Stage channel

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

Issue was created for a user within RBH, no log file provided.

**Comment by CodingNation1** [comment]
nice

**Comment by BabyBoySnow** [comment]
I barely since anyone use stage channels so I'm marking this as low priority for the time being. Might look into poking around at some point.

**Comment by BabyBoySnow** [comment]
I fixed this in 612f341e67bc6d7a6c54cf367591bf44a6d1d902
