### ISSUE TITLE
Bot "is typing...." for a very long time

### ISSUE THREAD

**Issue by kelvintan133** [Just-Some-Bots/MusicBot#2254]
Sometimes if I load a longer than usual playlist, the bot will be typing in the chat area. It may continue typing for more than hours sometimes. It kind of bug some of my members out as they don't know what the bot is doing.

I, myself, personally know it should be the bot processing the playlist. But sometimes for an hour plus, was what prompt me to wonder if there's a way around reducing the bot "is typing..." duration or disable it overall as a setting or sort. I never played anything longer than 200 songs. Not even once.

Just small quality of life things for some users.

To reproduce the issue mentioned:
1. Input a playlist URL from Spotify
2. Bot "joins" call, and begins "is typing..." process in the chat area

Latest Bot version
Ubuntu 20.04.3 LTS
VM Instance on Oracle Cloud

**Comment by Bence98007** [comment]
This bug still persist.

**Comment by andreyrd** [comment]
If the bot is still typing, then it's still processing the playlist.

**Comment by Bence98007** [comment]
I can put one-song only playlist, the same thing happens.

**Comment by amit177** [comment]
Please open a new issue with the correct issue template if still relevant
