### ISSUE TITLE
youtube_dl module downloads larger vids very slow

### ISSUE THREAD

**Issue by pancubano1** [Just-Some-Bots/MusicBot#2257]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [x] Question

----

### Description of issue

Download speeds for larger youtube videos is very slow if it is 10mins+ or 20mbs+. I'm not very good at python or coding in general, but I know enough to hold my own. I read that youtube-dl has had no dev for around 3 months and that the slow download issue has been common with this module. I was able to go in to download.py and replace the code for youtube_dl with yt_dlp and that solved the download speed issue instantly. 

Are there currently any plans to migrate the module from youtube_dl to yt_dlp?

### Steps to reproduce

1. Summon bot to a VC
2. !play any youtube vid longer than 10mins or larger than 20mb
3. Monitor audio_cache for file size increase

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by DemonFire7** [comment]
How do I do this for the bot? Do you have a copy of the yt-dlp code?
Is it only the downloader.py file?

This would help a lot, thanks!

EDIT: Think I figured it out, bot is playing stuff again, and quick/fast queue/play time now.  Commands use yt_dlp instead of yt-dlp and it is working.

**Comment by jayktaylor** [comment]
The bot now uses yt-dlp in the latest `master` release.
