### ISSUE TITLE
"Could not import pip"

### ISSUE THREAD

**Issue by musicbothelp** [Just-Some-Bots/MusicBot#226]
Everytime I run "Runbot" I get this error
http://i.imgur.com/HcicgRH.png?1

What am I doing wrong ? :P

**Comment by imayhaveborkedit** [comment]
You installed python without pip.  Reinstall/modify python and make sure you check the `Install pip` box.

**Comment by musicbothelp** [comment]
I did... What else can I do?

**Comment by jacobmix** [comment]
If you use Windows 7 try this (Tho i guess you can do something similar on other OS):
Go here: https://bootstrap.pypa.io/get-pip.py Press "Ctrl+A". Then "Ctrl+S"
Save it to a location you'll remember. (Like `C:\RhinoMusicBot`)
Run CMD as admin. (Click start, search "CMD", and right click it. Then click "Run as Administrator)
Type: `CD /D "C:\RhinoMusicBot"` Press enter. Then Type:
`"C:\Users\*User*\AppData\Local\Programs\Python\Python35-32\python.exe" get-pip.py`
Remember. Replace `C:\RhinoMusicBot` with where you saved "get-pip.py".
And replace `*User*` with your user.

(if you don't wanna write it all you can just copy the path+code here, edit it in the comment box, copy it, and right click on the CMD window. Then click "paste" to... Well, paste it. Ctrl+C/V doesn't work in CMD)

If it doesn't work try: `C:\Users\*user*\AppData\Local\Programs\Python\Python35-32\Scripts\pip.exe install --upgrade setuptools` (In an Admin run CMD of course)

Start is the Windows symbol on the task-bar down to the left. http://prnt.sc/aybw3i (If not changed)
This should show you where to search for CMD, and your user: http://prnt.sc/aybx15

Hope this helps. If you get any errors don't be afraid to post them. Hope I explained this well enough :)
