### ISSUE TITLE
SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by CJSparrow** [Just-Some-Bots/MusicBot#2260]
Please tick all applicable boxes.

- [* ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [* ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [* ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [*] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [*] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
![image](https://user-images.githubusercontent.com/65213455/137586936-32aed654-ee0a-422b-8614-27f2356c2fdb.png)

Logs:
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/7357522/musicbot.log)

**Comment by BabyBoySnow** [comment]
Try the latest version
