### ISSUE TITLE
[FR] Auto-Disconnect after song has finished playing

### ISSUE THREAD

**Issue by kubo6472** [Just-Some-Bots/MusicBot#2265]
What type of issue are you creating?
- [x] Feature request
----

### Description of feature:
Config option and a feature that can disconnect the bot after the current song ends to save bandwidth. I see this was attempted once already, but not finished. I only know very little in python, so I do not feel confident enough to do it myself. If I would be able to help in some way, I will try my best. I migrated from the ever-too-often breaking JMB due to LavaPlayer being always behind youtube for long periods of time. I like the Spotify feature, that it hadn't. But the whole experience of playing music is quite a bit different from anything I have seen.

**Comment by BabyBoySnow** [comment]
I feel like this is somewhat done already through https://github.com/Just-Some-Bots/MusicBot/commit/a19faa3d1f3c33bc17a4388d19282d388a22a11c but I do see the difference here. I can certainty look into this.

**Comment by BabyBoySnow** [comment]
https://github.com/Just-Some-Bots/MusicBot/commit/08239419320e9b172f157ef9db54ae22a6625ce2
