### ISSUE TITLE
[FR] Deafen the bot

### ISSUE THREAD

**Issue by kubo6472** [Just-Some-Bots/MusicBot#2266]
What type of issue are you creating?
- [x] Feature request
----

### Description of feature:
New FR, new issue (#2265). I already opened one issue for the MusicBot I was using b4 (jagrosh/MusicBot#519). But since I had/have very little experience in both Java, which was that bot's lang, and async Python, here, that I do not feel confident enough to do it myself. It does save bandwidth, period. That's why I'm referencing it in the first place :)

**Comment by AleanaA** [comment]
This already exists in review. #2230

**Comment by kubo6472** [comment]
Aighty
