### ISSUE TITLE
[FR] Ability to replace GitHub embed footer image with our own

### ISSUE THREAD

**Issue by walllable** [Just-Some-Bots/MusicBot#2269]
What type of issue are you creating?

- [x] Feature request
----

I noticed while looking through `bot.py` that the image for the little github icon next to the footer text is just an imgur link. I could, of course, just edit this myself, but I figure this could conflict with future updates or break things. It would be wonderful if we could replace this with our own image link in the `options.ini` file, similar to how we can set custom footer text.

**Comment by codeoffun2** [comment]
I don’t think it would conflict with anything if you ask me
I changed it and it works fine

**Comment by jayktaylor** [comment]
Hey there! You're more than welcome to edit the code to change the footer text/image. I don't see a need for another configuration option for this at the moment.
