### ISSUE TITLE
Can't get the bot to work.

### ISSUE THREAD

**Issue by ImASadBoy** [Just-Some-Bots/MusicBot#2270]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (release-260419)
- [X] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
The bot just won't start on my VPS (Ubuntu 20.04).

### Steps to reproduce

1. When executing the first guide command: `sudo add-apt-repository ppa:deadsnakes/ppa` I get the following error:
```
E: The repository 'http://ppa.launchpad.net/webupd8team/java/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
2. Decided to go ahead anyway and everything worked, except the bot won't start. 
this happens:
```
root@mail:~/MusicBot# sudo ./run.sh
./run.sh: line 7: python: command not found
./run.sh: line 7: python: command not found
./run.sh: line 7: python: command not found
./run.sh: line 9: python3.5: command not found
./run.sh: line 10: python3.6: command not found
./run.sh: line 14: [: no py: integer expression expected
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
Traceback (most recent call last):
  File "run.py", line 438, in <module>
    main()
  File "run.py", line 347, in main
    finalize_logging()
  File "run.py", line 179, in finalize_logging
    dlh.setFormatter(logging.Formatter('.'))
  File "/usr/lib/python3.8/logging/__init__.py", line 580, in __init__
    self._style.validate()
  File "/usr/lib/python3.8/logging/__init__.py", line 433, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '.' for '%' style
```

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/7428643/musicbot.log)

**Comment by ldwyer1** [comment]
I am having the same issue, have you found a solution yet?

**Comment by delidolu1adam** [comment]
No solution found for this problem? I'm having the same problem.

```
C:\Users\Serhat\Desktop\MusicBot>run.bat
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
Traceback (most recent call last):
  File "C:\Users\Serhat\Desktop\MusicBot\run.py", line 438, in <module>
    main()
  File "C:\Users\Serhat\Desktop\MusicBot\run.py", line 347, in main
    finalize_logging()
  File "C:\Users\Serhat\Desktop\MusicBot\run.py", line 179, in finalize_logging
    dlh.setFormatter(logging.Formatter('.'))
  File "C:\Users\Serhat\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 589, in __init__
    self._style.validate()
  File "C:\Users\Serhat\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 429, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '.' for '%' style
```

init.py

LINE 426 to 429:    ```
 def validate(self):
        """Validate the input format, ensure it matches the correct style"""
        if not self.validation_pattern.search(self._fmt):
            raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0])) 
```
            
LINE 567 TP 595:  def __init__(self, fmt=None, datefmt=None, style='%', validate=True, *,
                 defaults=None):
        """
        Initialize the formatter with specified format strings.

        Initialize the formatter either with the specified format string, or a
        default as described above. Allow for specialized date formatting with
        the optional datefmt argument. If datefmt is omitted, you get an
        ISO8601-like (or RFC 3339-like) format.

        Use a style parameter of '%', '{' or '$' to specify that you want to
        use one of %-formatting, :meth:`str.format` (``{}``) formatting or
        :class:`string.Template` formatting in your format string.

        .. versionchanged:: 3.2
           Added the ``style`` parameter.
        """
        if style not in _STYLES:
            raise ValueError('Style must be one of: %s' % ','.join(
                             _STYLES.keys()))
        self._style = _STYLES[style][0](fmt, defaults=defaults)
        if validate:
            self._style.validate()

        self._fmt = self._style._fmt
        self.datefmt = datefmt

    default_time_format = '%Y-%m-%d %H:%M:%S'
    default_msec_format = '%s,%03d'

**Comment by DestinyofYeet** [comment]
**Help! I'm getting an error! Invalid format '.' for '%' style**

This is a result of using python 3.8 or above. Please either downgrade to a version below that such as 3.7.x, or you can switch to the review branch which supports higher versions of Python.

**How do I switch to review?**
♻️ If you have already cloned MusicBot master branch, simply navigate to your MusicBot folder through a terminal, or even easier, go to your MusicBot folder, and click open git bash here. Once there you can type `git checkout review`.

**Don't have MusicBot yet? No worries.**
📥   use `git clone https://github.com/Just-Some-Bots/MusicBot.git ~/MusicBot -b review`.

**Comment by JaraSG2** [comment]
I am having the same problem. 

```
jarasg2@vps-361095:~/MusicBot$ sudo ./run.sh
./run.sh: line 7: python: command not found
./run.sh: line 7: python: command not found
./run.sh: line 7: python: command not found
./run.sh: line 9: python3.5: command not found
./run.sh: line 10: python3.6: command not found
./run.sh: line 11: python3.7: command not found
./run.sh: line 14: [: no py: integer expression expected
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
Traceback (most recent call last):
  File "run.py", line 438, in <module>
    main()
  File "run.py", line 347, in main
    finalize_logging()
  File "run.py", line 179, in finalize_logging
    dlh.setFormatter(logging.Formatter('.'))
  File "/usr/lib/python3.8/logging/__init__.py", line 580, in __init__
    self._style.validate()
  File "/usr/lib/python3.8/logging/__init__.py", line 433, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.def                                                                             ault_format[0]))
ValueError: Invalid format '.' for '%' style
```

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/7652227/musicbot.log)

**Comment by AleanaA** [comment]
> I am having the same problem.
> 
> ```
> jarasg2@vps-361095:~/MusicBot$ sudo ./run.sh
> ./run.sh: line 7: python: command not found
> ./run.sh: line 7: python: command not found
> ./run.sh: line 7: python: command not found
> ./run.sh: line 9: python3.5: command not found
> ./run.sh: line 10: python3.6: command not found
> ./run.sh: line 11: python3.7: command not found
> ./run.sh: line 14: [: no py: integer expression expected
> [INFO] launcher: Starting sanity checks
> [INFO] launcher: Checking for Python 3.5+
> [INFO] launcher: Checking console encoding
> [INFO] launcher: Ensuring we're in the right environment
> [INFO] launcher: Required checks passed.
> [INFO] launcher: Optional checks passed.
> [INFO] launcher: Moving old musicbot log
> Traceback (most recent call last):
>   File "run.py", line 438, in <module>
>     main()
>   File "run.py", line 347, in main
>     finalize_logging()
>   File "run.py", line 179, in finalize_logging
>     dlh.setFormatter(logging.Formatter('.'))
>   File "/usr/lib/python3.8/logging/__init__.py", line 580, in __init__
>     self._style.validate()
>   File "/usr/lib/python3.8/logging/__init__.py", line 433, in validate
>     raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.def                                                                             ault_format[0]))
> ValueError: Invalid format '.' for '%' style
> ```
> 
> [musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/7652227/musicbot.log)

Please view the reply directly above yours.

**Comment by jayktaylor** [comment]
The `master` branch now has a fix for this.
