### ISSUE TITLE
MusicBot not able to queue Soundcloud playlists

### ISSUE THREAD

**Issue by GasPoweredStick** [Just-Some-Bots/MusicBot#2271]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
The bot isn't able to queue up playlists from soundcloud. In the server it says "Error handling playlist" and in the control panel it outputs: `"[ERROR:bot] Error in play: CommandError: Error handling playlist https://soundcloud.com/therealgps/sets/music-bot-stuff queueing."` 
The playlist I tried to queue was: https://soundcloud.com/therealgps/sets/music-bot-stuff

### Steps to reproduce

1. Use the `play` command with any soundcloud playlist 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/7480282/musicbot.log)

**Comment by jayktaylor** [comment]
This should be fixed in the latest `master` release.
