### ISSUE TITLE
Not being abble to start

### ISSUE THREAD

**Issue by zarigata** [Just-Some-Bots/MusicBot#2272]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

After running it does an hope it worked mensage

./run.sh: line 10: python3.6: command not found
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "/home/pi/MusicBot/musicbot/__init__.py", line 74, in <module>
    from .bot import MusicBot
  File "/home/pi/MusicBot/musicbot/bot.py", line 31, in <module>
    from .player import MusicPlayer
  File "/home/pi/MusicBot/musicbot/player.py", line 17, in <module>
    from websockets.exceptions import InvalidState
ModuleNotFoundError: No module named 'websockets'
[INFO] launcher: Attempting to install dependencies...
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pynacl in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 1)) (1.4.0)
Requirement already satisfied: discord.py[voice] in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 2)) (1.7.3)
Requirement already satisfied: pip in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 3)) (21.3.1)
Requirement already satisfied: youtube_dl in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 4)) (2021.6.6)
Requirement already satisfied: colorlog in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 5)) (6.5.0)
Requirement already satisfied: cffi>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from pynacl->-r requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from pynacl->-r requirements.txt (line 1)) (1.12.0)
Requirement already satisfied: aiohttp<3.8.0,>=3.6.0 in /usr/local/lib/python3.7/dist-packages (from discord.py[voice]->-r requirements.txt (line 2)) (3.7.4.post0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp<3.8.0,>=3.6.0->discord.py[voice]->-r requirements.txt (line 2)) (21.2.0)
Requirement already satisfied: chardet<5.0,>=2.0 in /usr/lib/python3/dist-packages (from aiohttp<3.8.0,>=3.6.0->discord.py[voice]->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp<3.8.0,>=3.6.0->discord.py[voice]->-r requirements.txt (line 2)) (3.0.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.7/dist-packages (from aiohttp<3.8.0,>=3.6.0->discord.py[voice]->-r requirements.txt (line 2)) (5.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp<3.8.0,>=3.6.0->discord.py[voice]->-r requirements.txt (line 2)) (1.7.2)
Requirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.7/dist-packages (from aiohttp<3.8.0,>=3.6.0->discord.py[voice]->-r requirements.txt (line 2)) (3.10.0.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.4.1->pynacl->-r requirements.txt (line 1)) (2.20)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp<3.8.0,>=3.6.0->discord.py[voice]->-r requirements.txt (line 2)) (2.6)

[INFO] launcher: Ok lets hope it worked

[INFO] launcher: All done.

### Steps to reproduce

1.  ./run.sh

---

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
does not have a log folder and not have a file
![image](https://user-images.githubusercontent.com/39637452/140591744-130f0ea8-b022-42a6-8a2b-6b177ebc1630.png)

**Comment by DestinyofYeet** [comment]
run `py -3.7 -m pip install websockets`
