### ISSUE TITLE
when i play the song, error occurs queuer not in voice

### ISSUE THREAD

**Issue by Sar-1124** [Just-Some-Bots/MusicBot#2273]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] release-260819-5-gc87dc05

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

This error occurs when I play the song "Skipping next song in added by as queuer not in voice". How do i resolve this problem?

### Steps to reproduce

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/7524425/musicbot.log)

**Comment by BabyBoySnow** [comment]
Are intents enabled?

**Comment by BabyBoySnow** [comment]
Can't seem to get this issue myself, and no response from OP.
