### ISSUE TITLE
Feature Request - Seek

### ISSUE THREAD

**Issue by Toryllan** [Just-Some-Bots/MusicBot#2274]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

### Description of issue

Just added the bot, absolutely love it. I found old an old fork for the Seek feature from 2017, is there a more updated version available? 

### Steps to reproduce

1.  N/A

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by amit177** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/452
