### ISSUE TITLE
Crashing on Ubuntu

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#228]
I've got a Ubuntu VPS from DigitalOcean running the bot. Runs fine for a day or so after which it just crashes. Here's what appears when it does.

Task was destroyed but it is pending!
task: <Task pending coro=<VoiceClient.keep_alive_handler() running at /usr/local/lib/python3.5/dist-packages/discord/voice_client.py:198> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.run() running at /usr/local/lib/python3.5/dist-packages/websockets/protocol.py:302> wait_for=<Future pending cb=[Task._wakeup()]>>

**Comment by Echoskope** [comment]
See this reference:
[(https://github.com/SexualRhinoceros/MusicBot/issues/207)]

**Comment by arunesh90** [comment]
Do: `pip3.5 install -r requirements.txt --upgrade`

**Comment by imayhaveborkedit** [comment]
Use the review branch and update deps (`pip3.5 install --upgrade -r requirements.txt`).  This should stop happening now.
