### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FiberAhmed** [Just-Some-Bots/MusicBot#2282]
I was able to get the bot into the discord server but the bot doesn't join stays offline. the dependencies are fully updated no errors. Spent the whole day on this I'm legit at a loss. Please help.

### Log File:

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.8+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "C:\Users\أحمد\Desktop\Codes\MusicBot\MusicBot\run.py", line 409, in main
    from musicbot import MusicBot
  File "C:\Users\أحمد\Desktop\Codes\MusicBot\MusicBot\musicbot\__init__.py", line 74, in <module>
    from .bot import MusicBot
  File "C:\Users\أحمد\Desktop\Codes\MusicBot\MusicBot\musicbot\bot.py", line 48, in <module>
    from .json import Json
ModuleNotFoundError: No module named 'musicbot.json'

### Which operating system are you using?

Windows 7 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by AleanaA** [comment]
Can you provide a screenshot of the main `MusicBot` folder, along with the lowercase `musicbot` folder?

**Comment by FiberAhmed** [comment]
> 



> Can you provide a screenshot of the main `MusicBot` folder, along with the lowercase `musicbot` folder?

![image](https://user-images.githubusercontent.com/72029350/146676909-7cf4d9fa-a7df-48ea-b358-500fd176bf52.png)

**Comment by FiberAhmed** [comment]
> > 
> 
> > Can you provide a screenshot of the main `MusicBot` folder, along with the lowercase `musicbot` folder?
> 
> ![image](https://user-images.githubusercontent.com/72029350/146676909-7cf4d9fa-a7df-48ea-b358-500fd176bf52.png)

![image](https://user-images.githubusercontent.com/72029350/146676983-4c223b58-7f70-43b6-8527-77b47ffe6f69.png)

**Comment by AleanaA** [comment]
Not sure why but looks like `MusicBot/musicbot/json.py` was renamed to `json1.py`
Rename it back to `json.py` and the bot should work fine, if you have any other issues or questions, feel free to join our [support discord](https://discord.gg/bots).

**Comment by FiberAhmed** [comment]
> Not sure why but looks like `MusicBot/musicbot/json.py` was renamed to `json1.py`
> Rename it back to `json.py` and the bot should work fine, if you have any other issues or questions, feel free to join our [support discord](https://discord.gg/bots).

Thanks :), but now there is another error which is [ERROR:bot] Error in cleanup, I don't know what it means exactly
