### ISSUE TITLE
Clear queue when not in voice channel

### ISSUE THREAD

**Issue by andreyrd** [Just-Some-Bots/MusicBot#2287]
### What new feature would you like to see?

I'd like the ability to clear the queue even when the bot is not in a voice channel. This is so that I can summon it with a blank slate instead of having to `summon`, `clear`, then `skip`.

### Which of these categories fit your request?

Existing command update

### Just checking...

- [X] I have confirmed that my feature has not already been requested.
- [X] I have confirmed that my feature has not already been implemented in the `review` branch.

**Comment by BabyBoySnow** [comment]
just add player.skip() to the cmd_clear in bot.py
