### ISSUE TITLE
Weird Error On Command Execution

### ISSUE THREAD

**Issue by Catchii** [Just-Some-Bots/MusicBot#2290]
### What went wrong?

When I Run An Command I Get An Weird Error 

[ERROR:bot] Exception in on_message

This Happens on every command i run Messages With No Embeds Work Fine But Commands Like Help Wont Send Anything

even On Text ( Like play or search command ) Command i Still Get The Error

(look at the log)

### How do we reproduce this?

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/7954563/musicbot.log)

Log Of The Error

[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "C:\Users\justi\Desktop\discord bot\bot\MusicBot\musicbot\bot.py", line 4064, in on_message
    content = self._gen_embed()
  File "C:\Users\justi\Desktop\discord bot\bot\MusicBot\musicbot\bot.py", line 1361, in _gen_embed
    icon_url=self.user.avatar_url,
AttributeError: 'ClientUser' object has no attribute 'avatar_url' 

### Which version of the bot are you using?

release-151221

### Which operating system are you using?

Windows 7 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by AleanaA** [comment]
Please provide the output of `python -m discord --version`

**Comment by Catchii** [comment]
- Python v3.8.9-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a0
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000 (im on windows 11?)

**Comment by AleanaA** [comment]
Musicbot at this time does not support the alpha version of d.py or py-cord. Please ensure you're using the version released on PyPi.
`python -m pip uninstall py-cord`
`python -m pip install py-cord`
