### ISSUE TITLE
setavatar wont work

### ISSUE THREAD

**Issue by zarigata** [Just-Some-Bots/MusicBot#2293]
### What went wrong?

the bot wont copile to work to set an avatar

Error
Unable to change avatar: 400 Bad Request (error code: 50035): Invalid Form Body
In username: Username cannot contain "discord"

Just-Some-Bots/MusicBot (release-260819-5-gc87dc05)

### How do we reproduce this?

!setavatar {LINK TO IMAGE}

### Which version of the bot are you using?

release-151221

### Which operating system are you using?

Ubuntu 18.04 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by AleanaA** [comment]
> Just-Some-Bots/MusicBot (release-260819-5-gc87dc05)

Please update the bot.
If the issue happens once you've updated, feel free to reopen this.

**Comment by zarigata** [comment]
updated and yet the same problem

**Comment by AleanaA** [comment]
> updated and yet the same problem

Provide a log file.

**Comment by zarigata** [comment]
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/8083968/musicbot.log)

**Comment by AleanaA** [comment]
That log is still using `release-260819`
Please ensure that the update is working as intended, feel free to send a the output of the update script here if you're unsure.

**Comment by zarigata** [comment]
sorry was on the incorrect version, but still it wont work
i did a RM music bot and reloaded

**Comment by BritishBenji** [comment]
You may want to edit that log as it contains your Discord bot token

**Comment by zarigata** [comment]
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/8084158/musicbot.log)

**Comment by zarigata** [comment]
> You may want to edit that log as it contains your Discord bot token

thank you, ive erased

**Comment by AleanaA** [comment]
Can confirm after testing this and rereading the log, this isn't a bug. This is intentional behavior.
As the error states, the username cannot contain "discord"
If you want to modify the bot's properties, you'll have to do it manually, or change the username of the bot.
