### ISSUE TITLE
Error for avatar_url

### ISSUE THREAD

**Issue by haxurus** [Just-Some-Bots/MusicBot#2294]
### What went wrong?

When I add a song on the queue, the bot gives me this error:

```
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/home/debian/DiscordBots/LocandadiArroway-MusicBot-1-stanza1/musicbot/bot.py", line 4064, in on_message
    content = self._gen_embed()
  File "/home/debian/DiscordBots/LocandadiArroway-MusicBot-1-stanza1/musicbot/bot.py", line 1361, in _gen_embed
    icon_url=self.user.avatar_url,
AttributeError: 'ClientUser' object has no attribute 'avatar_url'
```

I downloaded all the repo some minutes ago for check if the error was fixed in the latest versions, but it didn't.

### How do we reproduce this?

Just add a song on the queue with embed enables.

### Which version of the bot are you using?

release-151221

### Which operating system are you using?

Ubuntu 18.04 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by Jcodeerd** [comment]
Try the steps in #2290

**Comment by haxurus** [comment]
Tried, but it didn't fix the problem

**Comment by AleanaA** [comment]
Please provide the output of `python -m discord --version`

**Comment by haxurus** [comment]
- Python v3.9.2-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Linux 5.10.0-11-cloud-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18)

**Comment by haxurus** [comment]
I'm having this error too when I try to skip a song:

```
Traceback (most recent call last):
  File "/home/debian/.local/lib/python3.9/site-packages/discord/player.py", line 616, in _call_after
    self.after(error)
  File "/home/debian/DiscordBots/LocandadiArroway-MusicBot-2-stanza2/musicbot/player.py", line 247, in _playback_finished
    if e.winerror == 32:  # File is in use
AttributeError: 'PermissionError' object has no attribute 'winerror'
```

**Comment by BRAVO68WEB** [comment]
Are you sure that their that you have given your bot appropriate perms on Discord?

**Comment by haxurus** [comment]
Yes. It has full permissions everywhere

**Comment by BRAVO68WEB** [comment]
Ok

Hmm this should not be happening

**Comment by BRAVO68WEB** [comment]
Ok I also this issue. Lets see

**Comment by slotting** [comment]
you need to use avatar.url because this is most likely using discord.py master branch

**Comment by Jcodeerd** [comment]
> you need to use avatar.url because this is most likely using discord.py master branch
The bot uses pycord

**Comment by Jcodeerd** [comment]
I cannot reproduce this, could you remove your token in option.ini and zip the entire Musicbot folder and post it here?
Also, please run `python3.9 -m pip list` and post that here too so I know what modules are installed.

**Comment by amit177** [comment]
Closed due to no reply
