### ISSUE TITLE
about Token.run()

### ISSUE THREAD

**Issue by geoo023** [Just-Some-Bots/MusicBot#2295]
### What new feature would you like to see?

Hi, I want to ask where is the command of token.run(), I am trying to upload this to replit run for 24h, sorry for my english is bad.

### Which of these categories fit your request?

Other

### Just checking...

- [X] I have confirmed that my feature has not already been requested.
- [X] I have confirmed that my feature has not already been implemented in the `review` branch.

**Comment by AleanaA** [comment]
We do not support repl.it, use a host such as AWS, Digital Ocean, or any other VPS host.
