### ISSUE TITLE
Constant "Connected to ..." message when loading playlists

### ISSUE THREAD

**Issue by DarkTerrorWolf** [Just-Some-Bots/MusicBot#2296]
### What went wrong?

The music bot fires up and runs perfectly normal... until you attempt to !play (spotify playlist here). the bot starts processing this playlist and as it does calls the cmd_summon command after every load of the song either from download or cache.
This started showing up after I called the update.sh command due to bot forgetting its in a discord channel with other people at random.

Snip of the Log.last file since github doesn't allow me to upload it

![image](https://user-images.githubusercontent.com/56730822/155857708-73b3a0fc-9af5-4c67-8870-763fd109a8d2.png)

and here is a snip of the discord side of the output

![image](https://user-images.githubusercontent.com/56730822/155857742-c5807d1c-3928-4e4c-bbad-7a2e98fbf973.png)

### How do we reproduce this?

Start the bot using run.sh
play (spotify playlist)

### Which version of the bot are you using?

release-151221

### Which operating system are you using?

Ubuntu 18.04 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by sk33ny** [comment]
I'm also having this issue

**Comment by Xplodin** [comment]
how do you fix this on review branch?

**Comment by DestinyofYeet** [comment]
Have you updated the repository?

**Comment by Xplodin** [comment]
there has not been an update in almost a year..

**Comment by DestinyofYeet** [comment]
While true, I do think you were running an older version of the master branch. That aside, you should try the review branch and see if your issue persists.

`git checkout review`

**Comment by Xplodin** [comment]
already am on the review branch. This specific issue came up on me quite a few weeks after using the bot.

**Comment by DestinyofYeet** [comment]
Very interesting behaviour. Unfortunately I don't run the bot for an extend period of time anymore, so I can't replicate the issue. 

Did this issue continue after a restart?

**Comment by Xplodin** [comment]
> Very interesting behaviour. Unfortunately I don't run the bot for an extend period of time anymore, so I can't replicate the issue.
> 
> Did this issue continue after a restart?

Yeah, it does it only with spotify. YT playlists tend to take quite a long time to load depending on size. But sometimes it just wont play the playlist

**Comment by YesImAk** [comment]
having the same issue

**Comment by DestinyofYeet** [comment]
When this issue appears again, send in the discord.log and musicbot.log files.

**Comment by YesImAk** [comment]
it happens whenever I play Spotify playlist

**Comment by delta440** [comment]
I was having the same issue, everytime it looked up/downloaded a song from a spotify playlist it would spam the "Connected to <voice channel>" line. I commented out this block:
```        if permissions.summonplay:
            voice_channel = author.voice.channel if author.voice else None
            response = await self.cmd_summon(
                channel, channel.guild, author, voice_channel
            )  # @TheerapakG: As far as I know voice_channel param is unused
            if self.config.embeds:
                content = self._gen_embed()
                content.title = "summon"
                content.description = response.content
            else:
                content = response.content
            await self.safe_send_message(
                channel,
                content,
                expire_in=response.delete_after if self.config.delete_messages else 0,
            )
            player = self.get_player_in(channel.guild)
```
            
Honestly I didn't put much thought into it since it seemed like this would just break the auto summon feature, but this fixed it. Hopefully that narrows it down

**Comment by BabyBoySnow** [comment]
Should be fixed in review! https://github.com/Just-Some-Bots/MusicBot/commit/daa73be5681abe541aef9fb6460eeea777efcddf
