### ISSUE TITLE
After few hours bot stops working

### ISSUE THREAD

**Issue by smaartscz** [Just-Some-Bots/MusicBot#2298]
### What went wrong?

If you leave bot in voice channel for few hours it will undeafen himself and start thinking it isn't in voice channel.
Summoning will say it connected to voice channel but that doesn't help at all. Using !restart usually solves issues.

I'm using Debian 10 but bot is conternized using [official docker image](https://hub.docker.com/r/justsomebots/musicbot/).
Log:
```
000000000000000000/xxxx#0000: !summon,
Joining XXXXXX/🪑VoiceChannel🪑,
000000000000000000/xxxx#0000: !p test,
[ERROR:bot] Error in play: CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.,
Traceback (most recent call last):,
  File "/musicbot/musicbot/bot.py", line 4058, in on_message,
    response = await handler(**handler_kwargs),
  File "/musicbot/musicbot/bot.py", line 1649, in cmd_play,
    return await self._cmd_play(,
  File "/musicbot/musicbot/bot.py", line 1720, in _cmd_play,
    raise exceptions.CommandError(,
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.
```

### How do we reproduce this?

1. Summon bot
2. Leave him alone for few hours
3. Done

### Which version of the bot are you using?

release-151221

### Which operating system are you using?

Other

### Just checking...

- [x] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by Jcodeerd** [comment]
Could you send the entire log?
It might have gotten disconnected by discord.

**Comment by smaartscz** [comment]
Of course. I hope I didn't leak something important xd.
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/8343995/musicbot.log)
.

**Comment by Jcodeerd** [comment]
Yep, I was correct. Discord decided to reconnect
Not much we can do afaik

**Comment by smaartscz** [comment]
oh okay, thank you.
