### ISSUE TITLE
"The bot is not in a voice channel" bug

### ISSUE THREAD

**Issue by maecry** [Just-Some-Bots/MusicBot#2299]
### What went wrong?

![image](https://user-images.githubusercontent.com/52035116/160111268-40d1c860-a231-40f6-95c1-35ede83bf8a7.png)

It's in a voice channel already, however when I used the "-play" command, It said that on the picture.
I tried to "-summon" it into another channel and it still acted the same.

and here is the error logs
![opera_K7W49HFqms](https://user-images.githubusercontent.com/52035116/160111625-bd0e3602-1737-457c-bd03-12b6810e470f.png)

### How do we reproduce this?

I don't really know how, but I did have the bot leave AFK on the voice channel for like 3 hours without playing anything.

### Which version of the bot are you using?

release-151221

### Which operating system are you using?

Windows 7 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by maecry** [comment]
It appeared to happen when the bot reconnect to Discord

**Comment by amit177** [comment]
Could you try using the review branch and confirm whether it's still happening there?

**Comment by ImASadBoy** [comment]
@april2202 any info about the review branch working?

**Comment by maecry** [comment]
Oh hi I completely forgot bout this as I have moved on using others and not having time to setup the server again so I guess I will close this issue
