### ISSUE TITLE
Spotify Playlist

### ISSUE THREAD

**Issue by Mr-Robot-ops** [Just-Some-Bots/MusicBot#2302]
### What went wrong?

Raspberry Pi
Spotify Playlist: https://open.spotify.com/playlist/1L0vaT3y0xnAGQ4ZpXORnH?si=f44a65061f534f01

ERROR: Sign in to confirm your age
This video may be inappropriate for some users.

### How do we reproduce this?

!play https://open.spotify.com/playlist/1L0vaT3y0xnAGQ4ZpXORnH?si=f44a65061f534f01

### Which operating system are you using?

Other

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by DestinyofYeet** [comment]
Since downloading songs from Spotify directly is against their ToS, we search for the song on youtube. If youtube now decides you have to log in, there's not much we can do.
