### ISSUE TITLE
Cannot play the music in voice channel (M1) "Failed to deserialize player"

### ISSUE THREAD

**Issue by Amo-is-Sleeping** [Just-Some-Bots/MusicBot#2303]
### What went wrong?

Cannot play the music in voice channel (M1)

"Failed to deserialize player" is print on the terminal
<img width="1282" alt="screenshot" src="https://user-images.githubusercontent.com/55903332/171596633-fbe80ceb-8b31-4f1d-b456-3455abd8a52d.png">
.

### How do we reproduce this?

run the run.py

### Which version of the bot are you using?

release-151221

### Which operating system are you using?

macOS Catalina or higher, with Apple M1 chip

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by jayktaylor** [comment]
The upstream library for Discord does not yet seem to support Opus/voice on Apple chipsets.

**Comment by BabyBoySnow** [comment]
Has this been resolved?

**Comment by itsTheFae** [comment]
I don't have an M1 apple to test with, but this issue might have been resolved.  
See these two links for more details related to this error:  
https://github.com/Rapptz/discord.py/issues/8046  

and

https://github.com/python/cpython/issues/92892
