### ISSUE TITLE
Ubuntu 22.04

### ISSUE THREAD

**Issue by hexahigh** [Just-Some-Bots/MusicBot#2304]
### What new feature would you like to see?

Can you add support for ubuntu 22.04?

### Which of these categories fit your request?

Other

### Just checking...

- [x] I have confirmed that my feature has not already been requested.
- [X] I have confirmed that my feature has not already been implemented in the `review` branch.

**Comment by BRAVO68WEB** [comment]
Have you tried installing?

**Comment by hexahigh** [comment]
No.

**Comment by hexahigh** [comment]
I could try later

**Comment by ImASadBoy** [comment]
Can confirm it works on Ubuntu 22.04 just fine
