### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Naiml007** [Just-Some-Bots/MusicBot#2311]
### What went wrong?

Pls fix 

### How do we reproduce this?

![Screenshot_2022-08-02-10-33-52-905_com android chrome](https://user-images.githubusercontent.com/90306726/182292562-d610ff7c-989f-4400-a70b-0b7ce06326f9.jpg)

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by AleanaA** [comment]
Musicbot has never, and will never support Replit.
