### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by mulano1977** [Just-Some-Bots/MusicBot#2314]
### What new feature would you like to see?

German translation

[klick me](https://www.german7sins.de/de.json)

### Which of these categories fit your request?

New configurable option or change to existing one

### Just checking...

- [X] I have confirmed that my feature has not already been requested.
- [X] I have confirmed that my feature has not already been implemented in the `review` branch.

**Comment by BabyBoySnow** [comment]
Please create a pr for this, make sure to update with the latest I18n strings.
