### ISSUE TITLE
Issue with restart command

### ISSUE THREAD

**Issue by weerl** [Just-Some-Bots/MusicBot#2315]
### What went wrong?

I've been frequently encountering an error described in issue #2298. The bot stops responding to commands aside from the restart command. After running the restart command it works normally. Recently the restart command has stopped working with my instance of the bot. The bot will encounter a couple of errors and not start again until started manually. I am running the bot on Rasbian, and have had this error persist on fresh (aside from copies of my options.ini, permissions.ini, aliases.json, blacklist.txt, and whitelist.txt files) installs of both the master and review branch. 

Logs:
Master - https://pastebin.com/uLirmQee
Review - https://pastebin.com/PSL3fsaf

### How do we reproduce this?

1. Start the bot using "./run.sh" or "sudo python run.py"
2. Use "restart" command in a text channel the bot is bound to
3. Bot does not restart and needs to be launched again manually

### Which version of the bot are you using?

I am using the "review" branch

### Which operating system are you using?

Other

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by JustShaum** [comment]
Now I have absolutely no coding knowledge and I have no idea what the line does but I managed to get it restarting by removing line 46 of downloader.py. 

            ytdl_format_options["outtmpl"] = os.path.join(download_folder, otmpl)

Again, I don't know what I'm doing but figured it might help somewhere

**Comment by weerl** [comment]
@JustShaum Thanks so much for the suggestion, I commented out line 46 in downloader.py and now my bot is able to restart. I do still get a chunk of errors before the restart initiates, however haven't experienced any issues because them. 
[ERROR:bot] Error in cleanup
Traceback (most recent call last):
  File "/home/pi/musicbot/musicbot/bot.py", line 1082, in run
    self._cleanup()
  File "/home/pi/musicbot/musicbot/bot.py", line 1057, in _cleanup
    pending = asyncio.all_tasks()
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 45, in all_tasks
    loop = events.get_running_loop()
RuntimeError: no running event loop
[INFO] launcher: Restarting in 2 seconds...
