### ISSUE TITLE
Support slash commands

### ISSUE THREAD

**Issue by DmitriyPekar** [Just-Some-Bots/MusicBot#2323]
### What new feature would you like to see?

https://discord.com/blog/welcome-to-the-new-era-of-discord-apps

### Which of these categories fit your request?

Existing command update

### Just checking...

- [X] I have confirmed that my feature has not already been requested.
- [X] I have confirmed that my feature has not already been implemented in the `review` branch.

**Comment by BabyBoySnow** [comment]
Since we use a custom command handler for MusicBot, this feature I do not see being supported.
