### ISSUE TITLE
bot no worky because ytdl

### ISSUE THREAD

**Issue by Xplodin** [Just-Some-Bots/MusicBot#2324]
### What went wrong?

musicbot.exceptions.CommandError: Error extracting info from search string, youtubedl returned no data. You may need to restart the bot if this continues to happen.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 377, in _run_event
    await coro(*args, **kwargs)
  File "/root/MusicBot/musicbot/bot.py", line 4104, in on_message
    content = self._gen_embed()
  File "/root/MusicBot/musicbot/bot.py", line 1361, in _gen_embed
    icon_url=self.user.avatar_url,
AttributeError: 'ClientUser' object has no attribute 'avatar_url'

### How do we reproduce this?

use the bot lol same log happens with spotify

### Which version of the bot are you using?

release-151221

### Which operating system are you using?

Ubuntu 18.04 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by AleanaA** [comment]
This has nothing to do with ytdl, use the review branch.

**Comment by weerl** [comment]
@AleanaA my instance of the bot has been returning this same error while trying to pull from youtube. I am however am using the review branch and have updated all my dependencies.

**Comment by AleanaA** [comment]
> @AleanaA my instance of the bot has been returning this same error while trying to pull from youtube. I am however am using the review branch and have updated all my dependencies.

Make sure the bot is up to date and that pycord is update, this error is caused by either an out of date bot, or an out of date pycord.
