### ISSUE TITLE
Long Playlist Sudden song stop and

### ISSUE THREAD

**Issue by kw4z1eb0i** [Just-Some-Bots/MusicBot#233]
So i was playing a super long playlist and ran into this error
https://gyazo.com/73e957eee0ab053af36b14e362e79adf
i added a ton of songs and its just thrown away cause i would have to renter the whole playlist :(
is there an option to resume where it left off or to at least save my playlist without me re entering a ton of songs.
i know the songs are cached

**Comment by imayhaveborkedit** [comment]
There is no error in that picture.  The red text is a warning from ffmpeg about something in the audio data.  It happens all the time, and doesn't break anything.  Saving the queue and reloading it when the bot restarts will be something for the next version, included with playlist stuff I suppose.
