### ISSUE TITLE
Task exception was never retrieved

### ISSUE THREAD

**Issue by theguy404** [Just-Some-Bots/MusicBot#234]
my bot crashs serveral times a day with the following error, any idea how to fix this?

> Task exception was never retrieved
> future: <Task finished coro=<WebSocketCommonProtocol.run() done, defined at C:\Users\Terry\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py:296> exception=ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)>
> Traceback (most recent call last):
>   File "C:\Users\Terry\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 241, in _step
>     result = coro.throw(exc)
>   File "C:\Users\Terry\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 302, in run
>     msg = yield from self.read_message()
>   File "C:\Users\Terry\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 324, in read_message
>     frame = yield from self.read_data_frame(max_size=self.max_size)
>   File "C:\Users\Terry\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 379, in read_data_frame
>     frame = yield from self.read_frame(max_size)
>   File "C:\Users\Terry\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 411, in read_frame
>     self.reader.readexactly, is_masked, max_size=max_size)
>   File "C:\Users\Terry\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\framing.py", line 77, in read_frame
>     data = yield from reader(2)
>   File "C:\Users\Terry\AppData\Local\Programs\Python\Python35-32\lib\asyncio\streams.py", line 509, in readexactly
>     block = yield from self.read(n)
>   File "C:\Users\Terry\AppData\Local\Programs\Python\Python35-32\lib\asyncio\streams.py", line 482, in read
>     yield from self._wait_for_data('read')
>   File "C:\Users\Terry\AppData\Local\Programs\Python\Python35-32\lib\asyncio\streams.py", line 423, in _wait_for_data
>     yield from self._waiter
>   File "C:\Users\Terry\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 358, in __iter__
>     yield self  # This tells Task to wait for completion.
>   File "C:\Users\Terry\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 290, in _wakeup
>     future.result()
>   File "C:\Users\Terry\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
>     raise self._exception
>   File "C:\Users\Terry\AppData\Local\Programs\Python\Python35-32\lib\asyncio\selector_events.py", line 664, in _read_ready
>     data = self._sock.recv(self.max_size)
> ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
> Task was destroyed but it is pending!
> task: <Task pending coro=<VoiceClient.keep_alive_handler() running at C:\Users\Terry\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py:198> wait_for=<Future pending cb=[Task._wakeup()]>>
> Task was destroyed but it is pending!
> task: <Task pending coro=<WebSocketCommonProtocol.run() running at C:\Users\Terry\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py:302> wait_for=<Future pending cb=[Task._wakeup()]>>

**Comment by link2110** [comment]
This is the WS being closed by cloudflare. There is nothing you can do about this, other than running review. https://github.com/SexualRhinoceros/MusicBot/archive/review.zip
