### ISSUE TITLE
IndexError: list index out of range on Fedora 38

### ISSUE THREAD

**Issue by OzzyHelix** [Just-Some-Bots/MusicBot#2341]
### What went wrong?

playing songs using the play cmd produces a `IndexError: list index out of range` on Fedora 38 amd64 using a venv
```
Download started: https://youtu.be/L5uV3gmOH9g
Download complete: https://youtu.be/L5uV3gmOH9g
WARNING: Could not grab data from i18n key on_player_play-onChannel_playingMention.
Task exception was never retrieved
future: <Task finished name='Task-61' coro=<MusicBot.on_player_play() done, defined at /home/ozzy/Desktop/MusicBot/musicbot/bot.py:560> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/home/ozzy/Desktop/MusicBot/musicbot/bot.py", line 646, in on_player_play
    videoID = url.split("watch?v=")[1].split("&")[0]
              ~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

### How do we reproduce this?

be running Fedora 38 on amd64
be running a venv virtual envirerment
python run.py
also this is happening with the dev branch 

### Which version of the bot are you using?

None

### Which operating system are you using?

Other

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by BabyBoySnow** [comment]
This would happen on the review branch as well, since it's caused by my implementation of embedding the now playing messages. Are you using a link or just doing something like `!play song_name`?

**Comment by OzzyHelix** [comment]
I've done both

**Comment by OzzyHelix** [comment]
I just tried doing it with links doesn't work but doing names does

**Comment by BabyBoySnow** [comment]
Huh, weird behavior I'm not really sure what the underlying issue is. Basically all this code does is rewrite the URL to be fetchable to create an embed. Is there any other errors?

**Comment by OzzyHelix** [comment]
the problem is with using urls in the play command but the weird thing is I haven't noticed this issue on other OSs I've only been having this issue on Fedora 38 I tried it on Arch Linux and Windows and it worked fine

**Comment by OzzyHelix** [comment]
I can't remember off the top of my head by if but I think when trying to do the np cmd if a link was used to play the np cmd breaks in the same way

**Comment by OzzyHelix** [comment]
I was testing this last night so my memory of the np cmd issue is not great

**Comment by BabyBoySnow** [comment]
I'm at work rn, but I'll look into this tonight when I get home. It shouldn't have any issues with a link at all, but if it is that's very odd. Thank you for telling me

**Comment by OzzyHelix** [comment]
np

**Comment by OzzyHelix** [comment]
again I see this is issue on Fedora 38 but not other OSs tho I've only tested Windows and Arch Linux

**Comment by BabyBoySnow** [comment]
I just pushed a change to address this, please lmk if it solves it.

**Comment by OzzyHelix** [comment]
yes that change fixed it thanks
