### ISSUE TITLE
Unable to queue playlist on Fedora 38

### ISSUE THREAD

**Issue by OzzyHelix** [Just-Some-Bots/MusicBot#2342]
### What went wrong?

I am unable to queue playlist from YouTube and SoundCloud with YouTube it errors out but on soundcloud queuing a playlist hangs
```
Traceback (most recent call last):
  File "/home/ozzy/chickenfocker/musicbot/bot.py", line 4387, in on_message
    response = await handler(**handler_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozzy/chickenfocker/musicbot/bot.py", line 1721, in cmd_play
    return await self._cmd_play(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozzy/chickenfocker/musicbot/bot.py", line 2254, in _cmd_play
    t0 = time.time()
         ^^^^^^^^^
AttributeError: 'builtin_function_or_method' object has no attribute 'time'
```

### How do we reproduce this?

be running in a venv virtual environment with python 3.11.3
summon the bot to a channel 
and try and do the play cmd with a youtube playlist and it will error out
and try and do the play cmd with a soundcloud playlist and it will do nothing and when you try and shut the bot down the program will hang when shutting down the bot.
I am using the dev branch for this 
and I renamed the folder the bot exist in for my server 

### Which version of the bot are you using?

None

### Which operating system are you using?

Other

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by OzzyHelix** [comment]
I'm sorry I looked on the first page of issues I didn't look completely through them but I noticed it errors out when I try to do any playlist from YouTube and just hangs the program on closing when a soundcloud playlist is attempted

**Comment by OzzyHelix** [comment]
I apologize if I'm being a nuisance I choose to use the dev branch because it was more up to date and I'm just reporting issues as I find them

**Comment by BabyBoySnow** [comment]
Nah, it helps get stuff ready to be pushed to review for final testing before going to master. The idea of dev branch is to be able to push stuff with minimal testing, and have users help pin point issues. As for this one, it's very odd since time is imported in the code. I honestly haven't the slightest why it wouldn't work. A shot in the dark surely but maybe try changing `import time` to `from time import time, sleep` ? It should be in the first lines of bot.py

**Comment by OzzyHelix** [comment]
I can try that

**Comment by OzzyHelix** [comment]
this is what I got when I ran that it might just be because the video has a copyright claim I'm going to try a different playlist
```
ERROR: [youtube] w5GisyvQJ3Q: Video unavailable. This video is no longer available due to a copyright claim by Tristan Lohengrin
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/home/ozzy/chickenfocker/musicbot/bot.py", line 4387, in on_message
    response = await handler(**handler_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozzy/chickenfocker/musicbot/bot.py", line 1721, in cmd_play
    return await self._cmd_play(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozzy/chickenfocker/musicbot/bot.py", line 2254, in _cmd_play
    t0 = time.time()
         ^^^^^^^^^
AttributeError: 'builtin_function_or_method' object has no attribute 'time'
```

**Comment by OzzyHelix** [comment]
no dice same error different reason
```
.play https://youtube.com/playlist?list=PL9JuFiYPkN3kOw5BDfWQ6bqI8jo9R7Odp&feature=shared
ERROR: [youtube] pZd-AOZNAXo: Private video. Sign in if you've been granted access to this video
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/home/ozzy/chickenfocker/musicbot/bot.py", line 4387, in on_message
    response = await handler(**handler_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozzy/chickenfocker/musicbot/bot.py", line 1721, in cmd_play
    return await self._cmd_play(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozzy/chickenfocker/musicbot/bot.py", line 2254, in _cmd_play
    t0 = time.time()
         ^^^^^^^^^
AttributeError: 'builtin_function_or_method' object has no attribute 'time'
```

**Comment by BabyBoySnow** [comment]
Well the bad news is that you wouldn't be able to listen to whatever you're trying anyways since it's a private video and we don't have access to those through yt-dlp. I don't know what's going on with time but I'll try to ask around and see what I can find

**Comment by OzzyHelix** [comment]
I was just grabbing random playlist off YouTube to try with the bot none of them seem to work tho

**Comment by OzzyHelix** [comment]
I wasn't try any particular thing I was just searching playlist on YouTube and trying them

**Comment by OzzyHelix** [comment]
I never expected yt-dlp to give me access to something I'm not allowed to its more that I'm throwing random playlist at the bot to try and it keeps erroring out in the same sort of way

**Comment by BabyBoySnow** [comment]
I can't create this error on windows so I'll keep this open for now and see if anyone maybe can find a solution or reproduce.

**Comment by OzzyHelix** [comment]
I will test this on other systems as well the only other systems I have are a fedora 38 VM in VMware and Arch Linux and Windows I'll test it on those 3 systems

**Comment by OzzyHelix** [comment]
I was able to reproduce the issue on my Fedora 38 VM I will now test on Windows

**Comment by OzzyHelix** [comment]
from what I can tell so far tho is its a problem with the response handling code because I do not get a message in discord when this error occurs either it only shows up in the command line

**Comment by OzzyHelix** [comment]
this is the error I got on the Fedora VM
```
Traceback (most recent call last):
  File "/home/ozzy/Desktop/MusicBot/musicbot/bot.py", line 4387, in on_message
    response = await handler(**handler_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozzy/Desktop/MusicBot/musicbot/bot.py", line 1721, in cmd_play
    return await self._cmd_play(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozzy/Desktop/MusicBot/musicbot/bot.py", line 2254, in _cmd_play
    t0 = time.time()
         ^^^^^^^^^
AttributeError: 'builtin_function_or_method' object has no attribute 'time'
```

**Comment by OzzyHelix** [comment]
this is the error I got on Windows
```
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "E:\Users\ozzy\Documents\development\MusicBot\musicbot\bot.py", line 4387, in on_message
    response = await handler(**handler_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\ozzy\Documents\development\MusicBot\musicbot\bot.py", line 1721, in cmd_play
    return await self._cmd_play(
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\ozzy\Documents\development\MusicBot\musicbot\bot.py", line 2254, in _cmd_play
    t0 = time.time()
         ^^^^^^^^^
AttributeError: 'builtin_function_or_method' object has no attribute 'time'
```

**Comment by OzzyHelix** [comment]
same issue on Arch Linux
```
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/mnt/e/Users/ozzy/Documents/development/MusicBot/musicbot/bot.py", line 4387, in on_message
    response = await handler(**handler_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/Users/ozzy/Documents/development/MusicBot/musicbot/bot.py", line 1721, in cmd_play
    return await self._cmd_play(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/Users/ozzy/Documents/development/MusicBot/musicbot/bot.py", line 2254, in _cmd_play
    t0 = time.time()
         ^^^^^^^^^
AttributeError: 'builtin_function_or_method' object has no attribute 'time'
```

**Comment by OzzyHelix** [comment]
I'm going to feel silly if this is my fork but I will check for that

**Comment by BabyBoySnow** [comment]
This has been merged into the discord.py[voice] master branch but when using it I was having issues. Please make sure you're using the voice internals rewrite

`python -m pip install git+https://github.com/imayhaveborkedit/discord.py@voice_rewrite#egg=discord.py[voice]`

**Comment by OzzyHelix** [comment]
I'm going to admit I goofed. I had `import time from time` and `import time` and it was causing a conflict somewhere reworked my log deletion code to work with just `import time` and it now works this was an issue with my fork and I'm sorry for wasting your time no pun intended

**Comment by BabyBoySnow** [comment]
I lol'ed at the unintentional pun no worries glad you got it sorted.

**Comment by OzzyHelix** [comment]
I'll be sure to test my fork against the dev branch before making issues in the future
