### ISSUE TITLE
Update Wiki to include Fedora 38 and Rocky Linux 9 documentation 

### ISSUE THREAD

**Issue by OzzyHelix** [Just-Some-Bots/MusicBot#2343]
### What new feature would you like to see?

the wiki is well put together and has a lot of Linux distros on it and mac os and windows etc but the CentOS Documentation is all that exist for RHEL based distro users it would be super helpful to people using Fedora as a Server or people using Rocky and AlmaLinux if they were included in the install guide on the wiki

### Which of these categories fit your request?

Other

### Just checking...

- [X] I have confirmed that my feature has not already been requested.
- [X] I have confirmed that my feature has not already been implemented in the `review` branch.

**Comment by Jcodeerd** [comment]
Sure, I can probably include it with https://github.com/Just-Some-Bots/MusicBot/pull/2187

**Comment by OzzyHelix** [comment]
sounds good
