### ISSUE TITLE
QOL: Differentiating channels, assuming !play when a link is posted on its own

### ISSUE THREAD

**Issue by Noctimor** [Just-Some-Bots/MusicBot#235]
In my Discord room, I have a "#music" channel designed to keep the clutter out of the main chat when adding songs to the bot. Given that the sole purpose of this channel is to add music, it'd be nice if there was an option to assume that if a standalone link is posted in a designated channel, then that song should be placed in the queue, as it's more convenient to just Ctrl-C, Ctrl-V a link and then go back to whatever I was doing. Definitely more of a quality-of-life thing than anything, and I totally understand (and agree) that other things should probably come first.

**Comment by rrbailey89** [comment]
It sounds like what your saying is that you want the bot to read other channels that its not bound to.. and if someone posts in the wrong channel to move it to the correct channel and then execute?

**Comment by Noctimor** [comment]
Not quite. I'm fine with the current system of only accepting commands from the channels its bound to, it's just within those channels I want to forego having to put !play in front of a link. When I have a channel that's dedicated to queueing music, it'd be nice to just copy-paste a link and get on with what I'm doing.

**Comment by imayhaveborkedit** [comment]
This is extra low priority, but if I ever run out of things to do this seems like something decent to add.

**Comment by lavender-sys** [comment]
You could set the prefix to nothing. @Noctimor

**Comment by Noctimor** [comment]
If I set the prefix to nothing, wouldn't I still have to say "play" first? And yeah, definitely low priority -- just aimed to get the suggestion out there
