### ISSUE TITLE
Bot hangs suddenly without any errors

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#236]
I updated MusicBot yesterday. Since then it's started to just suddenly stop playing music to the channel. When putting !np it still shows that the song is still playing. Putting more songs will still keep the music bot not playing the song for the channel. The bot is showing no errors neither in console or in the chat.

The only solution so far has been restarting the bot, but this has had to be done roughly every 30-60 minutes or so.

What could be the problem here?

**Comment by ghost** [comment]
I also have this same problem can confirm it happens around 40-50 minutes

**Comment by rrbailey89** [comment]
have you updated dependencies .. are you using latest version of review?

**Comment by ghost** [comment]
@rrbailey89 Yes, I did. the bot still doesn't play any song at all after some time.Basically no errors, the bot seems to work fine, except no sound

**Comment by Figworth** [comment]
This happens to me when discord's servers have ping issues. Everyone will sound like a robot, the song will be choppy, and then the bot will stop playing songs.

**Comment by nhmelo** [comment]
I've been having the same issue. It's really annoying and I have no idea why it happens. 
No error is shown, it just stops and acts like it still works but does not play anything.

**Comment by n7Angel** [comment]
Same issue here, I'm going to monitor that suggestion about ping.

**Comment by link2110** [comment]
This is a library issue, we're waiting on a fix from the library author. For now you can `!restart` the bot when this happens.

**Comment by brawaru** [comment]
This is not good to restart bot every 10 minutes...
Especially when you listened playlist.

**Comment by imayhaveborkedit** [comment]
This should be fixed.
