### ISSUE TITLE
Song Speed Randomly Changes.

### ISSUE THREAD

**Issue by Zelioom** [Just-Some-Bots/MusicBot#237]
The bot will randomly play the song a bit faster, as if trying to catch up. It happens at random. (running on i5 4670k, upload speed is 5mbps) Any way to fix this?

**Comment by rrbailey89** [comment]
This is your internet connection.

**Comment by Figworth** [comment]
This can also happen when there are problems with the Discord servers, I've noticed. Seems to happen when other people sound choppy.

**Comment by sameer** [comment]
This issue should be closed, not caused by the bot itself.

**Comment by Gaaamin** [comment]
Same problem here, even when all the songs are already downloaded. It's like it depends on the cpu usage or something...
Still got it with the last update. Except it, it's all good, thanks for the good work!

**Comment by jayktaylor** [comment]
This isn't caused by the bot and is instead down to a number of possible reasons:
- Internet connection
- Discord's servers
- CPU usage

Host it on a good VPN. You will tend not to have problems. Switch server regions if it helps.

**Comment by sameer** [comment]
Don't comment on an issue where the solution has already been provided please, this is almost a month old and was pointlessly brought to the center of attention.

This issue should've been closed a while ago.

Thanks, Robotia.
