### ISSUE TITLE
[Feature Request] Stream support for playlists

### ISSUE THREAD

**Issue by BgueC6595** [Just-Some-Bots/MusicBot#2376]
### What new feature would you like to see?

`!stream` is a pretty great feature as it e.g. instantly plays 1hr+ long videos without even taking up disk space.

It would be really nice if this feature was compatible with playlists. Currently using it on a playlist (tested with Youtube playlists) will simply return "this is not a stream".

### Which of these categories fit your request?

Existing command update

### Just checking...

- [X] I have confirmed that my feature has not already been requested.
- [X] I have confirmed that my feature has not already been implemented in the `review` branch.

**Comment by BabyBoySnow** [comment]
I wouldn't hold your horses on this one, I think it will be quite a bit of work.
