### ISSUE TITLE
It a problem and i can't figure it out 

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#238]
![issue](https://cloud.githubusercontent.com/assets/18206477/14938720/099f87a6-0efb-11e6-9ca1-90bb13178ed9.PNG)
I have no clue what this is so if i could get some help with it that would be great.

**Comment by link2110** [comment]
To fix the bug with `AttributeError: '<class 'musicbot.bot.MusicBot'>' object has no attribute '_session_id_found'` please download the review version of the bot, found at: https://github.com/SexualRhinoceros/MusicBot/archive/review.zip
Also update your deps by running `update_deps.bat` on windows, or running `python -m pip install --upgrade -r requirements.txt` on Mac/Linux

**Comment by ImthePeach** [comment]
To fix the bug with AttributeError: '<class 'musicbot.bot.MusicBot'>' object has no attribute '_session_id_found' please download the review version of the bot, found at: https://github.com/SexualRhinoceros/MusicBot/archive/review.zip
Also update your deps by running update_deps.bat on windows, or running python -m pip install --upgrade -r requirements.txt on Mac/Linux

**Comment by ghost** [comment]
Now, the commands aint working but the bot is. is there a fix for this too ?

**Comment by rrbailey89** [comment]
ensure you dont have an extra space behind "bind to channels" ..

**Comment by ghost** [comment]
it has no spaces

**Comment by ghost** [comment]
the music bot will play music just not the music i pick its on the auto playlist and i disabled that and the commands still didn't work.

**Comment by ghost** [comment]
the commands just don't do anything
