### ISSUE TITLE
"bot is not in voice channel"

### ISSUE THREAD

**Issue by akiiyra** [Just-Some-Bots/MusicBot#239]
i've done all the steps but no matter what, my bot wont play music and say "The bot is not in a voice channel.  Use .summon to summon it to your voice channel."

how do i fix this, ive tried manually leaving voice channels through browser and even use other accounts

even my friend who tried making a bot is experiencing the same problem

**Comment by sameer** [comment]
There was an issue that was mentioned on the official SexualRhinoceros Discord. You need to do `git clone https://github.com/SexualRhinoceros/MusicBot` then `git checkout review`. That version should work for you.

**Comment by MichaelFedora** [comment]
Or just go [here](https://github.com/SexualRhinoceros/MusicBot/tree/review) and click the `Download ZIP` on the right... or a [link for the lazy](https://github.com/SexualRhinoceros/MusicBot/archive/review.zip).

**Comment by sameer** [comment]
:+1: that works too

**Comment by sameer** [comment]
For future reference: use the main branch now, not review.
