### ISSUE TITLE
Playlist take long to play if there are inaccessible videos

### ISSUE THREAD

**Issue by Armagedon13** [Just-Some-Bots/MusicBot#2392]
### What went wrong?

Playlist take long to play if there are inaccessible videos and the songs don't start until check the status of all the videos in the playlist

### How do we reproduce this?

1_start the bot
2_+p playlist https://www.youtube.com/playlist?list=PLg0uzHBxKbxEJlb8YNvt0QBirjEg4-A_V
(example)
3_wait until check all the playlist and take too long, maybe add the playlist and check later when the song is blocked skip it.

### Which version of the bot are you using?

release-260419

### Which operating system are you using?

Windows 7 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by Armagedon13** [comment]
+shuffle make to check again all the videos

**Comment by BabyBoySnow** [comment]
Hi there 👋 thanks for opening an issue, would you mind sharing the branch you are using? I suspect you are using the master branch and I would encourage you to use the dev branch which has some overhauls to the way music is processed.

**Comment by Armagedon13** [comment]
yes i follow the [guide](https://just-some-bots.github.io/MusicBot/installing/windows/), im gonna check the dev branch 🫡

**Comment by BabyBoySnow** [comment]
If you need any assistance switching feel free to ask here or on our [support server](https://www.discord.gg/bots)

**Comment by Armagedon13** [comment]
works really good 👌thanks for the info
