### ISSUE TITLE
[Minor Feature Request] have logs files with date and time based filename and clean up routine

### ISSUE THREAD

**Issue by OzzyHelix** [Just-Some-Bots/MusicBot#2393]
### What new feature would you like to see?

This is a simply request. I would like it if the logs filenames contained the date and time of their creation and then maybe have a routine that every time the bot is started up. It deletes logs older than say 7 days for example. Overwriting the existing log file has been a pet peeve of mine for a while. Having log files with date and time based filenames and a routine to clean older logs up would fix a lot of my problems with the logging system. I hope you will consider this and maybe make it a feature thank you
- Ozzy

### Which of these categories fit your request?

Other

### Just checking...

- [X] I have confirmed that my feature has not already been requested.
- [X] I have confirmed that my feature has not already been implemented in the `review` branch.

**Comment by OzzyHelix** [comment]
my goal with this is to improve small Quality of life stuff with the bot this has been an annoyance for me for some time

**Comment by itsTheFae** [comment]
So Python logging does have a file handler that theoretically will do what you want, essentially making the log system handle rotation of the log files as-needed, but only triggered by logs being emitted in the first place rather than the current implementation in `dev`  which only bothers to rotate files at shutdown, when logging is finished.

**Comment by OzzyHelix** [comment]
I will retract this because `python run.py  --logs-kept 100` suites my needs perfectly

**Comment by itsTheFae** [comment]
> I will retract this because `python run.py --logs-kept 100` suites my needs perfectly

And for setting the date format using `--log-rotate-fmt` you can use the table on this page to understand the '%' formats that are available for use:  https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior
