### ISSUE TITLE
Error traceback

### ISSUE THREAD

**Issue by Heldegar** [Just-Some-Bots/MusicBot#241]
![bug](https://cloud.githubusercontent.com/assets/19143393/14946596/ab203844-1024-11e6-9ce6-5f76d5a14962.png)

Hello i'm getting this error when i launch the file "runbot" can you help me ?

**Comment by imayhaveborkedit** [comment]
Use review, not the old version.  https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Windows-7-and-up#2a-download-musicbot
