### ISSUE TITLE
Music Looping

### ISSUE THREAD

**Issue by hiblychibly** [Just-Some-Bots/MusicBot#2410]
### What new feature would you like to see?

a command which can loop a single song over and over again until stop command is given

### Which of these categories fit your request?

New command

### Just checking...

- [X] I have confirmed that my feature has not already been requested.
- [X] I have confirmed that my feature has not already been implemented in the `review` branch.

**Comment by BabyBoySnow** [comment]
Please see [commands here](https://just-some-bots.github.io/MusicBot/using/commands/) the command is called repeat, use `!help repeat` for further information
