### ISSUE TITLE
aliases with spaces don't work

### ISSUE THREAD

**Issue by Jonas1999** [Just-Some-Bots/MusicBot#2413]
### What went wrong?

I'm trying to get `"restart upgrade": ["upgrade", "update", "test"]` in aliases.json to work but it doesn't work.
My other aliases work except that one, the entire aliases.json contains the following:
`{
    "play": ["p"],
    "skip": ["s"],
    "queue": ["q"],
    "latency": ["ping"],
    "restart": ["reboot", "reset"],
    "restart upgrade": ["upgrade", "update", "test"],
    "checkupdates": ["checkupdate"],
    "summon": ["join", "connect", "come"],
    "disconnect": ["leave", "stop"]
}`

### How do we reproduce this?

Have an aliases.json contain what I mentioned above and run the bot, the aliases won't be acknowledged by the bot.
The bot is running on an Raspberry Pi 4 with Debian 12/ Raspberry Pi OS 64 Bit.

### Which version of the bot are you using?

I am using the "review" branch

### Which operating system are you using?

Ubuntu 18.04 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by itsTheFae** [comment]
Currently, aliases are quite limited and will only function as replacement names for command names.  

I did poke around with this while working on the last few rounds of updates.  I think the feature could definitely use a handful of changes.   For example, being able to manage the aliases via command would be nice to have, or minimally some indicator that the aliases even exist via like help command responses.  

At least I can say it was on my radar.  Was going to take it on before doing the UI stuff I had planned. But it could be a while before I get the time to work out proper updates for it.

**Comment by BabyBoySnow** [comment]
I'm closing this as complete due to the latest pr merged into dev, if it still doesn't meet you're requirements feel free to open a new issue
