### ISSUE TITLE
Bot Continuously Downloads Music From Autoplaylist.

### ISSUE THREAD

**Issue by Zelioom** [Just-Some-Bots/MusicBot#242]
I have savevideos off, but, while music is playing, it shows in the console, music being downloaded all time. I think it happening when savevideos was on aswell. http://imgur.com/arHQCpm
It isn't even saving the videos to the cache, it is just downloading them. http://imgur.com/EZ5BF6w

**Comment by Loafabreadly** [comment]
Are there videos in your audio cache @

**Comment by Zelioom** [comment]
This is what is going on in the audio cache. https://www.youtube.com/watch?v=6Cf4mAhPV2g&feature=youtu.be

**Comment by Loafabreadly** [comment]
I do t think this is an issue if the bot is playing music. It's just downloading the song playing it then deleting it

**Comment by Zelioom** [comment]
No, it downloads, and completes a video every second.

**Comment by Zelioom** [comment]
Alright, it does not constantly download music when savevideos is ON.

**Comment by imayhaveborkedit** [comment]
I just noticed something like this happening with the demo bot.  I'll look into this a bit more.  This probably has nothing to do with the SaveVideos option by the way.

**Comment by imayhaveborkedit** [comment]
I don't remember why this happened but I probably fixed it.
