### ISSUE TITLE
ERROR: [youtube] 8MmR-TbI5n8: Sign in to confirm you’re not a bot.

### ISSUE THREAD

**Issue by Wehrum** [Just-Some-Bots/MusicBot#2420]
### What went wrong?

Hi, I noticed when trying to play songs via YouTube it started erroring on this.

`ERROR: [youtube] 8MmR-TbI5n8: Sign in to confirm you’re not a bot. This helps protect our community. Learn more`

It was working a few days ago, so this is fairly recent. Wondering if the issue is being tracked and if there are any current workarounds?

Thanks,
- Connor
![IMG_5862](https://github.com/user-attachments/assets/a09afbca-f91a-488e-b8e2-f883904e2594)

### How do we reproduce this?

Play any YouTube song

### Which version of the bot are you using?

release-260419

### Which operating system are you using?

Ubuntu 18.04 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by BabyBoySnow** [comment]
Yes we're aware of this issues, it's a result of YouTube fighting bots and adblock. The dev branch has some options to help fight this such as setting a custom user agent, cookie file support and proxy support. Some users have reported that using 0auth2 has helped as well. Join the discord server if you need help with any of that

**Comment by MrSpookyAngel** [comment]
Related: https://github.com/yt-dlp/yt-dlp/issues/10128#issuecomment-2157140324

Basically just install this [yt-dlp plugin](https://github.com/coletdjnz/yt-dlp-youtube-oauth2) through pip.

Update [musicbot/downloader.py](https://github.com/Just-Some-Bots/MusicBot/blob/f7786d795133e18b0c8b55e523ebcbed356ab7ca/musicbot/downloader.py#L40C1-L58C2) to the following:
![image](https://github.com/user-attachments/assets/c089b66e-0845-40a2-8064-d48d3b8da7e9)

Start the bot and  play a song through youtube. This should prompt Oauth. Enter the code and sign into your account (maybe use a throwaway in case of account ban).

Finally, re-enable `quiet` and `no_warnings` as it might cause issues with the bot.

Edit: Make sure to add `youtube:search+oauth2` to `Extractors` in `config/permissions.ini` for each applicable role if you want non-owners to play music through youtube

**Comment by Wehrum** [comment]
> Related: [yt-dlp/yt-dlp#10128 (comment)](https://github.com/yt-dlp/yt-dlp/issues/10128#issuecomment-2157140324)
> 
> Basically just install this [yt-dlp plugin](https://github.com/coletdjnz/yt-dlp-youtube-oauth2) through pip.
> 
> Update [musicbot/downloader.py](https://github.com/Just-Some-Bots/MusicBot/blob/f7786d795133e18b0c8b55e523ebcbed356ab7ca/musicbot/downloader.py#L40C1-L58C2) to the following: ![image](https://private-user-images.githubusercontent.com/69997739/356845171-c089b66e-0845-40a2-8064-d48d3b8da7e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NzU5MTUsIm5iZiI6MTcyMzQ3NTYxNSwicGF0aCI6Ii82OTk5NzczOS8zNTY4NDUxNzEtYzA4OWI2NmUtMDg0NS00MGEyLTgwNjQtZDQ4ZDNiOGRhN2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDE1MTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MDMwNDJjMWJiNDdlZDY1YzIxNDJhMWM5MDc3NGU2YjI3YWM2NTAwN2UyYmE4OTg4MzZlZjdmYzE3ODJlM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N9YwMzebnlsPRmg8abN6OP3-ec-Kkk8YBu1KSYhFEPo)
> 
> Start the bot and play a song through youtube. This should prompt Oauth. Enter the code and sign into your account (maybe use a throwaway in case of account ban).
> 
> Finally, re-enable `quiet` and `no_warnings` as it might cause issues with the bot.
> 
> Edit: Make sure to add `youtube:search+oauth2` to `Extractors` in `config/permissions.ini` for each applicable role if you want non-owners to play music through youtube

Following up with @MrSpookyAngel, I did exactly what you suggested and it is now working again. I really appreciate the post, and hopefully this will help others that also stumble upon this issue.

- Using the `dev` branch
