### ISSUE TITLE
Youtube playback issues (fix with OAuth2 integration?)

### ISSUE THREAD

**Issue by alvin-est** [Just-Some-Bots/MusicBot#2429]
### "Sign in to confirm you’re not a bot. This helps protect our community."

Bot will not play music from YouTube:
`musicbot.exceptions.MusicbotException: ERROR: [youtube] eVli-tstM5E: Sign in to confirm you’re not a bot. This helps protect our community.`

### How do we reproduce this?

Bot is set up on a remote server - YouTube most likely has the IP range flagged. 
Have not tried if it works on local.

The other repo have devised [this solution](https://github.com/jagrosh/MusicBot/pull/1670) but yet to merge into main.

Source files were git cloned and built from Master.
Python 3.10.13 alt-installed on Debian 10.

Issue has been happening only recently.

### Which version of the bot are you using?

None

### Which operating system are you using?

Other

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by BabyBoySnow** [comment]
This is already in the dev branch

**Comment by alvin-est** [comment]
> This is already in the dev branch

Nice! I got it working using the dev branch. 
Bit ugly having to register a throwaway account though but works for now.
