### ISSUE TITLE
3 Days error

### ISSUE THREAD

**Issue by ShayBox** [Just-Some-Bots/MusicBot#243]
I've been getting this error for 3 days now, and have tried updating every day, still https://i.imgur.com/4Z9kr7a.png any ideas why? some of my other bots are broken too

**Comment by imayhaveborkedit** [comment]
You need to update the bot again.  The last few days discord.py has been updated and broke the previous versions of the bot.

**Comment by ShayBox** [comment]
I just did, could you look at my update script and see if its good... https://i.imgur.com/Zj73BcQ.png

**Comment by imayhaveborkedit** [comment]
No.  There's no reason not to use `git` if you're on linux.  Just stop the bot, `git pull`, restart.  You might need to move the autoplaylist if that changed.

**Comment by ShayBox** [comment]
i tried that, but it resets my configs every time its run, and other files... which i dont want

**Comment by ShayBox** [comment]
and i cant install git on amazon aws

**Comment by ImthePeach** [comment]
https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Ubuntu-14.04-and-other-versions
Did you look at this guide? It explains how to run the bot on Ubuntu for servers such as AWS, Digital Ocean, etc.
