### ISSUE TITLE
What is the run command 

### ISSUE THREAD

**Issue by SHADOW-EXE07** [Just-Some-Bots/MusicBot#2439]
### What went wrong?

What is the run command for MusicBot so I can use it in replit 
![Screenshot_20241123_144414](https://github.com/user-attachments/assets/69e692bf-a318-4e89-ac8d-de8d460773e3)

### How do we reproduce this?

Help ;-;

### Which version of the bot are you using?

I am using the "review" branch

### Which operating system are you using?

Other

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by Jcodeerd** [comment]
You could try run.py but I believe replit isn’t supported by musicbot

**Comment by BabyBoySnow** [comment]
Jcodeerd is correct, the bot is not supported on the replit platform. 

**__Recommended VPS hosts:__**
[AWS:](<https://aws.amazon.com/free/>) While AWS has a free tier, it is only limited data usage under this plan. You may still pay monthly for it, and you don't get any customer support if an issue should arise.

**__Free hosting:__**
**No.**
There is no good free VPS hoster, outside of persuading somebody to host for you, which is incredibly unlikely.

[Oracle Cloud Free Tier](<https://www.oracle.com/cloud/free/>)
If you've got enough experience with Linux and managing servers yourself you can try their free tier. 
[Setting up a VCN](<https://docs.oracle.com/en-us/iaas/Content/GSG/Tasks/creatingnetwork.htm#Creating_a_Virtual_Cloud_Network>)
[Setting up an compute instance](<https://docs.oracle.com/en-us/iaas/Content/GSG/Tasks/launchinginstance.htm#Launching_a_Linux_Instance>)
***Note: You are on your own to set this up, and we will not provide support for setting up your server. Nor are we responsible for anything that you do on that server.***
