### ISSUE TITLE
Ubuntu Setup Issue

### ISSUE THREAD

**Issue by Blir** [Just-Some-Bots/MusicBot#244]
Getting this error when going through the Ubuntu setup:

sudo apt-get install libsodium-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libsodium-dev

I am on version 14.04.4 and I did run all the other commands before it.

Am I missing something?

**Comment by imayhaveborkedit** [comment]
That package may not be required for some users.  Skip that one and see if the bot works without it.

**Comment by Blir** [comment]
Okay... I'm getting this error now.

Traceback (most recent call last):
  File "run.py", line 160, in main
    m = MusicBot()
  File "/home/sassyhoratio/dj-bot/musicbot/bot.py", line 68, in **init**
    self.voice_clients = {}
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 237, in **setattr**
    return setattr(self.connection, name, value)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 233, in **getattr**
    raise AttributeError(msg.format(self.**class**, name))
AttributeError: '<class 'musicbot.bot.MusicBot'>' object has no attribute 'connection'
Cleaning up... Done.
Restarting in 6 seconds...

And when it restarts it gets the same error and restarts again.

**Comment by jamesonp** [comment]
@Blir On a side note, to install libsodium-dev do the following:

```
sudo add-apt-repository ppa:chris-lea/libsodium
sudo echo "deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
sudo echo "deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
sudo apt-get update && sudo apt-get install libsodium-dev
```

**Comment by Blir** [comment]
Okay so I discovered the issue was that I copied an existing music bot installation from another machine. Redoing the git clone stuff and then reconfiguring the music bot allowed it to work.
