### ISSUE TITLE
Failed building wheel for cchardet

### ISSUE THREAD

**Issue by Arkeniq** [Just-Some-Bots/MusicBot#2440]
### What went wrong?

Can't install the bot due to dependencies on Debian GNU/Linux 11 (bullseye)

### How do we reproduce this?

I followed the instructions [here.](https://just-some-bots.github.io/MusicBot/installing/debian/) Running `python3.9 -m pip install -U -r requirements.txt` gives the following error:

`ERROR: Failed building wheel for cchardet`
`Running setup.py clean for cchardetFailed to build cchardet`
`ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cchardet)`

### Which version of the bot are you using?

`git clone https://github.com/Just-Some-Bots/MusicBot.git MusicBot -b master`

### Which operating system are you using?

Debian GNU/Linux 11 (bullseye)

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by Arkeniq** [comment]
Requirements.txt asks for cchardet v2.1.7 that is **not** compatible with Python3.10.

**Comment by BabyBoySnow** [comment]
You may find luck with the updating docs [here](https://itsthefae.github.io/MusicBot/) it's in a pr, pending a merge.

**Comment by itsTheFae** [comment]
Please include version information in issue reports.  There are multiple versions of Debian and multiple versions (as well as branches) of MusicBot.

**Comment by Arkeniq** [comment]
Fixed it by installing python-dev and getting cchardet manually.

`sudo apt install python3.9-dev`
`pip install cchardet`
