### ISSUE TITLE
[Feature Request] Autopausing after startup and autojoining an empty voice channel

### ISSUE THREAD

**Issue by Loafabreadly** [Just-Some-Bots/MusicBot#245]
Im running the review branch of the bot and I noticed that the bot will autosummon ti the voice channel I have defined but even if that voice channel is empty, it will cstart to play music to the void even with autopause enabled. Any way to add if AutoPause is enabled, it runs a quick check on Autosummon to voice channel to see if it is empty and run the AutoPause function accordingly?

**Comment by jayktaylor** [comment]
https://github.com/SexualRhinoceros/MusicBot/commit/abb86048649191cbca511166105f65ab6517057e and later commits to `review` have implemented this feature. It'll be in the next release version.

**Comment by jayktaylor** [comment]
Released.
