### ISSUE TITLE
Blacklist for sources

### ISSUE THREAD

**Issue by rrbailey89** [Just-Some-Bots/MusicBot#251]
The ability to allow audio from either only a whitelist or to blacklist certain audio sources I believe is an important feature.

**Comment by arunesh90** [comment]
![image](https://cloud.githubusercontent.com/assets/5787588/15020547/be22ac38-1222-11e6-8c68-478a2d632c5c.png)
No need to repost

**Comment by rrbailey89** [comment]
Except borked has stated before to post feature requests here.

**Comment by imayhaveborkedit** [comment]
#249
