### ISSUE TITLE
Fails to run on Arch Linux

### ISSUE THREAD

**Issue by pcbmaster** [Just-Some-Bots/MusicBot#253]
When I try to run the bot under Arch Linux with all the dependencies installed, I get this:

`Traceback (most recent call last):
  File "run.py", line 202, in <module>
    main()
  File "run.py", line 182, in main
    MusicBot().run()
  File "/home/brett/MusicBot/musicbot/bot.py", line 63, in __init__
    self.voice_clients = {}
  File "/usr/lib/python3.5/site-packages/discord/client.py", line 237, in __setattr__
    return setattr(self.connection, name, value)
AttributeError: can't set attribute
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f220d4870f0>
`
It works on my Debian server, but not here. Why?

**Comment by jayktaylor** [comment]
Use the latest version of review. Yours is outdated. https://github.com/SexualRhinoceros/MusicBot/archive/review.zip

**Comment by pcbmaster** [comment]
I cloned the git repo, is it not the latest version?  I don't use the zip.

**Comment by jayktaylor** [comment]
You need to checkout the **review** branch when using git.
