### ISSUE TITLE
Vote stacking when bot removes messages.

### ISSUE THREAD

**Issue by dwaynehulsman** [Just-Some-Bots/MusicBot#254]
If the bot is set to remove it's messages after x time players can vote again after their confirmation on their vote skip is removed from the chat.

**Comment by santichu95** [comment]
I just tried this on mine and it showed the message again but the votes needed to skip the song did not change\

**Comment by ImthePeach** [comment]
Skip votes log to the bots console. Having a person delete their message, or the bot auto deleting their skip command should have no impact on the skip vote.

**Comment by imayhaveborkedit** [comment]
The voting state has nothing to do with message deletion.
