### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by brawaru** [Just-Some-Bots/MusicBot#255]
How about localization support?

People on my server doesn't know English at "well" level. So I translated some strings for them. But when a new commit is coming I need to manually change lines of code. It's not so good as could be.

For example folder `lang`:
File: `./en_us.json`

``` json
{ 
    "now_playing": "Now playing in %s: **%s**",
    "now_playing_mention": "%s - your song **%s** is now playing in %s!",
    ...
}
```

File `./ru_ru.json`

``` json
{ 
    "now_playing": "Сейчас играет в %s: **%s**",
    "now_playing_mention": "%s Ваша песня - **%s** сейчас играет в %s!",
    ...
}
```

File `./uk_ua.json`

``` json
{ 
    "now_playing": "Зараз грає в %s : **%s**",
    "now_playing_mention": "%s Ваша пісня - **%s** зараз грає в%s!",
    ...
}
```

And just 3 lines in `config/options.ini` file

``` ini
...
[MusicBot]
; Language used by bot
; Make sure your language file placed in "lang" folder
Language = en_us

; The starting volume of the bot.  You can use any value from 0.01 to 1.0 but 0.15 is probably fine
DefaultVolume = 0.15

; Only allow whitelisted users to use commands
; Deprecated in favor of permissions
WhiteListCheck = no

...
```

If you can implement this it will great.

**Comment by imayhaveborkedit** [comment]
I'm going to write a sort of responses file, where the text and delete timeouts are stored.  This will probably be after I write playlists though.

**Comment by jayktaylor** [comment]
Duplicate of #115
