### ISSUE TITLE
Permissions Issue since the New Update

### ISSUE THREAD

**Issue by LaxSlash** [Just-Some-Bots/MusicBot#256]
Ever since the new update, the roles on the bottom of permissions.ini are no longer taking precedence, and it looks like users in my server are someway somehow being granted the perms of their lowest role in the hierarchy.

This presents an issue in my case because I have two groups - Clan Member and Leadership - that both have permissions setup in the server, and leaders need to be clan members as well due to certain programming of other bots that I have running in the server.

**Comment by marvinside** [comment]
Having the Same Problem.
I have some groups to individually grant Comands to users.

``` ini
[Limited]
CommandWhitelist = play queue np perms help skip perms
; CommandBlacklist =
IgnoreNonVoice = play skip search
GrantToRoles = 210825168795205633
MaxSongLength = 600
MaxSongs = 8
AllowPlaylists = no
InstaSkip = no

; Allows summon Command
[SummonBot]
CommandWhitelist = summon
; CommandBlacklist =
GrantToRoles = 223523212242321408

[User]
CommandWhitelist = perms
GrantToRoles = 223525780032978945
```

And if i assign a user to SummonBot and User, he isn't longer able to use the !perms command.

```
max_playlist_length: 0
allow_playlists: True
name: SummonBot
max_songs: 0
instaskip: False
max_song_length: 0
granted_to_roles: {'223523212242321408'}
command_whitelist: {'summon'}
```

**Comment by Matthanic** [comment]
I'm still having this issue as well. However, listing the users individually always gives them the proper rights. But that is a lot of effort to keep up with on busy servers.

**Comment by amit177** [comment]
If this is still an issue in the latest version, please open a new issue.
