### ISSUE TITLE
Is there a fix to this ?

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#257]
![49ffc936a9bf104898a58a16f9368e2b](https://cloud.githubusercontent.com/assets/18206477/15094452/9352b55a-1472-11e6-9d6b-fd47371449c4.png)
None of the commands are working. is there a fix ?

**Comment by Echoskope** [comment]
Is the bot showing any logs of commands being received? Can you double check that your command symbol is `!` in the configuration file?

**Comment by ghost** [comment]
no it is showing nothing

**Comment by link2110** [comment]
Come on the help server and we will give you a hand.

**Comment by imayhaveborkedit** [comment]
I assume this is sorted out.
