### ISSUE TITLE
!ignoring command from myself? (PLEASE HELP)

### ISSUE THREAD

**Issue by Benjoi4231** [Just-Some-Bots/MusicBot#259]
Hello, I was wondering about the "!ignoring command from myself" when i try to "!play https://www.youtube.com/watch?v=mE1K6Pyoclg" any explanation or did I seriously screw up?

**Comment by imayhaveborkedit** [comment]
As stated in the config file, the bot needs a dedicated account to work.  You're either logged in as the bot somewhere or you're running the bot on your own account.

**Comment by Benjoi4231** [comment]
Thank you! that solved it
