### ISSUE TITLE
Failed connection

### ISSUE THREAD

**Issue by Pepperonis** [Just-Some-Bots/MusicBot#267]
Hey guys, I tried to make a music bot for my server but whenever I try to run the bot it keeps failing to connect to my voice channel.
![error](https://cloud.githubusercontent.com/assets/19367390/15271448/d139a82e-19fe-11e6-8cab-4e907d4cbff4.JPG)

**Comment by narrundo** [comment]
maybe you haven't give proper permission for your bot to join any channel

**Comment by Pepperonis** [comment]
He has full permissions on the server

**Comment by sameer** [comment]
Is this issue still persisting? If so, could you check if python is being blocked by your windows firewall?

**Comment by Pepperonis** [comment]
It still is. I've tried turning off both my firewall and anti virus but still the same results.

**Comment by sameer** [comment]
What kind of router are you using?

**Comment by Pepperonis** [comment]
Nevermind, I got it working now.

**Comment by piedoom** [comment]
Can you explain how you got it working please?  Having the same issue.
