### ISSUE TITLE
attributeError : can't set attribute

### ISSUE THREAD

**Issue by shaille** [Just-Some-Bots/MusicBot#269]
I had this problem when I made the updating of the bot
![ss 2016-05-15 at 02 40 09](https://cloud.githubusercontent.com/assets/19372849/15274092/64d9154a-1aab-11e6-9f23-0b61fc54f4c3.png)

**Comment by shaille** [comment]
no it's fine. i fond it

**Comment by GhostBladeDreams** [comment]
What did you do to fix it im having this same issue. i dont know if i just missed something or what. the account for the bot isnt logged in any where and i legitimently dont know how to fix

**Comment by imayhaveborkedit** [comment]
He was using an outdated version of the bot.  The review branch version is currently the only working version.
