### ISSUE TITLE
Add an option to remove 'Playing {song name}' 

### ISSUE THREAD

**Issue by caramelpony** [Just-Some-Bots/MusicBot#270]
yeah. Pretty self explanatory.

**Comment by jayktaylor** [comment]
As of the latest commits to the `review` branch, this will update to show the number of servers if multiple servers are playing music.

**Comment by caramelpony** [comment]
How would I go about using that branch? Would I just git-clone it?

**Comment by jayktaylor** [comment]
You should be using review regardless. No other version is supported anymore. You can get it by cloning, and then `git checkout review`

**Comment by imayhaveborkedit** [comment]
I'm probably not going to add an option to remove the np message entirely.  It's fixed for multiserver, but if you want to disable it you can tweak the code yourself.  That would be the `update_now_playing` function.
