### ISSUE TITLE
BindChannels exits, but no channel binded on new server

### ISSUE THREAD

**Issue by lilyremigia** [Just-Some-Bots/MusicBot#272]
If there is no binded channels for a server, but the binded channels option enabled the bot cannot be used at all. 
I suggest that in that case it will get follow these commands:
- !help for instructions
- !listids so server administrators can get the id lists.

Plus two new commands on any channel from that server:
- !bindtochannel <id>: if the user who runed the comment has the Manage Server permission it will add this channel to the BindToChannels list. Then disable itself on that server, until no binded channels exits on that server.
- !setvoicechannel <id> Same with bindtochannel , but with the AutojoinChannels.

**Comment by lilyremigia** [comment]
or it could just DM the owner of the bot a Invite Link, if the bot can create it.
But the first one would be more handy, anyway.

**Comment by jayktaylor** [comment]
Editing of configuration options (like you suggest, `!bindtochannel` and `!setvoicechannel`) are a feature that is likely to be added at some point.

Additionally, if you uncomment the `BindToChannels` line in the config you're expected to add IDs there. If you don't, then you clearly haven't read the instructions and therefore should be left with an unusable bot. It's not hard.

**Comment by lilyremigia** [comment]
I read the instructions, I'm just saying if no channels binded on the duild, while you have channels binded on other guild you need to get the id with #channel_metion add to the config, and stuff. And it's very long, a bit, and requires, me to initialize the bot to work on the guild.

**Comment by amit177** [comment]
If this is still an issue in the latest version, please open a new issue.
