### ISSUE TITLE
wont join channel

### ISSUE THREAD

**Issue by xsnowfoxx** [Just-Some-Bots/MusicBot#280]
I'm running the review as stated on the readme

root@vpn:/MusicBot-develop# cd /bot
root@vpn:/bot# sh  run.sh
Connected!  Musicbot v1.9.5-review-2016.5.17

Bot:   ***********************************************
Owner: *******************************************

Server List:
- *****************

Not bound to any text channels
Not autojoining any voice channels

Options:
  Command prefix: !
  Default volume: 15%
  Skip threshold: 1 votes or 50%
  Now Playing @mentions: Enabled
  Auto-Summon: Enabled
  Auto-Playlist: Enabled
  Auto-Pause: Enabled
  Delete Messages: Enabled
    Delete Invoking: Disabled
  Debug Mode: Disabled
  Downloaded songs will be deleted

Attempting to autosummon...
Found owner in "Quaggan Party", attempting to join...

then the bot just hangs on that.

the release candidate 7 actually works for a few hours and then crashes so I've been using that for like the past 3 weeks

**Comment by pamymaf** [comment]
We're helping him in the help channel.

**Comment by xsnowfoxx** [comment]
you can go ahead and close it!
