### ISSUE TITLE
Autopause after joining empty Channel

### ISSUE THREAD

**Issue by p0thi** [Just-Some-Bots/MusicBot#282]
It would be great, if the bot  autopauses after it was autosummoned into an empty channel. It could check if the channel is empty on entry.

Keep up the hard work. It's an awsome bot so far! :)

**Comment by imayhaveborkedit** [comment]
I've been meaning to do that.  #250 does something similar to that but I want to sort this out in a nice clean way.

**Comment by jayktaylor** [comment]
Duplicate of https://github.com/SexualRhinoceros/MusicBot/issues/245.
