### ISSUE TITLE
Help error?

### ISSUE THREAD

**Issue by KarutisL** [Just-Some-Bots/MusicBot#284]
> Traceback (most recent call last):
>   File "run.py", line 202, in <module>
>     main()
>   File "run.py", line 182, in main
>     MusicBot().run()
>   File "C:\Users\karut\Desktop\MusicBot-develop\musicbot\bot.py", line 63, in **init**
>     self.voice_clients = {}
>   File "C:\Users\karut\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 238, in **setattr**
>     return setattr(self.connection, name, value)
> AttributeError: can't set attribute
> Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x01526650>

C:\Users\karut\Desktop\MusicBot-develop>

Don't know what to do.

**Comment by brawaru** [comment]
Look at #265.

> You have downloaded an outdated version of the bot. The current download link is in the tutorial. https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Windows-7-and-up#2a-download-musicbot
