### ISSUE TITLE
Longer tracks skip frequently - can I increase buffer?

### ISSUE THREAD

**Issue by raxitron** [Just-Some-Bots/MusicBot#290]
Longer songs seem to skip a lot but shorter ones are fine. Yes I have a shitty/slow connection.

**Comment by jayktaylor** [comment]
> Longer songs seem to skip a lot but shorter ones are fine.

Not sure what you mean by this...

> Yes I have a shitty/slow connection.

The bot can't run efficiently on bad connections. If you're using a slower connection, you will suffer performance problems using the MusicBot. It downloads music and effectively streams it to Discord. If your download/upload speed is slow, it will struggle to this. It will struggle even more if you're running it off your own PC. Buy a VPS, such as that of Amazon Web Services or DigitalOcean.

**Comment by Forstride** [comment]
I have the bot running off of a DigitalOcean droplet myself, and songs frequently have stutters/speedups for me as well.  My home connection is [perfectly fine](http://www.speedtest.net/result/5382198625.png), my bot is on a US East server, and my Discord server is also US East.

It's pretty annoying having songs stuttering/randomly speeding up.  I have no idea if it's an issue with the bot, Discord, DigitalOcean, or what.

**Comment by sideh** [comment]
Im am having the same problems as @TDWPFTW but instead of digital ocean I am using Amazon Web Service.

**Comment by jayktaylor** [comment]
This isn't caused by the bot and is instead down to a number of possible reasons:
- Internet connection
- Discord's servers
- CPU usage

Host it on a good VPN. You will tend not to have problems. Switch server regions if it helps.
