### ISSUE TITLE
clear a song from the middle of a queue !clear 4

### ISSUE THREAD

**Issue by omerbadawy11** [Just-Some-Bots/MusicBot#292]

**Comment by link2110** [comment]
Planned feature.

**Comment by berkuhlee** [comment]
[remove and undo.zip](https://github.com/SexualRhinoceros/MusicBot/files/288910/remove.and.undo.zip)

This has the command !remove [x] which functions like how you suggested

**Comment by omerbadawy11** [comment]
@berkuhlee i downloaded that and replaced the bot and playlist and the bot wont start, i keep getting an error. got any ideas? :)

**Comment by berkuhlee** [comment]
@omerbadawy11 woops never read this, what's the error? Maybe we have different branches/versions ;_; should have probably sent the whole package

**Comment by jayktaylor** [comment]
#63
