### ISSUE TITLE
Unable to locate package libsodium-dev

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#296]
when trying to install bot on linux server get this ^^^^^^^^error^^^^^^^^^. When starting bot i get RuntimeError: Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib

**Comment by ADetectionAlgorithm** [comment]
Have you installed libsodium-dev?

Update Package List:
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:fkrull/deadsnakes -y
sudo add-apt-repository ppa:mc3man/trusty-media -y
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install build-essential unzip -y

Install Dependencies:
sudo apt-get install git python3.5 python3.5-dev ffmpeg libopus-dev libffi-dev libsodium-dev -y

**Comment by Specro** [comment]
Also try running the bot with super user permissions for the first time:
`sudo python3.5 run.py`

**Comment by bdogrulz** [comment]
https://gist.github.com/jonathanpmartins/2510f38abee1e65c6d92 this worked for me

**Comment by ghost** [comment]
i did all things nothig

**Comment by imayhaveborkedit** [comment]
Those two issues are unrelated.  Sometimes libsodium isn't required to build pynacl, but your problem is you never installed libopus.

**Comment by jayktaylor** [comment]
Resolved.
