### ISSUE TITLE
 FORBIDDEN (status code: 403): Missing permission...

### ISSUE THREAD

**Issue by iMxAndyy** [Just-Some-Bots/MusicBot#297]
When we use any of the commands that respond with a pm we get this error
For example, !pldump
gives this error:

```
Traceback (most recent call last):
  File "C:\Users\andy-\Desktop\Music Bot\Music Bot Official\MusicBot-master\musicbot\bot.py", line 1931, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Users\andy-\Desktop\Music Bot\Music Bot Official\MusicBot-master\musicbot\bot.py", line 1653, in cmd_pldump
    await self.send_file(channel, fcontent, filename='playlist.txt', content="Here's the url dump for <%s>" % song_url)
  File "C:\Users\andy-\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 956, in send_file
    yield from utils._verify_successful_response(response)
  File "C:\Users\andy-\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\utils.py", line 235, in _verify_successful_response
    raise Forbidden(response, message, text)
discord.errors.Forbidden: FORBIDDEN (status code: 403): Missing permission...
```

I don't know enough to properly trouble shoot this myself and i can't find anyone else with this same problem so its probably just me. so apologies if I'm just stupid.

**Comment by imayhaveborkedit** [comment]
Edit: whoops wrong function.  The bot can't upload a file to the channel.

**Comment by iMxAndyy** [comment]
The issue is the same if i use !listroles. It just can't seem to be able to do anything with pms. I tested logging into that account and messaging myself to make sure its not a discord issue and i can message myself from that account on that server so its not that.

**Comment by jaydenkieran** [comment]
Could it perhaps be this Privacy Option enabled?

![Privacy Option](http://i.imgur.com/YjK1exK.png)

**Comment by iMxAndyy** [comment]
read my last comment

**Comment by jayktaylor** [comment]
Ah. Actually it's trying to send a file to the channel. Make sure it has permissions to send files to channel you're using the command in.

**Comment by iMxAndyy** [comment]
Ahh, i see now. 
I assume its not meant to be sending it to channel since it also sends the mailbox_with_mail icon. 
simple fix?

**Comment by imayhaveborkedit** [comment]
It does send the file to the channel. The mailbox response was probably copy pasted from another function, but it doesn't matter.
