### ISSUE TITLE
Bot is online but stop playing the music

### ISSUE THREAD

**Issue by HeavenIsLost** [Just-Some-Bots/MusicBot#298]
The bot still answer our commands to skip, restart, !play etc but the bot look like it have lost the connection and its need a !restart and !summon to get back working again. It even answer its playing the music and the time is passing, but no sound(the bot seens to be not talking anything while when its works OK its "green" like the bot is speaking all the time).

**Comment by jayktaylor** [comment]
This was a known bug that was recently _hopefully_ fixed. Make sure you're using the latest version (`1.9.5`) which is obtainable via the `master` branch or [this release](https://github.com/SexualRhinoceros/MusicBot/releases/tag/1.9.5).

**Comment by EmeliaK** [comment]
It still occurs; the current remedy is a loop that occasionally checks if the websocket is closed (this randomly happening is the cause of the problem); it could stand to be a little more frequent since periods between disconnect and the loop reconnecting can last for more than a minute, though.

**Comment by imayhaveborkedit** [comment]
The check loop runs once a second.  Not sure what's breaking for you lot.

**Comment by EmeliaK** [comment]
I noticed a few days ago in the script that the check ran very frequently. Don't know why it lets the connections lapse for so long still - has it reconnected more instantly for you?

**Comment by HeavenIsLost** [comment]
i believe we will try to merge the current branch, when we do that we will comeback with the answer(if its working or not). thanks :)

**Comment by CaraOnTheRadio** [comment]
He guys is this fixed yet or is there a solution?

**Comment by jayktaylor** [comment]
As of a version or two ago, this should be resolved.

**Comment by lmmfranco** [comment]
Still happening to me. At least once per day.
