### ISSUE TITLE
Bot works on Windows but not Ubuntu

### ISSUE THREAD

**Issue by depthbomb** [Just-Some-Bots/MusicBot#302]
The bot works perfectly fine when I run it on Windows, but it won't log in when I try to run it on my Ubuntu server. The error I get is:

`Connecting...`
`An error has occured:`

 `Problem:  Bot cannot login, bad credentials.`
`Solution: Fix your Email or Password or Token in the options file.  Remember that each field should be on their own line.`

`Unclosed client session`
`client_session: <aiohttp.client.ClientSession object at 0x7f32d29002b0>
`

The credentials on both OS's are the exact same and I've even tried making a new account for Discord and, yet again, the bot on Windows works with it while Ubuntu says the credentials are bad.

The installation on Ubuntu went smoothly albeit I needed to install libsodium-dev from another repo because the package couldn't be found.

**EDIT:** I ended up getting the bot to  work using the OAuth method, but I'm still confused as to why the login method wouldn't work.

**Comment by ImthePeach** [comment]
Did you follow the installation guide for ubuntu properly?
Because it works on my server.

**Comment by henhouse** [comment]
@depthbomb What was wrong? Because I am having the same issue and have no idea why its occurring. Email/pass are correct, on different lines, everything. Keeps failing to authenticate.

**Comment by depthbomb** [comment]
@henhouse It ended up being that I simply didn't check my alternate email, the one the bot used, for the authorization link. It worked on Windows because it is the same machine you created the account on and thus needed no authentication.

If you get this problem just simply check the email associated with the bot. However, the OAuth method is my preferred since it gives the bot a Bot tag by its name.

**Comment by henhouse** [comment]
Ah, that did the trick. Thank you! I did not realize Discord was now requiring IP verification. I feel like the guide should be updated to reflect this since if anyone using Linux is using a server to do so, the bot will not validate and be sending it's verification emails to what ever alternative email you registered the bot with...

Thanks again.
