### ISSUE TITLE
Limit on successive queues from the same user

### ISSUE THREAD

**Issue by tpkelly** [Just-Some-Bots/MusicBot#305]
We had an issue where one user would queue up over an hour of songs and lock down the playlist.

A solution for this I am currently looking at in my own fork is a limit on how many successive songs a user can queue up, and a cooldown timer so that after a certain amount they can queue up another.

E.g. Limit 3, Cooldown: 5

If the user already has 3 songs queued up, they must wait 5 minutes before queuing up another song, or have someone else queue up a song so that they can queue again.

Would this be something other people would want?

**Comment by imayhaveborkedit** [comment]
You can already limit queued songs by users with permissions.  A cooldown seems redundant.

**Comment by tpkelly** [comment]
Ah, I couldn't find the setting for this. My bad!
