### ISSUE TITLE
Can't find my music bot options??

### ISSUE THREAD

**Issue by GoSleep** [Just-Some-Bots/MusicBot#309]
I go into update bot and it has no options here? https://gyazo.com/c715aee58912f987ed0f3fc843ee8156
I try to find it by running the bot and I run it and it continuously does this.
https://gyazo.com/1b028d2658396446476bf81f94d5ebfd
My options still don't appear? can someone help me with this please?

**Comment by dovry** [comment]
backup both example_ files, then remove 'example_' from both filenames.

**Comment by sideh** [comment]
@GoSleep as it says on the intructional Wiki. You need to do the following:

> Configuration
> 
> The main configuration file is config/options.ini, but is not included. Simply make a copy of example_options.ini and rename to options.ini. See example_options.ini for more information on how to configure it.

I am not sure but assume that this is because if they update `example_options.ini` it won't overwrite `options.ini`.

**Comment by jayktaylor** [comment]
**PEBKAC.** Your first issue is that you need to create `options.ini` yourself. Your second issue is that you need to update the bot, then update your dependencies.
