### ISSUE TITLE
Whitelist users with specific role only?

### ISSUE THREAD

**Issue by xaqbr** [Just-Some-Bots/MusicBot#31]
Is it possible for the white list to configure itself where it allows only users with a specific role to use the MusicBot? Thanks!

**Comment by deansheather** [comment]
Functionality for that should come as soon as the permissions system is developed (and we go down the server roles road, not custom roles). You can have a look at the permissions issue at #7.

**Comment by Sveden** [comment]
Would love this feature as well.

**Comment by imayhaveborkedit** [comment]
Permissions.
