### ISSUE TITLE
Music not being able to play another song when a song ends

### ISSUE THREAD

**Issue by flufflyTaco** [Just-Some-Bots/MusicBot#310]
Hi, Recently I have found a bug that when a song ends from the autoplaylist, it is unable to play the next one.
I get something like

```
[Download] Started: https://www.youtube.com/watch?v=zvCBSSwgtg4
[Download] Complete: https://www.youtube.com/watch?v=zvCBSSwgtg4
ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))
[Info] Removing unplayable song from autoplaylist: https://www.youtube.com/watch?v=88XxoddW9iY
ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))
[Info] Removing unplayable song from autoplaylist: https://www.youtube.com/watch?v=5xO0NV8-ICc
ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))
[Info] Removing unplayable song from autoplaylist: https://www.youtube.com/watch?v=KfKIq1Pmc8Q
```

And as soon as i kill the bot, it starts downloading a song, like nothing happened but the bot ends up closing itself. I really do not know what is happening :(

**Comment by bdogrulz** [comment]
what does you playlist look like? this what mine looks like
[autoplaylist.txt](https://github.com/SexualRhinoceros/MusicBot/files/297448/autoplaylist.txt)
i just used the one onslaught gave me after asking nicely
thanks again onslaught for the file

**Comment by flufflyTaco** [comment]
same result...
It plays the first song, then the bot freeze (not replying to command but still playing the song) then when the song ends I get same error

```
Attempting connection...
Connection established.
[Download] Started: http://www.youtube.com/watch?v=IPIoRPtzdG4
[Download] Complete: http://www.youtube.com/watch?v=IPIoRPtzdG4
ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))
[Info] Removing unplayable song from autoplaylist: http://www.youtube.com/watch?v=MsFNDf3fX1A
```

It's not like it's a wrong link either..  It is almost like my connection is being blocked

**Comment by bdogrulz** [comment]
maybe a firewall or something?. try backing up the musicbot files to somewhere else and redownload the files

**Comment by bdogrulz** [comment]
also what are you running the musicbot on windows linux osx?

**Comment by flufflyTaco** [comment]
I doubt it's a firewall thing, as it always download the first song when summoned. I tried re downloading the master branch and still the same. I'm on a linux VPS

**Comment by jayktaylor** [comment]
That error means that there is a problem with your internet/DNS. It can't resolve the website properly and thus throws a fit. This is probably down to your VPS host blocking or limiting outgoing traffic.

Try switching to another VPS or contacting them regarding this issue. The error is thrown by `youtube-dl`. If you still have this issue after switching, feel free to re-open this issue.
