### ISSUE TITLE
what does this mean and is it a problem

### ISSUE THREAD

**Issue by bdogrulz** [Just-Some-Bots/MusicBot#311]
my muscbot plays and works fine but when i look at musicbot console i see this `[s16le @ 0x2b0a380] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
` what does it mean and is it a problem if so how do i fix?

**Comment by imayhaveborkedit** [comment]
Just a message from ffmpeg.  You can ignore it.
