### ISSUE TITLE
Bot crashes at random.

### ISSUE THREAD

**Issue by CaraOnTheRadio** [Just-Some-Bots/MusicBot#314]
He guys i was wondering what to do when this pops up: **http://imgur.com/HNcRTC5** i dont realy know how to put this issue in question format so i hope its ok like this.

**Comment by imayhaveborkedit** [comment]
https://github.com/Twentysix26/Red-DiscordBot

**Comment by CaraOnTheRadio** [comment]
woops man i used the wrong picture :(
http://imgur.com/Rn78tPV

**Comment by imayhaveborkedit** [comment]
I believe this is a bug that happens when the bot reconnects to discord after it gets disconnected.  I'm not sure if this is a lib bug or something I have to fix though, will look into it a bit more.
