### ISSUE TITLE
Bot crashes at random. (I used wrong picture last time mb)

### ISSUE THREAD

**Issue by CaraOnTheRadio** [Just-Some-Bots/MusicBot#315]
He guys i was wondering what to do when this pops up: **http://imgur.com/Rn78tPV** i dont realy know how to put this issue in question format so i hope its ok like this.

**Comment by MagnaMensa** [comment]
http://imgur.com/HNcRTC5

**Comment by imayhaveborkedit** [comment]
Its fine just use the first issue.
