### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by masterworgen** [Just-Some-Bots/MusicBot#319]
Good afternoon, I would like to playlists from Youtube reproduced all, not just one song.
https://www.youtube.com/watch?v=u9Dg-g7t2l4&list=PLhd1HyMTk3f5yqcPXjLo8кроВЖиММФБСк
In this syllke music playlist, but they only play one tune ... I would like to know how to fix it

**Comment by dude22072** [comment]
You're doing it wrong. Read the [FAQ](https://github.com/SexualRhinoceros/MusicBot/wiki/FAQ).

**Comment by imayhaveborkedit** [comment]
Yes, that link is a single video in a playlist, not the playlist itself.  Play the playlist with the playlist url or just the playlist id.
