### ISSUE TITLE
Can't open file run.py

### ISSUE THREAD

**Issue by Corvus48** [Just-Some-Bots/MusicBot#321]
hey, after I install everything and am ready to press runbot.bat, the CMD opens and I get this error:

C:\Users\Admin\AppData\Local\Programs\Python\Python35\python.exe: can't open fil
e 'run.py': [Errno 2] No such file or directory

C:\Users\Admin\AppData\Local\Temp\Temp2_MusicBot-master.zip\MusicBot-master>

**Comment by imayhaveborkedit** [comment]
Consider extracting the bot from the zip and then running it.
