### ISSUE TITLE
Autoplaylist can't play youtube playlists?

### ISSUE THREAD

**Issue by ZweiEuro** [Just-Some-Bots/MusicBot#324]
I want to play a playlist from youtube which i edit with a few friends so we can keep track what's on it and what is missing.
Problem is, the bot doesn't seem to be able to interpret the playlist at all.
Am i doing something wrong ? ( my playlist.txt literally just contains the link to the youtube playlist)

**Comment by imayhaveborkedit** [comment]
No, it doesn't handle playlists yet.  This is what the pldump command is for.

**Comment by ZweiEuro** [comment]
I don't quite know what you mean with that command, but thanks for the information!
--btw thanks for making it !
I'm a huge fan of your bot, pals + me have been using it a lot!

**Comment by pamymaf** [comment]
If you use `!pldump <playlist link>` it will output a .txt file that you can then put into the autoplaylist.txt

**Comment by ghost** [comment]
im so glad u guys put in a !pldump command... the default autoplaylist has some... _interesting_ choices lol.

**Comment by ZweiEuro** [comment]
Where is that playlist output to? for me it seems like the bot doesn't do anything and just straight up ignores the command...
it doesn't seem to change the playlist.txt either

**Comment by link2110** [comment]
@DasVoelkel The pldump command outputs to the channel in a text file. You then have to replace the links in your `autoplaylist.txt` with the ones the bot sends you. 

http://i.imgur.com/arspXwV.png

**Comment by ZweiEuro** [comment]
@link2110 i sent this in the chat of my bot, just like you did ( it doesn't react in the private chat either anyways).
it seems to just ignore the message alltogether
https://imgur.com/Bkm6dyD

Did you use it off the bat without changing any settings?

**Comment by link2110** [comment]
If pldump doesnt work you're using an outdated version. Please update and run `update_deps.bat`

**Comment by ZweiEuro** [comment]
@link2110 well, as soon as i ran the update_deps.bat it won't start anymore 
"No module named 'discord.enums'"   -is the only message it shows now

https://imgur.com/ubINyVl  <<

**Comment by ZweiEuro** [comment]
fixed it, was problem in the requirements! thanks for your help !

**Comment by jayktaylor** [comment]
This issue should be closed as it has been resolved.
