### ISSUE TITLE
Music bot doesn't play autoplaylist anymore

### ISSUE THREAD

**Issue by TheGreatPingu** [Just-Some-Bots/MusicBot#325]
I've tried restarting the bot but it's unable to play the autoplaylist. It does play songs that are added with the !play, however

**Comment by gfrewqpoiu** [comment]
~~I would guess it is a library bug, I yesterday reinstalled the bot (on a new machine, Ubuntu 16.04) and the auto playlist now only works for a few tracks and only after I played a song manually. Could also be a bug in my fork though. Will test with the standard review branch.~~
Edit: Was a bug in my code for me

**Comment by sideh** [comment]
Can you put up what the bug in the code was? I'm currently having the same issue

**Comment by sideh** [comment]
I fount that the issue for me was the HDD filled up and then would not do anything unless !play was used, if you queued things up it would just not play them. I think auto save needs a time limit on keeping files?

**Comment by TheGreatPingu** [comment]
That's not the issue for me. Tried removing all the temp audio files (all 1.4k of them) and the bot remains inactive.
