### ISSUE TITLE
Just not working.

### ISSUE THREAD

**Issue by SaultInc** [Just-Some-Bots/MusicBot#329]
[help.docx](https://github.com/SexualRhinoceros/MusicBot/files/308394/help.docx)
I don't know what to do.

**Comment by link2110** [comment]
You need to update your bot and run `update_deps.bat`

**Comment by ZweiEuro** [comment]
@SaultInc have you give your bot an account? i remember getting this error when i started the bot out of the box without setting one

**Comment by jayktaylor** [comment]
Resolved. Update your bot and then your dependencies.

_p.s please don't ever send a screenshot embedded in a .docx file ever again_
