### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by seraphkz** [Just-Some-Bots/MusicBot#33]
Did everything in the guide, and I get this:

root@default:~/MusicBot-develop# python3 run.py
Python 3.5+ is required. This version is 3.4.3+
Attempting to locate python 3.5...
Python 3 found.  Launching bot...
Killed
root@default:~/MusicBot-develop# sh: 1: b/usr/bin/python3.5\n: not found

**Comment by imayhaveborkedit** [comment]
That's a bug with the restart function.  Try `python3.5 run.py`

**Comment by seraphkz** [comment]
Fixed! Thank you!!

Loving your bot.
