### ISSUE TITLE
[Feature Request] Genre playlists

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#330]
Possible to have each genre, or however a person wants to classify their music, so that one day we could use heavy_metal_playlist.txt and if we are in a country_music.playlist.txt mood the next day.

Maybe have each file just end with a *.playlist extension and we set the name of which playlist in the config or perhaps a command like !playlist <playlist name> and the bot loads it and off it goes.

**Comment by pamymaf** [comment]
This is planned for the future when Bork puts in the playlist management.

**Comment by jayktaylor** [comment]
#43
