### ISSUE TITLE
your help server link is expired

### ISSUE THREAD

**Issue by dude8513** [Just-Some-Bots/MusicBot#331]
I can't find my owner id because the link for the help server is expired

**Comment by ImthePeach** [comment]
the one on the main page? this one?
https://discordapp.com/invite/0iqN3da4zqr6WDdI

**Comment by dude8513** [comment]
I meant the one in the readme. I was unaware there was one on the main page. thank you

**Comment by ImthePeach** [comment]
They are both the same url
https://discordapp.com/invite/0iqN3da4zqr6WDdI

**Comment by imayhaveborkedit** [comment]
Well its fixed now.
