### ISSUE TITLE
Missing permission for !pldump

### ISSUE THREAD

**Issue by ZweiEuro** [Just-Some-Bots/MusicBot#332]
Now that i got the bot registered and working well, i still can't use the !pldump <playlist> command.
well, not it gets recognised but i get a "missing permissions" response.
since i am the owner i donT' expect it to be missing on my part (in the bot options) and i have granted the bots server permissions to send files as well, so i really don't know what i am doing wrong here.

https://imgur.com/RNfGRP4

What permissions does it require where?

**Comment by arunesh90** [comment]
The bot has no permissions to send files

**Comment by ZweiEuro** [comment]
@arunesh90  
it does, it has the group (on discord) "shopkeeper" and thus group is allowed to attach files

--maybe it's something with the new auth system ? i don't quite get behind it..
ok yes it seems to be something with my bots permissions, but i don't understand oauth2 much, i'd need a guide on what the hell to do ...

**Comment by ZweiEuro** [comment]
foundit , it needs admin priveleges to ... send files ? okey sure ,
case closed
