### ISSUE TITLE
Use bot from cmd

### ISSUE THREAD

**Issue by omerbadawy11** [Just-Some-Bots/MusicBot#333]
Hello,
Is it possible to use the bot from the CMD instead of the server to add hidden commands?
Thanks.

**Comment by pamymaf** [comment]
No, it currently only accepts commands from the Discord server.

**Comment by omerbadawy11** [comment]
@KoopaKiy So there is no way at all to change anything in the codeing to make it accept from the bat file?

**Comment by imayhaveborkedit** [comment]
No.
