### ISSUE TITLE
AttributeError?? I Think

### ISSUE THREAD

**Issue by brahkell** [Just-Some-Bots/MusicBot#339]
[New Text Document.txt](https://github.com/SexualRhinoceros/MusicBot/files/311173/New.Text.Document.txt)

**Comment by imayhaveborkedit** [comment]
Update your bot.

**Comment by brahkell** [comment]
i have updated it over 5 times :|

**Comment by imayhaveborkedit** [comment]
`update_deps.bat` does not update the bot.

**Comment by brahkell** [comment]
well then how would i go about "updating" a bot? i have re-downloaded/configured it a couple times and it always seems to come back to this error

**Comment by imayhaveborkedit** [comment]
https://github.com/SexualRhinoceros/MusicBot/releases
