### ISSUE TITLE
Connecting...

### ISSUE THREAD

**Issue by brahkell** [Just-Some-Bots/MusicBot#341]
Updated bot then ran it and it said:

Ok lets hope it worked

Cleaning up... Done.
Restarting in 2 seconds...
Connecting...

And has been stuck on the connecting for 10 minutes. The bot account is already logged into the discord (i did that from the browser) but it just says connecting.

**Comment by imayhaveborkedit** [comment]
That has just been fixed, update your deps again.  Also you don't need to be logged in as the bot in the browser.
