### ISSUE TITLE
Small bits of lag. (Nothing Major)

### ISSUE THREAD

**Issue by brahkell** [Just-Some-Bots/MusicBot#343]
The songs skip for a couple miliseconds every couple seconds or so. Maybe it's normal, just didn't know if there was any way to fix/minimize this. I'm running on approx a 115 Down/15 Up connection.

**Comment by brahkell** [comment]
by the way the songs always say Now playing in Russia: idk if that helps/can be changed closer to where i live

**Comment by sideh** [comment]
I get the same issue man, there is another Issue already up mentioning this in #328 

Put up what server you are using to run the bot and we just have to wait until the devs have free time to address it.

**Comment by ImthePeach** [comment]
If the audio is lagging, it can be down to a number of reasons. You should check each of the following for potential problems and issues.

**CPU/disk usage** - If the CPU/disk usage is high, it can lag out your bot.
**Internet speed/bandwidth** - If your internet isn't too great, it can lag out your bot.
**Discord's servers** - Discord sometimes has problems. Try switching voice server.

**Comment by ImthePeach** [comment]
Also, can you pls provide a better explanation on this:  
`"by the way the songs always say Now playing in Russia"`  
A imgur screenshot would be nice to see as well.

**Comment by jayktaylor** [comment]
Not our problem - lag could be caused by number of reasons.
