### ISSUE TITLE
Can't run the bot

### ISSUE THREAD

**Issue by t9tu** [Just-Some-Bots/MusicBot#347]
![screenshot 331](https://cloud.githubusercontent.com/assets/19936723/16055663/df02a812-328f-11e6-9035-20cd5bb299fd.png)
help pls and I don't know python at all

**Comment by jaw3l** [comment]
Have you updated deps?  (via update_deps.bat)

**Comment by ImthePeach** [comment]
You are probably using a version that the has a part of a broken library, use the `Master` branch rather than the review one then. Remember to update your dependencies afterwards.

**Comment by imayhaveborkedit** [comment]
This appears to be an old version of the bot. See https://github.com/SexualRhinoceros/MusicBot/releases
