### ISSUE TITLE
Don't know what to do

### ISSUE THREAD

**Issue by t9tu** [Just-Some-Bots/MusicBot#348]
![screenshot 331](https://cloud.githubusercontent.com/assets/19936723/16067472/9ad21722-32da-11e6-8855-fd0fc636906e.png)
Help me fix this issue and I really don't know python guide me through it .
Thanks ayways

**Comment by imayhaveborkedit** [comment]
Your issue hasn't changed (#347).  You have an old version of the bot.

**Comment by jayktaylor** [comment]
Resolved, probably worth closing this now.
