### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by t9tu** [Just-Some-Bots/MusicBot#349]
Can anyone tell me how to add whitelist users, do we write like this in the .txt file?
Email :- name@email.com
Password :- password

**Comment by ImthePeach** [comment]
use the permissions file, not the whitelist file, and you just use the user or role ids.

You can get those id's by using the `!listids` command

**Comment by t9tu** [comment]
How to add pause for the bot in CommandWhitelist for other users

**Comment by t9tu** [comment]
Now how do I grant roles to the user like default and musicmaster

**Comment by arunesh90** [comment]
https://github.com/SexualRhinoceros/MusicBot/blob/master/config/example_permissions.ini#L61-L63

**Comment by jayktaylor** [comment]
**PEBKAC.** Should be closed.
