### ISSUE TITLE
after i updated it said active client session restarting

### ISSUE THREAD

**Issue by kingcatdaan** [Just-Some-Bots/MusicBot#351]
im running on ubuntu server (digitalocean) and after i updated i got client session still active restarting in ...
http://imgur.com/Tfs4jZP

**Comment by kingcatdaan** [comment]
before it ran fine

**Comment by imayhaveborkedit** [comment]
Remember to update deps after updating the bot.  `pip3.5 install --upgrade -r requirements.txt`

**Comment by kingcatdaan** [comment]
I did it but now I'm getting a different error I'll post as picture in the morning

**Comment by kingcatdaan** [comment]
http://imgur.com/ais2JrI

**Comment by kingcatdaan** [comment]
leave it im marking this solved i completely reinstalled it and it fixed it

**Comment by kingcatdaan** [comment]
admins mark this a solved since i dont know how to do it

**Comment by kingcatdaan** [comment]
hah
