### ISSUE TITLE
Trouble with perms

### ISSUE THREAD

**Issue by JammyWaffles** [Just-Some-Bots/MusicBot#355]
I'm having trouble setting permissions to roles, I've added roles to the permissions file, but it's still saying people don't have permission to change volume and such
EDIT: Never mind, I've done it
cant figure out how to delete this.

**Comment by Jan200101** [comment]
@JammyWaffles Can you tell me how exactly I set the perms to I can use commands ? I added my ID (137268543874924544) to UserList at [MusicMaster] but it wont work
