### ISSUE TITLE
Ask: Step By Step Video for the new method

### ISSUE THREAD

**Issue by LiderKonmils** [Just-Some-Bots/MusicBot#356]
Hi,
With the new method to install the bot, i'm completely lost. Can someone do a video step by step to install it? 

(before someone ask, i don't know where the GIT command [git clone https://github.com/SexualRhinoceros/MusicBot.git MusicBot -b master] place the folder)

**Comment by jayktaylor** [comment]
**PEBKAC.** The guides should be easy to follow if you read them and follow them step by step. Videos usually become outdated over time and are a pain in the ass to update compared to a text guide.
