### ISSUE TITLE
Unrecognized option 'nostdin'

### ISSUE THREAD

**Issue by mikemassari** [Just-Some-Bots/MusicBot#358]
Hello. My installation went smoothly but when I try to play a song I get this message

```
[Download] Cached: https://www.youtube.com/watch?v=tg00YEETFzg
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
Unrecognized option 'nostdin'
```

and in the discord channel the bot doesn't do anything and no sound is heard.

May you please help? I'm running the bot on Ubuntu 12.04

**Comment by TheTitor** [comment]
I had the same problem, but am on debian. It was because apt-get was automatically installing an older version of ffmpeg. I had to add a third party built source here: http://www.deb-multimedia.org/ then select the newest version for ffmpeg and it fixed my problem, so you would have to do the analog of that on ubuntu probably.

**Comment by imayhaveborkedit** [comment]
That message is from avconv, not ffmpeg.  I have to figure out if I can use avconv with similar options but for now you need to use ffmpeg.

**Comment by script-head** [comment]
Having the same issue the vps is running CentOS 6 I hope you can figure out if you can use avconv or not

**Comment by AlDfriD** [comment]
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
Unrecognized option 'nostdin'

**Comment by imayhaveborkedit** [comment]
Good news.  I have figured out if avconv (libav) can be used or not.  The answer is **no**.  The version on my crunchbang VM is not able to play webms, which is what a majority of youtube videos are.  Good to know that nothing needs to be changed and ffmpeg is still required.
