### ISSUE TITLE
Music bot wont run even with new installation and setup

### ISSUE THREAD

**Issue by Tecseven7** [Just-Some-Bots/MusicBot#359]
Idk what it is but here is a screen shot of the runbot.bat https://puu.sh/pwCTl/e8f055a841.png

**Comment by designategold7** [comment]
update your dependencies

**Comment by Tecseven7** [comment]
@voqz how might i go about doing that?

**Comment by Tecseven7** [comment]
@voqz nvm, I just did it. It said i was on pip 7.1.2 and i need 8.1.2. It says to update via 'python -m pip install --upgrade pip' command, but i dont know where to use that command

**Comment by Kode103** [comment]
My friend and I have the same issue. I updated Python hoping that would solve the issue but it didn't.

**Comment by NotSoSuper** [comment]
@Tecseven7 Try to update discord.py with command "pip3.5 install --upgrade git+https://github.com/Rapptz/discord.py@async"

**Comment by Tecseven7** [comment]
@NotSoSuper where do i enter that command? I tried git bash and the update.bats command prompt.

**Comment by Kode103** [comment]
I was able to fix it. What I did was uninstalled Python and Python launcher, then reinstall it (3.5.1). Finally, I redownloaded MusicBot, edited the Options/Permissions files and was able to launch it without issues. 
NOTE: I use Iobit Uninstaller to uninstall any software from my computer, as it can force delete any files left over that weren't deleted from a normal uninstall.
