### ISSUE TITLE
Redownloaded bot and now it keeps on crashing :S

### ISSUE THREAD

**Issue by vladerie** [Just-Some-Bots/MusicBot#363]
Dear sir/madame

First of all thanks for this awesome bot! I have been using it for quite a while now but it broke down :( This is what happend: Like I said I have used the bot before so it worked perfectly for me. But for some reason it just stopped playing music while still being online and which point I needed to restard the bot. Because of this I looked around on the internet and found out that it would be solved if I updated the bot which I did afterwards. This was a big hassle since I downloaded the bot before the use of github and the bot feature from discord themselves. I re did everything following the instructions but it doesn't work for some reason. Me and a friend also have some experience with coding so we tried to solve it ourselves. But at the moment we have no clue what we should do. if I open the Runbot.bet it gives me this message:

No module named 'discord'
Attempting to install dependencies...
Collecting https://github.com/Rapptz/discord.py/archive/async.zip (from -r requirements.txt (line 1))
  Downloading https://github.com/Rapptz/discord.py/archive/async.zip (452kB)
    100% |████████████████████████████████| 454kB 747kB/s 
Requirement already up-to-date: youtube-dl>=2016.4.24 in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: aiohttp<0.22.0,>=0.21.0 in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from discord.py==0.10.0a0->-r requirements.txt (line 1))
Requirement already up-to-date: websockets==3.1 in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from discord.py==0.10.0a0->-r requirements.txt (line 1))
Collecting PyNaCl==1.0.1 (from discord.py==0.10.0a0->-r requirements.txt (line 1))
  Using cached PyNaCl-1.0.1-cp35-none-win_amd64.whl
Requirement already up-to-date: chardet in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<0.22.0,>=0.21.0->discord.py==0.10.0a0->-r requirements.txt (line 1))
Requirement already up-to-date: six in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from PyNaCl==1.0.1->discord.py==0.10.0a0->-r requirements.txt (line 1))
Collecting cffi>=1.1.0 (from PyNaCl==1.0.1->discord.py==0.10.0a0->-r requirements.txt (line 1))
  Using cached cffi-1.7.0.tar.gz
Requirement already up-to-date: pycparser in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from cffi>=1.1.0->PyNaCl==1.0.1->discord.py==0.10.0a0->-r requirements.txt (line 1))
Installing collected packages: cffi, PyNaCl, discord.py
  Running setup.py install for cffi
    Complete output from command C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\python.exe -c "import setuptools, tokenize;**file**='C:\Users\GEBRUI~1\AppData\Local\Temp\pip-build-m2i9t0pj\cffi\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record C:\Users\GEBRUI~1\AppData\Local\Temp\pip-kskxlr9f-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\cffi
    copying cffi\api.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\backend_ctypes.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\cffi_opcode.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\commontypes.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\cparser.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\ffiplatform.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\lock.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\model.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\recompiler.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\setuptools_ext.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\vengine_cpy.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\vengine_gen.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\verifier.py -> build\lib.win-amd64-3.5\cffi
    copying cffi__init__.py -> build\lib.win-amd64-3.5\cffi
    copying cffi_cffi_include.h -> build\lib.win-amd64-3.5\cffi
    copying cffi\parse_c_type.h -> build\lib.win-amd64-3.5\cffi
    copying cffi_embedding.h -> build\lib.win-amd64-3.5\cffi
    running build_ext
    building '_cffi_backend' extension
    error: Unable to find vcvarsall.bat

```
----------------------------------------
```

Command "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\python.exe -c "import setuptools, tokenize;**file**='C:\Users\GEBRUI~1\AppData\Local\Temp\pip-build-m2i9t0pj\cffi\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record C:\Users\GEBRUI~1\AppData\Local\Temp\pip-kskxlr9f-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\GEBRUI~1\AppData\Local\Temp\pip-build-m2i9t0pj\cffi
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

You may need to run as admin to install dependencies.

I have no clue what to do at this point and really want the bot back because it is awesome! Thanks for reading this and hopefully get a responce soon ^^

Yours sincerly,
Valerie

**Comment by imayhaveborkedit** [comment]
Try running it again.  I'm assuming this happened a little while ago.  One of the dependencies was updated and the precompiled windows binaries probably weren't uploaded when you tried it.

**Comment by vladerie** [comment]
I ran the runbot.bat again and got the same message :S

**Comment by imayhaveborkedit** [comment]
If you open cmd and type `pip install cffi` does it print the same message?:

**Comment by vladerie** [comment]
yeas it does

**Comment by imayhaveborkedit** [comment]
In that case run `pip install cffi==1.6.0`

**Comment by vladerie** [comment]
C:\Users\Gebruiker>pip install cffi==1.6.0
Collecting cffi==1.6.0
  Downloading cffi-1.6.0-cp35-none-win_amd64.whl (156kB)
    100% |################################| 159kB 1.3MB/s
Requirement already satisfied (use --upgrade to upgrade): pycparser in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from cffi==1.6.0)
Installing collected packages: cffi
Successfully installed cffi-1.6.0
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

I recieved this message after using that code

**Comment by imayhaveborkedit** [comment]
Now running the bot should work.

**Comment by vladerie** [comment]
No module named 'discord'
Attempting to install dependencies...
Collecting https://github.com/Rapptz/discord.py/archive/async.zip (from -r requirements.txt (line 1))
  Downloading https://github.com/Rapptz/discord.py/archive/async.zip (452kB)
    100% |████████████████████████████████| 454kB 651kB/s 
Requirement already up-to-date: youtube-dl>=2016.4.24 in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: aiohttp<0.22.0,>=0.21.0 in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from discord.py==0.10.0a0->-r requirements.txt (line 1))
Requirement already up-to-date: websockets==3.1 in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from discord.py==0.10.0a0->-r requirements.txt (line 1))
Collecting PyNaCl==1.0.1 (from discord.py==0.10.0a0->-r requirements.txt (line 1))
  Using cached PyNaCl-1.0.1-cp35-none-win_amd64.whl
Requirement already up-to-date: chardet in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<0.22.0,>=0.21.0->discord.py==0.10.0a0->-r requirements.txt (line 1))
Requirement already up-to-date: six in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from PyNaCl==1.0.1->discord.py==0.10.0a0->-r requirements.txt (line 1))
Collecting cffi>=1.1.0 (from PyNaCl==1.0.1->discord.py==0.10.0a0->-r requirements.txt (line 1))
  Using cached cffi-1.7.0.tar.gz
Requirement already up-to-date: pycparser in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from cffi>=1.1.0->PyNaCl==1.0.1->discord.py==0.10.0a0->-r requirements.txt (line 1))
Installing collected packages: cffi, PyNaCl, discord.py
  Found existing installation: cffi 1.6.0
    Uninstalling cffi-1.6.0:
      Successfully uninstalled cffi-1.6.0
  Running setup.py install for cffi
    Complete output from command C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\python.exe -c "import setuptools, tokenize;**file**='C:\Users\GEBRUI~1\AppData\Local\Temp\pip-build-g_7rarsl\cffi\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record C:\Users\GEBRUI~1\AppData\Local\Temp\pip-hz9tuhgz-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\cffi
    copying cffi\api.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\backend_ctypes.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\cffi_opcode.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\commontypes.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\cparser.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\ffiplatform.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\lock.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\model.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\recompiler.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\setuptools_ext.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\vengine_cpy.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\vengine_gen.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\verifier.py -> build\lib.win-amd64-3.5\cffi
    copying cffi__init__.py -> build\lib.win-amd64-3.5\cffi
    copying cffi_cffi_include.h -> build\lib.win-amd64-3.5\cffi
    copying cffi\parse_c_type.h -> build\lib.win-amd64-3.5\cffi
    copying cffi_embedding.h -> build\lib.win-amd64-3.5\cffi
    running build_ext
    building '_cffi_backend' extension
    error: Unable to find vcvarsall.bat

```
----------------------------------------
```

  Rolling back uninstall of cffi
Command "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python35\python.exe -c "import setuptools, tokenize;**file**='C:\Users\GEBRUI~1\AppData\Local\Temp\pip-build-g_7rarsl\cffi\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record C:\Users\GEBRUI~1\AppData\Local\Temp\pip-hz9tuhgz-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\GEBRUI~1\AppData\Local\Temp\pip-build-g_7rarsl\cffi
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

You may need to run as admin to install dependencies.

C:\Users\Gebruiker\Desktop\MusicBot>

Still doesn't work :s

**Comment by imayhaveborkedit** [comment]
Ok, it seems to want to use the source version it has cached.  If you put the line `cffi==1.6.0` in requirements.txt, it should use that version.  After that run it again.

```
cffi == 1.6.0
https://github.com/Rapptz/discord.py/archive/async.zip
youtube_dl >= 2016.4.24
```

**Comment by vladerie** [comment]
Now I recieved this message:
No module named 'discord'
Attempting to install dependencies...
Collecting https://github.com/Rapptz/discord.py/archive/async.zip (from -r requirements.txt (line 2))
  Downloading https://github.com/Rapptz/discord.py/archive/async.zip (452kB)
    100% |████████████████████████████████| 454kB 268kB/s 
Requirement already up-to-date: cffi==1.6.0 in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: youtube-dl>=2016.4.24 in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: aiohttp<0.22.0,>=0.21.0 in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from discord.py==0.10.0a0->-r requirements.txt (line 2))
Requirement already up-to-date: websockets==3.1 in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from discord.py==0.10.0a0->-r requirements.txt (line 2))
Collecting PyNaCl==1.0.1 (from discord.py==0.10.0a0->-r requirements.txt (line 2))
  Using cached PyNaCl-1.0.1-cp35-none-win_amd64.whl
Requirement already up-to-date: pycparser in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from cffi==1.6.0->-r requirements.txt (line 1))
Requirement already up-to-date: chardet in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<0.22.0,>=0.21.0->discord.py==0.10.0a0->-r requirements.txt (line 2))
Requirement already up-to-date: six in c:\users\gebruiker\appdata\local\programs\python\python35\lib\site-packages (from PyNaCl==1.0.1->discord.py==0.10.0a0->-r requirements.txt (line 2))
Installing collected packages: PyNaCl, discord.py
  Running setup.py install for discord.py
Successfully installed PyNaCl-1.0.1 discord.py-0.10.0a0
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Ok lets hope it worked

Cleaning up... Done.
Restarting in 2 seconds...

An error has occured reading the config:

  Problem:  OwnerID was not set.  
  Solution: Please set the OwnerID in the config.  If you don't know what that is, use the !id command                  

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000291B358ADA0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000291B6FABE10>

C:\Users\Gebruiker\Desktop\MusicBot>

**Comment by imayhaveborkedit** [comment]
Ok there you go, it installed.  Now set up your config and you're good to go.
