### ISSUE TITLE
Bot doesn't add some videos

### ISSUE THREAD

**Issue by TheDramaMan** [Just-Some-Bots/MusicBot#367]
```
[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 997, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 912, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 975, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'ur'
 (caused by ExtractorError("Could not find JS function 'ur'",))
```

This is the error that bot returns if some of this tracks (or many others) are proposed by users using !play command:
https://www.youtube.com/watch?v=43sJ__i6iSs
https://www.youtube.com/watch?v=DEaMKXqZj4I
https://www.youtube.com/watch?v=KDcgOpUp2nc
(_and other_)

I got this error obly since today, like other users, who leaved comments here.

**Comment by marijnv2000** [comment]
> [0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
>     video_id, player_url, s
>   File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
>     res = self._parse_sig_js(code)
>   File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
>     initial_function = jsi.extract_function(funcname)
>   File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
>     raise ExtractorError('Could not find JS function %r' % funcname)
> youtube_dl.utils.ExtractorError: Could not find JS function 'ur'
>  (caused by ExtractorError("Could not find JS function 'ur'",))

I don't know how to properly format it like @TheDramaMan did so I quoted, since it leaves the text as intact as I could get it

Get the same problem, only since today, yesterday my bots were working fine.
Also when using the search youtube function, I get the same error.

**Comment by arunesh90** [comment]
Update your dependencies with update_deps.bat 
If you're on linux:
pip install --upgrade -r requirements.txt

**Comment by marijnv2000** [comment]
I guess that worked, but now once I start the bot using `python3.5 run.py` I get this:

Warning: Autoplaylist is empty, disabling.
Traceback (most recent call last):
  File "run.py", line 163, in main
    m = MusicBot()
  File "/home/vogelxpsycho/Desktop/MusicBots/Music Bot/musicbot/bot.py", line 90, in init
    self.headers['user-agent'] += ' MusicBot/%s' % BOTVERSION
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 254, in getattr
    raise AttributeError(msg.format(self.class, name))
AttributeError: '<class 'musicbot.bot.MusicBot'>' object has no attribute 'headers'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f23bd653cf8>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f23bd653be0>
Cleaning up... Done.
Restarting in 12 seconds...

This repeats itself, waiting longer to restart everytime (Restarting in 2 seconds, Restarting in 4 seconds, etc..)

**Comment by The-MAD-Virus** [comment]
``` sh
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 997, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 912, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 975, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'ur'
 (caused by ExtractorError("Could not find JS function 'ur'",))
```

Same error here.
i also run `pip install --upgrade -r requirements.txt`
and it doesn't change any thing.

Edit : 
in fact you need to clear all MusicBot  **pycache**
Now it work again !

**Comment by marijnv2000** [comment]
I downloaded the bot again, copied my old config file into the new one, and everything works fine. Is there anyway to just update the Cloned directory from the command line instead of making new folders, cloning, copying config file, autoplaylist and permissions, deleting the old MusicBots? I'm fairly new to github and cloning so this may sound stupid to some of you :p

**Comment by jayktaylor** [comment]
@VogelxPsycho You can run the command `git pull` inside of your MusicBot's directory using the command line to update with the latest changes, as long as you cloned the `master` branch :+1:

**Comment by k-egor-smirnov** [comment]
Try to run with sudo

**Comment by marijnv2000** [comment]
I did this:

> Update your dependencies with update_deps.bat 
> If you're on linux:
> pip install --upgrade -r requirements.txt

Thanks @arunesh90 
and:

> You can run the command git pull inside of your MusicBot's directory using the command line to update with the latest changes, as long as you cloned the master branch.

Thanks @jaydenkieran 

@The-MAD-Virus 

> in fact you need to clear all MusicBot pycache
> Now it work again !

Haven't tried it, since my bot is working now :)

**Comment by Heavywavez** [comment]
@VogelxPsycho  where did you clean MusicBot pycache?

**Comment by marijnv2000** [comment]
@Heavywavez I didn't, I said I haven't tried it, because my bot is already working. I got it to work by first updating the deps:

> Update your dependencies with update_deps.bat 
> If you're on linux:
> pip install --upgrade -r requirements.txt

and after that update the bot itself:

> You can run the command git pull inside of your MusicBot's directory using the command line to update with the latest changes, as long as you cloned the master branch.

The git pull command will only work if you have git installed on your computer, and if you cloned the master branch. If you installed the musicbot by downloading the zip file, then download the latest version now, extract it, and copy the config folder from your old bot to your new bot and you should be good to go!

**Comment by jayktaylor** [comment]
**Resolved.** Fixed by updating your dependencies.
