### ISSUE TITLE
Only accept commands from people in the channel

### ISSUE THREAD

**Issue by iMxAndyy** [Just-Some-Bots/MusicBot#37]
It would make sense for the bot to ignore commands from people that aren't in the same channel as itself. 
To stop people trolling those listening to the music. (or at least make it harder)

**Comment by deansheather** [comment]
+1 :+1:

**Comment by Chew** [comment]
+1 Yes please!

**Comment by imayhaveborkedit** [comment]
This would be the `ignorenonvoice` permissions option.
