### ISSUE TITLE
Bot is offline all the time

### ISSUE THREAD

**Issue by MrTaco4ewa** [Just-Some-Bots/MusicBot#373]
Hi i just watched a video followed all the instrutions and still my bot is not working first it doesnt find me in a channel later it doesnt auto join to a channel even though i have set it up to do so.
Please help me i dont know what i did wrong...

**Comment by rome1245** [comment]
What does your options ini file look like?

**Comment by MrTaco4ewa** [comment]
Ehm i only need to remove the email and pass to safely send it right??

**Comment by MrTaco4ewa** [comment]
oki it was nothing i did something and it worked
