### ISSUE TITLE
download?

### ISSUE THREAD

**Issue by Benjoi4231** [Just-Some-Bots/MusicBot#375]
Where can i redownload music bot? i had to delete because of error downloading youtube videos

**Comment by arunesh90** [comment]
https://github.com/SexualRhinoceros/MusicBot/wiki

**Comment by jayktaylor** [comment]
**PEBKAC.** Guy too lazy to read wiki guides > guy posts issue > guy gets directed to wiki guides

**Comment by AlDfriD** [comment]
That error is common because ffmpeg its being unable on ubuntu servers and so theres no solution yet.

**Comment by arunesh90** [comment]
wat
