### ISSUE TITLE
A fatal error.

### ISSUE THREAD

**Issue by CaraOnTheRadio** [Just-Some-Bots/MusicBot#376]
Hi guys,

I can summon my bot in my channel but when i try to use the: play command i get this instead.

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\TooRichTooFamous\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\TooRichTooFamous\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\TooRichTooFamous\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "C:\Users\TooRichTooFamous\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'ur'
 (caused by ExtractorError("Could not find JS function 'ur'",))

What can i do?

**Comment by arunesh90** [comment]
![image](https://cloud.githubusercontent.com/assets/5787588/16335828/268f317a-3a09-11e6-82e7-df71afd83998.png)

**Comment by CaraOnTheRadio** [comment]
he man after the update i went and started the bot again, it started doing all sorts of things but now it stuck on: restarting in 38 sec and it keeps climbing 40sec 42sec what do i do now?

**Comment by arunesh90** [comment]
more info would be gr8

**Comment by CaraOnTheRadio** [comment]
hmm i went and did the following: like i have been told i used update_deps.bat and then i followed to use runbot.bat while running runbot.bat it seemed to do a lot installing a few files and deleting a few others, then it said its gonna restart but its not doing this.

**Comment by CaraOnTheRadio** [comment]
![image](https://cloud.githubusercontent.com/assets/19749390/16336974/329e605e-3a12-11e6-9e1a-b442acc2fdb4.png)

**Comment by CaraOnTheRadio** [comment]
as you can see it keeps repeating the same action and then tels me its restarting in ... seconds...

**Comment by arunesh90** [comment]
You're using a old version.

**Comment by CaraOnTheRadio** [comment]
a i see thx i got it running again.

**Comment by Tyty717** [comment]
I'm having this Same problem and cant seem to find a fix
I updated and am having the Restart problem

**Comment by CaraOnTheRadio** [comment]
Well @Tyty717 what i did was i downloaded the bot again completly new and fresh. And then i coppied the config file in to the new installed music bot, and then it worked. Be sure to delete your old bot after to make sure you are cant be confused (like me :) ) hope it works!.

**Comment by CaraOnTheRadio** [comment]
And by the config file i mean your old bot's config file

**Comment by jayktaylor** [comment]
**Resolved.** Update your bot, then update your dependencies.
