### ISSUE TITLE
No songs were added - playlist

### ISSUE THREAD

**Issue by IceRaider** [Just-Some-Bots/MusicBot#377]
I'm trying to add a playlist from YouTube with plenty of songs but I get the error message
"No songs were added, all songs were over max duration (0s)"

What is causing this?

**Comment by jaydenkieran** [comment]
**Resolved.** This issue was fixed in version `1.9.5_2`. Update your bot, then your dependencies.

**Comment by ArgonQQ** [comment]
Maybe you've got a permission conflict. Set yourself as a radio master in the options.ini file.

**Comment by jayktaylor** [comment]
If you're still having this problem, feel free to re-open this issue.
