### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by xaqbr** [Just-Some-Bots/MusicBot#38]
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 87, in run
    self.player(data)
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 572, in play_audio
    sent = self.socket.sendto(packet, (self.endpoint_ip, self.voice_port))
PermissionError: [Errno 1] Operation not permitted

I get this error when the bot tries to play music in the vc.

**Comment by deansheather** [comment]
@Tomiaz I believe this means that the bot doesn't have voice permissions for the specified channel. Make a server rank called "Bot" and give it all permissions for text and voice channels (it doesn't exactly need all permissions for text and voice, but it's easier than going into specifics + updates get released with new features constantly and a new feature might require new permissions).

**Comment by xaqbr** [comment]
@deansheather I've given the bot a role with complete access to the server, but it still happens. It doesn't happen all the time, it happens arbitrarily.

**Comment by deansheather** [comment]
According to imayhaveborkedit, this is a `discord.py` bug and will be fixed soon. Hang in there.

**Comment by xaqbr** [comment]
~~I think I may have found something that appears to be related to the error.
The error occurs when I use Youtube links that are in playlists (e.g.: https://www.youtube.com/watch?v=awimSQD2Dyo&list=RDawimSQD2Dyo)~~

~~Regular ones work (e.g.: https://www.youtube.com/watch?v=awimSQD2Dyo)~~

EDIT: Nevermind, the error still remains arbitrary

**Comment by imayhaveborkedit** [comment]
I'm actually not sure what this is.  @deansheather may have mixed this up with another issue with the same trace, but a different error message.  I need to know more about what triggers this.

**Comment by imayhaveborkedit** [comment]
According to danny and spoopy, this is not a bot issue, but a user issue.  The bot is unable to send udp packets for some reason, such as running another bot connected to voice, or something holding the port.  I don't know how to deal with this but evidently it's not my job to fix.

**Comment by imayhaveborkedit** [comment]
It's likely that this is being caused by your firewall.  Check that and close this if that was the case.

**Comment by imayhaveborkedit** [comment]
Closing stale issue; if it happens again, reopen it.

**Comment by DoNotSpamPls** [comment]
_opens issue_
I have this problem too. I use Cloud9 to host the bot.

**Comment by itslukej** [comment]
^ same here

**Comment by imayhaveborkedit** [comment]
Cloud9 blocks UDP.  Get a real VPS.
