### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by danielen91** [Just-Some-Bots/MusicBot#381]
Hello. I can see the Bot on the server 
![image](https://cloud.githubusercontent.com/assets/19835479/16357099/3c02792e-3aed-11e6-9213-2e10213d3aa5.png)
but i cant make it join any rooms. When i press "runbot.bat" i get this window:

![image](https://cloud.githubusercontent.com/assets/19835479/16357102/690186ea-3aed-11e6-89a0-82fba99ef597.png)

Lots of things that makes no sense to me.

**Comment by arunesh90** [comment]
To resolve this issue, put the following on a new line in your requirements.txt file: cffi==1.6.0

**Comment by jayktaylor** [comment]
**Resolved.** This is fixed in version `1.9.5_2`. Update your bot, then update your dependencies.
