### ISSUE TITLE
Could not load an opus lib

### ISSUE THREAD

**Issue by TwoPieee** [Just-Some-Bots/MusicBot#382]
Downloaded the bot, changed the options and permissions accordingly, and started runbot.bat.
Does this error mean I need to redownload node-opus?  Where would I place it?
My apologies-I don't have that much experience with these things.
[Screenshot](https://i.gyazo.com/8c3c9d04a90356d3243095ef2e8907c2.png)
It restarts indefinitely

Thanks in advance ^^

**Comment by mxwha0** [comment]
Also getting this error, older build of the bot is working fine but i cannot get the new build to work at all.

**Comment by mxwha0** [comment]
managed to fix this by running update_deps.bat and then running the main file as usual.

**Comment by TwoPieee** [comment]
This worked, thanks!
