### ISSUE TITLE
Bug: not cleaning certain messages

### ISSUE THREAD

**Issue by grizzogor** [Just-Some-Bots/MusicBot#385]
So, I wanted to clear all of the messages of a chat room but whenever I do //clean (or !clean), it doesn't delete certain messages (like with symbols) and sometimes, it won't even delete normal messages.

**Comment by Dradonis** [comment]
> **# !clean <amount>**
> Search through amount of messages and **_remove any sent by the bot_**. If the bot has Manage Messages permission in the channel, _**the bot will also remove message that invoked bot commands**_ (messages that were commands for the bot, !play, !np, etc).
> 
> Note: amount is not how many messages to remove, it's how many messages to search through to remove.

So basically it's not supposed to clear all messages.

**Comment by grizzogor** [comment]
Oh, I never knew that.
