### ISSUE TITLE
Failed loading Voice_Client.py

### ISSUE THREAD

**Issue by St3amer** [Just-Some-Bots/MusicBot#388]
Please help fix this issue I have tried updating the dep and also have latest version of bot I also reinstalled GIT and Python they both are working correctly :/ here's a screenshot to my error: https://gyazo.com/52f4e827cd991448fc4e517accef0efb

**Comment by matthelm18** [comment]
I got the same issue.

**Comment by jayktaylor** [comment]
**Resolved.** This is fixed in version `1.9.5_2`. Update your bot, then update your dependencies.
