### ISSUE TITLE
"The bot is not in a voice channel.  Use !summon to summon it to your voice channel." Error?

### ISSUE THREAD

**Issue by Impactz99** [Just-Some-Bots/MusicBot#389]
Hey Guys!

When I try 2 play some songs I always get the same Error:
"The bot is not in a voice channel.  Use !summon to summon it to your voice channel."
Console: http://prntscr.com/bm6p2o

And when I start the bot I get this Error:
http://prntscr.com/bm6ofy

I ran update_deps.bat but it didnt help me 

Can anyone help me?

Greetz 
Jonas

**Comment by Impactz99** [comment]
Fixed it for me: Replace the first line in requirements.txt with: discord.py[voice]

Greetz
Jonas

**Comment by Richiachu** [comment]
That didn't seem to fix it for me, I appear to still be getting the same error. Any specific line or dialogue you changed?

**Comment by Impactz99** [comment]
Hmmm...when you open your requirements.txt you will have at ur first line a github link. Change this with discord.py[voice]

http://prntscr.com/bm97wv

**Comment by Richiachu** [comment]
Didn't seem to work at all, shame. I'll keep trying other things.

Fixed: Add this line to the bottom of the requirements file: cffi==1.6.0

**Comment by Impactz99** [comment]
Did u run "update_deps.bat" after it?

**Comment by jayktaylor** [comment]
**Resolved.** This is fixed in version `1.9.5_2`. Update your bot, then update your dependencies.
