### ISSUE TITLE
Auto play error when video not available in your country

### ISSUE THREAD

**Issue by iMxAndyy** [Just-Some-Bots/MusicBot#39]
When the bot is playing through the backup list of music when the queue is empty, If the video it tries to play is not available in my country it can't play it and it stops playing music untill its restarted or someone adds something new to the queue. 
would be nice to have an exception for when the video is not available in your country for it to skip it and play the next song

**Comment by imayhaveborkedit** [comment]
Yep, probably because it doesn't check if the video data is available before trying to queue it.  Added to my todo list.
