### ISSUE TITLE
Error Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by ZachariLJohn** [Just-Some-Bots/MusicBot#398]
There was an error after I followed all the steps and it said "error: Unable to find vcvarsall.bat"

No module named 'discord'
Attempting to install dependencies...
Collecting discord.py[voice](from -r requirements.txt %28line 1%29)
  Using cached discord.py-0.10.0.zip
Collecting youtube-dl (from -r requirements.txt (line 2))
  Using cached youtube_dl-2016.6.27-py2.py3-none-any.whl
Collecting pip (from -r requirements.txt (line 3))
  Using cached pip-8.1.2-py2.py3-none-any.whl
Collecting cffi (from -r requirements.txt (line 4))
  Using cached cffi-1.7.0.tar.gz
Requirement already up-to-date: aiohttp<0.22.0,>=0.21.0 in c:\users\yukio daichi\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]->-r requirements.txt (line 1))
Requirement already up-to-date: websockets==3.1 in c:\users\yukio daichi\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]->-r requirements.txt (line 1))
Collecting PyNaCl==1.0.1 (from discord.py[voice]->-r requirements.txt (line 1))
  Using cached PyNaCl-1.0.1-cp35-none-win_amd64.whl
Requirement already up-to-date: pycparser in c:\users\yukio daichi\appdata\local\programs\python\python35\lib\site-packages (from cffi->-r requirements.txt (line 4))
Requirement already up-to-date: chardet in c:\users\yukio daichi\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<0.22.0,>=0.21.0->discord.py[voice]->-r requirements.txt (line 1))
Requirement already up-to-date: six in c:\users\yukio daichi\appdata\local\programs\python\python35\lib\site-packages (from PyNaCl==1.0.1->discord.py[voice]->-r requirements.txt (line 1))
Installing collected packages: cffi, PyNaCl, discord.py, youtube-dl, pip
  Running setup.py install for cffi
    Complete output from command "C:\Users\Yukio Daichi\AppData\Local\Programs\Python\Python35\python.exe" -c "import setuptools, tokenize;**file**='C:\Users\YUKIOD~1\AppData\Local\Temp\pip-build-6aejc4jb\cffi\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record C:\Users\YUKIOD~1\AppData\Local\Temp\pip-5dr9fclh-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\cffi
    copying cffi\api.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\backend_ctypes.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\cffi_opcode.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\commontypes.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\cparser.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\ffiplatform.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\lock.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\model.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\recompiler.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\setuptools_ext.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\vengine_cpy.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\vengine_gen.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\verifier.py -> build\lib.win-amd64-3.5\cffi
    copying cffi__init__.py -> build\lib.win-amd64-3.5\cffi
    copying cffi_cffi_include.h -> build\lib.win-amd64-3.5\cffi
    copying cffi\parse_c_type.h -> build\lib.win-amd64-3.5\cffi
    copying cffi_embedding.h -> build\lib.win-amd64-3.5\cffi
    running build_ext
    building '_cffi_backend' extension
    error: Unable to find vcvarsall.bat

**Comment by ZachariLJohn** [comment]
solved

**Comment by ghost** [comment]
Why do people keep closing these without providing a solution. Oh well, I'll keep on looking around.

**Comment by jayktaylor** [comment]
@DatapawWolf If you're still having this issue try updating pip using `pip install --upgrade pip`
