### ISSUE TITLE
Docker wiki fix

### ISSUE THREAD

**Issue by jseed** [Just-Some-Bots/MusicBot#399]
I am in the process of updating the wiki for the Docker installation/deployment and thought I would create an issue to discuss the current issues, since there seems to be no 'pull requests' for wiki changes.  

Currently, the guide instructs users to pull the container from Dockerhub, and not to build it themselves.  The current 'maintainer' set up this container as an automatic build from his own fork of the repository.  This meant that any time there was changes to this repository, he would have to resync his fork in order for the changes to be deployed to the container.   The issue is that at some point, he stopped syncing the fork, leaving the container outdated and broken.  

The container was created from a forked repository because you can only set up automated builds on Dockerhub for your own repositories, or repositories for an organization that you belong too.  ( You may also be able to set it up for repositories you have access too, not sure on this one)

To resolve this, I will update the wiki to instruct users on how to build the image themselves.  
If someone involved with the project wishes to set up an automated build for the main repo, I would be happy to provide instruction, or set it up myself (if given the permissions), just let me know.  

I will close this issue after a week or two, or once someone involved with the project acknowledges it.

**Comment by ghost** [comment]
I just wanted to mention that I'm super new to docker, and these are the troubles I ran in to using the docker walkthrough:

The command `docker build -t MusicBot .` yields the following error: `invalid value "MusicBot" for flag -t: Error parsing reference: "MusicBot" is not a valid repository/tag`

Using `docker build .` works, however the image doesn't have a repository or tag this way, just an id. If you replace "MusicBot" in the final run & stop commands with the id obtained from building the image, everything works swimmingly.

**Comment by jseed** [comment]
Interesting, I wonder why the tag isn't working, I will have to look into that.  Probably a silly little syntax error on my end.
I'm glad  to hear it works with the id though! The tag is really just for convenience and ease of use.

**Comment by jseed** [comment]
You can't have capital letters in the image name, woops.
Updated the wiki to use the tag musicbot instead of MusicBot

**Comment by jseed** [comment]
Closing this issue since it the new process has been confirmed working
