### ISSUE TITLE
Traceback (most recent call last); , File "run.py" among others.

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#401]
Whole cmd:

"Traceback (most recent call last):
  File "run.py", line 168, in main
    from musicbot import MusicBot
  File " [directory] \musicbot__init__.py", line 1, in <module>
    from .bot import MusicBot
 File " [directory] \musicbot\bot.py", line 38, in <module>
    load_opus_lib()
 File " [directory] \musicbot\opus_loader.py", line 17, in load_opus_lib
   raise RuntimeError('could not load an opus li. Tried %s' % (', '.join(opus_libs)))
RuntimeError: could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib

[Directory] \MusicBot-master>"

Got no clue what this can be.
Any ideas?

Thanks.

**Comment by binury** [comment]
Did you install libopus?

**Comment by FlixWolf** [comment]
Yes. I do.
The MusicBot was working fine, until I got that error from nowhere.

Should I need to re-install it?

**Comment by binury** [comment]
`pip3.5 install --upgrade git+https://github.com/Rapptz/discord.py@async`

**Comment by ghost** [comment]
That worked. Thank you for your help.

**Comment by jayktaylor** [comment]
@FlixWolf If your issue is resolved, please close this - thanks!

**Comment by FlixWolf** [comment]
close

**Comment by FlixWolf** [comment]
close #401
