### ISSUE TITLE
Error on deps update

### ISSUE THREAD

**Issue by GenericUser76** [Just-Some-Bots/MusicBot#404]
No module named 'aiohttp'
Attempting to install dependencies...
Collecting discord.py[voice](from -r requirements.txt %28line 1%29)
  Could not fetch URL https://pypi.python.org/simple/discord.py/: There was a pr
oblem confirming the ssl certificate: [Errno 2] No such file or directory - skip
ping
  Could not find a version that satisfies the requirement discord.py[voice](fro
m -r requirements.txt %28line 1%29) (from versions: )
No matching distribution found for discord.py[voice](from -r requirements.txt %28
line 1%29)

**Comment by dan2wik** [comment]
Do you by any chance have kaspersky?

**Comment by GenericUser76** [comment]
I do not.
