### ISSUE TITLE
AVStream.codec codec parameters to muxers is deprecated.

### ISSUE THREAD

**Issue by theantihero** [Just-Some-Bots/MusicBot#405]
[s16le @ 0x3a35640] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.

I know its a benign error, but I want to fix it.

**Comment by Zumyl** [comment]
Hi, it's an Ffmpeg bug which appeared in build 20160412 and still exists in the latest build 20160711.
It can be reproduced with this single line "ffmpeg -loglevel 24 -i d:\videoin.mp4 -y d:\videoout.mp4".

The latest Ffmpeg version without this bug can be downloaded here :
https://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-20160409-git-0c90b2e-win32-static.7z

You only need to extract and replace 1 file : ffmpeg.exe

**Comment by jayktaylor** [comment]
This will be hidden in a later update. It's not an error as such.
