### ISSUE TITLE
Soundcloud fails: ERROR: Unable to download JSON metadata

### ISSUE THREAD

**Issue by theantihero** [Just-Some-Bots/MusicBot#406]
```
ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>)
<class 'musicbot.exceptions.CommandError'>: ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>)

```

**Comment by arunesh90** [comment]
That is not your side, it's soundcloud's side. So we can do nothing about it

**Comment by o-be-one** [comment]
Hello,

you use the youtube-dl framework, so they have the same issue i assume ... Or they've already fixed it and you have to update the framework on your side ?

I don't know, i just want to know more on how you can't fix it :/.

**Comment by theantihero** [comment]
i found out why it was receiving an error. it depends on where your host is located. for me it was singapore server that blocks soundcloud or soundcloud blocking that region. way to get around is using a proxy with proxychains. but i just switched to a NYC server in United States and connection to soundcloud works.

**Comment by o-be-one** [comment]
Hey, you are probably right ! I think OVH IPs are blacklisted on SoundCloud if i remember correctly (my bot is hosted at OVH) ... That's probably why.

Thanks for your answer it was helpful :+1: :).
