### ISSUE TITLE
Improve skip : !forceskip

### ISSUE THREAD

**Issue by sholan** [Just-Some-Bots/MusicBot#412]
Hello dear devs,

Is it possible to consider the following :
## What
1. Create a new perm|command set called forceskip :
   It would only be granted to owner, admin, moderator and allows to skip without vote (like the current !skip for owners/admins)
2. Change !skip behaviour to allways offer a vote.
## Why

Allows moderator/admins to propose to skip a song they don't like while they can still skip (without vote) an unappropriate song.

Regards,

**Comment by o-be-one** [comment]
All my users with instaskip were asking this today ... They want to use it as a normal user and not as a moderator, and wants forceskip if there's problem with a track. maybe just a "!skip force" could be anough, not need of a new trigger.

**Comment by imayhaveborkedit** [comment]
You can already do this with permissions, there's no point in making a command for this.  I don't see why a moderator would want/need to vote to skip a song.  Skip counting ignores users with the instaskip permission.
https://github.com/SexualRhinoceros/MusicBot/blob/master/config/example_permissions.ini#L51-L52

**Comment by o-be-one** [comment]
I understand your point and the fact that you develop your bot for your Discord server need only. This suggestion is for community where moderators use our services like users, and use moderator power only when it's needed (like to resolve a conflict, to punish when it's required, to restart on crash, etc.). It's not cause of management rules, it's cause the mind of the community is less important than a company.
Anyway, just maybe you can think on the way that moderators dont want to force a skip, they just want to be able to vote. It's like on a forum, moderators can vote without forcing the result or taking the decision anyway.

**Comment by Brend-Smits** [comment]
Have to agree with o-be-one. Great tool for user-like-moderators. 
Shame it won't be implemented though =/

**Comment by gfrewqpoiu** [comment]
yeah agree with @o-be-one and @Rubbertjuh  that was one of the first things I changed as I made my fork. We reserve !instantskip for rule breaking songs and the normal skip works as a vote, even for the Owner Account. Sad to see it will not be implemented here.

**Comment by o-be-one** [comment]
I think @imayhaveborkedit maybe you can reconsider this ?

**Comment by imayhaveborkedit** [comment]
I know what it is you want but it's not very important right now.  Maybe when I'm done with the major features and misc commands and stuff I can change this.  Currently I'm trying to iron out streaming logic and de-nazifying the autoplaylist song check so it doesn't remove your entire list when you have network issues.

**Comment by gfrewqpoiu** [comment]
Here are my patches to the !skip command in bot.py if anyone is interested. Remember that this is all my horrible coding and so if you use it and it breaks or you find a bug, harass me and not @imayhaveborkedit . Also this fixed the Issue of people counting double when they deafen themselves.
Please double check the correct indentation. It starts at if authorid==... and goes to numvoice=...

``` Python
        if author == player.current_entry.meta.get('author', None):
            player.skip()  # check autopause stuff here
            await self._manual_delete_check(message)
            return

        if author.self_deaf == True or author.deaf == True:
            return Response('You cannot use !skip while deafened', reply=True, delete_after=20)

        num_voice = sum(1 for m in voice_channel.voice_members if not (
            m.deaf or m.self_deaf or m.id == self.user.id))
```

And for the !instantskip command I just duplicated the whole !skip method (while renaming the method and description) until the  `if not player.current_entry:` clause is finished, then I just placed an 

``` Python
else:
    player.skip()
    return
```

**Comment by o-be-one** [comment]
Thanks Daniel for your comprehension, that's nice to see that you take this point into account even if you it's not a priority :).

Thanks gfreqqpoiu for the patch !

**Comment by chuushi** [comment]
Is there any chance this will be included in the main code?  I would like to see this feature coded in, but seeing this issue is closed and in a milestone, yet not officially implemented makes it confusing.
