### ISSUE TITLE
Can't Start up. Error on m = MusicBot() and more.

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#415]
While attempting to start the bot the following traceback occurs.

```
Traceback (most recent call last):
  File "CakeMusicBot.py", line 163, in main
    m = MusicBot()
  File "C:\Users\JasorYEH\Desktop\CakeBot\musicbot\bot.py", line 96, in __init__
    self.http.user_agent += ' MusicBot/%s' % BOTVERSION
  File "C:\Users\JasorYEH\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 234, in _
_getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'musicbot.bot.MusicBot'>' object has no attribute 'http'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0453B470>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0454D370>
```

**Comment by Porkchucker** [comment]
Same here. Exact same thing.

EDIT: FIxed it by using an older versions options.ini file

**Comment by bnema** [comment]
Same error here, trying to use a fresh new options.ini, it doesn't work.

Sadly I don't have an oldier version to try this out.

**Comment by Porkchucker** [comment]
Someone linked this version in a different thread and it works flawlessly for me. Give it a try

https://github.com/SexualRhinoceros/MusicBot/releases/tag/1.9.5_2

**Comment by junhyap** [comment]
run update_deps.bat.

Should solve this problem

**Comment by bindingflare** [comment]
Updating in one option is a way, but if you don't want to I disabled this line of code that probably was the root of the problem to start it again:

Line 90: self.headers['user-agent'] += ' MusicBot/%s' % BOTVERSION

I added a # to disable this line of code from running.

Line90: #Disabled self.headers['user-agent'] += ' MusicBot/%s' % BOTVERSION

**Comment by imayhaveborkedit** [comment]
^ Don't do this.  Just be a normal person and update your bot and deps together.
