### ISSUE TITLE
Add comments to autoplaylist.txt

### ISSUE THREAD

**Issue by spiral6** [Just-Some-Bots/MusicBot#417]
It would be really useful to label songs with comments. The bot could ignore lines when parsing them if they start with a certain character, i.e. #,

# Rick Astley - Never Gonna Give You Up
https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by imayhaveborkedit** [comment]
You can, since this commit: f96b769c2262a31403b4307d1d0cb431e9e81396  It's ok for distributing but when the bot removes a dead song from the list it rewrites the file and the comments get deleted.

**Comment by spiral6** [comment]
Oh, ok, thanks. Should add that to the wiki.
