### ISSUE TITLE
Question- Fun, Why?

### ISSUE THREAD

**Issue by Phonavis** [Just-Some-Bots/MusicBot#418]
One of the videos in our playlist is called "Fun", it's a youtube video with a kazoo basically.
It always shows in the queue command, for some strange reason...
Any clue why?
http://puu.sh/pYfmS/bd591138f7.png
Video location- https://www.youtube.com/watch?v=iLG_w9LLNSg&index=160&list=PLItIOUCyP-o_BkGsmhRo3gxAecVhikMWm

It's rather... Funny? To everyone, but uh, I'm curious why it's happening.

**Comment by vladfrangu** [comment]
Try restarting it..

**Comment by Phonavis** [comment]
I'm curious if you're joking...
I really hope you are.

**Comment by ImthePeach** [comment]
Pull off the last half of the url so instead of using:
https://www.youtube.com/watch?v=iLG_w9LLNSg&index=160&list=PLItIOUCyP-o_BkGsmhRo3gxAecVhikMWm
Use just this part instead:
https://www.youtube.com/watch?v=iLG_w9LLNSg

**Comment by Phonavis** [comment]
What difference would that make? I just linked it in the playlist on accident, It's easier to just use $play the playlist, instead of adding all 1.1k songs individually.
And if you're trying to say it's because we add it with the playlist, we actually link the playlist directly, aka this URL -> https://www.youtube.com/playlist?list=PLItIOUCyP-o_BkGsmhRo3gxAecVhikMWm.

So what exactly are you telling me to do Peach? 

More info just found, Apparently it's not just fun, a few different songs have this issue, and it causes it only to display 4 in queue, when it usually displays up to 20.
http://puu.sh/qcRnd/e76ea08669.png
And sometimes it only displays the odd balls.
http://puu.sh/qcRvt/a6f8821f27.png
