### ISSUE TITLE
connects, downloads song, then errors.

### ISSUE THREAD

**Issue by lupeloop** [Just-Some-Bots/MusicBot#423]
Heres what it says:

(it downloads the song)
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at C:\Users\Administrator\Desktop\Musicbot-master\musicbot\player.py:224> exception=TypeError<"create_ffmpeg_player() got an unexpected keyword argument 'stderr'",>>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _play
     result = coro.send(none)
  File "C\Users\Administrator\Desktop\MusicBot-Master\musicbot\player.py", line 260, in _play
      after=lambda: self.loop.call_soon_threadsafe(self._playback_finished)
TyperError: create_ffmpeg_player() got an unexpected keyword argument 'stderr'

i might have gotten some "()" mixed up with "<>" sorry, its really hard to tell in command prompt

_i have no idea how to use python, sorry_

**Comment by goeo-** [comment]
i'm having the same problem

**Comment by Youssef4d** [comment]
Same there...

```
[Download] Started: https://www.youtube.com/watch?v=mLRjFWDGs1g
[Download] Complete: https://www.youtube.com/watch?v=mLRjFWDGs1g
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at /root/MusicBot       /musicbot/player.py:229> exception=TypeError("create_ffmpeg_player() got an unex       pected keyword argument 'stderr'",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/root/MusicBot/musicbot/player.py", line 265, in _play
    after=lambda: self.loop.call_soon_threadsafe(self._playback_finished)
TypeError: create_ffmpeg_player() got an unexpected keyword argument 'stderr'

```

**Comment by jayktaylor** [comment]
Don't use the review branch of the bot. Use `master` instead.
