### ISSUE TITLE
Runs for 6-10 minutes then crashes

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#424]
I'm running the bot on an ubuntu server. Python is up to date, pip is too, as of right now I've run apt-get upgrade and gotten it up to date which did nothing. 

The issue is that I can run the bot but only for a limited time before it crashes with this error, pictured here: http://i.imgur.com/pajb05L.png . 

If any of you know how to fix this or a work around, please tell me.

**Comment by vladfrangu** [comment]
First.. Try updating your dependencies and/or bot files.. 

Then try again
