### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by grizzogor** [Just-Some-Bots/MusicBot#426]
I installed the MusicBot on my Pine(A)64 with the Debian/Raspian Instructions and whenever a new song plays, it outputs this in the console `[s16le @ 0x1926e60] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
`I don't know if it's a bug or I just installed it wrong. Also, the `0x1926e60` part changes when a new song plays.

**Comment by MistChristmas** [comment]
Have you tried running "update_deps"?

**Comment by grizzogor** [comment]
I can't because `update_deps.bat` is a Windows Batch File and I'm using Linux on the Pine(A)64.

**Comment by iNightmaree** [comment]
I've dealt with this bug before. To the best of my knowledge, this shouldn't do anything harmful to the music your trying to play. It should be safe to ignore it, although someone can correct me if I'm wrong on this.

In the future, if you struggle, your best off going to ask in the [Rhino Help Server](http://discord.me/rhinohelp) where you can get faster support for problems like this..
