### ISSUE TITLE
won't play any music

### ISSUE THREAD

**Issue by jspain93** [Just-Some-Bots/MusicBot#428]
my bot wont play any music, i made a playlist and i dont know why it wont work

ERROR: Signature extraction failed: Traceback (most recent call last):

**Comment by iNightmaree** [comment]
You need to provide what the Traceback error actually is, or I won't be able to understand the problem. Could you join the [Rhino Help Server](http://discord.me/rhinohelp) and enter the #musicbothelp channel whenever you get the chance to please?

**Comment by jspain93** [comment]
i fixed it, it just needed update. i are stupid

**Comment by devsnek** [comment]
@jspain93 can you please close this issue if your problem is solved?

Thanks :)
