### ISSUE TITLE
Local static playlists

### ISSUE THREAD

**Issue by DrewTylerJ** [Just-Some-Bots/MusicBot#43]
It would be nice not to have to set up a queue and be able to just play the auto playlist, or even other cached playlists. I checked the commands and I didn't see a way to do this. This would be a great addition, as it would be a lot easier on the network intensive side. Also gets rid of the annoying having to look up stuff in order to just try to get to my autoplaylist.

**Comment by imayhaveborkedit** [comment]
Local file playback is part of the static playlist stuff. It'll be something like you can create a folder (or symlink) and the bot will play songs from there.

**Comment by DrewTylerJ** [comment]
Do we know how far away this is?

**Comment by woj2012** [comment]
A bit different idea (I don't find creating a new topic necessary).
Maybe you can make something like playing from a folder, eg C:\Users\UserName\folder1\musicname.mp1?

**Comment by DethBringa** [comment]
Thanks for that, didn't realize this meant the same as what I requested. I read the title and instantly thought local songs like mp3s. lol.

Awesome job btw. Works great.
