### ISSUE TITLE
Add !say command

### ISSUE THREAD

**Issue by danfinlay** [Just-Some-Bots/MusicBot#430]
Would be simple enough to add a `!say` command that has the bot just parrot the owner, or if you have a permissions system, slap that on here too.

I'd enjoy that a lot.

By the way, great work, this is really nice! I love the YouTube integration!

**Comment by jhgg** [comment]
This feature falls out of the scope of what a "music bot" should do. The project is open source though, and you're more than welcome to implement this on your own fork and run it.
