### ISSUE TITLE
Pine(A)64 Debian MusicBot Image (16GB or higher cards ONLY)

### ISSUE THREAD

**Issue by grizzogor** [Just-Some-Bots/MusicBot#432]
I made a Debian image for the Pine(A)64 with MusicBot 1.9.5_2, SSH, and FTP support already installed.
This will help for people that are too lazy or scared to compile everything.
Windows Installation: Use WinRAR or 7zip to extract the RAR file, then use [Win32DiskImager](https://sourceforge.net/projects/win32diskimager/) write to the microSD card.
Mac/Linux Installation: Use tar (or something else) and use dd to write the image onto the microSD card.

[Google Drive RAR Download](https://drive.google.com/open?id=0B6KAd6OjYm5benZ5UDJfd1VWYjA)

**Comment by jayktaylor** [comment]
We've written our guides, including the Debian one, to be more friendly. We strongly encourage compiling Python and required dependencies manually.
