### ISSUE TITLE
Bug Report: Stops displaying what it's playing in the sidebar when skipping multiple times. 

### ISSUE THREAD

**Issue by grizzogor** [Just-Some-Bots/MusicBot#433]
Whenever I skip many times in a row, it stops displaying what music it's playing in the sidebar.
Is this a bug or a error with my installation?

EDIT: Apparently, when I did the .np command (!np), it fixes it.

**Comment by imayhaveborkedit** [comment]
Its because skipping songs rapidly tries to change the status too fast, resulting in the bot getting rate limited.  Discord limitation, not really much I can do.
