### ISSUE TITLE
Proxy YouTube requests

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#434]
Hi,
Would it be possible to make the bot use youtube-dl via proxy, so that one can run the server in Germany and not have to deal with GEMA?

Regards,
Billy.

**Comment by jayktaylor** [comment]
This isn't currently a feature of the bot. I'd highly advise against using this kind of bot in Germany due to their strict restrictions.

**Comment by gfrewqpoiu** [comment]
It is possible to add a proxy url to the youtube dl options by manually editing downloader.py in the musicbot folder. It should look like this 
<img width="1020" alt="proxy" src="https://cloud.githubusercontent.com/assets/1358212/16907419/eeddf0ea-4cc3-11e6-9915-fcea665492da.png">

But @jaydenkieran is correct, you should try to get the bot hosted elsewhere. Also please don't post any error messages here when you edit this.
