### ISSUE TITLE
Problems with running runbot.bat

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#436]
Hi guys,

so i got this weird thing that the .bat is:
1. starting
2. closes really fast

So to find out whats standing in there i startet it like 100 times to read it and i found out that it can't recognize the commands: "CHCP" and "CMD". (It's in the code from the .bat )
I got Python installed (v. 3.5.2) and i really wonder whats not good with my PC.

I got win 7 64-bit btw.

Hope someone here can help me!

**Comment by vladfrangu** [comment]
When you installed Python, did you check the "Add to PATH" box?

**Comment by bindingflare** [comment]
Try running the file (runbot.bat) in Administrator mode using RIGHT CLICK.

**Comment by jayktaylor** [comment]
Check your PATH [environment variable](http://www.computerhope.com/issues/ch000549.htm). It should contain at least the following, if it doesn't add it:

`;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;`
