### ISSUE TITLE
Autoplaylist got wiped

### ISSUE THREAD

**Issue by Shananiganeer** [Just-Some-Bots/MusicBot#437]
I tailored the autoplaylist to my tastes and everything worked fine for several weeks until this afternoon when the playlist got wiped.

**Comment by jayktaylor** [comment]
The autoplaylist won't wipe itself. You either cleared/deleted it yourself, or you updated the bot (which would overwrite your autoplaylist file).

**Edit:** Clearly I was slightly misinformed, listen to Bork :+1:

**Comment by imayhaveborkedit** [comment]
Yes, it will.  The bot removes dead links from the file when it encounters an error processing a link, but it also does so when you have network related errors.  I'm fixing this but you should always have a backup of that file anyways.

**Comment by Shananiganeer** [comment]
Considering the bot regularly runs into errors on links it has successfully played in the past, this 'feature' should be treated as a bug and removed. Seeing as that seems to be the plan, keep up the good work!
