### ISSUE TITLE
how to let people use the summon coummand who is not owner

### ISSUE THREAD

**Issue by mcglynn14** [Just-Some-Bots/MusicBot#438]
i need help to see how I can let people use the summon command who is not owner of the bot

**Comment by junhui-f** [comment]
Assign them a role and provide the summon permissions? In my case i give the default user summon permissions, set it in permissions.ini .

**Comment by mcglynn14** [comment]
Can you show me a picture

**Comment by jayktaylor** [comment]
The top of the permissions.ini file explains how to do this.

**Comment by mcglynn14** [comment]
Can I get a picture so I know what I am looking for

**Comment by imayhaveborkedit** [comment]
Reading is an important skill in the modern world.  You will need to use it to learn how to configure the permissions settings for your bot.  This is all explained in the file.  You don't need pictures of text you already have.
