### ISSUE TITLE
Running bat file/ Code

### ISSUE THREAD

**Issue by DecemberDragon** [Just-Some-Bots/MusicBot#439]
So I keep getting this code when i try to open the file. Any ideas?
Traceback (most recent call last):
  File "run.py", line 162, in main
    from musicbot import MusicBot
  File "C:\Users\angel\Downloads\MusicBot-master\musicbot__init__.py", line 1, in <module>
    from .bot import MusicBot
  File "C:\Users\angel\Downloads\MusicBot-master\musicbot\bot.py", line 16, in <module>
    from discord.ext.commands.bot import _get_variable
ValueError: source code string cannot contain null bytes
C:\Users\angel\Downloads\MusicBot-master>
I done everything correctly and even uninstall and install git and python several times :c

**Comment by imayhaveborkedit** [comment]
Sometimes this will happen for unknown reasons when you download the bot.  Just delete the file or bot folder and reclone it.

**Comment by DecemberDragon** [comment]
I done this mutiple times ;-;

**Comment by itsthekermit** [comment]
Same problem  (on Linux debian7)

**Comment by SGCMainframe** [comment]
:start
node main#index.js
goto start
