### ISSUE TITLE
Automatically add any played track (that doesn't get skipped) to the backup list

### ISSUE THREAD

**Issue by nixxquality** [Just-Some-Bots/MusicBot#44]
Feature request

**Comment by FukujiMihoko** [comment]
Implemented this to my fork, except it doesn't check if the song was skipped as it adds the played track when the !play command succeeds.
https://github.com/FukujiMihoko/MusicBot

Nevermind, had a lot of amateur programming mistakes (like forgetting my own variable names). Will fix later.

**Comment by johnroot** [comment]
I believe I've implemented this in my fork. #47

**Comment by Chewsterchew** [comment]
+1
