### ISSUE TITLE
Suggestion: Pitch Command

### ISSUE THREAD

**Issue by snibk** [Just-Some-Bots/MusicBot#441]
I have no idea if this is even possible with the tools you are provided with, and youtube's limitations, but adding an option to control pitch would be pretty cool.
Example:
!pitch 1 - Normal Pitch
!pitch 2 - 2x Pitch
!pitch 0.5 - 1/2 Pitch
!pitch 10 - 10x Pitch

**Comment by imayhaveborkedit** [comment]
Youtube is irrelevant in this situation.  This would have to either be passed as an argument to ffmpeg, which affects the entire song from start to finish, or i'd have to figure out how to manipulate the PCM frames to get this affect.  Neither of which are good ideas, so this is not going to happen.
