### ISSUE TITLE
License

### ISSUE THREAD

**Issue by arthurbarros** [Just-Some-Bots/MusicBot#442]
Where can I find which license this project currently is on?

**Comment by jhgg** [comment]
Should be MIT.  Was my intent when we put the base together. Will have to seeeeeee what the other contributors think.

**Comment by imayhaveborkedit** [comment]
A while back we were considering GPL for some reason but we dumped the idea.  MIT is fine but it'd probably be best to poke @SexualRhinoceros about it too.

**Comment by jhgg** [comment]
:-1: to GPL

**Comment by srhinos** [comment]
:+1: to MIT 

fyi @jhgg was the one who suggest GPL... :eyes:

**Comment by jhgg** [comment]
was i? doesnt sound much like me to suggest GPL >_>

**Comment by srhinos** [comment]
yeah GPL requires a ton of work on my part but you suggested GPL would be the best. this was a long time ago though

**Comment by FrankMercer** [comment]
Hey i have a question. what if i wanted to grab your music bot and change the bot account to another but only for my friend's server? Like we just want to change the icon so it fits the name we gave it. Could you explain me where to change the login credentials for the bot?

**Comment by yc1000** [comment]
Hi Rhino, so I used your music bot and added a couple of commands to it. Namely the ability to create your own autoplaylist, add songs to it, remove songs from it, and put all the songs in a certain playlist in the queue. The only file I changed was the bot.py file. I know from looking at your code that you were looking to do those in your own way, but would you like to see the edits I added? (It's like 100-200 lines of code all in one place that I could even just paste here).

**Comment by deansheather** [comment]
Bump. Licensing is important.
cc @SexualRhinoceros @imayhaveborkedit

**Comment by jayktaylor** [comment]
I'm pretty sure MIT was decided on. Bork said that to me before and I added it to the FAQ. It should really be added in some LICENSE file or something though

**Comment by jayktaylor** [comment]
A LICENSE file was added.
