### ISSUE TITLE
Runtime error: Could not load an opus lib.

### ISSUE THREAD

**Issue by Nightshadow42** [Just-Some-Bots/MusicBot#444]
I set up the bot properly, attempted to run it and got this error running the runbot.bat

![image](https://cloud.githubusercontent.com/assets/20590822/17046805/d19edeaa-4f9c-11e6-8543-549eed6242c5.png)

**Comment by vladfrangu** [comment]
You dont have the dependencies..

Run update-something and try again
Make sure you have a requirements.txt file
