### ISSUE TITLE
RuntimeError: PyNaCl library needed in order to use voice

### ISSUE THREAD

**Issue by Stebenn** [Just-Some-Bots/MusicBot#446]
Everytime I start up the bot it always says that it needs PyNaCl Library needed in order to use voice and  I don't see why it would be doing this as I started completely new with the bot through the .zip and I'm getting this issue. How would I fix this problem
![screenshot_1](https://cloud.githubusercontent.com/assets/20601510/17065007/87684148-500d-11e6-9b9f-d1bd63c34317.png)

**Comment by jayktaylor** [comment]
Update your dependencies.
