### ISSUE TITLE
Equalise volume between tracks (ReplayGain?)

### ISSUE THREAD

**Issue by nixxquality** [Just-Some-Bots/MusicBot#45]
Feature request

**Comment by Wicloz** [comment]
We need this, it's so annoying when one track is super loud and you lower the volume, only to not be able to hear the next track.

**Comment by sgdc3** [comment]
+1
An enable/disable command would be awesome! (!normalization true/false)

**Comment by imayhaveborkedit** [comment]
Normalization between tracks is most likely not going to happen.  I'll probably experiment with it when I do single track normalization stuff, but don't expect anything.
