### ISSUE TITLE
Unclosed client session?

### ISSUE THREAD

**Issue by tacoman918** [Just-Some-Bots/MusicBot#453]
when I try to launch music bot, I come up with an error that looks like this
https://gyazo.com/c6231b0ecf7e0827febab363d79d6d79
It goes in an endless loop and wont launch, can I get some help?

**Comment by gfrewqpoiu** [comment]
This seems to be an issue with the installed version of the Discord Api. Try to run update_dependencies.bat and then starting the bot again.

**Comment by jayktaylor** [comment]
You're using an outdated version of the MusicBot. Use 1.9.5_2. Follow the correct installation guides.
- Windows: https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Windows-7-and-up
- Ubuntu: https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Ubuntu-14.04-and-other-versions
- Debian: https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Raspberry-Pi-with-Raspbian-or-PC-with-Debian
- OSX: https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-OSX
- Docker: https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Docker
