### ISSUE TITLE
How do I make MusicBot follow youtube-dl options?

### ISSUE THREAD

**Issue by m8wtf** [Just-Some-Bots/MusicBot#457]
My server IP is being blocked by youtube so MusicBot Isn't working, to get around this I can give a youtube accounts details and sign in, I have added the options to the youtube-dl.conf file and I can download from youtube from console. 

How can I make MusicBot follow the options or where do I add them?

**Comment by gfrewqpoiu** [comment]
There is nothing in the bot yet to enable that functionality, you could theoretically add the flags to downloader.py but that would make the bot fail any download that is not coming from youtube.

**Comment by m8wtf** [comment]
I had tried adding 
'username' : 'myemail@whatever.yes',
'password' : 'PassWord1'

to the "ytdl_format_options" bit but it didn't do anything, I don't mind only being able to play youtube songs.

I think there was another way I could get it to download as well by just using the --prefer-insecure and --no-check-certificate options in the youtube-dl options config. Would adding these to the download.py file break functionality for soundcloud etc?

Also how/where would I add the username and password to the download.py file?

Thanks for your response

**Comment by jayktaylor** [comment]
We do not provide this functionality in the bot. If your IP has been blocked by YouTube, it's because you are making too many requests.

**Comment by m8wtf** [comment]
Being a VPS it's only a virtual server on something much bigger, all of the IP's owned by my VPS provider get blocked by youtube, I disabled the autoplaylist so that only requests I put forward manually go through and it blocks every request every time. google searching the error shows other people experiencing the same problem with their VPS provider however some can force Ipv4 and it will work while others will have to add options in the "youtube-dl" file.

Guess I'll have to use a proxy.

**Comment by jayktaylor** [comment]
You can proxy requests through youtube-dl but we won't help you with that. You need to add the options in `downloader.py`, and a list of youtube-dl's options are available here: https://github.com/rg3/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L128-L278
