### ISSUE TITLE
How to enable bot running 24hrs

### ISSUE THREAD

**Issue by dereksiol** [Just-Some-Bots/MusicBot#458]
How do I keep the bot online for 24 hours even if I have to off my computer? 

Its kinda sad the bot has to go down if I have to go offline. Any ways?

**Comment by m8wtf** [comment]
You have to have a server, a computer that is turned on all the time. You could use a raspberry pi if you have one, you don't.

**Comment by Cryzin** [comment]
Just get a Standard VPS for very cheap, thats what I am using for hosting the bot.

http://ramnode.com/vps.php

**Comment by arunesh90** [comment]
My recommendation for best pricing and getting high specs:
https://www.scaleway.com/pricing/

2GB ram, 50GB SSD, 2 cores, unlimited internet 1gbps for ~3 euro

**Comment by jayktaylor** [comment]
Information about running the bot permanently is available in the installation guides which you should've followed in the first place.
- Windows: https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Windows-7-and-up
- Ubuntu: https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Ubuntu-14.04-and-other-versions
- OSX: https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-OSX
- Debian: https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Raspberry-Pi-with-Raspbian-or-PC-with-Debian
- Docker: https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Docker
