### ISSUE TITLE
Cant play youtube videos (Ubuntu)

### ISSUE THREAD

**Issue by AlDfriD** [Just-Some-Bots/MusicBot#462]
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
Unrecognized option 'nostdin'

Any fix for that guys i have installed latest ffmpeg version and its on also tried tons of thing but still doesnt work for me....

**Comment by leonekmi** [comment]
Same problem !

**Comment by jayktaylor** [comment]
There is already an issue about this with solutions and appropiate information: #358.
