### ISSUE TITLE
Why cant I set Default group to do volume.

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#463]
When I go on permission txt and grant people to that group but some reason they cant to !volume and I try adding volume in the commandwhitelist and when I get back on discord and do !perms it show all of command_whitelist: {'search', 'id', 'skip', 'clean', 'help', 'perms', 'queue', 'np', 'play'} That's it and I try different ways still wont work can some one please help me?

**Comment by jayktaylor** [comment]
As is hinted to in the name, `[Default]` is the group that is used **_by default_**. You shouldn't be adding users or roles to it.

To add a command to the whitelist, add it with a space.

```
CommandWhitelist = search id skip clean help perms queue np play volume
```

You need to restart the bot after saving permissions.txt.

**Comment by ghost** [comment]
I did restart the bot when adding the volume with space and still people can't change the bot volume it keep saying it's not enable for this group (default)

**Comment by jayktaylor** [comment]
You've misconfigured your permissions. We'll be able to help you more with this if you join our help server on Discord: http://discord.me/rhinohelp
