### ISSUE TITLE
Is there a way to change the download quality?

### ISSUE THREAD

**Issue by sypion** [Just-Some-Bots/MusicBot#464]
Hi there! I decided to come to the Music Bot Git hoping to find the answer to my question I've been searching upon for hours. Is there a way to increase the audio quality, or video quality (360p to 720p) on a Discord Music Bot like: https://github.com/SexualRhinoceros/MusicBot

In other terms, is there a way to change the quality the Music Bot downloads?

I hope I made sense. Thanks in advance!

**Comment by m8wtf** [comment]
Yes, it automatically downloads in the highest quality but you can change it if you have a look at the youtube-dl git and find the options https://github.com/SexualRhinoceros/MusicBot/blob/master/musicbot/downloader.py

'format': 'bestaudio/best'

**Comment by ttchristopher** [comment]
Oh my god thank you so much! One last question I guess. What options do I have to put in the format?

**Comment by sypion** [comment]
Thank you very much! I just had two more questions. What are my choices that I can replace 'bestaudio/best' with, and is there a way to change the download bit rate as well like in the attached image?
![image](https://cloud.githubusercontent.com/assets/8906653/17272242/0dffb31a-5646-11e6-8655-043157048c0e.jpeg)

**Comment by jayktaylor** [comment]
youtube-dl format options are documented here: https://github.com/rg3/youtube-dl#format-selection-examples

**Comment by Solamnus7** [comment]
i'm new here, but im trying to use command -r, --limit-rate RATE, just like they say "-r, --limit-rate 50K" and just get 
"
youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
"
any help?

**Comment by jayktaylor** [comment]
Commands won't work with the bot, you have to specify format options in downloader.py. Though we won't help you with that. You should gain some programming experience to be able to edit the bot's files.
