### ISSUE TITLE
Bot Is In Voice Channel But Doesn't Work

### ISSUE THREAD

**Issue by Widek** [Just-Some-Bots/MusicBot#467]
Auto summon is on and when I try to get it to play a song from youtube it says it's not in a voice channel when it clearly is. I then type the "!summon" command and it works but there's no real point in doing it if the bot is already in my voice channel. Yet, it still doesn't work even if I switch voice channels.

**Comment by ghost** [comment]
Make sure you download the python I'll put he link here https://www.python.org/ and download the new version . that's what happen to me it would do the same as it would do to you once I re-download other it work. Hope it works for you

**Comment by Widek** [comment]
I'm afraid it didn't work. Thanks though.

**Comment by ghost** [comment]
Oh its ok

**Comment by ghost** [comment]
Can you take a screenshot of the file
There post to be 3 file's one is audio_cache,config,Musicbot

**Comment by Widek** [comment]
![1](https://cloud.githubusercontent.com/assets/20746618/17274068/644917cc-5694-11e6-8607-125123837f3c.JPG)
![2](https://cloud.githubusercontent.com/assets/20746618/17274070/645997fa-5694-11e6-9958-9bd75b83413c.JPG)
![3](https://cloud.githubusercontent.com/assets/20746618/17274069/64596cda-5694-11e6-96d9-84cb8e8f1b22.JPG)

**Comment by jayktaylor** [comment]
Follow the [Installation Guide for Windows](https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Windows-7-and-up) properly. You installed it wrong.
