### ISSUE TITLE
Song speed, lag, and random skip issue.

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#469]
So, my friend is using MusicBot in his Discord server. We are expieriencing this problem where the song will lag (i dont know if its just my end), but sometimes the song lags so much it complete skips to the next song in the queue. It gets annoying after a while.

**Comment by junhui-f** [comment]
Poor connection from the Bot (VPS/User hosted) to Discord servers. Run tests from the bot machine to the connected discord server and check for packet loss.

**Comment by jayktaylor** [comment]
There are many reasons why this could happen, mostly happening because of a poor internet connection or poor CPU. It can also sometimes be caused by Discord's servers. We can't help you with this.
