### ISSUE TITLE
Changing the bot account

### ISSUE THREAD

**Issue by FrankMercer** [Just-Some-Bots/MusicBot#472]
So my friends and I love your music bot. We love how easy to use the bot is. We were wondering if we could idk make a clone of your bot but with a different bot account so we could match it to the theme we are currently running in our Discord Server. I was just wondering how we could do that or if you were willing to do a private version for us. This is all because is unfortunate we can't change the image the bot uses for the server. Sorry if am bothering you. I just really like your bot and I would love to learn more about this aswell. 
Thanks!

**Comment by kojitsari** [comment]
You mean like these commands that the bot has had?
![](https://i.zelakto.tv/nqHZMhh.jpg)

**Comment by FrankMercer** [comment]
Damm this is good Thanks m8!
