### ISSUE TITLE
Bot doesn't join server?

### ISSUE THREAD

**Issue by ImDale** [Just-Some-Bots/MusicBot#473]
Sorry in advance, I'm a super noob when it comes to this stuff. As far as I know, I set it up right, but when I run the bot, it doesn't show up in online users and also doesn't take commands. This is what the cmd window looks like http://i.imgur.com/NXuvnQM.png . I tried to read through all the notes in the files as best I could and couldn't find a solution.

**Comment by jayktaylor** [comment]
Can you show your entire traceback? You seem to have cut off parts after the bottom of your screenshot.

**Comment by ImDale** [comment]
http://i.imgur.com/Eduwkaq.png

**Comment by jayktaylor** [comment]
:inbox_tray: Updating your **MusicBot dependencies**
You will need to update your dependencies to resolve most common issues, and to be able to run the bot efficiently. Try and keep them updated as much as possible.

**Windows** - Open `update_deps.bat`
**Linux** - In your console, run `python3.5 -m pip install --upgrade -r requirements.txt`
**Mac** - Open `update_macdeps.command` in Terminal

**Comment by ImDale** [comment]
opened `update_deps.bat` and ran it, it finished, I closed it, and still got http://i.imgur.com/YxmiBP1.png

**Comment by jayktaylor** [comment]
Your bot has no permission to join the voice channel you're trying to make it autosummon to. You can clearly see in the screenshot. `Can't join channel 'Overwatch', no permission`
Give it all of the permissions on the server.

**Comment by ImDale** [comment]
Could you explain how to do that? From what I read, it looked like when I have it my owner ID, it gave the bot all the permissions that I had but I now assume that is not the case.

**Comment by jayktaylor** [comment]
You literally need to just give it a role that has permissions on the server e.g

![Image](http://i.imgur.com/GWZ0nqw.png)

**Comment by ImDale** [comment]
How do I give it a role without it joining the server?

**Comment by ghost** [comment]
It easy go to what Jayden said and push that + and add the role and make sure to check the box I just checked all of them xp hope this works

**Comment by ghost** [comment]
Oh and don't forget to give the bot the role by right clicking it and push + and five the role what you put

**Comment by ImDale** [comment]
Okay so update, my issue seemed to be with discord itself, not the bot. I had to go to the server members list to add a role because discord wasn't displaying online users with no role.
