### ISSUE TITLE
Bot commands and permissions

### ISSUE THREAD

**Issue by FrankMercer** [Just-Some-Bots/MusicBot#475]
So i got the bot working in my server but my friends and I dont want the bot to autojoin and such. So i turned off the auto summon and the aunto join feature so it comes when you summon the bot. Now the summon commands default permissions does not allow for anybody bot me to summon it. how do i change the permissions so everyone can summon the bot? And also is there a command to tell the bot to stop playing and leave the voice channel?

**Comment by jayktaylor** [comment]
`!disconnect` makes the bot leave the voice channel.

For permissions help, read the top of `permissions.ini`.

**Comment by R3aper3123** [comment]
hey just got it setup but how do i use the commands it only plays the auto playlist
