### ISSUE TITLE
Bot won't queue up youtube.

### ISSUE THREAD

**Issue by AdmiralTeitoku** [Just-Some-Bots/MusicBot#476]
https://puu.sh/qjrvH/f4675a5175.png
Bot keeps displaying this error when trying to queue up a video to be played. I made new bots and reinstalled the bot. And it isn't a internet connectivity issue. I also updated youtube_dl by running update_deps.bat.

**Comment by jayktaylor** [comment]
This is a youtube-dl error. Does it occur with any of youtube-dl's supported sites? e.g Soundcloud
