### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by HunBurry** [Just-Some-Bots/MusicBot#479]
I keep getting an error reading:

fatal: could not create work tree dir 'MusicBot': permission denied

**Comment by jayktaylor** [comment]
To fix this, either run Git Bash with administrator privileges or run it in a place that doesn't require them.
You should open Git Bash by **right-clicking the folder you want the bot to go in** and choosing 'Git Bash Here'
If the option doesn't exist, you installed Git Bash wrong.
