### ISSUE TITLE
Failed to Connect

### ISSUE THREAD

**Issue by Cryzin** [Just-Some-Bots/MusicBot#481]
It's not joining voice channel anymore.

![musicbot](https://cloud.githubusercontent.com/assets/1764503/17347943/b745ceca-58d8-11e6-9e8c-605fdd2b174c.png)

**Comment by jaydenkieran** [comment]
`4004, reason = not found.`

Make sure that you're using the right ID for the voice channel. If you deleted it and remade it or something, this ID will be different.

**Comment by DNAGamer** [comment]
As far as i can tell all of them are doing it right now, i think its an issue with discord
Just keep looking here: https://status.discordapp.com/

**Comment by raideer** [comment]
Same here

**Comment by Cryzin** [comment]
Any updates?

**Comment by jayktaylor** [comment]
Can you try changing your server's voice region?
