### ISSUE TITLE
How to use URL Dump?

### ISSUE THREAD

**Issue by Chromesy** [Just-Some-Bots/MusicBot#484]
I have an extensive playlist on soundcloud, and I'm not really sure how to queue up all the songs in one fell swoop. Is that possible? I'd really prefer not to have to queue up 200+ songs individually. I'm sure you have a feature for this but I am failing to find it.  Perhaps explain the use of !pldump a little better?

**Comment by imayhaveborkedit** [comment]
The pldump command is for getting a list of links from a playlist with the intent of putting them in the autoplaylist (or whatever else you want to do with them).  If you have a soundcloud set you can just queue that directly.

**Comment by Chromesy** [comment]
I just realized that... I feel very dumb... Thanks anyway :+1:
