### ISSUE TITLE
When song from autoplaylist is unavailable - bot hangs 

### ISSUE THREAD

**Issue by brawaru** [Just-Some-Bots/MusicBot#485]
https://gist.github.com/DaFri-Nochiterov/8189c799453184beddd44c354e8f3f7b

**Comment by imayhaveborkedit** [comment]
3431252

**Comment by brawaru** [comment]
Another error :new_moon_with_face: 
https://gist.github.com/DaFri-Nochiterov/bbc53cbe6396d252cab305b5b3a9ce02

**Comment by imayhaveborkedit** [comment]
:ok:
