### ISSUE TITLE
Login Email not specified in the config.

### ISSUE THREAD

**Issue by HeliumxU** [Just-Some-Bots/MusicBot#487]
I downloaded the newest MusicBot-master.zip, and ported my old configs, but now I get the following error: 

An error has occured reading the config:

  Problem:  The login email was not specified in the config.  
  Solution: Please put your bot account credentials in the config.  Remember that the Email is the email address used               to register the bot account.                                                                                

C:\Users*****\Desktop\MusicBot-master>

Yet, I have the correct credentials in the config. What do I do?

Config had to be packed in a .zip

[options - censored.zip](https://github.com/SexualRhinoceros/MusicBot/files/404923/options.-.censored.zip)

**Comment by junhui-f** [comment]
Example says its
`
Email = bot_discord@email
`
your copy says
`
Username = *******@live.no
`

Change "Username" to "Email"

**Comment by HeliumxU** [comment]
Now it recognizes the password and Email, but I get this error:

Traceback (most recent call last):
  File "run.py", line 163, in main
    m = MusicBot()
  File "C:\Users***_\Desktop\MusicBot-master\musicbot\bot.py", line 96, in **init**
    self.http.user_agent += ' MusicBot/%s' % BOTVERSION
  File "C:\Users\**_*\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 249, in **getattr**
    raise AttributeError(msg.format(self.**class**, name))
AttributeError: '<class 'musicbot.bot.MusicBot'>' object has no attribute 'http'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x047FB570
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x047FB8B0

C:\Users****\Desktop\MusicBot-master>

**Comment by jayktaylor** [comment]
Update your dependencies.

**Comment by kingcatdaan** [comment]
y u no git pull

**Comment by scruffyduck18** [comment]
![image](https://user-images.githubusercontent.com/35208742/34657836-35a5923a-f3f8-11e7-8df0-fdf7993eb6e7.png)

I need some help someone please.. I have the same issue as above except mine still didn't recognize even after updating dependancies

**Comment by jayktaylor** [comment]
@scruffyduck18 The bot no longer supports an email/pass authentication flow because it is not recommended for bots by Discord. Please create a bot account and fill in the `Token` option instead. See https://github.com/Just-Some-Bots/MusicBot/wiki/FAQ#how-do-i-create-a-bot-account for a step-by-step guide on how to do this.
