### ISSUE TITLE
Improve logging and output when non-owners attempt to summon

### ISSUE THREAD

**Issue by gurchik** [Just-Some-Bots/MusicBot#497]
When MusicBot is not currently in a voice channel and a non-owner attempts to summon it to a voice channel, MusicBot does not reply, which is a bad user experience -- a message such as "You must be owner to use this command" would be better.

Additionally, there is weird log output when nonowners and owners use the summon command. Take the following excerpt for instance:

```
[Command] NON-OWNER (!play)
Owner not found in a voice channel, could not autosummon.
[Command] NON-OWNER (!summon)
<class 'musicbot.exceptions.CommandError'>: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.
[Command] NON-OWNER2 (!summon)
<class 'musicbot.exceptions.PermissionsError'>: You don't have permission to use that command.
Reason: This command is not enabled for your group (Default).
[Command] NON-OWNER (!summon)
<class 'musicbot.exceptions.PermissionsError'>: You don't have permission to use that command.
Reason: This command is not enabled for your group (Default).
[Command] NON-OWNER (!play)
<class 'musicbot.exceptions.PermissionsError'>: You don't have permission to use that command.
Reason: This command is not enabled for your group (Default).
[Command] OWNER (!summon)
<class 'musicbot.exceptions.CommandError'>: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.
```

Throwing an except saying the bot isn't in a voice channel when you are attempting to use `!summon` doesn't make sense. Additionally, the command is still thrown when the owner uses the command, even though the command executes as expected.

**Comment by jayktaylor** [comment]
1. `!summon` is not an owner-only command
2. The bot does respond to users that don't have the permission to use the command, as shown in your excerpt. [See here](https://github.com/SexualRhinoceros/MusicBot/blob/master/musicbot/bot.py#L1906).
3. `The bot is not in a voice channel.  Use !summon to summon it to your voice channel.` being thrown when summoning can be caused by you not having the correct `discord.py` dependency installed. Make sure you are using the latest version of the bot (**1.9.5_2**) and you have updated your dependencies.

**Comment by gurchik** [comment]
It would seem you're correct from looking through `cmd_summon()`, but for me on default permissions only the owner can use `!summon`. I can look into it further tonight.

My excerpt is from the bot logs, not from the Discord channel. It definitely logs that the user doesn't have the correct permissions, but doesn't tell them in the Discord channel (the bot simply does nothing). However, the `The bot is not in a voice channel` is sent to the discord channel.

I'm fully up-to-date on all dependencies and on the bot version. I run an update cronjob nightly.

If you prefer, feel free to mention me (ishiz) in #feature-requests

**Comment by gurchik** [comment]
Upon closer inspection it would appear that it _does_ write the permission error to the Discord text channel, but deletes it later; it does not delete the `not in a voice channel` error. In my opinion, errors should not be automatically deleted, but if they are, then all errors should be deleted, not just permission errors. If I can verify this once more I will open a separate issue for this.

The issue still remains that the log should not ever state `The bot is not in a voice channel` when a user uses `!summon`, and it should not happen when the summon command is successful as in the last line in my log output.

**Comment by jayktaylor** [comment]
The reason that permission errors are deleted after a short time are because they're user-specific errors, compared to how `not in a voice channel` is an actual 'error'. 

When a `!summon` is successful and `The bot is not in a voice channel` appears in the console, does it also send it to the Discord text channel the command was invoked in? (it's meant to)

**Comment by gurchik** [comment]
I can't reproduce this reliably. Right now I'm getting no errors:

```
[Command] OWNER (!help)
[Command] OWNER (!summon)
```

But before I was getting errors, as can be seen from the logs above. I'm going to leave this open for a bit while I try to find a method to replicate this reliably, and if I can't find it I will close this.

**Comment by gurchik** [comment]
@jaydenkieran Let me know what happens for you when following the following steps:
1. Have all your server voice channels empty (including yourself), except the bot if it is currently logged on.
2. Shut off your bot, wait for it to leave your voice channel
3. Turn on your bot, and verify that the last line in the log says `Attempting to autosummon...`
4. Join a voice channel (one that your bot was not in last, if possible).
5. Type `!help`

You should see in your logs:

```
[Command] NAME (!help)
Owner not found in a voice channel, could not autosummon.
```

It doesn't seem to matter how long you wait between steps 3 and 4, it always prints that error immediately after `!help`, not before.

**Comment by jayktaylor** [comment]
Marking this as a PEBKAC issue as can't reproduce.
