### ISSUE TITLE
[request] multiple playlists and command to change.

### ISSUE THREAD

**Issue by DethBringa** [Just-Some-Bots/MusicBot#499]
An option to have multiple playlists and a command to change between them. 
Add a setting in config to load xxxxxx.txt on bot load, so you can select the default one to load up.
Add command like !apl (AutoPlayList) so you could "!apl rock" to load autoplaylist rock.txt or "!apl 90s" to load playlist called 90s.txt

**Comment by jayktaylor** [comment]
#43
