### ISSUE TITLE
(Feature Request) Audio input / Local Sound File

### ISSUE THREAD

**Issue by ninjarisu** [Just-Some-Bots/MusicBot#501]
Have it to where it can listen into a sound input looped back from an output (Such as Virtual DJ from the DJ Console audio for DJs who want to stream there live mixes or those who like to call themselves DJs and playlist).
The ability to play local MP3 or other audio files.

**Comment by jayktaylor** [comment]
Your first request is probably never going to happen due to technical limitations.
Your second request is a duplicate of #43.
