### ISSUE TITLE
Laggy

### ISSUE THREAD

**Issue by nockstarr** [Just-Some-Bots/MusicBot#503]
Hi, I'm experiencing a lot of lagging. Running on a Ubuntu VM with lots of resources(barely being used) and 80/80 bandwidth. In the bot console I can see the line printing a lot:
`[s16le @ 0x39cc7e0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.`
Everything else seems fine and I'm not experiencing any other problems..
I followed the wiki for installation. Any suggestions`?

Edit: Debug mode enabled do not give more info.

**Comment by grizzogor** [comment]
You can usually ignore this. It's displays this error on my system too. 
Here's my post on this topic. #426
