### ISSUE TITLE
Connect to deezer

### ISSUE THREAD

**Issue by paulsavoye** [Just-Some-Bots/MusicBot#504]
How can we connect the bot to a deezer account to get the full musics please ?

Thank's !9

**Comment by arunesh90** [comment]
> 6) Will not use the Services in any way or on any website that is associated or promotes in whatever manner the illegal or unauthorized use, streaming, download, or sharing of music and associated elements content, including but not limited to the Content provided by DEEZER.

tl;dr It's not gonna happen
Source: _https://developers.deezer.com/termsofuse_
