### ISSUE TITLE
Error: Python has either not been installed or not added to your PATH

### ISSUE THREAD

**Issue by lookitsducky** [Just-Some-Bots/MusicBot#508]
I have python installed and everything :(

**Comment by jayktaylor** [comment]
Follow the guides properly.
- Windows: https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Windows-7-and-up
- Ubuntu: https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Ubuntu-14.04-and-other-versions
- Debian: https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Raspberry-Pi-with-Raspbian-or-PC-with-Debian
- OSX: https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-OSX
- Docker: https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Docker

**Comment by arunesh90** [comment]
@jaydenkieran FYI, your debian link is wrong

**Comment by jayktaylor** [comment]
@arunesh90 it's a saved reply on github, will change ty
