### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by wouter-heerwegh** [Just-Some-Bots/MusicBot#511]
After some time the bot crashes and says something about a timeout

**Comment by arunesh90** [comment]
"says something about a timeout"
Don't expect help if you don't supply us with actual info about the crash, like a log or printscreen/screenshot of the console

**Comment by wouter-heerwegh** [comment]
Yeah, sorry closed the cmd to soon, forgot to screenshot. Haven't let it run for that long since. I will provide it as soon as i get it again
