### ISSUE TITLE
Error on Start up

### ISSUE THREAD

**Issue by ayeitzjeter** [Just-Some-Bots/MusicBot#513]
No module named 'aiohttp'
Attempting to install dependencies...
Collecting discord.py[voice](from -r requirements.txt %28line 1%29)
  Could not fetch URL https://pypi.python.org/simple/discord.py/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645) - skipping
  Could not find a version that satisfies the requirement discord.py[voice](from -r requirements.txt %28line 1%29) (from versions: )
No matching distribution found for discord.py[voice](from -r requirements.txt %28line 1%29)

You may need to run as admin to install dependencies.

C:\Users\Batman\Desktop\MusicBot-master (1)\MusicBot-master>

**Comment by jayktaylor** [comment]
Try installing this certificate on your system - https://support.comodo.com/index.php?/Knowledgebase/Article/GetAttachment/969/821026

**Comment by ayeitzjeter** [comment]
No module named 'aiohttp'
Attempting to install dependencies...
Collecting discord.py[voice](from -r requirements.txt %28line 1%29)
  Could not fetch URL https://pypi.python.org/simple/discord.py/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645) - skipping
  Could not find a version that satisfies the requirement discord.py[voice](from -r requirements.txt %28line 1%29) (from versions: )
No matching distribution found for discord.py[voice](from -r requirements.txt %28line 1%29)

You may need to run as admin to install dependencies.

C:\Users\Batman\Desktop\MusicBot-master (1)\MusicBot-master>

**Comment by ayeitzjeter** [comment]
no it still says this

**Comment by jayktaylor** [comment]
Strange. Can you try using this command in a command prompt in your Musicbot folder? You can open lazy_cmd.bat to open a command prompt there for you. `pip install --trusted-host pypi.python.org -r requirements.txt`

**Comment by ayeitzjeter** [comment]
Microsoft Windows [Version 10.0.10240](c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Batman\Desktop\MusicBot-master (1)\MusicBot-master>pip install --trusted-host pypi.python.org -r requirements.txt
Collecting discord.py[voice](from -r requirements.txt %28line 1%29)
  Downloading discord.py-0.11.0.zip (436kB)
    100% |################################| 440kB 6.6MB/s
Collecting youtube-dl (from -r requirements.txt (line 2))
  Downloading youtube_dl-2016.8.17-py2.py3-none-any.whl (1.4MB)
    100% |################################| 1.4MB 3.3MB/s
Requirement already satisfied (use --upgrade to upgrade): pip in c:\users\batman\appdata\local\programs\python\python35-32\lib\site-packages (from -r requirements.txt (line 3))
Collecting cffi==1.6.0 (from -r requirements.txt (line 4))
  Downloading cffi-1.6.0-cp35-none-win32.whl (145kB)
    100% |################################| 153kB ...
Collecting aiohttp<0.22.0,>=0.21.0 (from discord.py[voice]->-r requirements.txt (line 1))
  Downloading aiohttp-0.21.6-cp35-cp35m-win32.whl (237kB)
    100% |################################| 245kB 6.6MB/s
Collecting websockets==3.1 (from discord.py[voice]->-r requirements.txt (line 1))
  Downloading websockets-3.1.tar.gz
Collecting PyNaCl==1.0.1 (from discord.py[voice]->-r requirements.txt (line 1))
  Downloading PyNaCl-1.0.1-cp35-none-win32.whl (103kB)
    100% |################################| 112kB 6.6MB/s
Collecting pycparser (from cffi==1.6.0->-r requirements.txt (line 4))
  Downloading pycparser-2.14.tar.gz (223kB)
    100% |################################| 225kB 6.5MB/s
Collecting chardet (from aiohttp<0.22.0,>=0.21.0->discord.py[voice]->-r requirements.txt (line 1))
  Downloading chardet-2.3.0.tar.gz (164kB)
    100% |################################| 174kB 6.5MB/s
Collecting six (from PyNaCl==1.0.1->discord.py[voice]->-r requirements.txt (line 1))
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: chardet, aiohttp, websockets, pycparser, cffi, six, PyNaCl, discord.py, youtube-dl
  Running setup.py install for chardet ... done
  Running setup.py install for websockets ... done
  Running setup.py install for pycparser ... done
  Running setup.py install for discord.py ... done
Successfully installed PyNaCl-1.0.1 aiohttp-0.21.6 cffi-1.6.0 chardet-2.3.0 discord.py-0.11.0 pycparser-2.14 six-1.10.0 websockets-3.1 youtube-dl-2016.8.17
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\Batman\Desktop\MusicBot-master (1)\MusicBot-master>

**Comment by ayeitzjeter** [comment]
im done it and this is what i got

**Comment by jayktaylor** [comment]
Okay then it was successful, now just run your bot.

**Comment by ayeitzjeter** [comment]
It work thank you
