### ISSUE TITLE
Rate-limiting !play

### ISSUE THREAD

**Issue by kindlyfire** [Just-Some-Bots/MusicBot#514]
It would be nice to be able to rate-limit the !play command. The rate-limit would be bigger (you can add more songs) if the queue is short, and shorter (you can add less songs) when the queue is long.

An option to disable the "!play" command entirely if the queue is X songs or minutes long would be nice as well.

This would prevent people from adding a play-list with a big amount of songs in it and force an admin to !clean it.

**Comment by link2110** [comment]
This is already a thing with permissions. Use the `MaxSongs` setting in `permissions.ini` on the `Default` group to limit the number of songs somebody can queue.

**Comment by ImthePeach** [comment]
Prob's can be closed.
