### ISSUE TITLE
"That video cannot be played."

### ISSUE THREAD

**Issue by connortehhall** [Just-Some-Bots/MusicBot#516]
Hey, I'm just wondering if I can fix this issue that I'm having.
whenever i do !play _url_, it says "That video cannot be played", why?

**Comment by arunesh90** [comment]
Can be because of several reasons such as copyright, taken down, only playable in a specific country/region etc

**Comment by connortehhall** [comment]
But i've been able to play these in the past

**Comment by arunesh90** [comment]
check your console for the reason why it doesn't play
