### ISSUE TITLE
Filter songs with bad words in title?

### ISSUE THREAD

**Issue by LBUlises** [Just-Some-Bots/MusicBot#520]
Basically the title, trying to get this to run for a streamer and we don't want it to play songs (with bad words in title) that could get the streamer banned.

**Comment by barringtome18** [comment]
how tf is the bot gonna know the lyrics to the song XD its not like they come embbeded in the TY link wtf

**Comment by arunesh90** [comment]
title !== lyrics

**Comment by LBUlises** [comment]
Yes, not the lyrics the title. I was thinking since the bot Lists the title for youtube videos if it could also blacklist them if they have bad words from the various blacklists online.
