### ISSUE TITLE
Play with keyword arguments

### ISSUE THREAD

**Issue by noahbkim** [Just-Some-Bots/MusicBot#522]
While the `play` YouTube search is nice, I think the `play` command with keyword arguments would be better suited to searching the downloaded music library since the `search` command can already pull music off YouTube. I was wondering if this could be added as at least a configurable option, if not a full change to the `play` command.

_Thanks for the great software!_

**Comment by jayktaylor** [comment]
I'm not 100% sure what you're asking here, can you reiterate?
