### ISSUE TITLE
Announce the autoplaylist

### ISSUE THREAD

**Issue by insert3coins** [Just-Some-Bots/MusicBot#526]
so how do i get it to announce the autoplaylist songs?

cheers

**Comment by jayktaylor** [comment]
There is (currently) no configurable option to enable autoplaylist songs being announced in chat the same way that they would be if a song was played normally.

**Comment by insert3coins** [comment]
hrm anyway to add something in ?

**Comment by ImthePeach** [comment]
Bork will be adding this in as an option that will be configurable in the options.ini file. @jaydenkieran pls label as planned feature.

**Comment by OiYouYeahYou** [comment]
Any plans on this?

**Comment by sceather** [comment]
I didn't see it in options and was just wondering if this is still planned? I currently use the bot only with an autoplaylist and this would be a nice addition.
