### ISSUE TITLE
Playlist Hot-loading and selections

### ISSUE THREAD

**Issue by LaxSlash** [Just-Some-Bots/MusicBot#527]
It would be nice if there was a way to hot-reload the playlist with restarting the bot. It'd also be nice if a server could select from multiple playlists on the bot to play from (in the case of multi-server bots).

**Comment by ImthePeach** [comment]
Soon and probably soon.
I assume the first part is reloading/saving the queued songs for is the bot dies or you need to restart it for some reason. #190

**Comment by LaxSlash** [comment]
Sorry, I'm an idiot. I meant without restarting the bot :facepalm:
