### ISSUE TITLE
Can't play youtube links?

### ISSUE THREAD

**Issue by sigvaldr** [Just-Some-Bots/MusicBot#528]
It seems to throw this error when it tries to play some of the songs on my autoplaylist, as well as from youtube requests. Soundcloud links work fine though. I don't believe i'm missing a req or anything, but I can't seem to fix it.

Error:
`[Command] 142076624072867840/Iwan (!play https://www.youtube.com/watch?v=F0u90QZLjl8)
[Download] Started: https://www.youtube.com/watch?v=F0u90QZLjl8
[Download] Complete: https://www.youtube.com/watch?v=F0u90QZLjl8
[Command] 142076624072867840/Iwan (!skip)
Guessed Channel Layout for  Input Stream #0.0 : stereo
[abuffer @ 0xaab140] Unable to parse option value "(null)" as sample format
    Last message repeated 1 times
[abuffer @ 0xaab140] Error setting option sample_fmt to value (null).
[graph 0 input from stream 0:0 @ 0xaaa700] Error applying options to the filter.
Error opening filters!
`

**Comment by ImthePeach** [comment]
Does it still play the songs that are requested?

**Comment by jayktaylor** [comment]
It appears to be an issue with older versions of `ffmpeg`, try and use a newer version (http://stackoverflow.com/a/38690118).
