### ISSUE TITLE
AutoPlaylist queuing songs before queue clear

### ISSUE THREAD

**Issue by codebasu** [Just-Some-Bots/MusicBot#53]
Tested this with Borked before, same issue is reproducible on Numpty. 

Have autoplaylist enabled, queue a few songs, when reduced to the last song in queue, and then queue another song it will play an autoplaylist song in between them.

 Ideally autoplaylist should be working to where queue is completely clear and finished before playing from there.

**Comment by imayhaveborkedit** [comment]
This was because of the predownloading of the next song thing.  I was considering other ways to fix this, but it's not a high priority thing.
