### ISSUE TITLE
Operation Not Permitted Possible Fix?

### ISSUE THREAD

**Issue by xXBuilderBXx** [Just-Some-Bots/MusicBot#531]
So i recently started using discord alot because it is a whole lot better than skype and found out this awesome project that you have developed which works supprisingly very well. Although this issue has been hinted at many times there might be a possible fix for this. My issue is that on a 50/50 chance the hosting cloud9 blocks the script from working apparently its a UDP issue - https://github.com/SexualRhinoceros/MusicBot/issues/38

Whenever you do !play it has a 50/50 chance of encountering this error sometimes it works perfectly other times it constantly breaks.

**Comment by jayktaylor** [comment]
Cloud9 blocks UDP packets. This isn't something we can fix.
