### ISSUE TITLE
Songs won't stop playing

### ISSUE THREAD

**Issue by IeuanK** [Just-Some-Bots/MusicBot#534]
Queue up a song; it plays normally. Then after it's done it'll stop playing but the bot won't recognize this. Queuing up another song says it's queued but won't start playing it. Can't do !resume because it's not paused, can't do !pause because it's not playing.

**Comment by AleanaA** [comment]
wut

**Comment by ImthePeach** [comment]
I'm with Conner on this 'wut?' question. Can you somehow explain this a bit better or provide images?

**Comment by IeuanK** [comment]
There's sadly not much else I can say, really..

What happens is this;
- Bot connects
- Bot starts autoplaying music fine, keeps doing so as long as it's untouched
- Queue up song, works fine
- First queued up song ends, bot stops playing music
- Queue up another song and it'll say it's queued up but won't play immediately, !pause and !resume both don't work. Bot thinks it's still playing but the song has ended/no more audio

**Comment by jayktaylor** [comment]
Are you using the latest `master` version of the bot?

**Comment by IeuanK** [comment]
Yes, I downloaded the latest version 3 days ago

**Comment by ImthePeach** [comment]
Did you also make sure you ran update_deps.bat? I'm not promising this will fix it but might as well give it a go.

**Comment by IeuanK** [comment]
I have updated the dependencies, the script says they're all up to date
