### ISSUE TITLE
The bot dies.

### ISSUE THREAD

**Issue by nl-tata** [Just-Some-Bots/MusicBot#535]
![image](https://cloud.githubusercontent.com/assets/10136563/18025467/3e91daa2-6bf0-11e6-9a6d-6157f9ac318e.png)
line numbers may be off. ehh. Fix it?

**Comment by Fuyukai** [comment]
Terrible font

**Comment by nl-tata** [comment]
I had to have the font like that for another project I am working on. Pretty much, I have my reasons, but I didn't want to have it like that.

**Comment by ImthePeach** [comment]
What happened before this error that caused the error?

**Comment by nl-tata** [comment]
The bot was just running as normal as far as I can tell. Just normal usage.
I can give a longer error the next time it occurs.

**Comment by 88chrisuk** [comment]
I'm getting the exact same problem right now. Hosted on Windows Server 2012. Tried updating but still no luck. The only thing that resolves this is restarting the bot on discord.
![musicbot](https://cloud.githubusercontent.com/assets/21123886/18144476/c2539ab6-6fbe-11e6-97be-93c54463a6e2.PNG)

**Comment by imayhaveborkedit** [comment]
@HinksUK It's not the same problem. What you have is a discord.py issue.  Websocket keepalive threads weren't being properly closed, and the version of discord.py on pipy (pip) hasn't been updated yet.  

As for the original problem, its youtube_dl being bad.  Nothing I can do about it failing randomly.

**Comment by nl-tata** [comment]
Can you make it restart or continue the queue? It essentially breaks the
bot, forcing a restart. And if someone isn't always paying attention, that
can mean quite a lot of downtime.

**Comment by xXBuilderBXx** [comment]
Yea it happens to me aswell a !restart always fixes it :)

**Comment by xNanochip** [comment]
I'm getting this issue as well, and as the above said, could you possibly catch the exception and do a restart if this occurs?

**Comment by ImthePeach** [comment]
@tatatat0 Queue serialization is available in the review branch now.  When the bot is restarted after it gets shutdown/dies the queue it had when it was last running is restored.

**Comment by ImthePeach** [comment]
@xNanochip Review branch also has many more Sanity checks and better logging system. These features are still being worked on and are coming soon.

**Comment by xNanochip** [comment]
@ImthePeach Been testing out the Review branch and it seems to disconnect every hour or so. No errors in the console, however, just random disconnect. Going to revert back to the normal branch.
