### ISSUE TITLE
AttributeError: '' object has no attribute 'headers'

### ISSUE THREAD

**Issue by deriando** [Just-Some-Bots/MusicBot#536]
Traceback (most recent call last):
  File "run.py", line 163, in main
    m = MusicBot()
  File "C:\Games\Server\MusicBot-1.9.5\musicbot\bot.py", line 90, in **init**
    self.headers['user-agent'] += ' MusicBot/%s' % BOTVERSION
  File "C:\Users\cr8ti\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 264, in **getattr**
    raise AttributeError(msg.format(self.**class**, name))
AttributeError: '<class 'musicbot.bot.MusicBot'>' object has no attribute 'headers'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F01AFED128>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F01C136BE0>
Cleaning up... Done.

**Comment by jayktaylor** [comment]
You're using an outdated version of the bot. Update using the guides.

**Windows** - https://goo.gl/ES5HNr
**Linux (Ubuntu)** - https://goo.gl/odqx0J
**Linux (Raspbian)** - https://goo.gl/xcE2aW
**Linux (Debian Jessie)** - https://goo.gl/abgTIR
**Mac** - https://goo.gl/LNfJUw
**Docker** - https://goo.gl/l9v0rM
