### ISSUE TITLE
Bot keep giving error messages.

### ISSUE THREAD

**Issue by CaraOnTheRadio** [Just-Some-Bots/MusicBot#537]
It seems to slow my pc a tiny bit too what should i do?
![screenshot027](https://cloud.githubusercontent.com/assets/19749390/18029283/0c1edd6e-6c94-11e6-8f0e-8ebab9b64713.jpg)

**Comment by ImthePeach** [comment]
You can ignore these errors. It's just ffmpeg complaining about something, these errors will be 'blocked' in coming updates, and these errors popping up shouldn't have any effect on your computers speed.
