### ISSUE TITLE
How to add extra code

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#538]

**Comment by jayktaylor** [comment]
The bot you're coding is **Javascript**, the MusicBot is coded in **Python**. You can't do this.

**Comment by ghost** [comment]
.

**Comment by byronvanstien** [comment]
Yes @Zedom it's pretty easy to translate it, you just throw it into bing translate and translate from japanese to spanish and it'll pop out python code in a heartbeat

**Comment by ghost** [comment]
Your sarcasm is needed elsewhere, friend.
