### ISSUE TITLE
Feature Request: Take input audio from local device

### ISSUE THREAD

**Issue by thorsteneb** [Just-Some-Bots/MusicBot#539]
Feature Request to have MusicBot take input audio from a local audio recording device. 

The use case is to "pipe" sound in that comes from programs running locally, for example:
- Syrinscape for sound effects
- Aimp for music from local files

On Windows, an example of a recording device is that created by Virtual Audio Cable. The local program playing sound is set to output to, say, Line 1, and the bot takes input from Line 1 and outputs to the Discord channel.

I don't know how audio recording devices function in OSX and Linux. I'd have to think along similar lines, though.

**Comment by ImthePeach** [comment]
The bot will have local file playing support soon. Its a planned feature #168

**Comment by jayktaylor** [comment]
This would be extremely difficult to do, however as Peach mentioned, local file support is coming soon :tm:
