### ISSUE TITLE
Navigating MusicBot

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#540]
Simple question for this beginner: where could codes for bot responses be stored? 

@client.event
@asyncio.coroutine
def on_message(msg):
    if msg.content == "Hi":
         yield from bot.send_message(msg.channel, "hi")

Stuff like this... I'm not very familiar with Python but I know a thing here and there, no need to spoonfeed, just need to know where I should begin.

**Comment by jayktaylor** [comment]
We don't help with modifying the code, but MusicBot uses the discord.py library, so you should ask for help in the Discord channel for it in the Discord API server: https://discord.gg/KZBHSxz
