### ISSUE TITLE
Enqueued [Electro] Nitro Fun - Cheat Codes [Monstercat Release] to be played. Position in queue: Up next!

### ISSUE THREAD

**Issue by Xshoepe** [Just-Some-Bots/MusicBot#541]
I don't know what this means, but it's not playing anything from the music bot. pls help!

**Comment by ImthePeach** [comment]
Does it show a green ring around its user avatar in the voice chat? If it does that means it is playing but you have something audio wise wrong on your discord application messed up. Check your audio levels, make sure you didn't mute the bot, etc.

**Comment by Xshoepe** [comment]
No, it's not playing anything because it doesn't have the green ring.

**Comment by ImthePeach** [comment]
Whats your cmd console look like when you use a play command? Screenshot preferable

**Comment by jayktaylor** [comment]
As it's been 19 days without a reply to Peach's question, I'll close this and assume it's resolved. Re-open if not.
