### ISSUE TITLE
[REQUEST]Option to pause between songs and unmute.

### ISSUE THREAD

**Issue by mawkews** [Just-Some-Bots/MusicBot#545]
After the song is over pause for 30 seconds unmute everyone then play the next song and mute. Also another option to skip the wait time.

**Comment by link2110** [comment]
What use case do you have for this, instead of just doing it manually? Seems unnecessary and will only be used by you.

**Comment by ImthePeach** [comment]
What link said. This type of a request is a request that would be made only by you or by such a minority that making it a feature would not be reasonable. Something along the lines of this matches the case of this request.

![image](https://cloud.githubusercontent.com/assets/17447156/18075169/b37dc1c8-6e2f-11e6-9525-569569a1c248.png)

**Comment by jayktaylor** [comment]
This is too "personalised" to ever happen. Learn Python and code it for yourself.
