### ISSUE TITLE
YouTube_dl supported sites list has been taken off FAQ

### ISSUE THREAD

**Issue by LittleEndu** [Just-Some-Bots/MusicBot#548]
The !play command explanation references FAQ as the source but it has been removed from the FAQ

**Comment by jayktaylor** [comment]
Sorry. The entire wiki went through a rewrite today. I have re-added that FAQ.
https://github.com/SexualRhinoceros/MusicBot/wiki/FAQ#what-sites-can-the-bot-play-music-from
