### ISSUE TITLE
How to make te Music bot keep playing when the owner is offline

### ISSUE THREAD

**Issue by RealMonkeyDAce** [Just-Some-Bots/MusicBot#558]
hello rhineceros really great program really thanks but i only have 1 question is there a way to let the bot stay in my server and play music when i am offline (the owner)

**Comment by byronvanstien** [comment]
You ask the code very nicely and if you say please it'll work while you're offline

**Comment by arunesh90** [comment]
If you mean that the bot still runs while your computer is offline, then no.

Otherwise Google would be ran on thin air

**Comment by ImthePeach** [comment]
I will go ahead and assume you are running this on your own computer. The bot can still continue to play if you have your discord client closed/you are offline, as long as the cmd/terminal is still running. If you shut your computer down, make it hibernate, or sleep that will cease the operation of the bot. The only way to avoid this is by investing in a dedicated server. If you decide you want to do that check out our [Ubuntu guide](https://github.com/SexualRhinoceros/MusicBot/wiki/Guide-for-Ubuntu)

**Comment by jayktaylor** [comment]
There is information at the bottom of the [Windows guide](https://github.com/SexualRhinoceros/MusicBot/wiki/Guide-for-Windows) regarding why the bot doesn't work if the computer is offline etc, and a solution to this.
