### ISSUE TITLE
probleme system firewall or anti-virus firewall.

### ISSUE THREAD

**Issue by shaille** [Just-Some-Bots/MusicBot#560]
![ss 2016-09-02 at 04 58 46](https://cloud.githubusercontent.com/assets/19372849/18208169/a0276384-712e-11e6-9788-b736e7f794e1.png)

so i have this probleme with the bot. this is the first time it happens after 6 or 7 months of use
i don't have anti-virus and don't anti-virus firewall....

**Comment by jayktaylor** [comment]
If you're still having this problem, send a screenshot of your console window when this error occurs. Make sure you are using the latest version of the bot from `master`.
