### ISSUE TITLE
Restart command causes repeats in logs

### ISSUE THREAD

**Issue by brawaru** [Just-Some-Bots/MusicBot#563]
![image](https://cloud.githubusercontent.com/assets/10401817/18222675/8cb668dc-71c8-11e6-91e3-47fbb15e2f80.png)

**Comment by imayhaveborkedit** [comment]
Yeah I just noticed this today.

**Comment by jayktaylor** [comment]
https://github.com/SexualRhinoceros/MusicBot/commit/fde744c5a7c97543966d668046b07b7bdedc5d98
