### ISSUE TITLE
Duration of audio files is 0:00

### ISSUE THREAD

**Issue by haolink** [Just-Some-Bots/MusicBot#564]
Hi RhinoBot team,

first of all - your bot is amazing. :+1: 

I run it on a server and we also created a little semi-public music folder (as in: the bot can access it other people require credentials) - as the bot has no troubles to play standard audio files it works amazingly well. There's just a little bug. It will always claim the length of the file is 0:00 - and as of such it's coming up with negative remaining times until a certain song plays.

Replies like this are well possible:
`Enqueued 053 Route 8 to be played. Position in queue: 1 - estimated time until playing: -1 day, 23:59:39`

And yeah, that's obviously wrong ^^

**Comment by nightpool** [comment]
ran into this today as well! 

![image](https://user-images.githubusercontent.com/233815/38530721-07a04a44-3c3a-11e8-85e5-200cfbbad047.png)

**Comment by amit177** [comment]
If this is still an issue in the latest version, please open a new issue.
