### ISSUE TITLE
Cant update dependencies because of my path to python

### ISSUE THREAD

**Issue by BlazS14** [Just-Some-Bots/MusicBot#565]
C:\Users\Blaž\AppData\Local\Programs\Python that is my path to python and any time i try to update pip or things like that i get an error with the 'ž' character in the file path ''UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 57083: invalid start byte''. is there any way i can manually update the dependencies or am i screwed?

**Comment by jayktaylor** [comment]
This isn't a problem with the bot, and is more a problem the way that Python encodes text in the console, really. The next minor version of Python has made `UTF-8` encoding default on Windows, so these issues shouldn't happen. Feel free to give the pre-release version of Python 3.6 a try (https://www.python.org/downloads/release/python-360b1/). Other than that, I'm not sure what other potential solutions to give you.
