### ISSUE TITLE
normalization

### ISSUE THREAD

**Issue by insert3coins** [Just-Some-Bots/MusicBot#569]
how do i apply the normalization in the ffmpeg?

because some songs on youtubes are quieter than others etc

Cheers

**Comment by Xerionty** [comment]
Please have a look over [here](http://superuser.com/questions/323119/how-can-i-normalize-audio-using-ffmpeg).

**Comment by insert3coins** [comment]
that being said.. what file do i edit in musicbot? 

i can look at the docs, but the musicbot calls ffmpeg what part do i need to edit to add commandlines?

Cheers

**Comment by Xerionty** [comment]
If you read carefully you noticed that ffmpeg is third-party software.
Ways to "edit" it are described in the link i posted.

> I created a Python script to normalize media files, available on PyPi as well. You simply:
> 
> download ffmpeg (choose a static build)
> put the ffmpeg executable in your $PATH by either adding it in, for example, /usr/local/bin, or adding its >directory to $PATH
> To install: Either run pip install ffmpeg-normalize or in the source code, run python setup.py install.
> Once the script is installed, use ffmpeg-normalize
> On Ubuntu / Debian:
> 
> sudo apt-get install ffmpeg python-pip
> sudo pip install ffmpeg-normalize
> 
> For example, to normalize the audio of every MP4 file to 0 dB, run this:
> 
> ffmpeg-normalize *.mp4 
> It'd output WAV files with the normalized audio, using the prefix normalized-. You have to merge the audio back into the original files. See this answer on how to do it.

**Comment by insert3coins** [comment]
i think you don't get what i am asking, this musicbot itself uses ffmpeg does it not? and if so somewhere int here is the function to call it, i'm asking where, so i can add the propper for normalization

**Comment by jayktaylor** [comment]
Yes, the MusicBot does use ffmpeg. We won't help you modify the code though. If we did that we'd have to help the hundreds of other people that ask for code help regularly. 

We have a separate issue about sound normalisation here which you might want to read: https://github.com/SexualRhinoceros/MusicBot/issues/156
