### ISSUE TITLE
Bot doesn't login/go online

### ISSUE THREAD

**Issue by JFulweber** [Just-Some-Bots/MusicBot#572]
I've set the token and the owner ID options.ini, and when I run the runbot.bat it says "ok lets hope it worked" and nothing happens. It doesn't go online and work.  Is there something I'm missing here?

**Comment by jayktaylor** [comment]
Did you follow the [guide for your system](https://github.com/SexualRhinoceros/MusicBot/wiki)?

**Comment by JFulweber** [comment]
Yeah

**Comment by Xerionty** [comment]
A screenshot from your **options.ini** and a log from your **CMD Console** could help us out troubleshooting.

**Comment by jayktaylor** [comment]
As you haven't replied in over a week, I am going to assume this issue was resolved. If not, let me know.
