### ISSUE TITLE
Can not load Opus Lib

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#573]
`Traceback (most recent call last):
  File "run.py", line 162, in main
    from musicbot import MusicBot
  File "/Users/Person/Desktop/MusicBot-master/musicbot/__init__.py", line 1, in <module>
    from .bot import MusicBot
  File "/Users/Person/Desktop/MusicBot-master/musicbot/bot.py", line 38, in <module>
    load_opus_lib()
  File "/Users/Person/Desktop/MusicBot-master/musicbot/opus_loader.py", line 17, in load_opus_lib
    raise RuntimeError('Could not load an opus lib. Tried %s' % (', '.join(opus_libs)))
RuntimeError: Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib
logout
`
This is what happens when I try to run musicboat. Any help? I'm very new to all this.

**Comment by Xerionty** [comment]
Please run **update_deps.bat** from your MusicBot folder and make sure **requirements.txt** is in there.

**Comment by ghost** [comment]
I'm on a mac and I don't know what program to run update_deps.bat on? What should I download to make it work? Sorry again, very new to this.

**Comment by ghost** [comment]
So I assume for Mac i'd do update_macdeps.command which I did earlier as per the how to guide instructed but it still comes out the same as my first comment.

Here's what it says when i put update_macdeps.command into the terminal:

`Persons-MacBook-Pro:~` Person$ /Users/Person/Desktop/MusicBot-master/update_macdeps.command ; exit;
Ignoring cffi: markers "sys_platform == 'win32'" don't match your environment
Requirement already up-to-date: discord.py[voice] in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: youtube_dl in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: pip in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: aiohttp<0.22.0,>=0.21.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from discord.py[voice]->-r requirements.txt (line 1))
Requirement already up-to-date: websockets==3.1 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from discord.py[voice]->-r requirements.txt (line 1))
Requirement already up-to-date: PyNaCl==1.0.1 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from discord.py[voice]->-r requirements.txt (line 1))
Requirement already up-to-date: chardet in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from aiohttp<0.22.0,>=0.21.0->discord.py[voice]->-r requirements.txt (line 1))
Requirement already up-to-date: six in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from PyNaCl==1.0.1->discord.py[voice]->-r requirements.txt (line 1))
Requirement already up-to-date: cffi>=1.1.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from PyNaCl==1.0.1->discord.py[voice]->-r requirements.txt (line 1))
Requirement already up-to-date: pycparser in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from cffi>=1.1.0->PyNaCl==1.0.1->discord.py[voice]->-r requirements.txt (line 1))
logout

[Process completed]
'
I have the requirements text and everything so I don't know what I did wrong.

**Comment by imayhaveborkedit** [comment]
One of the OSX steps is to install a few things with brew, one of which is opus.  The command is `brew install opus`.  If you didn't do that or it says brew isn't a command, then you seem to have skipped a step in the OSX guide.
