### ISSUE TITLE
Help on skype?

### ISSUE THREAD

**Issue by Muhncheez** [Just-Some-Bots/MusicBot#574]
Hey SexualRhinoceros, just wondering if I could add you on skype because I have a few questions regarding custom playlists that play if nothing else is playing, and a few more. I can explain further on skype if need be. 

Thanks in advance
- Muhncheez

**Comment by Xerionty** [comment]
Wouldn't it be better to discuss things like that here so that others have a resource too?

**Comment by arunesh90** [comment]
This is not a personal helping service.
If you want help, just ask here or at the Discord help server
