### ISSUE TITLE
Custom Playlists/ other

### ISSUE THREAD

**Issue by Muhncheez** [Just-Some-Bots/MusicBot#576]
Hello, Just wondering how (if at all) I could have a custom playlist that plays instead of the random one that plays until somones requests a song.

Also, is there any way I can "blacklist" people from entering commands such as !skip, !play, etc.

Thanks in advance

**Comment by Xerionty** [comment]
You clearly did not read the **README.md**.

As for the custom playlist; this could be found in the folder **config** the file you will need to edit is **autoplaylist.txt**.

As for the rights; I would suggest you to read the README and edit the **permissions.ini** also to be found in the config folder.

**Comment by jayktaylor** [comment]
[Read this](https://github.com/SexualRhinoceros/MusicBot/wiki/Configuration#useautoplaylist) and [this](https://github.com/SexualRhinoceros/MusicBot/wiki/Permissions).
