### ISSUE TITLE
Download error on Windows 7

### ISSUE THREAD

**Issue by istoleyurballs** [Just-Some-Bots/MusicBot#578]
Hi,

I have 2 computers, one with win 10 and one with win 7.
With win 10 the bot work perfectly without any problem but with win 7 i got this error sometimes: http://pastebin.com/7udNizYT
I think its from youtube_dl.
After this error no more music but the bot still working fine.

**Comment by imayhaveborkedit** [comment]
Yeah this is one of the random errors that can happen sometimes.  For whatever reason youtube-dl just fails and everything goes to hell.  I think i've managed to sort out the voice connection bugs so this one is next on the list.

**Comment by istoleyurballs** [comment]
Nice !
Thanks for tout reactivity !

**Comment by MattBSG** [comment]
Hi @JesusCrie , is this still happening for you?

**Comment by istoleyurballs** [comment]
@MattBSG Well, it was a year ago, now I create my own bots in Java. Soooo i don't know ¯\_(ツ)_/¯

**Comment by jayktaylor** [comment]
No problem. I’ll close this issue, thanks!
