### ISSUE TITLE
re: running the runbot mac command

### ISSUE THREAD

**Issue by Eretria** [Just-Some-Bots/MusicBot#587]
RuntimeError: Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib
logout
 help pls it says this when i start the bot

**Comment by jayktaylor** [comment]
You didn't `brew install opus`.

**Comment by Eretria** [comment]
How do i do that

**Comment by jayktaylor** [comment]
Read this entire page: https://github.com/SexualRhinoceros/MusicBot/wiki/Guide-for-OSX

**Comment by Surfice1** [comment]
When I do the whole command it says press return to install, and when I press it nothing happens.
