### ISSUE TITLE
Add max length

### ISSUE THREAD

**Issue by LaxSlash** [Just-Some-Bots/MusicBot#59]
A way to add the maximum length of a video, in seconds. To prevent users from entering 6 hour-10 hour things.

hardlimit: Allow leniancy undisclosed to this amount.
softlimit: The limit displayed to users in chat.

**Comment by imayhaveborkedit** [comment]
This is easy enough to do for things like youtube, but some things that youtube-dl supports doesn't have a duration field, so the bot won't know how long the song is.  I don't know how you would want to handle that, but I could add another option for either allowing or denying unknown length media.

**Comment by MattBSG** [comment]
`MaxSongLength` added with commit 136032363df9c5fe7fbed26cb0c0f26efd3cec73
