### ISSUE TITLE
Disable shuffling of the autoplaylist.txt

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#591]
Hello!

I would love to see a setting to play through the autoplaylist.txt in order when no songs are queued, rather than in a random order.

Thanks!

**Comment by LOTRotaconLOTR** [comment]
This will be awesome, for me bot loop same 10-20 song even if i have 50 of them, there is small chance for it to play new one and sometimes it play same song twice in a row.

**Comment by glenlivet99** [comment]
I like the option of having it play random songs instead of going in order. Perhaps revisit the algorithm that performs the random function?

**Comment by ghost** [comment]
Or it could be a configuration option as I mentioned in the original
thread.

**Comment by DethBringa** [comment]
definitely a setting. I love the idea of shuffle (once its a bit more shuffled and less repeatey), but a toggle option would be great.

**Comment by MattBSG** [comment]
Implemented in 650e60da7c0454b96d38391b538dea73be3dd57e and will be in the next release
