### ISSUE TITLE
ffmpeg debian8

### ISSUE THREAD

**Issue by xCuzImPro** [Just-Some-Bots/MusicBot#593]
My Fehler:
My language is German...

Options:
  Command prefix: !
  Default volume: 15%
  Skip threshold: 4 votes or 50%
  Now Playing @mentions: Disabled
  Auto-Summon: Enabled
  Auto-Playlist: Enabled
  Auto-Pause: Enabled
  Delete Messages: Enabled
    Delete Invoking: Disabled
  Debug Mode: Disabled
  Downloaded songs will be saved

Attempting to autojoin Musik in MC SoulForge
Attempting connection...
Connection established.

[Download] Started: https://www.youtube.com/watch?v=mHxOltrMfX8
[Download] Complete: https://www.youtube.com/watch?v=mHxOltrMfX8
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at /root/MusicBot/musicbot/player.py:221> exception=ClientException('ffmpeg/avconv was not found in your PATH environment variable',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 405, in create_ffmpeg_player
    p = subprocess.Popen(args, stdin=stdin, stdout=subprocess.PIPE, stderr=stderr)
  File "/usr/local/lib/python3.5/subprocess.py", line 947, in **init**
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/root/MusicBot/musicbot/player.py", line 256, in _play
    after=lambda: self.loop.call_soon_threadsafe(self._playback_finished)
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 408, in create_ffmpeg_player
    raise ClientException('ffmpeg/avconv was not found in your PATH environment variable') from e
discord.errors.ClientException: ffmpeg/avconv was not found in your PATH environment variable

**Comment by Akuba-** [comment]
German:
Dir fehlt ffmpeg. Ich weiß nicht ob das ffmpeg packet für Debian inzwischen wieder funktioniert, versuch ffmpeg mal mit `apt-get install ffmpeg` zu installieren. Falls dies nit funktioniert wirst du wohl (so wie ich) ffmpeg selber kompilieren müssen. Schau dir dazu diese anleitung an: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

English:
You are missing ffmpeg. I am not sure if the debian package for ffmpeg does work again but try to install it with `apt-get install ffmpeg`. If this does not work you have to compile it yourself (like I had to do). Take a look at this guide: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

**Comment by xCuzImPro** [comment]
>  German:
> Dir fehlt ffmpeg. Ich weiß nicht ob das ffmpeg packet für Debian inzwischen wieder funktioniert, versuch >ffmpeg mal mit apt-get install ffmpeg zu installieren. Falls dies nit funktioniert wirst du wohl (so wie ich) >ffmpeg selber kompilieren müssen. Schau dir dazu diese anleitung an: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu 
> 
> English:
> You are missing ffmpeg. I am not sure if the debian package for ffmpeg does work again but try to >install it with apt-get install ffmpeg. If this does not work you have to compile it yourself (like I had to >do). Take a look at this guide: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

Hey, @Akuba- 
Danke für deine Antwort :)
Da es **nicht** mit apt-get install ffmpeg ging habe ich es mit der beschriebenen Anleitung versucht.
aber er hat glaube nix gemacht mit "hash -r" 

Meine Lösung..:
Ich hoste den aktuell auf einem Windows Server und da klappt alles:)
