### ISSUE TITLE
New to this

### ISSUE THREAD

**Issue by MrAmazingFlash** [Just-Some-Bots/MusicBot#598]
Everything seemed to be working fine, until I stopped using it for about an hour. At first i had a problem with its connection being timed out, or first it was 10060(?) and then it went to 10054. Fiddled with it, then it fixed itself and was finding the songs from the links once more, but now when it goes to play them in the chat, no actual sound comes forth. Says its playing the song just find, but no music or sound.

**Comment by jayktaylor** [comment]
Can you screenshot the error?

**Comment by jayktaylor** [comment]
I'm going to close this issue for now. Reply if you still have problems with a screenshot of your error(s).
