### ISSUE TITLE
Youtube Playlists won't play (all songs were over max duration (0s))

### ISSUE THREAD

**Issue by EroTwenty** [Just-Some-Bots/MusicBot#599]
Hi,

When I try to add a youtube playlist to the queue,
(Example : https://www.youtube.com/playlist?&list=PLURBlBqSzVmH8ZxBwnIiQgTDi7hbcA89k)
I get this error : No songs were added, all songs were over max duration (0s)

It could come from the config file where the "0" duration means infinite duration allowed.

This MusicBot is really epic, very nice work. I successfully installed it on my ArchLinux server.

**Comment by bANNji** [comment]
I have this same issue. Anyone got any ways to fix im still scrubbing the config files right now ill check back if i find anything.

**Comment by bdogrulz** [comment]
Also check the permissions.ini file that has it listed there

**Comment by betheshooter** [comment]
was this fixed? I am having this issue.

**Comment by spgill** [comment]
I'm also having this issue recently. Is there any known solution?

**Comment by anton-johansson** [comment]
Me too. Maybe re-open? I have added playlists before, with the same user, so I doubt it's permissions. Either way, a better error message would be nice. :)

**Comment by bdogrulz** [comment]
Try updating youtube.py and try. that worked for me

**Comment by betheshooter** [comment]
The the batch file that updates the bot. That fixed it for me

**Comment by bdogrulz** [comment]
So like run these if you're on ubuntu 
# Ubuntu 14.04(.*) LTS
python3.5 -m pip install --upgrade pip

# Ubuntu 16.04 LTS or higher
python3 -m pip install --upgrade pip
