### ISSUE TITLE
Autoplaylist cleared

### ISSUE THREAD

**Issue by brawaru** [Just-Some-Bots/MusicBot#601]
Tonight my ISP disabled internet. They want to redirect you to specific page, but because https, browser or any other program resets connection. So.. Bot tried to download songs via youtube-dl, but it returns error: 

```
ERROR: Unable to download webpage: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host> (caused by URLError(ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None),))
```

and bot removes song from playlist as unplayable. At morning I noticed, that autoplaylist was cleared 😀 There's no problem to restore playlist, because now bot puts removed song to other file, but it's annoying. Fix this, please :3

**Comment by DaFri-Nochiterov** [comment]
Sorry, code is invalid. I will fix it soon. 😟

**Comment by jayktaylor** [comment]
I feel like this is intended behaviour. If the bot can't play the song, it will remove it from the autoplaylist. It doesn't take into account what reason, it's just that if the song can't be downloaded, it will mark it as unplayable.

**Comment by FatRagdoll** [comment]
This has already happened to me twice after using the bot for 2 weeks on my Raspberry Pi 3. I'd be nice to be able to disable the auto-remove feature in the bot config file.
