### ISSUE TITLE
Weird errors thrown in terminal periodically

### ISSUE THREAD

**Issue by dannyvoid** [Just-Some-Bots/MusicBot#602]
This happens randomly but it doesn't _seem_ to be having any negative effects. So far it's just extra noise in my terminal. What's causing this?
![screenshot from 2016-09-13 10-35-41](https://cloud.githubusercontent.com/assets/12226555/18480701/40c6af20-799f-11e6-86de-831bd897815e.png)

**Comment by jayktaylor** [comment]
You can mostly ignore this. It shouldn't cause major issues, at most the voice connection might die, where you can just use the reconnect or restart command. These issues should be mostly negated in the next stable version of the bot (code changes are in review branch, but isn't recommended to use it currently)
