### ISSUE TITLE
Restart command not working

### ISSUE THREAD

**Issue by brawaru** [Just-Some-Bots/MusicBot#603]
Now restart command is not working. It stops process and wait before I press return in command prompt, then bot starting, but any you enter after this will be redirected to cmd and it looks like:

```
Joined chanell ....
git pull
Already up-to-dateDownload started: ...
```

Also, sometimes `Return` press causes Windows "Python has stopped working" dialog.

![image](https://cloud.githubusercontent.com/assets/10401817/18509356/5a16666a-7aa2-11e6-9b52-d0d8409fe74a.png)

**Comment by mdod** [comment]
Why did you run `git pull` after you started the bot...?

**Comment by Injusticecraft** [comment]
Same here
