### ISSUE TITLE
How to change the song save location

### ISSUE THREAD

**Issue by Soneydom13** [Just-Some-Bots/MusicBot#606]
How do I change the song save location
I am using a raspberry pi and want to use an external HDD to store the songs

**Comment by jayktaylor** [comment]
For now wouldn't it make sense to place the entire bot on the external HDD and run it from there?

**Comment by alpha-tango-kilo** [comment]
@jaydenkieran that's exactly what I do at the moment. Raspberry Pi with the Music Bot on an external HDD.
