### ISSUE TITLE
RuntimeError: PyNaCl

### ISSUE THREAD

**Issue by k1n3t1c** [Just-Some-Bots/MusicBot#607]
RuntimeError: PyNaCl library needed in order to use voice

![image](https://cloud.githubusercontent.com/assets/20934051/18604856/1516ead4-7c51-11e6-97ed-5addc05fca5a.png)
![image](https://cloud.githubusercontent.com/assets/20934051/18604860/21c87a54-7c51-11e6-81fb-ade48355c1c4.png)

**Comment by ImthePeach** [comment]
ubuntu?

**Comment by k1n3t1c** [comment]
Realized someone upgraded to 16.04. Uninstalled the library and installed it back. Works fine.
