### ISSUE TITLE
Bot crashes on websocket closing

### ISSUE THREAD

**Issue by brawaru** [Just-Some-Bots/MusicBot#608]
![image](https://cloud.githubusercontent.com/assets/10401817/18614528/34d29fde-7dba-11e6-92d4-ec5b53d77e15.png)

**Comment by Eufranio** [comment]
Same.

**Comment by deansheather** [comment]
I mean, it lost connection to Discord. Some bots attempt to reconnect at intervals, some don't. If you want support for autoreconnect, make an issue asking for it. Otherwise, this is not a bug.
