### ISSUE TITLE
Unable to add the three PPAs on RPi 3B running Raspbian Jessie

### ISSUE THREAD

**Issue by rsylthe** [Just-Some-Bots/MusicBot#609]
So I'm a complete newbie when it comes to Linux, but wanted to try installing the MusicBot on my Pi.
When I got to the point in the installation guide for Raspbian where I have to add the three PPAs it completely stopped for me, as I get thrown this error:

```
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 167, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 105, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 595, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/jessie
```

I get a similar error for all three PPAs. I googled around a little bit and figured out how to add the PPAs manually to the sources.list file and how to add the PPA keys. Probably not a good idea, but worth experimenting a little bit.

This is what it looks like now:
![wh4fffe](https://cloud.githubusercontent.com/assets/22095159/18617969/b20adb8e-7ddc-11e6-9226-ce7e41550a11.png)
Reason the version is trusty on all of them is because all the PPAs supported that version. So there's that.

Kept pushing on with the installation guide and on the step for FFmpeg where I typed "sudo make" I get thrown a bunch of errors again, probably related the PPA?
Errors are similar to these. Hundreds of them:
![mtfldre](https://cloud.githubusercontent.com/assets/22095159/18618025/c79ec3ce-7ddd-11e6-8a20-9c4ddb1c9cb2.png)
![cp6f1hc](https://cloud.githubusercontent.com/assets/22095159/18618026/ca5ce4ba-7ddd-11e6-849d-22ebc7d73e6a.png)

Anyways, what I'm wondering is how to do this correctly. Is there a fix to installing the dependencies like the guide intend me to do?

**Comment by mdod** [comment]
Did you get this to work?

**Comment by rsylthe** [comment]
I got the bot running but its performance is absolutely horrible. Sound crackling and cutting out constantly, bot taking a long time to respond to commands and to start playing songs.

Short answer: I did not get it to work, still unable to add PPAs.

**Comment by mdod** [comment]
It _seems_ like those PPAs aren't needed at all. 

I had the MusicBot running on one of my Raspberry Pis and just installed it on another one to test my theory out. I received the same error you had when adding them and continued with the installation. The MusicBot is working fine and there are no sound issues or anything.

Also, you were installing Ubuntu packages on Raspbian, which while both Operating Systems are similar in certain respects, they are certainly not the same and those packages designed for Ubuntu might be your problem.

I believe the reason the PPAs aren't needed is that everything they would have added was installed later.
- Python 3.5 was installed
- FFmpeg was installed, along with its packages
- Libsodium was installed

**Comment by rsylthe** [comment]
The bot is up and running!

Reinstalled Raspbian and went through the installation process but skipped the PPAs this time.
Experiencing a few insignificant sound stutters from time to time, but I believe I also experience these when I had the bot running on my desktop - probably nothing I can do about it?

Anyways, bot is running fine regardless - thanks for the help!

**Comment by mdod** [comment]
> Copying from the tag in the help server

If your bot is lagging when playing music
- Check CPU/disk usage
- Can your PC/the VPS' bandwidth/speed handle the bot?
- Is there an issue on https://status.discordapp.com?
