### ISSUE TITLE
I can't add users in Default group to obtain permissions.

### ISSUE THREAD

**Issue by casi9095** [Just-Some-Bots/MusicBot#611]
I'm in Administrators Mode. I click right and then "copy ID", then I go to permissions.ini, I open it with Notepad ++ and then add the user ID after "UserList" under the group "default".
I put Userlist = 12345667880 . With a space between the "=" and the ID, and then another space for the next ID.
But when I'm in discord the users I added can't do commands, such as "!volume" up and down and "!pause" .
The bot works perfectly for me.

**Comment by jayktaylor** [comment]
You shouldn't add users to the default group. The default group is exactly as it says on the tin, default. All users will have the permissions of this group unless indicated otherwise. You shouldn't explicitly add IDs or roles in that group.

**Comment by imayhaveborkedit** [comment]
You can't add users or roles to the Default group, those options are ignored.  (Also spaces around the `=` don't matter)  If you want users to use certain commands, add those to the default group command whitelist.

**Comment by casi9095** [comment]
So, how do I allow a friend of mine in my server and voice channel to pause an change volume (for example?).
I understood now that the sentence with ";" and are written in green doesn't count for the program. Thank You.
But You said "add those to the default group command whitelist". **Those** who? The users ID's? Or the commands? The commands are already in command whitelist, but I don't understand otherwise.. I have to add the ID's after "whitelist commands"?

**Comment by jayktaylor** [comment]
Your default group should look exactly how it was when you downloaded the bot for the first time. If you want to add a specific command for all of your users to be able to use, add it in that group's whitelist. 

```
[Default] 
CommandWhitelist = play search skip
```

This would allow all of your users to use three commands, play, search, and skip. Just change the command whitelist as you see fit.

**Comment by casi9095** [comment]
So, you're telling me that I haven't to add the USERS to the group but I have to add the commands? Because my friends in Discord can't change volume or pause because the bot says that they aren't in default group. Casually in default group command whitelist there aren't these commands! ;)
But in a few words I have to add volume and pause and other users in my channel can do that?

**Comment by Andersmann** [comment]
Have the exact same problem!
Wanting one friend to get the same permissions as me (the owner), but all it says is that they are aren't in default group. Even though I have taken their IDs into another group in the permission file, it still doesn't work.
