### ISSUE TITLE
Restart on UbuntuServer

### ISSUE THREAD

**Issue by Matthanic** [Just-Some-Bots/MusicBot#614]
![chrome_2016-09-20_19-49-52](https://cloud.githubusercontent.com/assets/19475593/18682509/d21ba8d6-7f6c-11e6-97cc-da1315442d99.png)

Everytime someone tries to restart the bot that error shows up and the bot needs to be turned on manually again.

**Comment by LPArigma** [comment]
How'd you even set it up on your Ubuntu Server, not working for me

**Comment by mdragon159** [comment]
@Matthanic Out of curiosity, is this in a fresh terminal/tmux session, with the queue empty? And does the bot leave the voice channel or such inside the Discord server?

@LPArigma If you follow the Ubuntu guide, it's not really anything special. May need a different issue thread but I'd be happy to discuss it assuming you got most of the way through the guide (and the bot runs normally elsewhere)

**Comment by Matthanic** [comment]
@jawadmn Yep! I've tried restarting in multiple situations. And yes it does half the restart process just fine. Leave voice channel and etc. Turning back on seems to be the issue?

@LPArigma I used the ubuntu tutorial on the wiki page, though I did some things that were not on there. What exactly is not working for you? The bot altogether? Or for example an issue I had, the bot not playing music after summoning.

Sidenote: the rest of the entire bot works 100% fine. Just the restart function does not but really compared it's a minor issue. Would like it to work though so that others can restart it without me.

**Comment by ImthePeach** [comment]
> I used the ubuntu tutorial on the wiki page, though I did some things that were not on there. 

@Matthanic If you follow the guide to the T everything should work as expected. What did you do differently from the guide? I am unable to reproduce the issue you have.
