### ISSUE TITLE
I don't understand how to add the bot to a voice channel

### ISSUE THREAD

**Issue by AlamoMusic** [Just-Some-Bots/MusicBot#618]
Am I supposed to enter a command? If so, where?

**Comment by junhui-f** [comment]
!summon ?? unless you mean add bot to server
https://discordapp.com/oauth2/authorize?client_id=[BOT_ID_HERE]&scope=bot&permissions=66321471

**Comment by jayktaylor** [comment]
`!summon` makes the bot enter your voice channel. The bot should be in your server first. See https://github.com/SexualRhinoceros/MusicBot/wiki/FAQ#how-do-i-add-my-bot-account-to-a-server
