### ISSUE TITLE
Bot-managed "timeout" moderation feature request

### ISSUE THREAD

**Issue by OrdinatorStouff** [Just-Some-Bots/MusicBot#619]
Bot-managed "timeout" moderation feature request

Proposed feature: Add ability for the bot to moderate users by changing their role to a defined "mute" or "timeout" role for a temporary time before automatically restoring their previous role(s). It could be invoked manually by moderators like "!timeout @SomeUser 5" for a 5-minute timeout.

More importantly, however would be the bot's ability to use this feature automatically (when configured) to auto-moderate users that attempt to abuse banned search/title terms or specific blacklisted songs like defined in #249 and #520.

A very basic implementation of auto-moderation is a short (5 minutes or less) timeout for any attempted search/play of a blacklisted song or term. A much more advanced implementation (but not necessary) would have configurable quantity of repeat offenses in some configurable 'reset time-frame before triggering various timeout actions (ex: 1st offense warning, 2nd = 5 min timeout, 3rd = 30 min timeout, 4th = 2 hour timeout, 5th = indefinite timeout).

**Comment by deansheather** [comment]
Moderation features are not in the scope of a music bot. A music bot plays music, and doesn't moderate your server. Try [RH1-N0](https://github.com/Just-Some-Bots/ModTools/wiki/Main).
