### ISSUE TITLE
Blacklist, permissions and song limits

### ISSUE THREAD

**Issue by DzejBee** [Just-Some-Bots/MusicBot#62]
Hey, we at Lirik's Discord love your bot. Few things I wanted to ask if could be added:

**Blacklist** - We get a lot of trolls coming in and trolling with troll songs etc
**Commands** - I'd like to ask, if it would be possible to not let people use certain commands like volume, since it changed for everyone and again is a part of trolling
**Song Limit** - Perhaps time limit, but also an amount limit. We had a guy queue 120 songs.

Thanks again for the bot, it's great!

**Comment by LaxSlash** [comment]
The blacklist thing already exists (!blacklist), and the commands thing is being worked on. But I definitely like the idea about a song limit, as we had that issue too.

**Comment by DzejBee** [comment]
Ah, thanks. Time to pull out the ban hammer :)

**Comment by imayhaveborkedit** [comment]
User blacklist already exists, command permissions are comming soonish, and people have asked about song time limits/queue entry limit.  I guess that'll have to check playlists too.

**Comment by DzejBee** [comment]
Yeah, maybe make a command that turns playlist request on and off.

But thanks for the quick reply! :)

**Comment by deansheather** [comment]
This has been implemented in review.
