### ISSUE TITLE
Cannot run update_deps.bat

### ISSUE THREAD

**Issue by Pixeladed** [Just-Some-Bots/MusicBot#623]
Hey,
I'm trying to run update_deps.bat because i got the error: "Could not load opus lib" and an issue on here said that's what i needed to do. However, i keep getting this error: 

```
~ $ update_deps.bat
bash: update_deps.bat: command not found
```

and

```
~ $ bash update_deps.bat
update_deps.bat: line 1: @ECHO: command not found
update_deps.bat: line 3: REM: command not found
update_deps.bat: line 4: syntax error near unexpected token `('
update_deps.bat: line 4: `    IF "%PROCESSOR_ARCHITECTURE%" EQU "amd64" ('
```

I'm trying to run it on heroku vm

I also tried manual update with 
`pip install --upgrade -r requirements.txt`
but i still got the could not load opus lib error

**Comment by junhui-f** [comment]
`~ $` are you using Linux ? 
.bat files are for windows :) Make sure you are following the right installation guide.

**Comment by jayktaylor** [comment]
`.bat` files are for Windows.
`.sh` files are for Linux.
