### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by wsline** [Just-Some-Bots/MusicBot#627]
I can't seem to find a way around this issue... I am using a mac. Please help me!
![runtimeerror](https://cloud.githubusercontent.com/assets/22486379/18897135/a77f5bae-84e4-11e6-8012-06e2ced1f93c.png)

**Comment by wsline** [comment]
I followed this guide https://github.com/SexualRhinoceros/MusicBot/wiki/Guide-for-OSX.
Plus even the update_macdeps.command doesn't seem to resolve the issue.

**Comment by mdod** [comment]
Try `brew install opus`
