### ISSUE TITLE
Playlist dump not getting all tracks from soundcloud likes

### ISSUE THREAD

**Issue by Badtz13** [Just-Some-Bots/MusicBot#629]
I have used the !pldump command a few times to create auto playlists of my soundcloud likes, but now it is not getting all of them. On my soundcloud profile, it says that [I have over 200 likes](https://i.imgur.com/kPiE9GP.png), but when I make a playlist of my likes, it [does not grab all of them](https://i.imgur.com/5T4nQQA.png), leaving me with a shorter list.

**Comment by deansheather** [comment]
This is most likely an availability issue rather than an issue with the logic in the bot. Some tracks are not able to be streamed from SoundCloud - they may have a 30s preview or some other protection measure in place.

Could you please send a link so we could attempt to reproduce this?
