### ISSUE TITLE
More playlist control

### ISSUE THREAD

**Issue by LaxSlash** [Just-Some-Bots/MusicBot#63]
What about a way to more directly control songs in the playlist? Ie,

!removesong [#] | [videoName] | [queuedBy]
!skiptosong [#] | [videoName] | [queuedBy](Queued By would go directly to the first song queued by that user)
!cancelsong [#] | [videoName](Allows a user to cancel a song that they queued up %28different from !removesong, since it would only work on songs queued by the user running the command%29)

**Comment by MattBSG** [comment]
`remove [#]` added with #568

**Comment by StormCake** [comment]
What about `skiptosong` or `skipto` ?

**Comment by AutumnClove** [comment]
#1580 #1877  #2242
