### ISSUE TITLE
Error after downloading a song DeprecationWarning

### ISSUE THREAD

**Issue by GM-Shenmue** [Just-Some-Bots/MusicBot#631]
"bot.py:467: DeprecationWarning: change_status is deprecated, use change_presence instead.
  await self.change_status(game)" dunno what is going on bot was working fine without this errors, the musics still plays but everytime it plays the next song it shows that error.
![error](https://cloud.githubusercontent.com/assets/22497369/18912719/d8c5dffc-857b-11e6-9bc5-8b0825c9b56e.png)

**Comment by jayktaylor** [comment]
This is normal and is because of changes to discord.py. Ignore it, and the message will not occur in the next bot version.

**Comment by GM-Shenmue** [comment]
ah cool, thanks ;)
