### ISSUE TITLE
Failing To Connect

### ISSUE THREAD

**Issue by ThomasW11** [Just-Some-Bots/MusicBot#632]
Hello,

I am using debian OS

I am new so please be very basic :P

I get this error
http://prntscr.com/cnj6k5

bot connects and disconnects all the time.

**Comment by javierdlg** [comment]
Do you have an antivirus or active firewall running in the background? You might need to add a rule for this specific app.

**Comment by ThomasW11** [comment]
This issue has been resolved. 

FIX: Move to windows server (you do not have to - but I could not be bothered to use linux :P)
