### ISSUE TITLE
Bot won't connect or anything.

### ISSUE THREAD

**Issue by Shaamdragon25** [Just-Some-Bots/MusicBot#633]
CMD prompt shows this.
[permissions] Permissions not found, copying example_permissions.ini
Traceback (most recent call):
  File "run.py", line 163, in main
    m=MusicBot()
  File "C:\Users\owner\Desktop\MusicBot-master\musicbot\bot.py", line 96, in_init_
    self.http.user_agent += ' MusicBot/s%' % BOTVERSION
  File "C:\Users\owner\AppData\Local\Programs\Python35\lib\site-packages\discord\client.py, line 234, in_getattr_
    raise AttributeError(msg.format(self._class_, name))
AttributeError: '<class 'musicbot.bot.MusicBot'>' object has no attribute 'http'
Unlclosed client session
client_session: <aiohttp.client.ClientSession object 0x000001801F1163C8>
Unlclosed client session
client_session: <aiohttp.client.ClientSession object 0x000001801F116908>

I don't even know how to begin tackling this mess.

**Comment by jayktaylor** [comment]
Use the guides on the wiki https://github.com/SexualRhinoceros/MusicBot/wiki to install the bot again. The bot and the installation process have changed since you obtained the version you have. Make sure to update your dependencies after reinstalling/updating.

**Comment by jayktaylor** [comment]
(If you are actually using the new version but you downloaded the zip instead of cloning through Git, still proceed to follow the guides to install it properly - we don't support zip downloads)

**Comment by Shaamdragon25** [comment]
I didn't know that.  Thanks for the info.

**Comment by Shaamdragon25** [comment]
I'll try that now.

**Comment by Shaamdragon25** [comment]
It does indeed work now.  Also I was using the proper version previously.  I was just using the Zip and probably did some things horribly wrong.  However, I know one thing I didn't do was run the update_deps.bat.  Well, thanks for the help.
