### ISSUE TITLE
Bot doesn't recognize commands.

### ISSUE THREAD

**Issue by Augustaeum** [Just-Some-Bots/MusicBot#637]
The bot successfully joins a specific text channel. But it is not recognizing commands from said text channel, and I am using the correct prefix.

**Comment by Rollsroyces** [comment]
Same issue here! I ran the bot he joins the channel succesfully but when typing -play titlehere he does not respond anymore. I ran the update.deps but nothing changed.

Screenshot of bat http://prntscr.com/cp5dzi

**Comment by junhui-f** [comment]
Does the bot have the appropriate permissions assigned to it?

**Comment by mdod** [comment]
@Augustaeum @Rollsroyces If permissions aren't the problem, screenshot the CMD/Terminal window when you start the bot, but higher up than what @Rollsroyces already screenshotted.

**Comment by Augustaeum** [comment]
Hey, yo, I am so sorry for taking so long. So here is the picture requested :  http://imgur.com/a/H4dOD.
I'll also post a pastebin of my options.ini :  http://pastebin.com/8yE9a4Xr

In response to Grift I gave my bot Administrator privileges.

EDIT: I changed the pastebin to censor my bot token, whoops, I know I'm using the right token because it is playing music right now in my server.

**Comment by junhui-f** [comment]
Try removing the text channel binding.
Line 47 on pastebin

**Comment by Augustaeum** [comment]
My friend ended up solving my issue. It turned out I had not given the bot the proper permissions. I am an idiot, but I swear I gave it admin rights.

But anyway, it now functions correctly.
