### ISSUE TITLE
Hot to add multiple owners or permit other users to clear list/set volume?

### ISSUE THREAD

**Issue by PapiAlex** [Just-Some-Bots/MusicBot#640]
Hot to add multiple owners or permit other users to clear list/set volume?

I can't seem to find any setting for this.

**Comment by jayktaylor** [comment]
https://github.com/SexualRhinoceros/MusicBot/wiki/Permissions

**Comment by PapiAlex** [comment]
I already added a user to the following group but he still can't control volume/clear queue

; This group has full permissions.
[MusicMaster]
; GrantToRoles =
; UserList = 174838386677383169
MaxSongLength = 0
MaxSongs = 0
MaxPlaylistLength = 0
AllowPlaylists = yes
InstaSkip = yes

**Comment by NNTin** [comment]
Your UserList is commented. Also I think you need to specify which commands they are allowed to use via CommandWhitelist.

**Comment by PapiAlex** [comment]
yea, solved the comment thing, still doesnt work.

Looked in the entire permissions file, didnt see a command for !clear or !volume to add them to the MusicMaster user group.

I need something like:
QueueClear = yes
VolumeControl = yes

That would be awesome but again, didnt find something like that in the permissions. 
Anyone have another idea?

**Comment by imayhaveborkedit** [comment]
No, you don't need those options.  If a permissions group has neither a whitelist nor a blacklist option set, it has access to all normal commands.  Remember you need to restart the bot for new permissions to be applied.

**Comment by PapiAlex** [comment]
Thank you all for your help. I worked it out in the end :D.
Really great support!
