### ISSUE TITLE
New Option for Config

### ISSUE THREAD

**Issue by SaubereSacheLP** [Just-Some-Bots/MusicBot#642]
Hi,
can you please add the option that a Bot Group (like DJ) is granted to the Discord Group DJ!
If this is already added I didnt found it / its not working

**Comment by mdod** [comment]
It won't do it automatically, but you can set it up yourself.
https://github.com/SexualRhinoceros/MusicBot/wiki/Permissions#add-a-role-to-a-group

**Comment by imayhaveborkedit** [comment]
The bot won't mess with your server roles.  The bot just uses server roles as a way to make managing permissions easier, its your job to assign roles accordingly.

**Comment by SaubereSacheLP** [comment]
But I dont like to set the ID of the Role I like to set the name because Im using the Bot public

**Comment by jayktaylor** [comment]
You were already linked how to add a role to a group earlier in this thread. There's no way of using names right now, use the role's ID.
