### ISSUE TITLE
Warning appearing in CMD window

### ISSUE THREAD

**Issue by Dradonis** [Just-Some-Bots/MusicBot#644]
Hi just did a fresh install as I upgraded my drive after installing a fresh copy of the bot and setting it up again the bot has started to display this in the CMD window repeatedly 

"C:\MusicBot\MusicBot\musicbot\bot.py:467: DeprecationWarning: change_status is deprecated, use change_presence instead.
  await self.change_status(game)"

**Comment by jayktaylor** [comment]
Just ignore it, it'll be removed in the next version.

**Comment by Dradonis** [comment]
Ok, thanks for the fast reply 😊
