### ISSUE TITLE
Bot randomly disconnects from voice channel

### ISSUE THREAD

**Issue by mindleak** [Just-Some-Bots/MusicBot#645]
So this seems to happen a couple times per day, but the bot will randomly disconnect from the voice channel.

The only error in the console anywhere close to the time it disconnects is:
`[s16le @ 00ade8a0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 2216 >= 2191`

It'll throw that and keep playing maybe 10 songs then disconnect.

The bot stays in the active users list and continues to display what song it's playing and even responds to commands in chat.

We try !summon, which brings the bot back, but it's not playing any audio.

The only way to resolve it is by doing !restart

**Comment by deansheather** [comment]
When the bot is still online in the server members list, does the `Playing` text change at all (wait about 5-10 minutes before you check again)?

**Comment by mindleak** [comment]
Yes, it keeps downloading and playing YouTube videos and displaying the current song.

Although I recently ran the update_deps.bat, even though there wasn't a bot update at the time, and it updated the YouTube plugin (or whatever it is) and I haven't noticed a disconnect since then, even when the above error came up in the console.

But I'm still monitoring it.

**Comment by sunshoes** [comment]
We have had this happen with multiple different instances of the bot on different servers. It happens about once a week on a server where the bot gets used for maybe a couple hours a day, and it always disconnects at some point when no one has used it for a while. On another server though, with a lot of users through most of the day it has been disconnecting multiple times a day. As the OP said it can only be fixed with a reconnect.

**Comment by chuushi** [comment]
This occurance seems to be happening at random (even on the review branch).  I've seen the bot gone from the voice channel and had to run summon on it.
Though it is rare, it's annoying when it happens.

**Comment by xShineyThighx** [comment]
This actually just happened to me as well exactly how the OP described it.

**Comment by UnbendableStraw** [comment]
I have the same issue but I was banned from the support server for bringing it up and arguing with a support guy that this was a legitimate issue

**Comment by jayktaylor** [comment]
This appears to have been fixed in ffmpeg (the error message). The disconnects should have been resolved in recent bot versions.
