### ISSUE TITLE
Return to a default voice channel if everyone leaves the one the bot is currently in

### ISSUE THREAD

**Issue by alpha-tango-kilo** [Just-Some-Bots/MusicBot#647]
So say a bunch of my friends are playing Overwatch, so they summon the bot to the Overwatch voice channel from the Music Hub voice channel. When they all eventually leave the Overwatch voice channel, could we have a way of moving the bot automatically back to their original voice channel that they joined on startup (Music Hub in this case)?

**Comment by ngelus** [comment]
I'd like that!
