### ISSUE TITLE
Stop deleting the audio_cache folder

### ISSUE THREAD

**Issue by Injusticecraft** [Just-Some-Bots/MusicBot#648]
On start up for the Music Bot the audio_cache folder gets deleted then recreated is there a way to make it stop getting deleted?

I'll try to work on this myself but if anyone knows how to please let me know.

**Comment by jayktaylor** [comment]
Change `SaveVideos` in the config to `yes`

**Comment by Injusticecraft** [comment]
Is there a way to do this when SaveVideos in the config is set to no?

**Comment by imayhaveborkedit** [comment]
This will be changed when I add modes to how this works.  Instead of just on and off, there'll be settings for the max size and deletion strategy.

**Comment by Injusticecraft** [comment]
Ok cool :)
