### ISSUE TITLE
Auto-delete commands and output

### ISSUE THREAD

**Issue by Chew** [Just-Some-Bots/MusicBot#65]
I'm not sure if this exists or not, but I would like if the bot has the permission to remove people's messages, it should.

FOR EXAMPLE:

before suggestion:

`User A: !!help`
`Bot: [Commands here].`
_some time later_
_**Bot removes message**_

with suggestion

`User A: !!help`
`Bot: [Commands here].`
_Some time later_
_Bot removes both messages_

Would clear up chat a lot :P

**Comment by imayhaveborkedit** [comment]
There's a clear command for that.  I stubbed it out in the code but it doesn't do anything.  I've added it, but I still need to test it and push to review.

**Comment by Chew** [comment]
Yeah but automatically would be cool.
