### ISSUE TITLE
Possible to limit bandwidth?

### ISSUE THREAD

**Issue by dannyvoid** [Just-Some-Bots/MusicBot#650]
Is it possible to only have MusicBot download youtube videos in a lower quality?
I'm not sure what bitrate it currently downloads in, but is there a way to limit it to 480p perhaps? Or something similar.

**Comment by imayhaveborkedit** [comment]
480p is a video resolution, which is irrelevant in this situation.  The bot downloads audio only if possible.  It tries to get the best quality, but quality across different extractors isn't really that consistent.  Frankly the audio quality is bad enough without reducing the input quality.  I can do some tests to see if I can put a reasonable limit on how high it'll go.  Honestly though, if you're concerned about bandwidth usage, you might not be suited to host a musicbot.
