### ISSUE TITLE
runbot_mac.command & user owner ID issue

### ISSUE THREAD

**Issue by kusnim** [Just-Some-Bots/MusicBot#651]
I'm having issues with the final step of downloading MusicBot through MacOSX (Just updated to Sierra btw).
So after 3+ hours of trying to figure out each step with 0 experience on using terminal, I learned that the link shown under "How do I add a bot account to my server?", in the FAQ page, is the wrong link. I tried the following link
https://discordapp.com/oauth2/authorize?&client_id=<CLIENT ID>&scope=bot&permissions=0
and it didn't work so I dug around Google searches for this link
https://discordapp.com/oauth2/authorize?client_id=157730590492196864&scope=bot&permissions=0
and eventually this link through a reddit post
https://discordapp.com/oauth2/authorize?&client_id={bot-id}&scope={scope}&permissions={permissions}&response_type=code
(https://www.reddit.com/r/discordapp/comments/4gjar1/how_do_i_add_my_bot_to_my_server/)

I got one of those 3 links to work but its been so long ago and so much trial and error, I forgot which one worked but I think it was the 2nd or 3rd. Regardless, my problem is that even though I got a confirmation page saying that I successfully set my OwnerID (the bot ID) using the correct link, and I double click 'runbot_mac.command' (the final step), I still get this message on Terminal:
An error has occured reading the config:

---

  Problem:  OwnerID was not set.  
  Solution: Please set the OwnerID in the config.  If you don't know what that              is, use the !id command                                             

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

---

I'm on literally the last step as I've already installed Atom to edit files and all that other jazz and I'm losing sleep over this. Any help would be greatly appreciated.

edit: here's a link to the OSX installation guide for reference.
https://github.com/SexualRhinoceros/MusicBot/wiki/Guide-for-OSX
The "Adding it to your server" under step 3: Configure

**Comment by ImthePeach** [comment]
As for the invite URL you needed to replace the `<CLIENT ID>` that is in the url with the Client ID that is listed on your bots application page. Refer to this part of the FAQ, it is correct: https://github.com/Just-Some-Bots/MusicBot/wiki/FAQ#how-do-i-add-my-bot-account-to-a-server

As for your ID question did you put your ID in the options file on the line that says `OwnerID =` ?
If you didn't edit that you need to. Refer to this: https://github.com/Just-Some-Bots/MusicBot/wiki/Configuration#ownerid

If that is not the issue comment back.
