### ISSUE TITLE
Bot is restarting if a command takes too much time

### ISSUE THREAD

**Issue by marco213** [Just-Some-Bots/MusicBot#652]
Hey guys,

Recently I've noticed that if a command take too much time, the bot restarts itself. For say, if I try to play a song who takes forever to download, it will just quit and restart. Is there a way to fix this? I have a very bad internet speed and this happens often

**Comment by ImthePeach** [comment]
When it "restarts" does it come up with an error? It's possible that if you internet is truly that bad then it could just be losing connection to discord and that's why it's restarting because it errors in a lost connection.
