### ISSUE TITLE
Permissions for Administrator

### ISSUE THREAD

**Issue by SaubereSacheLP** [Just-Some-Bots/MusicBot#654]
Hey,
could you add that the Server Groups with "Administrator" got all Permissions to the bot?
I like to use the bot public, and you cant set permissions to groups without their IDs, thats the Problem!

**Comment by xXBuilderBXx** [comment]
Type !listids
To get a list of the group ids 👍

**Comment by ImthePeach** [comment]
like builder said, use the `!listids` command to get the role id then add that to the permissions file.
