### ISSUE TITLE
Suggestion for the Music Bot Online State(s) or Not in Voice Channel(s)

### ISSUE THREAD

**Issue by Injusticecraft** [Just-Some-Bots/MusicBot#655]
When the bot is paused/Playing nothing make it Idle
When the bot is playing make it Online 
When the bot is paused for a certain amount of time/not in a voice channel make it Do not Disturb

**Comment by jayktaylor** [comment]
But what difference would this make other than for vanity reasons? It's not like the bot will care about being mentioned or PMed?

**Comment by Injusticecraft** [comment]
Just a suggestion just thought it would be cool

**Comment by chuushi** [comment]
I think having the bot status as idle when not connected to any voice channel will be useful.  That'll make it easy to tell that the bot isn't doing anything at the moment on Discord.

**Comment by jayktaylor** [comment]
The bot's 'Now Playing' status indicates if it's doing anything on any server. Feel free to add this yourself, but it feels like an un-needed addition in the grand scheme of things.
