### ISSUE TITLE
Adding songs to the audioplaylist.txt file

### ISSUE THREAD

**Issue by Injusticecraft** [Just-Some-Bots/MusicBot#656]
You will use something like !add to use the command so Example:
!add (https://youtu.be/P0PpyUsvT9w) <----- Undertale OST 50 FYI not advertising
It would add that link to the audioplaylist.txt file
Anyone can use it unless you want to set perms up for it

**Comment by jayktaylor** [comment]
Duplicate of #88

**Comment by Injusticecraft** [comment]
But its not because your using a spifice URL to add to the audioplaylist.txt file
