### ISSUE TITLE
use delete_message=(message)

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#658]
Where would I put it? My goal is to get the bot to automatically remove the original message after the bot has commented on it. I would have enough information if someone could make that work on this simple ping script. _(delete the Ping message sent by an user, after the bot has sent the Pong! message)_

```
async def cmd_ping(self, channel):
    """
    Usage:
        {command_prefix}ping
    Ping command to test latency
    """
    await self.safe_send_message(channel, "Pong!")
```

**Comment by jayktaylor** [comment]
This is already a feature of the bot. It's called `DeleteInvoking` in the config.
