### ISSUE TITLE
Songs seem to stutter at random in the discord room

### ISSUE THREAD

**Issue by Bowstrike** [Just-Some-Bots/MusicBot#659]
Was curious to see if i could reduce the amount of stuttering the songs do its not a lot as it sits but its a bit taxing when your hosting a server of 30+ people at any given point and the songs stutter. started stuttering today around 8:00 AM PST.

**Comment by ImthePeach** [comment]
If your bot is lagging when playing music
- Check CPU/disk usage
- Can your PC/the VPS' bandwidth/speed handle the bot?
- Is there an issue on https://status.discordapp.com?
