### ISSUE TITLE
Use music_cache instead of autoplaylist.txt for playing when there is no queue

### ISSUE THREAD

**Issue by fullmetal1** [Just-Some-Bots/MusicBot#660]
Feature request for option to play songs that are stored in the music_cache rather than using autoplaylist.txt

**Comment by imayhaveborkedit** [comment]
Downloaded songs will be a special kind of playlist, like the autoplaylist, when I get around to that with the local playlists feature in the update after this next one.

**Comment by fullmetal1** [comment]
Okay thanks mate
