### ISSUE TITLE
Bot won't join at all 

### ISSUE THREAD

**Issue by bobrossfan** [Just-Some-Bots/MusicBot#664]
![capture pngdff](https://cloud.githubusercontent.com/assets/22783744/19296378/e8651f94-8fef-11e6-8480-4f77a6923233.PNG)

**Comment by ImthePeach** [comment]
Erm.. why are you trying to run this from the recycle bin?

**Comment by ImthePeach** [comment]
Move it to your desktop, then run it. Also, you should follow our guides as you already downloaded the bot incorrectly.
https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Windows
