### ISSUE TITLE
Can you make a guide/version for Redhat/CentOS

### ISSUE THREAD

**Issue by RTUnreal** [Just-Some-Bots/MusicBot#669]
I wanted to run the Bot on my CentOS server and the wiki didn't had an explanaition for the OS.
Thanks in advance. Yours Unrealrussian

Edit: I don't really know much about scripting and Python in generall

**Comment by ImthePeach** [comment]
We don't have anyone on the staff that runs that operating system which is why there hasn't been a guide made. You should be able to reference the Ubuntu guide for the packages you need to install and Google how to install them for your system in the mean time though. Your request though is noted and we will see what we can do.

**Comment by WuTofu** [comment]
perhaps the most easy way for you is running your bot with docker.

**Comment by MayhemBill** [comment]
I have a machine I used to test CentOS on. If you'd like I can write a guide on it, sometime in the next few days.

**Comment by ghost** [comment]
@TheHeroBilly Please do write a guide, thanks!

**Comment by FreshDumbldore** [comment]
If you really want to do this @vldr  , then i tell you that you need a really long time.
First get everything you need like python3, git and such. ([http://stackoverflow.com/questions/32618686/how-to-install-pip-in-centos-7] Link to pip if it says that it isn't installed or properly updated)
Then, i would suggest you installing all of this: https://gist.github.com/mustafaturan/7053900
in order for the bot to work properly. (that is the most timeconsuming part)
I am not sure if Opus was installed with it too, so extra link :P
`wget ftp://mirror.switch.ch/pool/4/mirror/scientificlinux/7rolling/x86_64/os/Packages/opus-1.0.2-6.el7.x86_64.rpm`
Now you should be safe to download the bot and install it.
Make sure that it has proper folder rights or it may error out.
And that should be it. If i missed something or something is unclear, please don't hesitate to contact me :)

Edit#1: Just noticed that i made the @mention to someone also with the attempt to make a guide XD
sry :P

**Comment by parkervcp** [comment]
@Unrealrussian I have a CentOS install working now.

https://gist.github.com/parkervcp/f598bc9899d4e44dd90c3bae5a3226a5

**Comment by erichowey** [comment]
I made a working systemd unit file for CentOS 7 in case anyone is interested. No screen required. You will need to modify it to your username, install location and what not.

```
[Unit]
Description=Discord Music Bot
ConditionPathExists=/home/musicbot/MusicBot
After=network.service

[Service]
Type=simple
WorkingDirectory=/home/musicbot/MusicBot/
ExecStart=/usr/bin/python3.5 run.py
StandardOutput=syslog
StandardError=syslog
User=musicbot
KillSignal=SIGINT

[Install]
WantedBy=basic.target
```

**Comment by amit177** [comment]
A bit delayed, but a guide was added.

https://just-some-bots.github.io/MusicBot/installing/centos/
