### ISSUE TITLE
Can't install it?

### ISSUE THREAD

**Issue by venimo** [Just-Some-Bots/MusicBot#676]
Did python3.5 run.py And then appears this: 

No module named 'aiohttp'
Attempting to install dependencies...

That's all

**Comment by itslukej** [comment]
pip3.5 install aiohttp?

**Comment by MayhemBill** [comment]
What OS?

**Comment by venimo** [comment]
Ubuntu 16.04

**Comment by jimmy697845** [comment]
I am having the same issue but in windows 10. I have tried everything. I have spent 6 hours on google trying to figure out how to fix this error and nothing works. Can someone please help

**Comment by chuushi** [comment]
@jimmy697845 I successfully installed it on my windows machine. Did you follow this guide? https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Windows

**Comment by jimmy697845** [comment]
yes i followed it, i get an error every time i try to open runbot.bat

**Comment by jayktaylor** [comment]
@jimmy697845 If you're still having problems, feel free to open an issue.
