### ISSUE TITLE
Raspbian repos have no distribution template

### ISSUE THREAD

**Issue by ElectricSquid** [Just-Some-Bots/MusicBot#677]
Trying to install the dependencies for the bot on Jessie and adding the repos just returns `aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/Jessie`  

It does this for all PPAs I need to add. Is there even a reason for having these repos if we can't install anything from them? 

Running Raspbian Jessie (8)

**Comment by Renvolt** [comment]
I noticed the same thing, Bot works fine without it. Probably just outdated guide.

**Comment by mdod** [comment]
#609

**Comment by mdod** [comment]
Unfortunately, I can't update the guides, but they aren't needed.

**Comment by ElectricSquid** [comment]
Didn't realize this was a copy. Didn't see that one when I searched for it. Bot completely functions without them. Just wasn't sure if anyone was made aware. Thanks!
