### ISSUE TITLE
URL BlackList

### ISSUE THREAD

**Issue by tutur1004** [Just-Some-Bots/MusicBot#678]
Add cmd to add URL blacklist !

!BlackSound

And the sound can't be added to queue

**Comment by zstinnett** [comment]
This sound be very useful if it was implemented.

**Comment by arunesh90** [comment]
It would be a waste of time. And why?
People will just re-upload it or grab the song/sound from a other source.
There are always multiple versions/uploads of (troll) songs

**Comment by chuushi** [comment]
I think it would be an okay investment.  It's not hard to write an extra check to check the song name keyword or the url of the song.  If some people keep abusing the system, then they should be banned (from using the bot).

**Comment by zstinnett** [comment]
I agree with SimonOrj, If a song was banned by URL and key title it would be a sufficient block. It would be very useful!

**Comment by KingGold171** [comment]
``` Python
        if "pornhub" in song_url:
            reply_text = "Videos from PornHub CANNOT be played!"
            raise exceptions.CommandError(reply_text)
```

**Comment by ImthePeach** [comment]
If this were to be an upcoming feature it would be so far down the totem pole of priorities that it probably wouldn't be touched for a while unless someone did a PR for it and bork liked it. Until such time tell your users to not request those things you don't want and if they do then blacklist that user from being able to use the bot.

**Comment by jayktaylor** [comment]
#140 #249 #520 #672
