### ISSUE TITLE
Stuck on options display

### ISSUE THREAD

**Issue by Callumpy** [Just-Some-Bots/MusicBot#680]
Hello, I have only recently started having this issue.

When the bot starts up, it just gets stuck displaying the options, it doesn't join the server or channel.

I've have deleted my entire MusicBot folder and have downloaded the latest version, still not working for me.

**Comment by mdod** [comment]
Please provide a screenshot

**Comment by Callumpy** [comment]
![bot](https://cloud.githubusercontent.com/assets/6465413/19614059/0e7485b6-97e9-11e6-848b-057f40a07e96.png)

**Comment by Callumpy** [comment]
Ah, running the authorization again fixed it, I wonder if it got banned.

Sorry about that.
