### ISSUE TITLE
[Bug] Suddenly no more music

### ISSUE THREAD

**Issue by Bomberlux** [Just-Some-Bots/MusicBot#688]
This has been happening constantly the past week, my bot is in a voice channel, and then suddenly the music stops. The bot is still there, not playing any music. I either have to play a music myself, or restart it, which is quite annoying... I get a very, very, very long error message in the cmd box, can't even screenshot all of it(also because I'm a bit lazy...) but here's the start:
http://image.prntscr.com/image/84ff41f5d9584881b1aec27207419e9b.png

**Comment by MayhemBill** [comment]
It looks like the YTDL fails and it just throws a fit entirely. I've been having this issue for a few days now as well. Not sure what's starting it.

**Comment by jayktaylor** [comment]
Are you still having this issue? Have you tried updating youtube-dl? Have you tried testing your network connection? Is your firewall blocking the script?

**Comment by Bomberlux** [comment]
I didn't really change anything, but it works as it's supposed to again. In my opinion, it had something to do with my network connection, I had trouble even joining a voice channel myself the days after, but after some time it all got fixed.

**Comment by arunesh90** [comment]
good to hear you got it working again
