### ISSUE TITLE
[Question] About the musicbot

### ISSUE THREAD

**Issue by ABCLost** [Just-Some-Bots/MusicBot#690]
Is there anyway to put this anywhere on a vpn site so its 24/7? i dont wanne run my pc 24/7 for music for my discord server

**Comment by jayktaylor** [comment]
Yes, you can host this on a VPN. I'd advise an Ubuntu VPN. Use something like DigitalOcean or Amazon Web Services.

**Comment by KingGold171** [comment]
vps: What's a VPS you say?!
A virtual private server (VPS) is a virtual machine sold as a service by an Internet hosting service. A VPS runs its own copy of an operating system, and customers have superuser-level access to that operating system instance, so they can install almost any software that runs on that OS. This means that you can run the MusicBot 24/7 and allow yourself to turn off your computer or let it sleep every so often.

Recommended VPS hosts:
AWS: https://aws.amazon.com/free/ While AWS has a free tier, it is only limited data usage under this plan. You may still pay montly for it, and you don't get a any customer support if an issue should arise.

Digital Ocean: https://m.do.co/c/04df8e10578f You can run the MusicBot easily under the $5 per month plan. This is a set monthly payment and can use more data than AWS allows, you will also get customer support at no additional cost. Also if you use the URL in this post you can get a $10 credit to your account when you sign up.

**Comment by arunesh90** [comment]
Just a little comment, It's better to use this link when you're gonna sign up for Digitalocean: https://blog.codeanywhere.com/announcing-partnership-with-digitalocean/

If you follow those instructions you get $25 instead of $10

**Comment by chuushi** [comment]
My bot is doing pretty amazingly on an Ubuntu VPS for $4/month.  It's running an Ogar (Unofficial Agario) server as well, which further amazes me.  OVH is another good choice.

Those who went with Amazon's free tier, how does it work out for you? I'm paranoid that it might go over the free data limit.
