### ISSUE TITLE
Auto playlist repeating songs over and over

### ISSUE THREAD

**Issue by jiwicharms** [Just-Some-Bots/MusicBot#691]
I made my auto playlist with 50 songs; however when the bot is on autoplaylist mode, only the first few songs chosen at the beginning are constantly repeated.

**Comment by jayktaylor** [comment]
The way that the bot currently works is that it randomly picks a song from the file. This means that it can play the same songs multiple times in a row due to bad RNG. We're going to tackle this in #613.
