### ISSUE TITLE
"PyNaCl library needed in order to use voice" with all dependencies satisfied

### ISSUE THREAD

**Issue by thunderysteak** [Just-Some-Bots/MusicBot#693]
The bot doesn't realize that it's in a voice channel and thinks that the PyNaCl dependency is missing, when it is in fact installed

`Attempting to autosummon...
Found owner in "General", attempting to join...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 273, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/home/discord/MusicBot/musicbot/bot.py", line 710, in on_ready
    owner_vc = await self._auto_summon()
  File "/home/discord/MusicBot/musicbot/bot.py", line 149, in _auto_summon
    await self.cmd_summon(owner.voice_channel, owner, None)
  File "/home/discord/MusicBot/musicbot/bot.py", line 1344, in cmd_summon
    player = await self.get_player(author.voice_channel, create=True)
  File "/home/discord/MusicBot/musicbot/bot.py", line 362, in get_player
    voice_client = await self.get_voice_client(channel)
  File "/home/discord/MusicBot/musicbot/bot.py", line 249, in get_voice_client
    voice_client = VoiceClient(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 213, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice
`

The dependencies from requirements.txt are all installed

`python3.5 -m pip install -U -r requirements.txt
Requirement already up-to-date: discord.py[voice]~=0.12.0 in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: youtube_dl in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: pip in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: cffi==1.6.0 in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: aiohttp<1.1.0,>=1.0.0 in /usr/local/lib/python3.5/site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: websockets<4.0,>=3.1 in /usr/local/lib/python3.5/site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: PyNaCl==1.0.1 in /usr/local/lib/python3.5/site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: pycparser in /usr/local/lib/python3.5/site-packages (from cffi==1.6.0->-r requirements.txt (line 4))
Requirement already up-to-date: async-timeout in /usr/local/lib/python3.5/site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: multidict>=2.0 in /usr/local/lib/python3.5/site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: chardet in /usr/local/lib/python3.5/site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: six in /usr/local/lib/python3.5/site-packages (from PyNaCl==1.0.1->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
`

Running CentOS 7 x64

**Comment by jayktaylor** [comment]
Make sure you have libsodium installed properly.

**Comment by thunderysteak** [comment]
Issue fixed by doing a full wipe of Python and doing a fresh install of Python 5.2 and recompiling libsodium.
