### ISSUE TITLE
My Bot Wont Join Server....

### ISSUE THREAD

**Issue by SumRed** [Just-Some-Bots/MusicBot#694]
http://imgur.com/a/UbCUP is the problem I keep having on the last step of the guide. Not sure how to fix it so in need of some help.

Thanks in advance

**Comment by brawaru** [comment]
Remove second `token` option from your `options.ini` file 
![image](https://cloud.githubusercontent.com/assets/10401817/19827898/b0beb320-9de1-11e6-8eea-035a082dea7a.png)

**Comment by SumRed** [comment]
Thank you very much for helping me it works now!!
