### ISSUE TITLE
Bot is skipping Linux

### ISSUE THREAD

**Issue by NekoTony** [Just-Some-Bots/MusicBot#697]
Yeah, when playing music it skips every second.

**Comment by ImthePeach** [comment]
If your bot is lagging when playing music
- Check CPU/disk usage
- Can your PC/the VPS' bandwidth/speed handle the bot?
- Is there an issue on https://status.discordapp.com?

You can try changing voice regions to a more closer voice region to where you bot is being hosted and see if that helps as well.

**Comment by NekoTony** [comment]
Cpu is pretty high, is there a way of reduce that while running the bots?

**Comment by ImthePeach** [comment]
Not sure, find out what extra is running on your os and kill things that are taking up extra CPU usage and and of unimportance as the bot should run fine on a 1 core processor with 512 mb of memory if it's the only thing running. There is probably something else more taxing on your system than the bot.

**Comment by salamieri** [comment]
Well, you could either get more CPU power from your VPS provider (assuming you're on a VPS), or use less bots.
