### ISSUE TITLE
V2.0 Feature: Permissions

### ISSUE THREAD

**Issue by imayhaveborkedit** [Just-Some-Bots/MusicBot#7]
Currently any user can use any command, and this is obviously sub optimal for any setting other than a group of friends.  Denying users access to certain commands is obviously necessary for more public settings.  This issue is twofold: the implementation of the internal permissions system, and how the user access it.  **Other variations are still a possibility.**
- **Option 1: Internalize Everything**
  - Using this method means that commands will be assigned permission groups in the config, and users will be managed with commands, adding and removing permissions though chat.  
  - Alternatively, commands will be marked as needing permission, and users will be permitted to use them via some sort of `!permit user` style of command.  
  - For both variations, these settings will be saved to a file in the musicbot folder.
- **Option 2: Assigning Server Groups**
  - Access to certain commands will be permitted through the process of assigning a user a user-defined server group, matching something set in the config.  For example: 
    - A user would set several commands they want limited to the group `DJ`, and only users with the group `DJ` would be able to use those commands.  
  - Alternatively, commands would have a predefined identifier, and server groups containing the identifier along with an arbitrary prefix to designate the group is the command group.  For example: 
    - The skip command would have an identifier of `s`
    - The volume command would have an identifier of `v` 
    - The command prefix would be `botperms-`
    - Any user with the group `botperms-s` would have access to the skip command
    - Any user with the group `botperms-v` would have access to the volume command
    - Users with the group `botperms-sv` would have access to both commands
    - _This idea was based on the regex flag system. (?iLmsux)_

**Comment by ArneNaessens** [comment]
I would suggest Option 2. Because it's easyer for discord server admins to setup. But probally harder for the coders.

**Comment by Arzte** [comment]
I vote for option 2, discord already has a permissions system, so why not take advantage of it. (its also easier for the server admins like @CyberStar1 said)

**Comment by amit177** [comment]
Old issue, we already have a permission system.
