### ISSUE TITLE
[request] Volume gain (!volume 150 = +1dB)

### ISSUE THREAD

**Issue by sgdc3** [Just-Some-Bots/MusicBot#70]

**Comment by imayhaveborkedit** [comment]
When @jhgg was making the volume command, whenever he tried to raise the volume, it broke.  It only works for lowering it.  I don't know why, I don't know if he knows why, but all I know is that we can't right now.  If you need to turn the bot up past 100% volume, for whatever reason that would be, you can just increase the bot's volume in discord by clicking on his name.

**Comment by sgdc3** [comment]
@imayhaveborkedit You need a library to manipulate audio stream's volume i think. 

> If you need to turn the bot up past 100% volume, for whatever reason that would be, you can just increase the bot's volume in discord by clicking on his name.

Yeah but i was looking for a bot side solution.

**Comment by jhgg** [comment]
If we want to go over 100% we need to make sure that we clamp each pcm frame to the s16le bound or we'll overflow.

**Comment by imayhaveborkedit** [comment]
Its now possible to do this but I think I want to add some sort of permission because `!volume 200` is even worse than the random `!volume 100`.
