### ISSUE TITLE
i need talk to you

### ISSUE THREAD

**Issue by Rooting21** [Just-Some-Bots/MusicBot#700]
i need talk to you on discord please

**Comment by jayktaylor** [comment]
http://discord.me/rhinohelp

**Comment by Gamer08YouTube** [comment]
Hi ich bins Gamer08 ich bin Reseller auf Lesplaylounge aber ich kann kein Server erstellen

**Comment by ImthePeach** [comment]
Bist ihr dumm? Ich denke du hast nicht mehr alle Tassen im Schrank.
@Gamer08YouTube

**Comment by Rooting21** [comment]
Sry bro ich weiß nicht wie man auf die idee kommt hier soetwas zu schreiben

**Comment by ImthePeach** [comment]
No not you. The gamer guy

**Comment by Gamer08YouTube** [comment]
Sry ich wusste net wo ich es sonst schreiben Sollte :-( ich konnte dich sonst nirgends erreichen
