### ISSUE TITLE
[request] Audio normalization

### ISSUE THREAD

**Issue by FatRagdoll** [Just-Some-Bots/MusicBot#702]
Often when listening to playlists, a bunch of the tracks will be very low volume compared to the rest. This results in you having to manually change the volume once those low tracks starts playing, which is not something that you'd want to have to do when listening to the musicbot in the background while playing games or doing other stuff.

A solution to this problem would be to have some kind of audio normalizer which can analyze the youtube/soundcloud link and automatically make lower volume tracks louder.

**Comment by jayktaylor** [comment]
Thanks for your issue.

This feature has been requested quite a bit, we're keeping discussion and suggestions for it here: #156

**Comment by FatRagdoll** [comment]
Ohh, maybe I should have been doing some searching before posting.
