### ISSUE TITLE
Play an audio file when the bot joins a voice channel on startup.

### ISSUE THREAD

**Issue by DeathPixl** [Just-Some-Bots/MusicBot#703]
Is there any way to make the bot play an audio file when it joins the voice channel its bound to? If there isn't a way to do this is there any possibility of this being a feature in the future? This would also include a message to the server that it's online.

**Comment by KingGold171** [comment]
enable autoPlaylist in options.ini,   Bot will automatically play songs from this file.

autoplaylist.txt in     config folder.

1 URL per line.

 https://github.com/Just-Some-Bots/MusicBot/wiki/Configuration#useautoplaylist

**Comment by ImthePeach** [comment]
Most likely won't be added. Not sure if bork would even want to try and attempt such a thing.
