### ISSUE TITLE
How to disable vote skip for @everyone on discord

### ISSUE THREAD

**Issue by Mackenzieboi1** [Just-Some-Bots/MusicBot#705]
Pretty much people on my discord can vote to skip which is something i DO not want to be a thing on my discord. I and I only want to be the one to skip the music. any solutions to the votes requires / skip ratio part ?

**Comment by chuushi** [comment]
You should look into how to set up [permissions](https://github.com/Just-Some-Bots/MusicBot/wiki/Permissions).

In other words, remove `skip` from your [`config/permissions.ini:69`](https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_permissions.ini#L69).

**Comment by ImthePeach** [comment]
^ he speaks the truth
