### ISSUE TITLE
Crossfade between songs

### ISSUE THREAD

**Issue by FatRagdoll** [Just-Some-Bots/MusicBot#706]
It would be nice to have the option to crossfade between songs, meaning that when the song is ending it slowly fades out as another song starts fading in. Im not sure how hard this would be to implement, but if it would get implemented it would certainly help to keep the flow up while listening to playlists.

**Comment by ImthePeach** [comment]
Won't be added anytime really soon tbh but it's something that could be considered.

**Comment by jayktaylor** [comment]
Gonna merge this and #360 together.
