### ISSUE TITLE
Error adding song from autoplaylist

### ISSUE THREAD

**Issue by KiiDii** [Just-Some-Bots/MusicBot#707]
I put the link: "https://www.youtube.com/playlist?list=PLOA1ARTjP2BCh46dUrazsCMB_M0hdnypa".  But I geting this "Error adding song from autoplaylist: ( '. This is a playlist', True, 'https://www.youtube.com/playlist?list=PLOA1ARTjP2BCh46dUrazsCMB_M0hdnypa')" How do I fix this?
![capture](https://cloud.githubusercontent.com/assets/23314538/20143731/ca4233d4-a6a2-11e6-960c-f7ce4a1d13df.PNG)

**Comment by jayktaylor** [comment]
You should use the `!pldump <playlist url>` command while the bot is running to create an autoplaylist friendly list. The autoplaylist file does not accept YouTube playlist URLs directly like that.
