### ISSUE TITLE
streaming internet radio

### ISSUE THREAD

**Issue by mikeparadinas** [Just-Some-Bots/MusicBot#708]
it will start downloading my internet radio (AAC encoded) but it wont finish downloading it, or start playing what it has so far.
5.133.182.174:33220/listen.m3u

can you make it so it will play my stream that would be fucking amazing.
![461c1a50d6ea4666bb69e3f31f31153a 1](https://cloud.githubusercontent.com/assets/13681989/20156899/9afee650-a6d2-11e6-88e2-db948b7bfeca.png)

**Comment by imayhaveborkedit** [comment]
This is what the `stream` command in review is for.

**Comment by mikeparadinas** [comment]
FUCK ITS WORKING ITS GLORIOUS THANKS
