### ISSUE TITLE
[request] Discord Audio settings in config

### ISSUE THREAD

**Issue by DasLetsPlaySchaf** [Just-Some-Bots/MusicBot#71]
Will you add an option do edit all video settings like volume and background noise etc. so we don't need to log in and edit this by hand after every !summon command?

**Comment by imayhaveborkedit** [comment]
If you mean commands to change config options, yes, i'm adding those soon.  Also, auto summon is on by default, so you don't really need to summon it every time.

**Comment by DasLetsPlaySchaf** [comment]
I want to set the !volume to 3 automatically by startup without setting it by hand.

**Comment by imayhaveborkedit** [comment]
Right now you can change `DEFAULT_VOLUME = 0.15` in constants.py to `0.03` but I can add the default volume to the options file.

**Comment by DasLetsPlaySchaf** [comment]
Thx

**Comment by imayhaveborkedit** [comment]
This is in the options file now.
