### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by techgithub345** [Just-Some-Bots/MusicBot#711]
When I open bpython in Ubuntu and typed in the first step, the Terminal said this:

`bpython version 0.15 on top of Python 2.7.12 /usr/bin/python
 sudo add-apt-repository ppa:mc3man/xerus-media -y
  File "<input>", line 1
    sudo add-apt-repository ppa:mc3man/xerus-media -y
           ^
SyntaxError: invalid syntax
`

**Comment by techgithub345** [comment]
I used Ubuntu 16.04 or higher.

**Comment by ImthePeach** [comment]
When you opened bpython in ubuntu?

**Comment by ImthePeach** [comment]
![image](https://cloud.githubusercontent.com/assets/17447156/20242865/3664bde8-a8fb-11e6-9885-80d4d69b0d9f.png)

**Comment by techgithub345** [comment]
@ImthePeach  Well, I could not download from websites, but I searched for "Python" and Python never appeared. So I tried using bpython from Ubuntu Software.

**Comment by techgithub345** [comment]
Although when I open discord on Firefox on Ubuntu, Firefox is most likely to crash on me.

P.S I am using Ubuntu as a virtual machine

**Comment by techgithub345** [comment]
![](https://cloud.githubusercontent.com/assets/22946142/20244783/24089156-a969-11e6-8a5a-5a6d04d85e8d.JPG) See? It did not work.

**Comment by jayktaylor** [comment]
You're trying to run the command in a Python interpreter. The commands are ran in the Terminal, without any kind of wrapper. Stop using bpython. Your version (2.7.12) is wrong anyway, and needs to be 3.5 to run the bot.
