### ISSUE TITLE
Strange error during some plays

### ISSUE THREAD

**Issue by JetLennit** [Just-Some-Bots/MusicBot#714]
I am unsure if this is important, but sometimes when I or other people in my server use the play command there is an error
`[s16le @ 0x2dca0a0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 2216 >= 2191
`
It doesn't crash or anything, but I don't know if this causes any problems under the hood. 

Thanks, 
jet

**Comment by imayhaveborkedit** [comment]
Nope, just ffmpeg warnings.  Ignore them.
