### ISSUE TITLE
HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by PetiZila** [Just-Some-Bots/MusicBot#717]
Hi, I tried to install the bot on a new VPS, but each time it try to load the auto-playlist or any youtube Link there's this message in the server logs, I know what it means but is there any way to unblock that situation ? 

```
> ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>)
> <class 'musicbot.exceptions.CommandError'>: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>)
> 
```
My VPS is on debian 8 (if it can help)
Thanks in advance for the help

**Comment by arunesh90** [comment]
If you are getting this error every single time, so even after a day, then try changing the ip of your vps.
This error usually pops up when the bot made many requests in a short time period, although is pretty rare to come across with the bot, so like I said, if you get it always, try changing ip

**Comment by PetiZila** [comment]
Thanks for the answer !
So, do you know a quick way to change the IP on debian 8 ? (I'm not really used to linux)

Edit: gonna contact my VPS hosting
