### ISSUE TITLE
Bot permission check doesn't work 

### ISSUE THREAD

**Issue by Kedakai** [Just-Some-Bots/MusicBot#719]
I run several docker instances of the musicbot of yours.
yesterday i wasn't able to get one bot to connect to the channel.
It always told that it hasent the permissions, but it had everything that it needed.
I removed the following code:

> if not chperms.connect:
            self.safe_print("Cannot join channel \"%s\", no permission." % author.voice_channel.name)
            return Response(
                "```Cannot join channel \"%s\", no permission.```" % author.voice_channel.name,
                delete_after=25
            )

> elif not chperms.speak:
            self.safe_print("Will not join channel \"%s\", no permission to speak." % author.voice_channel.name)
            return Response(
                "```Will not join channel \"%s\", no permission to speak.```" % author.voice_channel.name,
                delete_after=25
            )

and the bot connected to the channel without any problems.
Here is the config needed to debug.

Bot-Role
![bot-role](https://cloud.githubusercontent.com/assets/17503545/20455841/b9e2ba70-ae65-11e6-9f6a-04c5ca65098e.png)

Permissions for bot for voice channel
![voice-channel-permission-bot](https://cloud.githubusercontent.com/assets/17503545/20455843/b9e58a34-ae65-11e6-9e1e-5565e81f907c.png)

Everyone Permission for voice channel
![voice-channel-permission](https://cloud.githubusercontent.com/assets/17503545/20455842/b9e4f3e4-ae65-11e6-899f-0ba1be114b36.png)

**Comment by Akuba-** [comment]
It is not a bug. The everyone role is the lowest role and every other role overrides it's settings.

**Comment by Kedakai** [comment]
Yea, i know that?
If you look at the pictures carefully you should see, that "everyone" is not allowed to connect while members with the "Bot" permissions are able to connect, so i dont see the problem?

And even if we dont look at that at all. 
After i removed the code i posted above, the bot joined the channel without problems.
And you try to tell me it's not a bug, when the bot tells me, that it hasn't got enought permissions, i remove this "permission check" from the code, rebuild the docker image with another tag and start the bot with the changed code, and it works without problems?

**Comment by Akuba-** [comment]
Ups, looks like I did not read carefully enough. I actually thought the bot joined and you do not want him too.

**Comment by LateHomage** [comment]
Can confirm, bot only wants to connect when I give it the server-wide admin permission. It ignores both role and user channel overwrites. (I would give it full admin rights but I don't want it sitting in every text channel)

**Comment by KingGold171** [comment]
Ok so I duplicated your permissions exactally (no admin perms or anything but ones you have selected.
While I got the same error on bot start up of "will not join, no permission to speak"

![2016-12-12_0650_001](https://cloud.githubusercontent.com/assets/3100621/21090393/5fb36ca0-c037-11e6-9044-e6a73ce63da0.png)

After giving the bot-role `speak` it joined successfully

If no `connect` permission the bot returns

![2016-12-12_0650](https://cloud.githubusercontent.com/assets/3100621/21090392/5fb019c4-c037-11e6-98b1-26de193cd9d0.png)

I believe this issue IS NOT a bug, just coded to check for `speak` AND `connect`.

A simple fix will be to ensure the bot has
![2016-12-12_0648](https://cloud.githubusercontent.com/assets/3100621/21090391/5fab5f56-c037-11e6-80a6-82d7d1d1eac3.png)

You can still have it so @ everyone cannot connect, that doesn't effect the bot (unless bot has no roles assigned)

The code itself checks the bot for those 2 permission nodes
`
# Check if bot has `CONNECT` permission
    if not chperms.connect:
    self.safe_print("Cannot join channel "%s", no permission." % author.voice_channel.name)
    return Response(
    "Cannot join channel \"%s\", no permission." % author.voice_channel.name,
    delete_after=25
    )
# Check if bot has `SPEAK` permission
    elif not chperms.speak:
    self.safe_print("Will not join channel "%s", no permission to speak." % author.voice_channel.name)
    return Response(
    "Will not join channel \"%s\", no permission to speak." % author.voice_channel.name,
    delete_after=25
    )
`
oh and 

> And you try to tell me it's not a bug, when the bot tells me

Not a bug mate 😉

**Comment by Kedakai** [comment]
Seems not to work.
The Bot, with the Permissions above displays:
`[Command] 137215612815540224/Alexander (¬summon)
Cannot join channel "The Real OGs", no permission.`
If i want him to connect. He does not say, that he hasn't got permissions to speak.

If i set the permissions like to did above, the bot displays the same message (obviously)
Sooo, i cannot see where this is not a bug. The Bot can join and speak and tells me it has no permissions.
Again, if i remove the lines you mentions above, the bot works perfectly fine. Even without the explicit "Speak" permissions.

**Comment by KingGold171** [comment]
I made sure to test in depth before posting here.
If you would Like to DM me on Discord, (name is the same as here)

By removing the code that checks for the permissions, then it'll most likely do the same, just won't give you the error on the console.

Also it's looking for Channel perms (not role perms) aka requires it directly assigned that that voice channel, regardless of that you gave the role for global perms.

**Comment by KingGold171** [comment]
These matter and the bot checks for these
![2016-12-12_1110](https://cloud.githubusercontent.com/assets/3100621/21097272/b0ae419c-c05b-11e6-960c-4668aeb9b120.png)

Bot doesn't care if these don't exist
![2016-12-12_1109](https://cloud.githubusercontent.com/assets/3100621/21097270/b081fdda-c05b-11e6-8daa-da11f3bceb70.png)




This config works, and bot will only throw an error if i remove either one of them from the voice channel, then it says either no permission or no permission to speak

**Comment by jayktaylor** [comment]
The bot checks both the `Connect` and `Speak` permissions for the bot in the channel.  You need both of these to be ☑️ for the channel in order for the bot to function correctly.

**Comment by Kedakai** [comment]
Like i said... I've already done that.
It still shows that message:

> [Command] 137215612815540224/Alexander (¬summon) Cannot join channel "The Real OGs", no permission.

I attached into the docker container and started the bot manually.
That way i was sure whats exactly happening.

**Comment by KingGold171** [comment]
Drop me a DM with an invite to your server   shall come and take a look (just to prove what i have said and Jayden has confirmed) http://discord.me/rhinohelp

> The bot is open source. This means that you can edit, and modify the Python code to do what you want with it within reason. We are totally fine with this - but please note we will not help you in our help server on Discord, **if your problem appears to be directly caused by your changes**.

^ since you admited to removing code from the bot (bot has the checks scripts for the autojoin AND summon command)

But because im stubben as a mule, I'll still help just to prove a point.

        > And you try to tell me it's not a bug, when the bot tells me

What the bot tells you is the result of validation checks,  not a bug report

**Comment by KingGold171** [comment]
### if no connect or speak
**return no permission**
![2016-12-12_2157](https://cloud.githubusercontent.com/assets/3100621/21118547/3ba5baaa-c0b6-11e6-9b17-97da29140262.png)
![2016-12-12_0650](https://cloud.githubusercontent.com/assets/3100621/21118518/273bf7dc-c0b6-11e6-8a0f-c38dfd16ec2b.png)

----------------------------------------------------------------------

### if connect BUT no speak
**does not connect and says no permission to speak**
![2016-12-12_0639](https://cloud.githubusercontent.com/assets/3100621/21118516/2734f9dc-c0b6-11e6-807c-39cc579e67cc.png)
![2016-12-12_0650_001](https://cloud.githubusercontent.com/assets/3100621/21118519/273e509a-c0b6-11e6-94fc-9a540c6bd4b2.png)

----------------------------------------------------------------------

### if no connect BUT has speak
**return no permission**
![2016-12-12_2158](https://cloud.githubusercontent.com/assets/3100621/21118520/2741b19a-c0b6-11e6-92c4-6cc1f24c37ce.png)
![2016-12-12_0650](https://cloud.githubusercontent.com/assets/3100621/21118518/273bf7dc-c0b6-11e6-8a0f-c38dfd16ec2b.png)

----------------------------------------------------------------------

### if HAS BOTH
**work successfully**
![2016-12-12_0648](https://cloud.githubusercontent.com/assets/3100621/21118517/2736a44e-c0b6-11e6-94f5-43439f1aaf26.png)
![2016-12-12_2205](https://cloud.githubusercontent.com/assets/3100621/21118748/24731b6a-c0b7-11e6-8f6f-71f0990a1cd6.png)

**Comment by KingGold171** [comment]
@Kedakai I guess we were right and it's not a bug? Just a permissions issue your end?

**Comment by Kedakai** [comment]
@KingGold171 , nope, still a bug. I just had no time to reply or make further steps. 
I will be at home around 8pm (Timezone UTC+1). 
Will send you a message then.

**Comment by KingGold171** [comment]
We can garentee it's not a bug....

Just make sure bot has the required permissions for the voice channel you want it to join.

**Comment by Kedakai** [comment]
I am 100% absolutely sure that the permissions are setup in the right way.
I'm only the one hosting the Bot in a Docker Container. If my opinion itn't enough't, the admin of the discord server can talk with you. I've invited him to join this conversation here. Maybe you want to believe me then.

**Comment by Kedakai** [comment]
@KingGold171 , we just setup a new server to investigate the problem further.
We found out, that the permission error is not connected to the permissions of the voice chats.
The problem is that he is not allowed to see the messages in the general channel. If thats the case the bot won't join any voice channel even through he still responds in the bot test channel.
If you want to test it by yourself: https://discord.gg/5FZjQyV
Note: This is the unchanged code of yours.

**Comment by MattBSG** [comment]
I'll attempt to help you with this today if you give me proper permissions to manage channels and roles


EDIT: The issue is very weird and the bot has permission to join the voice channel, but ignores it. @Kedakai can reply with repro steps for it

**Comment by Kedakai** [comment]
These are the steps for 100% repro:
1: Create new server (because i didn't want to mess up anything) 
Then invite Bot to server.
2: Create bot text channel
3: Create bot voice channel
4: uncheck "read Messages, send messages" in server-wide permissions for "everyone"  
5: allow everyone to send, write and read older messages in the bot text channel
6: allow everyone to connect, and to speak in bot voice channel

Now, if you join the voice channel "bot" and try to summon the bot he cannot join. 
Error: "Cannot join channel "bot", no permission."

If you set Server-wide permissions for everyone to "read messages, write messages" = allow the bot can join.
If the modified code is used, bot can join even if server-wide "everyone" permissions: read Messages, write messages are unchecked.
This works in any case not depending of which role the bot has. If the role is not allowed to read or write into general, the bot permission check thinks, that the bot is not able to join, although he has permission to join.

**Comment by KingGold171** [comment]
Now we have repro steps, this has helped to finally agree with you.  It's wierd why it's going of the read and send for everyone when it's scripted to look for connect and speak.

**Comment by quicktus** [comment]
Hi
I just found out what seems to be the reson.
Apparently the bot doesnt just need connect and speak, it also needs send messages in all text channels. This is therefore a legit bug.

**Comment by Kedakai** [comment]
So, is there any update yet?

**Comment by MattBSG** [comment]
@Kedakai I am unaware if this has been fixed. If you can still reproduce it on 1.9.6_1 let me know.

**Comment by amit177** [comment]
If this is still an issue in the latest version, please open a new issue.
