### ISSUE TITLE
Audio_Cache Location

### ISSUE THREAD

**Issue by MadamJazzy** [Just-Some-Bots/MusicBot#720]
Trying to change the audio_cache location and i get an error. I changed the bot.py code to list a different location for the audio_cache folder. Tried to get support via the help server and no luck. I think i was banned because i cannot get back into the chat. Need help with this.

**Comment by KingGold171** [comment]
[403] Forbidden
Still no help modifying the bot.

**Comment by arunesh90** [comment]
We will not help you if you've modified the bot

**Comment by MadamJazzy** [comment]
I have not modified the bot yet. I'm trying to find a way to get it to do what u need it to. the bots coding is still how it was when it was downloaded. I have attempted to change it and get it working but I was unsuccesful.

Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by KingGold171** [comment]
MadamJazzy commented 8 hours ago 
> I changed the bot.py code to list a different location for the audio_cache folder

MadamJazzy commented 2 hours ago
> I have not modified the bot yet.

Try not to trip yourself over..

And please understand that 

1. You will not get help on the Help Server 
2. Posting the same issue on here after being told you won't get help on discord is "i can't read"
3. You won't get help here either for modifying the bot

**Comment by MadamJazzy** [comment]
I have 2 versions of the bot. one I have tried modifying and the other is NOT MODIFIED. I am asking if there is a way WITHOUT modifying the bot to change the download folder or have a shared cache between two versions of the bot.

Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by jayktaylor** [comment]
You need to modify the bot to do this.

- <https://github.com/Just-Some-Bots/MusicBot/blob/cb74339a08f66b5449745a397209283332d71788/musicbot/constants.py#L7>
- <https://github.com/Just-Some-Bots/MusicBot/blob/cb74339a08f66b5449745a397209283332d71788/musicbot/bot.py#L80>

As previously mentioned, we do not provide much support for modification. If you are familiar with Python, you should be fine 😃
