### ISSUE TITLE
Multiple owners 

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#725]
I have tried adding one extra person to the ownerid with there role and there personal I want too add thanks

**Comment by ghost** [comment]
Edit: I did edit example_permissions for musicmaster I set there userid and it didn't wrk soo I added there roles no wrkrd I did rename it

**Comment by jayktaylor** [comment]
Read https://github.com/Just-Some-Bots/MusicBot/wiki/Permissions for information on how to set up permissions.
