### ISSUE TITLE
Bot gives error after running on multiple servers after some time?

### ISSUE THREAD

**Issue by jacobmix** [Just-Some-Bots/MusicBot#726]
Got an error after the bot's been on two servers for some time.
It seemed to play fine on the first server. But when i joined the 2nd it rebooted it seems.
Here's my [log](https://docs.google.com/document/d/1apFcA0R0FuA4OhpPaRlOpwprHr-BfkaLJijp_w_Zi4o/edit?usp=sharing).
I've also converted most of the songs to mp3s.
The bot, and dependencies should be up to date.

**Comment by amit177** [comment]
If this is still an issue in the latest version, please open a new issue.
