### ISSUE TITLE
I'm trying to install and this shows up when i try to run the bot

### ISSUE THREAD

**Issue by hentailord** [Just-Some-Bots/MusicBot#729]
![2016-11-28 18_45_57-c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/24236431/20690985/dfd54dd2-b59b-11e6-8a30-96bcfc9c590c.png)

I don't know what the issue is. I did everything properly and this just happens :(((

**Comment by chuushi** [comment]
Have you taken time to read the printed "Problem" and "Solution" in the screenshot you provided?  Are they configured correctly?

**Comment by hentailord** [comment]
Yes. I did and I used the email account for my second discord account made for the bot

**Comment by link2110** [comment]
Come see us on discord or post an image of your (censored) credentials. You probably have a token in a password, or a password in a token.

**Comment by hentailord** [comment]
Actually I put the wrong token LOL I put the account token instead of the bot token. But thank you all for trying to help me <3
