### ISSUE TITLE
!playImmediately (Code Question)

### ISSUE THREAD

**Issue by DalenWBrauner** [Just-Some-Bots/MusicBot#733]
Code Question for the devs:
I'm trying to implement something like a !playImmediately function: a !clear, followed by a !play, followed by a !skip. Unfortunately, I can't figure out any good way to make the code wait until the song I'm adding is properly loaded into the queue, so most of the time !skip ends up finishing its execution before !play does. We like having our bot play music when the queue is empty, so this always results in our Musicbot sneaking a song from the autoplaylist in.

If anyone here thinks they might have an answer, I'd appreciate it. (I've found a bunch of terrible solutions: waiting a set amount of time, running two !play function calls in a row, etc, but I'd prefer something that's actually _guaranteed_ to work, even if it's inelegant.)

**Comment by jayktaylor** [comment]
You're better off asking here: https://discord.gg/KZBHSxz

We don't tend to provide much support for modification to the bot, especially when it is a question that is more related to how Python works than the bot itself. See the [modification page](https://github.com/Just-Some-Bots/MusicBot/wiki/Modification) for more info, and read up on [Python's `asyncio`](https://docs.python.org/3/library/asyncio-task.html).

**Comment by DalenWBrauner** [comment]
That's totally fair; thanks for the quick response!
