### ISSUE TITLE
JSON metadate error when trying to queue a soundcloud playlist or link

### ISSUE THREAD

**Issue by Brad-Sayers** [Just-Some-Bots/MusicBot#734]
[0;31mERROR:[0m Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>)

https://gyazo.com/04ddb31d75698093c7e4c4c90bb00296

https://gyazo.com/c986e9376ae113e6f3e9e707d9762d41
I hope you get back to me soon.  
Thanks!

**Comment by arunesh90** [comment]
Update your dependencies

**Comment by Brad-Sayers** [comment]
Hi Arunesh,
    I updated my dependencies on my ubuntu server and it didn't fix my issue

**Comment by arunesh90** [comment]
How did you exactly update your dependencies?

**Comment by Brad-Sayers** [comment]
I followed the steps under the ubuntu wiki

**Comment by arunesh90** [comment]
Post the output you got when updating the dependencies

**Comment by Brad-Sayers** [comment]
brad@server:~$ sudo apt-get update -y
[sudo] password for brad:
Ign:1 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu xenial InRelease
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Ign:5 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial InRelease

Hit:6 http://ppa.launchpad.net/mc3man/xerus-media/ubuntu xenial InRelease

Ign:7 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial Release

Get:8 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Ign:9 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial Release

Ign:10 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main i386
Packages
Get:11 http://archive.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Ign:12 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main all
Packages
Get:13 http://archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages
[428 kB]
Ign:14 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
Translation-en_CA
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/main i386 DEP-11
Metadata [293 kB]
Ign:16 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
Translation-en
Get:17 http://archive.ubuntu.com/ubuntu xenial-updates/main DEP-11 64x64
Icons [182 kB]
Get:18 http://archive.ubuntu.com/ubuntu xenial-updates/universe i386 DEP-11
Metadata [121 kB]
Get:19 http://archive.ubuntu.com/ubuntu xenial-updates/universe DEP-11
64x64 Icons [145 kB]
Get:20 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse i386
DEP-11 Metadata [2,516 B]
Get:21 http://archive.ubuntu.com/ubuntu xenial-backports/main i386 Packages
[4,400 B]
Get:22 http://archive.ubuntu.com/ubuntu xenial-backports/main i386 DEP-11
Metadata [208 B]
Get:23 http://archive.ubuntu.com/ubuntu xenial-backports/universe i386
DEP-11 Metadata [212 B]
Get:24 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse i386
DEP-11 Metadata [212 B]
Get:25 http://archive.ubuntu.com/ubuntu xenial-security/main i386 DEP-11
Metadata [68.2 kB]
Ign:26 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main i386
DEP-11 Metadata
Get:27 http://archive.ubuntu.com/ubuntu xenial-security/main DEP-11 64x64
Icons [43.0 kB]
Get:28 http://archive.ubuntu.com/ubuntu xenial-security/universe i386
DEP-11 Metadata [19.4 kB]
Ign:29 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
DEP-11 64x64 Icons
Get:30 http://archive.ubuntu.com/ubuntu xenial-security/multiverse i386
DEP-11 Metadata [212 B]
Ign:31 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386
Packages
Ign:32 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all
Packages
Ign:33 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
Translation-en_CA
Ign:34 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
Translation-en
Ign:35 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386
DEP-11 Metadata
Ign:36 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
DEP-11 64x64 Icons
Ign:10 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main i386
Packages
Ign:12 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main all
Packages
Ign:14 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
Translation-en_CA
Ign:16 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
Translation-en
Ign:26 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main i386
DEP-11 Metadata
Ign:29 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
DEP-11 64x64 Icons
Ign:31 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386
Packages
Ign:32 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all
Packages
Ign:33 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
Translation-en_CA
Ign:34 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
Translation-en
Ign:35 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386
DEP-11 Metadata
Ign:36 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
DEP-11 64x64 Icons
Ign:10 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main i386
Packages
Ign:12 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main all
Packages
Ign:14 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
Translation-en_CA
Ign:16 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
Translation-en
Ign:26 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main i386
DEP-11 Metadata
Ign:29 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
DEP-11 64x64 Icons
Ign:31 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386
Packages
Ign:32 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all
Packages
Ign:33 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
Translation-en_CA
Ign:34 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
Translation-en
Ign:35 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386
DEP-11 Metadata
Ign:36 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
DEP-11 64x64 Icons
Ign:10 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main i386
Packages
Ign:12 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main all
Packages
Ign:14 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
Translation-en_CA
Ign:16 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
Translation-en
Ign:26 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main i386
DEP-11 Metadata
Ign:29 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
DEP-11 64x64 Icons
Ign:31 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386
Packages
Ign:32 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all
Packages
Ign:33 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
Translation-en_CA
Ign:34 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
Translation-en
Ign:35 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386
DEP-11 Metadata
Ign:36 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
DEP-11 64x64 Icons
Ign:10 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main i386
Packages
Ign:12 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main all
Packages
Ign:14 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
Translation-en_CA
Ign:16 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
Translation-en
Ign:26 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main i386
DEP-11 Metadata
Ign:29 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
DEP-11 64x64 Icons
Ign:31 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386
Packages
Ign:32 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all
Packages
Ign:33 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
Translation-en_CA
Ign:34 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
Translation-en
Ign:35 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386
DEP-11 Metadata
Ign:36 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
DEP-11 64x64 Icons
Err:10 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main i386
Packages
  404  Not Found
Ign:12 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main all
Packages
Ign:14 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
Translation-en_CA
Ign:16 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
Translation-en
Ign:26 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main i386
DEP-11 Metadata
Ign:29 http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial/main
DEP-11 64x64 Icons
Err:31 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386
Packages
  404  Not Found
Ign:32 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all
Packages
Ign:33 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
Translation-en_CA
Ign:34 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
Translation-en
Ign:35 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386
DEP-11 Metadata
Ign:36 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main
DEP-11 64x64 Icons
Fetched 1,614 kB in 16s (96.4 kB/s)

AppStream cache update completed, but some metadata was ignored due to
errors.
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/chris-lea/libsodium/ubuntu
xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore
potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration
details.
W: The repository 'http://ppa.launchpad.net/mc3man/trusty-media/ubuntu
xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore
potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration
details.
E: Failed to fetch
http://ppa.launchpad.net/chris-lea/libsodium/ubuntu/dists/xenial/main/binary-i386/Packages
 404  Not Found
E: Failed to fetch
http://ppa.launchpad.net/mc3man/trusty-media/ubuntu/dists/xenial/main/binary-i386/Packages
 404  Not Found
E: Some index files failed to download. They have been ignored, or old ones
used instead.

**Comment by arunesh90** [comment]
https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Ubuntu#5-start

**Comment by Brad-Sayers** [comment]
Ugh i cant believe i completely overlooked that section.  It now works.  Sorry for wasting your time

**Comment by arunesh90** [comment]
No problem
