### ISSUE TITLE
"Your config files are missing" even though config files are there

### ISSUE THREAD

**Issue by soya-daizu** [Just-Some-Bots/MusicBot#736]
Im running this MusicBot with CentOS VPS.
Suddenly, when I tried to run "run.py" with "python ~/MusicBot/run.py", it returns error below

```
[config] Config file not found, copying example_options.ini

An error has occured:

  Problem:  Your config files are missing.  Neither options.ini nor example_options.ini were found.                                     
  Solution: Grab the files back from the archive or remake them yourself and copy paste the content from the repo.  Stop removing important  files!
```

i checked many times that config file is there (options.ini and permissions.ini) but still returns this error.
any solution?

**Comment by dannyvoid** [comment]
cd to the MusicBot folder before running the command and it should work.

**Comment by jayktaylor** [comment]
^

**Comment by caves123** [comment]
I need help Keep saying Config not found options.ini nor example.options.ini were found
