### ISSUE TITLE
Help creating a playlist

### ISSUE THREAD

**Issue by MartinMolen** [Just-Some-Bots/MusicBot#739]
Hey, I was just curious about how the playlists works, and how to create them.
I have tried to do !pldump (playlisturl) but that does not work.

**Comment by 1337Steven1337** [comment]
It should work, check if your link is correct.
Once you got a dumped playlist you have to go to BOTFOLDER\config\autoplaylist.txt and replace everything in autoplaylist.txt with your newly dumped playlist.

**Comment by link2110** [comment]
The pldump command should also output a `playlist.txt` in chat for you to click to download. 

![](https://i.imgur.com/Vt7Jzhf.png)


The `autoplaylist.txt` is one url per line, and will play when nothing is queued and the option to use it is on.
