### ISSUE TITLE
[request] Bot should autosummon without owner being connected to a channel.

### ISSUE THREAD

**Issue by Bergster** [Just-Some-Bots/MusicBot#74]
It's tedious to start the bot if you don't plan on staying in the voice channel afterwards. There should be an option to designate a channel the bot should join upon startup, rather than having the owner be in the voice channel beforehand.

**Comment by Chewsterchew** [comment]
+1 on this.

**Comment by ignasmomo** [comment]
+1

**Comment by imayhaveborkedit** [comment]
Please don't leave low effort comments.  There's literally a +1 button for this express purpose now.  Use that instead.

**Comment by imayhaveborkedit** [comment]
There's now an option to set a channel to autosummon to in review.
