### ISSUE TITLE
[Issue] Can't update my dependencies

### ISSUE THREAD

**Issue by Catalyze** [Just-Some-Bots/MusicBot#742]
When I run the 'update_deps.bat' it just says 
'C:\Users\Leon\AppData\Local\Programs\Python\Python35\python.exe: Error while finding spec for 'pip.__main__' (<class 'ImportError'>: cannot import name 'pkg_resources'); 'pip' is a package and cannot be directly executed'

I tried reinstalling, python, git and the MusicBot itself, nothing worked.

**Comment by Brad-Sayers** [comment]
I am also having this issue.  I was told to update my dependencies.  I am running my bot on ubuntu so i did.  Even though i updated my dependencies my problem wasnt fixed

**Comment by arunesh90** [comment]
@Brad-Sayers this is not related to your issue

**Comment by Catalyze** [comment]
Whiped my python completely and reinstalled it; everything's working now.
