### ISSUE TITLE
Adding command makes bot.py unrunable | can't fix

### ISSUE THREAD

**Issue by ScubaDiving** [Just-Some-Bots/MusicBot#744]
So, like the title suggests, I tried to add a command to fetch and view lyrics. I'm pretty sure the command itself is working, but the bot just won't work saying there is indentation error. I tried replacing the spaces with tabs and the other way around but it doesn't seem to work. The Question is - in what environment was the code written and how indentation is made there? I'll try to match it in my own code.

I'm attaching the code so whoever wishes to check this for themselves can confirm that I'm either right or stupid.

Thanks in advance!
[lyrics.zip](https://github.com/Just-Some-Bots/MusicBot/files/629388/lyrics.zip)

**Comment by arunesh90** [comment]
https://github.com/Just-Some-Bots/MusicBot/wiki/Modification
