### ISSUE TITLE
Issue with Permissions

### ISSUE THREAD

**Issue by Iraelaemei** [Just-Some-Bots/MusicBot#747]
According to the Permissions.ini the Default group is a catch-all for anyone not assigned to a group. However in that group, no one (but myself, the owner) can adjust the volume, or pause a song. I have tried to adjust the permissions.ini file but no luck. What am I doing wrong, and what more information would you need?

Thanks!

**Comment by chuushi** [comment]
Did you create any new group?  You're not being specific on what you tried to adjust.  Have you checked the wiki?
https://github.com/Just-Some-Bots/MusicBot/wiki/Permissions

**Comment by Iraelaemei** [comment]
I have not created a new group, when I don't assign someone to a group, it is my understanding that they are in the Default group (which has full permissions). If that is indeed the case then why can't someone in the default group use commands like summon, pause, and volume?

**Comment by chuushi** [comment]
As you can see [here](https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_permissions.ini#L69):
```ini
[Default]
CommandWhitelist = play perms queue np skip search id help clean
; CommandBlacklist =
IgnoreNonVoice = play skip search
```

the default group can only use the commands in the list `CommandWhitelist`.  If you want to allow everyone to use more commands, you will have to add on to the `CommandWhitelist`.  I think you may be better off using `CommandBlacklist` if you are looking into giving everyone all permissions..

**Comment by Iraelaemei** [comment]
Thanks! That worked
