### ISSUE TITLE
You don't have permission to use that command. Reason: This command is not enabled for your group (Default).

### ISSUE THREAD

**Issue by Bracci19** [Just-Some-Bots/MusicBot#748]
I made a music bot for one of my servers, but I am the only one that can summon the bot to any of the channels in the sever. I made a separate account to try and fix the issue but I still don't understand it. I use the command !Summon and then the "You don't have permission to use that command.
Reason: This command is not enabled for your group (Default)." error message appears. I have no programming background so I apologize in advance if I don't understand. I looked around the internet and found to make group roles in discord and then assign them to the bot in the permissions.ini but that still gives me the error code when trying to summon the bot from a none owner account.

**Comment by arunesh90** [comment]
Check https://github.com/Just-Some-Bots/MusicBot/wiki/Permissions
