### ISSUE TITLE
Step 4: Terminal Permissions on Mac not working(solved)

### ISSUE THREAD

**Issue by PublicMenace** [Just-Some-Bots/MusicBot#753]
When i type chmod +x in my terminal it says:
MacBook-Pro-13:~ Johan$ chmod +x 
usage:	chmod [-fhv] [-R [-H | -L | -P]] [-a | +a | =a  [i][# [ n]]] mode|entry file ...
	chmod [-fhv] [-R [-H | -L | -P]] [-E | -C | -N | -i | -I] file ...
I don't know whats wrong...
Thanks in advance,
Johan

**Comment by arunesh90** [comment]
you also need to define a file
