### ISSUE TITLE
Nothing really happens when i run the runbot.command command

### ISSUE THREAD

**Issue by PublicMenace** [Just-Some-Bots/MusicBot#754]
/Users/Johan/Desktop/MusicBot/runbot_mac.command ; exit;
MacBook-Pro-13:~ Johan$ /Users/Johan/Desktop/MusicBot/runbot_mac.command ; exit;
/Users/Johan/Desktop/MusicBot/runbot_mac.command: line 8: python3.5: command not found
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
 Thats basically everything that happens...

**Comment by PublicMenace** [comment]
This is probably a PEBKAC, but i really don't get it.

**Comment by PublicMenace** [comment]
Step 5 says:
"5: Run

In the main folder (called MusicBot), double-click update_macdeps.command to install the required Python dependencies. After it is finished, you can close the window and then double-click runbot_mac.command to run the bot.

If you close Terminal, your bot will stop working. This window is required to be open for the bot to run. The bot will also stop if you turn your computer off, sleep, or hibernate it. To avoid these issues, you can buy a dedicated server."
but how should the code really look in my terminal?

**Comment by KingGold171** [comment]
Im guessing its not reconising `python3.5` as a command,  

so maybe you don't have

- Python installed
- Pythan added to PATH
