### ISSUE TITLE
the bot get to lasy for the sound come out the app 

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#755]

**Comment by arunesh90** [comment]
eh what?

**Comment by ghost** [comment]
the come out the to sound get lazy

**Comment by arunesh90** [comment]
What do you mean exactly with that? That it's stuttering?

**Comment by ghost** [comment]
hold

**Comment by ghost** [comment]
[voicerecrder.zip](https://github.com/Just-Some-Bots/MusicBot/files/647540/voicerecrder.zip)

with open good sound for the bot

**Comment by arunesh90** [comment]
If your bot is lagging when playing music
- Check CPU/disk usage
- Can your PC/the VPS' bandwidth/speed handle the bot?
- Is there an issue on https://status.discordapp.com?

**Comment by ghost** [comment]
ty
