### ISSUE TITLE
Changing audio cache folder, storage of cache in RAM

### ISSUE THREAD

**Issue by gccpy** [Just-Some-Bots/MusicBot#756]
MusicBot causes many writes to my already burdened sd card, by storing every song it downloads. Due to limited space I configured it to delete the files after usage.

Can entire cache be stored in RAM instead?

**Comment by KingGold171** [comment]
The audio_cache CANNOT be stored in RAM as it is small files of just the audio with each song.
Raspberry Pi only has either 512mb or 1GB (PI3) of RAM so even if it was possible space would be even more limited

 you can either

> SaveVideos = no

in options.ini to disable the cache

or take a look at  #720 for how to change the location.

![lgwx8ga](https://cloud.githubusercontent.com/assets/3100621/21161798/034f6f30-c182-11e6-94e9-c7e496dd317d.png)

**Comment by gccpy** [comment]
PI2 has 1Gb, which is more than enough for one song. I don't need a cache of library of all the songs every user on the server plays, that would kill my regular hard disk, not to mention a much less robust sd card.

As a workaround I added an entry to fstab so that audio_cache points to a ramdisk and disabled SaveVideos, however the hack to add local folders to fstab is really dirty. 

Modifying the code would be my last resort, so just out of curiosity why did the dev team decide against adding custom cache folder to options? 

Setting it to /tmp/ramdisk/musicbot_audio_cache/ in my case would at least prevent fstab modification if i ever move the code to a different folder.
