### ISSUE TITLE
Noob question - Not connecting to text channels

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#759]
Hey,
On my options.ini file I have the same IDs for Bindtochannels and Autojoinchannels.
When I run the bot, it says "Cannot join text channels" but is able to join the voice channels. 
In the options.ini file the config looks like this:
```
BindToChannels = ID1 (text), ID2 (voice), ID3 (text), ID4 (voice)
AutojoinChannels = ID1 (text), ID2 (voice), ID3 (text), ID4 (voice)
```
OS: Mac OS X Lion 10.7.5
All dependencies installed, running in Terminal.app.
More logs (from runbot_mac.command's run):
```
Bound to text channels:
 - ili's server/musicbot
 - M u s i c/music

Not binding to voice channels:
 - M u s i c/Music
 - ili's server/Music

Autojoining voice chanels:
 - M u s i c/Music
 - ili's server/Music

Cannot join text channels:
 - ili's server/musicbot
 - M u s i c/music
```
Hope you guys can help. 
Thanks

**Comment by ili-codes** [comment]
More logs (from runbot_mac.command's run):
```
Bound to text channels:
 - ili's server/musicbot
 - M u s i c/music

Not binding to voice channels:
 - M u s i c/Music
 - ili's server/Music

Autojoining voice chanels:
 - M u s i c/Music
 - ili's server/Music

Cannot join text channels:
 - ili's server/musicbot
 - M u s i c/music
```

**Comment by ghost** [comment]
For some odd reason, each time I post a GitHub issue on the problem at hand, it magically fixes itself. :/ 

Closing now. 

Anyone who has this problem: Just restart the bot a few times. It'll try to connect for a while, but then it'll finally get connected to voice and text.
