### ISSUE TITLE
Random jumping in voice channels

### ISSUE THREAD

**Issue by brawaru** [Just-Some-Bots/MusicBot#760]
But jumps from channel to channel *randomly*:
![](http://i.imgur.com/2JN6fJJ.gif) 

Latest lines from log
https://gist.github.com/DaFri-Nochiterov/73297f5373567b82f25c6299ed0cc7f4

 ¯\\\_(ツ)_/¯

**Comment by arunesh90** [comment]
I guess someone is moving the bot, ask your staff if they are doing it.

**Comment by brawaru** [comment]
No, lol. Nobody of server staff was online at this time. Bot started flooding in logs and join/leave random channels of the server. This is not first time when something same happens. I remember when at morning I detected, that joined/left single voice channel about 300 times by the logs.  I think somewhere in code exists bug and bot just stucks in Infinite loop.

**Comment by arunesh90** [comment]
try changing voice region

**Comment by KingGold171** [comment]
Maybe a member of your staff **WAS** online?
![2016-12-17_0619](https://cloud.githubusercontent.com/assets/3100621/21284884/def828ce-c420-11e6-9573-ece29ea63a60.png)

**Comment by ImthePeach** [comment]
There would be no reason for the bot doing this. Someone must be moving it. Do you have multiple voice channel ID's listed in the options file for autojoinchannels? If you do the bot may be picking ones at random and your server region may have been having issues causing the bot to restart multiple times, otherwise there is no reason for the bot to be doing this.

**Comment by brawaru** [comment]
It disconnected after long session without restarts and started to join channels where it was some time ago. I saw this 2 times after creating this issue and tried to find "random", so... it's not random, bot just creates multiple sessions and tries to join every channel where it was, then after joining in one of them, other sessions gets "errors" and trying to join again. Don't know how it even works. Anyways, this bug is hidden somewhere, so If I'll ever get repro steps, I will create new issue. 🙂


*sorry for my bad English*
