### ISSUE TITLE
autoplaylist.txt empty when disconnect

### ISSUE THREAD

**Issue by TheIndra55** [Just-Some-Bots/MusicBot#761]
Hi

When my internet disconnects the bot's autoplaylist will be empty

Screenshot: https://s.theindra.eu/?img=15-03-06.png

**Comment by jayktaylor** [comment]
When the bot cannot play a song from the autoplaylist, it removes it. This is meant for when the video no longer exists or something similar, but obviously having no internet connection will cause it to happen too. In the `review` branch, removed songs are backed up to a different file to try and negate this issue.
