### ISSUE TITLE
Unauthorized (Soundcloud)

### ISSUE THREAD

**Issue by ryand56** [Just-Some-Bots/MusicBot#763]
I need help

**Comment by ryand56** [comment]
[0;31mERROR:[0m Unable to download API page: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>)

**Comment by KingGold171** [comment]
401: If you are having issues playing music from certain websites such as soundcloud such as

> 0;31mERROR:[0m Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>)

Resolution

On Windows run update_deps.bat
On Mac run update_macdeps.command
On Linux run sudo pip install --upgrade youtube-dl
