### ISSUE TITLE
Youtube playlist in the autoplaylist.txt

### ISSUE THREAD

**Issue by rayschpp** [Just-Some-Bots/MusicBot#766]
Hi, 

first of all great work with the bot, works perfect on our servers.
Now to my question is it possible to insert in the autoplaylist.txt just a single youtube link to a playlist where others can contribute and attach to the playlist, and let the bot just restart at the end the playlist again?

If not how could be an easy workaround look like to achieve that, letting others add songs to the playlist?

Thx for the help already, and Merry Christmas.

Our setup: the bot is running on a centos azur server.

**Comment by MattBSG** [comment]
No, you can only use single song links right now. Use !pldump <link> to get a file with every YouTube link in a playlist to put in autoplaylist.txt

**Comment by rayschpp** [comment]
Ok thanks for the fast respond and help.

Maybe as a coming feature make the !pldump command write directly in the autoplaylist.txt and let it add the songs to the playlist if they aren't already inside.
