### ISSUE TITLE
!pldump not dumping all songs in a YouTube playlist?

### ISSUE THREAD

**Issue by Forstride** [Just-Some-Bots/MusicBot#767]
I tried dumping all of the songs from this playlist: https://www.youtube.com/playlist?list=PLnh5qZl7j7wDiFhhMqsdgUIhYXPC5K0X7, which has 711 videos, but !pldump only dumps 653 of them.

Any idea what could be causing this?

**Comment by KingGold171** [comment]
Maybe some videos in the playlist are private? or removed? or not availible in your country?

**Comment by Forstride** [comment]
I added all of the videos to the playlist manually (As in, going through each video and clicking Add To Playlist), and all of them worked just fine, so that's not it.

**Comment by KingGold171** [comment]
After running pldump on both Master and Review I also got 653/711

I scrolled though your playlist and noticed a few duplicates
![2016-12-17_0751](https://cloud.githubusercontent.com/assets/3100621/21285370/40ab9a26-c42e-11e6-9c60-73d252943475.png)
![2016-12-17_0752](https://cloud.githubusercontent.com/assets/3100621/21285369/40a84c22-c42e-11e6-9ed0-d1a4d94db846.png)

If you removed the duplicates, do you get 653 on youtube?

Not 100% certain but maybe bot is smart enough to avoid adding these many times as it already exists.

(I know you can spam 1 URL as many times you you wish in autoplaylist.txt manually, but could just be a thing on !pldump)

**Comment by Forstride** [comment]
Yeah, that seems to be it.  YouTube does get kind of screwy when trying to add videos to a playlist, so I guess that's why.
