### ISSUE TITLE
Volume normalization feature request

### ISSUE THREAD

**Issue by gccpy** [Just-Some-Bots/MusicBot#768]
I've been having a problem with differences in song volume. If someone plays some moderately quiet song, like say some slow 80s music, and immediately after somebody puts on some techno -- the volume gap is very noticeable and distracting. 

Is it possible to add some sort of volume normalization?

**Comment by stuntguy3000** [comment]
Already requested, and it's coming soon(TM).

**Comment by jayktaylor** [comment]
#156
