### ISSUE TITLE
Bot stops working after a while

### ISSUE THREAD

**Issue by ikatzuchi21** [Just-Some-Bots/MusicBot#77]
When the bot is on for a long time it just start to be glitch and not play anything and any commands do not work properly at that point. If you could add a restart function for so it will reboot without having to close the bot

**Comment by Chew** [comment]
Helpful Hint:
If the bot works perfectly for a few songs or more. Then it just stops mid-song, using `(COMMAND-PREFIX)skip` will solve your troubles. It will skip song and should get back to working. If it connects but doesn't work the first time, second or third times a charm
