### ISSUE TITLE
[Feature] Make the bot play an internet radio station.

### ISSUE THREAD

**Issue by mee4895** [Just-Some-Bots/MusicBot#770]
Is it possible to make the bot (maybe even instead of the autoplaylist) relay an internet radio station by entering a command like `!radio <url>`.

**Comment by MattBSG** [comment]
Already in review branch. !stream

**Comment by mee4895** [comment]
Sry just searched through the open Issues.

Keep up the good work :-D and thanks for the bot I use it nearly every day.
