### ISSUE TITLE
Unable to download API page

### ISSUE THREAD

**Issue by newchild** [Just-Some-Bots/MusicBot#772]
Whenever I try to use the play command it does not work.

[Command] 137472421061066752/Fabian (!play sing me to sleep)
ERROR: Unable to download API page: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))
ERROR: Unable to download API page: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))
<class 'musicbot.exceptions.CommandError'>: Error extracting info from search string, youtubedl returned no data.  You may need to restart the bot if this continues to happen.

(Restarting did not help)

**Comment by KingGold171** [comment]
Try updating the dependencies.
