### ISSUE TITLE
How to setup the bot to only get commands from specified text channel?

### ISSUE THREAD

**Issue by kubamusic** [Just-Some-Bots/MusicBot#775]
I want to setup the bot only to get commands from a specified text channel on the server. I mean if you post a !command on #general text channel and the bot is set only to get commands from #commands the bot is gonna ignore that command.
Is that possible?
Thanks.

**Comment by MattBSG** [comment]
BindToChannels in options.ini

You put the id of #commands there, or any channel for that matter
https://github.com/Just-Some-Bots/MusicBot/wiki/FAQ#how-do-i-get-an-id
