### ISSUE TITLE
no idea what this is.

### ISSUE THREAD

**Issue by Porkchucker** [Just-Some-Bots/MusicBot#778]
```
C:\Users\gayretard\Desktop\MusicBot-1.9.5_1\MusicBot-1.9.5_1\musicbot\bot.py:459: DeprecationWarning: change_status is deprecated, use change_presence instead.
  await self.change_status(game) 
```

Keeps telling me that after I open runbot.bat or whenver a song is done. Long pauses. What is fucked up? I downloaded two different versions and still have this problem.

**Comment by chuushi** [comment]
There's no problem with the bot.  The message just says that a Python function [`change_status()`](https://github.com/Just-Some-Bots/MusicBot/blob/master/musicbot/bot.py#L467) is deprecated and should use `change_presence()` instead.

You don't have to worry about it, as the review branch fixes it.

**Comment by Porkchucker** [comment]
Gotcha
