### ISSUE TITLE
[Request] Show which site the song is from and more

### ISSUE THREAD

**Issue by lilyremigia** [Just-Some-Bots/MusicBot#779]
Formula could be: Now Playing in {Channel}: **{Song Name}** from {Song's Site}
Example could: Now Playing in Music Room: **Example Song** from Youtube
And if you see fancy add in the uploader's name too.
And if you want it super fancy maybe add in filtering options too.

Anyway, thanks for reading.

**Comment by sn8to** [comment]
Yeah, this seems like a good idea. +1 vote for adding it. (Although most if not every song from search is on YouTube, anyway. Barely anybody does the link to anywhere other than YouTube)

**Comment by ImthePeach** [comment]
like this?
![image](https://cloud.githubusercontent.com/assets/17447156/21830560/c4ea343e-d75a-11e6-8416-a2ee85d6ee20.png)

**Comment by jayktaylor** [comment]
Added in review
