### ISSUE TITLE
"non monotonically increasing" Error message

### ISSUE THREAD

**Issue by DasLetsPlaySchaf** [Just-Some-Bots/MusicBot#78]
![snap_00023](https://cloud.githubusercontent.com/assets/17067148/12860216/7e4b3baa-cc5b-11e5-80f0-d80b59ad151c.png)

What does it mean?

**Comment by DasLetsPlaySchaf** [comment]
Oh and in the review build it skips all deletions. :/

**Comment by imayhaveborkedit** [comment]
It's a warning from ffmpeg, you can ignore it.  I'll look into the song deletions breaking.
