### ISSUE TITLE
Cant Start My Bot And Update deps

### ISSUE THREAD

**Issue by NotMrMelon** [Just-Some-Bots/MusicBot#782]
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

this is my problem the text under here is the total command prompt text

Requirement already up-to-date: discord.py[voice]~=0.12.0 in c:\users\diémo\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: youtube-dl in c:\users\diémo\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 2))
Collecting pip (from -r requirements.txt (line 3))
  Using cached pip-9.0.1-py2.py3-none-any.whl
Requirement already up-to-date: cffi==1.6.0 in c:\users\diémo\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: aiohttp<1.1.0,>=1.0.0 in c:\users\diémo\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: websockets<4.0,>=3.1 in c:\users\diémo\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: PyNaCl==1.0.1 in c:\users\diémo\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: pycparser in c:\users\diémo\appdata\local\programs\python\python35\lib\site-packages (from cffi==1.6.0->-r requirements.txt (line 4))
Requirement already up-to-date: chardet in c:\users\diémo\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: multidict>=2.0 in c:\users\diémo\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: async-timeout in c:\users\diémo\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: six in c:\users\diémo\appdata\local\programs\python\python35\lib\site-packages (from PyNaCl==1.0.1->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Installing collected packages: pip
  Found existing installation: pip 7.1.2
Exception:
Traceback (most recent call last):
  File "C:\Users\Diémo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\basecommand.py", line 211, in main
    status = self.run(options, args)
  File "C:\Users\Diémo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\commands\install.py", line 311, in run
    root=options.root_path,
  File "C:\Users\Diémo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "C:\Users\Diémo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_install.py", line 673, in uninstall
    for path in pip.wheel.uninstallation_paths(dist):
  File "C:\Users\Diémo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\wheel.py", line 512, in unique
    for item in fn(*args, **kw):
  File "C:\Users\Diémo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\wheel.py", line 531, in uninstallation_paths
    r = csv.reader(FakeFile(dist.get_metadata_lines('RECORD')))
  File "C:\Users\Diémo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1619, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "C:\Users\Diémo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1616, in get_metadata
    return self._get(self._fn(self.egg_info, name)).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 22367: invalid continuation byte
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\DIMO~1\Desktop\MusicBot>

**Comment by Daniel7689** [comment]
Try to uninstall and install again python
i guess i don't know if this will help...

**Comment by NotMrMelon** [comment]
no it doesnt work

**Comment by ImthePeach** [comment]
```
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```
The very bottom of that mumble jumble you posted gives you a hint. Otherwise uninstall python and download the latest version of it from their site 3.5.2 I believe it is and install it properly. `check the box that says install to path`. From there you can update_deps again.

**Comment by ImthePeach** [comment]
If that doesn't work then its possible it still didn't install to path or is continuing to run an older version of python and pip. do the following in a new CMD console

```
py -3 -m pip install --upgrade pip
C:\\Windows\\py.exe -3.5 -m pip install --upgrade pip
```

**Comment by Daniel7689** [comment]
:+1:
