### ISSUE TITLE
Issue when starting runbot.bat

### ISSUE THREAD

**Issue by michxu** [Just-Some-Bots/MusicBot#785]
Already got the config done but when I open runbot.bat - this message keeps repeating...
![cawpture](https://cloud.githubusercontent.com/assets/24831857/21554033/846687fe-cdc9-11e6-9e83-89f46af92bfc.JPG)

**Comment by jayktaylor** [comment]
You're using an outdated version of the bot. Follow the guides here https://github.com/Just-Some-Bots/MusicBot/wiki
