### ISSUE TITLE
PlayNext Command - Prepend Queue

### ISSUE THREAD

**Issue by TheBrambleShark** [Just-Some-Bots/MusicBot#786]
I propose a new command be added:

`!playnext <search terms>`
`!playnext <URL>`

Functionally, it would be identical to the existing `!play` function except that it prepends the song to the start of the queue instead of the end. This would guarantee that the selected song is played next, barring download failures or not having the song before the next one starts playing... the usual things.

Functionally this shouldn't be too hard to add.... you may have to create a new list in memory and dispose of the old one, but it shouldn't be too much of a hassle with the right helper functions.

Amendment: I don't use github for this too often.... can someone add the Feature Request label? I don't see where to do that...

**Comment by KingGold171** [comment]
#733

**Comment by jayktaylor** [comment]
I'm treating #733 as a question and this as a request.

**Comment by ImthePeach** [comment]
#205 reference as well. Replacing this issue with the one currently in the playlists milestone for better wording.

**Comment by Selkea** [comment]
I actually implemented this command myself (along a couple others) a few weeks ago without much difficulty, and I don't have prior experience with Python, though I'm not new to coding (worked with C++/C#). If you take some time to read up on some online Python documentation and pay attention to how the authors wrote the bot, you should be able to do this yourself OP

**Comment by Naitotchi** [comment]
I came here to request this feature! this would be amazingly helpful!

**Comment by flatlin-e** [comment]
Commenting to definitely approve of this feature as well!

**Comment by flatlin-e** [comment]
Bumping. Please add this! Been waiting so long
