### ISSUE TITLE
Removing the bot

### ISSUE THREAD

**Issue by Firesquirrel66** [Just-Some-Bots/MusicBot#787]
I was wondering what the most effective and clean way of removing the bot is. Is it as simple as deleting the folder, or is there some more clean up I would then have to do in other places?

**Comment by sn8to** [comment]
If you do decide to delete the folder, that will be just about it for removing the bot from your hard drive. Any installed programs such as FFmpeg will stay on there, but all of the bot files will in fact be gone. However, this does not delete the bot itself. The bot account will still exist.

**Comment by KingGold171** [comment]
You can delete your bot account @ https://discordapp.com/developers/applications/me

**Comment by jayktaylor** [comment]
To delete the bot, just remove the folder.
