### ISSUE TITLE
Redpill me on Jake

### ISSUE THREAD

**Issue by beng** [Just-Some-Bots/MusicBot#788]
please redpill me on jake

- [exhibit a](https://github.com/Just-Some-Bots/MusicBot/blob/cb74339a08f66b5449745a397209283332d71788/musicbot/bot.py#L1192-L1193)
- [exhibit b](https://github.com/Just-Some-Bots/MusicBot/blob/cb74339a08f66b5449745a397209283332d71788/musicbot/config.py#L24)

**Comment by KingGold171** [comment]
Well this was a waste of an issue...
