### ISSUE TITLE
How can I disable !joinserver 

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#789]
its a private bot and only for my server, how can i disable the !joinserver command so people cant add the bot

**Comment by ImthePeach** [comment]
The `!joinserver` command is an `@owner` only command. Only the persons id under the OwnerID setting in the options file can use it. Any and all other commands can be blacklisted or whitelisted for use of others in the permissions file please see our [Permissions](https://github.com/Just-Some-Bots/MusicBot/wiki/Permissions) page for more info.
