### ISSUE TITLE
!pldump - Unable to extract title

### ISSUE THREAD

**Issue by Crakila** [Just-Some-Bots/MusicBot#790]
Hey guys. New Year New Issues 😝 (Happy New Year to ya's)

Doing a `!pldump <youtube playlist URL>` is returning the following in Discord:

```
Could not extract info from input url
[0;31mERROR:[0m Unable to extract [0;34mtitle[0m
```

In the console, it is showing the following:

```
[Command] 60687148793204736/VampiricPadraig (!pldump https://www.youtube.com/playlist?list=PLK9Sc5q_4K6aNajVLKtkaAB1JGmKyccf2)
ERROR: Unable to extract title
<class 'musicbot.exceptions.CommandError'>: Could not extract info from input url
ERROR: Unable to extract title
```

Rest of the commands do work, just not this one (I normally use this to update the `autoplaylist.txt` file)

cat /etc/debian_version = 8.6

Any help would be appreciated. :)

**Comment by ImthePeach** [comment]
Currently working in the `REVIEW` branch. 
![image](https://cloud.githubusercontent.com/assets/17447156/21585277/6033c960-d07a-11e6-9d86-67acaab709e6.png)

Try updating dependencies, something may be out of date.

**Comment by Crakila** [comment]
Updated all my packages on my server (`sudo apt-get upgrade`) and restarted the bot and it now works. I think youtube-dl updated for another package and something went screwy. :)
