### ISSUE TITLE
Couldn't command my bot

### ISSUE THREAD

**Issue by bbyyw** [Just-Some-Bots/MusicBot#791]
i just can't give command such as !play or !stop etc, please help

**Comment by FreshDumbldore** [comment]
Have you entered your users or group id's into the permissions.ini file?
Do this with enabled discord developer mode so you can copy them.

**Comment by Techno11** [comment]
Your question was very vague.... Go here to talk to some people who may be able to help you: http://discord.me/rhinohelp @bbyyw

**Comment by FreshDumbldore** [comment]
Who's question? his or mine? @Techno11

**Comment by Techno11** [comment]
@bbyyw 's Question, sorry.

**Comment by FreshDumbldore** [comment]
not a problem but i get the feeling that people don't read the "readme" on purpose so they can ask question that are all answered in their :D

**Comment by Techno11** [comment]
Yes, that, and sometimes it seems the user never read the setup instructions either.

**Comment by bbyyw** [comment]
solved guys, sorry i just forgot to save some settings xD i was so confused yesterday

**Comment by Techno11** [comment]
If you solved the issue click the "Close Issue" button at the bottom of the comment input field

**Comment by bbyyw** [comment]
thank you @Techno11

**Comment by Techno11** [comment]
Glad I could help @bbyyw
