### ISSUE TITLE
How i can add more owner?

### ISSUE THREAD

**Issue by angelocipullo** [Just-Some-Bots/MusicBot#793]
Hi, i love your bot, it's fantastic and fully funcional, but, there is a way to add more owner? (or a simple way to make that an user can use the bot )

**Comment by FreshDumbldore** [comment]
Sorry if i ask but are you too stupid to read the readme?
Everything is explained in there. Enable the developer mode in discord, copy all your desired player and/or room id's and enter them into the permissions.ini file.
not a problem,was it?
In case you are confused: https://github.com/Just-Some-Bots/MusicBot/blob/master/README.md

**Comment by angelo001** [comment]
Saluti, Angelo

Il giorno 03 gen 2017, alle ore 15:14, FreshDumbldore <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Sorry if i ask but are you too stupid to read the readme?
Everything is explained in there. Enable the developer mode in discord, copy all your desired player and/or room id's and enter them into the permissions.ini file.
not a problem,was it?

-

**Comment by angelo001** [comment]
i've readed yet the readme, but there is no specified how. if i want add 2 owner, it's like this?
`[Permissions]
; This number should be your id.  It gives you full permissions.  You do not put the bot's id here.  That's silly.
; If you don't know how to get this, scroll up a bit and read the part that says "HOW TO GET VARIOUS IDS"
; If you can't do that for some reason, join the help server (invite in the readme) and type this in chat: !id
; If you still don't understand, watch this https://streamable.com/4w8e and may your respective deity have mercy on your soul.
; I don't want any more "how do I get the OwnerID" questions.
OwnerID = ID1, ID2
`

**Comment by angelocipullo** [comment]
i've readed yet the readme, but nothing. if (for example) i want add 2 owner, the code is like this?

OwnerID = ID1, ID2

**Comment by FreshDumbldore** [comment]
take the comma out and you are golden (ID1 ID2) just let a space between it

**Comment by angelocipullo** [comment]
oh ok, thanks a lot!

**Comment by angelocipullo** [comment]
ok, now i've tested this thing, and don't work

that's the error

An error has occured reading the config:

  Problem:  An invalid OwnerID was set.
  Solution: Correct your OwnerID.  The ID should be just a number, approximately 18 characters long.  If you don't know             what your ID is, use the /id command.  Current invalid OwnerID: 196672599542071296 265532846842707968

**Comment by MattBSG** [comment]
You cannot have more than one owner. Use permissions https://github.com/Just-Some-Bots/MusicBot/wiki/Permissions
