### ISSUE TITLE
Autopause doesn't pause if autojoining empty channel

### ISSUE THREAD

**Issue by AwkwardGuy** [Just-Some-Bots/MusicBot#794]
If the bot autojoins an empty channel on startup (via the options), autopause doesn't pause it even though it should
You have to pause it manually or join and leave the channel (so autopause triggers).

**Comment by ImthePeach** [comment]
The autopause feature on startup of an empty channel was implemented but is buggy currently. A full fix will come in the future.

**Comment by jayktaylor** [comment]
Fixed in review
