### ISSUE TITLE
Banned in help server

### ISSUE THREAD

**Issue by MadamJazzy** [Just-Some-Bots/MusicBot#795]
I asked a few questions a while back and for an unknown reason i was banned from the help server (not kicked str8 out banned). I would like to request that my ban be removed (as i did not to deserve it) so that i can keep up with new features and have access to support if i need it. My name on discord now is Sapphire#7630 but on Nov 20th when i was banned I went by Jazzi#7630. I was never given a reason or warning before ban and since have solved my issue on the git help page with help from others from the server. 
Thank you

**Comment by arunesh90** [comment]
![image](https://cloud.githubusercontent.com/assets/5787588/21690524/fd6c9f2a-d374-11e6-9767-a5a5c5d3235e.png)
![image](https://cloud.githubusercontent.com/assets/5787588/21690540/10613adc-d375-11e6-9f19-7063f9e7703b.png)

**Comment by MadamJazzy** [comment]
Alright I admit that i did not read the welcome before hand. It could have been possible for a warning rather than an outright ban? I made this thread to appeal the ban decision made against me and try and see if it was possible to be invited back to the server. I now know not to tag people in the chat. Is it possible to have the ban overturned? And i might point out that it says "will result in a kick" does not say that you will be banned for your 1st infraction. Not trying to be smart just suggesting that someones first infraction not be met with a perm ban from the server.
