### ISSUE TITLE
Domain Blacklist

### ISSUE THREAD

**Issue by ZatsuneSakurako** [Just-Some-Bots/MusicBot#796]
Could it be possible to add a whitelist / blacklist system to limit the website usable?

Youtube-dl works with a lot of website including some with... "special" content that should not be possible in a "serious" Discord.

**Comment by KingGold171** [comment]
Normally help isn't given to modifications, but this is something i had laying around
(Now hopefully people stop asking) - Only works for the !play and not !search  (edit it yourself, no further help)

If you can't get it to work from the code below, then we won't help you any further, nor should you be playing in the code if you don't understand it.

- !play url
- !play search for something


_config.py_
```
self.banned_sites_file = config.get('Files', 'BannedSitesFile', fallback=ConfigDefaults.banned_sites_file)
banned_sites_file = 'config/bannedSites.txt'   # this will prevent the bot downloading from certain sites
```


_class musicbot(discord.Client):_
`self.bannedSites = load_file(self.config.banned_sites_file)`


_cmd_play_
```
        for bs in self.bannedSites:
            if bs in song_url:
                raise exceptions.CommandError("Banned site detected, will not play!")
```

**Comment by jayktaylor** [comment]
We don't take responsibility for the code above. Our official answer is that a way to do this will come soon, it just hasn't been implemented yet.

**Comment by ZatsuneSakurako** [comment]
Anyway idea about delay?

**Comment by KingGold171** [comment]
Major updates will come after the libary update (discord.py) still no ETA

**Comment by jayktaylor** [comment]
More or less added in https://github.com/Just-Some-Bots/MusicBot/commit/c4e9ef519b4684255788b6e78ead24e1f3a92343.
