### ISSUE TITLE
.

### ISSUE THREAD

**Issue by nobleBean** [Just-Some-Bots/MusicBot#797]
.

**Comment by KingGold171** [comment]
By [Default] @ everyone can use   play perms queue np skip search id help clean

**Comment by MeisterFabian21** [comment]
ok, now i made a role for the music bot so only the users that are in the role can use the commands 

So i took the Id from the group and paste it everywhere where stands GrandToRoles

but it won´t work

**Comment by KingGold171** [comment]
Did you remove the `;` from start of the line?

**Comment by MeisterFabian21** [comment]
Sry, I am a idiot
