### ISSUE TITLE
(Raspberry Pi 3B / Raspian Jessie) - Bot errors often.

### ISSUE THREAD

**Issue by AbstractUmbra** [Just-Some-Bots/MusicBot#798]
Hi there,

Bought an RPi and my first thought was to run the bot on it. Followed the instructions to the letter (3 times to be safe) and still erroring. Excerpt from the log:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/home/pi/Discord/MusicBot/musicbot/player.py", line 256, in _play
    after=lambda: self.loop.call_soon_threadsafe(self._playback_finished)
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 430, in create_ffmpeg_player
    raise ClientException('ffmpeg/avconv was not found in your PATH environment variable') from e
discord.errors.ClientException: ffmpeg/avconv was not found in your PATH environment variable
```

I looked through the issues for previous errors and so far all I can see is that I've to 're-install ffmpeg correctly' which I have done using the exact instructions provided. Any chance you could maybe tell me if I'm doing something wrong, or is there an actual issue here?

**Comment by 64Hz** [comment]
I re-installed Raspbian last night along with the bot and am still getting the same error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/home/pi/Discord/MusicBot/musicbot/player.py", line 256, in _play
    after=lambda: self.loop.call_soon_threadsafe(self._playback_finished)
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 430, in create_ffmpeg_player
    raise ClientException('ffmpeg/avconv was not found in your PATH environment variable') from e
discord.errors.ClientException: ffmpeg/avconv was not found in your PATH environment variable
```

Am I missing something?

**Comment by 64Hz** [comment]
I think the issue was with how I run the bot.

I use the Supervisor daemon to launch the bot to give my server moderators the ability to stop, start and restart the bot in the event of a crash (pretty frequent unfortunately). It seems the daemon can't interact with the python3.5 executable or the run.py properly. Wether it be an incorrect PATH or lost config files error.

Bit of a long shot here - don't suppose you'd know a way I can get it working with Supervisor?

**Comment by AbstractUmbra** [comment]
Scrap this - I think I fixed it :)
