### ISSUE TITLE
Config Files are misssing.

### ISSUE THREAD

**Issue by kanbee** [Just-Some-Bots/MusicBot#799]
When I run runbot.bat it says it cannot find my options.ini or my example_options.ini. even though they are in the same place. I even ran it under admin and still no luck. Please Help!
It looks like this. 
http://imgur.com/a/YTjhb

**Comment by KingGold171** [comment]
You can grab the example_options.ini from here [https://github.com/Just-Some-Bots/MusicBot/tree/master/config](url)

But at a guess You may of renamed example_options.ini to options.ini.ini so naturally both will be broken.
