### ISSUE TITLE
Issue With Ubuntu 14.04... Install guide

### ISSUE THREAD

**Issue by Chew** [Just-Some-Bots/MusicBot#80]
`mkdir /MusicBot-develop`
`git clone https://github.com/SexualRhinoceros/MusicBot.git /MusicBot-develop`
`cd MusicBot-develop`

This tells the computer (on ubuntu 14.04) to create the directory `/MusicBot-develop` INSTEAD of `/root/MusicBot-develop`
Seems all good right? But now you're telling them to `cd` to `/root/MusicBot-develop` but it doesn't exist, they need to go to `/MusicBot-develop`

Just a minor issue but confusing for noobs like me :)

**Comment by abalabahaha** [comment]
Yeah the person that wrote the install wiki for Ubuntu made a few blunders

**Comment by deansheather** [comment]
Actually, it wasn't me @abalabahaha. It was @xwmario

**Comment by Chew** [comment]
I forgot you can edit the wiki :P xD
