### ISSUE TITLE
Can you add a radio on the internet?

### ISSUE THREAD

**Issue by DaYWhiTe** [Just-Some-Bots/MusicBot#801]
Do you add commands to listen to internet radios?

**Comment by link2110** [comment]
It *should* be the same as playing a stream, so as long as you are using the review version it should work. I've played a couple internet radio stations and they've worked.

**Comment by ImthePeach** [comment]
Review branch: `!stream <url>` command; works for some radio stations but not all. See if your site is supported [here](https://rg3.github.io/youtube-dl/supportedsites.html).
