### ISSUE TITLE
Music Bot seems to have broken with youtube watch links, dumps an error into chat.

### ISSUE THREAD

**Issue by Squish8294** [Just-Some-Bots/MusicBot#807]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',))

**Comment by Squish8294** [comment]
command given was !play https://www.youtube.com/watch?v=Ad00lkJo9hs

Also duplicate of issue https://github.com/mps-youtube/mps-youtube/issues/577

Some songs work, others do not - possibly an incoming API change on youtube's end

**Comment by phlop1304** [comment]
I am also having the exact same issue. Also happens with another music bot I have added to my server that I tried to use to solve the problem.

**Comment by JustBru00** [comment]
I am also having this problem.

**Comment by bindingflare** [comment]
Start this file:
![image](https://cloud.githubusercontent.com/assets/18100713/21812849/54c00484-d77a-11e6-98a9-2b84076eab9d.png)
You may need to run it as administrator.

It will update your dependencies which is important for it to work properly.

**Comment by JustBru00** [comment]
How do I update the dependencies in a Raspbian environment?

**Comment by bindingflare** [comment]
Try:

sudo apt-get update -y

Not really sure cuz I use Win 10.

**Comment by bindingflare** [comment]
^ If the above doesn't work try without the -y

found this website which may help: https://help.ubuntu.com/community/AptGet/Howto

**Comment by JustBru00** [comment]
It appears doing the command `sudo pip3.5 install youtube-dl --upgrade` worked. ~~Will test then edit this comment.~~ Appears to have fixed the problem. Installed a updated version of youtube-dl.

**Comment by bindingflare** [comment]
Nice!

**Comment by Tiz2008** [comment]
@JustBru00  Nice! Worked for me. Thanks :)

**Comment by ghost** [comment]
[Update youtube-dl](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl), fixed it for me!

**Comment by tomihbk** [comment]
Update youtube-dl, fixed it for me too thx 👍

**Comment by ImthePeach** [comment]
Referencing #806
