### ISSUE TITLE
Bot error when playing most songs

### ISSUE THREAD

**Issue by davson19** [Just-Some-Bots/MusicBot#812]
I'm getting a bit of a problem starting today, I'm not sure how to fix it.
` ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\itsno\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\itsno\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Users\itsno\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Users\itsno\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Users\itsno\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Users\itsno\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC' `

**Comment by kerntoni** [comment]
I'm getting the same thing on ubuntu. I tried updating and reinstalling the youtube-dl, but it didn't work. it doesn't happen to all songs on youtube, but most of them.
Problem started a few hours ago.

**Comment by whatamike** [comment]
Same issue for me on ubuntu VM. Just a heads up, it cleared out my autoplaylist file since each song got an error and was removed. Hope you have a backup.

**Comment by ghost** [comment]
Getting the exact same issue here, hopefully we get some sort of resolution soon. Cheers.

**Comment by FriendlyProgrammer** [comment]
I heard its a youtube issue, according to some of my friends it just got updated and its messing with the bots code. It would make sense too

**Comment by junhui-f** [comment]
Fixed after running `update_dependencies` on `review` version.

**Comment by FriendlyProgrammer** [comment]
^He's right worked like a charm. Thanks Grift

**Comment by LoliCheeks** [comment]
I'm getting the same issue, but I'm running off of my secondary Windows PC rather than Ubuntu. Any chance someone has fixed this issue, and could let me know what they've done? I've tried just about everything I can think of o/

**Comment by Vanhuhn** [comment]
^^ I feel kinda dumb to ask that, but I have the same issue and no idea how to do the mentioned thing: 
> Fixed after running update_dependencies on review version.

A little advice would be greatly appreciated, thanks in advance!

**Comment by alexeldeib** [comment]
You need to checkout the review branch (e.g., `git fetch origin review; git checkout review`).  Note that your autoplaylist.txt may cause a conflict (I don't have anything in mine so I just `git stash; git stash clear`). Then run the update_dependencies script.  On Ubuntu/macOS: `./update_dependencies_linux.sh`

You can also do this with `python3.5 -m pip install --upgrade -r requirements.txt` (which is all the script does anyway).

**Comment by ImthePeach** [comment]
reference #806
