### ISSUE TITLE
Can't update dependencies

### ISSUE THREAD

**Issue by Raynni** [Just-Some-Bots/MusicBot#813]
When I run the update_deps.bat, it doesn't work and this appears in the command prompt: C:\Users\pc\AppData\Local\Programs\Python\Python35-32\python.exe: No module named pip.__main__; 'pip' is a package and cannot be directly executed

**Comment by ImthePeach** [comment]
You didn't install python to your PATH environment. During installations you should have checked  box that says Add Python* to PATH

**Comment by sayling** [comment]
I fixed this issue by reinstalling python to a different directory in Windows (C:\Python35) - the Windows Python installer defaults to installing to a local directory - which may cause permissions issues (but the error doesn't actually mention any of this)
