### ISSUE TITLE
Ubuntu Install Guide Issue, deadsnakes:ppa

### ISSUE THREAD

**Issue by LaxSlash** [Just-Some-Bots/MusicBot#82]
Package Python3.5 is NOT being found in the deadsnakes PPA. Where else can I get it?

**Comment by imayhaveborkedit** [comment]
http://askubuntu.com/questions/682869/install-python-3-5-on-vivid-using-apt-get

**Comment by Chew** [comment]
Actually, I've originally tried Ubuntu 15.10 but the bot wont install properly. If you are using Ubuntu 15.10, try switching to Ubuntu 14.04, if you can.

**Comment by ghost** [comment]
Running bot flawlessly on 14.04. :)

**Comment by crater0** [comment]
Hmm, I'm running it perfectly on 15.10, just had to install the dependencies and it worked fine.

**Comment by abalabahaha** [comment]
Closed due to inactivity
