### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by haladslader** [Just-Some-Bots/MusicBot#822]
I dont know what is wrong, i just added it to a new server and its saying this
![36c7e9f91b575d0619ee2f70d56fd55b](https://cloud.githubusercontent.com/assets/25071427/21876324/a6c34d4a-d847-11e6-9c37-0260c78d3a59.png)

**Comment by ImthePeach** [comment]
#806

**Comment by haladslader** [comment]
Thanks
