### ISSUE TITLE
Key error qc

### ISSUE THREAD

**Issue by raul10100** [Just-Some-Bots/MusicBot#824]
![image](https://cloud.githubusercontent.com/assets/21158791/21877663/88fcd412-d85a-11e6-8a31-1d380c7a3920.png)
![image](https://cloud.githubusercontent.com/assets/21158791/21877664/8904b498-d85a-11e6-966a-935812d82605.png)

**Comment by KingGold171** [comment]
Please read some of the [CLOSED] Issues with a similer title,   this has ready been asked many times and has already been fixed.

#806 #812 #816   etc etc


This is a youtube_dl bug ([rg3/youtube-dl#11663](url)) and is fixed. You need to update ytdl using our dependency update scripts:

-     Windows: Open update_deps.bat
-     Linux: Run python3.5 -m pip install --upgrade -r requirements.txt
-     Mac: Open update_macdeps.command in Terminal

**Comment by raul10100** [comment]
Ty
