### ISSUE TITLE
Songs getting deleted from auto playlist 

### ISSUE THREAD

**Issue by Firesquirrel66** [Just-Some-Bots/MusicBot#825]
For some reason a lot of the songs in the auto playlist are getting deleted from my bot automatically. Then the bot ends up playing only about 3 of the 50 songs I originally put in.

**Comment by junhui-f** [comment]
Might be this issue

Refer to #812 

> **whatamike** commented a day ago
Same issue for me on ubuntu VM. Just a heads up, it cleared out my autoplaylist file since each song got an error and was removed. Hope you have a backup.

**Comment by ghost** [comment]
On a related note, the autoplaylist.txt file should probably get backed up if any entries are to be removed.

**Comment by jayktaylor** [comment]
In the development version of the bot, the autoplaylist is backed up when entries are removed, and the reason for removal is commented in this backed up file. We're aware of the complaints about how the current system works.
