### ISSUE TITLE
!perms @person

### ISSUE THREAD

**Issue by TheBrambleShark** [Just-Some-Bots/MusicBot#828]
As the title suggests, I would like to have the ability (when given the ability to run the `!perms` command), to tag a person as an argument and being shown what their specific perms are as if they executed the command themselves. This can be useful for troubleshooting permissions issues.

Use: `!perms @Foxtrek_64`

Responds with text file, as normal, but as if the specified user ran the command.

**Comment by KingGold171** [comment]
Chances are there is an issue in your permissions.ini on the GrantToRoles / Userlist

The !perms command currently is designed to PM the user with a list generated from permissions.ini

Dosen't sound overly hard of a challenge to intergrate your suggestion.

**Comment by Foxtrek64** [comment]
My issue was forgetting to add the user group ID to the MusicBotMaster group in the permissions.ini file. As soon as I opened the file I realized what I'd done.

**Comment by TheBrambleShark** [comment]
@jaydenkieran Can we add the Feature Request tag instead of just closing the issue? I would do it myself but it seems I don't have permissions. Will clean to make this specifically a feature request.

**Comment by jayktaylor** [comment]
@Foxtrek64 I closed your issue as I assumed it was resolved. Considering you've revised it to be a feature request, I'll re-open.
