### ISSUE TITLE
Trying to play a youtube link fails. 

### ISSUE THREAD

**Issue by darkgusgus** [Just-Some-Bots/MusicBot#829]
My bot has been turned of for a few days and now when I try to play a youtube video i get this

> [0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 997, in _decrypt_signature
>     video_id, player_url, s
>   File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 924, in _extract_signature_function
>     cache_res = res(test_string)
>   File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 976, in <lambda>
>     return lambda s: initial_function([s])
>   File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 254, in resf
>     res, abort = self.interpret_statement(stmt, local_vars)
>   File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
>     v = self.interpret_expression(expr, local_vars, allow_recursion)
>   File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 174, in interpret_expression
>     return obj[member](argvals)
> KeyError: 'Ai'
>  (caused by KeyError('Ai',))

Am i the only one ?

**Comment by MattBSG** [comment]
No, your not

Please update your dependencies by doing the following:

**Windows**- Open `update_deps.bat`
**Linux** - In your console, `run python3.5 -m pip install --upgrade -r requirements.txt`
**Mac** - Open `update_macdeps.command` in Terminal

**Comment by darkgusgus** [comment]
Works, TY
