### ISSUE TITLE
Choppy audio

### ISSUE THREAD

**Issue by YPowTecH** [Just-Some-Bots/MusicBot#83]
I am not sure if this is just me but the audio is really choppy at certain times and it will just fade in and out. Any fix?

**Comment by imayhaveborkedit** [comment]
The audio quality is heavily dependent on the quality of the the bot's (and your) connection to discord servers.  Nothing I can do about it.

**Comment by CuddleBear92** [comment]
i notice that in the desktop windows client im having choppy audio alot of the time, while in the browser version of discord it works aswell. just a not tho :D 

this was in the PBT after further testing.
the stable client works just fine!

EDIT: stable client is also screwed now, tho this is obv a discord issue and not a bot issue. this is just info for those that might have the same issues. 

made an issue about it here for them: https://support.discordapp.com/hc/en-us/requests/30500

**Comment by arunesh90** [comment]
Open your client, YPowTecH, join the channel your bot is supposed to play on and try this:
![Discord Voice Ping](https://images-1.discordapp.net/.eJwNyFEOgyAMANC7cAAqsbXM2xAkaKYtgZp9mN19e5_vcXc_3ep2szZWgO0YWfvmh2lPtfiqWs-S2jF81guSWcr7VcQGhDlOYVmIIiOHFyNCwEhEM_8TCcNEDLe8RT_im1T3_QEJDSLq.XdvZIQR0rdeUVZmMtCfNIIqe4jw.png?width=265&height=300)
Look if the ping isn't too high and is stable

**Comment by YPowTecH** [comment]
It was just wifi vs plugged in. Its fine.

**Comment by imayhaveborkedit** [comment]
:+1:

**Comment by xameryn** [comment]
go into channel settings and change bitrate.
