### ISSUE TITLE
Unable to install Pip dependencies in Ubuntu 14.04

### ISSUE THREAD

**Issue by dmuth** [Just-Some-Bots/MusicBot#831]
Hi,

I've just been getting started with MusicBot, and I'm a big fan of it!  I've been working on installing it on an Ubuntu server, and noticed that the `requirements.txt` has some challenges out of the box.  Specifically, when I try to run `python3.5 -m pip install -U -r requirements.txt`, I get this error:

```
ValueError: ('Expected version spec in', 'discord.py[voice] ~= 0.12.0', 'at', ' ~= 0.12.0')
```

So I tried editing `requirements.txt` and changed the `~=` to `==` and ran the command again, leading to this error:

```
ValueError: ("Expected ',' or end-of-list in", "cffi==1.6.0; sys_platform == 'win32'", 'at', "; sys_platform == 'win32'")
```

If I remove the part that reads `; sys_platform == 'win32'`, I can then finish installing the pip modules.

Since this appears to eb related to an older version of Pip, I'd like to suggest as a fix that a separate file called `requirements-ubuntu-14.04.txt` or similar be created, and the instructions at https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Ubuntu be updated accordingly.  

I would be happy to make this change and send in the pull request, just let me know!

Thanks for reading,

-- Doug

**Comment by jayktaylor** [comment]
It is because you're using an older version of pip yes, but that can easily be solved with `pip install --upgrade pip`

**Comment by dmuth** [comment]
Thanks, that worked. (And I <a href="https://github.com/dmuth/MusicBot-Ansible/commit/0ce398594f526cf29e3f6bd8c1b9fc4a7f2c9f81">updated my Playbook</a>, too)
