### ISSUE TITLE
Created an Ansible Playbook

### ISSUE THREAD

**Issue by dmuth** [Just-Some-Bots/MusicBot#832]
Hi (again),

I'm also a huge fan of Ansible and automating system builds, so I created an Ansible playbook to install MusicBot and enable it as a service on an Ubuntu 16.04 system:

https://github.com/dmuth/MusicBot-Ansible

I'd be interested in knowing what you think, and if you'd like me to do any more with it (other distros), etc.

All the best,

-- Doug

**Comment by dmuth** [comment]
Update: Ubuntu 14.04 is now supported, Munin support has been added for generation of performance graphs, and I added support for configuring Digital Ocean hosts as well.

**Comment by jayktaylor** [comment]
Thanks! 👍 

We've added this to our [wiki page](https://github.com/Just-Some-Bots/MusicBot/wiki) and will be closing this issue for the time being. If anyone has an issue with this distribution, contact [dmuth](https://github.com/dmuth) directly or leave an issue in [this repository](https://github.com/dmuth/MusicBot-Ansible/issues).
