### ISSUE TITLE
Runtime Error?

### ISSUE THREAD

**Issue by DJ0071** [Just-Some-Bots/MusicBot#833]
![image](https://cloud.githubusercontent.com/assets/25115952/21953526/7981161a-da6c-11e6-9c6f-c9dbe0f0f280.png)

I tried update_deps.bat.. not working please help me with the steps. I am not really good with this stuff

**Comment by Arthacus** [comment]
Hi, I have the same problem. I'm running macOS Sierra 10.12.2. 
Same thing occurs after running update_macdeps.command.
![image](https://cloud.githubusercontent.com/assets/10133791/22212812/530408da-e192-11e6-93e3-d293ade6a225.png)

Think this relates to Closed Issue [(#344)](https://github.com/Just-Some-Bots/MusicBot/issues/344)(closed by inactivity)

**Comment by amit177** [comment]
If this is still an issue in the latest version, please open a new issue.
