### ISSUE TITLE
unable to download api page 

### ISSUE THREAD

**Issue by bbyyw** [Just-Some-Bots/MusicBot#834]
ERROR: Unable to download API page: <urlopen error EOF occurred in violation of protocol (_ssl.c:645)> (caused by URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:645)'),))

i got this message when i try to play music, anyone know how to fix ?

nb : first time trying after 1 week not using bot or discord

**Comment by amit177** [comment]
If this is still an issue in the latest version, please open a new issue.
