### ISSUE TITLE
Weird issue if you create your own autoplaylist

### ISSUE THREAD

**Issue by Girtablulu** [Just-Some-Bots/MusicBot#835]
Hi

I have a weird issue when I create my own autoplaylist.txt and replace the default autoplaylist.txt with it, the bot stops playing songs and delete songs from my new autoplaylist after I restart the bot, anyone else has this problem?

**Comment by ghost** [comment]
Check if the bot is showing any error messages. If it's unable to play a song, it will remove it from the list.

**Comment by Girtablulu** [comment]
it doesn't like any youtube link in my autoplaylist, I moved back to the default list but now I'm greeted with even more errors and he isn't working at all...

http://pastebin.com/C8dhLa5k

**Comment by Lmg4real** [comment]
I get the same problem. I spent a few hours creating a my own autoplaylist. 
Let it autoplay for a few days, come back and instead of several hundred songs listed, there is only 16.
So it deleted 90% of them. Not sure what to do.

**Comment by kelticmaid** [comment]
I'm having the same issue most of my playlist is direct from the bands official videos.  It shortened my 80 songs down to about 10.  Most of my songs are official band  youtube video links; the 10 were uploaded by randoms except one from Invocation array.  I corrected the list by reloading the dump file and within 15 mins the list was back to 10.

**Comment by jayktaylor** [comment]
See #967 for information regarding the bot deleting songs from the autoplaylist.
