### ISSUE TITLE
The bot is not in a voice channel.  Use ?summon to summon it to your voice channel.

### ISSUE THREAD

**Issue by Soylent1337** [Just-Some-Bots/MusicBot#836]
When I start runbot.bat bot connects to server for few seconds then it loses connection and gives this error:
https://u.nya.is/npukvi.png

**Comment by chuushi** [comment]
Have you tried looking into the solution it mentions?  How are you hosting the bot?

**Comment by Soylent1337** [comment]
UDP is open. I am hosting it on my VPS.

**Comment by jayktaylor** [comment]
Recent updates to the bot may help counter this issue. Let us know if there are still problems.
