### ISSUE TITLE
bot laggy

### ISSUE THREAD

**Issue by bbyyw** [Just-Some-Bots/MusicBot#838]
anyone know how to fix my bot so laggy, when i request !play the bot always delay 30s - 20 minutes. help 

or is it my connection problem ?

**Comment by arunesh90** [comment]
It's probably because your internet speed is low

**Comment by bbyyw** [comment]
ah yeah i can see when i ping yt there's timed out. im never had this problem 1-2 weeks ago

**Comment by Zenrac** [comment]
same problem with !play..

**Comment by arunesh90** [comment]
make your own issue.
