### ISSUE TITLE
Crashes when downloading age-resticted/explicit content where sign in is required from Youtube

### ISSUE THREAD

**Issue by rbonomo** [Just-Some-Bots/MusicBot#839]
Try "!play badass bitch lilith"

**Comment by yanirz** [comment]
Doesn't crash for me.

**Comment by jayktaylor** [comment]
I've been able to reproduce this.

**Comment by yanirz** [comment]
@jaydenkieran try updating youtube-dl

**Comment by jayktaylor** [comment]
@yanir3 My dependencies are set to update before every time I run the bot, using the latest ver.

**Comment by jayktaylor** [comment]
This doesn't seem to be an issue as of recent versions of youtube-dl.
