### ISSUE TITLE
Unicode issue in the title of the server

### ISSUE THREAD

**Issue by Leninsky** [Just-Some-Bots/MusicBot#84]
```
--Server List--
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 259, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/root/MusicBot-develop/musicbot/bot.py", line 227, in on_ready
    [print(s) for s in self.servers]
  File "/root/MusicBot-develop/musicbot/bot.py", line 227, in <listcomp>
    [print(s) for s in self.servers]
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f525' in position 8: ordinal not in range(128)
```

The server name is eXtream 🔥, i commented out line 227 as a temporary fix and appended an .encode('utf-8') to all other lines that gave me an error. I am using ubuntu 14.04 and python3.5

**Comment by imayhaveborkedit** [comment]
Ah yes, unicode encoding issues.  Since this is a linux issue i'll see what I have to do.  It's probably just doing an encode like you did, but on windows this is dealt with by using `CHCP 65001` in the run bat.

**Comment by imayhaveborkedit** [comment]
Should be fixed, as of a while ago.
