### ISSUE TITLE
CMD Instantly closes after opening "runbot.bat"

### ISSUE THREAD

**Issue by Waiben** [Just-Some-Bots/MusicBot#848]
So yeah, the title pretty much says everything. When I open the "runbot.bat" file it instantly closes. It doesn't provide text on the cmd and I am clueless as to why this happens.

**Comment by ImthePeach** [comment]
Try the following steps:

- Run `lazy_cmd.bat` inside the MusicBot folder. 
- Type `python run.py` and press enter

Let me know what happens when you do this.

**Comment by jayktaylor** [comment]
If you are able to give further information as requested above, let us know.

**Comment by FR3SHPR1NCE** [comment]
I have had exactly the same issue, and get the following message when I type python run.py into lazy_cmd.bat :

python is not recognized as an internal or external command, operable program or batch file. 

I had originally installed python 3.5 last year and I just now updated it to 3.5.1. I have also run update_deps.bat and there were no issues. However, the runbot.bat file still won't open, it immediately closes when trying to open.

**Comment by davor115** [comment]
By doing what ImthePeach said it will run the bot and connect it. But after giving !play (song) command the bot will automatically disconnect.. any ideas?
