### ISSUE TITLE
default volume setting in settings file?

### ISSUE THREAD

**Issue by CuddleBear92** [Just-Some-Bots/MusicBot#85]
default volume setting in settings file?
would be great to have a default setting for the volume. to be able to set it at 75-100 or whatever and let the users choose the volume themselfs with the client settings. 

this would work with https://github.com/SexualRhinoceros/MusicBot/issues/45 aswell IMO!

**Comment by imayhaveborkedit** [comment]
The default volume options has already been moved from constants.py to the config file in review.

**Comment by CuddleBear92** [comment]
close this as its in the pre-release version?
