### ISSUE TITLE
Using a name instead of an ID with grantToRoles

### ISSUE THREAD

**Issue by Zenrac** [Just-Some-Bots/MusicBot#851]
Dear dev',

Maybe it can be a good idea to makes the permission grantztorole able to read a role's name. 
If its possible, it can makes easier the permission of the bot, in all servers. 

Example : 
GrantToRoles : 'DJBOT' 
For example, the role named DJBOT have full permissions. If you wan't to give full permission to someone you just have to create the role called DJBOT and give it to him. So he will have full permission without any edit on the permission.py.

What do you think ? Its possible ?

**Comment by jayktaylor** [comment]
This is possible yes, but it isn't something we'll implement as it can cause issues where multiple servers have the same role name and things like that. [Snowflakes](https://dev.twitter.com/overview/api/twitter-ids-json-and-snowflake) ("IDs") are unique and therefore better to deal with.

**Comment by zenrac** [comment]
Thanks for replying, 

Do you have an idea in order to add this to my bot ? Maybe with the r.name (used in listids)
thanks you again
