### ISSUE TITLE
Bot not playing my songs

### ISSUE THREAD

**Issue by Wolfleader101** [Just-Some-Bots/MusicBot#852]
so i when and copied a youtube playlist and converted each song into its url e.g https://www.youtube.com/watch?v=_dK2tDK9grQ and  i then save the autoplaylist and run runbot.bat and it plays the old songs which i deleted.

**Comment by Zenrac** [comment]
Did you try to get all the URL with the !pldump and just copy/paste the content in the autoplaylist ?

Or maybe try to update youtube-dl with pip
in the Terminal use the following command : 
pip3 install -U youtube-dl

**Comment by Wolfleader101** [comment]
>@zenrac that worked thank you

**Comment by ImthePeach** [comment]
Appears issue has been resolved, closing...
