### ISSUE TITLE
Auto playing songs on multi servers.

### ISSUE THREAD

**Issue by xShineyThighx** [Just-Some-Bots/MusicBot#853]
I have the bot set to auto join on the 4 servers i have. I noticed that every time I restart the bot, it will start playing songs in a room when nobody is there.

(the py.exe box will continue downloading songs, and the bot will say playing music on 4 servers.) 

Is there a settings Im missing, or is this a bug that can be fixed?
**Example:** 
Autojoining voice channels:
 - Kaytes Personal/Music
 - s6 Halo/Music
 - Symbolic Factions/Music
 - Amethyst RP Unturned Server/Music Channel

Options:
  Command prefix: !
  Default volume: 8%
  Skip threshold: 4 votes or 50%
  Now Playing @mentions: Enabled
  Auto-Summon: Disabled
  Auto-Playlist: Enabled
  Auto-Pause: Enabled
  Delete Messages: Disabled
  Debug Mode: Disabled
  Downloaded songs will be saved

Attempting to autojoin Music in Kaytes Personal
Attempting connection...
Connection established.
Attempting to autojoin Music in s6 Halo
[Download] Cached: https://www.youtube.com/watch?v=QZRrIajouqs
Attempting connection...
Connection established.
Attempting to autojoin Music in Symbolic Factions
[Download] Cached: https://www.youtube.com/watch?v=VJL_DlHmwzg
Attempting connection...
Connection established.
Attempting to autojoin Music Channel in Amethyst RP Unturned Server
[Download] Cached: https://www.youtube.com/watch?v=__oSdfgDF_c
Attempting connection...
Connection established.

**Comment by gnuttenx** [comment]
Disable Auto-Playlist: Enabled in options.ini. And it should stop.
Dunno if it overides Auto-pause first time it joins a channel and the channel is empty.

**Comment by jayktaylor** [comment]
[Disable this](https://github.com/Just-Some-Bots/MusicBot/wiki/Configuration#useautoplaylist).

**Comment by xShineyThighx** [comment]
hmm, I'd still like it to pull from the playlist when songs aren't being requested though.

is that the only way to stop it from auto playing when users are not present in the channel after a restart?

**Comment by jayktaylor** [comment]
The intended behaviour for the bot is for it to autopause when joining a channel, however this is currently only available in the `review` branch. (#245).

You may use the review branch at your own risk (using `git checkout review`). It contains the very latest features, but also means that it is **developmental** and can have problems.
