### ISSUE TITLE
Incorrect GamerID or Wrong Credentials 

### ISSUE THREAD

**Issue by SpitFireEternal** [Just-Some-Bots/MusicBot#855]
Hello, Im new to a lot of this so I do hope my question isnt that bad. When I attempt to run MusicBot from the folder I get the following error. Now Ive followed the guides and as far as I can tell I did everything correctly. Maybe I overlooked something or messed up on a step? Im not sure. Help would be much appreciated as my friends have told me how great this MusicBot is for Discord Servers. Thank you guys and have a great day
![image](https://cloud.githubusercontent.com/assets/25310830/22227261/6e20693c-e198-11e6-8b71-9b6a96ce4d28.png)

**Comment by KingGold171** [comment]
Ensure it is your ID and not the bot's you are entering.

Should be about 18 numbers long

Come join us at http://discord.gg/bots   so we can help you with a quicker responce.

**Comment by ImthePeach** [comment]
7 days old, no new comments. Closing issue based on assumption that help was provided to user in Discord.
