### ISSUE TITLE
Restart 

### ISSUE THREAD

**Issue by AutumnClove** [Just-Some-Bots/MusicBot#856]
I noticed that when using the restart command it doesn't actually reset say permissions or options. Would there be anyways to change or make this a thing? As having to shutdown or terminate the console seems like a hassle if your're just changing one or two things. Thanks~Autumn Clove

**Comment by KingGold171** [comment]
Already a planned feature

**Comment by AutumnClove** [comment]
Sorry, didn't notice that thanks for letting me know 😅 when this happens would user have to reinstall the files and re write custom stuff such as adjusting command names and max volume etc? I'm a bit new to all this.

**Comment by KingGold171** [comment]
when the time comes,  make a backup of your 

options.ini
permissions.ini
autoplaylist.txt
audio_cache (folder)

then use git pull to update everything else, then just add them 4 files back in.


Any custom commands will be lost, so best to ensure you have a copy somewhere.

**Comment by ImthePeach** [comment]
It should reload the files, or at least it does in the review branch. It's been a while since I've touched the master branch so idr if it was supposed to or not there.

**Comment by arunesh90** [comment]
This issue is being closed due inactivity of OP
