### ISSUE TITLE
About Translation

### ISSUE THREAD

**Issue by Boifuba** [Just-Some-Bots/MusicBot#858]
I would like to translate to my language, how is the best way to do it?

**Comment by KingGold171** [comment]
Currently there is no easy way to translate the bot.

HOWEVER it is currently under active developemnt to implement a way todo so by myself and 3 others with great progress so far, and almost ready to fully test once a few little kinks are sorted out.

Dpending on how well you can translate English into your own language, I can give a file in which the translations are based of.

Please note this is a thrid party modification which Just-Some-Bots won't help you do, hopefully once its completed it can be included with the main MusicBot release.

**Comment by Boifuba** [comment]
i can help you with this project translating to portuguese! are you using gettext?

**Comment by KingGold171** [comment]
Since the project is third party i won't release all info here as this is meant for Just-Some-Bots Support.

Feel free to DM me on Discord    (KingGold171#3066)

**Comment by Boifuba** [comment]
done!

**Comment by Boifuba** [comment]
you refused my invite, try to add Boifubá#2375

**Comment by KingGold171** [comment]
My apologies,
Names are different so it didn't register as who it was.

Have sent you a DM on Discord.

**Comment by ImthePeach** [comment]
Closing this issue, we will handle the pr's and such for the translations feature in the background with KingGold and his team...

**Comment by lmmfranco** [comment]
Was there any progress on this?
Just moving strings into a separate file would be already of great help

**Comment by Boifuba** [comment]
Lol u cutted me out The prijetc a ling time a go

-----Mensagem Original-----
De: "lmmfranco" <notifications@github.com>
Enviada em: ‎03/‎01/‎2018 19:37
Para: "Just-Some-Bots/MusicBot" <MusicBot@noreply.github.com>
Cc: "cefasheli" <cefasheli@gmail.com>; "Author" <author@noreply.github.com>
Assunto: Re: [Just-Some-Bots/MusicBot] About Translation (#858)

Was there any progress on this?
Just moving strings into a separate file would be already of great help

**Comment by jayktaylor** [comment]
This is something I'm planning to add soon. I started updating the MusicBot recently.
