### ISSUE TITLE
!playing or !song

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#86]
It would be nice to have a `!playing` or `!song`. Not everyone knows all the songs in the backup list and sometimes chat floods the "now playing ..." message out of the way. :)

**Comment by jhgg** [comment]
it exists, called !np

**Comment by ghost** [comment]
I didn't see it on the commands page. D: My bad!

**Comment by ghost** [comment]
Hmm...doesn't seem to work for me. I'm on the development branch.

**Comment by srhinos** [comment]
I did a shitty implementation of it for private use. We might want it

**Comment by imayhaveborkedit** [comment]
Its an easy command to do, i'll just copy paste some code from the queue function.

**Comment by ghost** [comment]
Didn't even think about that. I guess it would just be `!queue` minus some stuff. :D
