### ISSUE TITLE
My bot is not running

### ISSUE THREAD

**Issue by Reterfreezer** [Just-Some-Bots/MusicBot#860]
I run runbot.bat and I get this meesage in my Command Prompt

No module named 'musicbot.bot'
Attempting to install dependencies...
Requirement already up-to-date: discord.py[voice]~=0.12.0 in c:\users\jayden\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: youtube_dl in c:\users\jayden\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: pip in c:\users\jayden\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: cffi==1.6.0 in c:\users\jayden\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: aiohttp<1.1.0,>=1.0.0 in c:\users\jayden\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: websockets<4.0,>=3.1 in c:\users\jayden\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: PyNaCl==1.0.1 in c:\users\jayden\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: pycparser in c:\users\jayden\appdata\local\programs\python\python35\lib\site-packages (from cffi==1.6.0->-r requirements.txt (line 4))
Requirement already up-to-date: chardet in c:\users\jayden\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: multidict>=2.0 in c:\users\jayden\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: async_timeout in c:\users\jayden\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: six in c:\users\jayden\appdata\local\programs\python\python35\lib\site-packages (from PyNaCl==1.0.1->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))

Ok lets hope it worked

C:\Users\Jayden\Desktop\MusicBot-master>

**Comment by KingGold171** [comment]
If the bot is a fresh download/clone it shouldn't be throwing that error.

**Comment by Reterfreezer** [comment]
I recently re-downloaded the file since this happened to my old bot. It was fine for a few days but this happened again. :/

**Comment by jayktaylor** [comment]
Follow the installation guides on https://github.com/Just-Some-Bots/MusicBot/wiki. This error won't happen if you follow the instructions. Downloading the zip is not sufficient.

**Comment by Reterfreezer** [comment]
Thanks Jayden, I tried what you recommended and it worked!
