### ISSUE TITLE
Error: unable to download JSON metadata: TTP Error 401: unauthorized

### ISSUE THREAD

**Issue by basilicedj** [Just-Some-Bots/MusicBot#863]
![image](https://cloud.githubusercontent.com/assets/14005747/22314338/f939acda-e32e-11e6-9cc7-1f9f448126ed.png)
![image](https://cloud.githubusercontent.com/assets/14005747/22314358/198a2f00-e32f-11e6-8aa2-50892574e5ca.png)

On a windows machine 

Works with youtube songs but not with soundcloud links for some reason? Tried uninstalling the bot and reinstalling it but that didn't change the error I was getting.

**Comment by doublehelixx2** [comment]
I've been having the same issue for a few days as well, i think it might be something to do with sound-cloud SPECIFICALLY. as in they possibly blocking the bot from their site.

**Comment by arunesh90** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/846
