### ISSUE TITLE
MusicBot via Docker doesn't play after ~1 day

### ISSUE THREAD

**Issue by danielmarquard** [Just-Some-Bots/MusicBot#864]
Our MusicBot works great in the hours after starting the Docker container, but if you try to queue a song the following day, nothing plays. The bot acknowledges the request and lets the user know that their song is now playing, but nothing is heard over voice. With debug output on, no relevant information is printed in the console that I can use to troubleshoot.

This may or may not have something to do with our users and bots being automatically disconnected from their voice channel after a period of inactivity, a problem that no one else seems to have when I try to google for it.

**Comment by Surjj** [comment]
Hey there, not really a coder or anything, but I have experienced that behavior from the bot as well. I found that it was being triggered by users requesting an invalid stream, something live like Youtube mixes or a Twitch stream. I can correct the problem by having the bot disconnect and rejoin !disconect / !summon, or by using the !restart command.  Hope that helps in some way.

**Comment by danielmarquard** [comment]
Only a restart works for us. This issue happens regardless of whether or not the bot is used at all. If I summon it after about a day, it just doesn't play anything at all, but still announces that a song is playing.

**Comment by jayktaylor** [comment]
I'd recommend giving the developmental `review` branch a go, but I'm not sure how you'd do that with Docker.

**Comment by danielmarquard** [comment]
@jaydenkieran, I'd imagine it would build an image just like the `master` branch does, but are there changes in that branch that fix issues like this?

**Comment by jayktaylor** [comment]
@DanielMarquard It has better reconnect/disconnect logic that could negate/reduce this issue. If you can figure out how to use that branch on Docker (I am unfamiliar), then it may help

**Comment by TBK** [comment]
I switched to the review branch because of the 1 day timeout issue. You can build it with the following commands:

git clone https://github.com/Just-Some-Bots/MusicBot.git MusicBot -b review
cd MusicBot

docker build -t musicbot .

docker run -d musicbot


https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Docker

**Comment by jayktaylor** [comment]
@TBK0000 ty for providing instructions
