### ISSUE TITLE
Can not connect to discordapp.com:443

### ISSUE THREAD

**Issue by FabioZumbi12** [Just-Some-Bots/MusicBot#866]
I having this issue when running my bot:

```
  File "C:\Users\FabioNote\AppData\Local\Programs\Python\Python35\lib\site-
ges\aiohttp\connector.py", line 314, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 1] Cannot connect to host discordapp.c
3 ssl:True [Can not connect to discordapp.com:443 [[SSL: CERTIFICATE_VERIFY
ED] certificate verify failed (_ssl.c:645)]]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000000004756588>
```

How to fix this?

Running on Windows 7 x64 and latest Pyton

**Edit**: This https://github.com/Just-Some-Bots/MusicBot/issues/281 dont solved.

**Comment by FabioZumbi12** [comment]
Fixed

**Comment by ALink95** [comment]
I'm sorry but i have the same problem and this solution don't worked for me...

**Comment by FabioZumbi12** [comment]
In my case, the time of my notebook are not sync with the internet time, i sync and worked.

**Comment by ALink95** [comment]
I'm running the bot on a Raspberry Pi 3, i'll watch if i have the same problem.
