### ISSUE TITLE
Runbot.bat CMD window closes

### ISSUE THREAD

**Issue by WatchAc** [Just-Some-Bots/MusicBot#868]
Everytime I open the runbot.bat or run.py they close instantly showing no text. I then tried to open the update_deps and still didn't work. It updated the deps but the bot doesn't start and every other console window shows this path ,, C:/Users/confidential(not really my pc name)/Desktop/MUSICB~1'' I know the ,,/'' are reversed normally but it's hard to type it. I have already tried the run as admin , same thing also I have tried but i don't know if i did it right  , adding the: ;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;

To my system enviromental variables , since i saw the other post. Please tell my why it doesn't work , I have both Python 3.5  and 3.6 installed with all plugins.

**Comment by jayktaylor** [comment]
It probably has nothing to do with your environment variables. Try the following steps:

- Run `lazy_cmd.bat` inside the MusicBot folder. 
- Type `python run.py` and press enter

Let me know what happens when you do this.

**Comment by blixen1994** [comment]
i am having the same problem. i tried doing the run.py and it didn't do anything. at the start it keeps telling me no module named discord found.

**Comment by Chew** [comment]
What is the exact error?

**Comment by blixen1994** [comment]
It's says cannot find discord module or something like that.

On Feb 11, 2017 3:10 PM, "Chew" <notifications@github.com> wrote:

What is the exact error?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Just-Some-Bots/MusicBot/issues/868#issuecomment-279175982>,
or mute the thread

**Comment by arunesh90** [comment]
This issue is being closed due inactivity of OP

**Comment by Popdude125** [comment]
any resolution to this issue?
