### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by train21** [Just-Some-Bots/MusicBot#869]
Can't startup bot. Keep getting this error. 

Traceback (most recent call last):
  File "/home/dylan/.local/lib/python3.5/site-packages/discord/client.py",
line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/home/dylan/Desktop/TRAIN-BOT/musicbot/bot.py", line 608, in on_ready
    self.safe_print("Bot:   %s/%s#%s" % (self.user.id, self.user.name,
self.user.discriminator))
  File "/home/dylan/Desktop/TRAIN-BOT/musicbot/bot.py", line 516, in safe_print
    sys.stdout.buffer.write((content + end).encode('utf-8', 'replace'))
AttributeError: 'PseudoOutputFile' object has no attribute 'buffer'

Running linux

**Comment by Zenrac** [comment]
I've the same problem, it must be an discord.py's or youtube-dl's issue, i think we have to wait for update.

**Comment by train21** [comment]
You can run it if you do it in terminal. Just CD to the folder of the music bot then type python3 run.py. Worked for me

**Comment by Zenrac** [comment]
Thanks for the tip ;)

**Comment by cmsiss** [comment]
I'm experiencing this exact same issue as well. I first noticed it while using the bot last night. I will try running from the terminal tonight and see if this resolves the issue - thanks for the tip - I've already tried running update_deps again with no luck. @zenrac can you advise if running from the terminal worked for you too?

**Comment by Zenrac** [comment]
I dont know, I never had this issue again after my post, seems weird.

**Comment by Rangnarok123** [comment]
I can confirm that I run the bot from a terminal and the same thing still happens. It's been like this for a couple of days.

EDIT: read @cmsiss 's comment. Ran the update and it seems the dl-youtube lib has just been updated today. Try again and things are fine now

**Comment by cmsiss** [comment]
so far, running from the terminal seems to be working for me. i don't know if this is just a happy coincidence or not though. i only noticed the traceback error for the first time last night - it was with a personal youtube playlist that i've been using as my autoplaylist for some time now, and with song !play requests the bot had carried out only an hour before the issue surfaced. in any case, no issues so far tonight. very peculiar

EDIT: apologies. i did forget to mention that i also ran update_deps again for good measure. @Rangnarok123 appears to be accurate. so far the bot passing all the stress tests i can throw at it this evening

**Comment by TomLongAshfords** [comment]
I was getting this. Running from CLI didn't help, but I ran update_deps and seems to be fine now. That seems to be the solution.

**Comment by cmsiss** [comment]
I would agree. I put the bot through its paces last night and report no issues. Updating the dependencies resolved my issue. I expect anyone else experiencing this particular issue also needs the updated youtube-dl lib to resolve their problem

**Comment by jayktaylor** [comment]
Thanks for the info guys.
