### ISSUE TITLE
Raspbian issue : Cannot connect to host discordapp.com:443

### ISSUE THREAD

**Issue by ALink95** [Just-Some-Bots/MusicBot#872]
Hello everyone!
I was easly running the MusicBot on my Raspberry Pi 3, but yesterday when i tried to reboot it, i could'nt start the bot anymore.
I get this error message : [Errno 113] Cannot connect to host discordapp.com:443 ssl:True Unclosed client session
And i can run the bot with my PC, with the same files, the issue is juste on the Raspberry.
Thx for your help!!!

EDIT : _I already tried to install comodorsacertificationauthority.crt it doesn't do anything._
![a9edfce5c5f9627096b525f57c8197e8](https://cloud.githubusercontent.com/assets/25413426/22402897/640559a8-e607-11e6-8aa1-64be3e64a13c.png)

**Comment by achariyth** [comment]
i'm using 'crontab' to start bot on boot.
i think the script is executed before the pi is connected to internet.
then i inserted sleep command before triggering the run.py like: 'sleep 5s'
it worked on my pi.
