### ISSUE TITLE
Bad Request error

### ISSUE THREAD

**Issue by Aivaruxx** [Just-Some-Bots/MusicBot#876]
I keep on getting 

<class 'musicbot.exceptions.CommandError'>: BAD REQUEST (status code: 400)

when i do some commands. Anyone knows how to fix it?

**Comment by McLovin157** [comment]
I'm having the same issue. Any time the command !play is used that's what comes up in the bat.

**Comment by jayktaylor** [comment]
This is the same issue as #873.
