### ISSUE TITLE
Playing a playlist just plays 5/35 songs

### ISSUE THREAD

**Issue by Bomberlux** [Just-Some-Bots/MusicBot#878]
Hey, title is pretty self-explanatory, basically I just want to send a youtube playlist to the bot, and it only registers the 5 last songs. The other 30 songs are still available on youtube, and I get this error message that repeats itself a lot:

![image](https://cloud.githubusercontent.com/assets/17890377/22473767/35e2db98-e7da-11e6-85fe-e0fa8e0fad24.png)

**Comment by jayktaylor** [comment]
Issue is fixed, see #873
