### ISSUE TITLE
[Feature Request] !promote to promote currently playing song to backuplist.txt

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#88]
!promote to insert currently playing song to backuplist.txt
!promote < URL > to insert < URL > into backuplist.txt
!promoteprev to insert previous played song to backuplist.txt

**Comment by imayhaveborkedit** [comment]
When I write static playlists the autoplaylist will be made into one of those playlists.  I'll have management commands for those, including adding songs.
