### ISSUE TITLE
Bot deleting music

### ISSUE THREAD

**Issue by Senyksia** [Just-Some-Bots/MusicBot#884]
My bot is deleting music from my auto playlist as soon as it starts up. This is strange because it will delete every song in the playlist. Just a day ago it was playing the exact same songs perfectly.

http://pastebin.com/qagcJhTW

I cut out some stuff in the command lines that I copied and pasted like my id and stuff.

**Comment by KingGold171** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3100621/22491756/7a1cddca-e81d-11e6-8bd7-95c0579afec6.png)

**Comment by jayktaylor** [comment]
This is a `youtube_dl` bug and is fixed. You need to update ytdl using our dependency update scripts:

- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal

You can also update ytdl manually using the command `sudo pip install -U youtube-dl`.
