### ISSUE TITLE
Bot disconnects randomly from voice channel but stays online on the server.

### ISSUE THREAD

**Issue by FreshDumbldore** [Just-Some-Bots/MusicBot#892]
i have recently found the bug that my bot randomly disconnects from any voice channel after long playtimes. i am not sure if my ram is filling up to it's maximum and causes the bot to clear it's playlist and disconnects it to clear out ram. (will keep an eye on that)
it could also be that my hoster is causing the issues since mine is running on a vps (Intel® Xeon® Processor E5-2650 [4 cores]; 6Gb ram) where other people could max out their virtual ram and causes the host to lag.
Any ideas from your side?
I apprechiate any help :)

**Comment by Jademalo** [comment]
I'm having the exact same issue, after a while the bot just flat out disconnects from the voice channel. After it has disconnected, !summon no longer works and I cannot get the bot back into the voice channel without a restart.

However, I have mine in two servers, mainly for testing. If it dies on one of the servers, it's perfectly responsive and functional in the other one.

**Comment by FreshDumbldore** [comment]
Mine is also on two servers, but both are separated instances. And the one on my server is a bit older than the other one on the second server

**Comment by adamja** [comment]
+1 for this.

**Comment by n1tr0-5urf3r** [comment]
same for me, !restart fixes the problem for a while
seems only to happen if nobody is in voice channel with the bot, so while the bot is auto paused

**Comment by jayktaylor** [comment]
Try using the `review` branch by running the command `git checkout review` (with bot off obviously). There's better reconnection logic there.
