### ISSUE TITLE
Music doesn't work

### ISSUE THREAD

**Issue by 0xelion** [Just-Some-Bots/MusicBot#895]
Everytime i try to play music (windows based bot) :

`[03/02/2017 22:18] ERROR red on_command_error 363: Exception in command 'play'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Xelion\Documents\Red Bot\Red-DiscordBot\cogs\audio.py", line 1342, in play
    await self._join_voice_channel(voice_channel)
  File "C:\Users\Xelion\Documents\Red Bot\Red-DiscordBot\cogs\audio.py", line 633, in _join_voice_channel
    await self.bot.join_voice_channel(channel)
  File "lib\discord\client.py", line 3196, in join_voice_channel
    voice = VoiceClient(**kwargs)
  File "lib\discord\voice_client.py", line 213, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice`

And yes i've already tried to update the requirements, but no change :/

**Comment by doranych** [comment]
just update youtube-dl
https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl

**Comment by 0xelion** [comment]
How do i do that on Windows ?

**Comment by doranych** [comment]
XelionIO 
have you tried run update_deps.bat?

**Comment by 0xelion** [comment]
i don't have that bat file but like i've said i've already tried to update all the requirements

**Comment by doranych** [comment]
ok, then
Error occurs only when you try execute play cmd? Or even on voice channel connection?
try run in cmd
python -m pip list
if PyNaCl is not in list execute
python -m pip install pynacl
if it will not help
download https://github.com/Just-Some-Bots/MusicBot/blob/master/update_deps.bat
and execute

**Comment by 0xelion** [comment]
i've figured out the problem, i was running Python 3.6 not 3.5 :)

**Comment by doranych** [comment]
i actualy use 3.5...

**Comment by 0xelion** [comment]
Sorry my mistake, i was running 3.6 not 3.5
