### ISSUE TITLE
[question] bot playing

### ISSUE THREAD

**Issue by OugiFormula** [Just-Some-Bots/MusicBot#899]
hey
i want to change my bot playing/game but when i change it its doesnt work
i search in bot.py
discord.game and its find me that
http://prntscr.com/e4fcbq
well now i change this
http://prntscr.com/e4fdbn
and its still doesnt work
i did something wrong? or i change in the wrong place?

**Comment by jayktaylor** [comment]
That will only change what is displayed when the bot is on more than one server playing music simultaneously.
