### ISSUE TITLE
Can't issue restart command twice with Review branch

### ISSUE THREAD

**Issue by ajimiii** [Just-Some-Bots/MusicBot#901]
Hi. I'm running the review branch bot. Everything else is working fine so far. But I notice a bug that if I issued the restart command the first time after running the bot, it will restart just fine. But when I issued the restart command again the following error comes up.

`!restart
  File "run.py", line 314
    def pyexec(pycom, *args, pycom2=None):
                                  ^
SyntaxError: invalid syntax
`

I'm hosting the bot using Ubuntu server 16.04.1 VM. 

PS: I've tried running the bot under Windows. The second time the restart command issued would cause the bot to stop running.

**Comment by jayktaylor** [comment]
I can't reproduce this. Can you give some information about the environment you're running the bot on? (system, Python version, etc).

**Comment by rafaelwastaken** [comment]
I've been able to reproduce this. Mine outputs the same error in the console after using !restart twice
Mine's running on a VPS with Ubuntu Server 16.04.2 and Python 3.5.2.

**Comment by chuushi** [comment]
Can you put the code around three tick marks (\`\`\`)? It seems that the `^` arrow is pointing to the position of the line that errors

Three tick marks such that
>\`\`\`
>(code)
>\`\`\`

**Comment by rafaelwastaken** [comment]
Sure thing. sorry about that, I've only recently started using github, didn't know how to do that haha.
```
File "run.py", line 314
    def pyexec(pycom, *args, pycom2=None):
                                  ^
SyntaxError: invalid syntax
```

I tested this on Windows and it doesn't appear to happen in Windows.

**Comment by blalp** [comment]
I fixed this problem with some shell scripting
```
#!/bin/bash
INPUT_STRING=run
while [ "$INPUT_STRING" != "shutdown" ]
do
	python3.5 run.py
	read -p "Type shutdown to quit" -t 5
done #If you want to check erros put the code below this line above this line.
read -p "Press enter to exit" nothing
echo "Hope I work next time"
sleep 5
```

change the 5 in `read -p "Type shutdown to quit" -t 5` if you want more of a chance to stop it from auto-restarting. If you want to check erros and not auto-restart move 
```
read -p "Press enter to exit" nothing
echo "Hope I work next time"
sleep 5
```
 before `done`

**Comment by jadedtdt** [comment]
I too get this error after calling !restart twice in a row. Same error message as fofofofofofofofofoXD. I'm also running Ubuntu 16.04 and Python 3.5. I would really like to know how to solve this by improving the python code rather than a shell script

**Comment by jadedtdt** [comment]
I may have fixed it by changing

```
def restart(*args):
    pyexec(sys.executable, *args, *sys.argv, pycom2='python')
```
to
```
def restart(*args):
    pyexec(sys.executable, *args, *sys.argv, pycom2='python3')
```

But this takes away from the modular approach I feel like this was going for.

**Comment by Manifold0** [comment]
Any word on when this will hit master? We're having the issue pretty consistently after the bot idles and needs to be restarted.

**Comment by MattBSG** [comment]
@Manifold0 The review branch is currently a release candidate. So very soon
