### ISSUE TITLE
!play should play embeded files

### ISSUE THREAD

**Issue by ngelus** [Just-Some-Bots/MusicBot#902]
It would be cool, if the bot could download audiofiles that are sent to the discordchat and play them afterwards, wouldn't it?

**Comment by siku2** [comment]
If you can't wait for this to be implemented, here's how you can do it yourself:

- Open the **bot.py** file inside the **musicbot** subfolder with a text editor like [Atom ](https://atom.io/) or [Notepad++](https://notepad-plus-plus.org/download/)
- Scroll down to the line 845 and change the line to this:
```python
    async def cmd_play(self, player, channel, message, author, permissions, leftover_args, song_url = ""):
```
- Add the following lines right after the line 854:
```python
        if len(leftover_args) < 1:
            attachments = message.attachments
            if len(attachments) < 1:
                return Response("You need to provide a song url or attach a file!")
            song_url = attachments[0]["url"]
```

This is how it should look:
![How it should look](https://cloud.githubusercontent.com/assets/16530283/23107790/fd3088b6-f703-11e6-969e-42eabaa591b7.PNG)
