### ISSUE TITLE
Pin Command

### ISSUE THREAD

**Issue by TheKingJaffa** [Just-Some-Bots/MusicBot#903]
I've seen the Game Detectives Bot be able to pin messages, but actually looking for one that does it doesn't seem to be physical possible. I'm not experienced enough in Python to fiddle confidently. What would I need to put in a file and which directory does the file sit in?

**Comment by KingGold171** [comment]
You won't get help here to modify the bot, but we can point you in the right directiom.

But it is possible to make the bot pin messages via command,   yet what use will it  have?

It's a Music Bot.....

http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.pin_message

**Comment by jayktaylor** [comment]
https://github.com/Just-Some-Bots/MusicBot/wiki/Modification
http://discordpy.readthedocs.io/en/latest/api.html
We don't provide official support for modifying the bot.
