### ISSUE TITLE
KeyboardInterrupt - Bot hanging

### ISSUE THREAD

**Issue by ViscousSummer88** [Just-Some-Bots/MusicBot#908]
OS: Ubuntu 16.04.1 x64

When running the bot randomly the bot process will hang however bot process will still be running but the bot will not function until the process is restarted. 

The bot will function for 4, 8, 12 hours but on seemingly random times hang, but not drop its connection to Discord, will interact with commands for example !restart, !summon however the bot will not function / play music from the auto playlist or music requested via !play.

Someone said before in the Support Discord that it may be related to the 'KeyboardInterrupt' so I used different ways of closing my SSH session etc rather than Ctrl+C and using exit etc; this hasn't made a difference it seems however. The bot via PM2 right now and have also tried in Tmux and Screen but also get the bot crashes.

> Traceback (most recent call last):
  File "/root/MusicBot/run.py", line 224, in <module>
    main()
  File "/root/MusicBot/run.py", line 165, in main
    m.run()
  File "/root/MusicBot/musicbot/bot.py", line 551, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 375, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1276, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 441, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe391c60eb8>

**Comment by jayktaylor** [comment]
Try switching to and using the review branch using `git checkout review`. Also, fyi, `KeyboardInterrupt` is simply the generic Python error that is thrown when you terminate the program using CTRL + C and doesn't really have anything to do with your problem.

**Comment by ViscousSummer88** [comment]
Hey, I've been running the review branch and the issue still occures - clean install on Ubuntu following the directions on the website on multiple servers.

It's not a huge issue because !restart fixes the issue and the bot comes back but it would be nicer if it didnt happen :)

**Comment by jayktaylor** [comment]
Recent updates to the bot may have helped deal with this issue. Let us know if there are still issues.
