### ISSUE TITLE
Can't change bots nickname

### ISSUE THREAD

**Issue by JunkKnight** [Just-Some-Bots/MusicBot#909]
I'm trying to update the bots nickname, but when I use the !setnick name command it returns "Unable to change nickname: no permission" . I'm the bot and channel owner, I've set myself as part of the group with the highest permissions and I'm using the latest version of the bot. The bot is hosted on windows server 2016

**Comment by jayktaylor** [comment]
That means that the bot is unable to change its own nickname. Check it has permission to do so, based on the roles it has.
