### ISSUE TITLE
youtube playlist not working , was before

### ISSUE THREAD

**Issue by Wolfleader101** [Just-Some-Bots/MusicBot#912]
so i converted my youtube list into links and i get this error which i never use to get : https://hastebin.com/cawaduveha.sql

**Comment by ViscousSummer88** [comment]
@Wolfleader101 run the following, the issue relates to a YTDL bug.

Windows - Open update_deps.bat
Linux - In your console, run python3.5 -m pip install --upgrade -r requirements.txt
Mac - Open update_macdeps.command in Terminal

**Comment by plasmo63** [comment]
@ViscousSummer88 http://prntscr.com/e7x12j i got this when i tried to update dependencies idk what to do after

**Comment by arunesh90** [comment]
@plasmo63 Your issue is not related to this, make your own issue.
