### ISSUE TITLE
Is there a way to make the bot play on multiple servers?

### ISSUE THREAD

**Issue by Anonymouse15** [Just-Some-Bots/MusicBot#913]
Currently, the bot is in 2 servers. But if someone plays a song in a voice channel from server 1, then the bot joins a voice channel in server 2, it plays the song from server 1 and vice versa. Is there a way to make it play different songs on the different servers?

**Comment by jayktaylor** [comment]
It shouldn't do this if you're using an oauth bot rather than a created user account.
