### ISSUE TITLE
Can't play music from SoundCloud 

### ISSUE THREAD

**Issue by johannesfk** [Just-Some-Bots/MusicBot#916]
When i try to play music from soundcloud i get this error:

Me:   `!play https://soundcloud.com/davebaxter/slow-changebeat-2016`

Bot: `[0;31mERROR:[0m Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>)
`

Please help me or fix it. It started to happen 2 days ago. it used to work before.

**Comment by jayktaylor** [comment]
#915
