### ISSUE TITLE
How to let anyone use Summon and restart?

### ISSUE THREAD

**Issue by zdqxxx124** [Just-Some-Bots/MusicBot#918]
Hi there, 

I build my bot in a DO server, but I'm trying to let other people to summon and restart it when it has problem. But bot says they don't have persimmon. So how to make them have persimmon to do that?

**Comment by KingGold171** [comment]
https://github.com/Just-Some-Bots/MusicBot/wiki/Permissions

**Comment by zdqxxx124** [comment]
Thanks a lot! And another question   what if I want to build more bots on same one server, how to do that? its a ubuntu server. 

Thanks a lot.

**Comment by junhui-f** [comment]
Have not test but you probably need to have separate bot folders containing their own specific config files which contain different bot ids from each other.

**Comment by KingGold171** [comment]
^ what he said

You require: (per bot)

1 Folder
1 Token / account
1 options.ini
1 permissions.ini
1 Command prefix (set in options.ini)

Advanced:
Cheat and use the same permissions.ini (so long as all bots are on one server (copy and paste it))
You can bind to different text channels and use same prefix if you wantesd (just ensure other bots don't have access)
AutoJoin different voice channels
Remember which folder and console window is what bot (incase of manual shutdown/restart)

What i done was right click runbot.bat > create shortcut    then moved shortcut to desktop and renamed it to the bots name  😈

**Comment by zdqxxx124** [comment]
yeah I got it. I builded another two bots in the same server, they are working well, I'm using different prefix that should be good for us. and I write down prefix, name and console in a doc so I can find them whenever I need it. 
Thank you so much.
