### ISSUE TITLE
[Feature request] Command to reset bot

### ISSUE THREAD

**Issue by BaconMonkey** [Just-Some-Bots/MusicBot#92]
Possibly useful for If the bot stops playing due to an error, a user with the right rights could send a command (!reset) in chat to force a reset.

**Comment by Ivoz** [comment]
That, and/or/also a command to reload the bot's configuration. Either options or permissions (or both? or whichever is easy?).

!reload permissions|options

**Comment by imayhaveborkedit** [comment]
Yes, both are planned.

**Comment by imayhaveborkedit** [comment]
There's now a restart command in review.
