### ISSUE TITLE
Autoplaylist only playing one song

### ISSUE THREAD

**Issue by jomaor1** [Just-Some-Bots/MusicBot#923]
It is very important that I state here, that i've translated the Bot to my native language. So maybe I did something wrong. No matter how many times I restart, the bot only plays a random song from the list, and just stops. Can someone point me where exactly(line) on the .py files should be this option that may be wrong on my files?

**Comment by KingGold171** [comment]
Since you have admited to modifying the code,  suppot is very limited and next to none and while you have translated it we have no clue as to which part of your change has caused it.

**Comment by Zenrac** [comment]
Search after "while autoplaylist" in bot.py
