### ISSUE TITLE
Websocket disconnect leads to all songs in queue being skipped

### ISSUE THREAD

**Issue by royalaid** [Just-Some-Bots/MusicBot#925]
Hey all,
When I have queued up a bunch of songs if the error below happens it seems to throw music bot off. It will skip to the end of whatever is in the queue and does not try to reconnect. I am on the review branch with a fresh `git pull` and rebuilt container. The songs were being pulled from a mix of soundcloud and mixcloud with most of the them being over 40 minutes long.
```
Task exception was never retrieved
future: <Task finished coro=<on_player_play() done, defined at /usr/src/MusicBot/musicbot/bot.py:581> exception=ConnectionClosed('WebSocket connection is closed: code = 1006, no reason.',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/src/MusicBot/musicbot/bot.py", line 582, in on_player_play
    await self.update_now_playing_status(entry)
  File "/usr/src/MusicBot/musicbot/bot.py", line 712, in update_now_playing_status
    await self.change_presence(game=game)
  File "/usr/lib/python3.5/site-packages/discord/client.py", line 1593, in change_presence
    yield from self.ws.change_presence(game=game, status=status, afk=afk)
  File "/usr/lib/python3.5/site-packages/discord/gateway.py", line 433, in change_presence
    yield from self.send(sent)
  File "/usr/lib/python3.5/site-packages/discord/gateway.py", line 398, in send
    yield from super().send(data)
  File "/usr/lib/python3.5/site-packages/websockets/protocol.py", line 309, in send
    yield from self.ensure_open()
  File "/usr/lib/python3.5/site-packages/websockets/protocol.py", line 393, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006, no reason.
```

**Comment by royalaid** [comment]
I should also comment that it appears that musicbot will still download the queue but does not play it.

**Comment by Jimgersnap** [comment]
My bot seems to only do this when the server synchronizes time with an NTP server. I figured this out by checking the Windows event logs and tieing the time of the time sync to the time of the websocket errors - they are definitely related. 

Any idea on how to fix this without having to turn off the Windows Time service?

**Comment by jayktaylor** [comment]
Are you using 1.9.6_1?

**Comment by Jimgersnap** [comment]
Sorry for taking so long to get back to you. No I was not - I was on my own custom version of 1.9.6-review up until today. I just updated the bot to 1.9.6_2 and have added my additions to the new version and I'll report back if I experience the same issues. 

Note that my additions are simply commands and nothing breaking to the base code, so it shouldn't make a difference.

**Comment by amit177** [comment]
If this is still an issue in the latest version, please open a new issue.
