### ISSUE TITLE
Imgur command 

### ISSUE THREAD

**Issue by Meepojuan** [Just-Some-Bots/MusicBot#927]
Hello there, 
I'm trying to program a command which could put a image from imgur and post it on the text channel, here i send what i have done untill now   
[bot.txt](https://github.com/Just-Some-Bots/MusicBot/files/768725/bot.txt)

**Comment by KingGold171** [comment]
[404] Modification Support Not Found.

The only help given here for modding the bot is the modification page on the Wiki.

You could try asking on Discord API server but MusicBot is also rare unless you know what you are doing.

**Comment by jayktaylor** [comment]
https://github.com/Just-Some-Bots/MusicBot/wiki/Modification

**Comment by Meepojuan** [comment]
So, there is no way this feature will be implement someday?

**Comment by arunesh90** [comment]
The bot is **only** for music, it's not a all-in-one shitposting bot.
