### ISSUE TITLE
Docker error.

### ISSUE THREAD

**Issue by teodorocolombo** [Just-Some-Bots/MusicBot#928]
When I try to build MusiBot on Docker this message appears:
`[teodoro@teodoro-pc MusicBot]$ docker build -t musicbot .
Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

**Comment by TheEssem** [comment]
Try this: https://forums.docker.com/t/cannot-connect-to-the-docker-daemon-is-the-docker-daemon-running-on-this-host/8925/4
