### ISSUE TITLE
An error occurred AbortError: GET can't be processed. The connection is already closed.

### ISSUE THREAD

**Issue by 1doL** [Just-Some-Bots/MusicBot#933]
What is that guys??The bot is not playing music when i'm texting but they play only from youtube??Any suggestions  ty..

**Comment by jayktaylor** [comment]
Can you screenshot the whole error and provide repro steps? Thanks.

**Comment by 1doL** [comment]
http://prntscr.com/e7r0b1  repro steps?  :D

**Comment by jayktaylor** [comment]
Try updating your dependencies. 

- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal
