### ISSUE TITLE
aiohttp

### ISSUE THREAD

**Issue by slickxz** [Just-Some-Bots/MusicBot#935]
When I put in the command python3 run.py it says no module named aiohttp then it tries to download some stuff and then when it stops there is red text at the end that says Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-p81i0l7x/PyNaCl/. What???? pls help

**Comment by ioandev** [comment]
install the dependencies that are in the documentation for ubuntu "14.04" only (just the apt-get, you don't have to add the repos) and it should work

**Comment by slickxz** [comment]
I have Ubuntu 16.04 LTS

**Comment by ioandev** [comment]
Yea, do it anyway.

**Comment by slickxz** [comment]
I don't know the command. Can you tell me please?

**Comment by ioandev** [comment]
see the installation guide for ubuntu 14.04

**Comment by slickxz** [comment]
I searched up "Ubuntu 14.04 installation guide". I found something but it wasn't.  pls help

**Comment by ioandev** [comment]
Run these:

```
sudo apt-get update -y
sudo apt-get install git python python3.5-dev ffmpeg libopus-dev libffi-dev libsodium-dev -y
sudo apt-get upgrade -y
```

**Comment by slickxz** [comment]
didn't work

**Comment by chuushi** [comment]
Did you do everything written in [this guide](https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Ubuntu)?  Your error may have something to do with missing packages.

**Comment by slickxz** [comment]
yeah I did

**Comment by slickxz** [comment]
wait i fixed it
now it's working thanks for the help though guys
(love you fam) lol
