### ISSUE TITLE
Autoplaylist repeating the same few songs

### ISSUE THREAD

**Issue by Synquix** [Just-Some-Bots/MusicBot#936]
For some reason, despite having over 550 songs in the autoplaylist, it seems to keep playing the same like 20ish songs. Is it just bad RNG or is there something else going on? Its fairly annoying but overall the bot is great. Any help would be appreciated!

**Comment by Selkea** [comment]
I had a similar issue and I never found out whether it was bad luck or something else at play. I chose to modify how the autoplaylist chooses it's songs to just make it play every song in order and then repeat because I wasn't a fan of the current implementation.

**Comment by jayktaylor** [comment]
#591 #613
