### ISSUE TITLE
DeprecationWarning: change_status is deprecated, use change_presence instead.   await self.change_status(game)

### ISSUE THREAD

**Issue by athen66** [Just-Some-Bots/MusicBot#939]
Getting this warning all of a sudden

**Comment by KingGold171** [comment]
deprecation: If you're getting a warning about deprecation, you can ignore it. Deprecation is something for the developers to deal with, not you. It won't impact the running of the bot. Learn more: https://en.wikipedia.org/wiki/Deprecation
