### ISSUE TITLE
Request music in PM 

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#941]
##please add a function that allows to request music in pm for userbots , they can stream only on one server

**Comment by siku2** [comment]
You could do it yourself:

- Open the **bot.py** file located in the **musicbot** subfolder with a text editor like [Atom](https://atom.io/) or [Notepad++](https://notepad-plus-plus.org/download)
- Delete lines 1836 to 1839
- Add the following lines right after the line 1835:
```python
        message.server = self.get_server("YOUR SERVER ID")
        message.channel = message.server.get_channel("YOUR CHANNEL ID")
```
- Replace "YOUR SERVER ID" with your server's id and "YOUR CHANNEL ID" with your channel's id.
[Click me if you don't know how to get an id](https://github.com/Just-Some-Bots/MusicBot/wiki/FAQ#how-do-i-get-an-id)

**That's it!**

Your code should look something like this:
![Snippet of code](https://cloud.githubusercontent.com/assets/16530283/23107480/436cc822-f6fe-11e6-8277-eccd3634aa7e.png)


Any questions? **siku2#7390** on [Discord](https://discordapp.com/)

**Comment by jayktaylor** [comment]
This won't happen as it seems like an un-necessary feature. Feel free to implement it in your own fork however, as @siku2 gives steps for above.
