### ISSUE TITLE
Bot instantly deletes the message when pinged

### ISSUE THREAD

**Issue by AlexZ014** [Just-Some-Bots/MusicBot#945]
If I write $help, the bot should display list of commands.

It does that, then it instantly deletes that message.

edit: It does this occasionally. Currently that issue isn't happening, but it happens randomly.

**Comment by siku2** [comment]
I assume there aren't any errors?
Have you done any kind of modification?

**Comment by jayktaylor** [comment]
Unless you've modified the bot, I don't see why this would be happening.

**Comment by AlexZ014** [comment]
There are no modifications done.

It happens rarely, so i'll tell you if it happens again
