### ISSUE TITLE
[Feature Request] Allow the use of default YouTube playlist URLs

### ISSUE THREAD

**Issue by OmenLW** [Just-Some-Bots/MusicBot#947]
Can you please automatically format URLs or allow the use of default playlist URLs?

Example: https://www.youtube.com/watch?v=JGwWNGJdvx8&list=PL55713C70BA91BD6E 
converts to 
https://www.youtube.com/playlist?list=PL55713C70BA91BD6E

**Comment by siku2** [comment]
Now what if someone actually wants to play that specific song from the playlist? I imagine that this won't be implemented for that exact reason but if you want this, you can do the modification yourself:

- open the **bot.py** file which is located in the _musicbot_ subfolder
- add `import re` at the top of the file
- goto line 857 (below `song_url = song_url.strip('<>')`)
- insert the following lines below it:

```python
        matches = re.search(r"watch\?v=.+&(list=.+)", song_url)
        groups = matches.groups() if matches is not None else []
        song_url = "https://www.youtube.com/playlist?" + groups[0] if len(groups) > 0 else song_url
```

If you try to play a link in the format you provided it'll automatically convert it to the playlist's url.

----------------

#### edit 14/03/2017
Thanks to @OmenLW I now know that youtube links can also contain non-word characters.

**Comment by OmenLW** [comment]
I suppose making this optional in the config would work for those who want this functionality.  Thank you for the code, it is working great.

**Comment by giovani3** [comment]
@siku2  Hi I am sorry but this is not working for me I did just like you said but its not working
I have to do it just like this right? http://prntscr.com/ef7hwp
Yes I have past the `import re` at beggin too

**Comment by siku2** [comment]
the code needs to be aligned with **line 856**. Just remove 4 spaces in front of the lines **857** to **859** and you should be fine.

**Comment by giovani3** [comment]
@siku2 hi like this right? http://prntscr.com/egu2jb  its not working :(

**Comment by OmenLW** [comment]
@siku2 It seems that if the playlist has any special characters, this format doesn't work and you have to resort to the original playlist?list=js8h6_wef-3 method. How would we get this to work with playlists containing special characters?

@giovani3 Here is what mine looks like: [http://i.imgur.com/LNNPyFJ.png](http://i.imgur.com/LNNPyFJ.png)

**Comment by siku2** [comment]
@OmenLW To be honest I didn't know that youtube playlists can have special characters in them...
I updated my solution for it to handle those too.

**Comment by OmenLW** [comment]
@siku2 Thank you for this modification. Much appreciated. I wish I knew regular expressions! One day.

**Comment by OmenLW** [comment]
@siku2 Any tips on how to get this working with the `review` version?  I am experiencing the same issues that others are having (bot not responding after a long period of inactivity) so I am trying out the suggested `review` build. There are now 2 sections containing `song_url = song_url.strip('<>')` and an error is thrown when using either or both.

`Exception in on_message
Traceback (most recent call last):
  File "E:\Discord\MusicBot\musicbot\bot.py", line 2472, in on_message
    response = await handler(**handler_kwargs)
  File "E:\Discord\MusicBot\musicbot\bot.py", line 1254, in cmd_play
    matches = re.search(r"watch\?v=.+&(list=.+)", song_url)
NameError: name 're' is not defined`

**Comment by siku2** [comment]
@OmenLW
I'll take a closer look at this later. In your case though, could it be that you forgot to add the 'import re' line?

**Comment by siku2** [comment]
I haven't come around to test it yet but here's the commit for the necessary changes:
e54fc3c565da05723985e9b95190f5b3d2f7fc68

Sadly I can't test this right now as my current connection doesn't allow the musicbot to start up but as soon as I'm home I'll update this accordingly.

**Comment by OmenLW** [comment]
@siku2 doh...yup, that was it. `import re` Thanks again!
