### ISSUE TITLE
Audio Problems

### ISSUE THREAD

**Issue by philwep** [Just-Some-Bots/MusicBot#948]
Everything runs properly, but the audio that's getting played is a little choppy?, is there any solution out there to fix this

**Comment by arunesh90** [comment]
most likely your internet or computer/server being slow.

**Comment by siku2** [comment]
Have you disabled the option **SaveVideo** inside the _config/_**options.ini** by any chance? If you have, try enabling it for once and check whether it helps.

If you haven't, your internet connection is probably too bad.
