### ISSUE TITLE
[Feature] Multiple Owners/Admins

### ISSUE THREAD

**Issue by JanB1** [Just-Some-Bots/MusicBot#95]
Change the owner variable from string to array to allow multiple owners so the bot is server proof.

**Comment by imayhaveborkedit** [comment]
The bot can only be in one voice chat at a time, so there's not really a point in trying to use it on multiple servers.  This will be resolved with command permissions anyways.

**Comment by JanB1** [comment]
Not multiple servers. One server, but multiple people that are able to moderate it/are able to use the owner-only commands.

Okay, in that case I'll close this again.
