### ISSUE TITLE
[Feature Request] Proper perms group for owner

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#952]
Can we add a way of retaining ownership while toggling some permissions such as InstaSkip? I' d like to vote to skip instead of being a dictator. I very often find myself not skipping at all since I feel its unfair.

**Comment by siku2** [comment]
### For the meantime if you'd like to implement this yourself, you can do the following:

[Here's](https://github.com/siku2/MusicBot-Request-Fulfillment/tree/no_owner_instaskip) the branch!
Here's the commit cc0962ed91ea74b94ac46217422e1af98cb17917

### If you'd rather do the edits yourself:
- Open the **bot.py** file located in the **musicbot** subfolder with a "modern" text editor like [Atom](https://atom.io/) or [Notepad++](https://notepad-plus-plus.org/)
- Goto line `1441` where it says:
```python
        if author.id == self.config.owner_id \
                or permissions.instaskip \
                or author == player.current_entry.meta.get('author', None):
```
- Remove this `author.id == self.config.owner_id \
                or ` so the code looks like this:
```python
        if permissions.instaskip \
                or author == player.current_entry.meta.get('author', None):
```

Now the only way someone can instaskip is if they either have the **permission** to or if **they added the song** to the queue in the first place.

**Comment by krishna1841999** [comment]
I m unable to give permission to other users of my server help me plzz they cant access commands plz help

**Comment by siku2** [comment]
@krishna1841999 I don't see how this is related to the problem @JewBearr issued, but have you ever read the [permissions wiki](https://github.com/Just-Some-Bots/MusicBot/wiki/Permissions)?

**Comment by TheerapakG** [comment]
#1740 should address this
