### ISSUE TITLE
Docker - document update

### ISSUE THREAD

**Issue by Okasgtr** [Just-Some-Bots/MusicBot#954]
Issue: The audio_cache folder is missing and not defined as part of the docker startup from the setup page, the following is defined.

   **docker run -d -v $(pwd)/config:/musicBot/config musicbot**

You need to create the audio_cache directory and change the startup command

One time only '**mkdir audio_cache**' in the musicbot root ( same directory as config and musicbot )

Update the run command to the following.

   **docker run -d -v $(pwd)/config:/musicBot/config -v $(pwd)/audio_cache:/musicBot/audio_cache musicbot**

**Comment by chuushi** [comment]
I believe maintenance for docker documentation is necessary as well. I had to give up on Docker and move back to using screen when using Docker didn't let me update the bot dependencies successfully.

**Comment by Okasgtr** [comment]
Going to further update this with some enhancements

Problem: the discord bot name is inconsistent in docker, so we're going to assign one, we are also going to clean up the container when we shut it down like a good app should

**docker run --rm -d --name musicbot1 -v $(pwd)/config:/musicBot/config -v $(pwd)/audio_cache:/musicBot/audio_cache musicbot**

We will also enhance the kill command to kill by name instead of any container it finds, especially important if you have multiple containers.

**docker kill $(docker ps -q -f name=musicbot1)**

Doing this will also allow you to run multiple bots from the same image without having to change any code utilizing named containers just by duplicating the config folder with a new name ( each docker container would then get its own name ) 

Working example ( which you could put in a startup script etc ) 

**docker run --rm -d --name musicbot1 -v $(pwd)/config:/musicBot/config -v $(pwd)/audio_cache:/musicBot/audio_cache musicbot**
**docker run --rm -d --name musicbot2 -v $(pwd)/config2:/musicBot/config -v $(pwd)/audio_cache:/musicBot/audio_cache musicbot**

**docker kill $(docker ps -q -f name=musicbot1)**
**docker kill $(docker ps -q -f name=musicbot2)**

**Comment by jayktaylor** [comment]
Our team personally don't utilise Docker which is why there is no maintained documentation for installing the bot using it. The docker image in the repo is maintained by someone else, but we haven't heard from him in a long time.

**Comment by stuntguy3000** [comment]
None of these commands work. :(

**Comment by Xylems** [comment]
So question, for whatever reason when i go to run the command for bot #2 bot #1 skips for a second and continues to play. Almost as if it tried to run as the same config file.. Why is that? These are the commands i sent in

docker run --rm -d --name bot1 -v $(pwd)/bot1:/musicBot/config -v $(pwd)/audio_cache:/musicBot/audio_cache musicbot

docker run --rm -d --name bot2 -v $(pwd)/bot2:/musicBot/config -v $(pwd)/audio_cache:/musicBot/audio_cache musicbot

One has a prefix of ! the other !! and when i run the second command the !! prefix doesnt work and if i do !queue it shows the queue and also says the bot is not in the channel... All of the proper files are in each location

**Comment by jayktaylor** [comment]
We no longer provide official setup steps for Docker as we haven't got anyone to maintain it. Building the image and running a container yourself may still certainly be possible, but you'll have to figure out how to do it.
