### ISSUE TITLE
Bot won't start up

### ISSUE THREAD

**Issue by Azsunyx** [Just-Some-Bots/MusicBot#956]
So I run update_deps.bat and get the following:

> Requirement already up-to-date: discord.py[voice]~=0.12.0 in c:\users\amanda\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 1))
> Requirement already up-to-date: youtube_dl in c:\users\amanda\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 2))
> Requirement already up-to-date: pip in c:\users\amanda\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 3))
> Requirement already up-to-date: cffi==1.6.0 in c:\users\amanda\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 4))
> Requirement already up-to-date: aiohttp<1.1.0,>=1.0.0 in c:\users\amanda\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
> Requirement already up-to-date: websockets<4.0,>=3.1 in c:\users\amanda\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
> Requirement already up-to-date: PyNaCl==1.0.1 in c:\users\amanda\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
> Requirement already up-to-date: pycparser in c:\users\amanda\appdata\local\programs\python\python35\lib\site-packages (from cffi==1.6.0->-r requirements.txt (line 4))
> Requirement already up-to-date: chardet in c:\users\amanda\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
> Requirement already up-to-date: multidict>=2.0 in c:\users\amanda\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
> Requirement already up-to-date: async_timeout in c:\users\amanda\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
> Requirement already up-to-date: six in c:\users\amanda\appdata\local\programs\python\python35\lib\site-packages (from PyNaCl==1.0.1->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
> 
> C:\Users\Amanda\MusicBot>

Then I try to run runbot.bat, and it hangs and never fully loads.  The bot account comes online in discord, but the cmd doesn't fully start up.
I've tried reinstalling both the bot, python, and Git Bash, which has not worked.

It gets this far into loading and then hangs:

> Microsoft Windows [Version 10.0.14393]
> (c) 2016 Microsoft Corporation. All rights reserved.
> 
> C:\Users\Amanda\MusicBot>python run.py
> Connected!  Musicbot v1.9.5_2
> 
> Bot:   257208623313321985/Music#8814
> Owner: 109806754157559808/Azsunyx#9267
> 
> Server List:
>  - zsazouli tavern
>  - Holy Crit
>  - Execute
> 
> Bound to text channels:
>  - Holy Crit/music-bot
>  - zsazouli tavern/music-bot
>  - Execute/bot
> 
> Not autojoining any voice channels
> 
> Options:
>   Command prefix: #
>   Default volume: 10%
>   Skip threshold: 2 votes or 50%
>   Now Playing @mentions: Enabled
>   Auto-Summon: Disabled
>   Auto-Playlist: Enabled
>   Auto-Pause: Disabled
>   Delete Messages: Enabled
>     Delete Invoking: Disabled
>   Debug Mode: Disabled
>   Downloaded songs will be deleted

**Comment by siku2** [comment]
Could you please try the following:

- Open **lazy_cmd.bat** in the MusicBot folder
- Run the command `pip uninstall -r requirements.txt` and everytime you're prompted with the question whether you want to proceed, answer with `y`
- Run the **run.bat** file as administrator and wait

**Comment by arunesh90** [comment]
What do you exactly mean with "the cmd doesn't fully start up."?

**Comment by Azsunyx** [comment]
arunesh90, I mean in the cmd window when I run the run.bat file, the bot doesn't fully start up

siku2, I get the following error when I try to uninstall:

> Microsoft Windows [Version 10.0.14393]
> (c) 2016 Microsoft Corporation. All rights reserved.
> 
> C:\Users\Amanda\MusicBot>pip uninstall -r requirements.txt
> Cannot uninstall requirement discord.py, not installed
> 
> C:\Users\Amanda\MusicBot>

So I installed it via the following, and then tried to run your command to uninstall (I tried opening runbot.bat in between each change, and the startup was still hanging in the same place):

> C:\Users\Amanda\MusicBot>python -m pip install -U discord.py[voice]
> Collecting discord.py[voice]
>   Downloading discord.py-0.16.6.tar.gz (409kB)
>     100% |################################| 409kB 1.4MB/s
> Collecting aiohttp<1.1.0,>=1.0.0 (from discord.py[voice])
>   Downloading aiohttp-1.0.5-cp35-cp35m-win32.whl (132kB)
>     100% |################################| 133kB 1.8MB/s
> Collecting websockets<4.0,>=3.1 (from discord.py[voice])
>   Using cached websockets-3.2-py33.py34.py35-none-any.whl
> Collecting PyNaCl==1.0.1 (from discord.py[voice])
>   Downloading PyNaCl-1.0.1-cp35-none-win32.whl (103kB)
>     100% |################################| 112kB 2.2MB/s
> Collecting multidict>=2.0 (from aiohttp<1.1.0,>=1.0.0->discord.py[voice])
>   Downloading multidict-2.1.4-cp35-cp35m-win32.whl (132kB)
>     100% |################################| 133kB 1.8MB/s
> Collecting chardet (from aiohttp<1.1.0,>=1.0.0->discord.py[voice])
>   Downloading chardet-2.3.0-py2.py3-none-any.whl (180kB)
>     100% |################################| 184kB 1.8MB/s
> Collecting async-timeout (from aiohttp<1.1.0,>=1.0.0->discord.py[voice])
>   Using cached async_timeout-1.1.0-py3-none-any.whl
> Collecting six (from PyNaCl==1.0.1->discord.py[voice])
>   Using cached six-1.10.0-py2.py3-none-any.whl
> Collecting cffi>=1.1.0 (from PyNaCl==1.0.1->discord.py[voice])
>   Downloading cffi-1.9.1-cp35-cp35m-win32.whl (146kB)
>     100% |################################| 153kB 2.3MB/s
> Collecting pycparser (from cffi>=1.1.0->PyNaCl==1.0.1->discord.py[voice])
>   Using cached pycparser-2.17.tar.gz
> Installing collected packages: multidict, chardet, async-timeout, aiohttp, websockets, six, pycparser, cffi, PyNaCl, discord.py
>   Running setup.py install for pycparser ... done
>   Running setup.py install for discord.py ... done
> Successfully installed PyNaCl-1.0.1 aiohttp-1.0.5 async-timeout-1.1.0 cffi-1.9.1 chardet-2.3.0 discord.py-0.16.6 multidict-2.1.4 pycparser-2.17 six-1.10.0 websockets-3.2
> 
> C:\Users\Amanda\MusicBot>pip uninstall -r requirements.txt
> Uninstalling discord.py-0.16.6:
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord.py-0.16.6-py3.5.egg-info
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__init__.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\__init__.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\calls.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\channel.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\client.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\colour.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\compat.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\embeds.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\emoji.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\enums.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\errors.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\game.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\gateway.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\http.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\invite.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\iterators.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\member.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\message.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\mixins.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\object.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\opus.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\permissions.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\reaction.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\role.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\server.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\state.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\user.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\utils.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\__pycache__\voice_client.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\bin\libopus-0.x64.dll
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\bin\libopus-0.x86.dll
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\calls.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\channel.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\client.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\colour.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\compat.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\embeds.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\emoji.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\enums.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\errors.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\__init__.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\__pycache__\__init__.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\__init__.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\__pycache__\__init__.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\__pycache__\bot.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\__pycache__\context.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\__pycache__\converter.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\__pycache__\cooldowns.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\__pycache__\core.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\__pycache__\errors.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\__pycache__\formatter.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\__pycache__\view.cpython-35.pyc
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\bot.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\context.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\converter.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\cooldowns.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\core.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\errors.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\formatter.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\ext\commands\view.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\game.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\gateway.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\http.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\invite.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\iterators.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\member.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\message.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\mixins.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\object.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\opus.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\permissions.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\reaction.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\role.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\server.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\state.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\user.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\utils.py
>   c:\users\amanda\appdata\local\programs\python\python35-32\lib\site-packages\discord\voice_client.py
> Proceed (y/n)? y
>   Successfully uninstalled discord.py-0.16.6
> **Cannot uninstall requirement youtube-dl, not installed**
> 
> C:\Users\Amanda\MusicBot>

**Comment by siku2** [comment]
Well that's interesting...
Try running **update_deps.bat** once more and make sure to **run it as administrator**

Once you've done that open any command window (for example by double clicking the **lazy_cmd.bat**) and run `pip freeze`. Once you've done that please pass along the results (screenshot or just copy paste).

**Comment by Azsunyx** [comment]
Here are the results:

> Microsoft Windows [Version 10.0.14393]
> (c) 2016 Microsoft Corporation. All rights reserved.
> 
> C:\Users\Amanda\MusicBot>pip freeze
> aiohttp==1.0.5
> async-timeout==1.1.0
> cffi==1.6.0
> chardet==2.3.0
> discord.py==0.12.0
> multidict==2.1.4
> pycparser==2.17
> PyNaCl==1.0.1
> six==1.10.0
> websockets==3.2
> youtube-dl==2017.2.22
> 
> C:\Users\Amanda\MusicBot>

**Comment by siku2** [comment]
Just to clarify... You've actually tried to use the bot before?
As in:
1. giving him the necessary permissions
2. joining a voice channel to which he has access to
3. using `!summon` to get him to join your channel

According to the log the bot starts up just fine. You didn't define any "autojoin" channels so of course he wouldn't join one randomly... I haven't spotted anything that could hinder him from doing his purpose.

**Comment by Azsunyx** [comment]
Yes, the bot was working fine last week, these problems started around sunday

**Comment by Azsunyx** [comment]
So, I finally got it working again, I reinstalled youtube-dl and discord.py[voice] then I ran update_deps.bat again, and it started right up this time.  Thank you for your help!
