### ISSUE TITLE
How do I setup up the bot on digitalocean? 

### ISSUE THREAD

**Issue by moody420** [Just-Some-Bots/MusicBot#957]
I have Ubuntu 16.04.2 x64 droplet on DigitalOcean and I've set up the server using this guide: https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-16-04?comment=56291 

What should I do next to get the bot running on it?

**Comment by chuushi** [comment]
_**Check the [Readme](https://github.com/Just-Some-Bots/MusicBot) or the [wiki](https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Ubuntu) first. All information is laid out for everyone.**_
