### ISSUE TITLE
Bot is using /tts ?

### ISSUE THREAD

**Issue by powerd062** [Just-Some-Bots/MusicBot#958]
This is annyoing me. i'm not sure if it is the bot or discord but it keeps saying the things it types how do i stop it for example it uses tts to say stuff like "Now Playing bla bla bla" .How do i stop it

**Comment by siku2** [comment]
You can do the following:
- Open the **bot.py** file inside the **musicbot** subfolder with a modern text editor like [Atom](https://atom.io/) or [Notepad++](https://notepad-plus-plus.org/download/)
- Scroll down to the line **473** which says:
```python
 msg = await self.send_message(dest, content, tts=tts)
```
- Replace the part where it says `tts=tts` to `tts=False` so the line says:
```python
msg = await self.send_message(dest, content, tts=False)
```

This will ensure that the musicbot doesn't use tts.

You could also **disable** the tts option in your [Discord settings](https://support.discordapp.com/hc/en-us/articles/208613137-How-can-I-disable-Text-To-Speech-) or disable the *send tts messages* permission.

**Comment by powerd062** [comment]
Thank you so much!!!

**Comment by TheYoungLoris** [comment]
fot js?

**Comment by TheYoungLoris** [comment]
for js?
