### ISSUE TITLE
Runtime error (mac)

### ISSUE THREAD

**Issue by Tsundubu** [Just-Some-Bots/MusicBot#961]
when I run "runbot_mac.command" i get this 
```
  File "/Users/student/Desktop/MusicBot/musicbot/opus_loader.py", line 17, in load_opus_lib

    raise RuntimeError('Could not load an opus lib. Tried %s' % (', '.join(opus_libs)))

 RuntimeError: Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib
logout
```

running Sierra 10.12.1

**Comment by lkraack** [comment]
I had this same issue but I just figured it out. Did you install Homebrew first?

**Comment by lkraack** [comment]
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Run this in terminal. I started over all the way from the beginning and now my bot is up and running!

**Comment by Tsundubu** [comment]
I installed it and it doesn't seem to have fixed anything.

Do you need to run anything else after? I'm still getting the same error message.

**Comment by jayktaylor** [comment]
Looks like you're missing opus which should be installed using `brew install opus`.

**Comment by IKalman** [comment]
http://macappstore.org/opus/ this is what i did and it worked
