### ISSUE TITLE
PVPCraft Music bot offline

### ISSUE THREAD

**Issue by tylerbusching** [Just-Some-Bots/MusicBot#965]
The music bot was working fine just a few hours ago, I tried kicking it and adding it multiple times, I can't find out how to make it online.

**Comment by junhui-f** [comment]
How is this related?

**Comment by itslukej** [comment]
Steps to reproduce:
1. Fill a large pot 2/3 of the way with water. Add some salt, if desired.
2. Bring the water to a boil over high heat.
3. Add the pasta and stir.
4. Reduce to medium or meduim-high.
5. Cook for 8 to 10 minutes.
6. Pour the pasta through a strainer. Shake out the excess water.
7. Return the pasta to the pot and toss it with your favorite sauce.

**Comment by macdja38** [comment]
@TylerTCBB in the future please report issues to one of the maintainers of pvpcraft... so pretty much me...
