### ISSUE TITLE
Randomly removing links from auto playlist

### ISSUE THREAD

**Issue by mari-arondeus** [Just-Some-Bots/MusicBot#967]
For some reason every time I check the auto playlist it's missing about 100 songs. Is this a bug or a poorly implemented song cap? Any help would be appreciated :)

you can see there are 321 lines of links in the auto playlist 
![capture2](https://cloud.githubusercontent.com/assets/15707989/23334794/446a059e-fb74-11e6-9f96-3e188fd340cb.PNG)

but a couple days later I check on it and it loses almost 100 links?
![capture](https://cloud.githubusercontent.com/assets/15707989/23334795/46417d52-fb74-11e6-805a-46b78344f1a2.PNG)

**Comment by arunesh90** [comment]
If you check the console, you can see why it has removed those links.

**Comment by mari-arondeus** [comment]
Does it log the console output anywhere? I frequently restart the bot so there's usually a fairly empty console.

**Comment by mari-arondeus** [comment]
Ahhhhh I see it says "removed unplayable song from playlist." It was a song from a Disney movie so could it be a copyright issue keeping it from downloading it? I tried downloading it from a youtube to mp3 site and it wouldn't so that's probably it...

**Comment by arunesh90** [comment]
Yeah, that's it then.
