### ISSUE TITLE
Uncomplete File

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#968]
This is very odd. Whenever I attempt to install the folder itself, it saves as "28.2" instead of "29.5". I've had this issue before, eventually I actually got a hold of the complete folder once, which I had no knowledge of how I did that. Whenever I insert the information in the options and permission (which example_options[.ini] is missing), I always get the error message that I did not input an Owners ID. I'm running off a Macbook currently in Windows which was done through Bootcamp, and I do not have the full version of Windows (no product key). Not sure if anyone has had this problem before.

**Comment by jayktaylor** [comment]
Not entirely sure what your issue is here, but if you're still having it (I know this issue is old), ask for help in http://discord.gg/bots.
