### ISSUE TITLE
Bot cannot login, bad credentials

### ISSUE THREAD

**Issue by rowan-smith** [Just-Some-Bots/MusicBot#969]
Connecting...
An error has occured:

  Problem:  Bot cannot login, bad credentials.
  Solution: Fix your Email or Password or Token in the options file.  Remember
            that each field should be on their own line.

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5acdf72f28>

Credentials are correct, have tried logging in through web-based and has worked. 
Using Ubuntu on a VPS, I haven't tried token as that isn't what I am looking for, it also works fine with the credentials on localhost. Any Idea's?

**Comment by Zenrac** [comment]
Be care about put an ; at the beggining of the line if you don't use the token

**Comment by rowan-smith** [comment]
I already did that, it's confusing, works with a token off the VPS but not Email/Password.

However, as stated. Works fine with both from localhost.

**Comment by Thunder33345** [comment]
i actually experienced this before
discord have some sort of protection when you try to login from a new location
check the bot's email
if not you may just have to set up VPN on your vps to get discord to recognize it

**Comment by paradox8599** [comment]
I have the same problem as yours. 
I have tried on Ubuntu, Fedora, raspbian, debian and it always comes with the error.
I am trying to use a Token by the way.
Normal account works fine.

**Comment by rowan-smith** [comment]
Ah, I forgot about the protection. That would probally explain what was happening. I just converted the account into a bot. That worked. So yeah. :)
