### ISSUE TITLE
[Feature request] !report command

### ISSUE THREAD

**Issue by JanB1** [Just-Some-Bots/MusicBot#97]
Command !report to report spammers and trolls. You can set the maximum amount of reports and the lifetime of a report in the config file. 
If the maximum amount of reports is reached for a person, the person get's blacklisted.
If the lifetime of a report is over, the report get's removed again.

(Maaaybe you have to work with a database or text file for this one.)

**Comment by imayhaveborkedit** [comment]
Eh... no.
