### ISSUE TITLE
Permissions Problems

### ISSUE THREAD

**Issue by elyafk** [Just-Some-Bots/MusicBot#971]
I've tried making a custom group, which should have worked just fine seeing as how I copied settings from the premade groups. Even when trying to add someones ID and give them InstaSkip it wouldn't work no matter what I tried. Please help because I don't know what I'm doing wrong.

**Comment by elyafk** [comment]
Is it also possible to add a second owner to the bot? I feel like this would be easier than trying to make the IDs work.

**Comment by jayktaylor** [comment]
Our permissions documentation is here: https://github.com/Just-Some-Bots/MusicBot/wiki/Permissions

To simulate having multiple owners, we suggest adding users to the `MusicMaster` group.
