### ISSUE TITLE
"no module named discord" - Running python run command for install

### ISSUE THREAD

**Issue by Akoni88** [Just-Some-Bots/MusicBot#972]
"No module named Discord
attempting to install dependencies."

Also the python version I had installed was "3.6.0".

![errormusicbot](https://cloud.githubusercontent.com/assets/26070822/23376758/5b5dfbb0-fcfb-11e6-83f2-614fdaf7c55a.jpg)

Followed steps in this youtube video to install it. (https://www.youtube.com/watch?v=A6bY7P8FaZA)

However my bot will not come online, and i'm assuming when I click "Run" (Python file) the not finding discord app is causing the issue. It shows the bot as an offline contact though....

There is a 'runbot' BAT file but in the youtube video there was no instructrions on any command that was needed to get the bot up and running. A bit lost (Sorry pretty new to this)

![installedfoldermusicbot](https://cloud.githubusercontent.com/assets/26070822/23376844/a48ba0da-fcfb-11e6-9495-fd90a90e691a.jpg)

This is what I have currently installed in my folder, I had copied the options file in config and renamed it "options.ini" and edited it with Notepad++ like the video stated as well.

**Comment by Zenrac** [comment]
run as an administrator the update_deps.
If it didn't work, use pip install discord.py in the terminal

**Comment by junhui-f** [comment]
https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Windows

Try this

**Comment by jayktaylor** [comment]
Please install the bot using our official guides. The YouTube video you linked is not by us and is incorrect in places. Thanks.
