### ISSUE TITLE
chcp doesnt recognize internal or external comand 

### ISSUE THREAD

**Issue by arkanlems** [Just-Some-Bots/MusicBot#973]
i dont understand this problem, when i try to start the bot with lazy_cmd in admin mode its says 
"CHCP" dont recognize as a internal or external comand
program or file by lots executable 
dont expect  =ValueValue in this moment

P.D: sorry for the traduction

**Comment by arunesh90** [comment]
In the runbot.bat file, delete the highlighted text as shown below. 
![image](https://cloud.githubusercontent.com/assets/5787588/23519940/1606299a-ff79-11e6-938b-b0e8cf6c8c33.png)
