### ISSUE TITLE
Bot wont play more than 2 songs

### ISSUE THREAD

**Issue by pshyco69** [Just-Some-Bots/MusicBot#974]
So yeah as i said if i write !play and add more than 2 songs links it will play only the first one and will ignore the last one. When i just installed the bot it worked but when i restarted pc it fucked up :(.
Help please.

**Comment by tehknox** [comment]
I had the same problem, and some other, and updated the dependencies to fix all of those. Seems like the a new version of youtube_dl (as of 2017.02.28), fixed all my problems. Worth a try.

**Comment by jayktaylor** [comment]
Try updating your dependencies:

- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal
