### ISSUE TITLE
can't run "update_deps"

### ISSUE THREAD

**Issue by SoginoBro** [Just-Some-Bots/MusicBot#975]
Every single time I try to run this it opens up and 3 seconds or less it closes right away

**Comment by jayktaylor** [comment]
Can you try opening `lazy_cmd.bat` instead and typing `pip install --upgrade -r requirements.txt`?

(Edit: Accidental close, sorry).

**Comment by SoginoBro** [comment]
Papa bless thank you so much!

**Comment by jayktaylor** [comment]
No problem.
