### ISSUE TITLE
Possible to remove songs individually?

### ISSUE THREAD

**Issue by No-Death** [Just-Some-Bots/MusicBot#978]
Hi! I was just wondering if there is a command to remove like the 5th song in a queue? And if not, is it something that could be added? :)

**Comment by siku2** [comment]
Take a look at [this](https://github.com/Just-Some-Bots/MusicBot/pull/486)
#486

**Comment by No-Death** [comment]
I have no Idea how that work lmao :joy:

**Comment by siku2** [comment]
Go to [this link](https://github.com/Artanys/MusicBot) and download the musicbot from there. When you've done that you should have a `!remove` function

**Comment by jayktaylor** [comment]
We do not provide support for modifying the bot beyond what is written on this page: https://github.com/Just-Some-Bots/MusicBot/wiki/Modification. A feature request already exists here: #91
