### ISSUE TITLE
Musicbot is giving all users instaskip. [review]

### ISSUE THREAD

**Issue by wellivea1** [Just-Some-Bots/MusicBot#979]
Musicbot immediately skips a song no matter who it is, with only one person, even though I have disabled that in the permissions for everybody except MusicMaster (which I only give to channel owner). Here's the stated options:
Options:
  Command prefix: !
  Default volume: 50%
  Skip threshold: 2 votes or 50%
  Now Playing @mentions: Enabled
  Auto-Summon: Disabled
  Auto-Playlist: Enabled
  Auto-Pause: Enabled
  Delete Messages: Enabled
    Delete Invoking: Disabled
  Debug Mode: Disabled
  Downloaded songs will be deleted
Just one person, who should have the default permissions can skip a song without a vote. This is incredibly annoying, since it tends to get abused.
### More info:
[Default]
CommandWhitelist = play perms queue np skip search id help clean
 CommandBlacklist = restart shutdown
IgnoreNonVoice = play skip search
MaxSongLength = 1200
MaxSongs = 6
AllowPlaylists = no
; MaxPlaylistLength = 20
InstaSkip = no

**Comment by EndenDragon** [comment]
Look at this line:
`Skip threshold: 2 votes or 50%`
It allows the user to skip with either 2 !skip votes or that 50% of the users in the voice channel has used !skip command, whichever comes first. Just set that to something high/impossible and you will be fine.

Though the real question is: Why wouldn't you want the person to not skip the song when he is the only one using the bot? I mean the user can just listen to youtube instead, where he has the freedom to skip the song...

**Comment by chuushi** [comment]
https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_options.ini#L68

Please recheck this option in your configuration.  1 vote when alone is 100%, which is above 50% (or 0.5) threshold.

I don't see any reason to be incredibly annoyed about a single person in a voice channel skipping songs they don't like.  If anything, you can create a new permissions group that disallows `skip` command, remove `skip` from default permission group, or  sit around/afk in the music channel.

**Comment by wellivea1** [comment]
I am fully aware of how the settings work. I am saying that when there is a group of, say 3 people, the bot allows any user to skip the song playing without a vote.

**Comment by wellivea1** [comment]
I can give an invite to one of the servers it is on to demonstrate if you can't replicate the issue.

**Comment by wellivea1** [comment]
https://discord.gg/TjwZcfT

**Comment by dshoreman** [comment]
@wellivea1 If one of the 3 is the owner and it's set to 50%, any vote will still count; the owner is ignored. If there are more people and you still have issues, you could try the ratio fix in PR #1012 

If you want the owner to be included in the count when it calculates the skip ratio, edit [musicbot/bot.py#L1432](https://github.com/Just-Some-Bots/MusicBot/blob/109fac5b31cc13f28168ca042b662ebbdcf4de27/musicbot/bot.py#L1432) to remove `self.config.owner_id, `.

**Comment by jayktaylor** [comment]
#1012 was merged.
