### ISSUE TITLE
[Review] YouTube streaming

### ISSUE THREAD

**Issue by amit177** [Just-Some-Bots/MusicBot#980]
When using the review branch with youtube stream it spams
The TLS connection was non-properly terminated.
in console, and it laggs

**Comment by Zenrac** [comment]
same here

**Comment by AmiT177** [comment]
bump

**Comment by AmiT177** [comment]
bump

**Comment by amit177** [comment]
bump

**Comment by MarcStocker** [comment]
Same issue with Youtube Live Streams. While downloading the link the following error pops up for me.
[tls @ 0581a660] The TLS connection was non-properly terminated.ate= 818.1kbits/s speed=6.41x

Would love some advice for how to fix this.

**Comment by TomLongAshfords** [comment]
I also get this spam (every 5 seconds) but it only seems to lag intermittently, not each time the message comes up.

**Comment by MarcStocker** [comment]
Mine will not play the selected stream at all. 
As soon as the download begins, I get the message every 2-5 seconds. Once the "Song" (Live Stream) starts playing, the program stops responding to commands (from what I've experienced) and stops streaming any kind of audio. I'm forced to shutdown the program and restart it. 

Edit: Clarification

**Comment by amit177** [comment]
My problem is same as duke,
every 5 seconds there is a spam, and the bot is lagging.

**Comment by Zenrac** [comment]
not fixed :(

**Comment by AmiT177** [comment]
bump

**Comment by junhui-f** [comment]
Quite sure streaming is part of the review branch and its not even part of the "command list" yet so I wouldn't expect any support until they finish the bot rewrite.

**Comment by rafaelwastaken** [comment]
Just wanted to say that streaming works perfectly fine for me. I read somewhere that apparently YouTube doesn't properly TLS connections so this is probably to be expected.

If you wanna get rid of these messages, compile ffmpeg with OpenSSL, since it appears that only gnuTLS is vocal about this.
