### ISSUE TITLE
[Feature] Blacklisting by keyword

### ISSUE THREAD

**Issue by Butterwhales** [Just-Some-Bots/MusicBot#985]
For me at least this would be very helpfull because my friends like to play ear rape videos on the bot. So i would like to blacklist the word.

**Comment by Zenrac** [comment]
juste after on_message add something like this
```
        if 'BANNEDWORD' in message:
            await self.safe_delete_message(message, quiet=True) #remove this if you don't want to delete the message
            return
```

**Comment by jayktaylor** [comment]
Duplicate of: #520 
Related: #249 #796
