### ISSUE TITLE
[Bug] Help Command is using incorrect (old?) link to command list.

### ISSUE THREAD

**Issue by FerusGrim** [Just-Some-Bots/MusicBot#987]
The correct link is [here](https://github.com/Just-Some-Bots/MusicBot/wiki/Commands), but when you type !help, it appears as though the Bot is spitting out an invalid link. Or, perhaps, an older link that used to be valid.

![Output](http://i.imgur.com/IM9iXi4.png)

This issue is occurring on the latest master commit (3519ee8).

**Comment by chuushi** [comment]
https://github.com/Just-Some-Bots/MusicBot/blob/review/musicbot/bot.py#L1153
Looks like the link is hard-coded. Update would be cool.

Edit: I have a feeling the same link is also in other files, but I have yet to find the rest.

**Comment by jayktaylor** [comment]
It's an old link that we've yet to update in the bot code. We'll get around to this eventually.

**Comment by Argos-Rho** [comment]
@jaydenkieran is it hard-coded? Could there be any way to add your own commands or change the commad name?  It's not fun having outdated commands as well as incorrect prefixes with the help for people on my server.

**Comment by chuushi** [comment]
It'd be great if all kind of messages were variable-based into separate files, especially to make localization and language/message customization easier.

**Comment by jayktaylor** [comment]
Information about localization is here: #255

**Comment by dshoreman** [comment]
@Argos-Rho Search `musicbot/bot.py` for cmd_help and you can change the text and URL to whatever you need.

#850 and #646 both attempted to fix the `!help` link, but one was posted to the wrong branch and the other references the old repo

**Comment by jayktaylor** [comment]
Fixed in https://github.com/Just-Some-Bots/MusicBot/commit/949a4b608973d0aaafd18c7c7b9e0149b36516a6.
