### ISSUE TITLE
Permissions problems

### ISSUE THREAD

**Issue by MoonGlow07** [Just-Some-Bots/MusicBot#988]
[Default]
CommandWhitelist = play perms queue np search id help clean
; CommandBlacklist = skip
IgnoreNonVoice = play search
; GrantToRoles =
; UserList =
MaxSongLength = 3600
MaxSongs = 0
AllowPlaylists = yes
; MaxPlaylistLength = 20
InstaSkip = no

; This group has full permissions.
[MusicMaster]
; GrantToRoles =
; UserList = 239445322223452170
MaxSongLength = 0
MaxSongs = 0
MaxPlaylistLength = 0
AllowPlaylists = yes
InstaSkip = yes

; This group can't use the blacklist and listids commands, but otherwise has full permissions.
-------------------------------------------------------------------------------------------------------------------
![46](https://cloud.githubusercontent.com/assets/26281363/23712395/77cbdb82-042b-11e7-9266-da73451ed458.png)
Please I need resolve for it, id is true, but my friend can't skip music!

**Comment by jayktaylor** [comment]
You need to add `skip` to the command whitelist of your default group.
https://github.com/Just-Some-Bots/MusicBot/wiki/Permissions
