### ISSUE TITLE
update_deps.bat is not working

### ISSUE THREAD

**Issue by Bravewave** [Just-Some-Bots/MusicBot#989]
Upon trying to run `update_deps.bat`, the command prompt opens and closes too quickly for me to see anything other than a "... is not recognized" error.

I saw a workaround #975  which is to open `lazy_cmd.bat` and instead type `pip install --upgrade -r requirements.txt`. However, when I try to run this - I get the following error in red text:

`    ----------------------------------------
  Rolling back uninstall of cffi
Command "c:\users\user1\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\User1\\AppData\\Local\\Temp\\pip-build-unbkjxzw\\cffi\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\User1\AppData\Local\Temp\pip-196eg1bb-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\User1\AppData\Local\Temp\pip-build-unbkjxzw\cffi\`

I can provide a full log if needed. Any help with this would be greatly appreciated.

**Comment by jayktaylor** [comment]
Can you provide the full log? Thanks!

**Comment by Bravewave** [comment]
Sure. I've provided a link to it below. User1 is the user I am currently using on my PC. Again, many thanks!

http://pastebin.com/BLhsaees

**Comment by Bravewave** [comment]
I'm assuming it has something to do with the fact that I haven't got the `cl.exe` file/directory...

**Comment by jayktaylor** [comment]
http://landinghub.visualstudio.com/visual-cpp-build-tools Try installing this and running the command again, it looks like you don't have a C compiler on your system.

**Comment by Bravewave** [comment]
I tried and the command still failed. I do have a C compiler on my system (I actually have Visual Studio too) - I program in C# frequently.

**Comment by justinokirk** [comment]
Remember when you are building console apps with VS you need to run the environment batch file for the build target in the shell which is executing the compile job.  For most python/ruby/etc package build+install that needs to be an elevated shell and if you run the operation from an non-Administrator shell it will spawn a subshell requesting Administrator role.  So run an Administrator shell first, then run the batch file, then the build+install operation

For VS 2017:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat
or 
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat

should do the trick.

All this assumes you have already installed VC + cli options from the VS installer.

**Comment by Bravewave** [comment]
Hello @justinokirk thanks for your reply. These files do not exist in those directories, instead they are in `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64`. I'm trying to run these files but it does nothing. Could you expand upon the VC + cli options? And what do you mean by an elevated shell?

**UPDATE:** I tried to run it in an admin cmd and it came up with the following error: `ERROR: Cannot determine the location of the VS Common Tools folder.`

**Comment by amit177** [comment]
If this is still an issue in the latest version, please open a new issue.
