### ISSUE TITLE
Guide for installing on linux tells user to use SFTP to modify configuration

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#99]
Just use ssh and a text editor

**Comment by imayhaveborkedit** [comment]
Yeah I don't really review wiki stuff that much.  I'll rewrite them as part of this update, but they're made mostly by other people.

**Comment by deansheather** [comment]
@lecomonad It's done, though... there is a screenshot guide on how to update files using Cyberduck using SSH on the Wiki. Check the Ubuntu 14.04 install guide bot configuration section: https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Ubuntu-14.04-and-other-versions#6b-change-configuration-file
