### ISSUE TITLE
Bot not staying online when CMD is closed

### ISSUE THREAD

**Issue by BrandonGamesYT** [Just-Some-Bots/MusicBot#990]
How do you keep the bot to stay on the discord even with the cmd closed?

**Comment by KingGold171** [comment]
A) Never close the console
B) Rent a VPS

If you don't know what a VPS is or don't have money to buy one, then stick with option A.

Closing CMD = Bot not running

**Comment by thesawolf** [comment]
You don't. the batch file needs to be actively running to keep your bot on and running.

**Comment by BrandonGamesYT** [comment]
Alright thank you
