### ISSUE TITLE
Error when playing SoundCloud links

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#991]
As of recently, attempting to play a SoundCloud link prints the following error in the console:

`ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>)
<class 'musicbot.exceptions.CommandError'>: ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>)
`

This error is repeatable with every known-good link I have tried.

**Comment by jayktaylor** [comment]
You just need to update your dependencies.

- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal
