### ISSUE TITLE
Music stops when i close the runbot.bat file

### ISSUE THREAD

**Issue by MinesomeMC** [Just-Some-Bots/MusicBot#992]
This is really annoying when I want it to keep running when im away, but it closes so the music stops playing.... If there is a fix i would like to know!

**Comment by KingGold171** [comment]
#990

**Comment by KingGold171** [comment]
What did you expect  if the runbot.bat gives you the bots console, closing it will naturally kill the bot.

Thats how all applications and softwares work.


Kinda like a phone call,  if you hang up you don't sit there and keep talking.

**Comment by MinesomeMC** [comment]
Thank you!
