### ISSUE TITLE
Problem at first start/ starting the bot

### ISSUE THREAD

**Issue by LuBlaBo** [Just-Some-Bots/MusicBot#996]
Hey guys,

my englisch is not as well but I still have a problem that prevents the start of the server.
As OS i use Linux Server 16.xx LTS.
I´m trying to run the Server via the run.py/ .sh and the script stopps everytime at the same point.

This is copied out of my putty session: "Attempting to install dependencies..."
After this message in the cmd the script dies and i´m now at the startpoint...
![screenshot 1](https://cloud.githubusercontent.com/assets/25789316/23805066/bdfeb9d4-05bc-11e7-9f44-96c7d36f0930.png)

I dont know if i done something wrong or else, but i know that this Server works fine at my Windows 10 PC with Python...

Thank you for any kind of help ;)

~ LuBlaBo aka Lukas ^^

**Comment by jayktaylor** [comment]
https://github.com/Just-Some-Bots/MusicBot/wiki please follow the guides properly to install the bot
